### ISSUE TITLE
[suggestion] For RxJava2

### ISSUE THREAD

**Issue by ZeroBrain** [realm/realm-java#4175] opened 2017-02-12 08:45 UTC
these day RxJava2 has released, still Realm support RxJava1

I tried to change it to RxJava2. but Realm has some issues for legacy code.
for it, I think Realm should change many codes of relation of RxJava.

so I suggest how to change it.
my suggestion is like Retrofit2's style.

Retrofit2 has `CallAdapterFactory`.
`CallAdapter` implements `return value` by users as third party developers.

If users wanna return values as raw-instances, then users don't need to register CallAdapter.
but if they want to return `Observable` as RxJava1, users should register RxJava1CallAdapter.
for `Observable` as RxJava2, just add RxJava2CallAdapter.

it means users can get many return types. not only RxJava1 but RxJava2, Reactive Stream, etc...

for understanding, reference : https://github.com/square/retrofit/wiki/Call-Adapters

**Comment by Zhuinden** [comment] 2017-02-12 09:59
Considering Retrofit has the luxury of generating a a dynamic proxy at runtime which actually uses the configuration provided as `AdapterFactory`, I don't see how the API would look like with the Realm instance that directly returns a `RealmResults`. 

I do not see where `AdapterFactory` fits in.

**Comment by Zhuinden** [comment] 2017-02-12 10:00
BTW, duplicate of https://github.com/realm/realm-java/issues/3497

**Comment by ZeroBrain** [comment] 2017-02-12 11:00
alright, I will follow up #3497.

**Closed** 2017-02-12 11:01 UTC
