### ISSUE TITLE
 io.realm.internal.Table.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by tebica** [realm/realm-java#1599] opened 2015-10-15 04:56 UTC
Issur for Kakao Hello
io.realm.internal.Table.finalize() timed out after 10 seconds
 - Number 1 frequent issue on crash report
 - No route to reproduce
 - Galaxy S6, Galaxy S6 Edge, Galaxy S6 Edge+
 - OS version 5.1.1
 - reported by  @jungilhan
```
java.util.concurrent.TimeoutException: io.realm.internal.Table.finalize() timed out after 10 seconds
    at io.realm.internal.Table.finalize(SourceFile:121)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:206)
    at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:189)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by dalinaum** [comment] 2015-10-15 05:44
I changed  `#1` to `Number 1`

**Comment by dalinaum** [comment] 2015-10-15 05:49
Doesn't it involve the reaso of #1547? It only happens to Exynos 7420 too.

**Comment by petersnoopy** [comment] 2015-10-27 12:42
Same happens now on Blackberry Z10 after updating to 0.84.0

**Comment by beeender** [comment] 2015-10-27 12:49
@dalinaum Could be. Do we have the backtrace of other threads when this problem happens?

**Comment by beeender** [comment] 2015-10-27 12:50
@petersnoopy Does it only happen to Z10? Are you using the async query? Is it possible to share your project with us? to help@realm.io 
thanks!

**Comment by cmelchior** [comment] 2015-11-19 13:55
Root cause of this was a faulty kernel on the Korean version of S6 which didn't handle signals properly. 0.85.0 has been released which no longer uses signal handlers for encryption and it should fix this issue.

**Comment by dalinaum** [comment] 2016-03-18 06:27
This issue still exists: http://crashes.to/s/360245fd72a

**Comment by cmelchior** [comment] 2016-03-18 08:44
The original cause for this was our use of signals on encrypted Realms, since we moved away from signals, this cannot be the cause anymore. So i'll close this issue and move @dalinaum comment to a new issue to avoid confusion

**Closed** 2016-03-18 08:48 UTC
Labels: S:P1 Backlog, T:Bug
