### ISSUE TITLE
Expecting different RealmResults size

### ISSUE THREAD

**Issue by Orbyt** [realm/realm-java#3079] opened 2016-06-27 17:49 UTC
Using Realm in Android. I have the following code saving some data after an action:

In case your familiar with Android this is done in a Service, just in case that matters. Anyway, the code: 

```java
Realm realm = Realm.getDefaultInstance();
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {

                Log.d(TAG, "Copying to realm...");
                realm.copyToRealm(mPlayLog);
            }
        });

        RealmResults<PlayLog> res = realm.where(PlayLog.class).findAll();
        Log.d(TAG, "Size after saving: " + res.size());
```
This copies my data to realm, and properly returns the correct size after saving.

I then have a reoccurring task running to publish these logs to a server. So to get them, I obviously need to query Realm to get that data we just saved. I do that with the following code, in a BroadcastReceiver if that matters:

```java
myRealm = Realm.getDefaultInstance();
            RealmResults<PlayLog> res = myRealm.where(PlayLog.class).findAll();
            //I also tried "myRealm.allObjects(PlayLog.class);" above
            Log.d(TAG, "onReceive: " + res.size());
            res.addChangeListener(new RealmChangeListener() {
                @Override
                public void onChange() {
                    Log.d(TAG, "onChange: realm changed! Size: " + res.size());
                }
            }); 
```

Here, res.size() always prints out 0. Why is this? I can pull the database .realm file and look at it in Realm Browser and the number of objects is indeed there. So why is it returning 0?

**Comment by kneth** [comment] 2016-06-27 21:31
Duplicate of http://stackoverflow.com/questions/38059225/realmresults-size-not-returning-expected-value

**Comment by Orbyt** [comment] 2016-06-27 23:07
Yes, thats my thread, I posted here afterwards.'

Could it be that im trying to use Realm in a BroadcastReceiver?

**Comment by Zhuinden** [comment] 2016-06-28 00:00
....this also definitely has to do with the 0.89.0 breaking change

**Comment by Orbyt** [comment] 2016-06-28 00:13
@Zhuinden What was the .89.0 breaking change?

**Comment by stk1m1** [comment] 2016-06-28 02:56
@Orbyt 

Could you somehow specify following items for accelerated support?
1. What version of Realm are you currently using?
2. In what type of thread do you instantiate a Realm instance for `myRealm`? (e.g. main thread, AsyncTask, or/and a looper background thread) 
3. How do you control the life-cycle of `myRealm`?

Like @Zhuinden pointed, there has been a change as to when to recieve change notification in 0.89.0.

> `Realm.refresh()` and `DynamicRealm.refresh()` on a Looper no longer have any effect. `RealmObject` and `RealmResults` are always updated on the next event loop.

It would be great to have more comprehensive details to help you! Thanks.

**Comment by Orbyt** [comment] 2016-06-28 03:09
Currently using 1.0.1, after fixing my previous issue. I use Realm.getDefaultInstance inside an sdk i'm building. I did a check on every place I was grabbing an instance of realm and they all where on the main thread.

**Comment by zaki50** [comment] 2016-06-28 06:26
@Orbyt Can you show the code that create default `RealmConfiguration`?
Are you using in-memory Realm?

**Comment by Zhuinden** [comment] 2016-06-28 08:49
Wait a second, I think I misunderstood the issue in this case.

    Log.d(TAG, "onChange: realm changed! Size: " + res.size());

Did you see this line ever called in your code?

I'm not sure if the `BroadcastReceiver` is associated with a looper.

And also, does your receiver define `android:process=":remote"`?  Because if so, then Realm does not support multi-process.

**Comment by Orbyt** [comment] 2016-06-28 16:21
Yes, the Receiver has `android:process=":remote"` defined. So what is happening in that case? Is it creating a new and different Realm? Where would it be stored in the filesystem?

So what are my alternatives?

**Comment by Zhuinden** [comment] 2016-06-28 16:39
Well it's a strange issue because your receiver **has to be** on a different process in order to ensure that it runs even when your application is not running... but Realm does not like being opened from two different processes.

I ran into a similar problem in a similar situation with `SharedPreferences`, because that does not support multi-process either.

But I'm also not sure if Realm instances are auto-updated on a BroadcastReceiver's background thread. I think it has a looper, but does it actually *receive* the `REALM_CHANGED` event...?

Anyhow, I'm not sure what you have to do in this particular case. You'll definitely need to get help through `help[at]realm.io` with a minimal example, I think this one is over me.

**Comment by Orbyt** [comment] 2016-06-28 19:38
@zaki50 Its just:

```java
RealmConfiguration realmConfig = new RealmConfiguration.Builder(context.getApplicationContext()).build();
        Realm.setDefaultConfiguration(realmConfig);
```

not sure what you mean by in memory realm.

**Comment by zaki50** [comment] 2016-06-28 19:42
In-memory realm https://realm.io/docs/java/latest/#in-memory-realm

Hmm, you are not using in-memory Realm.

**Comment by zaki50** [comment] 2016-06-28 19:48
your code seems not to be compiled.
```
myRealm = Realm.getDefaultInstance();
            RealmResults<PlayLog> res = myRealm.where(PlayLog.class).findAll();
            //I also tried "myRealm.allObjects(PlayLog.class);" above
            Log.d(TAG, "onReceive: " + res.size());
            res.addChangeListener(new RealmChangeListener() {
                @Override
                public void onChange() {
                    Log.d(TAG, "onChange: realm changed! Size: " + res.size());
                }
            }); 
```

**Comment by Orbyt** [comment] 2016-06-28 22:18
@zaki50 Its not really relevant to this issue but it is accessible due to being _effectively final_ in java 8.

**Comment by stk1m1** [comment] 2016-06-29 07:05
@Orbyt 

Following this thread, it becomes clear that a small sample project would help us to support your issue. The sample project is necessary to reproduce your issue. Could you share one at help@realm.io please? We will look forward.

**Comment by beeender** [comment] 2016-07-13 03:00
@Orbyt I hope your issue is solved. Feel free to reopen this if needed.

**Closed by beeender** 2016-07-13 03:00 UTC
Labels: S:Waiting For User, T:Help
