### ISSUE TITLE
New RealmObject fails to save nested list of new RealmObjects. [SOURCES]

### ISSUE THREAD

**Issue by alekseichuk** [realm/realm-java#2154] opened 2016-01-25 19:20 UTC
Issue appears when application tries to append some newly created RealmObject (not persisted) to the RealmList nested into another newly created RealmObject which isn't persisted as well.

This issue has one exclusion: when all objects in structure are new Realm able to resolve dependencies and save the structure entirely.

Here's Android app which exposes problem: https://github.com/alekseichuk/realm-bugs

STEPS:

1. Build and run application.
2. You see 2 products tap any of them.
3. Now you see 3 options nested in product. Tap any.
4. Now you see 4 suboptions nested in option.
5. Restart app.
<! -- restarting generates 1 new option to each Product; also it puts new Suboptions into each Option)-->
6. Tap any product.
7. Tap option marked as (NEW)
8. Empty screen appears. 
 
9. Go back. Pick any other Option. Now you see list of suboptions including new one.

10. Close app.

Thanks.

**Comment by cmelchior** [comment] 2016-01-26 08:59
Hi @alekseichuk 

It is not really a bug, but by design given the way you implemented your insert/update. The reason it looks like it is failing is that we transparently use `copyToRealm` if you call `RealmList.add()` on an object that is not already in Realm (https://realm.io/docs/java/latest/api/io/realm/RealmList.html#add-E-). This has the side effect that further changes to that object are not persisted, which is what you are seeing.

```
        for (int i = 0; i < 2; i++) {
            Product p = findOrCreateProduct(realm, i);
            for (int j = 0; j < optCount; j++) {
                final int fakeOptionId = j + i * 10000;
                ProductOption po = findOrCreateOption(realm, p, fakeOptionId);
                p.getOptions().add(po);
                // 1) If po is not in Realm the above will make a copy of Realm, meaning that further changes  will not be saved. This is also why uncommenting works
                //TODO if to uncomment lines below issue disappears
                //if (!po.isValid()) {
                //    po = realm.copyToRealmOrUpdate(po);
                //}
                for (int k = 0; k < subCount; k++) {
                    int fakeSuboptionId = k + i * 10000 + j * 1000;
                    ProductSubOption pso = findOrCreateSuboption(realm, po, fakeSuboptionId);
                    po.getSuboptions().add(pso);
                }
            }
            // If p is already in Realm this method is just a no-op.
            realm.copyToRealmOrUpdate(p);
        }
        realm.commitTransaction();
```

I hope that makes sense?

**Comment by alekseichuk** [comment] 2016-01-26 12:29
Hi @cmelchior! Thanks for replying to me. 

I feel bet lost among available options. Can I save objects to realm one by one, like this
```
for (int id1...) {
  Product p = findOrCreteProd(realm, id1);
  //....update product's fields here...
  realm.copyToRealmOrUpdate(p); 
 // or maybe I should do it managed above by: p = realm.copyToRealmOrUpdate(p);
  for (int id2...) {
    ProductOption po = findOrCreateOption(realm, id2);
    //...update option's fields here...
  }
}
```
or I shouldn't do findOrCreate calls and rely only on PrimaryKey + copyToRealmOrUpdate
```
for (int id1...) {
  Product p = new Product();
  p.setId(id1);
  //....update other product's fields here...
  for (int id2...) {
    ProductOption po = new ProductOption();
    po.setId(id2);
    //...update other option's fields here...
  }
  realm.copyToRealmOrUpdate(p);
}
```

Sorry for massively attacking you with this questions.

Thanks.

**Comment by alekseichuk** [comment] 2016-01-26 14:57
@cmelchior Hi again,

I did small experiment here https://github.com/alekseichuk/realm-bugs/tree/experiment/primary_key

And now I prune to think that dealing with unmanaged entities and then feeding them into Realm via 
```
copyToRealmOrUpdate(object)
```
is correct way of doing things.

**Comment by cmelchior** [comment] 2016-01-26 15:00
`copyToRealmOrUpdate` is the correct way of doing it if your `object` is not managed by Realm. I think you logic would be cleaner if all `findOrCreate` methods only returned objects that was managed by Realm. That way you could also remove the last copyToRealm.

**Comment by alekseichuk** [comment] 2016-01-26 15:11
ok, I got your point. So it eligible to make it managed straight after creation like HERE: 
```
 private Product findOrCreateProduct(Realm realm, int i) {
        Product p = realm.where(Product.class).equalTo("id", i).findFirst();
        if (p == null) {
            Product p1 = new Product();
            p1.setId(i);
            p1.setName("Product " + i);
            p = realm.copyToRealm(p1); // <------ HERE
        }
        //Cleans up all options attached to product to prevent duplication
        p.setOptions(new RealmList<ProductOption>());
        return p;
    }
```

Cheers.

**Comment by cmelchior** [comment] 2016-01-29 07:56
Yes, that is correct. I'll close this issue now, feel free to reopen if other problems pop up.

**Closed by cmelchior** 2016-01-29 07:56 UTC
Labels: Help, Pending
