### ISSUE TITLE
SyncUser.currentUser is not cleared on log out

### ISSUE THREAD

**Issue by sipersso** [realm/realm-java#6006] opened 2018-06-08 14:15 UTC
Logging out doesn't seem to clear the current user. This makes it very hard to switch users. I had to manually remove the signed out user from the SyncManager user store to get sign out/switch user to work as expected. Are you supposed to have to do this manually? In the realm tasks app, the current user is ignored when switching users, which seems like a workaround too. 

I am using full synchronziation for my realm if that helps

#### Code Sample
```
SyncManager.addAuthenticationListener(object:AuthenticationListener{
    override fun loggedOut(user: SyncUser?) {
        SyncManager.removeAuthenticationListener(this)
        user?.let {
              //Without this line SyncUser.currentUser() will not return null even though the user has bee 
              // signed out
            SyncManager.getUserStore().remove(user.identity, user.authenticationUrl.toString())
        }
        signOutFromMyOwnAuthSystemAndRestartApp()
    }
    override fun loggedIn(user: SyncUser?) {}
})
SyncUser.current().logOut()
```
#### Version of Realm and tooling
Realm version(s): 5.2.0

Realm sync feature enabled: yes

Android Studio version: 3.1.3

Which Android version and device: Nexus 5x

**Comment by nhachicha** [comment] 2018-06-09 14:16
@sipersso [by design](https://github.com/realm/realm-object-store/blob/2df5b8ebf3c5a1095eb0a0d5e2480c85b2b73f93/src/sync/sync_manager.cpp#L125-L141) when you log out, the user is not removed immediately but instead tagged to be removed on the next app startup. However `SyncUser.current()` should return `null` when you log out.

I'm wondering why you need the user to be cleared immediately after a logout? if that's a requirement of your app then you can use your approach with `remove`

**Comment by sipersso** [comment] 2018-06-09 14:30
I don’t need the user to be cleared. I just need SyncUser.currentUser() to return null and it doesn’t unless I clear it from the user store. Is this really by design? If so, how am I supposed to see if there is a signed in user or not?

When logging out, i sign the user out, then starts the activity for initialization. The init activity checks SyncUser.current(). If a user exists it uses that to create a sync configuration, if not, it shows the sign in screen.

**Comment by nhachicha** [comment] 2018-06-09 15:11
> I just need SyncUser.currentUser() to return null and it doesn’t unless I clear it from the user store

This shouldn't be the case `SyncUser.currentUser()` should return `null` if the user was logged out (marked as inactive). It will be interesting to see if you can reproduce this scenario, then inspect [this line](https://github.com/realm/realm-java/blob/4cedeb961bab66ded4e9e9312ba1523a7c80e0ea/realm/realm-library/src/objectServer/java/io/realm/SyncUser.java#L841) to see why `user.isValid()` is returning `true`.

**Comment by cmelchior** [comment] 2018-06-10 16:27
We have unit tests for both logging out explicitly: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java#L220 and if the user expires https://github.com/realm/realm-java/blob/master/realm/realm-library/src/androidTestObjectServer/java/io/realm/SyncUserTests.java#L174

So if you find that this doesn't work for you, it would be great if you can reproduce in a sample project.

**Comment by sipersso** [comment] 2018-06-15 09:42
Definitely not working here, which is weird because SyncManager.getUserStore().remove is one of the first lines executed in the log out in the SyncUser.logOut() method.

Pretty short on time now and with the workaround in place (manually clear the userStore), log out works, so it might a few weeks until I can set up a sample project.

**Comment by sipersso** [comment] 2018-06-15 09:52
To add to this. If I call SyncUser.current() straight after SyncUser.logOut() it does return null. However, when called in the next activity it doesn't. I guess SyncUser.logOut() clears the sync user from a cache, while it remains on disk? And then the next SyncUser.current() reads from disk?

**Comment by cmelchior** [comment] 2018-06-15 10:04
Hmm, interesting. Thank you for that information. Our unit test just reads `SyncUser.current()` right after calling `.logout()`. This gives me something more to go after

**Comment by sipersso** [comment] 2018-06-15 10:41
Sorry about all the edits. I thought I was mistaken when I said I had identified the issue, but it turned out I was right ;)

I think the problem is that you need to make sure that all realms are closed when logging out, else SyncUser.current might return a non null value even after logging out. This is not very easy to do because of the Android lifecycle, so I had to put in the same workaround as when handling client resets as descrbed in [https://github.com/realm/realm-java/issues/5944](https://github.com/realm/realm-java/issues/5944)

**Comment by sipersso** [comment] 2018-06-15 10:43
Sorry for all the edits, I deleted the comment by mistake and have pasted it back now.

Ok, I think I have identified the issue. When logging out you can't have any open realms or else SyncUser.current won't be cleared when starting another activity. This is a big issue, since the local realm files gets corrupted if you use them with the wrong sync configuration.

Making sure that no realm instances are open is easier said than done because of the activity lifecycle in android. To get this working, I had to put the same workaround in place that I used when handling ClientResetErrors #5944.

I added the following code and now sign out works as expected, but the workaround is very ugly to say the least

```
private fun signOutFromObjectServer() { 
    if (Realm.getGlobalInstanceCount(Realm.getDefaultConfiguration()) > 0) {
            val handler = Handler()
            handler.postDelayed(Runnable {
                signOutFromObjectServer()
            }, 500)
            return
    }
    SyncUser.current().logOut()
    //Sign out from custom auth system and restart app    
}
```

**Comment by pavelpoley** [comment] 2019-03-23 10:14
> java.lang.IllegalStateException: Current user is not valid if more that one valid, logged-in user exists.

i am call SyncUser.current().logOut(); but when logging in (With different account) again this exception is thrown, with same account not thrown.

Using Google authentication with JWT.

Realm 5.9.1

**Comment by obianachebe** [comment] 2019-12-02 06:38
Is there a solution for this yet? Right now, I've had to resort to restarting the application any time a user logs out in order to avoid the issue where SyncUser.current() throws an exception when logging in with a different account. 

I don't have this problem on the iOS SDK. How do other developers currently handle this issue?

**Comment by sipersso** [comment] 2019-12-02 07:11
@obianachebe I am using the following workaround to make sure the Realm is closed. 
> 
> ```
> private fun signOutFromObjectServer() { 
>     if (Realm.getGlobalInstanceCount(Realm.getDefaultConfiguration()) > 0) {
>             val handler = Handler()
>             handler.postDelayed(Runnable {
>                 signOutFromObjectServer()
>             }, 500)
>             return
>     }
>     SyncUser.current().logOut()
>     //Sign out from custom auth system and restart app    
> }
> ```

Be careful though. This only works if it is the Android lifecycle that is causing delays before the Realm is closed. You still have to make sure to actually call close or else you will still have an issue. 

Realm doesn’t make it easy to debug these issues, so I’d recommend adding a lifecycle listener that prints out the global instance count to make it easier to pinpoint if you have forgotten to close the Realm anywhere.

If you are on Kotlin I’d recommend to use the ”use” function to wrap your Realm usage. That way the Realm is closed automatically.

I am glad to see that this has been added to the Realm backlog as I think the issue is pretty severe.

**Comment by sipersso** [comment] 2019-12-02 07:17
Be careful with the workaround though. If you actually have an open Realm somewhere and it is not just the Android lifecycle that is causing delays when closing it. Then the workaround will cause the Application to hang, so you may want to add a max number of retries.

**Comment by pavelpoley** [comment] 2019-12-02 08:13
Very sad 1.5 years and no result.

**Comment by obianachebe** [comment] 2019-12-02 08:54
@sipersso thanks for the suggestion, but I don't think that'll work for my use-case. 

When that exception is thrown, I attempt to find the most recently logged in user using the `expires` field from the SyncUser JSON and then create a new `RealmConfiguration` from that object. 

The exception is no longer thrown, but instead of fetching the new user's data, it only gets data for the previously logged in user.

```
            var currentUser: SyncUser? = tryOrNull { SyncUser.current() }
            if (SyncUser.all().count() > 1) {
                val sortedUsers = SyncUser.all().values.sortedBy {
                    val json = JSONObject(it.toJson())
                    val userToken = json.optJSONObject("userToken")
                    val tokenData = userToken.optJSONObject("token_data")
                    val expires = tokenData.optInt("expires")
                    return@sortedBy expires
                }

                for (i in 0 until sortedUsers.count() - 1) {
                    sortedUsers[i].logOut()
                }

                currentUser = sortedUsers.lastOrNull()
            }
```

**Comment by cmelchior** [comment] 2019-12-02 10:40
As mentioned in https://github.com/realm/realm-java/issues/6006#issuecomment-396062131 we should have unit tests covering the behavior of `SyncUser.current()`. I gave them a second look today but from what I can tell everything looks like it is working as expected.

That doesn't mean there isn't a bug somewhere, but it would help a lot if you could provide a minimal working sample that showed exactly when it breaks.

**Comment by sipersso** [comment] 2019-12-02 10:59
As stater earlier. SyncUser.getCurrent returns null if you call it directly after log out, which is probably what the unit test is covering. But when you start the next activity it won’t be null anymore. 

In my case, the workaround works good enough, which is why it is hard to prioritize producing a repro case. But without a workaround this can lead to corrupted realms, so it is severe. I’ll see if I can make time for producing a sample, but I can’t make any promises. Already spent a lot of time on this issue.

**Comment by bmunkholm** [comment] 2021-11-30 15:03
Closing as this is related to legacy sync.

**Closed by bmunkholm** 2021-11-30 15:03 UTC
Labels: T-Bug, Reproduction-Required, O-Community
