### ISSUE TITLE
notEqualTo does not consider empty lists

### ISSUE THREAD

**Issue by degill** [realm/realm-java#2428] opened 2016-03-11 15:01 UTC
> What do you want to achieve?
> Find all TestObjects whose containing RealmList does not contain an OtherObject with a simple constraint.
#### Expected Results

A list of all TestObjects, whose otherObjects-list does not contain OtherObjects with a count value of 2. I should not specifically consider TestObjects with an empty otherObjects-list.
#### Actual Results

A list of TestObjects which do have a non-empty otherObjects list that does not contain any OtherObject with a count of 2. TestObjects with an empty otherObjects list are ignored.
#### Code Sample

``` java
public class OtherObject extends RealmObject {
    int count;
}

public class TestObject extends RealmObject {
    RealmList<OtherObject> otherObjects;
}

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        RealmConfiguration config = new RealmConfiguration.Builder(this).build();
        Realm.setDefaultConfiguration(config);

        Realm realm = Realm.getDefaultInstance();

        realm.beginTransaction();
        realm.deleteAll();
        realm.commitTransaction();

        realm.beginTransaction();
        OtherObject otherObject1 = realm.createObject(OtherObject.class);

        otherObject1.count = 1;

        TestObject testObject1 = realm.createObject(TestObject.class);
        TestObject testObject2 = realm.createObject(TestObject.class);

        testObject1.otherObjects.add(otherObject1);
        realm.commitTransaction();

        //Neither testObject1 nor testObject2 do contain an otherObject with count == 2

        RealmQuery<TestObject> query = realm.where(TestObject.class).notEqualTo("otherObjects.count", 2);
        Log.d("MainActivity", String.format("TestObjects which do not have OtherObjects with a count-value of 2: %d", query.count())); //Prints "...: 1" instead of "...: 2"

        query = query.or().isEmpty("otherObjects");
        Log.d("MainActivity", String.format("TestObjects which do not have OtherObjects with a count-value of 2: %d", query.count())); //Prints "...: 2"

        realm.close();
    }
```
#### Version of Realm and tooling

Realm version(s): Tested with 0.87.5 and 0.88

Android Studio version: 2.1 Preview 1

Which Android version and device: 6.0.1 - Nexus 5

**Comment by beeender** [comment] 2016-03-14 04:28
This is actually the expected behaviour.

It is obvious that `realm.where(TestObject.class).equalTo("otherObjects.count", 1);` doesn't return `testObject2` since `testObject2` has an empty list, non of the element meet the condition that `count == 1`.

It is also true when it comes to the `notEqualTo` although it is not that obvious. Since `testObject2` has an empty list, non of the element meet the condition that `count != 2`.

But we definitely should document this behaviour.

**Comment by cbush** [comment] 2019-08-13 19:48
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.

**Closed by cbush** 2019-08-13 19:48 UTC
Labels: O:User, T:Doc
