### ISSUE TITLE
Unable to find source java class when using latest gradle version

### ISSUE THREAD

**Issue by CDRussell** [realm/realm-java#2113] opened 2016-01-19 11:28 UTC
Previously, I was using 
`classpath 'com.android.tools.build:gradle:2.0.0-alpha3'` and everything was working fine.

After upgrading to 
`classpath 'com.android.tools.build:gradle:2.0.0-alpha5'` however, I see the following issue.

When using Realm version 0.86.0 the missing class is `DefaultRealmModuleMediator.java`, the error message is:
    
    Error:Execution failed for task ':app:compileDevDebugUnitTestJavaWithJavac'. 
    Unable to find source java class: '/Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/build/intermediates/classes/dev/debug/io/realm/DefaultRealmModuleMediator.java' because it does not belong to any of the source dirs: '[/Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/test/java, /Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/testDev/java, /Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/testDebug/java, /Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/testDevDebug/java]'

When using the latest 0.87.2, the error still happens but with a different class not being found, `UserProfileRealmProxy.java`:

    Execution failed for task ':app:compileDevDebugUnitTestJavaWithJavac'.
    Unable to find source java class: '/Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/build/intermediates/classes/dev/debug/io/realm/UserProfileRealmProxy.java' because it does not belong to any of the source dirs: '[/Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/test/java, /Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/testDev/java, /Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/testDebug/java, /Users/craig/Dev/digital-acre/Enquos/enquos-android-nutrition/app/src/testDevDebug/java]'

(`UserProfile` is a subclass of `RealmObject` in my project)

This is when running _pure_ Junit tests (not the Android instrumentation tests).
Note, the first time I run the tests after a clean, the tests build and execute fine. However, whenever I make any change to the app and run the tests again, I see the above error message.

This error happens in both Android Studio and from the command line. I assume it has something to do with the latest changes in the gradle plugin to further support Instant Run, but other than that, I'm at a loss.

Android Studio 2.0 Preview 5 (Build #AI-143.2532994)
JDK: jdk1.8.0_60

**Comment by Saketme** [comment] 2016-01-19 13:01
Gradle alpha 5 not being able to find the mediator proxy class was happening to me as well. I switched back to 1.5.

**Comment by CDRussell** [comment] 2016-01-19 13:13
@Saketme for me leaving Android Studio at 2.0 was fine but I had to revert the gradle plugin back to `alpha3`.

**Comment by cmelchior** [comment] 2016-01-19 19:10
@CDRussell I just tried to upgrade our examples to `2.0.0-alpha6` and it seemed to work. Can you try that as well?

**Comment by Saketme** [comment] 2016-01-20 07:22
@cmelchior This issue was happening randomly for me on alpha5. Like after a few builds.

**Comment by dalinaum** [comment] 2016-01-20 07:37
Hello, @Saketme. Can you upgrade to `2.0.0-alpha6`?

**Comment by CDRussell** [comment] 2016-01-20 08:29
@cmelchior hi, thanks for the reply. I tried upgrading to `2.0.0-alpha6` but it still failed with the same issue. I tried upgrading to realm `0.87.2` and even `0.88.0-SNAPSHOT` but still having the same problem.

I will grab the examples and see if they work for me and let you know. Thanks.

**Comment by CDRussell** [comment] 2016-01-20 10:21
@cmelchior Do you have working commit using `2.0.0-alpha6`? I am having issues changing the example project to use it. I have checked out and built the projects locally and can run the tests successfully. My issue is in trying to edit it to use `2.0.0-alpha6` instead of `1.5.0`.

I assumed it was as simple as editing `examples/build.gradle` and replacing 
`classpath 'com.android.tools.build:gradle:1.5.0'` 

with 
`classpath 'com.android.tools.build:gradle:2.0.0-alpha6'` 

However, this throws up compilation issues. I assume I am either doing something wrong or there are more steps to make this change than just changing that line. I figure in either case, you have solved this issue already locally?

**Comment by cmelchior** [comment] 2016-01-20 10:24
Main `build.gradle`:
```
project.ext.sdkVersion = 23
project.ext.buildTools = '23.0.0'

// Don't cache SNAPSHOT (changing) dependencies.
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

allprojects {
    def currentVersion = file("${rootDir}/../version.txt").text.trim()

    buildscript {
        repositories {
            mavenLocal()
            jcenter()
            maven { url 'https://jitpack.io' }
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:2.0.0-alpha6'
            classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.2'
            classpath 'com.github.JakeWharton:sdk-manager-plugin:0ce4cdf08009d79223850a59959d9d6e774d0f77'
            classpath 'com.jakewharton.sdkmanager:gradle-plugin:0.12.0'
            classpath 'com.novoda:gradle-android-command-plugin:1.3.0'
            classpath "io.realm:realm-gradle-plugin:${currentVersion}"
        }
    }

    group = 'io.realm'
    version = currentVersion

    repositories {
        mavenLocal()
        jcenter()
    }
}
```

The SDK-manager isn't supported in the 2.0.0-x plugin yet, so have to use an unofficial release.

**Comment by CDRussell** [comment] 2016-01-20 11:06
@cmelchior thanks for that. I dropped that into my local `examples` and can confirm that works OK and doesn't experience the issue I have. 

The examples all contain `apply plugin: 'realm-android'` but that isn't something I apply to my project. Should I be using that for mines?

A potential workaround for the issue I'm seeing is to delete my app's `build/intermediates` directory after every code change before running the unit tests. Obviously that is a bit nuclear and bound to cause other issues, but that is currently the only way I can 'fix' the compilation problem after making a source code change.

Any thoughts?

**Comment by cmelchior** [comment] 2016-01-20 11:10
@CDRussell Yes, the plugin is the way we intend to distribute Realm going forward. You can read more about it here: https://realm.io/news/android-installation-change/

The Gradle tools are alpha for a reason, so I suspect that they still contain errors in the mix of Instant Run / Annotation processors / Multidex. Clearing your build folder forces a clean build, which is why the problem isn't experienced there. At least that would be my theory.

**Comment by CDRussell** [comment] 2016-01-20 12:03
@cmelchior success! the plugin was the missing link!

In the end, I moved to using `2.0.0-alpha6` of the gradle plugin combined with the latest stable realm version `0.87.2`.

My unit test issue is fixed and instant run is working a treat. I think I'm all set now.

Many thanks for your speedy help. 👍

**Comment by dalinaum** [comment] 2016-01-20 12:13
Great. I'll close this issue. If you encounter the further problem, please feel free to reopen this issue or create a new one.

**Closed by dalinaum** 2016-01-20 12:13 UTC
Labels: Help, Pending
