### ISSUE TITLE
Crash: table index out of range #2522 still exists!

### ISSUE THREAD

**Issue by imidhuntv** [realm/realm-java#3215] opened 2016-07-26 12:58 UTC
The bug 'Crash: table index out of range #2522' is said to be closed in Realm version 1.0.0
This bug still exists. This happened in an old low end device.

CrashLog,

```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Table index out of range in io_realm_internal_Group.cpp line 190
       at io.realm.internal.Group.nativeGetTableNativePtr(Group.java)
       at io.realm.internal.Group.getTable(Group.java:199)
       at io.realm.internal.SharedGroupManager.getTable(SharedGroupManager.java:90)
       at io.realm.BaseRealm.getVersion(BaseRealm.java:427)
       at io.realm.Realm.getVersion(Realm.java:7120)
       at io.realm.Realm.createInstance(Realm.java:228)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
       at io.realm.Realm.getDefaultInstance(Realm.java:174)
       at com.talkoot.android.pubnub.PubNubObserverDelegateImpl$$Lambda$2.run(Unknown Source:1072)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)

```
We are using realm 1.0.0.
Device : iris405
OS : 4.2.2
Rooted : yes
Free Space :300.64 MB
Free Ram : 61.21 MB

**Comment by Zhuinden** [comment] 2016-07-26 13:05
This sounds like database corruption to me; is this reproducible?

**Comment by beeender** [comment] 2016-07-26 13:05
Since it is in the worker thread, I think https://github.com/realm/realm-core/pull/1958 should fix it which will be released in `v1.1.1`.

**Comment by cmelchior** [comment] 2016-10-25 06:28
1.1.1 has been out for a while and no other reports have been made on this. Closing.

**Closed by cmelchior** 2016-10-25 06:28 UTC
Labels: S:P1 Backlog, T:Bug-Crash

**Comment by NirpE** [comment] 2016-12-11 07:12
I just saw this error using Realm 2.2.1. Using encrypted Realm and RxJava2 with Retrofit for network and threading.

12-11 09:07:53.311 20566-20653/com.xxx E/REALM_JNI: jni: ThrowingException 5, Table index out of range in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92, .

io.realm.exceptions.RealmError: Unrecoverable error. Table index out of range in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
                                                                        at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                        at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
                                                                        at io.realm.BaseRealm.<init>(BaseRealm.java:82)
                                                                        at io.realm.Realm.<init>(Realm.java:138)
                                                                        at io.realm.Realm.createAndValidate(Realm.java:283)
                                                                        at io.realm.Realm.createInstance(Realm.java:264)
                                                                        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
                                                                        at io.realm.Realm.getInstance(Realm.java:227)
