### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error. open() failed: No such file or directory in io_realm_internal_SharedGroup.cpp line 188

### ISSUE THREAD

**Issue by vishnu888** [realm/realm-java#2308] opened 2016-02-20 07:48 UTC
Hi, 
I keep getting the above error in my app(crashes) when I logout and re-login. 
Using the realm config
`realmConfiguration = new RealmConfiguration.Builder(this)
                .name("hombotdata.realm")
                .deleteRealmIfMigrationNeeded()
                .schemaVersion(1)
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);`

On logout, I close out all open instances of realm and delete the realm database using
`Realm.deleteRealm(realmConfiguration);`

Even though the app crashes, when I reopen it, it's succesfully logged in(Session data is stored and the app is able to resume the session). 
How do I fix it?

**StackTrace:**
_io.realm.exceptions.RealmError: Unrecoverable error. open() failed: No such file or directory in io_realm_internal_SharedGroup.cpp line 188
                                                                                 at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
                                                                                 at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:99)
                                                                                 at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:60)
                                                                                 at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:116)
                                                                                 at io.realm.BaseRealm.commitTransaction(BaseRealm.java:292)
                                                                                 at io.realm.Realm.commitTransaction(Realm.java:108)
                                                                                 at com.vikilabs.hombot_android.home.HomeModel$3.onResponse(HomeModel.java:141)
                                                                                 at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:65)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:155)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5721)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)_

**Comment by beeender** [comment] 2016-02-22 01:54
Can you please share some code pieces where at com.vikilabs.hombot_android.home.HomeModel$3.onResponse(HomeModel.java:141)?

**Comment by vishnu888** [comment] 2016-02-22 03:53
I basically do a retrofit http call to get some information from a server and on success, I commit that information to Realm. The realm.commitTransaction is line 141

`ApiService apis = ServiceGenerator.getInstance().createService(ApiService.class);
        Call<HomesResponse> call = apis.getHomes(user.getEmail(), user.getAccessToken());
        call.enqueue(new Callback<HomesResponse>() {
            @Override
            public void onResponse(Response<HomesResponse> response) {
                if (response.isSuccess()) {
                    if (response.body().getSuccess()) {
                        HomesResponse resp = response.body();
                        List<Homes> homes = resp.getHomes();

                        realm.beginTransaction();
                        realm.copyToRealmOrUpdate(homes);
                        realm.commitTransaction();
                        Log.i("Loaded From ", "Network");
                        RealmResults<Homes> homes1 = realm.where(Homes.class).findAll();
                        presenter.onSetData(homes1);
                    } else {
                        presenter.onFailed();
                    }
                } else {
                    presenter.onFailed();
                }
            }

            @Override
            public void onFailure(Throwable t) {
                Log.e("Throw Error", t.getMessage());
            }
        });`

**Comment by beeender** [comment] 2016-02-22 04:02
Where did you put `setDefaultConfiguration`? And where/how is the declaration of the `realm` instance in `com.vikilabs.hombot_android.home.HomeModel$3.onResponse`?

`setDefaultConfiguration` is not thread safe, i am wondering maybe there is a chance you are calling `getDefaultConfiguration` and `setDefaultConfiguration` at the same time...

**Comment by vishnu888** [comment] 2016-02-22 04:53
The configuration is set only once on the start of the application. 

`public class HombotApplication extends Application {

    private RealmConfiguration realmConfiguration;

    @Override
    public void onCreate() {
        super.onCreate();
        Fabric.with(this, new Crashlytics());
        Thread.currentThread().setPriority(Thread.MAX_PRIORITY);
        realmConfiguration = new RealmConfiguration.Builder(this)
                .name("hombotdata.realm")
                .deleteRealmIfMigrationNeeded()
                .schemaVersion(1)
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }

    public void deleteDataBase() {
        Realm.deleteRealm(realmConfiguration);
    }

}`

The instance of Realm for HomeModel is being passed as a parameter from HomeActivity(we're using the MVP format) which is the first activity that's launched on login. The weird part is that it only happens on every alternate login. 

1st Login (No error) -> Logout -> 2nd Login (crashes but session launched on reopen) -> Logout -> 3rd Login (No error) and so on...

**Comment by beeender** [comment] 2016-02-22 04:57
> The weird part is that it only happens on every alternate login. 

Can you please show me the code related with Realm when you do login and logout?

**Comment by vishnu888** [comment] 2016-02-22 05:28
**On Login Response:**

`public void onResponse(Response<AuthenticationResponse> response) {
                    if (response.isSuccess()) {
                        User user;
                        Log.i("Login Success", response.body().toString());
                        if (response.body().getSuccess()) {
                            realm.beginTransaction();
                            user = data.size()>0?data.get(0):realm.createObject(User.class);
                            user.setEmail(email);
                            user.setPassword(password);
                            user.setSessionId(response.body().getData().getSessionId());
                            user.setStartTime(response.body().getData().getStartTime());
                            user.setAccessToken(response.body().getData().getAccessToken());
                            user.setDeviceId(uuid);
                            user.setDeviceType(deviceInfo);
                            realm.commitTransaction();
                            listener.onSuccess();
                        } else {
                            switch (response.body().getCode()) {
                                case ResponseCodes.AlreadyLoggedIn:
                                    listener.onFailed(response.body().getReason());
                                    break;

                                case ResponseCodes.UseDoesNotExist:
                                    listener.onPasswordError();
                                    break;

                                case ResponseCodes.WrongPassword:
                                    listener.onPasswordError();
                                    break;
                                default:
                                    listener.onFailed(response.body().getReason());
                            }

                        }
                    } else {
                        listener.onFailed("Something Went Wrong.");
                    }

OnSuccess method spawns the HomeActivity and the onFailed and onPassword just display toast messages on the screen.


**Logout:**

`ApiService apiService = ServiceGenerator.getInstance().createService(ApiService.class);
                        InvalidateSessionRequest request = new InvalidateSessionRequest();

                        request.setDeviceType(user.getDeviceType());
                        request.setDeviceId(user.getDeviceId());
                        request.setSessionId(user.getSessionId());
                        request.setEmail(user.getEmail());
                        Call<InvalidateSession> call = apiService.invalidateSession(request);

                        call.enqueue(new Callback<InvalidateSession>() {
                            @Override
                            public void onResponse(Response<InvalidateSession> response) {
                                if (response.isSuccess()) {
                                    if (response.body().getSuccess()) {
                                        realm.close();
                                        Intent i = new Intent(HomeActivity.this, LoginActivity.class);
                                        i.putExtra("Logout", true);
                                        i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                                        startActivity(i);
                                        finish();
                                    } else {
                                        Toast.makeText(HomeActivity.this, "Error Signing Out", Toast.LENGTH_SHORT).show();
                                    }
                                } else {
                                    Toast.makeText(HomeActivity.this, "Error Signing Out", Toast.LENGTH_SHORT).show();
                                }
                            }

                            @Override
                            public void onFailure(Throwable t) {

                            }
                        });`

Logout just invalidates the session on server side and Launches the login activity again and clears the activity stack. We're opening realm instances on every activity onCreate and closing them on every activity onDestroy.

PS: I appreciate you making time to help me out. Thank you.

`

**Comment by vishnu888** [comment] 2016-02-22 05:31
There seems to be a problem with GitHub's post code feature. Anyways, the data variable in Login code is to check if there is user info already present on the phone. If there is, we replace it else we create a new one.

**Comment by beeender** [comment] 2016-02-22 05:44
@vishnu888 When fortmat multi-lines of code in github, use "```" as the start line and "```" as the end line :)

**Comment by beeender** [comment] 2016-02-22 05:48
It is still difficult to tell what is the problem with those information. Is it OK to share your project with us? If you want to share it privately, you can send it to help@realm.io

**Comment by vishnu888** [comment] 2016-02-22 06:00
Give me a few hours and I'll get back to you on that. Thanks for the help.

**Comment by vishnu888** [comment] 2016-02-22 06:02
Quick question, what is line 188 in io_realm_internal_SharedGroup.cpp trying to open? and where can I find the cpp file to take a look?

**Comment by beeender** [comment] 2016-02-22 06:06
https://github.com/realm/realm-java/blob/master/realm/realm-jni/src/io_realm_internal_SharedGroup.cpp

here it is. The lower layer is inside our underline engine which is not open sourced yet. But your problem seems when calling the `getInstance`, the path to the realm file cannot be accessed. Maybe you can try to debug the problematic `getInstance`/`getDefaultInstance` call and try to see what is the path the realm file in the configuration at that time. I have seen similar problem caused by some illegal chars in the realm file path, but according to your source code, it doesn't seem to be the problem.

**Comment by beeender** [comment] 2016-03-02 02:38
@vishnu888 Do you find any more clues about this issue? Thanks!

**Comment by vishnu888** [comment] 2016-03-03 10:21
Hey, still no luck. We're trying to fix a couple of other issues with the app. I'll take a look in a couple of hours and if I can't figure it out, I'll mail the project to you. Thanks for the help.

**Comment by beeender** [comment] 2016-03-03 10:22
Thanks! If you want to share the project privately, you can just send it to help@realm.io .

**Comment by cmelchior** [comment] 2016-03-10 06:30
Hi @vishnu888 
Did you manage to solve the above?

**Comment by beeender** [comment] 2016-03-16 03:18
Close due to no response.

**Comment by chinmaygit** [comment] 2016-03-25 08:09
Sorry. issue, resurfaces again...

**Comment by dinhthaidaica** [comment] 2016-04-26 08:55
Hi guys, Today I'm still facing this is issue, can anyone help to have a look?
`FATAL EXCEPTION: main
                                                                         Process: com.planday.ninetofiveapp, PID: 3221
                                                                         io.realm.exceptions.RealmError: Unrecoverable error. open() failed: No such file or directory in io_realm_internal_SharedGroup.cpp line 188
                                                                             at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
                                                                             at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:99)
                                                                             at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:60)
                                                                             at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:116)
                                                                             at io.realm.BaseRealm.commitTransaction(BaseRealm.java:292)
                                                                             at io.realm.Realm.commitTransaction(Realm.java:108)`

My code:
`public void updateListRoleForScheduling(List<RoleInShift> list, long departmentId) {
        if (list != null && list.size() > 0) {
            Realm realm = RealmManager.getInstance().getRealm();
            realm.beginTransaction();
            for (int i = 0; i < list.size(); i++) {
                RoleInShift role = list.get(i);
                RRole rRole = realm.where(RRole.class).equalTo(RRole.ID, role.getId()).findFirst();
                if (rRole != null) { // update
                    rRole.setName(role.getName());
                    rRole.setColor(role.getColor());
                    rRole.setSort_order(role.getSort_order());
                    rRole.setIs_deleted(role.is_deleted());
                    rRole.setIs_visible(role.is_visible());
                    List<Long> ids = BPUtils.getListIDByString(rRole.getDepartmentId());
                    if (ids == null || ids.size() == 0 || !ids.contains(departmentId)) {
                        if (ids == null) {
                            ids = new ArrayList<>();
                        }
                        ids.add(departmentId);
                        rRole.setDepartmentId(BPUtils.getStringListID(ids));
                    }
                    if (role.getPermissions() != null && role.getPermissions().size() > 0) {
                        for (int i2 = 0; i2 < role.getPermissions().size(); i2++) {
                            if (role.getPermissions().get(i2).equals(BPUtils.PERMISSION_READ_ROLE)) {
                                rRole.setIs_readable(true);
                            } else if (role.getPermissions().get(i2).equals(BPUtils.PERMISSION_UPDATE_ROLE)) {
                                rRole.setIs_editable(true);
                            }
                        }
                    }
                } else if (!role.is_deleted()) { // create new
                    realm.copyToRealm(RealmModelConverter.convertFromRoleInShift(role, departmentId));
                }
            }
            realm.commitTransaction();
            realm.removeAllChangeListeners();
            realm.close();
        }
    }`

The log points that crash occur when I call `realm.commitTransaction();`

**Comment by beeender** [comment] 2016-04-26 09:12
@dinhthaidaica Need some more details about your problem:

1. Realm version
2. Can you please share the source code of RealmManager
3. If you can reproduce this problem, can you please share your project with us and let us know how to reproduce it?

If you want to share those privately, you can send it to help@realm.io.

**Comment by dinhthaidaica** [comment] 2016-04-26 10:31
I'm currently using version 0.87.4.
RealmManager class as below: 
```javascript
public class RealmManager {

    protected Context mContext;
    private Realm realm;
    private static RealmManager mInstance;
    private final String REALM_DATABASE_NAME = "Database.realm";

    public static RealmManager getNewInstance() {
        return new RealmManager(PlandayApplication.getPlandayApplicationContext());
    }

    private Realm getRealmFromConfig(Context context) {
        RealmConfiguration config = new RealmConfiguration.Builder(context)
                .name(REALM_DATABASE_NAME)
                .schemaVersion(1)
                .setModules(new Module())
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(config);
        return Realm.getInstance(config);
    }

    /**
     * RealmManager wraps your query and insert/update statements based on class type
     * @param context application context
     */
    RealmManager(Context context) {
        mContext = context;
        realm = getRealmFromConfig(mContext);
    }

    public Realm getRealm() {
        if (realm == null) {
            realm = getRealmFromConfig(PlandayApplication.getPlandayApplicationContext());
        }
        realm.refresh();
        return realm;
    }


}
```

**Comment by beeender** [comment] 2016-04-26 11:02
@dinhthaidaica Can you always reproduce the problem or only one some specific devices?

**Comment by beeender** [comment] 2016-04-26 13:04
Also, do you use `Realm.deleteRealm()`?

**Comment by dinhthaidaica** [comment] 2016-04-27 03:42
Yes, I use `Realm.deleteRealm()` in some case.
And the issue occurs with sequently about 80%, not always

**Comment by beeender** [comment] 2016-04-27 04:36
@dinhthaidaica Would the problem happen after `Realm.deleteRealm()` called?

**Comment by dinhthaidaica** [comment] 2016-04-27 04:48
No,  I dont think `Realm.deleteRealm()` was called

**Comment by beeender** [comment] 2016-04-27 04:53
> And the issue occurs with sequently about 80%, not always

80% means you can have 80% chance to reproduce this issue or you see 80% users have this issue in the crash log server?

If you can share your project with us and let us know what is the possible steps to reproduce this issue, it would be very helpful. Please send the project to help@realm.io if you can share it privately with us. thanks a lot!

**Comment by dinhthaidaica** [comment] 2016-04-27 05:01
Thank you so much for you support but I can't share my project due to privacy :(
80% with meaning that what I can reproduce it

**Comment by beeender** [comment] 2016-04-27 05:20
@dinhthaidaica OK then...

Would you please add below before calling any functions of Realm to enable more traces

```
io.realm.internal.Util.setDebugLevel(5);
RealmLog.add(new DebugAndroidLogger());
```

And get a full log for us? The log has to begin with the app process starting and end when crash.
Hope we can get more useful information. Thanks!!!

**Comment by beeender** [comment] 2016-04-28 08:37
Luckily I am able to reproduce the same backtrace with below test case while testing some other issues:

```java
public class RealmTests {
    @Test
    @RunTestInLooperThread
    public void luckyTest() {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Dog dog = realm.createObject(Dog.class);
                dog.setAge(10);
            }
        });

        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Realm realm = Realm.getInstance(realmConfig);

                    realm.beginTransaction();
                    realm.commitTransaction();

                    realm.close();
                }
            }
        }).start();

        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Realm realm = Realm.getInstance(realmConfig);

                    realm.beginTransaction();
                    Dog dog = realm.where(Dog.class).findFirst();
                    dog.setAge(0);
                    realm.commitTransaction();

                    realm.beginTransaction();
                    Dog dog1 = realm.where(Dog.class).findFirst();
                    dog1.setAge(10);
                    realm.commitTransaction();

                    realm.close();
                }
            }
        }).start();

        final RealmResults<Dog> results = realm.where(Dog.class).findAll().where().greaterThan("age", 0).findAll();
        final RealmChangeListener listener = new RealmChangeListener() {
            @Override
            public void onChange() {
                int size = results.size();
                if (size > 0) {
                    Dog dog = results.get(size - 1);
                    //Log.e("LUCKY", dog.toString());
                } else {
                    //Log.e("LUCKY", "empty");
                }
            }
        };

        realm.addChangeListener(listener);

    }
}
```

If simplify it to something like below, i can reproduce "io.realm.exceptions.RealmIOException: File not found: ."

```java
public class RealmTests {
    @Test
    @RunTestInLooperThread
    public void veryLuckyTest() {

        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Realm realm = Realm.getInstance(realmConfig);

                    realm.beginTransaction();
                    realm.commitTransaction();

                    realm.close();
                }
            }
        }).start();

        final RealmChangeListener listener = new RealmChangeListener() {
            @Override
            public void onChange() {
            }
        };

        realm.addChangeListener(listener);

    }
}
```

**Comment by vishnu888** [comment] 2016-04-28 10:14
Sorry, I'm afraid I still don't completely understand what's causing the issue. Can you please explain?

**Comment by beeender** [comment] 2016-05-03 12:47
@vishnu888 Never mind, the above comments are the tests cases which I can use to reproduce the issue. Since we can reproduce this, we will try to fix it ASAP.

**Comment by beeender** [comment] 2016-05-05 10:16
@vishnu888 The test case i posted is different from what you met. It would still be very helpful if you can share your project with us. Thanks!

**Comment by beeender** [comment] 2016-05-05 11:34
@vishnu888 Also, would you please check in the logcat, your logout/login happened in the same process? Since the `Activity.finish()` is called when logout and a intent started before to restart the activity, i doubt a new process might be created for the new login. In that case, this issue might happen.

**Comment by vishnu888** [comment] 2016-05-06 02:30
That might have been the issue. We've made a few changes to the way the logout/login happens and the issue seems to have disappeared. Will let you know if it pops up again. Cannot share the project due to privacy. Appreciate the help.

**Comment by kneth** [comment] 2016-05-17 12:55
@vishnu888 Have you seem the issue lately? Or do you believe we can close the issue?

**Comment by vishnu888** [comment] 2016-05-19 06:02
Hey, this issue hasn't resurfaced for me recently. Should be fine to close it. Not sure if @dinhthaidaica got his issue resolved though.

**Comment by kneth** [comment] 2016-05-19 07:37
@vishnu888 Thanks for the update

**Closed** 2016-05-25 12:55 UTC
Labels: Reproduction Required, S:P1 Backlog, T:Bug-Crash

**Comment by GokhanArik** [comment] 2016-09-02 16:23
I'm having the same issue in 1.1.0.

```
W/System.err: java.lang.IllegalArgumentException: Illegal Argument: open("*********/files/default.realm.management/log_access") failed: No such file or directory path: /data/data/**********/files/default.realm.management/log_access in io_realm_internal_SharedGroup.cpp line 188
W/System.err:     at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
W/System.err:     at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:149)
W/System.err:     at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:62)
W/System.err:     at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:118)
W/System.err:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:370)
W/System.err:     at io.realm.BaseRealm.commitAsyncTransaction(BaseRealm.java:357)
W/System.err:     at io.realm.Realm$1.run(Realm.java:1166)
W/System.err:     at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
```
