### ISSUE TITLE
Making sense of 'Encrypted interprocess sharing is currently unsupported'

### ISSUE THREAD

**Issue by biftekman** [realm/realm-java#3203] opened 2016-07-22 07:10 UTC
```
io.realm.exceptions.RealmError: Unrecoverable error. /data/data/<package>/files/database.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 22257. Current pid is 17958. in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.a(SourceFile:95)
	at io.realm.internal.SharedGroup.<init>(SourceFile:74)
	at io.realm.internal.SharedGroupManager.<init>(SourceFile:49)
	at io.realm.BaseRealm.<init>(SourceFile:81)
	at io.realm.Realm.<init>(SourceFile:140)
	at io.realm.Realm.b(SourceFile:240)
	at io.realm.Realm.a(SourceFile:220)
	at bbq.a(SourceFile:126)
	at io.realm.Realm.getDefaultInstance(SourceFile:166)
```

Crashlytics reports this kind of crash for around 1,5% of about 50k users so far and I can't figure out what causes it, neither reproduce it on any of our test devices or emulator.

**Things to consider:**
- `getDefaultInstance()` that causes the crash is always called inside `onCreate()` method of our Application class. That's where Realm's default configuration gets set and default instance is obtained.
- Our manifest file doesn't define any remote processes, like `process:remote`
- If a third party library created a remote process (like the case with #1477 ), we would expect the crash to always happen? (I also try to catch it with RealmIOException, but that doesn't seem to do anything for any reason)
- Crash always spikes on the first days following the update and drops significantly after, indicating that only users who updated get affected.
- Considering the sheer amount of crashes and users affected, we get no complaint emails reporting this.

#### Version of Realm and tooling
Realm version(s): 1.1.0
Android Studio version: 2.1.2
Which Android version and device: all supported (4.0.3+)

**Comment by stk1m1** [comment] 2016-07-25 07:14
@biftekman 

Would you mind if I ask you to close this issue and repost your observation on #1477? (Copy & paste would work fantastic.) It seems to us this need to be reliably reproduced to track down the cause and squash it, and it would be really helpful for us to collect related issues in one place to provide best possible support.

Thanks!

**Closed** 2016-07-25 07:27 UTC
