### ISSUE TITLE
Illegal Argument Exception encountered when compressing a Realm file created by version 0.83.0

### ISSUE THREAD

**Issue by creativepsyco** [realm/realm-java#1581] opened 2015-10-12 09:14 UTC
Hi peeps,

I am currently running into an `IllegalArgumentException` indicating that the format of the Realm file is invalid when I am trying to call `Realm.compactRealm(realmConfiguration...)` before I use the realm file.

I have a sample project to demonstrate the crash here: https://github.com/creativepsyco/sample-realm-crash/

Essentially I am trying to compact the realm file before it is ever used in the app.

Steps to reproduce:
1. Clone the project from https://github.com/creativepsyco/sample-realm-crash/
2. Compile and run. It will not crash because realm version is `0.82.2`
3. Now in `build.gradle` edit the version to `0.83.0`
4. Compile and run the app. 
5. It crashes with the stack trace:
```
 FATAL EXCEPTION: main
 Process: mohitkanwal.com.examplerealm, PID: 28687
 java.lang.RuntimeException: Unable to start activity
ComponentInfo{mohitkanwal.com.examplerealm/mohitkanwal.com.examplerealm.MainActivity}:\
java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3119)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
     at android.app.ActivityThread.access$1000(ActivityThread.java:198)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:145)
     at android.app.ActivityThread.main(ActivityThread.java:6837)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
  Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
     at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
     at io.realm.internal.SharedGroup.<init>(SharedGroup.java:68)
     at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
     at io.realm.BaseRealm.<init>(BaseRealm.java:87)
     at io.realm.Realm.<init>(Realm.java:151)
     at io.realm.Realm.createAndValidate(Realm.java:279)
     at io.realm.Realm.create(Realm.java:247)
     at io.realm.Realm.getInstance(Realm.java:219)
     at mohitkanwal.com.examplerealm.ContactHelper.getMeARealmFile(ContactHelper.java:53)
     at mohitkanwal.com.examplerealm.ContactHelper.getAllContacts(ContactHelper.java:64)
     at mohitkanwal.com.examplerealm.MainActivity.onCreate(MainActivity.java:25)
     at android.app.Activity.performCreate(Activity.java:6500)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218) 
```

Is the `SharedGroupManager.compact()` implementation compatible with the new format of the Realm File? Right now it seems to be unusable with any Realm created by `v0.83` or `v0.82.2` 

Regards
Mohit

**Comment by dalinaum** [comment] 2015-10-13 02:37
Hello @creativepsyco I can reproduce this probem too. We are investigating this.

**Comment by creativepsyco** [comment] 2015-10-13 02:57
:+1:  Sounds good.

**Comment by kneth** [comment] 2015-10-13 05:45
@creativepsyco When you don't call `Realm.compactRealm()` everything is fine, right? We are currently investigating the underlying method in the storage engine. My recommendation is to disable compaction. I hope we will be able to release a patch to fix it.

**Comment by creativepsyco** [comment] 2015-10-13 07:43
Yes everything is fine if I don't call `Realm.compactRealm()`. I suppose some format related issues with the core storage engine. Thanks for the prompt reply :+1:

**Comment by cmelchior** [comment] 2015-10-15 18:55
0.83.1 was released today with a fix for this.

**Closed by cmelchior** 2015-10-15 18:55 UTC
Labels: bug, P1

**Comment by creativepsyco** [comment] 2015-10-16 03:27
:+1: Verified and it works.

**Comment by erichkleung** [comment] 2015-12-16 19:28
Hi, I'm running into this problem with 0.86.0.  Old Realm was dropped and new one was created on this version.  

```

Fatal Exception: java.lang.RuntimeException: Unable to create application com.company.myapp.app: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5116)
       at android.app.ActivityThread.access$1600(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
       at io.realm.internal.SharedGroup.nativeCreate(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:71)
       at io.realm.internal.SharedGroupManager.compact(SharedGroupManager.java:174)
       at io.realm.BaseRealm.compactRealm(BaseRealm.java:547)
       at io.realm.Realm.compactRealm(Realm.java:1095)
       at com.company.myapp.app.checkForMigration(app.java:122)
       at com.company.myapp.app.onCreate(app.java:91)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5113)
       at android.app.ActivityThread.access$1600(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Answers Events Handler1
 raw
libcore.io.Posix.writeBytes (Posix.java)
java.io.RandomAccessFile.write (RandomAccessFile.java:673)
io.fabric.sdk.android.services.common.QueueFile.initialize (QueueFile.java:217)
io.fabric.sdk.android.services.common.QueueFile.<init> (QueueFile.java:130)
io.fabric.sdk.android.services.events.QueueFileEventStorage.rollOver (QueueFileEventStorage.java:86)
io.fabric.sdk.android.services.events.EventsFilesManager.rollFileOver (EventsFilesManager.java:114)
io.fabric.sdk.android.services.events.EnabledEventsStrategy.rollFileOver (EnabledEventsStrategy.java:100)
io.fabric.sdk.android.services.events.TimeBasedFileRollOverRunnable.run (TimeBasedFileRollOverRunnable.java:41)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:422)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun (ExecutorUtils.java:75)
io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run (BackgroundPriorityRunnable.java:30)
java.lang.Thread.run (Thread.java:818)
Queue
 raw
java.lang.Object.wait (Object.java)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:197)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:236)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:65)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:46)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.lang.Thread.run (Thread.java:818)
pool-1-thread-1
 raw
java.lang.Object.wait (Object.java)
java.lang.Thread.run (Thread.java:818)
com.mixpanel.android.AnalyticsWorker
 raw
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.HandlerThread.run (HandlerThread.java:61)
ReferenceQueueDaemon
 raw
java.lang.Object.wait (Object.java)
java.lang.Thread.run (Thread.java:818)
main
 raw
java.lang.Object.wait (Object.java)
java.util.concurrent.FutureTask.get (FutureTask.java:174)
com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException (CrashlyticsExecutorServiceWrapper.java:44)
com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException (CrashlyticsUncaughtExceptionHandler.java:275)
java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:693)
java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:690)
Queue
 raw
java.lang.Object.wait (Object.java)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:197)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:236)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:65)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:46)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.lang.Thread.run (Thread.java:818)
FinalizerDaemon
 raw
java.lang.Object.wait (Object.java)
java.lang.Thread.run (Thread.java:818)
Crashlytics Exception Handler1
 raw
dalvik.system.VMStack.getThreadStackTrace (VMStack.java)
java.lang.Thread.getAllStackTraces (Thread.java:522)
com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent (CrashlyticsUncaughtExceptionHandler.java:1010)
com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal (CrashlyticsUncaughtExceptionHandler.java:395)
com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException (CrashlyticsUncaughtExceptionHandler.java:298)
com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$200 (CrashlyticsUncaughtExceptionHandler.java:56)
com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$7.call (CrashlyticsUncaughtExceptionHandler.java:278)
com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$7.call (CrashlyticsUncaughtExceptionHandler.java:275)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun (ExecutorUtils.java:75)
io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run (BackgroundPriorityRunnable.java:30)
java.lang.Thread.run (Thread.java:818)
HeapTrimmerDaemon
 raw
java.lang.Object.wait (Object.java)
java.lang.Thread.run (Thread.java:818)
Queue
 raw
java.lang.Object.wait (Object.java)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:197)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:236)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:65)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:46)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.lang.Thread.run (Thread.java:818)
FinalizerWatchdogDaemon
 raw
java.lang.Object.wait (Object.java)
java.lang.Thread.run (Thread.java:818)
GCDaemon
 raw
dalvik.system.VMRuntime.waitForConcurrentGCRequest (VMRuntime.java)
java.lang.Thread.run (Thread.java:818)
pool-6-thread-1
 raw
java.lang.Object.wait (Object.java)
java.lang.Thread.run (Thread.java:818)
Queue
 raw
java.lang.Object.wait (Object.java)
java.util.concurrent.PriorityBlockingQueue.take (PriorityBlockingQueue.java:510)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation (DependencyPriorityBlockingQueue.java:197)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.get (DependencyPriorityBlockingQueue.java:236)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:65)
io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take (DependencyPriorityBlockingQueue.java:46)
java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1035)
java.lang.Thread.run (Thread.java:818)
Queue
 raw
java.lang.Object.wait (Object.java)
java.util.concurrent.FutureTask.get (FutureTask.java:162)
com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException (CrashlyticsExecutorServiceWrapper.java:47)
com.crashlytics.android.core.CrashlyticsCore.markInitializationStarted (CrashlyticsCore.java:796)
com.crashlytics.android.core.CrashlyticsCore.doInBackground (CrashlyticsCore.java:342)
com.crashlytics.android.core.CrashlyticsCore.doInBackground (CrashlyticsCore.java:59)
io.fabric.sdk.android.InitializationTask.doInBackground (InitializationTask.java:63)
io.fabric.sdk.android.InitializationTask.doInBackground (InitializationTask.java:28)
io.fabric.sdk.android.services.concurrency.AsyncTask$2.call (AsyncTask.java:311)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.lang.Thread.run (Thread.java:818)
```

**Comment by kneth** [comment] 2015-12-17 08:57
The `Invalid format of Realm file.` message indicate that the Realm file is damaged in some way. Can you elaborate a bit on your setup?

**Comment by erichkleung** [comment] 2015-12-17 09:01
We had a previous version of Realm installed, and decided it would be easier to drop the old Realm and create a new one.  

This is what we do immediately prior to attempting to compact Realm.  

```
        RealmConfiguration oldRealm = new RealmConfiguration.Builder(this)
                .name("default.realm")
                .build();

        boolean needToRebuildRealm = false;
        File f = new File(getFilesDir().getAbsolutePath(), "default.realm");
        if (f.exists()) {
            FSLog.log("old realm exists, will be rebuilding");
            needToRebuildRealm = true;
        }

        Realm.deleteRealm(oldRealm);

        RealmConfiguration.Builder builder = new RealmConfiguration.Builder(this)
                .name("cache")
                .migration(new MigrationToLatest())
                .schemaVersion(MigrationToLatest.LATEST_VERSION);

        RealmConfiguration realmConfiguration = builder.build();
        Realm.setDefaultConfiguration(realmConfiguration);
```

I'm not really sure how I can help elaborate on the setup, what exactly are you looking for?

**Comment by kneth** [comment] 2015-12-17 09:08
The error happens when you call `compactRealm()`. How do you call that method?

**Comment by erichkleung** [comment] 2015-12-17 09:10
Oh, immediately below the block above with this: 

```
Realm.compactRealm(realmConfiguration);
```

**Comment by kneth** [comment] 2015-12-17 12:16
@erichkleung I have tried to reproduce your case without luck. Please take a look at #1581and tell me if my test differs from your code.

**Comment by zaki50** [comment] 2015-12-17 12:45
#1958 ?

**Comment by kneth** [comment] 2015-12-17 12:58
@zaki50 Thanks - I have updated my comment.

**Comment by LiuDeng** [comment] 2016-02-11 02:02
@kneth 
i still get this problem in io.realm:realm-android:0.87.4 if i do not use compactRealm the realm file increase fast
when will you fix this！

**Comment by cmelchior** [comment] 2016-02-11 06:21
Hi @LiuDeng. This issue is unrelated to any file size increase. Please create a new issue with all relevant information instead.

**Comment by LiuDeng** [comment] 2016-02-11 06:29
@cmelchior i mean if i do not use compactRealm the realm size increase fast

**Comment by dalinaum** [comment] 2016-02-12 10:51
Hello, @LiuDeng. Could you create another issue for your problem? It would be helpful to handle your problem.

**Comment by puneetagarwal** [comment] 2016-04-11 15:14
Hello,
I am not using this method Realm.compactRealm() but still I am facing the same crash here.

Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
at io.realm.internal.SharedGroup.<init>(Unknown Source)
at io.realm.internal.SharedGroupManager.<init>(Unknown Source)
at io.realm.BaseRealm.<init>(Unknown Source)
at io.realm.Realm.<init>(Unknown Source)
at io.realm.Realm.createAndValidate(Unknown Source)
at io.realm.Realm.create(Unknown Source)
at io.realm.Realm.getDefaultInstance(Unknown Source) 

I am using Realm 0.85. 

Can you please help me with this. Thanks.

**Comment by kneth** [comment] 2016-04-12 07:20
@puneetagarwal Many things can cause this exception. For example, if you have an encrypted Realm file, and open it with the wrong key. Can you share your configuration?

**Comment by puneetagarwal** [comment] 2016-04-12 09:34
Hi Kneth,

Here is the code for my realm configuration:-

`private void configureRealm() {
        byte[] key = null;

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN_MR2) {
            SecurePreferences securePreferences = new SecurePreferences(this);

            if (!securePreferences.contains("DBAlias")) {
                // generate a key
                key = new byte[64];
                new SecureRandom().nextBytes(key);

                // store the key in the encrypted shared prefs
                securePreferences.edit().putString("DBAlias", Base64.encodeToString(key,  Base64.DEFAULT)).apply();
            } else {
                String keyString = securePreferences.getString("DBAlias", null);
                key = Base64.decode(keyString, Base64.DEFAULT);
            }
        } else {
            try {
                KeyStore keyStore = KeyStore.getInstance("AndroidKeyStore");
                keyStore.load(null);

                List<String> keyAliases = new ArrayList<>();
                Enumeration<String> aliases = keyStore.aliases();
                while (aliases.hasMoreElements()) {
                    keyAliases.add(aliases.nextElement());
                }

                SharedPreferences sharedPreferences = getSharedPreferences("DBPrefs", Context.MODE_PRIVATE);

                if (!keyStore.containsAlias("DBAlias")) {
                    // create a keystore alias
                    Calendar start = Calendar.getInstance();
                    Calendar end = Calendar.getInstance();
                    end.add(Calendar.YEAR, 1);
                    KeyPairGeneratorSpec spec = new KeyPairGeneratorSpec.Builder(this)
                            .setAlias("DBAlias")
                            .setSubject(new X500Principal("CN=Sample Name, O=Android Authority"))
                            .setSerialNumber(BigInteger.ONE)
                            .setStartDate(start.getTime())
                            .setEndDate(end.getTime())
                            .build();
                    KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA", "AndroidKeyStore");
                    generator.initialize(spec);

                    KeyPair keyPair = generator.generateKeyPair();
                    RSAPublicKey publicKey = (RSAPublicKey) keyPair.getPublic();

                    // generate a key
                    key = new byte[64];
                    new SecureRandom().nextBytes(key);

                    // encrypt the new key
                    Cipher input = Cipher.getInstance("RSA/ECB/PKCS1Padding", "AndroidOpenSSL");
                    input.init(Cipher.ENCRYPT_MODE, publicKey);

                    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
                    CipherOutputStream cipherOutputStream = new CipherOutputStream(outputStream, input);
                    cipherOutputStream.write(key);
                    cipherOutputStream.close();

                    // store the encrypted key in the shared prefs
                    sharedPreferences.edit().putString("DBAlias", Base64.encodeToString(outputStream.toByteArray(), Base64.DEFAULT)).apply();
                } else {
                    String encryptedString = sharedPreferences.getString("DBAlias", null);

                    if (encryptedString != null) {
                        KeyStore.PrivateKeyEntry privateKeyEntry = (KeyStore.PrivateKeyEntry) keyStore.getEntry("DBAlias", null);

                        Cipher output = Cipher.getInstance("RSA/ECB/PKCS1Padding");
                        output.init(Cipher.DECRYPT_MODE, privateKeyEntry.getPrivateKey());

                        CipherInputStream cipherInputStream = new CipherInputStream(new ByteArrayInputStream(Base64.decode(encryptedString, Base64.DEFAULT)), output);
                        List<Byte> values = new ArrayList<>();
                        int nextByte;
                        while ((nextByte = cipherInputStream.read()) != -1) {
                            values.add((byte) nextByte);
                        }

                        key = new byte[values.size()];
                        for (int i = 0; i < key.length; i++) {
                            key[i] = values.get(i);
                        }
                    }
                }

            } catch (NoSuchAlgorithmException |
                    KeyStoreException |
                    CertificateException |
                    IOException |
                    NoSuchProviderException |
                    InvalidAlgorithmParameterException |
                    InvalidKeyException |
                    UnrecoverableEntryException |
                    NoSuchPaddingException e) {
                e.printStackTrace();
            }
        }

        RealmConfiguration config = null;
        if (key != null) {
            config = new RealmConfiguration.Builder(getApplicationContext())
                    .encryptionKey(key)
                    .schemaVersion(AppRealmMigration.REALM_VERSION) // Must be bumped when the schema changes
                    .deleteRealmIfMigrationNeeded()
                    .migration(new AppRealmMigration()) // Migration to run
                    .build();
        } else {
            config = new RealmConfiguration.Builder(getApplicationContext())
                    .schemaVersion(AppRealmMigration.REALM_VERSION) // Must be bumped when the schema changes
                    .deleteRealmIfMigrationNeeded()
                    .migration(new AppRealmMigration()) // Migration to run
                    .build();
        }

        Realm.setDefaultConfiguration(config);
    }`

I just added `deleteRealmIfMigrationNeeded ()` method to resolve this issue in case if there is any issue with the DB migration. Does it helped you to understand if I am doing something wrong.
Thanks.

**Comment by kneth** [comment] 2016-04-12 12:49
`deleteRealmIfMigrationIsNeeded` will delete your Realm file, and all (Realm) data will be wiped.

If you can reproduce it on your local devices, it might be useful to log the key to see if you get the exact key every time.

**Comment by puneetagarwal** [comment] 2016-04-13 11:26
I tried to reproduce this issue at our end and it's not crashing but it crashes in the play store version only on some devices. 

Is this possible that if I use `deleteRealmIfMigrationIsNeeded()` and `migration()` methods at the same time while creating Realm configuration, it throws this exception "IllegalArgumentException: Illegal Argument: Invalid format of Realm file." 

Hope to hear from you soon. Thanks.
