### ISSUE TITLE
SecretKey

### ISSUE THREAD

**Issue by GavinThePacMan** [realm/realm-java#1306] opened 2015-07-20 09:12 UTC
Hi there! 

I am just wondering whether there is a plan to implement the use of the SecretKey java object for encryption?

Cheers,
Gavin

**Comment by emanuelez** [comment] 2015-07-20 09:30
Hello, there is no plan for it at the moment, but because of your feedback we will look into it! :)
Thank you very much!

**Comment by GavinThePacMan** [comment] 2015-07-20 09:34
Thank you very much! Unfortunately, the newest M preview has broken access to raw bytes from the keystore. 

I am unsure of how your encryption works, I have tried to find it in your source but I think it may be in the closed-source core. Is that correct? If that's not the case, could you point me to the code that deals with encryption? I'd love to help out!

Thanks again.

**Comment by emanuelez** [comment] 2015-07-20 09:43
You are correct: the encryption is handled in the core and the binding simply forwards the key to it.
Thank you for the valuable input! How about using secretKey.getEncoded[] to get the byte array?

**Comment by GavinThePacMan** [comment] 2015-07-20 09:45
Ah okay, well, if I can do anything else to help, let me know!

Unfortunately that just returns ``null`` in the latest Android M preview!

**Comment by emanuelez** [comment] 2015-07-20 09:47
`SecretKey` returns null if the encoding is not supported by the key. Is it possible they simply removed some encoders? Which one are you using?

**Comment by GavinThePacMan** [comment] 2015-07-20 10:03
This is the code I am using at the moment. I got it from here: http://nelenkov.blogspot.ie/2015/06/keystore-redesign-in-android-m.html

``
// key generation
KeyGenParameterSpec.Builder builder = new KeyGenParameterSpec.Builder("key1",
        KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT);
KeyGenParameterSpec keySpec = builder
        .setKeySize(256) //I know realm uses 64 bit but the lowest is 128. This doesn't make a difference anyway. Still returns null at 128
        .setRandomizedEncryptionRequired(true)
        .setUserAuthenticationRequired(true)
        .setUserAuthenticationValidityDurationSeconds(5 * 60)
        .build();
KeyGenerator kg = KeyGenerator.getInstance("AES", "AndroidKeyStore");
kg.init(keySpec);
SecretKey key = kg.generateKey();
Log.d("KEY", Arrays.toString(key.getEncoded()));    
``

I have tried changing multiple parameters of the KeySpec and KeyGenerator all to no avail. Would love some help on this.

Thanks!

**Comment by emanuelez** [comment] 2015-07-20 21:12
What if in the builder you only set the key size and nothing else? The `UserAuthenticationRequired` section might have some influence on the outcome

**Comment by GavinThePacMan** [comment] 2015-07-21 09:30
Still null unfortunately! :( Although, to be honest, I do require user authentication anyway.

**Comment by GavinThePacMan** [comment] 2015-07-28 13:11
Hey guys! Just wondering if you have tested this at all internally? Thanks, Gavin

**Comment by nhachicha** [comment] 2015-08-03 13:34
Hi @GavinThePacMan 
I did a quick test with 2 version of Android:

```java
kg = KeyGenerator.getInstance("AES", "AndroidKeyStore”);
```

throw `NoSuchAlgorithmException` on android 5.x & M, I guess the provider is not installed? 
(check this http://stackoverflow.com/questions/29310199/java-security-nosuchalgorithmexception-keygenerator-aes-implementation-not-foun).

in the other hand 
```java
kg = KeyGenerator.getInstance("AES");
```
works for both 5.x & M (with no null `key.getEncoded()`)

Hope this will help.

Cheers,

**Comment by GavinThePacMan** [comment] 2015-08-05 14:34
Hi @nhachicha 

Many thanks for your reply.

That does work to generate the key. However, my main problem is that I want to be able to store it in the Android KeyStore. By removing the `"AndroidKeyStore"`, it removes that ability.

Thanks again,
Gavin

**Comment by nhachicha** [comment] 2015-08-07 11:46
Hi @GavinThePacMan 
actually  `"AndroidKeyStore"` is a provider of asymmetric keys only (private-public). You can't get a symmetric key like `AES` from it. 
```java
kg = KeyGenerator.getInstance("AES", "AndroidKeyStore”);
``` 
should not work for `AES` but 
```java
KeyPairGenerator.getInstance("RSA", "AndroidKeyStore");
```
should, since we're requesting an asymmetric key `RSA`

BTW where did you hear about Android M breaking access to raw bytes? is it reported here https://code.google.com/p/android-developer-preview/issues/list?can=2&q=Type%3DDefect+&colspec=ID+Type+Status+Owner+Summary+Stars&cells=tiles ?

didn't find anything related here either http://developer.android.com/preview/support.html#preview2-notes

Cheers,

**Comment by cotfas** [comment] 2015-09-09 15:58
https://sourcedna.com/blog/20150730/app-crashes-on-android-m.html

**Comment by kneth** [comment] 2015-09-23 12:54
@cotfas Did you mean https://sourcedna.com/blog/20150806/predicting-app-crashes-on-android-m.html?

We have a work-around for this already in place.

**Comment by cotfas** [comment] 2015-09-23 13:16
:+1:

**Comment by cmelchior** [comment] 2015-09-23 16:28
Closing this issue then as OP's question is answered and the later issue is resolved. Please reopen if that is not the case.

**Closed by cmelchior** 2015-09-23 16:28 UTC
Labels: enhancement

**Comment by wickermoon** [comment] 2017-02-21 09:34
The links provided by cotfas and kneth don't work anymore and I can't seem to find the work-around anywhere else. Could you please post the work-around here, as the KeyStore does not allow symmetric keys to be exported. You can still use the SecretKey with a Cipher, but getEncoded() will always return null. :(

**Comment by GavinPacini** [comment] 2017-02-21 09:55
Our workaround is to just not encrypt data in Realm anymore... sucks, I know. The issue is the secure element doesn't allow raw byte access from the key store (as it shouldn't) and earlier workarounds were using undocumented APIs and loading raw bytes into memory.

I think Realm needs to change their encryption to take in a `SecretKey` and then use a `Cipher` instance under the hood (as Android's implementation of this will handle the secure element).

**Comment by wickermoon** [comment] 2017-02-21 10:28
While that seems to be the best option, have you taken a look at the SecurePreferences project at https://www.codeproject.com/articles/549119/encryption-wrapper-for-android-sharedpreferences ?

For the moment I'm storing my two keys in this encrypted version of the SharedPrefs file, but as you say that is only a (shoddy) work-around at best and should be fixed by realm using SecretKeys. :/

**Comment by GavinPacini** [comment] 2017-02-21 10:46
I haven't seen that but we had the idea of essentially implementing that and decided it wouldn't really make a difference as the key-encrypting-key is still there in raw bytes in memory.

It's definitely better than nothing but for our application it didn't matter enough.

I would like to have a go at changing Realm to use SecretKeys but I think it would be a huge endeavour. If I have time over the weekend I'll take a look.

**Comment by nhachicha** [comment] 2017-02-21 14:07
Hello @GavinPacini @wickermoon 

We can't initialise a Cipher with the provided SecretKey, as the encryption doesn't happen at the Java level (no call to `cipher.doFinal`)

If you want maximum security you can leverage the Android Keystore to do the following:

 - Generate an asymmetric RSA key, that will be stored/retrieved securely by Android, on  >= M the system requires user PIN (or finger print) for example to unlock the KeyStore, so even on rooted devices you have an extra layer of security

- Using the generated asymmetric key, generate a symmetric key (ex AES)

- Encrypt the AES key using your RSA key 

- Now it's _safe_ to store the encrypted AES key (in a SharedPref for example)

- When you need to use your encrypted Realm, retrieve your encrypted AES key, decrypt using the the RSA key then passing to the RealmConfiguration 

We did implement similar steps for this library if you need an end-to-end example 
https://github.com/realm/realm-android-user-store

Here's an example using the fingerprint API as well:
https://github.com/realm/realm-java/tree/feature/example/store_password/examples/StoreEncryptionPassword

I would not recommend using the SecurePreferences approach as it just stores the clear AES key inside an internal SecurePreferences
`SecurePreferences.sFile.edit().putString(key, value).commit();`

Cheers,

**Comment by abhyudayasrinet** [comment] 2017-12-05 16:13
@nhachicha 
That's what I tried. But to encrypt the AES key using the RSA key, we need to execute it through

`           Cipher cipher = Cipher.getInstance("RSA");
            cipher.init(Cipher.ENCRYPT_MODE, publicKey);
            byte[] encryptedBytes = cipher.doFinal(aesKey.getEncoded());`

but aesKey.getEncoded() returns null.

**Comment by thedoctor** [comment] 2018-02-24 00:37
@abhyudayasrinet  
> but aesKey.getEncoded() returns null.

That's because you're still generating the AES key via the `AndroidKeyStore`. 
The android keystore will not export AES keys, which is why @nhachicha suggested using the keystore-backed RSA key to encrypt a **non-keystore-backed** AES key.

So your code will work if you generate the AES key with `kg = KeyGenerator.getInstance("AES");` instead of `kg = KeyGenerator.getInstance("AES", "AndroidKeyStore");`
BUT note, you must still use `kg = KeyGenerator.getInstance("RSA", "AndroidKeyStore");` for the keystore-backed key that will encrypt the AES realm master key.

But I would also point out that there's no need to use an RSA key at all, you can use a keystore-backed AES key (which you will never export) to encrypt ANOTHER AES key for Realm. Symmetric encryption is preferable in this situation.

Note, the code below is UNTESTED:
```java
// Generate the keystore key (only used to encrypt your Realm master key)
KeyGenerator secureKg = KeyGenerator.getInstance("AES", "AndroidKeyStore");
secureKg.init(/* your KeyGenParameterSpec */);
SecretKey keystoreBackedWrapperKey = secureKg.generateKey();

// Generate the Realm master key
KeyGenerator lessSecureKg = KeyGenerator.getInstance("AES");
lessSecureKg.init(/* your KeyGenParameterSpec */);
SecretKey softwareRealmKey = lessSecureKg.generateKey();

// Encrypt the Realm master key with the 
Cipher cipher = Cipher.getInstance("AES"); 
cipher.init(Cipher.ENCRYPT_MODE, keystoreBackedWrapperKey); 
byte[] encryptedRealmKey = cipher.doFinal(softwareRealmKey.getEncoded());

// Then you can store the encryptedRealmKey in SharedPrefs or wherever, and decrypt it with the keystoreBackedWrapperKey whenever you need to initialize Realm. 
// Also, it looks like you're using random IVs, so make sure to store cipher.getIv() as well!
```
