### ISSUE TITLE
Search over RealmResults is unstable (realm 0.80.1)

### ISSUE THREAD

**Issue by funbringer** [realm/realm-java#1063] opened 2015-04-23 12:54 UTC
I've got a Contact class which has fields for first name etc. I've been trying to search through contact list provided by _RealmQuery_:

```
RealmQuery<ContactData> query = ContactRealmAdapter.this.realmResultsContacts.where();

switch (name.length) {
    case 1:
        query
              .beginsWith("firstName", name[0]).or()
              .beginsWith("patronym", name[0]).or()
              .beginsWith("lastName", name[0]);
        break;
....
}

ContactRealmAdapter.this.realmResultsContacts =
                            query.findAllSorted("lastName", true);
```

As you can see,  _String[] name_ contains person's name split by whitespaces, all names are written in cyrillic symbols (UTF-8). The problem is that _RealmResults_ is empty when _name[0]_ begins with some of cyrillic symbols (for example, К), for no particular reason. I am aware of the fact that case insensitive string matches in queries are only supported for certain character sets, so that's not the problem.

When I tried to query contacts directly through Realm instance, search worked perfectly. It also works when I search by one criteria, for example:

```
query.beginsWith("lastName", name[0])
```

**Comment by emanuelez** [comment] 2015-04-23 13:40
Can you please provide a valid instance of a name that does not work so that we can try to replicate the issue with your specific use-case?

**Comment by funbringer** [comment] 2015-04-23 20:50
Turns out these conditions are not sufficient to reproduce the bug, so I haven't make up simple demo yet.  In fact, I could've provided your with detailed source code of my project, but I appreciate your time, so I'll try to investigate this issue a little deeper. I'll add my results later.

**Comment by funbringer** [comment] 2015-04-24 00:58
Finally I'm able to describe issue properly. I'm developing an application which inter alia allows user to view department hierarchy of my university, including contacts. You shouldn't care about legal issues, whole data set is public. I'm merely collecting it from official website. I've uploaded DB backup (https://drive.google.com/open?id=0B_LfygiADEzlVVJ5WVVlRmtkdzQ&authuser=0), so you can reproduce bug.

DB stores two kinds of instances: ContactData and ContactGroupData, the latter contains information about hierarhy level. Contacts belong to groups, groups may also belong to groups (recursive relations are allowed, in fact, they exist).

I've noticed that these two queries produce quite different results:

1st:
```
realm
        .where(ContactData.class)
        .equalTo("groups.id", 1502)
        .findAllSorted("lastName", true)
        .where()
        .beginsWith("firstName", "С").or()
        .beginsWith("patronym", "С").or()
        .beginsWith("lastName", "С")
        .findAll()
```

2nd:
```
realm
        .where(ContactData.class)
        .equalTo("groups.id", 1502)
        .findAll()
        .where()
        .beginsWith("firstName", "С").or()
        .beginsWith("patronym", "С").or()
        .beginsWith("lastName", "С")
        .findAll()
```

1st query drops one of the contacts (_Олег Алексеевич Савонюк_), while 2nd returns both (_Олег Алексеевич Савонюк_, _Сергей Алексеевич Приведенцев_). Each contact has part of name which begins with cyrillic char C.

**Comment by cmelchior** [comment] 2015-04-24 10:20
Hi @funbringer 

Thank you for the database and reproduction case.

Sorting cyrillic characters are currently not supported (see http://realm.io/docs/java/#current-limitations). It is something we want to support though ( #1031 ).  That said, that the result sets are different in number doesn't sound right. We will look into it.

**Comment by rrrlasse** [comment] 2015-05-22 14:17
Is this issue solved? @kneth @cmelchior @emanuelez

**Comment by cmelchior** [comment] 2015-05-22 14:19
No it isn't

**Comment by kneth** [comment] 2015-05-22 14:20
It is not solved  but documented as a limitation. At some point we should investigate hos to use ICU for sorting.

**Comment by rrrlasse** [comment] 2015-05-22 15:07
That the sorting order is wrong is expected. I was worrying about the missing search result. I'll look into that now.

**Comment by rrrlasse** [comment] 2015-05-27 11:34
@funbringer We are unable to reproduce the missing search result in your 1'st query. Both queries give us 2 search results.

Are you sure you havn't made any copy/paste mistakes that could have transformed the cyrillic С into latin C? 

Also note that all text in your database is stored in UTF-8 format (the С is stored as the bytes pair 0xd0, 0xa1). However, some Java editors can save source code files in other formats (such as UTF-16), and give some mismatch.

**Comment by kneth** [comment] 2015-06-04 11:50
@funbringer Did you have a chance to check if the cyrillic C wasn't translated to latin C in your test?

**Comment by kneth** [comment] 2015-06-09 12:44
@funbringer I have been able to reproduce the issue using your Realm file (and the derived classes) and our current release. I have also tried with our snapshot release of today, and I cannot reproduce it with that.

I believe that you have reported the same bug as https://github.com/realm/realm-cocoa/issues/1863. It has been fixed by our core team. This explains why @rrrlasse wasn't able to reproduce it as he was using a Realm Core with the fix. I'm sorry that we didn't realize that it was the same bug.

Please try our snapshot release (see the `README.md` file for details). If the issue is still occurring, I ask you to open a new issue.

**Closed by kneth** 2015-06-09 12:44 UTC
Labels: bug

**Comment by funbringer** [comment] 2015-06-10 23:44
Thanks, everything seems to work just right. Keep up the good work.

**Comment by kneth** [comment] 2015-06-11 08:07
I'm happy to hear that it works.
