### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lawloretienne** [realm/realm-java#1863] opened 2015-11-30 23:40 UTC
The following crash is happening on 
Android 4.2.2
Android 4.4.2
Android 4.4.4

    Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "librealm-jni.so" (built with --hash-style=gnu?)
           at java.lang.Runtime.loadLibrary(Runtime.java:365)
           at java.lang.System.loadLibrary(System.java:526)
           at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:117)
           at io.realm.internal.SharedGroup.<clinit>(SharedGroup.java:42)
           at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:44)
           at io.realm.BaseRealm.<init>(BaseRealm.java:90)
           at io.realm.Realm.<init>(Realm.java:153)
           at io.realm.Realm.createAndValidate(Realm.java:280)
           at io.realm.Realm.create(Realm.java:244)
           at io.realm.Realm.getInstance(Realm.java:217)
           at io.realm.Realm.getInstance(Realm.java:182)

**Comment by beeender** [comment] 2015-12-01 03:56
Which Realm version are you using? And what kind of device are you testing with? Is it 100% reproducible on those devices? This is a new issue we haven't met before, very strange.

PS. Similar issue on SO http://stackoverflow.com/questions/28638809/android-ndk-unsatisfiedlinkerror-dlopen-failed-empty-missing-dt-hash

**Comment by lawloretienne** [comment] 2015-12-01 04:51
This is happening on Realm version 0.84.2 .  I cannot reproduce it on my devices but my users are experiencing this crash according to Crashlytics reports.

It is happening on the following devices

Samsung SCH I535
Samsung SGH T399N
Samsung SM N910F
Acer A1 840FHD
BLU DASH JR 4 0 K

**Comment by cmelchior** [comment] 2015-12-01 07:55
@beeender Maybe it is related to this? https://github.com/realm/realm-java/pull/1771

**Comment by kneth** [comment] 2015-12-02 09:39
I am sure that the default hash-style of NDK is sysv - Android's runtime linker does not support the gnu style. But to be certain, we could add the hash-style to our build files, and set it to both. Android AOSP did that recently (see https://android-review.googlesource.com/#/c/149951/)

@lawloretienne Is it possible that the users who experience this crash, is using a custom ROM? By reading http://www.windowsxlive.net/compile-xperia-ztablet-z-cm10-2-rom-with-full-linaro-4-8-including-o3-strict-aliasing-optimizations/ I can see that custom ROMs might use another hash style than the default one.

@beeender Don't you think we should set the hash style to "both"?

**Comment by beeender** [comment] 2015-12-02 11:26
@kneth I don't think use `both` for `hash-style` will solve this particular issue :disappointed: 

The bionic linker introduced the gnu hash style in 5.0 by this commit https://android-review.googlesource.com/#/c/113978/7/linker/linker.cpp

And we can see from the crash report and the log "dlopen failed: empty/missing `DT_HASH in`", those problematic devices doesn't have this commit to enable gnu style hash. (Otherwise the log should be "empty/missing `DT_HASH/DT_GNU_HASH` in ")

And because of this https://android-review.googlesource.com/#/c/139360/ , enable both might not be a good idea for now...

**Comment by beeender** [comment] 2015-12-02 11:28
@lawloretienne Is it possible for you to get one of those problematic devices to reproduce the issue?

**Comment by beeender** [comment] 2015-12-02 11:36
@lawloretienne One more question, is it the first time you met this issue? Did you make a release with an older version Realm before? Does it ever happen to an other version of Realm?

**Comment by lawloretienne** [comment] 2015-12-02 17:58
@beeender  I have not seen this specific crash with an earlier version of Realm.  Unfortunately I don't have access to the problematic devices.  If I had to buy a device for every different crash my users experienced I would be broke.

**Comment by beeender** [comment] 2015-12-04 05:40
@lawloretienne Totally understand you don't have access to the problematic devices :)

I just went though the recent changes in Realm side, none of them could be related with this issue.
Two more thing might be helpful:

1. Did you notice that the crash numbers (because of this) is increasing recently? I want to know if it is just random issue of the specific device.
2. Did you add other native libs with this release?

**Comment by beeender** [comment] 2015-12-04 05:57
PS.:

Some version of Android has bugs with PakcageManager, which doesn't update the so libs while updating the apk file. I did the test to simulate the issue, but in that case, the crash log would be something like `Native method not found:` . Hash checking is in the very early stage of bionic lib loader, even with an old so lib, that part should not fail.

http://cplusplusio0.blogspot.ru/2015/02/android-ndk-unsatisfiedlinkerror-failed.html here is another guy suffering the similar problem, who has not find the root cause either...

**Comment by beeender** [comment] 2016-01-21 08:32
With ReLinker merged to `0.88-SNAPSHOT` which might solve this issue i'll close this issue now. Please reopen if the problem persists.

**Closed by beeender** 2016-01-21 08:32 UTC
Labels: Help, Pending
