### ISSUE TITLE
Realm: On client side never call method onChange(RealmResults<PermissionOfferResponse> permissionOfferResponses)

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5182] opened 2017-09-01 13:08 UTC
Server side.
On server side I get new token and use it on client side.
Here code of generate new token.

`public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        init();
    }

    private void init() {
        Realm.init(this);
        loginAndRealmConfig();
    }

    private void loginAndRealmConfig() {
        SyncUser.Callback callback = new SyncUser.Callback() {
            @Override
            public void onSuccess(SyncUser user) {
                SyncConfiguration syncConfig = new SyncConfiguration.Builder(user, REALM_URL).build();
                Realm.setDefaultConfiguration(syncConfig);

                createToken(user, new PermissionOffer(REALM_URL, true, false, false, null));
            }

            @Override
            public void onError(ObjectServerError error) {
            }
        };

        SyncCredentials syncCredentials = SyncCredentials.usernamePassword(
                BuildConfig.USER_NAME, BuildConfig.PASSWORD, false);
        SyncUser.loginAsync(syncCredentials, AUTH_URL, callback);
    }

    private void createToken(SyncUser syncUser, final PermissionOffer permissionOffer) {
        Realm managementRealm = syncUser.getManagementRealm();
        managementRealm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.insert(permissionOffer);
            }
        });

        // Wait for server to handle the offer
        RealmResults<PermissionOffer> permissionOfferRealmResults = managementRealm.where(PermissionOffer.class)
                .equalTo("statusCode", 0)
                .findAll();

        permissionOfferRealmResults.addChangeListener(new RealmChangeListener<RealmResults<PermissionOffer>>()) {
            @Override
            public void onChange(final RealmResults<PermissionOffer> offers) {
        for (int index = 0; index < offers.size(); index++) {
                    PermissionOffer currentOffer = offers.get(index);
                    String token = currentOffer.getToken(); // send to client
            }
        });
    }
}

This code is success work. OK.
As result in method `onChange(final RealmResults<PermissionOffer> offers) `I get new token.

E.g.: **fffffffeeeeeeeeedddddddddddddddd:11111111-222222222-3333-444444444444**

and use them on client side.

Here client (Android application) side code that use token to get _realmUrl_:

```
`public class MainApp extends MultiDexApplication {
  public void onCreate() {
        super.onCreate();
	Realm.init(this);
        loginToRealm(BuildConfig.USER_NAME, BuildConfig.PASSWORD);
 }
private void loginToRealm(final String userName, String password) {
        SyncUser.Callback callback = new SyncUser.Callback() {
            @Override
            public void onSuccess(SyncUser user) {
                SyncUser syncUser = user;
		MyService myService = new MyService(syncUser);
            }

            @Override
            public void onError(ObjectServerError error) {
            }
        };
        SyncCredentials syncCredentials = SyncCredentials.usernamePassword(userName, password, false);
        SyncUser.loginAsync(syncCredentials, AUTH_URL, callback);
    }
}`
```

Here MyService that try to get realmUrl:

```
`public class MyService {
    private Set<RealmChangeListener<RealmResults<PermissionOfferResponse>>> realmChangeListenersPermissionOfferResponse = new HashSet<>();
    public MyService(SyncUser syncUser) {
        syncWithROS(syncUser);
    }
    private void syncWithROS(SyncUser syncUser) {
        Realm managementRealm = syncUser.getManagementRealm();
	String tokenFromServer = "fffffffeeeeeeeeedddddddddddddddd:11111111-222222222-3333-444444444444";
        final PermissionOfferResponse newPermissionOfferResponse =  new PermissionOfferResponse(tokenFromServer);
        managementRealm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.insert(newPermissionOfferResponse);
            }
        });
        RealmResults<PermissionOfferResponse> realmResultPermissionOfferResponse = managementRealm
	        .where(PermissionOfferResponse.class)
                .equalTo("id", newPermissionOfferResponse.getId())
                .equalTo("statusCode", 0) 
                .findAll();
        class RealmChangeListenerImpl implements RealmChangeListener<RealmResults<PermissionOfferResponse>> {
            private RealmResults<PermissionOfferResponse> results;
            public RealmChangeListenerImpl(RealmResults<PermissionOfferResponse> results) {
                this.results = results;
                realmChangeListenersPermissionOfferResponse.add(this);
                results.addChangeListener(this);
            }
            @Override
            public void onChange(RealmResults<PermissionOfferResponse> permissionOfferResponses) {
                realmChangeListenersPermissionOfferResponse.remove(this);
                MyService.this.onChange(permissionOfferResponses);
            }
        }
        new RealmChangeListenerImpl(realmResultPermissionOfferResponse);
    }
    private void onChange(RealmResults<PermissionOfferResponse> permissionOffers) {
        PermissionOfferResponse permissionOfferResponse = permissionOffers.first();
        String realmURL = permissionOfferResponse.getRealmUrl();
    }
}`
```

The problem is that after I success login to Realm the method `onChange(RealmResults<PermissionOfferResponse> permissionOfferResponses) `is **NEVER** call.
As result I can't get _relamUrl_ to work with Realm.

What is wrong?

**Comment by Zhuinden** [comment] 2017-09-01 13:49
That's weird, I remember this code from https://stackoverflow.com/questions/45781810/realm-why-on-devices-emulators-method-realmchangelistener-onchange-not-call-e/45783323#45783323 and I thought my answer fixed it....

Maybe the problem is that:

1.) MyServer myService = new MyServer(syncUser);

You are creating `MyServer` instead of `MyService`, so it doesn't actually execute.

2.) 

``` java
            @Override
            public void onError(ObjectServerError error) {
            }
```

the `onError()` clause is completely ignored, so if you receive an error, you aren't even logging it, so you can't know if an error occurs.

**Comment by lmdic** [comment] 2017-09-01 14:05
yes, this https://stackoverflow.com/questions/45781810/realm-why-on-devices-emulators-method-realmchangelistener-onchange-not-call-e/45783323#45783323

help me before , but now It's not work. I don't known why.

1. `MyServer myService = new MyServer(syncUser);` - it's syntax error. 
In code I use 
`MyService myService = new MyService (syncUser);` - it's syntax error. 

2.  I success login on server side to Realm Object Server and success login on client side to Realm Object server.

**Comment by Zhuinden** [comment] 2017-09-01 14:17
Hm, I suspect this is more ManagementRealm specific than I am aware of its internals 😢

**Comment by lmdic** [comment] 2017-09-01 17:59
Maybe the problem is that on server side I use this filter:

` RealmResults<PermissionOffer> permissionOfferRealmResults = managementRealm.where(PermissionOffer.class)
            .equalTo("statusCode", 0)
            .findAll();`

But on client side I use another filter:

```
 RealmResults<PermissionOfferResponse> realmResultPermissionOfferResponse = managementRealm
	        .where(PermissionOfferResponse.class)
                .equalTo("id", newPermissionOfferResponse.getId())
                .equalTo("statusCode", 0) 
                .findAll();
```

My question is: 
Is on server and client side MUST use the same filter?

In my case in the client must be:

```
 RealmResults<PermissionOfferResponse> realmResultPermissionOfferResponse = managementRealm
	        .where(PermissionOfferResponse.class)
                .equalTo("statusCode", 0) 
                .findAll();
```

Is I'm right?

**Comment by Zhuinden** [comment] 2017-09-01 19:10
Honestly I have no idea how this works, but soon there will be a 3.7.0-SNAPSHOT with which you can  use the new PermissionManager API instead of the management Realm.

**Comment by Zhuinden** [comment] 2017-09-01 20:39
Actually, I think 3.7.0 was just released with the PermissionManager just after 3.6.0. Interesting.

**Comment by cmelchior** [comment] 2017-09-01 20:43
Yes, we (= me) messed up internally. The PermissionManager was intended to be part of 3.6.0.

**Comment by lmdic** [comment] 2017-09-02 13:57
This code https://stackoverflow.com/questions/45781810/realm-why-on-devices-emulators-method-realmchangelistener-onchange-not-call-e/45783323#45783323 

works as before. 

I think the problem is in the filters. 

If on client side change filter like this:

```
RealmResults<PermissionOfferResponse> realmResultPermissionOfferResponse = managementRealm
	        .where(PermissionOfferResponse.class)
                .equalTo("statusCode", 0) 
                .findAll();
```

Than method `onChange()` call success.

**Comment by cmelchior** [comment] 2017-09-06 08:39
Hi @lmdic 
Sorry for the late reply.

The listener implementation should be fine, but it looks like you are not storing the reference to the `RealmResults` which means the listener gets GC'ed and never triggered:

```
    public MyService(SyncUser syncUser) {
        syncWithROS(syncUser); // You need to store this variable until it succeed
    }
```

Also, I would recommend using the new `PermissionManager` in 3.7.0, it has a much easier interface for this through `permissionManager.acceptOffer(token, callback)`

**Comment by Zhuinden** [comment] 2017-09-06 09:21
@cmelchior he actually uses this RealmChangeListenerImpl thing which is something I wrote to retain the results until the callback is called, but it doesn't seem to be used consistently.

I do not know when exactly the change listener should be called and how you know this change is the change you were waiting for, soooo....

**Closed** 2017-09-26 02:55 UTC
Labels: T:Help
