### ISSUE TITLE
Feature: Generate (wrap) getters and setters on compilation

### ISSUE THREAD

**Issue by SleeplessByte** [realm/realm-java#935] opened 2015-03-06 22:26 UTC
Realm requires the following:

- There MUST be a getter/setter for each field
- The getter and setters SHOULD be vanilla

This is a error-prone and boilerplate process. What I would like to see is an adoption of compile-time code generation for the realm getter/setter which wraps onto any custom wrapper/setter.

The processor would search for assignment or reading of the exact field and replace it with the appropriate logic/function call.

````Java
class MyRealmObject extends RealmObject {
    private int myfield;

    public void setMyField( int value ) {
        if ( SOME_CONTANT ) {
            myfield = value + 3;
        }
    }
    
    public int getMyField() {
        return myfield - 3;
    }
}
````
Would turn into something like (at compilation):

````Java
class GeneratedProxyMyField {
    private int myfield;

    public void setMyField( int value ) {
        if ( SOME_CONTANT ) {
            setField( 'myField', value + 3; )
        }
    }
    
    public int getMyField() {
        return getFieldAsInt( 'myField' ) - 3;
    }
}
````
This way setters and getters functionality would be retained.

**Comment by emanuelez** [comment] 2015-03-06 22:52
Unfortunately annotation processors are not provided with the ability to inspect the contents of methods.
But... there are other possibilities we are exploring.

**Comment by SleeplessByte** [comment] 2015-03-07 00:10
That's unfortunate. I just read up on it.

I haven't found a pretty solution without reflection yet.

**Comment by cmelchior** [comment] 2015-03-07 06:53
This is a duplicate of https://github.com/realm/realm-java/issues/908, so closing this one. In the other issue you can also see links to some of the alternatives we are considering.

**Closed by cmelchior** 2015-03-07 06:53 UTC

**Comment by SleeplessByte** [comment] 2015-03-07 20:58
Cool. I searched for it, but apparently with the wrong parameters.
