### ISSUE TITLE
Suspicious definition of role "everyone"

### ISSUE THREAD

**Issue by jedelbo** [realm/realm-java#5817] opened 2018-03-09 09:45 UTC
I you run the Advanced ToDo app with partial sync, you will have an "everyone" role created. This role will as members have the same user twice. This could be a sign of some logic gone wrong somewhere.

**Comment by cmelchior** [comment] 2018-03-09 09:47
I think this is caused by Java adding it offline and Sync doing the same when you log into the server. I believe Sync has logic in place for cleaning it up eventually, but I could be wrong? /cc @simonask 

This should ideally be fixed by having a `RealmSet` datatype.

**Comment by cmelchior** [comment] 2018-03-09 09:48
But we should probably document the behavior until we can get such a datatype in place, but it _is_  confusing when it happens.

**Comment by simonask** [comment] 2018-03-09 09:59
Are you connecting as an admin user in either case?

**Comment by simonask** [comment] 2018-03-09 10:00
But yes, it is very likely our problem. :-)

Can you use `asyncOpen()` or the Java equivalent? This should prevent the "everyone" role from containing duplicate entries (although it is benign when it does).

**Comment by jedelbo** [comment] 2018-03-09 10:06
I am logging in as a regular user via `SyncUser.loginAsync`

**Comment by cmelchior** [comment] 2018-03-09 10:13
Login doesn't effect this as the data is only created when the Realm is opened.



Opening a Realm async (and waiting for the server to send its data first) is something like this:

```
SyncConfiguration config = new SyncConfiguration.Builder(user, url)
  .waitForInitialRemoteData()
  .build();

Realm.getInstanceAsync(config, callback);
```

**Comment by cmelchior** [comment] 2018-03-22 10:05
Until we have a proper `RealmSet` data structure, this is working as intended. For the time being the server is responsible for cleaning duplicates eventually.

**Closed by cmelchior** 2018-03-22 10:05 UTC
