### ISSUE TITLE
Realm Transformer not correctly applied to classes inside androidTest

### ISSUE THREAD

**Issue by bkromhout** [realm/realm-java#2936] opened 2016-06-03 23:18 UTC
#### Bug Details
I've just recently started trying to add instrumented tests to my application project so that I can test the portions of my code which have to do with data manipulation and persistence (which is much of the code).

I tried to start out small by adding a test class, `RBookTest` which tests just one method I have on one of my model classes, `RBook`. However, when I run the `:app:assembleDebugAndroidTest` task to assemble the test APK, Realm's bytecode transformer is causing the build to fail when it gets to this line in `RBookTest`:

```java
book1.isNew = false;
```

I've attached a log with more content in the Actual Results section, but this is the top-level failure message from Gradle:

```
Execution failed for task ':app:transformClassesWithRealmTransformerForDebugAndroidTest'.
> javassist.CannotCompileException: [source error] realmSet$isNew(boolean) not found in com.bkromhout.minerva.realm.RBook
```

I should note that I'm having absolutely no issues assembling the regular debug APK (the `:app:assembleDebug` task), and am aware of a few places which use the same sort of line as the problematic one in the test class.

#### Expected Results
I should be able to compile the test APK (using the `:app:assembleDebugAndroidTest`) in order to run instrumented tests on an Android emulator or device.

#### Actual Results
Running the `:app:assembleDebugAndroidTest` task fails. I've attached a file which contains the log output which results from running that task with the `--info` and `--stacktrace` options, but have omitted the output of all but the `:app:transformClassesWithRealmTransformerForDebugAndroidTest` task for brevity: [Log.txt](https://github.com/realm/realm-java/files/298517/Log.txt)

#### Steps & Code to Reproduce
I think the steps to reproduce the issue are fairly self-explanatory. The app's code is open source, so if you want to clone it to try and reproduce the issue, [use this link to the repo (commit hash 3366874f7b)](https://github.com/bkromhout/Minerva/tree/3366874f7b553ee802b2d31501fe3b5da491a5ab). That's the commit where I pushed the affected test class, `RBookTest`. The transformer seems to be choking when it tries to manipulate the setter on line 48 (`book1.isNew = false`).

If you just want to quickly reference the relevant files, here are links to a couple of them as of that commit:

* [`RBook` class](https://github.com/bkromhout/Minerva/blob/3366874f7b553ee802b2d31501fe3b5da491a5ab/app/src/main/java/com/bkromhout/minerva/realm/RBook.java)
* [`RBookTest` class](https://github.com/bkromhout/Minerva/blob/3366874f7b553ee802b2d31501fe3b5da491a5ab/app/src/androidTest/java/com/bkromhout/minerva/realm/RBookTest.java)

A few other possibly-relevant points of note:

* I'm using retro-lambda
* I have a copy of `TestRealmConfigurationFactory` from your own suite of tests (very cool idea btw!), and am using it as a Rule for `RBookTest` so that it doesn't interfere with the usual Realm file

**IMPORTANT EDIT** I've just realized that I was also in the process of testing a custom fork of another library called epublib around this time.
While that has no bearing whatsoever on the issue at hand, it will cause you issues if you try to import the project directly as it is at the time of that commit. In order for you to be able to import the project cleanly, you'll need to edit the `settings.gradle` file in the root of the project so that it only contains the following content:

```groovy
include ':app'
```

Sorry for the confusion!

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.1

Which Android version and device: x86 Emulator running API 23 with Google APIs

**Comment by Zhuinden** [comment] 2016-06-04 13:36
This looks like a subset of the supposedly fixed [#2703](https://github.com/realm/realm-java/issues/2703) which might still happen during tests?

    Fixed CannotCompileException when related class definition in android.jar cannot be found (#2703).

The Realm people will know what to do. Although the quick workaround would most likely be using getters/setters instead of fields

**Comment by bkromhout** [comment] 2016-06-04 13:42
@Zhuinden That was my initial thought as well, except that the log clearly says:
```
Add boot class /Users/bkromhout/android-sdk-macosx/platforms/android-23/android.jar to class pool.
```
Which I believe was the fix that was implemented for that issue. 

To me it seems more like there's some sort of mismatching going on, because while my actual `RBook` class clearly wouldn't have a `realmSet$isNew(boolean)` method in it, the generated class `RBookRealmProxy` *does* have that method, and that's what the transformer should be pointing to when it's manipulating the getters and setters.

**Comment by Zhuinden** [comment] 2016-06-04 17:07
...Ah. I think this post will help the Realm guys figure out what's up.

**Comment by cmelchior** [comment] 2016-06-08 05:21
Hi @bkromhout 
Thanks for the detailed bug report. I can reproduce the error and am looking into it now.

**Comment by cmelchior** [comment] 2016-06-08 07:28
Hi @bkromhout 
It looks like our transformer is not being correctly applied to classes inside AndroidTests.

`RBookTest.doesNotUpdateRBook()` does something like this: `book1.isNew = false;` which seems to be what is breaking. If you replace it with your own setter it works, but it is obviously still a bug on our side.

We will look into it.
`

**Comment by bkromhout** [comment] 2016-06-08 16:14
Hi @cmelchoir, I'm glad the bug report was thorough enough to help you.
Thanks for keeping me updated!

-Brenden Kromhout

**Comment by bkromhout** [comment] 2016-06-12 16:20
Hi @cmelchior, have you had a chance to look into this at all? 
No worries if not, I'm just trying to decide if I should switch all of my realm objects back to getters/setters instead of public fields until the issue is resolved.
Thanks.

**Comment by cmelchior** [comment] 2016-06-12 17:56
Hi @bkromhout 
Sorry, not yet. I got side-tracked by some other issues. But will prioritise it next week.

**Comment by cmelchior** [comment] 2016-06-17 11:46
Just a small update. I still haven't been able to narrow this down but observations so far:
- Porting your unit test and model classes to Realms unit tests works fine
- Going back to Java 7 still crashes (removing retro-lamda)
- Removing all classpath gradle plugin still crashes
- Removing 'com.bkromhout.ruqus' still crashes.

So right now I am leaning towards it is some dependency in your project that somehow does something it shouldn't, but I would very much like to find out what and why.

**Comment by bkromhout** [comment] 2016-06-17 11:56
Interesting... Thanks for the update. I'll try either this afternoon or
tomorrow to try and narrow that down. I'm curious what dependency might
cause this, the two you mentioned seemed like the biggest possible culprits.

I should mention that I am now using the latest Android Studio preview (2.2
preview 3), and I believe I was using 2.1 when I reported this (I'm
replying by email, so not easy to check). Not that that has changed
anything, but just thought you should know.

-Brenden Kromhout

**Comment by cmelchior** [comment] 2016-06-17 11:57
It isn't Android Studio, this also fails when running Gradle from the command line.

**Comment by bkromhout** [comment] 2016-06-17 12:01
Good to know, thanks. It also isn't Guava (though I doubted it would be)
because I managed to remove that dependency in the most recent commits

-Brenden Kromhout

**Comment by cmelchior** [comment] 2016-06-17 14:46
Progress. I managed to reproduce this in our own unit test example . For some reasons our androidTests that run inside the library gets transformed correctly, while it doesn't if run as part of a proper app project.

**Comment by bkromhout** [comment] 2016-06-18 00:34
Well huh, so I assume the logical next step is determining what the library project is doing differently? The unit test example has a fairly minimal set of dependencies, so are you thinking the issue lies somewhere other than the dependencies of my project?
(Somehow I didn't get an email for that comment, so I've just seen it now)

**Comment by leibovic** [comment] 2016-09-06 15:11
I am also running into this issue, although my testcase isn't as simple as the one described here. Any update on progress? Or anything I can do to help debug?

**Comment by Zhuinden** [comment] 2016-09-06 15:21
@leibovic Well an interesting question is whether the problem occurs even if you're using getters/setters (Android Studio can do Refactor -> Encapsulate Fields and replace all field access with getter/setter)

**Comment by leibovic** [comment] 2016-09-06 15:54
@Zhuinden Thanks for the quick response. Using getters/setters did indeed fix the issue, but I had to do it for all of my models (thank god for that IDE shortcut!). I'm trying to incorporate Realm into my project for the first time, is there anything I will have to consider if I'm using getters/setters instead of accessing fields directly?

**Comment by Zhuinden** [comment] 2016-09-06 16:25
It's more like the other way around. Direct field access is more fragile than using getters/setters. 

Although if you can send the project over with direct field access and the bug you can into to help[at]realm.io, that's useful for fixing it :)

**Comment by cmelchior** [comment] 2016-09-06 16:38
@leibovic Field access should work fine expect in Android Instrumentation tests as you might have discovered. There is a bug tracking it here #3030. From what we can tell it is a bug in the Google Build Tools causing it. There is an link to the issue in #3030

**Comment by cmelchior** [comment] 2017-01-26 11:19
It would be interesting to see if moving to Jack's transform API would actually solve this #3038

**Comment by geralt-encore** [comment] 2017-04-10 08:31
I have the same issue while upgrading Kotlin from `1.1` to `1.1.1`. None of my realm models is written in Kotlin tho.

**Comment by ZenoxParadox** [comment] 2017-05-01 09:46
Perhaps this is nothing, but I bumped into this very issue and tried to figure out how to resolve it and found something that might be useful. It's fairly straightforward, so here it goes;

For the record; the compile exception for me was something like `realmSet$setIID(long)`

I had a model with a `@PrimaryKey` notation on a field called IID that was a `long`, then I decided to change it into a `String`. Somehow the generated code displayed the correct result (`setIID(String)`). After trying the usual Invalidate, Invalidate and Restart I simply deleted the build directory. After that the issue was no longer present.

**Comment by easazade** [comment] 2018-12-23 14:20
thanks for your shareing @ZenoxParadox . because i have similar problem with 
my androidTest fail with this error 
```Cause: realmGet$id() not found in ir.alirezaisazade.mars.model.entities.DbComment```
and i remember doing the exact same thing as @ZenoxParadox did. i did change the primary key of some of my realmobjects from long to String. i am not exactly sure if that caused the problem.
for me deleting the build folder didn't work i had to make one of my realmobject's fields private and define getters and setters. i did not change others. now my androidTest builds succeed.

**Comment by mannodermaus** [comment] 2019-04-25 04:50
Ran into this again out of nowhere yesterday, after running Realm-based instrumentation tests worked the day before. Our model classes are written in Kotlin, and the affected fields were annotated with `@JvmField`. After removing that annotation, compilation of instrumentation tests started working again.

```kotlin
// If a class like this...
open class PersistedModel(
  @JvmField
  var aField: String = ""
) : RealmObject()
```

```
// ...causes an error like this...
javassist.CannotCompileException: [source error] realmGet$aField() not found in com.example.PersistedModel
```

```kotlin
// ..., then change your class to:
open class PersistedModel(
  var aField: String = ""
) : RealmObject()
```

**Comment by DannySe** [comment] 2019-07-17 14:17
Does it only happen during tests for you? 
I've just ran into the same issue building the app

**Comment by bmunkholm** [comment] 2021-11-30 14:29
Closing as outdated. If anyone experiences this again, please create a new issue and refer to this. Thanks!

**Closed by bmunkholm** 2021-11-30 14:29 UTC
Labels: Blocked, T-Bug-Crash, O-Community
