### ISSUE TITLE
App crashing (librealm-jni.so)

### ISSUE THREAD

**Issue by rgdev** [realm/realm-java#3794] opened 2016-11-14 17:27 UTC
Realm is working flawlessly on almost devices in our user base but one user is unable to launch the app. The screen is white and then the app closes down. I was able to get the phone having the issue and check its logs.

The issue seems to happen after or during the loading of librealm-jni.so

#### Goal

> Start app and use Realm normally

#### Expected Results

> App running 

#### Actual Results

> App crash instantly when starting (ANR)

#### Code Sample

```crash stack

> 11-14 16:54:23.320 32150-32150/? D/dalvikvm: Trying to load lib /data/app-lib/com.myapp-1/librealm-jni.so 0x4175fe08
11-14 16:54:23.343 32150-32150/? D/dalvikvm: Added shared lib /data/app-lib/com.myapp-1/librealm-jni.so 0x4175fe08
11-14 16:54:23.437 32150-32150/? A/libc: Fatal signal 11 (SIGSEGV) at 0x5aa4cff0 (code=2), thread 32150 (com.myapp)
11-14 16:54:23.546 31669-31669/? I/DEBUG: pid: 32150, tid: 32150, name: com.myapp  >>> com.myapp <<<
11-14 16:54:23.976 31669-31669/? I/DEBUG:     #00  pc 00082052  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.976 31669-31669/? I/DEBUG:     #01  pc 000a50b7  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.976 31669-31669/? I/DEBUG:     #02  pc 0005a69d  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.976 31669-31669/? I/DEBUG:          be9fb2e8  5ee991cb  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.976 31669-31669/? I/DEBUG:          be9fb2ec  5eea0e85  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.976 31669-31669/? I/DEBUG:          be9fb2f4  5efd4168  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:     #00  be9fb318  5ee99c41  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb328  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb34c  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb354  5eec40bb  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb378  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb384  5eedb265  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb388  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb3c4  5eec0c3f  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb3d8  5efbfb8c  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb3e0  5efbf9ac  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:23.984 31669-31669/? I/DEBUG:          be9fb3e8  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
11-14 16:54:24.679 532-610/? D/CrashAnrDetector: Build: samsung/goldenvess3gxx/goldenvess3g:4.2.2/JDQ39/I8200XXUANJ3:user/release-keys
                                                 Hardware: PXA986
                                                 Revision: 3
                                                 Bootloader: I8200XXUANJ3
                                                 Radio: unknown
                                                 Kernel: Linux version 3.4.5-2794522 (se.infra@SWDA2607) (gcc version 4.6.x-google 20120106 (prerelease) (GCC) ) #2 SMP PREEMPT Thu Oct 23 12:24:56 KST 2014
                                                 
                                                 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
                                                 Build fingerprint: 'samsung/goldenvess3gxx/goldenvess3g:4.2.2/JDQ39/I8200XXUANJ3:user/release-keys'
                                                 Revision: '3'
                                                 pid: 32150, tid: 32150, name: com.myapp  >>> com.myapp <<<
                                                 signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 5aa4cff0
                                                     r0 5ac088d3  r1 5aa4cff0  r2 5ac179fb  r3 5aa4cff0
                                                     r4 00000000  r5 5aa4d000  r6 5ac1ca60  r7 5ac08890
                                                     r8 00000010  r9 00000010  sl 5efbf810  fp 00000010
                                                     ip 00000000  sp be9fb318  lr 00000000  pc 5eea1052  cpsr 20000030
                                                     d0  65706f72705f6b70  d1  532f6c616e726500
                                                     d2  56ce019856ce0100  d3  56ce020856ce0102
                                                     d4  65722e7365636e65  d5  616e616d2e6d6c61
                                                     d6  612f746e656d6567  d7  6f635f7373656363
                                                     d8  0000000000000000  d9  0000000000000000
                                                     d10 0000000000000000  d11 0000000000000000
                                                     d12 0000000000000000  d13 0000000000000000
                                                     d14 0000000000000000  d15 0000000000000000
                                                     d16 ffffffff00000000  d17 0000000000000000
                                                     d18 0000000000000000  d19 0000000000000000
                                                     d20 4008000000000000  d21 3fbc71c71c71c71c
                                                     d22 3fcc7288e957b53b  d23 3fd24998d6307188
                                                     d24 3fd99a27ad32ddf5  d25 3fe555b0aaeac752
                                                     d26 0000000000000000  d27 0000000000000000
                                                     d28 0000000000000000  d29 0000000000000000
                                                     d30 0000000000000000  d31 0000000000000000
                                                     scr 20000010
                                                 
                                                 backtrace:
                                                     #00  pc 00082052  /data/app-lib/com.myapp-1/librealm-jni.so
                                                     #01  pc 000a50b7  /data/app-lib/com.myapp-1/librealm-jni.so
                                                     #02  pc 0005a69d  /data/app-lib/com.myapp-1/librealm-jni.so
                                                 
                                                 stack:
                                                          be9fb2d8  5ac1d058  
                                                          be9fb2dc  00001680  
                                                          be9fb2e0  5ac1d2d8  
                                                          be9fb2e4  00001900  
                                                          be9fb2e8  5ee991cb  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb2ec  5eea0e85  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb2f0  00000000  
                                                          be9fb2f4  5efd4168  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb2f8  5ac1d060  
                                                          be9fb2fc  00000000  
                                                          be9fb300  be9fb330  [stack]
                                                          be9fb304  00000000  
                                                          be9fb308  5ac08890  
                                                          be9fb30c  5ac08890  
                                                          be9fb310  df0027ad  
                                                          be9fb314  00000000  
                                                     #00  be9fb318  5ee99c41  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb31c  00000001  
                                                          be9fb320  0000000f  
                                                          be9fb324  00000008  
                                                          be9fb328  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb32c  00000008  
                                                          be9fb330  5ac1ca68  
                                                          be9fb334  ffffffff  
                                                          be9fb338  00000000  
                                                          be9fb33c  5ac08890  
                                                          be9fb340  00000001  
                                                          be9fb344  00000001  
                                                          be9fb348  00000000  
                                                          be9fb34c  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb350  5ac07b78  
                                                          be9fb354  5eec40bb  /data/app-lib/com.myapp-1/librealm-jni.so
                                                     #01  be9fb358  ffffffff  
                                                          be9fb35c  00000000  
                                                          be9fb360  00000000  
                                                          be9fb364  00000008  
                                                          be9fb368  5dbe0ca8  
                                                          be9fb36c  00000000  
                                                          be9fb370  5dbe6b78  
                                                          be9fb374  5dbe0e18  
                                                          be9fb378  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb37c  00000008  
                                                          be9fb380  00000001  
                                                          be9fb384  5eedb265  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb388  5efbf810  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb38c  00000008  
                                                          be9fb390  00000000  
                                                          be9fb394  5dbe0ca8  
                                                          ........  ........
                                                     #02  be9fb3b8  00000000  
                                                          be9fb3bc  00000000  
                                                          be9fb3c0  5ac08890  
                                                          be9fb3c4  5eec0c3f  /data/app-lib/com.myapp-1/librealm-jni.so
                                                          be9fb3c8  00000000  
                                                          be9fb3cc  5dbe0ca8  
                                                          be9fb3d0  00000000  
                                                          be9fb3d4  00000000  
11-14 16:54:24.679 532-610/? D/CrashAnrDetector: processName:com.myapp
11-14 16:54:24.679 532-610/? D/CrashAnrDetector: broadcastEvent : com.myapp SYSTEM_TOMBSTONE
11-14 16:54:31.828 532-2992/? I/ActivityManager: Process com.myapp (pid 32150) (adj 0) has died.

```

#### Version of Realm and tooling
Realm version(s):  tested with 2.0.1 & 2.2.0

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: 4.0.3 Samsung Galaxy S3 Mini [GT-I8200](https://www.androiddevice.info/submission/8824/show) (armeabi-v7a)

The lib is present on the phone.

> adb shell ls -l /data/data/com.myapp/lib/librealm-jni.so
-rwxr-xr-x system   system    1811984 1979-12-30 23:00 librealm-jni.so

**Comment by JamesPaulKey** [comment] 2016-11-14 22:12
HI @rgdev

Your not alone. We have had the same issue, on an identical setup, but running android 4.2.

A few other devices potentially having the same issue as you were reported in #3651. Unfortunately, my own comment regarding this issue on the S3 Mini was 2 weeks ago, and have yet to receive an update.

Currently we are having to consider either down-grading to 1.2, or excluding support for affected device as the issue appears to be specific to all Realm 2.x releases.

**Comment by cmelchior** [comment] 2016-11-15 05:44
Hi @rgdev and @JamesPaulKey We are still working on getting a device to test on. Sorry for the delay. In the meantime, I'll close this as an duplicate of #3651 and let the discussion continue there.

**Closed** 2016-11-15 05:44 UTC
Labels: T:Duplicate

**Comment by Zhuinden** [comment] 2017-03-30 12:03
https://github.com/realm/realm-java/pull/4402 might fix this once it's merged
