### ISSUE TITLE
removeFromRealm ThrowingException

### ISSUE THREAD

**Issue by mystreamforyou** [realm/realm-java#2883] opened 2016-05-26 08:27 UTC
#### Goal
remove object by primary key
#### Actual Results

D/REALM: Row 0x9f325580 is no longer attached!
D/REALM: jni: ThrowingException 13, Object is no longer valid to operate on. Was it deleted by another thread?, .
D/REALM: Exception has been throw: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?

#### Code Sample

Realm realm = Realm.getDefaultInstance();
Group group = realm.where(Group.class).equalTo("groupId", groupId).findFirst();
realm.beginTransaction();
group.removeFromRealm();
realm.commitTransaction();
realm.close();

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by beeender** [comment] 2016-05-26 08:42
The error is caused by the deletion on the same object happened in anther thread.

```
Realm realm = Realm.getDefaultInstance();
Group group = realm.where(Group.class).equalTo("groupId", groupId).findFirst();
// Let's see group is valid here
// then it gets deleted here from another thread
realm.beginTransaction();
// beginTransaction will move you db version forward in this thread, which means, the group is not valid anymore
// Error happens
group.removeFromRealm();
realm.commitTransaction();
realm.close();
```

I think above is the case you met. But It depends on your use case. The simplest way would be checking the `goup.isValid()` before deletion. But it might not be the ideal solution for you. What is your use case?

**Comment by Zhuinden** [comment] 2016-05-26 19:42
You should query the group for deletion **inside the transaction** to obtain the newest version of the Realm.

**Comment by beeender** [comment] 2016-05-30 04:14
@mystreamforyou Hope above comments solved you problem. I am closing this issue now, feel free to reopen it if needed. Thanks!

**Closed by beeender** 2016-05-30 04:14 UTC
Labels: S:Waiting For User, T:Help
