### ISSUE TITLE
Realm 3.4.0: isEmpty for linked relationships causes SIGSEGV

### ISSUE THREAD

**Issue by polgacsa** [realm/realm-java#4864] opened 2017-06-27 22:10 UTC
#### Goal

Query for empty inverse relationships: get all dogs without owners.

#### Expected Results

Query should return the dogs without owners.

#### Actual Results

SIGSEGV:
```
06-27 22:21:19.670 3461-3461/com.realm.bug.realmbug A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x2429a227 in tid 3461 (lm.bug.realmbug)
                                                            
                                                            [ 06-27 22:21:19.670  1256: 1256 W/         ]
                                                            debuggerd: handling request: pid=3461 uid=10079 gid=10079 tid=3461
```
Full log attached: [full_log.txt](https://github.com/realm/realm-java/files/1106998/full_log.txt)

#### Steps & Code to Reproduce

The first query (`equalTo("owner.id", "person")`) is successful, and works as expected:
`06-27 21:52:47.999 31101-31101/com.realm.bug.realmbug I/MainActivity: size=1`
However the second (`isEmpty("owner")`) causes segfault.

#### Code Sample

`Dog` and `Person` are simple `RealmObject`s with `@PrimaryKey` id.

```java
private void testRealmBug(Context context) {
    Realm.init(context);
    RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
            .inMemory()
            .schemaVersion(2)
            .build();
    Realm realm = Realm.getInstance(realmConfiguration);

    realm.executeTransaction(new Realm.Transaction() {
        @Override
        public void execute(Realm realm) {
            Dog dog = realm.createObject(Dog.class, "dog");
            Person person = realm.createObject(Person.class, "person");
            person.getDogs().add(dog);
        }
    });

    // works as expected
    RealmResults<Dog> dogs = realm.where(Dog.class)
            .equalTo("owner.id", "person")
            .findAll();
    Log.i(TAG, "size=" + dogs.size());

    // SIGSEGV
    dogs = realm.where(Dog.class)
            .isEmpty("owner")
            .findAll();
    Log.i(TAG, "size=" + dogs.size());
}
```

```java
@RealmClass
public class Person extends RealmObject {

    @PrimaryKey
    private String id;

    private RealmList<Dog> dogs;

    public Person() {
    }

    public RealmList<Dog> getDogs() {
        return dogs;
    }

    public String getId() {
        return id;
    }
}
```

```java
@RealmClass
public class Dog extends RealmObject {

    @PrimaryKey
    private String id;

    @LinkingObjects("dogs")
    private final RealmResults<Person> owner = null;

    public Dog() {
    }

    public String getId() {
        return id;
    }
}
```

#### Version of Realm and tooling
Realm version(s): 3.4.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: API24 Nexus 5X (emulator), API25 Pixel (emulator)

**Comment by kneth** [comment] 2017-06-29 11:28
@polgacsa It is not solved by the fix in #4870. I'll continue the bug hunt.

**Comment by kneth** [comment] 2017-06-29 15:10
@polgacsa I think I have identify what the issue is, and I will come up with a fix - stay tuned.

**Comment by kneth** [comment] 2017-07-03 19:16
@polgacsa I have merged a fixed so I close the issue. Thanks for reporting!

**Closed by kneth** 2017-07-03 19:16 UTC
Labels: S:Review, T:Bug
