### ISSUE TITLE
Update from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by gang018** [realm/realm-java#3563] opened 2016-10-05 09:47 UTC
> What do you want to achieve?

Update from 2.0.0 to 2.0.1

> Actual Results

```
Gradle sync failed: No signature of method: org.gradle.api.internal.artifacts.DefaultDependencySet.removeIf() is applicable for argument types: (io.realm.gradle.RealmPluginExtension$_setSyncEnabled_closure1) values: [io.realm.gradle.RealmPluginExtension$_setSyncEnabled_closure1@27508a7f]
         Possible solutions: remove(java.lang.Object), removeAll(java.util.Collection), removeAll(groovy.lang.Closure), removeAll([Ljava.lang.Object;)
         Consult IDE log for more details (Help | Show Log)
```

#### Code Sample

```java

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'io.realm:realm-gradle-plugin:2.0.1'
    }
}

```

#### Version of Realm and tooling
Realm version(s): 2.0.1

Android Studio version: 1.5.1

**Comment by cmelchior** [comment] 2016-10-05 09:48
Does the same thing happen if you use Android Studio 2.2?

**Comment by gang018** [comment] 2016-10-05 09:50
@cmelchior 
gradle version 1.5.0

**Comment by cmelchior** [comment] 2016-10-05 09:51
Try upgrading to Android Studio `2.2` and Gradle `2.14.1`. Those should be the latest stable releases.

**Comment by le0nidas** [comment] 2016-10-05 12:36
I have a weird behavior after updating to version 2.0.1 (from 2.0.0).
I can work with gradle using the IDE (through the gradle pane) but when running the same commands (for example _gradlew clean_) i get the following:

> What went wrong:
> A problem occurred evaluating project ':data'.
> **Failed to apply plugin [id 'realm-android']**
> **Could not create an instance of type io.realm.gradle.RealmPluginExtension_Decorated.**

Part of the stacktrace (since it does not mention any class of realm):
```java
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:610)
        at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:571)
        at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:568)
        ....
```

I use Android Studio 2.2, Gradle 2.14.1 and the project is set to use the wrapper so no chance of using different gradle versions.
I should also mention that the project is a library one.

When i fallback to 2.0.0 everything works fine in both the IDE and the console.

Any thoughts?

**Comment by zaki50** [comment] 2016-10-06 00:34
I've reproduced this on Java 7 environment.

`removeIf` is only available on Java 8 or later.
We should avoid using that method in order to support Java 7.

Current work-around is using Java 8.

**Comment by zaki50** [comment] 2016-10-06 00:41
@le0nidas I think it is from the same cause.

**Comment by le0nidas** [comment] 2016-10-06 07:00
@zaki50 You were right. I had different JDKs in _studio_ and _gradle.properties_. I updated the one in the properties to 8 and everything works fine.

Thank you :)

**Comment by zaki50** [comment] 2016-10-06 13:05
fixed in 2.0.2.

**Closed by zaki50** 2016-10-06 13:05 UTC
Labels: S:Review, T:Bug

**Comment by gang018** [comment] 2016-10-06 13:13
I can confirm that in 2.0.2 all is working as expected. 
Thank you for such a quick fix!

**Comment by kalyani-panda** [comment] 2017-02-28 19:24
getting error while updating realm 2.3.0 to 2.3.1 in android. working fine for 2.3.0
Android studio and gradle both 2.2.3.
(Error:Cause: unable to find valid certification path to requested target)
while doing clean build,
Error:A problem occurred configuring project ':app'.
> Could not download realm-android-library.aar (io.realm:realm-android-library:2.3.1)
   > Could not get resource 'https://jcenter.bintray.com/io/realm/realm-android-library/2.3.1/realm-android-library-2.3.1.aar'.
      > Could not GET 'https://jcenter.bintray.com/io/realm/realm-android-library/2.3.1/realm-android-library-2.3.1.aar'.
         > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

please help:(

**Comment by zaki50** [comment] 2017-02-28 20:50
@kalyani-panda It's a different issue.

Could you create new issue?

**Comment by Zhuinden** [comment] 2017-02-28 21:00
Also considering its HTTPS path validation, you probably work in a place with some proxy up and that kills Gradle 's connection to bintray
