### ISSUE TITLE
[WARNING!] Obfuscation is not working with 2.1.0

### ISSUE THREAD

**Issue by FrancescoCapari** [realm/realm-java#3689] opened 2016-10-25 19:46 UTC
**Beware, don't release to Google Play with Realm 2.1.0** if you want your code to be obfuscated. Realm 2.1.0 won't allow any of your class names to be obfuscated, even on classes that are not RealmObjects.

I'm using custom dictionaries for it, but it probably does not matter. I tested this multiple times and my code with 2.0.2 is always correctly obfuscated, code with 2.1.0 is not obfuscated at all. Luckily this happened to me once with another library and I'm checking the resulting apk with an apktool before releasing.

**Comment by Zhuinden** [comment] 2016-10-25 19:50
Are you sure?  Realm's proguard configuration seems to be this :

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *

-keep class io.realm.internal.Keep
-keep,includedescriptorclasses @io.realm.internal.Keep class * { *; }

-keep class io.realm.internal.KeepMember
-keep,includedescriptorclasses class * { @io.realm.internal.KeepMember *; }

-dontwarn javax.**
-dontwarn io.realm.**
-keep class io.realm.RealmCollection
-keep class io.realm.OrderedRealmCollection
-keepclasseswithmembernames,includedescriptorclasses class io.realm.** {
    native <methods>;
}

-dontnote rx.Observable
```

Although I do admit, 

```
-keep,includedescriptorclasses class * { @io.realm.internal.KeepMember *; }
```

This line looks shady. 

@realm/java will look at it when they get here.

**Comment by FrancescoCapari** [comment] 2016-10-25 19:56
Yeah, I'm sure. I think that it's the exact line you mentioned.

**Comment by Zhuinden** [comment] 2016-10-25 20:25
@zaki50 the proguard config got goofed, apparently it keeps class * and the order of the class and the annotation is reversed in one or the other and it keeps all classes

**Comment by zaki50** [comment] 2016-10-25 22:12
I'lk check that

**Comment by zaki50** [comment] 2016-10-25 23:07
I confirmed that `-keep,includedescriptorclasses class * { @io.realm.internal.KeepMember *; }` is not correct.
I'll fix this.

**Comment by dawidhyzy** [comment] 2016-10-27 05:27
I also have parse error:
Error:Execution failed for task ':app:transformClassesWithNewClassShrinkerForPropertyFinderDebug'.
> ProGuard configuration parser error: /Users/DawidHyzy/Development/xxx/app/build/intermediates/exploded-aar/io.realm/realm-android-library/2.1.0/proguard.txt line 5:6 no viable alternative at input 'includedescriptorclasses'
is it connected?

**Comment by zaki50** [comment] 2016-10-27 09:16
Realm Java 2.1.1 which contains a fix for this issue has been released.

@dawidhyzy I think that old ProGuard does not support `includedescriptorclasses` option.
What version of `Android SDK Tools` are you using? Could you try `Android SDK Tools 25.2.2`?

**Comment by dawidhyzy** [comment] 2016-10-27 09:59
@zaki50 I have installed `25.2.2`

**Comment by zaki50** [comment] 2016-10-27 16:58
@dawidhyzy Is that error still there?

I think that error is not related to the original issue.
Could you make a new issue for that error if still happening.

**Closed by zaki50** 2016-10-27 16:58 UTC
Labels: S:P1 Backlog, T:Bug

**Comment by FrancescoCapari** [comment] 2016-10-27 17:01
Obfuscation now works correctly with 2.1.1. Thanks guys.

**Comment by zaki50** [comment] 2016-10-28 05:44
@dawidhyzy Is your project is using following configuration?

```
            minifyEnabled true
            useProguard false
```

I reproduced that error with that configuration.

**Comment by dawidhyzy** [comment] 2016-10-28 05:47
Yes. I'm using that.

**Comment by zaki50** [comment] 2016-10-28 05:51
@dawidhyzy I created an issue for that (#3714)
