### ISSUE TITLE
RealmSync feature issue. 

### ISSUE THREAD

**Issue by vladkarpman** [realm/realm-java#4727] opened 2017-05-30 09:18 UTC
#### Goal
> Take an advantage of Realm Sync feature.

#### Expected Results

> Correct synchronizing of local realm db with server realm db and getting correct notification about changes were made during the synchronizations

#### Actual Results

> Stop getting notification and moreover stop getting changed data if i set ChangeListeners on tables with inverse connections and with pretty much data inside. 

#### Steps & Code to Reproduce

> Check out GitHub repository: https://github.com/vladkarpman/RealmSyncingIssue 
in order to do steps which lead to Sync issues. 

#### Version of Realm and tooling
Realm version(s): 3.3.1

Realm sync feature enabled: yes

Android Studio version: 2.3.2

Which Android version and device: Google Nexus 6p

**Comment by beeender** [comment] 2017-05-31 05:35
Hi! I took a look of your project. it feels the slowness is caused by the circular links. We got some similar report before, see https://github.com/realm/realm-java/issues/4696#issuecomment-303617313 .

Can you try to break the circular links by using the `@LinkingObjects` we added before?

**Comment by Zhuinden** [comment] 2017-05-31 10:22
You guys really need to finish the linking objects queries for that to be a valid alternative

**Comment by vladkarpman** [comment] 2017-06-01 07:51
@beeender Hi! Thanks for yours reply. 
- First, i need such logic because order in the lists makes sense, i.e. I need specific order in the lists.
- Second, i checked whether syncing is working with `@ LinkingObjects`, and actually No. I still have the same issue: i get neither notifications nor data.

**Comment by idok595** [comment] 2017-06-01 13:35
i also facing the same issues, also have circular db structure, LinkingObjects is not a solution the relations are not reflect inverse relationship logic.

**Comment by beeender** [comment] 2017-06-02 08:18
@vladkarpman 
We are working on the optimizing the case with circular links, but that may take some time... Before we can fix that will those workaround feasible for you:

> First, i need such logic because I need specific order in the lists.

Is it possible that you can sort the `LinkingObjects` with some fields? `LinkingObjects` works like a normal `RealmResults` so it would be possible to sort it.

> Second, i checked whether syncing is working with @ LinkingObjects, and actually No. I still have the same issue: i get neither notifications nor data.

True, it won't be notified like the `RealmList`. But you can add listeners to it when needed. Adding listeners to every `LinkingObjects` in the collection won't be a good idea, but is it possible for you to add listeners to those `LinkingObject` only when needed? eg.: when they get displayed in the recyclerview. The idea is, the `LinkingObjects` won't trigger deletions/insertions but only modifications. You may also need to remove/add listener when deletion/insertion happens to the original list if the element is displayed in the view.

Let me know if I can help more with the workaround, i can create a PR to your repo if needed.

**Comment by Zhuinden** [comment] 2017-06-02 08:27
@beeender 

> . The idea is, the LinkingObjects won't trigger deletions/insertions but only modifications. 

that's... weird.

**Comment by beeender** [comment] 2017-06-02 08:38
@Zhuinden sorry it is not clear.

```
public class Owner extends RealmObject {
    Car car;
}

public class Car extends RealmObject {
    int id;
    @LinkingObjects("car")
    RealmResults<Owner> owners;
}

RealmResults<Car> allCars = realm.where(Car.class).findAll();

```

what i mean is you can handle the changes in listener on `owners` like handle modifications on a `RealmResults<Car>`.

**Comment by Zhuinden** [comment] 2017-06-02 08:43
@beeender but fine-grained notifs should specify insert/deletion if item becomes inserted and item becomes deleted, right?

Although the `owners.sort("id")` still applies for correct notifications.

**Comment by vladkarpman** [comment] 2017-06-06 10:55
@beeender Thanks for response. I've decided to change a bit structure of project and added a bit more functionality in order to be able to work with `@LinkingObjects`. So i am happy to say that it seems like everything works good. 

But anyway, issue with circular references exists. And developers should know about issue and how to solve it.

**Comment by beeender** [comment] 2017-06-06 11:12
@vladkarpman Great!
We have an issue #4544 opened to track that circular linking issue. I will just dup and close this one.

Thanks!

**Closed by beeender** 2017-06-06 11:12 UTC
Labels: T:Help
