### ISSUE TITLE
Deadlock when loading librealm-jni.so on specific device

### ISSUE THREAD

**Issue by ericmguimaraes** [realm/realm-java#3429] opened 2016-09-13 03:33 UTC
Hi guys, 

Thank you for the great library, but I'm having a issue trying to use it on a specific device. 

**Goal**
Create RealmConfiguration instance with `new RealmConfiguration.Builder(context).build()`

**Results**
I get no response from `new RealmConfiguration.Builder(context)`.

**Code sample**
https://github.com/ericmguimaraes/RealmIssue

**Debug**
- I debugged to see what specific call wasn't returning and ended at `SystemLibraryLoader.loadLibrary("realm-jni")`. 
- The librealm-jni.so is right there at the data/data folder as it should be. 
- I created a new app from scratch without any other library and it is still not working. (You can find it [here](https://github.com/ericmguimaraes/RealmIssue))
- The only thing on the logs were this: 
`09-13 00:09:53.986 1189-1189/com.realm.eric.realmproblem D/dalvikvm: Trying to load lib /data/data/com.realm.eric.realmproblem/lib/librealm-jni.so 0x4126b478`
- Tried using `io.realm.internal.Util.setDebugLevel(5);` but I got the same response
- It works fine on other devices

**Version of Realm/Android Studio/OS**
Android Studio 2.1.3 for osX
Realm 1.2.0
Device: Samsung GT-P5110 (Android 4.0.3, API 15)

Hope we can solve it, please let me know if you need something.

**Comment by beeender** [comment] 2016-09-13 03:43
What is the output of
```
adb shell getprop ro.product.cpu.abi
```

**Comment by ericmguimaraes** [comment] 2016-09-13 03:49
armeabi-v7a

**Comment by beeender** [comment] 2016-09-13 04:41
can you get the file size of `/data/data/com.realm.eric.realmproblem/lib/librealm-jni.so` on the device? 
like:

```
adb shell ls -l /data/data/com.realm.eric.realmproblem/lib/librealm-jni.so
```

**Comment by ericmguimaraes** [comment] 2016-09-13 10:21
`-rwxr-xr-x system   system    1193412 2016-10-13 00:47 librealm-jni.so`

**Comment by ericmguimaraes** [comment] 2016-09-14 14:29
What is interesting is that I use an old version of realm (0.85 I think) in another project, and this works fine in the same device. I just upgraded that other project to the newest realm lib and didn't test in this device yet. Might need to downgrade before sending to production? Any idea of what might be happening?

**Comment by kneth** [comment] 2016-09-15 10:52
Do your app load other `.so` files? The GT-P5110 has a ARMv7-A processor but if you load libraries compiled for other ARM processors, you might have issues. This doesn't explain why your app works with 0.85 and but 1.2.0.

Btw, it seems that your device lives in the future (mid October according to the above time stamp).

**Comment by ericmguimaraes** [comment] 2016-09-15 11:17
No, it doesn't load anything else. I created a [new app](https://github.com/ericmguimaraes/RealmIssue) just to try to create a RealmConfiguration in this device and still didn't work. =/

Well, that is odd.
```
shell@android:/data/data/com.realm.eric.realmproblem $ date                    
Thu Sep 15 08:23:51 BRT 2016

```

**Comment by WilliamWychgram** [comment] 2016-09-23 07:48
Hello there, 
I can confirm we are also seeing a very similar, if not the same issue with our app, when running it on a Kindle Fire HD 7, KFTT Model, running on Android 4.0.3 API Level 15, which can be found here https://developer.amazon.com/appsandservices/solutions/devices/kindle-fire/specifications/01-device-and-feature-specifications. 
We get the following in the logs:
Logcat:
09-19 15:37:14.940 11154-11154/com.ourapp.android D/dalvikvm: Trying to load lib /data/data/com.ourapp.android/lib/librealm-jni.so 0x415cb258

Following that log line, our app freezes, and follows up with ANR errors, and the dialog to wait or close. It never recovers, so we have to close it. Everything works fine on Realm 1.1.1 but as soon as we upgrade to Realm 1.2.0 we start to get this issue. It is 100% reproducible for us. Let me know if I can provide any further information to help.

Thanks for the awesome Library!

Best Regards

**Comment by kneth** [comment] 2016-09-23 07:51
@ericmguimaraes @WilliamWychgram Sounds like we need to find a 4.0.3 device and do some investigation.

**Comment by WilliamWychgram** [comment] 2016-09-23 07:57
Worth noting, we tried it on another 2012 Kindle on 4.0.3 and didn't have the issue, also tried it on a Samsung Galaxy tab 1 10inch and Samsung galaxy tab 2 7inch on 4.0.3 and both worked fine. Its just that random device that has the issue, and switching realm to the older version fixes it instandly. I don't believe it to be an ICS wide issue.

**Comment by cmelchior** [comment] 2016-09-23 08:02
I wonder if it is a problem with https://github.com/KeepSafe/ReLinker/ which we use to load the native files. I think we upgraded it for 1.2.0

**Comment by hdoria** [comment] 2016-09-26 19:44
Same problem here. ;(

**Comment by kneth** [comment] 2016-09-28 11:09
@WilliamWychgram mentions that it is not 100 % reproducible. I wonder is the `.so` is damaged during installation?  Are the failing device low on storage?

**Comment by WilliamWychgram** [comment] 2016-09-28 15:30
Hey @kneth, to clarify my previous statement. It is 100% reproducible on the model that exhibits the issue, and downgrading the library fixes it immediately. However it is not reproducible across all ICS devices. There doesn't appear to be an issue with storage space as far as I can tell.

**Comment by kneth** [comment] 2016-09-29 08:42
@WilliamWychgram Thanks for clarifying.  As mentioned earlier by @cmelchior, we have recently upgraded to ReLinker 1.2.2 (in Realm Java 2.0.0). Is it possible for you to upgrade and see if it solved the issue?

**Comment by kneth** [comment] 2016-10-11 10:32
I hope that upgrading to Realm Java 2.0.x has helped you. Don't hesitate to reopen or create new issue if you see the issue again.

**Closed by kneth** 2016-10-11 10:32 UTC
Labels: S:Waiting For User, T:Help

**Comment by WilliamWychgram** [comment] 2016-10-12 13:26
Hey there! 

Sorry for the delay, I had been on leave for a while. This update definitely seems to have solved most of our issues, the app no longer freezes when realm is loaded like it did on 1.2.0 with that device. We had a few minor other issues in the same code area as realm, but for now I think I will assume they are issues on our side, and report back if it turns out they are related to this.

Thanks again for your help and support!

Kind Regards
