### ISSUE TITLE
Can't skip field on deserialize

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6219] opened 2018-10-05 15:20 UTC
Here my pojo

```
public class Offer extends RealmObject {
   @PrimaryKey
   private long id;
   private LocalizedString name;
   @Expose(deserialize = false)
   private RealmList<Integer> availability;
   private boolean favorite;

   public static final String AVAILABILITY = "availability";
}
```

I use GSON lib. to deserialize  from json to pojo.
I want to skip field `availability` when deserialize from json to pojo. As result I annotate this field by:
```

   @Expose(deserialize = false)
   private RealmList<Integer> availability;
```

But it I get error:
 ```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BEGIN_OBJECT at line 197 column 12 path $[0].offers[0].availability[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:112)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.IllegalStateException: Expected an int but was BEGIN_OBJECT at line 197 column 12 path $[0].offers[0].availability[0]

```

It try to deserialize field `availability`. Why?

**Comment by Zhuinden** [comment] 2018-10-05 15:36
You probably didn't tell your Gson instance via `GsonBuilder` to respect `Expose` annotation.

**Comment by lmdic** [comment] 2018-10-05 16:02
It's not help:

 ```
       gsonBuilder.setExclusionStrategies(new CustomExclusionStrategy());
        gsonBuilder.registerTypeAdapter(Offer.class, new OfferAdapterJsonDeserializer());](url)

```

Here my custom strategy:

```
public class CustomExclusionStrategy implements ExclusionStrategy {
    @Override
    public boolean shouldSkipField(FieldAttributes f) {
        return (f.getDeclaringClass() == Offer.class && f.getName().equals(Offer.AVAILABILITY));
    }

    @Override
    public boolean shouldSkipClass(Class<?> clazz) {
        return false;
    }
}
```
Here my custom deserializer:

```
public class OfferAdapterJsonDeserializer implements JsonDeserializer<Offer> {

    @Override
    public Offer deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
         Offer offer = GsonUtil.gson.fromJson(json, Offer.class);
        // some custom code here
         return offer;
    }
}
```

But I get same error in line:
` Offer offer = GsonUtil.gson.fromJson(json, Offer.class);`


Error:

 ```
onFailure: Error: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.availability[0]
 com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.availability[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)

```

**Comment by Zhuinden** [comment] 2018-10-05 16:15
You need to explicitly enable `@Expose` annotation

**Comment by cmelchior** [comment] 2018-10-11 13:32
Since an explanation is given above and the issue is with GSON I'll close this issue.

**Closed by cmelchior** 2018-10-11 13:32 UTC
Labels: O:User
