### ISSUE TITLE
RealmTransformer not executing on with AGP 7.2.0/1

### ISSUE THREAD

**Issue by pedronveloso** [realm/realm-java#7685] opened 2022-05-09 21:39 UTC
### How frequently does the bug occur?

All the time

### Description

Android Studio just updated their stable IDE version. I'm using the recommended Gradle tooling version that came with the IDE update.
The app compiles normally, but crashes at runtime - and according to the error it seems fairly clear that the Realm plugin didn't work as expected. Let me know if you need further information.

### Stacktrace & log output

```shell
java.lang.ExceptionInInitializerError: RealmTransformer doesn't seem to be applied. Please update the project configuration to use the Realm Gradle plugin. See https://docs.mongodb.com/realm/sdk/android/install/#customize-dependecies-defined-by-the-realm-gradle-plugin
        at io.realm.RealmConfiguration.<clinit>(RealmConfiguration.java:80)
        at io.realm.RealmConfiguration.access$000(RealmConfiguration.java:68)
        at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:552)
        at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:538)
        at io.realm.Realm.initializeRealm(Realm.java:320)
        at io.realm.Realm.init(Realm.java:261)
        at com.patreon.android.data.manager.RealmManager.initialize(RealmManager.java:55)
```
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

_No response_

### Version

10.10.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

all

### Build environment

Android Studio version: Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022

Gradle : gradle-7.3.3-all

Realm: 10.10.1

**Comment by ewnu** [comment] 2022-05-10 04:12
I get same results when I update AGP from 7.1.3 to 7.2.0.
I'm sticking with 7.1.3 until this gets fixed

**Comment by cmelchior** [comment] 2022-05-10 06:35
I tried to reproduce this with our IntroExample, Chipmunk and AGP 7.2.0 and it seemed to work fine.

Can you provide more information about your project setup? If you can reproduce in a sample project it would be even better.

Also, have you tried a clean build to see if that fixes the issue?

**Comment by VicMikhailau** [comment] 2022-05-10 12:20
@cmelchior The same result. After upadtaing to the Chipmunk and AGP 7.2.0 - all works as expected.

**Comment by cmelchior** [comment] 2022-05-10 12:34
@VicMikhailau Not 100% sure if you mean it worked after upgrading or it failed with the same error that @pedronveloso is reporting?

**Comment by VicMikhailau** [comment] 2022-05-10 13:00
@cmelchior It worked after upgrading without any issues.

**Comment by pedronveloso** [comment] 2022-05-10 13:26
Clean build also has the same result. It compiles just fine, but crashes at runtime. I'll try Realm's sample for comparison.

**Comment by anshulmak** [comment] 2022-05-10 21:03
Got the same issue. I've tried clean build and Invalidate Caches too but the apk is crashing.

**Comment by VadimWelldone** [comment] 2022-05-11 09:53
Also, got crashes at runtime. Maybe it's related to this breaking change in AGP 7.2: https://developer.android.com/studio/releases/gradle-plugin-api-updates#instrumentatin-apis-deprecated because AGP produces such a warning message and points out to Realm plugin:

`AGPBI: {"kind":"warning","text":"API 'android.registerTransform' is obsolete.\nIt will be removed in version 8.0 of the Android Gradle plugin.\nThe Transform API is removed to improve build performance. Projects that use the\nTransform API force the Android Gradle plugin to use a less optimized flow for the\nbuild that can result in large regressions in build times. It’s also difficult to\nuse the Transform API and combine it with other Gradle features; the replacement\nAPIs aim to make it easier to extend the build without introducing performance or\ncorrectness issues.\n\nThere is no single replacement for the Transform API—there are new, targeted\nAPIs for each use case. All the replacement APIs are in the\n`androidComponents {}` block.\nFor more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.\nTo determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.","sources":[{}]}`

**Comment by cmelchior** [comment] 2022-05-11 10:48
Hi @VadimWelldone The API's should only be removed in AGP 8.0, not 7.2. So something else must be causing it.

For anyone else seeing this. Some more details on exactly you project structure looks like would be appreciated. I have tested with AGP 7.2.0 and Gradle 7.3.3 where it did work on a simple project. So maybe it is a specific project structure triggering this, or certain grade properties being set.

**Comment by pedronveloso** [comment] 2022-05-11 19:52
@cmelchior I wasn't able to get studio to properly initialize the demos from the repo. Looking at the Realm docs, the main different I see in my current setup is that I'm using the "Gradle Legacy Syntax" as opposed to the newer "Gradle Plugin Syntax". Not sure if this could be the root cause, but its the first thing that stood out to me.

**Comment by patricknanganocappello** [comment] 2022-05-12 07:39
> @cmelchior I wasn't able to get studio to properly initialize the demos from the repo. Looking at the Realm docs, the main different I see in my current setup is that I'm using the "Gradle Legacy Syntax" as opposed to the newer "Gradle Plugin Syntax". Not sure if this could be the root cause, but its the first thing that stood out to me.

I just tried to change my project gradle setup to the newer gradle plugin sintax and I get the same issue. Still crashes at runtime

**Comment by andersfredlund** [comment] 2022-05-12 10:03
Same problem here, my debug build works though not using proguard so could it be something in the code optimisation step which brakes the build?

**Comment by zhaosunny1** [comment] 2022-05-13 07:03
Butterknife And Realm  both got errors

**Comment by monday8am** [comment] 2022-05-16 16:06
Same problem here. In our case, it works in a branch without Hilt and the one with Dagger Hilt crashes.

**Comment by PriyaSindkar** [comment] 2022-05-16 19:17
> I get same results when I update AGP from 7.1.3 to 7.2.0. I'm sticking with 7.1.3 until this gets fixed

going back to 7.1.3 worked for me as well.

**Comment by PriyaSindkar** [comment] 2022-05-16 19:18
> Same problem here. In our case, it works in a branch without Hilt and the one with Dagger Hilt crash
@clementetb - if it helps, I am using hilt in my project..

**Comment by Jeff11** [comment] 2022-05-18 08:37
I got the same error stack trace with gradle plugin 7.2.0. Also using Hilt.

**Comment by CsabaMiomni** [comment] 2022-05-18 09:34
The same error here. Back to 7.1.3 works fine.

**Comment by vernazza** [comment] 2022-05-23 09:17
I have the same problem (not working in 7.2, working in 7.1.3
I'm not using HILT and, looking at the dependency tree, no library is using it either

**Comment by cmelchior** [comment] 2022-05-23 09:23
Hi @vernazza Thank you for the information 👍

**Comment by ewnu** [comment] 2022-05-23 10:16
@cmelchior I'm not using hilt either.

**Comment by bobekos** [comment] 2022-05-24 13:39
@cmelchior 

I too get crashes at runtime on Gradle version 7.2.0. There are no problems on 7.1.3. The errors are also strange. It almost seems that the proxy objects are null when access. Although the objects are filled when looking at them with the debugger. Writing to the DB doesn't seem to be a problem. My project also doesn't use hilt but dagger. 
I could not reproduce it on the fly with a fresh project. I don't know where the differences are. In the new project I used the same Realm and Dagger version. The only difference, the new project was in Kotlin and the other one in Java.

**Comment by GriffinJBC** [comment] 2022-05-27 17:14
I can confirm I started having this issue after installing hilt and adding @HiltAndroidApp to my application class. Unfortunately I cannot share my project as the code is not open sourced.

**Comment by nhachicha** [comment] 2022-05-27 18:30
I created a sample project using the latest Realm-Java with Dagger and AGP 7.2 https://github.com/nhachicha/realm_java_7685 (and it's working)
 could you please use it as a baseline to reproduce the issue so we can investigate cc @GriffinJBC @bobekos @ewnu @vernazza @pedronveloso

**Comment by ahmedsiddique-cb** [comment] 2022-06-01 05:41
I am using Hilt+Realm in my android project and i am facing this issue as well after upgrading to 7.2.0

**Comment by bobekos** [comment] 2022-06-01 10:12
@nhachicha 
No chance i can't reproduce it. That's super weird. In my project I can't really understand it either. I know why it crashes. It is simply a null pointer to a RealmObject which is 100% filled. The funny thing is, if I copy the exact same code (to fetch a realm object) somewhere else (into an existing class) then it works. If I create a new class that is identical, it doesn't work. The realm objects and the proxies are identical in both. But in one I can read the attributes in the other there are null. I can't even tell you what the reason is. Already deleted all cashes and cleaned up the project.

**Comment by PVGH19** [comment] 2022-06-01 15:58
So I'm also getting this error but I know exactly why it's happening: For me, it's because I introduced DaggerHilt which also uses an android gradle plugin. So I think that the Dagger Hilt plugin and Realm plugin are **incompatible**. So there may be some incompatible plugins within some applications...

Note: I created a new project with Realm + Dagger Hilt and confirmed this is the case. These are my configurations:

`build.gradle`
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:10.11.0"
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.42'
    }
}

plugins {
    id 'com.android.application' version '7.2.1' apply false
    id 'com.android.library' version '7.2.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.21' apply false
    id "org.jetbrains.kotlin.kapt" version "1.6.21" apply false
}
```

`build.gradle(app)`

```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
}

apply plugin: 'dagger.hilt.android.plugin'
apply plugin: "realm-android"
``` 

Gradle: `Gradle : gradle-7.3.3-all`

I would really, really, want a solution to this. Can't we, for example, **not** rely on the Realm plugin but instead add the dependencies manually?

**Comment by PVGH19** [comment] 2022-06-02 07:47
@ewnu I can assure you this is true. I created a very small project with just Dagger Hilt + Realm and it did not work with android application 7.2.1. It did work with 7.1.3. Now there **may** be other reasons that it is happening to you specifically.

**Comment by Jeff11** [comment] 2022-06-02 08:36
@PVGH19 could you upload your test project for @cmelchior and others to debug please?

**Comment by PVGH19** [comment] 2022-06-02 10:08
@Jeff11 @cmelchior I've added the sample project here: https://github.com/PVGH19/RealmAndDagger 

Initially, it should run correctly. As soon as we change android.application version to 7.2.1 you should see the RealmTransformer crash.

**Comment by SuperTango** [comment] 2022-06-02 19:45
More data: In our project, we have HILT defined, but we're not really using it. It works correctly with Gradle 7.2.0, but not 7.3.1. 🤷‍♂️

**Comment by TemMax** [comment] 2022-06-03 12:56
After updating to AGP 7.2.0 faced the same issue. Please, fix it.

**Comment by nhachicha** [comment] 2022-06-08 11:11
Thanks @PVGH19 I'm able to reproduce the issue. I'll have a look.

**Comment by nhachicha** [comment] 2022-06-10 15:13
Some updates regarding the issue:

Using `hilt` gradle plugin beyond version 2.38 can cause the `RealmTransformer` to not trigger, this might be caused by the fact that `hilt` strated using the new [ASM Transformer API](https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-removed) (which will be the only Transformer supported from [AGP 8.0 onwoard](https://developer.android.com/studio/releases/gradle-plugin-api-updates#agp-8-0-0)).

Using @PVGH19  sample one can use `com.google.dagger:hilt-android-gradle-plugin:2.38` with AGP `7.2.1` and it still works. Another work around is to keep using AGP 7.1.3 until we finish the process of rewriting the transformer using ASM (instead of Javassist currently).

We will post here once we completed the re-write of the trasnformer.

**Comment by pedronveloso** [comment] 2022-07-20 23:28
> Some updates regarding the issue:
> 
> Using `hilt` gradle plugin beyond version 2.38 can cause the `RealmTransformer` to not trigger, this might be caused by the fact that `hilt` strated using the new [ASM Transformer API](https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-removed) (which will be the only Transformer supported from [AGP 8.0 onwoard](https://developer.android.com/studio/releases/gradle-plugin-api-updates#agp-8-0-0)).
> 
> Using @PVGH19 sample one can use `com.google.dagger:hilt-android-gradle-plugin:2.38` with AGP `7.2.1` and it still works. Another work around is to keep using AGP 7.1.3 until we finish the process of rewriting the transformer using ASM (instead of Javassist currently).
> 
> We will post here once we completed the re-write of the trasnformer.

Sadly I can't do this because Kotlin requires a certain minimum version of Hilt, and `2.38` is more than a year old, I believe it supports version of Kotlin around 1.5 which is also pretty old at this point.

**Comment by o15a3d4l11s2** [comment] 2022-07-22 21:40
I noticed something strange:

```
Gradle: 7.2.1
Realm: tested with 10.11.1 and and older app with 6.1.0
```

All works fine until Firebase Performance Monitoring (`com.google.firebase:firebase-perf`) is added. Then the error shows.

**Comment by fanwgwg** [comment] 2022-07-31 07:30
Friendly ping, this issue has been open since May, is there a timeline when we can expect it to be resolved? This is currently blocking our migration of other libraries, which requires AGP minimum version of 7.2

**Comment by Jeff11** [comment] 2022-08-04 07:05
Today I updated all libs and tools and this crash isn't happening anymore for me.

Gradle plugin 7.2.2
Dagger 2.43.2
Realm 10.11.1

**Comment by cmelchior** [comment] 2022-08-04 09:39
@fanwgwg We don't have an exact timeline yet as we are still hitting a few issues, but you can follow the progress here https://github.com/realm/realm-java/pull/7694

**Comment by imknown** [comment] 2022-08-04 10:00
Android Studio official release notes of AGP 7.2.2 shows it fixed: 
https://developer.android.google.cn/studio/releases/gradle-plugin#7-2-0

**Comment by rorbech** [comment] 2022-08-04 10:52
@Jeff11 Thanks for the notice. 

Bumping to AGP 7.2.2 also fixes the issue for the reproduction project supplied in https://github.com/realm/realm-java/issues/7685#issuecomment-1144684084

**Comment by pedronveloso** [comment] 2022-08-10 22:47
> @Jeff11 Thanks for the notice.
> 
> Bumping to AGP 7.2.2 also fixes the issue for the reproduction project supplied in [#7685 (comment)](https://github.com/realm/realm-java/issues/7685#issuecomment-1144684084)

This has worked for us as well. Unclear why that particular version of AGP didn't work. Hopefully if something will break going forward this buys Realm's team more time to work on a proper fix.

**Comment by PriyaSindkar** [comment] 2022-08-31 07:36
> Also, got crashes at runtime. Maybe it's related to this breaking change in AGP 7.2: https://developer.android.com/studio/releases/gradle-plugin-api-updates#instrumentatin-apis-deprecated because AGP produces such a warning message and points out to Realm plugin:
> 
> `AGPBI: {"kind":"warning","text":"API 'android.registerTransform' is obsolete.\nIt will be removed in version 8.0 of the Android Gradle plugin.\nThe Transform API is removed to improve build performance. Projects that use the\nTransform API force the Android Gradle plugin to use a less optimized flow for the\nbuild that can result in large regressions in build times. It’s also difficult to\nuse the Transform API and combine it with other Gradle features; the replacement\nAPIs aim to make it easier to extend the build without introducing performance or\ncorrectness issues.\n\nThere is no single replacement for the Transform API—there are new, targeted\nAPIs for each use case. All the replacement APIs are in the\n`androidComponents {}` block.\nFor more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.\nTo determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.","sources":[{}]}`

I am getting this as warning as well when I bumped my AGP from 7.1.3 to 7.2.2 with gradle version 7.3.3. The obsolete APIs used is pointing to the realm plugin.

**Comment by rorbech** [comment] 2022-08-31 07:55
Hi @PriyaSindkar. Thanks for the observation. We are in the process of migrating to the new API in #7714.

**Comment by rorbech** [comment] 2022-10-19 08:17
Closing this issue as it was not an issue with Realm but an issue in AGP 7.2.0 and 7.2.1 ... which is also fixed in later versions of AGP. 

Regarding the comments about deprecation (from AGP 7.3) and removal (from AGP 8) of the old transformer API please see https://github.com/realm/realm-java/issues/7714#issuecomment-1262339720 that covers the details of providing a version  using the new migrated API from AGP 7.4 and onwards along with a backward compatible version for AGP 7.3 and below.

**Closed by rorbech** 2022-10-19 08:17 UTC
Labels: T-Bug, Reproduction-Required, O-Community, Needs-Attention
