### ISSUE TITLE
Fatal Exception: io.realm.exceptions.RealmError Unrecoverable error. Key not found in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 475

### ISSUE THREAD

**Issue by shrikantsonar** [realm/realm-java#7010] opened 2020-07-30 12:28 UTC
Some of our users are facing crashes after we updated to latest realm version. Following are the details about configuration & crash stack trace.

Project level gradle configuration 
**classpath "io.realm:realm-gradle-plugin:7.0.0"**

App level Gradle configurations
    **kapt 'androidx.databinding:databinding-compiler:4.0.0'
    kapt "io.realm:realm-annotations:7.0.0"
    kapt "io.realm:realm-annotations-processor:7.0.0"**

Following is the stack trace obtained from Google Crashlytics.

Fatal Exception: io.realm.exceptions.RealmError
Unrecoverable error. Key not found in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 475
io.realm.internal.OsResults.nativeEvaluateQueryIfNeeded (OsResults.java)
io.realm.internal.OsResults.load (OsResults.java:664)
io.realm.RealmResults.load (RealmResults.java:142)
io.realm.RealmQuery.createRealmResults (RealmQuery.java:2397)
io.realm.RealmQuery.findAll (RealmQuery.java:1778)

When our app is trying to do a **findAll** operation we are facing this issue. 
Same crash occurred for another user which points to realm **copyOrUpdate** method.

What may be the cause of this issue? Can you guys help me out ?
Thanks in advance.

**Comment by cmelchior** [comment] 2020-08-04 13:55
Duplicate of https://github.com/realm/realm-java/issues/6992. So merging it into that one.

**Closed by cmelchior** 2020-08-04 13:55 UTC
Labels: O-Community
