### ISSUE TITLE
Realm Instances memory leak check 

### ISSUE THREAD

**Issue by vaibhav2800** [realm/realm-java#7224] opened 2020-12-02 08:53 UTC
I am using Realm DB (Both local and ROS ) in my project . Now I am facing issue of High Database file size. it seems issue of memory leaks in project since Project is old and having large use of Realm , it is difficult to check every realm instance individually .
I have checked instances for Local Realm **Global Realm Count - 3 , Local Realm Count - 192**  by using Realm.getGlobalInstanceCount && Realm.getLocalInstanceCount respectively. How can I check memory leak or instances name/class .

**Comment by rorbech** [comment] 2020-12-02 09:29
The root cause of unexpected huge Realm size is usually that the Realm files are not closed after accessing them. This can cause a need to keep a lot of versions. Maybe read through https://realm.io/docs/java/latest/#faq-large-realm-file-size

Given you high instance count, you also might want to read through https://realm.io/docs/java/latest/#realm-instance-lifecycle and https://realm.io/docs/java/latest/#closing-realms

You can reduce the size of Realms by removing no longer needed space by compacting it with (https://realm.io/docs/java/10.0.1/api/io/realm/Realm.html#compactRealm-io.realm.RealmConfiguration-) it.

**Comment by vaibhav2800** [comment] 2020-12-03 06:45
> The root cause of unexpected huge Realm size is usually that the Realm files are not closed after accessing them. This can cause a need to keep a lot of versions. Maybe read through https://realm.io/docs/java/latest/#faq-large-realm-file-size
> 
> Given you high instance count, you also might want to read through https://realm.io/docs/java/latest/#realm-instance-lifecycle and https://realm.io/docs/java/latest/#closing-realms
> 
> You can reduce the size of Realms by removing no longer needed space by compacting it with https://realm.io/docs/java/10.0.1/api/io/realm/Realm.html#compactRealm-io.realm.RealmConfiguration-.

I am already using compactOnLaunch() which is not showing any effect even though it is written in application's onCreate()(I suppose no instance is open at that level).
Will Compacting Realm work even if 1 realm instance is open ?
Any Suggestions ?

**Comment by rorbech** [comment] 2020-12-03 09:14
Compacting will not work if any instance is open and will also not work if there is not enough free storage space to make a copy of the file. You can check the return value of explicit calls to [`compactRealm`](https://realm.io/docs/java/10.0.1/api/io/realm/Realm.html#compactRealm-io.realm.RealmConfiguration-) to see if it succeeded. 

If always using `compactOnLaunch()` on the configuration it should be compacted when retrieving the first instance if meeting the criteria for the [`DefaultCompactOnLaunchCallback`](https://realm.io/docs/java/latest/api/io/realm/DefaultCompactOnLaunchCallback.html) and there is sufficient space to perform the compacting. Consider to use the [variant](https://realm.io/docs/java/10.0.1/api/io/realm/RealmConfiguration.Builder.html#compactOnLaunch-io.realm.CompactOnLaunchCallback-) taking a custom `CompactOnLaunchCallback` to get an idea of the numbers and triggered the compacting more eagerly than the limits of the default callback.

**Comment by vaibhav2800** [comment] 2020-12-03 09:39
I have used [DefaultCompactOnLaunchCallback()](https://realm.io/docs/java/latest/api/io/realm/DefaultCompactOnLaunchCallback.html) whose limit is 50MB which is ok with me , so the cause of failure of this method would be low space in device right ?
 
So there are 2 scenario in which [compactOnLaunch()](https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.Builder.html#compactOnLaunch--) would not work .
1- if condition for compact is not fulfilled. 
2- if device does not have enough memory for creating DB copy for cleaning.

Correct me if I am wrong ?

**Comment by rorbech** [comment] 2020-12-03 09:53
Right. But the default callback is also not triggering unless _"more than 50% can be reclaimed"_.

**Comment by vaibhav2800** [comment] 2020-12-08 06:41
It still does not work. Condition for compactOnLaunch() is **more that 10% can be reclaimed** && all instances are close.
Still it shows Global count 1 and Local count : 70 . 
How can I debug this as all the local instances are close in code but still local count is so high ?

**Comment by edualonso** [comment] 2020-12-14 13:41
The global count represents
```
the number of open Realm instances across all threads in current process that are using this configuration
```
So having it at 1 is a good sign.

The local count represents
```
the current number of open Realm instances on the thread calling this method
```
Having the local count at 70 is a smell that points to not having closed those instances correctly when they are no longer needed.

There is no silver bullet to debug a scenario in which one has so many open instances. As @rorbech pointed out above, you should handle the opening/closing of instances in a similar fashion as shown in https://realm.io/docs/java/latest/#closing-realms.

**Closed** 2020-12-16 11:22 UTC
Labels: O-Community
