### ISSUE TITLE
kotlin.incremental=true cause problems with annotation processor

### ISSUE THREAD

**Issue by DinuIoan** [realm/realm-java#3115] opened 2016-07-03 15:09 UTC
Hello , I get this error when i build my project unreachable statament in DefaultRealmModuleMediator.java and it points to 
throw getMissingProxyClassException(clazz);
            if (iterator.hasNext()) {
                throw getMissingProxyClassException(clazz);
            }

Can you help me please ?

**Comment by Zhuinden** [comment] 2016-07-03 18:50
Do you have at least one class that extends `RealmObject`?

**Comment by beeender** [comment] 2016-07-04 02:15
Can you please share the whole file of `DefaultRealmModuleMediator.java`? It is a generated file which should be located in your `build` directory.

**Comment by DinuIoan** [comment] 2016-07-05 10:06
@beeender 
[DefaultRealmModuleMediator.txt](https://github.com/realm/realm-java/files/347482/DefaultRealmModuleMediator.txt)


@Zhuinden no, I don't have any class that extends RealmObject

**Comment by Zhuinden** [comment] 2016-07-05 10:37
You should make at least one class that extends RealmObject.

Any class will do, also specify `deleteIfMigrationNeeded()` for your RealmConfiguration builder.

**Comment by beeender** [comment] 2016-07-06 02:07
To @DinuIoan I think follow @Zhuinden 's comment will solve your problem.

Internal notes, in this case we should throw earlier in the annotation processor.

```java
    @Override
    public void insert(Realm realm, Collection<? extends RealmModel> objects) {
        Iterator<? extends RealmModel> iterator = objects.iterator();
        RealmModel object = null;
        Map<RealmModel, Long> cache = new IdentityHashMap<RealmModel, Long>(objects.size());
        if (iterator.hasNext()) {
            //  access the first element to figure out the clazz for the routing below
            object = iterator.next();
            // This cast is correct because obj is either
            // generated by RealmProxy or the original type extending directly from RealmObject
            @SuppressWarnings("unchecked") Class<RealmModel> clazz = (Class<RealmModel>) ((object instanceof RealmObjectProxy) ? object.getClass().getSuperclass() : object.getClass());

            throw getMissingProxyClassException(clazz);
            if (iterator.hasNext()) {
                throw getMissingProxyClassException(clazz);
            }
        }
    }

```

**Comment by NitroG42** [comment] 2016-07-12 08:29
I have this problem with kotlin since I updated android gradle plugin to 2.2.0-alpha5 version.
Even with realm 1.1.1-SNAPSHOT, still the same error.
The project is compiling 1 time out of 4.
I usually don't ask this (I know it's very annoying) but do you have any ETA on this ? I will move back to Android Studio 2.1 for the moment.

**Comment by beeender** [comment] 2016-07-12 08:46
@NitroG42 I am really sorry for the delay. I am looking into this issue right now.

**Comment by NitroG42** [comment] 2016-07-12 08:48
Hey I'm sorry I just saw there was a 1.2.0-snapshot, I'm trying this right now (because it seems fix on the latest source code version).

**Comment by beeender** [comment] 2016-07-12 08:50
I think it is not fixed ... Just to confirm, you have some `RealmObject` or `RealmModle` defined, right?

**Comment by NitroG42** [comment] 2016-07-12 08:56
Yes I have, but I as said, I only got this issue since updating to Android Studio 2.2 Preview 5 (was on Preview 4 before and it was working) with gradle plugin alpha 5. I'm not sure how it interact with your code generation (it shouldn't but hey... It's android !)

**Comment by Zhuinden** [comment] 2016-07-12 08:57
@NitroG42  do you by chance use your own `@RealmModule` to define your schema, or do you rely on the default schema (which contains all RealmObjects in the project)?

**Comment by NitroG42** [comment] 2016-07-12 09:02
I'm using the default schema, no custom module

**Comment by NitroG42** [comment] 2016-07-12 09:04
I just tested with 1.2.0-snapshot, same issue.

**Comment by beeender** [comment] 2016-07-12 09:06
@NitroG42 It might this issue https://github.com/realm/realm-java/issues/2822
Can you please try to add `@RealmClass` annotation to the classes to see if it works?

**Comment by NitroG42** [comment] 2016-07-12 09:08
It already done, I need this because i'm using RealmModel interface instead of RealmObject classes for my model.

**Comment by beeender** [comment] 2016-07-12 09:16
@NitroG42 Is it a java/kotlin mixed project? I just tried a kotlin project with AS 2.2 preview 5, it works ...

**Comment by NitroG42** [comment] 2016-07-12 09:18
There is one or two java class yes, I will try to remove them in a few moments, right now with 1.2.0-snapshot (I used the clean button, I should have done this before reporting), it seems to work (the generated DefaultRealmModuleMediator was entirely different after using Clean)

**Comment by beeender** [comment] 2016-07-12 09:21
@NitroG42 and maybe this helps https://github.com/realm/realm-java/pull/2568

**Comment by Zhuinden** [comment] 2016-07-12 09:23
@beeender  so essentially

> As a temporary workaround until this request is adopted, I wrote apply plugin 'realm-android' before apply plugin 'kotlin-android'.

?

**Comment by beeender** [comment] 2016-07-12 09:24
I guess so, but I haven't tested it before. @zaki50 Do you remember the problem of mixing java and kotlin apt?

**Comment by NitroG42** [comment] 2016-07-12 09:33
Ok some updates : 
I still doesn't work with 1.2.0-snapshot. What happens is : 
- Clean build, run => The DefaultRealmModuleMediator is generated with all my classes in it, no error.
- Second run, the mediator it is modified and there is no class in it => error
- It might be because I have one Java class in my project (but it's a behavior, a custom view for the CoordinatorLayout), or because of kotlin incremental build that is enabled on my project, or something else.

**Comment by NitroG42** [comment] 2016-07-12 09:37
Ok I can confirm that transforming my Java Class to Kotlin made the error disappear. So it is definitelly because of the kotlin/java mix (even if java is one class, without annotation)

**Comment by beeender** [comment] 2016-07-12 09:39
@NitroG42 Does below temp fix work for you? (from https://github.com/realm/realm-java/pull/2568)
> As a temporary workaround until this request is adopted, I wrote apply plugin 'realm-android' before apply plugin 'kotlin-android'.

**Comment by NitroG42** [comment] 2016-07-12 10:10
No I got lots of errors like : 
Caused by: java.lang.IllegalArgumentException: Child is not part of the schema for this Realm

Caused by: java.lang.ClassCastException: mypackage.model..Child cannot be cast to io.realm.ChildRealmProxyInterface

**Comment by beeender** [comment] 2016-07-12 13:41
@NitroG42 It seems it will take us some time to identify/fix the problem with preview AS (or maybe it is a android plugin issue :( ). Before it is fixed I think you need to switch back to AS 2.1 or using kotlin only. Really sorry for the convenience.

**Comment by NitroG42** [comment] 2016-07-12 13:44
Hey don't worry I just needed to identify the problem, now that I know it works with kotlin only I removed my java class ! 
Thank you very much for your reactivity btw !

**Comment by beeender** [comment] 2016-07-13 07:55
I think https://github.com/realm/realm-java/pull/2568 should fix this. And `apply plugin: 'realm-android'` should be put AFTER `apply plugin: 'kotlin-android'`

**Comment by NitroG42** [comment] 2016-08-03 09:17
Hey, I needed to add a lots of Java class to my project, so I decided to try the 1.2.0-SNAPSHOT one more time, and good news everyone !
It seems to work now.

**Comment by beeender** [comment] 2016-08-03 09:20
@NitroG42 Uh... I don't think we made any changes related to this ... 

So still a java & kotlin mixed project?

**Comment by Zhuinden** [comment] 2016-08-03 09:26
@NitroG42 now that I think about it, a possibility is that `incremental dex` should have been disabled:

```
android {
    dexOptions {
        incremental false
    }
```

**Comment by NitroG42** [comment] 2016-08-03 09:57
@beeender Yeah I just got the same error, but it worked multiple times before regenerating an empty Mediator, maybe it worked because of Instant run, I don't know.
Now, it is definitelly a java/kotlin mixed (Maybe i'll convert it to full kotlin later but right now there are too many java class)
@Zhuinden I'll try this !

**Comment by NitroG42** [comment] 2016-08-08 16:47
I don't have this issue anymore since using : 
compileOptions {
        incremental false
    }

**Comment by Zhuinden** [comment] 2016-08-08 17:26
@nitrog42 glad to hear that! :) 

Sorry I didn't realize that could have caused this problem earlier

**Comment by beeender** [comment] 2016-08-09 06:14
@NitroG42 Since we merged #2830 , I think it should work with `incremental true`.  Would you please help to verify this with our snapshot? Just try with `io.realm:realm-gradle-plugin:1.2.0-snapshort`

**Comment by NitroG42** [comment] 2016-08-09 12:39
I switched to 1.2.0 this morning and compiled many times, no error yet.

**Comment by beeender** [comment] 2016-08-09 12:44
Thank you very much!!!!!!
I am closing this issue. Let us know if the problem happens again.

**Comment by Adambl4** [comment] 2016-08-19 14:20
I still have it with `io.realm:realm-gradle-plugin:1.2.0` in every second run.

**Comment by beeender** [comment] 2016-08-19 14:24
@Adambl4 Try disable instant run?

**Comment by Adambl4** [comment] 2016-08-19 14:35
Instant run disabled. 
The issue passes away if I set `kotlin.incremental=false`

**Comment by beeender** [comment] 2016-08-19 15:06
I just changed the title of this issue and reopen this.

For now, please just use `kotlin.incremental=false` as a workaround.
We will try to figure out the reason later. Thanks!

**Comment by vbosnjak** [comment] 2016-08-23 13:36
I'm having the same problem, not using instant run. Kotlin is 1.0.3, Realm 1.2.0.
For now I'm using kotlin.incremental=false in gradle.properties as a workaround.

**Comment by sxua** [comment] 2016-08-23 13:52
I'm using latest versions of Kotlin and Realm and Instant Run works fine (Java only) in latest stable version of Android Studio with incremental kotlin builds turned off.

**Comment by asarazan** [comment] 2016-08-30 23:31
I've found that the problem goes away with `kapt.generateStubs = true` regardless of whether incremental is on or off. It comes back shortly after disabling `generateStubs`.

**Comment by kuno** [comment] 2016-09-05 07:09
I have similar issue with kotlin, but the `kotlin.incremental=false` tricky dose not work for me

**Comment by Zhuinden** [comment] 2016-09-05 07:14
@kuno disable instant run

**Comment by kuno** [comment] 2016-09-05 07:54
@Zhuinden 

I already disabled instant run.

**Comment by Zhuinden** [comment] 2016-09-05 08:10
Are you sure you're not getting some error message regarding some kind of other mistake somewhere?

Or is it still that the proper RealmMediator logic is not generated

**Comment by NitroG42** [comment] 2016-09-06 08:04
I can confirm I still got this issue. Before, using incremental on kotlin and java worked like 9/10 times, but yesterday I used the new experimental annotation processor (kapt2, more info here : https://discuss.kotlinlang.org/t/kotlin-1-0-4-eap/1901/3) and on my Mac, every incremental compilation seems to fail. 
Yesterday night though, I tried on my Windows and "seemed" to work.
I don't know what you can do with those info but if you need anything I'll try what you want.

Do you plan to support incremental compilation or will it never work for some reason ?

**Comment by NitroG42** [comment] 2016-09-06 08:18
Here's a sample that reproduces exactly the issue on my Mac (even at first compile) : 
[MyApplication.zip](https://github.com/realm/realm-java/files/456251/MyApplication.zip)

**Comment by yanex** [comment] 2016-09-08 20:19
@NitroG42 Incremental compilation in kapt is not supported in 1.0.4-eap-100, but will be supported very soon. Stay tuned!

**Comment by beeender** [comment] 2016-09-14 13:53
@NitroG42 Really!!?? haven't tried that before! So which plugin should be applied first? realm or kapt2?

**Comment by NitroG42** [comment] 2016-09-14 13:56
You need to use kotlin 1.0.4-eap-118, and as follow : 
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'

and remove kapt generateStubs as seens here : https://discuss.kotlinlang.org/t/kotlin-1-0-4-eap/1901/3

**Comment by beeender** [comment] 2016-09-14 13:58
Thanks a lot for the information! We will try to update Realm plugin with kapt2!

**Comment by NitroG42** [comment] 2016-09-14 14:01
@yanex will have better info but I think the 1.0.4 version will probably be released soon (it seems stable, at least for me)

**Comment by ShikaSD** [comment] 2016-09-16 21:01
I have set compatibility settings to java 1.7, which solved the issue for me. Hope this will help somebody.

````
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
````

**Comment by yanex** [comment] 2016-09-20 00:06
Please check the https://bintray.com/kotlin/kotlin-dev/kotlin/1.0.5-dev-3143 build as well, it contains some kapt2 fixes.

**Comment by eikaramba** [comment] 2016-09-22 19:27
kotlin 1.0.4 released https://blog.jetbrains.com/kotlin/2016/09/kotlin-1-0-4-is-here/#more-4275

**Comment by kuno** [comment] 2016-09-27 08:16
it seems kotlin 1.0.4 + kapt2 solved this issur for me

**Comment by cmelchior** [comment] 2019-04-26 08:47
This issue appears to be fixed. So closing.

**Closed by cmelchior** 2019-04-26 08:47 UTC
Labels: O:User, T:Bug
