### ISSUE TITLE
Support sorting by property in child object

### ISSUE THREAD

**Issue by snotyak** [realm/realm-java#709] opened 2015-01-02 23:23 UTC
Example:

Using the classes below:
```java
public class TypeA extends RealmObject {
   private String name;
}

public class TypeB extends RealmObject {
    private int number;
    private TypeA someType;
}
```

I can't perform:
```java
Realm realm = Realm.getInstance(this);
RealmQuery<TypeB> query = realm.where(TypeB.class);
query.findAll().sort("someType.name"); // Throws java.lang.IllegalArgumentException: Field 'someType.name' does not exist.

```

**Comment by cmelchior** [comment] 2015-01-05 08:20
Hi @snotyak 
Thank you for a detailed bug report. That feature is currently not supported, but the error message isn't very precise.  I have updated the error message to be more clear until we can add support for this.

**Comment by RobertoArtiles** [comment] 2015-05-13 00:40
+1

**Comment by fuwaneko** [comment] 2015-06-19 16:11
:+1:

**Comment by roughboy** [comment] 2015-06-28 14:39
+1

**Comment by snotyak** [comment] 2015-06-29 14:10
@cmelchior I see that the exception you threw in the merge above is no longer a part of master. Has this been fixed?

**Comment by psyren89** [comment] 2015-09-21 02:55
:+1:

**Comment by dator** [comment] 2015-11-13 17:22
Hello, do you have any ETA on this feature. it will be life saving ! Thanks a lot.

**Comment by mateusgrb** [comment] 2015-12-21 20:57
+1

**Comment by guillermomuntaner** [comment] 2015-12-24 19:59
+1 Query filtering works well with subproperties, so it would make sense that sorting can be used in conjuction.

**Comment by heitorpr** [comment] 2016-01-14 11:53
hey guys, this is solved?

**Comment by gpulido** [comment] 2016-02-14 18:45
+1
I'm trying to implement a RecyclerView backed by a realmResults that is capable to group and sort by any of the properties of the base class, creating a "sectionedAdapter" on the fly.
If I want to group by any of the related RealmObject of the base RealmObject, I also need to order the list by the same property hence the need of sort by child.
Also I'm using retrolambda and Java 8 streams that make the code very clean and straightforward, however, as I can't make RealmObject implement "IComparable" I'm also stuck there:
If I transform the RealmResults into a list to overcome the sorted by child, I need to make the child Icomparable, but I can't...

**Comment by AlokBansal8** [comment] 2016-02-15 19:49
:+1:

**Comment by tgbarker** [comment] 2016-02-16 08:35
+1

**Comment by SergeyTrukhachev** [comment] 2016-03-01 08:34
any updates here? :+1:

**Comment by maasad** [comment] 2016-05-21 08:53
+1

**Comment by AlokBansal8** [comment] 2016-05-21 17:28
It has been more than a year and 4 months and still no update on the feature.

**Comment by mmlii** [comment] 2016-06-02 05:39
+1

**Comment by cmelchior** [comment] 2016-06-02 07:00
This is a duplicate of #672, so moving all the +1's from here to there and closing this as an duplicate.

**Closed** 2016-06-02 07:01 UTC
Labels: T:Duplicate
