### ISSUE TITLE
Out Of Memory Error

### ISSUE THREAD

**Issue by IndianaSloan** [realm/realm-java#6733] opened 2020-01-31 08:20 UTC
I am receiving a crash on Crashlytics with the following exception:

`Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 2147483648 offset: 0 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101`

I understand this issue has been raised before a few times, however I have researched through all of the possible suggestions and cannot find a solution to this crash. This is an app in production for several years and this crash has only started to happen recently. It happens to less than 1% of my users but ironically it is only happening on one specific device - Samsung Galaxy Tab A SM-T510. 

The crash seems to be happening on launch of the app, when trying to get an instance of Realm, rather than when trying to execute a transaction, or perform any other operation. The database size varies in different crashes, they are one of the following:
- 2147483648
- 2013265920
- 1476395008
- 1342177280
- 1207959552

#### Steps I have taken to try and solve:
- [x] I have ensured all open instances of realm are closed as soon as I am finished with them
- [x] I have checked that all transactions are not inside long loops
- [x] I have attempted to migrate Realm to a new version, and delete all of the database

#### Actual Results
`Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 2147483648 offset: 0 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
       at io.realm.Realm.getDefaultInstance(Realm.java:407)
       at com.myapp.android.app.MyApp.initializeIntercom(MyApp.java:215)
       at com.myapp.android.app.MyApp.onCreate(MyApp.java:117)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1158)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6272)
       at android.app.ActivityThread.access$1200(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7100)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)`

#### Steps & Code to Reproduce
I have been unable to reproduce this crash. I have also inflated Realm on my own device to 2.45GB by inserting dummy data, and have yet been unable to reproduce. I have detailed below the function in my Application class where the crash happens.

``` 
private void initializeIntercom() {
        String intercomIdCheck = getString(R.string.intercom_api_id);
        String intercomKeyCheck = getString(R.string.intercom_api_key);
        if (intercomIdCheck.isEmpty() || intercomKeyCheck.isEmpty()) {
            return;
        }

        Realm realm = null;

        try {
            realm = Realm.getDefaultInstance(); <------ LINE 215 where crash happens

            User user = realm.where(User.class)
                    .equalTo("userId", datastore.getUserId())
                    .findFirst();
            if (user != null &&
                    user.settings != null &&
                    user.settings.intercom_enabled == 1) {
                Intercom.initialize(
                        this,
                        getString(R.string.intercom_api_key),
                        getString(R.string.intercom_api_id)
                );
            }
        } catch (Exception ex) {
            MyApp.logThrowable(ex);
        } finally {
            if (realm != null) {
                realm.close();
            }
        }
    }
```

#### Version of Realm and tooling

Realm version(s): 5.12.0

Realm Sync feature enabled: No

Android Studio version: 3.5.3

Android Build Tools version: 28

Gradle version: 5.4.1

Which Android version and device(s): Android 9 - Samsung Tab A SM-T510

**Comment by sdex** [comment] 2020-02-17 11:10
It's something wrong with this device. I've got a lot of OOM crash reports from this particular device too. The realm file is huge. 
```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 503316480 offset: 0 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
       at io.realm.Realm.getDefaultInstance(Realm.java:407)
```
Galaxy Tab A (gt510wifi) - Android 7.1
Galaxy Tab A (2017) (gta2slte) - Android 9

**Comment by nhachicha** [comment] 2020-02-19 22:33
@IndianaSloan the reported size is > 2G, are you expecting such volume of data? is this a normal usage? you can try to [compact](https://realm.io/docs/java/6.0.2/api/io/realm/Realm.html#compactRealm-io.realm.RealmConfiguration-) the Realm to see if this helps on this device

**Comment by IndianaSloan** [comment] 2020-02-19 22:44
Thanks for the suggestions @nhachicha , the size could potentially get this size over time, as I'm not ever clearing data. I have tried contacting realm, and also migrating realm to a new version and wiping realm. Yet still experiencing this crash

**Comment by WeiJieJin** [comment] 2020-08-04 06:23
io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 2013265920 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

**Comment by rubnov** [comment] 2020-08-10 09:54
I'm experiencing the exact same issue and have gone through the same steps to ensure that no realm instances are left open on background threads. The number of global instances is 1, occasionally rising to 2 and back to 1 as background threads close their Realm instances.  

The issue occurs when the app is launched to the background and on the first call to `Realm.getDefaultInstance()`:

98% if the crashes occurred when the app launched to the background. However, it happens to only a a handful our users (<10) and only on a few devices, namely: 

- Samsung Galaxy A10 (Android 10)
- Samsung J4+ (Android 8.1.0)

I am not sure, however, that this suggests a device-specific issue. It could well be that the crash has so far occurred on these devices / to these users only because the Realm DB for their account has bloated to a very large size. 
  
Here is the code where the crash occurs: 

```java
public class PSApplicationClass extends Application implements BeaconConsumer, RequestQueue.RequestFinishedListener {
...
    @Override
    public void onCreate() {
        super.onCreate();
        singleton = this;
        try {

            mRequestQueue = Volley.newRequestQueue(PSApplicationClass.this);
            mRequestQueue.addRequestFinishedListener(PSApplicationClass.this);
            pref = new PassengerPreferencesManager(this);

            Realm.init(PSApplicationClass.this);
            Config = new RealmConfiguration.Builder()
                    .name("myrealm.realm")
                    .schemaVersion(5)
                    .migration(new Migration())
                    .compactOnLaunch(new CompactOnLaunchCallback() {
                        @Override
                        public boolean shouldCompact(long totalBytes, long usedBytes) {
                            // Compact if the file is over 500KB in size and less than 20% 'used'
                            boolean should = (totalBytes > LARGE_REALM_FILE) && (usedBytes / (double) totalBytes) < 0.2;
                            String msg = "Realm totalSize " + totalBytes + " usedBytes " + usedBytes;
                            Utils.appendLog(msg, "I", Constants.REALM);
                            FirebaseCrashlytics.getInstance().log(msg);
                            return should;
                        }
                    })
                    .build();

            Realm.setDefaultConfiguration(Config);

            Realm realm = Realm.getDefaultInsance();  // <-- crashes here!
```

The specific error info in the crash report is: 
```
Fatal Exception: io.realm.exceptions.RealmError
Unrecoverable error. mmap() failed: Out of memory size: 1879048192 offset: 0 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
```

Sizes in the above message vary from 1GB (e.g. 1073741824) to 2GB. 

As seen in my code sample above, I am compacting the DB on launch. However, I am unsure as to whether this is done synchronously or asynchronously, or if there is a way to ensure that  `compactOnLaunch()` has finished before attempting to call `Realm.getDefaultInstance()`. I am also unsure of how compactOnLaunch() reports success/failure.

**Comment by rorbech** [comment] 2020-08-24 06:35
@rubnov Can you share some details on the version of Realm and whether you have sync enabled? We are currently investigating another crash that could be related to apps starting in background and compacting in #6889

**Comment by rubnov** [comment] 2020-08-24 06:45
```
    dependencies {
        classpath "io.realm:realm-gradle-plugin:5.15.1"
        ...
    }
```

We are _not_ using Realm Sync. We have a local Realm db within the app.

**Comment by cmelchior** [comment] 2020-08-26 09:36
@rubnov Are you still using 5.15.1? Is it possible for you to upgrade to 7.0.2? We added some improvements to how we memory map files there which might help solve issues like this.

Before 7.0, we had to map the entire Realm file in one continuous region. This was a problem for large files. Especially if the virtual address space was fragmented. With 7.0 we can now do this in 64 MB blocks.

**Comment by rubnov** [comment] 2020-08-30 14:21
Updated Realm plugin to 7.0.2 but still getting this error. 

Device info: Samsung Galaxy A10
RAM free: 410.47 MB
Disk free: 1.11 GB
Android 10

```
Error getting Realm instance: Unrecoverable error. mmap() failed: Out of memory size: 1879048192 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
```

Again, this happens immediately on launch, in `ApplicationClass.onCreate()` when calling `Realm.getDefaultInstance()` for the first time and from the main thread.

**Comment by cmelchior** [comment] 2020-09-30 05:50
So the Realm you are trying to open 1.8GB. I don't know if your Realm contains that much data, but usually when they get this big it normally points to problems controlling the Realm life cycle which can inflate the file size.

You can read more here:
https://realm.io/docs/java/latest/#faq-large-realm-file-size
https://realm.io/docs/java/latest/#realm-instance-lifecycle
https://realm.io/docs/java/latest/#closing-realms

**Comment by rubnov** [comment] 2020-10-31 10:29
Our app runs for extended periods in the background, and keeps a single realm instance (that of the main thread) alive all the time. Is this the cause of the bloating up of the database? If so - it is a serious design flaw in Realm library. 

Why is keeping a Realm instance in memory causing the Realm database file to grow indefinitely and disproportionally? Is this caused by the "versioning" of Realm objects? Is there a way to configure Realm NOT to keep multiple versions of objects? 

In order to work around this Realm _by-design_ limitation, I would have to refactor the entire app code base to close Realm instances on a function, Fragment or Activity boundaries. This would cost me weeks of work. Very frustrating!

**Comment by cmelchior** [comment] 2020-11-05 12:47
It should be fine to keep Realms open on threads with Loopers, like the main thread. Those are automatically kept up to date. You can read more about that here: https://academy.realm.io/posts/threading-deep-dive/

So if you are experiencing bloat it must happen for some other reason.

Note, there are number of methods that can be used to debug things like this.

https://realm.io/docs/java/10.0.0/api/io/realm/RealmConfiguration.Builder.html#maxNumberOfActiveVersions-long-
https://realm.io/docs/java/10.0.0/api/io/realm/Realm.html#getGlobalInstanceCount-io.realm.RealmConfiguration-
https://realm.io/docs/java/10.0.0/api/io/realm/Realm.html#getLocalInstanceCount-io.realm.RealmConfiguration-

**Comment by rubnov** [comment] 2020-11-06 07:46
OMG, I've just found out that Realm does not support **cascading deletes**. This means that when a `RealmObject` is deleted, all the objects related to it (e.g. within `RealmList` propereties) are NOT deleted ?!?!?

**Comment by ianpward** [comment] 2020-11-06 15:30
@rubnov 10.0 version of the SDKs contains an implementation of cascading deletes if you use embedded objects - 
https://developer.mongodb.com/article/realm-database-cascading-deletes#cascading-deletes

**Comment by rubnov** [comment] 2020-11-06 21:24
@ianpward I'm on Android. Are EmbeddedObjects also available in realm-plugin 10.0.0 for Java?

**Comment by ianpward** [comment] 2020-11-06 21:27
Yes

**Comment by clementetb** [comment] 2020-11-16 11:54
@rubnov Were you able to fix the issue?

**Comment by rubnov** [comment] 2020-11-16 13:31
It was the cascading delete issue indeed. The database was filling up with thousands of "zombie" objects - whose owner objects have been deleted with `deleteFromRealm()`. 

I had to refactor all RealmObject subclasses and add a custom delete method `cascadeDelete()`, which deleted all embedded RealmObjects and RealmList relationships before call `this.deleteFromRealm()`. 

So sad this feature was overlooked by Realm until version 10 (!).

**Comment by ianpward** [comment] 2020-11-16 14:26
@rubnov Thanks for your feedback on this free and open-source database.

I'm not sure I understand your comment. Are you saying that with Embedded Objects, deleting parent objects is not cascading deletes?

**Comment by rubnov** [comment] 2020-11-17 12:39
@ianpward I have not integrated Realm v.10. It mandated too many changes to my code. Instead, I continue to use version 7 for now and added my own `cascadeDelete()` methods to RealmObject subclasses.

**Comment by ianpward** [comment] 2020-11-17 15:26
I see - well I guess that's a decision that you only you, as the product manager of your app, can make. If you ever want us to handle cascading deletes for you - you can upgrade to v10

**Closed** 2020-11-30 14:02 UTC
Labels: O-Community, T-Help
