### ISSUE TITLE
MissingLibraryException librealm-jni.so on Android 4.x Realm 5.15.1

### ISSUE THREAD

**Issue by hzy00** [realm/realm-java#6635] opened 2019-10-11 09:35 UTC
#### Actual Results
Appliction crash while init realm
```
Caused by com.getkeepsafe.relinker.MissingLibraryException
librealm-jni.so
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary$757ca6fb (ApkLibraryInstaller.java:123)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary$11a583b2 (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:57)
io.realm.internal.RealmCore.loadLibrary (RealmCore.java:60)
io.realm.Realm.initializeRealm (Realm.java:322)
io.realm.Realm.init (Realm.java:265)
```

#### Version of Realm and tooling
I doesn't use app bundle. And i'm sure that the .so file is in the package.
Realm version(s): realm java 5.15.1

Realm Sync feature enabled: Yes

Android Studio version: 3.5

Android Build Tools version: 3.3.1

Gradle version: 4.10.1

Which Android version and device(s): 
![image](https://user-images.githubusercontent.com/8287934/66641414-4bceed00-ec4d-11e9-95b7-222dd19cffa3.png)
![image](https://user-images.githubusercontent.com/8287934/66641434-538e9180-ec4d-11e9-85ce-f0329ca063bf.png)

**Comment by Zhuinden** [comment] 2019-10-11 13:33
Do you have any other native libraries that could be 32-bit?

**Comment by hzy00** [comment] 2019-10-18 03:35
Yeah, I have some other native library. But I've used 'Android splits' tenc. The app would be splitted into multiple package to support 32-bit or 64-bit. So, I don't think it's the key point.

**Comment by cmelchior** [comment] 2019-11-26 13:50
Actually it might. If people are side-loading apps through other means than the app store there is a fairly high chance they are loading the architecture for their device which will result in crashes like this.

Unfortunately, there isn't much we can do about this, except trying to come up with a better error message (which wouldn't help end users though).

Unless you reproduce this issue I'll assume this is the root cause and close the issue, but feel free to re-open if you have more information about it.

**Closed** 2019-11-26 13:52 UTC
Labels: O-Community, Pipeline-Triage
