### ISSUE TITLE
RealmFileException: Top ref outside file

### ISSUE THREAD

**Issue by JoyHong** [realm/realm-java#6497] opened 2019-04-22 10:04 UTC
# main(1)

io.realm.exceptions.RealmFileException

Unable to open a realm at path '/data/data/packageName/files/userprofile.realm': Top ref outside file (size = 108824). top_ref[0]: 1AA78, top_ref[1]: 1A9F8, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0 Path:. (Top ref outside file (size = 108824). top_ref[0]: 1AA78, top_ref[1]: 1A9F8, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0 Path: /data/data/packageName/files/userprofile.realm) (/data/data/packageName/files/userprofile.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

The relation crash report so much that i don't known how to fix it, can u please give me a help?

**Comment by bmunkholm** [comment] 2019-05-06 11:36
@JoyHong IS this from a user or something you can reproduce? Which version of Realm are you using?
Please use the issue template to report issues as that ensures to answer some questions.

**Comment by JoyHong** [comment] 2019-10-25 11:00
Sorry，the issue is reported from Google Play console

I can not reproduce it

**Comment by cmelchior** [comment] 2019-10-25 11:03
Are you using encryption?

**Comment by JoyHong** [comment] 2019-10-28 05:41
No

**Comment by Zhuinden** [comment] 2019-10-28 11:34
Are you by any chance using pre-bundled Realm file or downloading it from remote?

File copying can fail and you'd end up with an incomplete file. It's happened to me before.

**Comment by lucaspommateau** [comment] 2020-07-28 09:20
Hello, 
I have the same error in production, on an Android application.

- Realm version: 6.1.0
<details>
  <summary>Stacktrace</summary>  

  ```kotlin
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.groupeseb.moncookeo/files/datatracking_realm.realm': Top ref outside file (size = 458752). top_ref[0]: 3031500000410E0, top_ref[1]: 46020200, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0 Path:Exception backtrace:
<backtrace not supported on this platform>. (Top ref outside file (size = 458752). top_ref[0]: 3031500000410E0, top_ref[1]: 46020200, mnemonic: 54 2D 44 42, fmt[0]: 9, fmt[1]: 9, flags: 0 Path: /data/data/com.groupeseb.moncookeo/files/datatracking_realm.realm
Exception backtrace:
<backtrace not supported on this platform>) (/data/data/com.groupeseb.moncookeo/files/datatracking_realm.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:337)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
       at io.realm.Realm.getDefaultInstance(Realm.java:407)
       at com.groupeseb.moddatatracking.api.data.local.EventLocalDataSource$12.run(EventLocalDataSource.java:206)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8347)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
  ```
</details>

- Device: 
![image](https://user-images.githubusercontent.com/2082033/88645212-291aa180-d0c4-11ea-8686-82e207812a38.png)
- Version:
![image](https://user-images.githubusercontent.com/2082033/88645257-359efa00-d0c4-11ea-826d-8e1cdaa41cf6.png)
- I do not use encryption
- I do not use pre-bundled realm file or downloaded one
I have no reproduction 😞

**Comment by cmelchior** [comment] 2020-08-26 08:51
Since the underlying implementation changed drastically in Realm Java 7.0.0. I'm closing this as outdated. Please re-open if you are still seeing this on 7.0.2 and above.

**Closed by cmelchior** 2020-08-26 08:51 UTC
Labels: O-Community, Pipeline-Waiting-for-User, Reproduction-Required, T-Bug-Crash
