### ISSUE TITLE
Android updated realm-gradle-plugin from 5.12 to 5.15 throws exception

### ISSUE THREAD

**Issue by tloshi** [realm/realm-java#6619] opened 2019-09-18 08:05 UTC
#### Goal
  I updated realm from 5.12 to 5.15 and without any changes on the models I got this exception when updating the app, but if I install as a fresh apk it will work.
 
java.lang.IllegalStateException: The following changes cannot be made in additive-only schema mode:
    - Property '__ResultSets.created_at' has been made required.
    - Property '__ResultSets.updated_at' has been made required.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
 

#### Steps & Code to Reproduce
 Calling like this:
          Realm.setDefaultConfiguration(SyncConfiguration.automatic())
          mRealm = Realm.getDefaultInstance()
 
#### Version of Realm and tooling

Realm version(s): 5.12 <-> 5.15.1

Realm Sync feature enabled: Yes 

Android Studio version: 3.5

Android Build Tools version: 29

Gradle version: 3.5.0

Which Android version and device(s): All versions

**Comment by cmelchior** [comment] 2019-09-18 11:50
Hmm, this could look like something we might have caused by accident. I'll look into it. Thanks for reporting.

**Comment by cmelchior** [comment] 2019-09-30 12:41
This should be fixed in Realm Java 5.15.2

**Closed by cmelchior** 2019-09-30 12:41 UTC
Labels: O-Community, T-Bug
