### ISSUE TITLE
RealmPrimaryKeyConstraintException: Value already exists: 0

### ISSUE THREAD

**Issue by jpaseneta** [realm/realm-java#3099] opened 2016-07-01 06:06 UTC
hi,

i'm practically new to this realm and have encountered a lot of problems here and then as i was testing out. this problem is now probably bugging me for a day now.

heres my realmconfiguration on my application class:

```java
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .name(Realm.DEFAULT_REALM_NAME)
                .schemaVersion(0)
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);`
```

I have this model now:

```java
public class RealmUser extends RealmObject {

    private int id;
    private String name;
    private String username;
    private String email;
    private String phone;
    private String website;

    public RealmUser(){
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }
```

my gson and my test insert to realm db:

```java
GsonBuilder gsonBuilder = new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")
                .setExclusionStrategies(new ExclusionStrategy() {
            @Override
            public boolean shouldSkipField(FieldAttributes f) {
                return f.getDeclaringClass().equals(RealmObject.class);
            }

            @Override
            public boolean shouldSkipClass(Class<?> clazz) {
                return false;
            }
        });
        try {
            gsonBuilder.registerTypeAdapter(Class.forName("io.realm.RealmUserRealmProxy"), new RealmUserSerializer());
        }catch (Exception e){}
        gson = gsonBuilder.create();
```

```java
RealmUser test = new RealmUser();
        test.setName("John Doe");
        realm.beginTransaction();
        realm.copyToRealm(test);
        realm.copyToRealm(test);
        realm.commitTransaction();
```
Yesterday i set the primary key to

```java
@PrimaryKey
private int id;
```
and decided to remove it today. now im having this error:

> Caused by: io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0
                                                                            at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:721)
                                                                            at io.realm.internal.Table.addEmptyRow(Table.java:414)
                                                                            at io.realm.Realm.createObject(Realm.java:688)
                                                                            at io.realm.RealmUserRealmProxy.copy(RealmUserRealmProxy.java:390)
                                                                            at io.realm.RealmUserRealmProxy.copyOrUpdate(RealmUserRealmProxy.java:381)
                                                                            at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:99)
                                                                            at io.realm.Realm.copyOrUpdate(Realm.java:1272)
                                                                            at io.realm.Realm.copyToRealm(Realm.java:727)
                                                                            at com.smartwavedev.genie.Activity.MainActivity.onCreate(MainActivity.java:200)

#### Version of Realm and tooling
Realm version(s): 1.1.0
Android Studio version: 2.1.1
Which Android version and device: ?

**Comment by jpaseneta** [comment] 2016-07-01 06:24
ofcourse i did a lot of clean and rebuild,  also deleted exploded-aar generated of realm, as well ass the ones in gradle/cache. but still same error.

**Comment by beeender** [comment] 2016-07-01 06:28
Hello, check this answer http://stackoverflow.com/questions/30162473/primary-key-constraint-broken-value-already-exists-0

**Comment by jpaseneta** [comment] 2016-07-01 06:38
hi @beeender , i've seen that.. I don't use `Realm.createObject()` but rather
`RealmUser test = new RealmUser();`. im not sure whats the implementation details between them.

also i have set my member variable id to be my primary key previously, but now i decided to remove it. I think the realmuserrealmproxy class isn't reflecting my changes to my` RealmUser extends Realm Object` class

**Comment by stk1m1** [comment] 2016-07-01 06:50
Hi @jpaseneta 

There are two points I'd like to help you with.

1. Please keep `@PrimaryKey` annoation on at least one. It guides Realm to copy or update an object according to a primary key value.
2. I see you call `copyToRealm()` twice. I'd urge you to change it to `copyToRealmOrUpdate()` instead. You can read more about it at <https://realm.io/docs/java/latest/#primary-keys>.

If the issue persists, please let us know. Thanks!

**Comment by jpaseneta** [comment] 2016-07-01 06:55
hi @stk1m1 thank you for the clean highlight. im also new to this so im only clicking insert code..

It was actually my intention to have duplicate data in my RealmUser table.. in that sense with your solution, i'm afraid im won't be able to achieve such?

**Comment by cmelchior** [comment] 2016-07-01 06:57
Hi @jpaseneta 
Can you post your `RealmUserProxy` class that Realm generated? It sounds like it still thinks you have a primary key defined.

**Comment by jpaseneta** [comment] 2016-07-01 07:01
@cmelchior yes i think so too. since im testing, im changing a lot in my models. how do i make sure every run a new schema is generated?

please see https://gist.github.com/jpaseneta/cb4f9a6ea969a562308db191309d2fc1

**Comment by stk1m1** [comment] 2016-07-01 07:30
@jpaseneta 
Could you turn of *Instant Run* in Android Studio and see if the issue persists with Realm?. You can read more it in #2139.

**Comment by jpaseneta** [comment] 2016-07-01 07:39
turned off instant run, but to no avail.

**What worked for me:**
uninstall the app manually then clean->rebuild->deploy. Damn, i wasted an almost a day trying to figure this out. :(

**Comment by stk1m1** [comment] 2016-07-01 07:55
@jpaseneta 

Good to hear the issue is solved. I'm closing the issue for now. Please let us know if you experience the same problem again.

**Closed by stk1m1** 2016-07-01 07:55 UTC
Labels: T:Help
