### ISSUE TITLE
Fluent setters for RealmObject

### ISSUE THREAD

**Issue by VedavyasBhatNomadly** [realm/realm-java#1653] opened 2015-10-23 13:17 UTC
I have a `RealmObject` with a fluent setter like so:

    class X extends RealmObject {
        private String member;
    
        public X setMember(String member) {
            this.member = member;
            return this;
        }
    }

This doesn't seem possible because the generated class `XRealmProxy` has a non-fluent setter, so `setMember` of `XRealmProxy` cannot override `setMember` of `X`.
Any way I can have fluent setters in my `RealmObject`s?

**Comment by cmelchior** [comment] 2015-10-23 13:25
Hi @VedavyasBhatNomadly Unfortunately not at this point, as right now RealmObjects has to be pure POJO's. Having fluent setters will be possible once we implement https://github.com/realm/realm-java/issues/909 however, so you can follow progress on that one.

I'll close this issue as an duplicate of #909

**Closed by cmelchior** 2015-10-23 13:25 UTC

**Comment by kneth** [comment] 2015-10-23 13:34
I guess you simply wish to be able to write `person.setName("John").setAge(16);`.  The Realm setters do not return the object as you have noticed.

It is not possible to write custom setters and getters (see https://realm.io/docs/java/latest/#faq "Why do I need to have getters and setters for all my fields?").

The short answer is that is no simple or elegant way to do it.
