### ISSUE TITLE
Not Receiving Notification when Field is Changed

### ISSUE THREAD

**Issue by qtstc** [realm/realm-java#4605] opened 2017-05-06 02:45 UTC
For the sample code below, I expect to receive notification on Person every time the name of the dog is changed. This was working in 3.0.0 but not anymore in 3.1.*
```java
public class IntroExampleActivity extends Activity {

  public static final String TAG = IntroExampleActivity.class.getName();

  private Realm realm;
  private int count = 0;

  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_realm_basic_example);
    realm = Realm.getDefaultInstance();
    realm.executeTransaction(new Realm.Transaction() {
      @Override public void execute(Realm realm) {
        realm.deleteAll();
        Person person = realm.createObject(Person.class);
        Dog c = realm.createObject(Dog.class);
        c.name = "the dog " + count;
        person.setDog(c);
      }
    });
    realm.where(Person.class).findFirstAsync().<Person>asObservable().filter(
        new Func1<Person, Boolean>() {
          @Override public Boolean call(Person person) {
            return person.isValid() && person.isLoaded();
          }
        }).subscribe(new Action1<Person>() {
      @Override public void call(Person person) {
        TextView t = (TextView) findViewById(R.id.result_text);
        t.setText(person.getDog().name);
      }
    });

    Button b = (Button) findViewById(R.id.add_button_1);
    b.setOnClickListener(new View.OnClickListener() {
      @Override public void onClick(View v) {
        realm.executeTransactionAsync(new Realm.Transaction() {
          @Override public void execute(Realm realm) {
            realm.where(Dog.class).findFirst().name = "the dog " + count;
            count += 1;
          }
        });
      }
    });
  }

  @Override protected void onDestroy() {
    super.onDestroy();
    realm.close();
  }
}
```

**Comment by zaki50** [comment] 2017-05-06 06:49
It is an intended behavior.
Previous behavior was a bug and fixed in 3.1 (#3894).

**Closed by zaki50** 2017-05-06 06:49 UTC

**Comment by qtstc** [comment] 2017-05-08 22:14
What is the recommended way for listening to changes in the Dog field of Person in 3.1? 

It seems that I would need to have two listeners, one on the Dog class and another one on the Person class:
```java
realm.where(Person.class).findFirstAsync().addChangeListener(new RealmObjectChangeListener<Person>() {
            @Override public void onChange(Person person, ObjectChangeSet changeSet) {
                if(changeSet != null) {
                    for(String changedField : changeSet.getChangedFields()) {
                        if(changedField.equals("dog")) {
                            // Also need to unregister change listener on the old Dog instance
                            // What's the best way to do that?
                            person.getDog().addChangeListener(new RealmChangeListener<Dog>() {
                                @Override public void onChange(Dog dog) {
                                    // do the usual stuff
                                }
                            });
                        }
                    }
                }
            }
        });
```
Is there a better way for doing this?

**Comment by Zhuinden** [comment] 2017-05-08 22:45
Considering you don't store the RealmResults which means it can get GC'd and there is no guarantee that `onChange()` can be called on a GC'd results, it might help if you provide more context to what you are doing.

**Comment by qtstc** [comment] 2017-05-08 23:14
I can store the RealmResult. Yeah I was using asObservable before 3.1, but asObservable doesn't support changeSet yet so have to switch to addChangeListener.

I am building a music app with a CurrentlyPlaying RealmObject. It has three fields: queueIndex (int), queue (which is a RealmObject), and playingSong (which is also a RealmObject). 

I was listening to changes on the CurrentlyPlaying RealmObject and then update the player in a Service. So I would want the change listener to be triggered when the queue/playingSong changed or when the content of queue/playingSong changed.
