### ISSUE TITLE
Too many open files after upgrade to 1.1.0

### ISSUE THREAD

**Issue by AlexLardschneider** [realm/realm-java#3199] opened 2016-07-20 14:26 UTC
#### Goal

> Add data to realm

#### Expected Results

> App crashes after a while with a "Too many open files" error

#### Actual Results

> io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in io_realm_internal_SharedGroup.cpp line 113
                                                                        at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
                                                                        at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
                                                                        at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
                                                                        at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
                                                                        at io.realm.BaseRealm.<init>(BaseRealm.java:81)
                                                                        at io.realm.Realm.<init>(Realm.java:140)
                                                                        at io.realm.Realm.createAndValidate(Realm.java:240)
                                                                        at io.realm.Realm.createInstance(Realm.java:220)
                                                                        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
                                                                        at io.realm.Realm.getDefaultInstance(Realm.java:166)
                                                                        at com.davale.sasabus.realm.UserRealmHelper.addBeacon(UserRealmHelper.java:504)
                                                                        at com.davale.sasabus.beacon.busstop.BusStopBeaconHandler.validateBeacon(BusStopBeaconHandler.java:363)
                                                                        at com.davale.sasabus.beacon.busstop.BusStopBeaconHandler.updateBeacons(BusStopBeaconHandler.java:290)
                                                                        at com.davale.sasabus.beacon.BeaconHandler.lambda$onBeaconServiceConnect$0(BeaconHandler.java:103)
                                                                        at com.davale.sasabus.beacon.BeaconHandler.access$lambda$0(BeaconHandler.java)
                                                                        at com.davale.sasabus.beacon.BeaconHandler$$Lambda$1.didRangeBeaconsInRegion(Unknown Source)
                                                                        at org.altbeacon.beacon.BeaconIntentProcessor.onHandleIntent(BeaconIntentProcessor.java:65)
                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:145)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

~2 seconds after I get the first exception I get the following one:
> java.lang.NullPointerException:` Null pointer exception during instruction 'monitor-enter v1'
                                                                at io.realm.internal.SharedGroup.finalize(SharedGroup.java:224)
                                                                at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:209)
                                                                at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:192)
                                                                at java.lang.Thread.run(Thread.java:818)

#### Steps & Code to Reproduce

> None, but the issue did not appear in v1.0.0, whereas it does in 1.1.0
The crash happens when I execute the following method 10-20 times, although the realm gets closed as many times as it gets opened, I already verified that. This issue happens while the app is running in the background in a bound service.

#### Code Sample

```java

Realm realm = Realm.getDefaultInstance();

realm.beginTransaction();

Beacon realmObject = realm.createObject(Beacon.class);
realmObject.setType(type);
realmObject.setMajor(major);
realmObject.setMinor(minor);
realmObject.setTimeStamp((int) (System.currentTimeMillis() / 1000));

realm.commitTransaction();
realm.close();

```

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.2 Preview 6

Which Android version and device: 

>Galaxy S5 running 6.0.1 Cyanogenmod
>Galaxy A3 running 5.0.2 stock
>Galaxy A3 running 4.4.4 stock

All devices have enough free RAM and storage when the issue happens, so I guess that isn't the problem.

**Comment by stk1m1** [comment] 2016-07-21 03:47
Hi @AlexLardschneider,

1. Could you reproduce this on other devices than Samsung?
2. Can you share a model project that shows this error?

**Comment by beeender** [comment] 2016-07-21 04:11
Dup to #3197 . @AlexLardschneider please share your information under #3197 since they are the same issue. And I am closing this now. Thanks a lot!

**Closed by beeender** 2016-07-21 04:11 UTC
Labels: S:Waiting For User, T:Duplicate, T:Help
