### ISSUE TITLE
out of memory when open an instance

### ISSUE THREAD

**Issue by stanchu** [realm/realm-java#2968] opened 2016-06-09 07:00 UTC
#### Goal

solve out of memory exception

#### Expected Results

no exception

I have a realm DB around 20k records
4 threads are using the DB: 
- Main thread keeps instance always open
- 3 Looper threads that open an instance every time they need to use the Realm DB

#### Actual Results

io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 201326592 offset: 0 in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.<init>(SharedGroup.java:64)
	at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
	at io.realm.BaseRealm.<init>(BaseRealm.java:77)
	at io.realm.Realm.<init>(Realm.java:138)
	at io.realm.Realm.createAndValidate(Realm.java:269)
	at io.realm.Realm.createInstance(Realm.java:249)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
	at io.realm.Realm.getInstance(Realm.java:213)
	at com.freshub.kitchenconnect.module.domain.logic.database.DatabaseManager.getTempLocalRealm(DatabaseManager.java:946)
	at com.freshub.kitchenconnect.module.domain.logic.database.DatabaseManager.getLocalRealm(DatabaseManager.java:920)
	at com.freshub.kitchenconnect.module.domain.logic.database.DatabaseManager.isCategoryTreeAvailable(DatabaseManager.java:234)
	at com.freshub.kitchenconnect.module.domain.logic.remote_update.RemoteUpdateMonitor.validateLastDeltaTime(RemoteUpdateMonitor.java:87)
	at com.freshub.kitchenconnect.module.domain.logic.remote_update.RemoteUpdateMonitor.checkForUpdates(RemoteUpdateMonitor.java:64)
	at com.freshub.kitchenconnect.module.domain.logic.remote_update.RemoteUpdateMonitor.checkForUpdatesAndReschedule(RemoteUpdateMonitor.java:56)
	at com.freshub.kitchenconnect.module.domain.logic.remote_update.RemoteUpdateMonitor.access$lambda$2(RemoteUpdateMonitor.java)
	at com.freshub.kitchenconnect.module.domain.logic.remote_update.RemoteUpdateMonitor$$Lambda$3.execute(Unknown Source)
	at com.freshub.kitchenconnect.module.domain.logic.concurrency.ConcurrencyController.executeAndCrashOnException(ConcurrencyController.java:216)
	at com.freshub.kitchenconnect.module.domain.logic.concurrency.ConcurrencyController.lambda$scheduleOnRemoteUpdateThread$72(ConcurrencyController.java:161)
	at com.freshub.kitchenconnect.module.domain.logic.concurrency.ConcurrencyController.access$lambda$12(ConcurrencyController.java)
	at com.freshub.kitchenconnect.module.domain.logic.concurrency.ConcurrencyController$$Lambda$13.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.os.HandlerThread.run(HandlerThread.java:61)

#### Steps & Code to Reproduce

I changed the code that only main thread will have an instance open after a lot of out of memory crashes occurred. This reduced the exceptions but not solve it completely.

#### Code Sample

```java
public Realm getTempLocalRealm()
    {
        Realm res = null;

        Context cntx = ConcurrencyController.getContextRealmOfThread() != null ? ConcurrencyController.getContextRealmOfThread() : this.context;
        String dbDir = ConcurrencyController.getRealmDirOfThread() != null ? ConcurrencyController.getRealmDirOfThread() : this.getDbDir();

        try
        {

            File dir = cntx.getDir(dbDir, Context.MODE_PRIVATE);
            // Create the Realm configuration
            RealmConfiguration realmConfig = new RealmConfiguration.Builder(dir).build();

            // Open the Realm for the thread.
            res = Realm.getInstance(realmConfig);
            setCounter(1);

        }
        catch (Exception e)
        {
            e.printStackTrace();

        }
        return res;
    }
```
#### Version of Realm and tooling
Realm version(s):  0.89.1

Android Studio version: 2.1.2

Which Android version and device: 4.4.2, Samsung tablet SM-T320

**Comment by stk1m1** [comment] 2016-06-09 08:21
hi @stanchu

It's hard to tell the cause of the error with short code snippet. Could you share a very simple project that could reproduce your error with us as help@realm.io ?  

One thing I can point is you're still using `0.89.1`, and it does not have all the improvements we've made so far to our latest release 1.0.0.

**Comment by kneth** [comment] 2016-06-10 09:31
@skyisle has sent files: https://secure.helpscout.net/conversation/212903691/4794/?folderId=367748 (only accessible by Realm members)

**Comment by stk1m1** [comment] 2016-06-10 09:36
@kneth 

Replied in helpscout. @beeender identified that @stanchu's issue has been addressed in v1.0.0. I'll look for his reply.

**Comment by emanuelez** [comment] 2016-06-19 10:55
Can this issue be closed?

**Comment by stk1m1** [comment] 2016-06-19 11:00
@stanchu @emanuelez 

I'm closing this issue.

**Closed by stk1m1** 2016-06-19 11:00 UTC
Labels: S:Waiting For User, T:Help
