### ISSUE TITLE
Too many open files after upgrade to 1.1.0

### ISSUE THREAD

**Issue by johnryan** [realm/realm-java#3197] opened 2016-07-19 23:07 UTC
#### Goal

> What do you want to achieve?

Not have the app crash

> ?

#### Actual Results

Seeing some unusual stack traces:

```
java.lang.IllegalArgumentException: Illegal Argument: open("/data/data/com.truly.truly/files/default.realm.management/log_access") failed: Too many open files path: /data/data/com.truly.truly/files/default.realm.management/log_access in io_realm_internal_SharedGroup.cpp line 188
```

```
java.lang.IllegalArgumentException: Illegal Argument: open("/data/data/com.truly.truly/files/default.realm.management/log_access") failed: Too many open files path: /data/data/com.truly.truly/files/default.realm.management/log_access in io_realm_internal_SharedGroup.cpp line 188
```

#### Steps & Code to Reproduce

The full stack traces don't reveal much additional useful information and no substantial changes that would cause may more realms to be created. Any suggestions for debugging would be appreciated.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1

Which Android version and device: Various devices and operating systems in production environment

**Comment by beeender** [comment] 2016-07-20 02:18
Is it something you can reproduce with you devices? Can you list some devices which have this problem so we can try to reproduce in our side? thanks!

**Comment by johnryan** [comment] 2016-07-20 02:31
Sure, here are the devices that have seen crashes:
Samsung SM-S820L (4.4.4)
Motorola XT1030 (4.4.4)
LG VS425 (5.1.1)
Nexus 6P (6.0.1)

I haven't yet been able to reproduce it on a device locally but I will be trying to get more information. Please let me know if there's any more info I can provide, and i'll post here if i find anything.

**Comment by beeender** [comment] 2016-07-20 02:45
Below information might be helpful:

1. Your `RealmConfiguration`
2. How many different `RealmCongifuration`s are you using in the app
3. Do you open other files in your app (both in java and JNI), are they properly closed after using?

**Comment by beeender** [comment] 2016-07-20 02:54
Also, can you see from the log, is it the first time in the app to open a Realm instance?

**Comment by johnryan** [comment] 2016-07-20 03:09
1) Realm configuration is nothing exciting:

```
  RealmConfiguration defaultConfig = new RealmConfiguration.Builder(this)
                .schemaVersion(1)
                .migration(new TrulyMigration())
                .build();

        Realm.setDefaultConfiguration(defaultConfig);
```

2) I only have the one configuration

3) I don't think there are any other files being opened.

4) Now that you mention it i think in some cases it is the first time the realm is opened, when the app crashes we upload some logs and most of the crashes seem to have no logs at all, leading me to believe it crashed the first time it started after install.

**Comment by Zhuinden** [comment] 2016-07-20 14:16
Is the initialization in `Application.onCreate()`, or do you wait until at least an Activity is started?

I've seen some weird things happening on some Samsung phones where `Application.onCreate()` didn't have the data folder yet and opening the Realm failed.

**Comment by johnryan** [comment] 2016-07-20 14:53
the RealmConfiguration code above is called in Application.onCreate(), but it has been there for several releases with no similar crashes.

**Comment by beeender** [comment] 2016-07-20 17:21
What is the previous Realm version you were using before `1.1.0`?

**Comment by johnryan** [comment] 2016-07-20 17:57
Before this I was using 1.0.0.

**Comment by zaki50** [comment] 2016-07-21 04:22
Another developer saw the same error on his app http://twitter.com/_yshrsmz/status/755779290503876609

**Comment by beeender** [comment] 2016-07-21 04:23
Information transferred from #3199 

> The crash happens when I execute the following method 10-20 times, although the realm gets closed as many times as it gets opened, I already verified that. This issue happens while the app is running in the background in a bound service.

Code Sample

```
Realm realm = Realm.getDefaultInstance();

realm.beginTransaction();

Beacon realmObject = realm.createObject(Beacon.class);
realmObject.setType(type);
realmObject.setMajor(major);
realmObject.setMinor(minor);
realmObject.setTimeStamp((int) (System.currentTimeMillis() / 1000));

realm.commitTransaction();
realm.close();
```

**Comment by AlexLardschneider** [comment] 2016-07-21 09:08
1.
```java

new RealmConfiguration.Builder(context)
                .name(DB_NAME)
                .schemaVersion(DB_VERSION)
                .assetFile(context, DB_NAME)
                .modules(new Module())
                .build()

new RealmConfiguration.Builder(context)
                .name(DB_NAME)
                .schemaVersion(DB_VERSION)
                .modules(new UserDataModule())
                .migration(new Migration())
                .build();

```

Crash happens with both configurations.

2. Using two configurations
3. Yes, the app opens some files, but closes them correctly.

**Comment by GiorgosOikonomou** [comment] 2016-07-22 15:42
Getting the same error

```
Fatal Exception: io.realm.exceptions.RealmIOException: Failed to access: . open("/data/data/myapp/files/db/db.management/log_access") failed: Too many open files path: /data/data/myapp/filed/db/db.management/log_access
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
       at io.realm.internal.SharedGroup.(SharedGroup.java)
       at io.realm.internal.SharedGroupManager.(SharedGroupManager.java)
       at io.realm.BaseRealm.(BaseRealm.java)
       at io.realm.Realm.(Realm.java)
       at io.realm.Realm.createAndValidate(Realm.java:240)
       at io.realm.Realm.createInstance(Realm.java:220)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
       at io.realm.Realm.getDefaultInstance(Realm.java:166)
```

**Comment by beeender** [comment] 2016-07-26 06:48
@johnryan @AlexLardschneider @GiorgosOikonomou 
If you can reproduce this issue on any device you have, please hep to run this attached apk and tell me what is the results shows on the screen.

[MaxFD_1.apk.zip](https://github.com/realm/realm-java/files/383175/MaxFD_1.apk.zip)

From 1.1.0, we have a change in the underlying storage engines which is using more file descriptors for internal lock files (12+ files for every Realm in one thread).  I checked my devices, the limitation of file descriptors can be opened for a process is around 1000.

So what is the max count of threads running at the same time opening a Realm instance at the same time? If you can reproduce the issue, one way to check this:

```java
try {
    // Here is the place which throw the exception
    Realm realm = Realm.getInstance(realmConfig);
    // ...
} catch (RealmIOException e) {
    Log.e("TTT", e); // Set a breakpoint here
}
```

When the debugger stops, do

```
adb shell lsof | grep <package_name>
```

Please let us know the output. Thanks!

**Comment by yshrsmz** [comment] 2016-07-26 07:30
Hi, I also had same issue on some device(Sony SO-02G), and tried the apk.
it shows 998. hope it helps

**Comment by beeender** [comment] 2016-07-26 07:34
@yshrsmz 
1. How many different Realm configurations are you using?
2. How many threads which is using Realm could exist at the same time?
3. Is it possible some Realm instance are not closed after using?

**Comment by yshrsmz** [comment] 2016-07-26 07:55
@beeender 
1. 1 configuration
2. I'm not sure since my app runs transactions and queries on RxJava's io scheduler
3. could be, but shouldn't be so many

**Comment by Zhuinden** [comment] 2016-07-26 08:35
In that case the code in which RxJava opens and closes the Realm instance it uses on the `io()` scheduler is required to make any analysis on what is happening.

**Comment by beeender** [comment] 2016-07-26 09:32
@johnryan @AlexLardschneider @GiorgosOikonomou @yoshyosh 

@zaki50 made a java class to show how many Realm instances are opened, the class can be found https://gist.github.com/zaki50/9d8f0eacf6be05a66c372c0002164e3c#file-realmutil-java-L123 .

Just add the file into your project and call `RealmUtil.dumpRealmCount()` at the place where the crash could happen. It returns a string to show how many Realm instances are opened. (Not quite sure about your scenarios, maybe the opened Realm number is not fixed. But it should not be a big number either I think. Otherwise maybe there are some unused instance is not closed?)

**Comment by zaki50** [comment] 2016-07-26 09:52
@johnryan @AlexLardschneider @GiorgosOikonomou @yoshyosh

Please make `io.realm` package in your app project and put `RealmUtil.java` into that package.

**Comment by diegomontoya** [comment] 2016-07-27 04:29
@beeender 

>  (12+ files for every Realm in one thread). 

What is the range of 12+? 12-20? or something dynamic based on number of open transactions/queries? We have encountered this issue for our case where we only open db in 2 specific persistent threads and only perform write/transactions in 1 of them. We have about 10 realms/configs. It is possible they are all open at the same time.

**Comment by dinhthaidaica** [comment] 2016-07-27 07:44
@beeender And @zaki50 
I have the same problem, my log was 
`io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in io_realm_internal_SharedGroup.cpp line 113
                                                                               at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
                                                                               at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
                                                                               at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
                                                                               at io.realm.internal.SharedGroupManager.compact(SharedGroupManager.java:177)
                                                                               at io.realm.BaseRealm.compactRealm(BaseRealm.java:724)
                                                                               at io.realm.Realm.compactRealm(Realm.java:1364)`

My device is Samsung Galaxy S6 (SM-G920F)
I use apk in about and get number 993.
1. How many different Realm configurations are you using? --> I have more configs, but 2 configs are using.
2. How many threads which is using Realm could exist at the same time? --> I'm not sure exactly how many thread, it may be 2 or 4.
3. Is it possible some Realm instance are not closed after using? --> No, all realm instances had been closed after be used.

**Comment by zaki50** [comment] 2016-07-27 10:40
@dinhthaidaica Can you try `RealmUtil.dumpRealmCount()` mentioned in https://github.com/realm/realm-java/issues/3197#issuecomment-235215117 and report the output?

**Comment by beeender** [comment] 2016-08-05 10:54
fixed by 1.1.1

**Closed by beeender** 2016-08-05 10:54 UTC
Labels: S:P1 Backlog, T:Bug-Crash

**Comment by diegomontoya** [comment] 2016-08-11 04:19
Have not had a fd error since 1.1.1. Nice update.

**Comment by monkeyfdude** [comment] 2017-01-03 21:29
Can this issue happen in 0.88.2? Do I need to upgrade from 0.88.2 to 1.1.1?

**Comment by Zhuinden** [comment] 2017-01-03 21:32
@monkeyfdude this was due to a change in 1.1.0, which was fixed till 1.1.1.

If anything, you should definitely upgrade to at least 0.88.3 to fix https://github.com/realm/realm-java/issues/2496

**Comment by monkeyfdude** [comment] 2017-01-03 22:05
@Zhuinden Thank you so much for the response. One more question as I am a newbie.

How can I find list of all open files by my app in emulator or on device?

I am not sure which component if leaking fds. In Unix I could do lsof. 

Thanks in advance,

**Comment by Zhuinden** [comment] 2017-01-03 23:44
@monkeyfdude I think you could probably do something very similar on the emulator using Terminal (I'm not sure if you need to root it somehow first - I'm not really well-versed with this).

**Comment by MGaetan89** [comment] 2017-01-05 13:39
I'm getting the same issue in my Android Tests (not in the application itself).
I delete and open the Realm in the `@Before` method, and close it in the `@After` method, like so:

```java
@Before
public void before() {
	RealmConfiguration realmConfiguration = ...;
	Realm.deleteRealm(realmConfiguration);

	this.realm = Realm.getInstance(realmConfiguration);
}

@After
public void after() {
	this.realm.close();
}
```

Each test then use `this.realm` to do what they need. The first 200 or so tests pass, but after  some time I get the following exceptions:

```
io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in io_realm_internal_SharedGroup.cpp line 113
at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
at io.realm.BaseRealm.<init>(BaseRealm.java:86)
at io.realm.Realm.<init>(Realm.java:135)
at io.realm.Realm.createAndValidate(Realm.java:233)
at io.realm.Realm.createInstance(Realm.java:214)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
at io.realm.Realm.getInstance(Realm.java:178)
at com.myapp.MyClass.myMethod(MyClass.java:246)
at com.myapp.StartActivity.onCreate(StartActivity.java:314)
at android.app.Activity.performCreate(Activity.java:6662)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:532)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

I tries to use the class in https://github.com/realm/realm-java/issues/3197#issuecomment-235215117, but it says that there are no 0 instances open.

The code causing the issue in the stacktrace simply open the Realm, get a value and close the Realm:

```java
Realm realm = Realm.getDefaultInstance();
myValue = realm.where(MyModel.class).equalTo("id", id).findFirst().getName();
realm.close();
```

I'm using Realm 1.2.0. I didn't try to update to 2.2.2 for the moment to see if it is fix in a future version.

**Comment by beeender** [comment] 2017-01-06 02:39
@MGaetan89 Can you setup a breakpoint before the problem happen, and get a list of opened FILEs by the test process? To list the opened files, this could help http://stackoverflow.com/a/15067880/1396606

**Comment by AlexLardschneider** [comment] 2017-03-16 17:25
@beeender while I could not reproduce the crash on my device, I captured some numbers from running the app on the emulator.

Most of the time between zero and one realm instances are open. With one instance running `ls -l . | grep realm | wc -l ` in my apps file descriptor directory results in around 7-15 open files, mostly hovering around 13. Most of the file descriptors point to files in `XXX.realm.management/XXX`.

Using the class in the gist from your comment, I never saw the realm count increase to numbers above 2 instances, which should be fine I guess.

Even though I did not capture any data before the crash (crash never happened on my devices tbh), hopefully this will help.

I'm seeing crashes from version 1.1.0 all the way up to 3.0.0.

**Comment by beeender** [comment] 2017-03-17 03:00
@AlexLardschneider how many different Realm are you using?

**Comment by AlexLardschneider** [comment] 2017-03-17 06:03
@beeendee two, which can be opened at the same time.

**Comment by beeender** [comment] 2017-03-17 06:41
@AlexLardschneider I feel like there is some other file handle opened than Realm are opened without closing in your app. Maybe you can do some check with `lsof`.

**Comment by AlexLardschneider** [comment] 2017-03-17 07:42
@beeender I already checked all the fds on the emulator and found nothing too suspicious.

In the latest update of my app i added some more open fd logging, I will pass the logs on to you as soon as possible.

**Comment by beeender** [comment] 2017-03-17 07:44
@AlexLardschneider Is it possible that you are opening Realm repeatedly in a background thread and forget to close it?

**Comment by AlexLardschneider** [comment] 2017-03-17 09:30
@beeender highly unlikely, but I will check again.
