### ISSUE TITLE
array_blob.cpp:113: [realm-core-5.23.6] Unreachable code

### ISSUE THREAD

**Issue by unengchen** [realm/realm-java#6813] opened 2020-04-27 09:17 UTC
#### Goal
backtrace not supported on this platform

#### Actual Results
E/REALM: /home/jenkins/workspace/realm_realm-core_release_5.23.6@3/src/realm/array_blob.cpp:113: [realm-core-5.23.6] Unreachable code
    <backtrace not supported on this platform>!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.
2020-04-27 17:02:28.057 2435-2525/com.zcla.bankchainaccesscontrol A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 2525 (pool-2-thread-1), pid 2435 (inaccesscontrol)

#### Steps & Code to Reproduce
when app start，app crash。

#### Version of Realm and tooling

Realm version(s): 6.0.2

Realm Sync feature enabled: No

Android Studio version: 3.6

Android Build Tools version:29

Gradle version: 3.6.3

Which Android version and device(s): 8.0

**Comment by cmelchior** [comment] 2020-05-07 11:10
Not sure what the problem is? LogCat should contain more information about the crash than the above?

**Comment by paktech1** [comment] 2020-05-15 20:43
having same issue with Realm version(s): 6.0.2, it crashing on some devices, working fine on most of them.

database name: BACKUP

Fatal Exception: io.realm.exceptions.RealmFileException
Unable to open a realm at path '/data/data/com.aluisderagisch.vocabulary/files/BACKUP': Unsupported Realm file format version (10) Path:Exception backtrace: <backtrace not supported on this platform>. (Unsupported Realm file format version (10) Path: /data/data/com.aluisderagisch.vocabulary/files/BACKUP Exception backtrace: <backtrace not supported on this platform>) (/data/data/com.aluisderagisch.vocabulary/files/BACKUP) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

**Comment by bmunkholm** [comment] 2020-05-26 06:10
@paktech1 Your issue is different. You are trying to open a file with a new file format (10) with version 6.0.2 that doesn't support that file format. The version 10 format has been made with  realm-java v7.

**Comment by bmunkholm** [comment] 2020-05-26 06:14
@jedelbo Do you know more about this issue?

**Comment by paktech1** [comment] 2020-05-26 07:35
Well why it works fine on 90% of the devices, and the pre populated database was made last year, how can it be from a new file format?

**Comment by bmunkholm** [comment] 2020-05-26 08:10
@paktech1 Could you please create another issue so we can separate the discussions from the original issue?

**Comment by cmelchior** [comment] 2020-06-17 11:33
@unengchen Has this happened multiple times or do you have the full stack trace?

**Comment by rezbuzz** [comment] 2020-08-14 05:13
I am having the same issue - on Wondows 

`
C:\Users\shahriar\Desktop\Tuner\tuner-soft\node-adapters\adapter-ros-to-kafka-pre-process>npm start

> node_adaptor@1.0.0 start C:\Users\shahriar\Desktop\Tuner\tuner-soft\node-adapters\adapter-ros-to-kafka-pre-process
> node adapter-ros-to-kafka-pre-process.js

[8/14/2020, 3:09:22 PM] : adapter is running profile is : ==> DEV <==
[8/14/2020, 3:09:23 PM] : Kafka producer is initialised successfully!
[8/14/2020, 3:09:23 PM] : Logged in user admin-adapter-ros-to-kafka
Connection[1]: Session[1]: client_reset_config = true, Realm exists = false, async open = true, client reset = false
Connection[1]: Session[1]: Client reset config, metadata_dir = 'C:\Users\shahriar\Desktop\Tuner\tuner-soft\node-adapters\adapter-ros-to-kafka-pre-process\realm-object-server\a099fd63-d534-4924-8229-a4fbe522bd4b\realms%3A%2F%2Ftuner1.us2a.cloud.realm.io%2Fadapter.resync', recover_local_changes = true, require_recent_state_realm = true
Connection[1]: Connected to endpoint '18.235.154.54:443' (from '127.0.0.1:55264')
Connection[1]: Verifying server SSL certificate using 155 root certificates
ERROR: Connection[1]: Session[1]: In finalize_state_transfer, the realm C:\Users\shahriar\Desktop\Tuner\tuner-soft\node-adapters\adapter-ros-to-kafka-pre-process\realm-object-server\a099fd63-d534-4924-8229-a4fbe522bd4b\realms%3A%2F%2Ftuner1.us2a.cloud.realm.io%2Fadapter.resync\version-1\partially_downloaded.realm could not be opened, msg = make_dir() failed: No such file or directory Path: C:\Users\shahriar\Desktop\Tuner\tuner-soft\node-adapters\adapter-ros-to-kafka-pre-process\realm-object-server\a099fd63-d534-4924-8229-a4fbe522bd4b\realms%3A%2F%2Ftuner1.us2a.cloud.realm.io%2Fadapter.resync\version-1\partially_downloaded.realm.management
Exception backtrace:
<backtrace not supported on this platform>
ERROR: Connection[1]: Session[1]: Illegal state message content
Connection[1]: Connection closed due to error
[8/14/2020, 3:09:27 PM] : (node:9976) UnhandledPromiseRejectionWarning: #<Object>
[8/14/2020, 3:09:27 PM] : (node:9976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[8/14/2020, 3:09:27 PM] : (node:9976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by rorbech** [comment] 2021-03-01 09:43
Closing this as we don't have sufficient information to reproduce it and the underlying implementation has changed significantly in newer versions. Feel to post new observations that might enlighten us.

**Closed by rorbech** 2021-03-01 09:43 UTC
Labels: O-Community, Reproduction-Required, T-Bug-Crash
