### ISSUE TITLE
Nested recursive list not being saved

### ISSUE THREAD

**Issue by botondbutuza** [realm/realm-java#1750] opened 2015-11-10 11:05 UTC
Hey guys,

First off, love Realm, and have been using it without issues for the past 8-10 months - this is the first issue I have with it that has stumped me a bit.

I have a Category data model that can have a list of Categories, or a list of Items. The Items in turn can have a list of Items as well (so they're recursive, but not self-referential, as in there aren't any loops). One of these Item classes deep in the hierarchy is losing its Items list.

The json is read out properly - if I do a count on said Item object's Item list, it shows 9, as it should. I then pop it into Realm, and when I try grabbing it again, the list is empty. The hierarchy is as follows: 

` [wrapper object (also in Realm)] -> Clients list -> Category list -> Category list -> Items list -> Items list`

The last Items list is empty. I wonder if it's something to do with the recursive nature of it? I don't really know where it's going wrong. I tried grabbing just the penultimate Item object from realm, and grabbing the wrapper object and drilling down into the hierarchy, but the list is empty in both cases.

If you need any more info, give me a shout. I can send data models and sample json if you need it. Any pointers would be greatly appreciated!

**Comment by botondbutuza** [comment] 2015-11-10 11:47
All Items are saved in the realm, they're just not linked up properly.

**Comment by zaki50** [comment] 2015-11-10 11:48
@botondbutuza Thank you for reporting the issue. I'll check that.

**Comment by zaki50** [comment] 2015-11-11 05:47
@botondbutuza Can you provide the code of `Category` and  `Item` class and json file?

**Comment by botondbutuza** [comment] 2015-11-11 10:19
@zaki50 Here you go: https://gist.github.com/botondbutuza/5735ad58d67416cb3943

If I can be of any further help, please let me know. Thanks very much for looking into this!

**Comment by zaki50** [comment] 2015-11-13 05:57
@botondbutuza Thank you and sorry for waiting.
I'll investigate it.

**Comment by botondbutuza** [comment] 2015-11-16 16:25
@zaki50 Any news on this weird issue?

**Comment by zaki50** [comment] 2015-11-17 10:33
@botondbutuza I tried to reproduce the issue, but no success.

I made a simple json since the provided json is so big.
I tried following code, and all assertions are OK.

@botondbutuza Can you find the differences between your code and my simplified one which cause the reported problems?

issue1750.json
```
{
  "id":100000,
  "categories": [
    {
      "id":1,
      "name":"name1",
      "artworks":[],
      "categories": [
        {
          "id":2,
          "name":"name2",
          "artworks":[
            {
              "id":1001,
              "name":"name1001",
              "variations":[
                {
                  "id":1002,
                  "name":"name1002",
                  "variations":[]
                }
              ]
            },
            {
              "id":2001,
              "name":"name2001",
              "variations":[
                {
                  "id":1001,
                  "name":"name1001",
                  "variations":[]
                },
                {
                  "id":2002,
                  "name":"name2002",
                  "variations":[]
                }
              ]
            }
          ],
          "categories": []
        }
      ]
    }
  ]
}
```

WareContainer.java
```
package io.realm.entities;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class WareContainer extends RealmObject {
    @PrimaryKey
    private long id;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    private RealmList<WareCategory> categories;

    public RealmList<WareCategory> getCategories() {
        return categories;
    }

    public void setCategories(RealmList<WareCategory> categories) {
        this.categories = categories;
    }
}
```

WareCategory.java
```
package io.realm.entities;

import io.realm.RealmList;
import io.realm.RealmObject;

public class WareCategory extends RealmObject {
    private int id;
    private String name;
    private RealmList<WareArtwork> artworks;
    private RealmList<WareCategory> categories;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public RealmList<WareArtwork> getArtworks() {
        return artworks;
    }

    public void setArtworks(RealmList<WareArtwork> artworks) {
        this.artworks = artworks;
    }

    public RealmList<WareCategory> getCategories() {
        return categories;
    }

    public void setCategories(RealmList<WareCategory> categories) {
        this.categories = categories;
    }
}
```

```
package io.realm.entities;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class WareArtwork extends RealmObject {
    @PrimaryKey
    private int id;
    private String name;
    private RealmList<WareArtwork> variations;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public RealmList<WareArtwork> getVariations() {
        return variations;
    }

    public void setVariations(RealmList<WareArtwork> variations) {
        this.variations = variations;
    }
}
```

```
    public void testIssue1750() throws IOException, JSONException {
        final WareContainer container;
        final InputStream is = loadJsonFromAssets("issue1750.json");

        try {
            testRealm.beginTransaction();
            container = testRealm.createOrUpdateObjectFromJson(WareContainer.class, is);
            testRealm.commitTransaction();
        } finally {
            is.close();
        }

        final RealmList<WareCategory> categories1 = container.getCategories();
        final RealmList<WareCategory> categories2 = categories1.get(0).getCategories();
        final RealmList<WareArtwork> artworksInCategoryId2 = categories2.get(0).getArtworks();

        assertEquals(1001, artworksInCategoryId2.get(0).getId());
        assertEquals(2, artworksInCategoryId2.get(1).getVariations().size());
        assertEquals(1001, artworksInCategoryId2.get(1).getVariations().get(0).getId());
    }
```

**Comment by zaki50** [comment] 2015-11-17 10:40
@botondbutuza What version of Realm are you using?

**Comment by botondbutuza** [comment] 2015-11-17 10:45
@zaki50 I'm using 0.84.1 - I'll test the above json, see if that works as intended. The issue could be something to do with the bigger json structure though.

**Comment by zaki50** [comment] 2015-11-17 10:49
@botondbutuza Can you provide all related model classes and the code which saves the json and which loads the Object from Realm?

**Comment by botondbutuza** [comment] 2015-11-17 10:51
@zaki50 If you give me an email address, I can send you the project. :)

**Comment by zaki50** [comment] 2015-11-17 11:02
@botondbutuza That's so helpful.

Please send the project to help@realm.io

**Comment by botondbutuza** [comment] 2015-11-17 11:34
@zaki50 Email sent. :) Thanks!

**Comment by zaki50** [comment] 2015-11-17 12:21
@botondbutuza Thanks!

**Comment by zaki50** [comment] 2015-11-18 05:23
@botondbutuza I execute your app and get the result below.

```
11-18 13:52:25.013 21064 21113 D VAR     : 9
11-18 13:52:25.416 21064 21113 D VAR     : 0
```

The length of `getVariations()` changed 9 to 0.
But this is an intended behavior.

The point is that `WareArtwork` has the `PrimaryKey` field and your json contains objects those have the same id.
I added log lines which print `id` and `position` field.

```
11-18 14:00:02.984 32141 32164 D VAR     : ID: 1305
11-18 14:00:02.985 32141 32164 D VAR     : POSITION: 12
```

This means a `WareArtwork` object whose id is 1305 and which has the variations list is first created, and that object is updated by another `WareArtwork` object whose id is also 1305 and which has empty variations list.

**Comment by zaki50** [comment] 2015-11-30 08:42
I'll close this issue since Realm is working as intended.

If you have further questions or request, please reopen this or create new issue.

**Closed** 2015-11-30 08:42 UTC
Labels: Help, Pending
