### ISSUE TITLE
field must be private in introExample

### ISSUE THREAD

**Issue by markpiller** [realm/realm-java#2387] opened 2016-03-03 17:16 UTC
Just to let you know one of the models in the introExample code does not compile:
https://github.com/realm/realm-java/blob/master/examples/introExample/src/main/java/io/realm/examples/intro/model/Cat.java

Compiler reports the following error:
Error:(9, 20) error: The fields of the RealmObject class must be private

## Version of Realm and tooling
Realm version(s): ?
0.87.5

Android Studio version: ?
1.5.1

Android version(s) on device/simulator: ?
API 23

**Comment by emanuelez** [comment] 2016-03-03 20:39
This is actually working as intended. We're preparing to release version 0.88.0 which will require Realm to be installed as a Gradle plugin and not as a library anymore. This allows to have model classes that are a lot more like POJOs, so we can allow custom methods, public fields and much more. 

You can find more info in this blog post: https://realm.io/news/android-installation-change/

I'll close this issue but don't hesitate to contact us again! :)

**Closed by emanuelez** 2016-03-03 20:39 UTC

**Comment by markpiller** [comment] 2016-03-03 21:09
Thank you for responding to this. I didn't find a problem with it - it was easy to change to private and add getters/setters. I was just  curious  clear why you publish an example that does not work out of the box *before* you published an update for the library that supports that kind of model.

**Comment by cmelchior** [comment] 2016-03-03 21:11
Where did you find the example? Our GitHub repository always assume you are working from our latest SNAPSHOT, but if you downloaded it from here https://realm.io/docs/java/latest/#installation it should work?

**Comment by markpiller** [comment] 2016-03-03 21:39
I navigated to it right from your website:
https://monosnap.com/file/En3ZcXEkSuJ04E5fqAM3kFCoVJAEBL

**Comment by cmelchior** [comment] 2016-03-03 21:41
Ok, I can see why that could cause some confusion. We should document the documentation to be clear about that. Thanks.
