### ISSUE TITLE
Crash In Android 4.2.1&Android 4.2.2  With Realm 3.0

### ISSUE THREAD

**Issue by shisu250** [realm/realm-java#4334] opened 2017-03-16 16:23 UTC
please help me.
I use realm 3.0. 
and collect crash in android 4.2.1& android 4.2.2 (level 17) . It looks like only crash in level 17.

## This is crash log:

main(1)
SIGSEGV(SEGV_ACCERR) 
#00 pc 00018b6c /system/lib/libc.so (memcpy+1324) [armeabi-v7a]
java:
io.realm.internal.SharedRealm.long nativeGetTable(long,java.lang.String)(Native Method)
io.realm.internal.SharedRealm.io.realm.internal.Table getTable(java.lang.String)(ProGuard:271)
io.realm.MasteryRealmBeanRealmProxy.io.realm.internal.Table initTable(io.realm.internal.SharedRealm)(ProGuard:149)
io.realm.PersonSchemaMediator.io.realm.internal.Table createTable(java.lang.Class,io.realm.internal.SharedRealm)(ProGuard:58)
io.realm.Realm.void initializeRealm(io.realm.Realm)(ProGuard:347)
io.realm.Realm.io.realm.Realm createAndValidate(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices[])(ProGuard:314)
io.realm.Realm.io.realm.Realm createInstance(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices[])(ProGuard:265)
io.realm.RealmCache.io.realm.BaseRealm createRealmOrGetFromCache(io.realm.RealmConfiguration,java.lang.Class)(ProGuard:143)
io.realm.Realm.io.realm.Realm getInstance(io.realm.RealmConfiguration)(ProGuard:228)
com.shensz.student.service.storage.StorageService.io.realm.Realm getPersonRealm()(ProGuard:120)

## This is my code:

private static final String REALM_NAME_PREFIX = "person.";
private static final String REALM = ".realm";
private RealmConfiguration getPersonRealmConfiguration(String uid) {
        Check.notNull(uid);
        Check.notEmpty(uid);
        String realmName;
        if (TextUtils.isEmpty(uid)) {
            realmName = REALM_NAME_PREFIX + "unknown" + REALM;
        } else {
            realmName = REALM_NAME_PREFIX + uid + REALM;
        }
        return new RealmConfiguration.Builder()
                .name(realmName)
                .deleteRealmIfMigrationNeeded()
                .modules(new PersonSchema())
                .schemaVersion(USER_REALM_VERSION)
                .build();
}

**Comment by Zhuinden** [comment] 2017-03-16 16:55
What device is this on? My guess goes that this is the same as https://github.com/realm/realm-java/issues/3651 ....

Which isn't good, although at least it's visible that the error is in `memcpy`.

**Comment by shisu250** [comment] 2017-03-16 17:09
@Zhuinden device is Samsung GT-I9118 and Samsung GT-I8558 and Samsung SM-G3812.
another crash log is：
unknown(23480)
SIGSEGV(SEGV_ACCERR)
#00 pc 00018b7c /system/lib/libc.so (memcpy+1340) [armeabi-v7a]

**Comment by Zhuinden** [comment] 2017-03-16 19:39
@shisu250 if you have one of these devices at hand, you can try adding `RealmLog.setLevel(LogLevel.ALL)` and obtain more information on the crash itself

**Comment by shisu250** [comment] 2017-03-17 06:09
@Zhuinden Sorry,I have no devices. I collect crash log from user through the website. Can I use the old version.such as 1.2.0 .

**Comment by Zhuinden** [comment] 2017-03-17 07:04
@shisu250 Realm 1.2.0 cannot open files created by Realm 2.x+, but technically Realm 1.2.0 did not have this problem yet.

**Comment by shisu250** [comment] 2017-03-17 08:47
@Zhuinden Have some way to clear before files(2.x created). when I use 1.2.0 realm app cover installation 3.0.0 realm.

**Comment by kneth** [comment] 2017-03-17 10:24
It looks a bit like #3651. And it indicates an issue with `memcpy` - a hypothesis I haven't been able to verify 100 % yet.

@shisu250 I don't have access to any of the devices, you mention. But I have at least one other device (SM-T111) where I have seen similar crashes. If possible, please send an APK to help@realm.io so I can see if I can reproduce it on my test device.

**Comment by shisu250** [comment] 2017-03-17 12:52
@kneth  I am have send apk to help@realm.io , Thank you for your help.

**Comment by kneth** [comment] 2017-03-17 13:57
@shisu250 The app didn't crash on my test device. But as @Zhuinden pointed out, your crash is likely the same as we have seen in #3651. I close this issue and ask you to follow than instead.

**Closed by kneth** 2017-03-17 13:57 UTC
Labels: Reproduction Required, T:Bug-Crash

**Comment by shisu250** [comment] 2017-03-17 15:42
@kneth ok,thx.  Can I use the old version.such as 1.2.0 . To avoid this problem for the time being.

**Comment by Zhuinden** [comment] 2017-03-30 11:39
@shisu250 good news is that thanks to your stack trace, Realm has finally been able to identify the root cause of the error: [memmove() native method is broken on old Samsung devices](https://code.google.com/p/android/issues/detail?id=81692).

While the fix in https://github.com/realm/realm-java/pull/4402 is being worked on (not yet merged), soon this error will be fixed! 😄

**Comment by shisu250** [comment] 2017-04-07 03:37
@Zhuinden thx very much,I will update my app's realm on later version. thanks again.

**Comment by kneth** [comment] 2017-04-07 14:46
@shisu250 version 3.1.1 is out with a fix - enjoy!

**Comment by shisu250** [comment] 2017-04-08 05:43
@kneth 😁
