### ISSUE TITLE
Unable to open realm at path

### ISSUE THREAD

**Issue by ankursharma234** [realm/realm-java#6302] opened 2018-11-16 06:18 UTC
Unable to start activity ComponentInfo{in.package/in.package.activity.MainActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/in.package/files/14570af5-d1e2-4801-a1b6-c4db485ad2a1': Invalid mnemonic. top_ref[0]: 0, top_ref[1]: 0, mnemonic: 0 0 0 0, fmt[0]: 0, fmt[1]: 0, flags: 0. (Invalid mnemonic. top_ref[0]: 0, top_ref[1]: 0, mnemonic: 0 0 0 0, fmt[0]: 0, fmt[1]: 0, flags: 0) (/data/data/in.package/files/14570af5-d1e2-4801-a1b6-c4db485ad2a1) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.

**Comment by cmelchior** [comment] 2018-11-16 09:12
Without having access to the file it is hard to say what is wrong. But that all values are 0 is suspicious and indicates that the file is somehow corrupted.

In any case, this is a duplicate of https://github.com/realm/realm-java/issues/6257 So I will be folding this into that issue.

If you are seeing multiple crashes of this we would be very interested in knowing which kind of devices it happens on.

See also https://github.com/realm/realm-java/issues/6257#issuecomment-434407376

**Closed by cmelchior** 2018-11-16 09:12 UTC
Labels: O:User, T:Duplicate
