### ISSUE TITLE
Exception "couldn't find libtightdb-jni.so" when adding multidex to project

### ISSUE THREAD

**Issue by jvdv86** [realm/realm-java#1708] opened 2015-10-31 23:47 UTC
Realm was working fine until I added multidex to my project in Android Studio. Exception matches #1421. Tested versions 0.80.0, 0.80.1, 0.83.1, 0.84.1 and tested various versions of Gradle (current 1.3.0), but nothing seems to help. Tested on Samsung Galaxy Note 4 (Android 5.1.1)

**Comment by zaki50** [comment] 2015-11-01 01:09
Hi @jvdv86 

Can you provide `build.gradle`?

**Comment by jvdv86** [comment] 2015-11-01 07:22
Hi @zaki50 

Top-level build.gradle
```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.google.gms:google-services:1.4.0-beta3'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

app build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
android {
    compileSdkVersion 23
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "..."
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:design:23.1.0'
    compile 'com.android.support:recyclerview-v7:23.1.0'
    compile 'com.android.support:cardview-v7:23.1.0'
    compile "com.google.android.gms:play-services-gcm:8.1.0"
    compile "com.google.android.gms:play-services-maps:8.1.0"
    compile 'com.jeremyfeinstein.slidingmenu:library:1.3@aar'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta1'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta1'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.commit451:PhotoView:1.2.4'
    compile 'io.realm:realm-android:0.84.1'
    compile 'com.android.support:multidex:1.0.1'
}

repositories {
    maven {url "http://jzaccone.github.io/SlidingMenu-aar"}
    maven {url "https://jitpack.io"}
}
```

**Comment by zaki50** [comment] 2015-11-01 07:41
@jvdv86 

Thanks.

You specified android gradle plugin `1.3.0` as follows.

    classpath 'com.android.tools.build:gradle:1.3.0'

But `classpath 'com.google.gms:google-services:1.4.0-beta3'` updates `com.android.tools.build:gradle` to `1.4.0-beta3` which has a bug not to pick *.so files up from dependency jars.

The easiest way to solve this issue for now is downgrading `com.google.gms:google-services` to `1.3.0-beta1`.

See this comment https://github.com/realm/realm-java/issues/1421#issuecomment-150303728

The root cause is https://code.google.com/p/android/issues/detail?id=188237

**Comment by jvdv86** [comment] 2015-11-01 09:36
@zaki50 
Thanks for your help. While I did previously try as you suggested. I think I did not clean and sync as often as I should have, while trying the different solutions other users had suggested. From what I can tell everything is up and running again. Thanks again!

**Comment by zaki50** [comment] 2015-11-01 09:38
@jvdv86 Great!

I'll close this issue.

**Closed by zaki50** 2015-11-01 09:38 UTC
Labels: Help, Pending
