### ISSUE TITLE
Crashed SharedRealm io.realm.internal.SharedRealm.nativeRefresh

### ISSUE THREAD

**Issue by mithrann** [realm/realm-java#3896] opened 2016-12-12 11:39 UTC
I got a crash in Crashlytics. Not sure how to reproduce. 

This is the stack trace:

```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Bad transaction log in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 210
       at io.realm.internal.SharedRealm.nativeRefresh(SourceFile)
       at io.realm.internal.SharedRealm.refresh(SourceFile:281)
       at io.realm.HandlerController.realmChanged(SourceFile:450)
       at io.realm.HandlerController.handleMessage(SourceFile:121)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5830)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

Realm version(s): 2.1.1

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: 5.1 & oppo A1601

**Comment by kneth** [comment] 2016-12-12 12:47
@mithrann It looks like it occurs in the change listener. Did you did a custom listener? If so, is it possible for you to share it?

**Comment by mithrann** [comment] 2016-12-14 05:01
@kneth  I have change listener for RealmResults<Model>

**Comment by kneth** [comment] 2016-12-14 08:24
@mithrann Can you share it?

The call to `SharedRealm.refresh` is part of Realm's handler. The error message indicates an issue with the Realm file. Do you have any clue of what happen prior to the crash? Something might have damaged the Realm file (and the transaction log). If you can get hold of the Realm file, you are welcome to send it to help@realm.io so we can examine it.

**Comment by mithrann** [comment] 2016-12-15 06:04
I don't have any clue what happens prior to the crash as the stack trace don't any info. Will try to reproduce.

**Comment by kneth** [comment] 2016-12-15 13:23
When you can reproduce it, you might to change the log level (https://realm.io/docs/java/2.2.1/api/io/realm/log/RealmLog.html#setLevel-int-). Doing that, we will be able to see which Realm calls your app was doing prior to the `RealmError`.

**Comment by mithrann** [comment] 2017-01-05 14:36
@kneth No I couldn't reproduce it.

**Comment by kneth** [comment] 2017-01-05 15:25
@mithrann I'll close the issue. If you see it again, don't hesitate to either reopen or create new issue.

**Closed by kneth** 2017-01-05 15:25 UTC
Labels: Reproduction Required, T:Help
