### ISSUE TITLE
Realm instance has already been closed.

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#2594] opened 2016-04-12 01:45 UTC
I received lots of Exception as the title says. But I can't locate where the problem is, although it seems to have something with a third banner library `convenientBanner`. 
I close Realm at `onDestory()` in `MainActivity` and other activities.
To find the problem, you may need to check out `BannerView`, `ZhihuListAdapter`(line 130) in my [repository](https://github.com/DanteAndroid/Knowledge).
Really really appreciate it!

Logcat:
```
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
	at io.realm.a.f(Unknown Source)
	at io.realm.al.b(Unknown Source)
	at io.realm.al.size(Unknown Source)
	at com.bigkoo.convenientbanner.a.a.a(Unknown Source)
	at com.bigkoo.convenientbanner.a.a.getCount(Unknown Source)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(Unknown Source)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(Unknown Source)
	at android.support.v4.view.ViewPager.setCurrentItem(Unknown Source)
	at com.bigkoo.convenientbanner.a.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5016)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by beeender** [comment] 2016-04-12 07:39
I cloned your repo, it would be easier for me if you can let me know how to reproduce it :)

**Comment by beeender** [comment] 2016-04-12 07:43
And I did a quick look on your `DB` class, it is not a good idea that keep a static field of Realm in the class. It is recommended to control the Realm's life cycle within the Activity/Fragment/etc.. 

https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances this might help you a bit

**Comment by DanteAndroid** [comment] 2016-04-12 07:44
I encountered it several times before, but not every time. Try following:
Click the banner on top, thus you enter the detail activity. Then go back from detail activity. Then you do that again(or you can click normal items instead of top banners). After several times, exit app.

**Comment by DanteAndroid** [comment] 2016-04-12 07:44
OK, I'll read that. Thanks first.

**Comment by beeender** [comment] 2016-04-12 07:49
If you want to wrap Realm related functionalities into the `DB` class, maybe just simply pass a `Realm` instance as a param to those static functions. Also, using the static field might cause some threading problems in the future, the Realm instance cannot used across different threads.

**Comment by DanteAndroid** [comment] 2016-04-12 07:52
Hmm, that is useful, coz I'm just a tyro :P

**Comment by kneth** [comment] 2016-04-15 07:50
@DanteAndroid Have you been able to resolve your problem using the suggestions from @beeender?

**Comment by DanteAndroid** [comment] 2016-04-15 08:13
@kneth I haven't refractor my DB.class for passing Realm instance. I'd appreciate if you can find what causes that exception.

**Comment by stk1m1** [comment] 2016-04-19 07:52
@DanteAndroid Could you please refactor according to @beeender 's suggestion and let us know how you've resolved your issue? 

I'd highly suggest to follow his suggestion since not only you keep an instance of realm in a static field but also re-assigning an instance of realm to _the very field_ in few more places in [`BaseActivity.java`](https://github.com/DanteAndroid/Knowledge/blob/9111f20c139f22fe45325fdb8cc0b127101d7aeb/app/src/main/java/com/dante/knowledge/ui/BaseActivity.java), which is inherited by other Acitivity classes in the same package. 

In that way, there is a great chance that one realm could be referred from many Activities and that would lead to the crash you are experiencing.

**Comment by DanteAndroid** [comment] 2016-04-19 08:09
@stk1m1 In DB.class, I got 
```        
if (realm.isClosed()){
            realm = Realm.getDefaultInstance();
        }
```
in every static method, could that avoid `closed` exception?

And I thought about refactor, just to find that in Model class, eg. `ZhihuModel.class`, in `onResponse`, where I need save data to realm, I can't get realm for activity(cause I don't pass activity to the model).
Does that means I need to:
1. Add realm in baseActivity's onCreate and close it in onDestroy.
2. Pass the activity to model class to get realm instance?
Thanks.

**Comment by stk1m1** [comment] 2016-04-19 08:30
Hi @DanteAndroid,

1. `closed` exception indicates that you're attempting to use a closed realm, utilizing Realm in a way that would not be promoted as the best practice. We'd highly appreciate if you could look into what @beeender has  [suggested](https://github.com/realm/realm-java/issues/2594#issuecomment-208759685)
2. If you'd follow what we have suggested in [the lifecycle of Realm instances](https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances), each activity is supposed to have _its own realm instance_ for best performance. Therefore, you'd need to refactor `BaseActivity` to create a realm instance at `onCreate()` and destroy the instance at `onDestory()`.
3. Another way is to pass an instance belong to an activity to models.

Hope these pointers help.

**Comment by DanteAndroid** [comment] 2016-04-19 08:53
@stk1m1 Thanks for your detailed explanations. Here's two new question:
1. if I create Realm in activity's onCreate, does that means I can only save data to realm in main thread?
2. Since I don't own realm in model class, should I call interface(and pass data) to let activity deal with saving job or I pass activity to model to get realm?

**Comment by stk1m1** [comment] 2016-04-19 09:00
Hi @DanteAndroid,

1. You can create a realm instance for each thread to get the best performance out of multi-threaded design.
2. If you're to share a realm instance between an Activity instance and model instances in various ways. The way you share a realm instance solely depends on your design.

**Comment by DanteAndroid** [comment] 2016-04-19 09:03
@stk1m1 Thank you so much! I'll remember your advice and try.

**Comment by kneth** [comment] 2016-04-20 08:00
@DanteAndroid I hope you have a better understanding of how Realm is working, and I'll close the issue.

**Comment by DanteAndroid** [comment] 2016-04-22 01:41
@beeender @stk1m1 I refactor my `DB.class` just to find this problem still exists.

```
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
	at io.realm.BaseRealm.checkIfValid(BaseRealm.java:344)
	at io.realm.RealmResults.isLoaded(RealmResults.java:758)
	at io.realm.RealmResults.size(RealmResults.java:389)
	at com.bigkoo.convenientbanner.adapter.CBPageAdapter.getRealCount(CBPageAdapter.java:39)
	at com.bigkoo.convenientbanner.adapter.CBPageAdapter.getCount(CBPageAdapter.java:35)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:518)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
	at com.bigkoo.convenientbanner.ConvenientBanner$AdSwitchTask.run(ConvenientBanner.java:110)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by beeender** [comment] 2016-04-22 02:11
@DanteAndroid Does you repo on github still have the issue you reported? Let me know how to reproduce it and i will take a look.

**Comment by beeender** [comment] 2016-04-22 10:39
Reopen the issue since more help needed :)

**Comment by kneth** [comment] 2016-04-25 07:47
@DanteAndroid We need a bit of source code to help you. Can you create either a unit test or a small project which reproduces the issue?

**Comment by DanteAndroid** [comment] 2016-04-25 07:54
@kneth I'm sorry, I just received the exception in the server(a bug analysis sdk). I myself met that problem before, but just several times and I don't know how to reproduce. I'll tell you as soon as I found out how to reproduce
BTW, I think this may have sth. to do with that problem, which I received lately:
```
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 1500 Pager id: com.dante.knowledge:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1000)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
	at android.view.View.measure(View.java:17593)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
	at android.view.View.measure(View.java:17593)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5578)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17593)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5578)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
	at android.view.View.measure(View.java:17593)
	at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:6874)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1396)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3497)
	at android.view.View.layout(View.java:15717)
	at android.view.ViewGroup.layout(ViewGroup.java:5040)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2174)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1148)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6049)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
	at android.view.Choreographer.doCallbacks(Choreographer.java:586)
	at android.view.Choreographer.doFrame(Choreographer.java:556)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5313)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
```
Thx.

**Comment by Zhuinden** [comment] 2016-04-25 09:04
Even if you reinitialize the Realm, you'll also need to reinitialize your RealmResults using the new realm.

**Comment by DanteAndroid** [comment] 2016-04-27 08:13
@kneth @beeender I know how to reproduce this issue:
Just click the banner, and do some pull to refresh, and click the banner, and exit the app.

**Comment by DanteAndroid** [comment] 2016-04-27 08:18
You may need to check out [BannerView](https://github.com/DanteAndroid/Knowledge/blob/master/app/src/main/java/com/dante/knowledge/mvp/view/BannerView.java), [ZhihuListAdapter](https://github.com/DanteAndroid/Knowledge/blob/master/app/src/main/java/com/dante/knowledge/mvp/other/ZhihuListAdapter.java)

**Comment by DanteAndroid** [comment] 2016-04-27 08:21
@Zhuinden Could you tell me how to reinitialize my realmResults?  Please help me check my [code](https://github.com/DanteAndroid/Knowledge/blob/master/app/src/main/java/com/dante/knowledge/mvp/other/ZhihuListAdapter.java#line-62)

**Comment by DanteAndroid** [comment] 2016-05-05 01:46
@beeender @kneth @stk1m1 Finally I figure out, this issue is caused by 'onResponse' in my okhttp request.
This GET request takes time. If I quit app when request not finished, 'onResponse' is called a moment later, at which time the Realm has been closed. So I changed code to:
```
            public void onResponse(ZhihuJson zhihuJson) {
                if (mActivity.isFinishing()) {
                    return;
                }
                //Begin Realm transaction here
            }
```
Is that okay?

**Comment by beeender** [comment] 2016-05-05 03:43
@DanteAndroid I think it is not a proper check.
```
/**
     * Check to see whether this activity is in the process of finishing,
     * either because you called {@link #finish} on it or someone else
     * has requested that it finished.  This is often used in
     * {@link #onPause} to determine whether the activity is simply pausing or
     * completely finishing.
     *
     * @return If the activity is finishing, returns true; else returns false.
     *
     * @see #finish
     */
```

It doesn't have direct relationship with `onDestory`.
In your case you can:
1. If you still want to save the response even when the activity is destroyed 
```
public void onResponse(ZhihuJson zhihuJson) {
    // Just create a new instance then it doesn't matter if `Activity.realm` is closed.
    Realm realm = Realm.getDefaultInstance();
    DB.saveList(realm, response.getPosts());
    realm.close();
}
```
2. If you really want to reuse the `Activity.realm`
```
public void onResponse(ZhihuJson zhihuJson) {
    if (realm.isClosed()) return; // Call Realm.isClosed() to check.
    DB.saveList(realm, response.getPosts());
}
```

**Comment by DanteAndroid** [comment] 2016-05-05 03:51
Thx for your solution. I have one more question:
When I add 'Thread.sleep(3000)' in 'onParseNetworkResponse()' (in okhttprequest, to simulate long time action), the 'mActivity.isFinishing()' still works (instead of NullPointer exception, which I expected), does that means my activity still not destroyed 3s later after I quit app? Could that be a memory leak?

**Comment by DanteAndroid** [comment] 2016-05-05 03:52
```
            @Override
            public ZhihuJson parseNetworkResponse(Response response) throws Exception {
               //Blahblah
 
                Thread.sleep(3000);
                return zhihuJson;
            }
            @Override
            public void onResponse(ZhihuJson zhihuJson) {
                if (mActivity.isFinishing()) {
                    Log.i(TAG, "onResponse: isFinishing");
                    return;
                }
                           //Blahblah
 
            }
```

**Comment by beeender** [comment] 2016-05-05 04:09
Quit app doesn't necessarily means the activity will be destroyed. You might need to read some document like http://developer.android.com/training/basics/activity-lifecycle/index.html

**Comment by DanteAndroid** [comment] 2016-05-05 04:16
I've read that several times, but still could not comprehend its lifecycle totally. Thanks, I'll read again.

**Comment by beeender** [comment] 2016-05-05 07:15
one more thing, a better fix would be just call OKHttp's `RequestCall.cancel()` in your activity's `onDestory()`.

**Comment by DanteAndroid** [comment] 2016-05-05 07:19
@beeender Actually I already did that in BaseActivity:
```
    @Override
    protected void onDestroy() {
        OkHttpUtils.getInstance().cancelTag(this);
        super.onDestroy();
        mRealm.close();
    }

```
But seems not work.

**Comment by DanteAndroid** [comment] 2016-05-05 07:20
cancelTag is just encapsulation of `call.cancel`

**Comment by beeender** [comment] 2016-05-09 03:20
@DanteAndroid I think we can close this issue now? Feel free let us know if you still need help on this. 

Thanks for the feedback!

**Closed by beeender** 2016-05-09 03:20 UTC
Labels: S:Waiting For User, T:Help
