### ISSUE TITLE
Realm migration rename field crash

### ISSUE THREAD

**Issue by softwarejoint** [realm/realm-java#5726] opened 2018-01-30 05:54 UTC
> Initially Realm schema version 20

    public class Contact extends RealmObject {
        public static final String TAG = "Contact";
        public static final String RESOURCE_URL = "resourceUrl";

        public String resourceUrl;
        ...
        other fields 
        ...
    }

> To update to Realm schema version 21
contact model is changed to this

* linkId field added
* resourceUrl field removed

        public class Contact extends RealmObject {
            public static final String TAG = "Contact";
            public static final String LINK_ID = "linkId";

            public String linkId;
            ...
            other fields 
            ...   
        }

> Realm Migration code is this

    @Override
    public void migrate(@NonNull DynamicRealm realm, 
                        final long oldVersion,
                        final long newVersion) {
          if (oldVersion < 21) {
            RealmObjectSchema schema = realmSchema.get(Contact.TAG);
            schema.renameField(Contact.RESOURCE_URL, Contact.LINK_ID);
        }
    }

It crashes with

`01-30 11:20:19.455 23663-23663/com.wafer E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.wafer, PID: 23663
                                                          io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
                                                          - Property ‘Contact.linkId’ has been added.
                                                          - Property ‘Contact.resourceUrl’ has been removed.
                                                              at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
                                                              at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
                                                              at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
                                                              at io.realm.BaseRealm.<init>(BaseRealm.java:124)
                                                              at io.realm.BaseRealm.<init>(BaseRealm.java:93)
                                                              at io.realm.Realm.<init>(Realm.java:153)
                                                              at io.realm.Realm.createInstance(Realm.java:424)
                                                              at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
                                                              at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
                                                              at io.realm.Realm.getInstance(Realm.java:353)`

> Version of Realm and tooling

Realm version: 4.3.3
Android Studio version: 3.0
Which Android version and device: All Devices

**Comment by softwarejoint** [comment] 2018-01-30 06:13
Also, Migration is running.

If I change the migration code to

addField(schema, Contact.LINK_ID, String.class);
removeField(schema, Contact.RESOURCE_URL);

It works, but I will like to preserve the values using the rename method call.

**Comment by cmelchior** [comment] 2018-01-30 07:47
Hi @softwarejoint 

Since both `linkId` and `resourceUrl` are String, using `renameField` should work. Are you 100% sure that the the migration code is running as expected?

**Comment by softwarejoint** [comment] 2018-01-30 10:24
yes, quite sure. As this does change the field but there is loss of data


    @Override
    public void migrate(@NonNull DynamicRealm realm, 
                                      final long oldVersion,
                                      final long newVersion) {
          if (oldVersion < 21) {
              RealmObjectSchema schema = realmSchema.get(Contact.TAG);
              schema.addField(Contact.LINK_ID, String.class);
              schema.removeField(Contact.RESOURCE_URL);
         }
    }

**Comment by Zhuinden** [comment] 2018-01-31 01:02
While `renameField` should do exactly what you want, the following should work...

      if (oldVersion < 21) {
          RealmObjectSchema schema = realmSchema.get(Contact.TAG);
          schema.addField(Contact.LINK_ID, String.class);
          schema.transform(new RealmObjectSchema.Function() {
               @Override
               public void apply(DynamicRealmObject obj) {
                    obj.setString(Contact.RESOURCE_URL, obj.getString(Contact.LINK_ID));
               }
          });
          schema.removeField(Contact.RESOURCE_URL);
     }

**Comment by softwarejoint** [comment] 2018-01-31 05:38
yes, I know. That approach works, but becomes a little slow as contact records are huge. For now I am not doing the transform. You can close the issue. But for others please check why rename doesn't work.

**Comment by Zhuinden** [comment] 2018-01-31 08:40
I wouldn't close the issue if `renameField` doesn't work as intended!

**Comment by cmelchior** [comment] 2018-08-27 10:34
I have not been able to reproduce this in tests. If there is a bug it isn't straightforward at least. Closing for now. Feel free to reopen if you can reproduce in a sample project.

**Closed by cmelchior** 2018-08-27 10:34 UTC
Labels: O:User, T:Help
