### ISSUE TITLE
RealmRecyclerViewAdapter bug

### ISSUE THREAD

**Issue by Tej42** [realm/realm-java#3186] opened 2016-07-14 19:21 UTC
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?
I am using RealmRecyclerViewAdapter with RecycleView and I want to achive async updates in the UI from database updates live.
#### Expected Results
Update the RecycleView as the data in Database is changed.
> ?

#### Actual Results
Not working with latest version 1.1.0 which is previously working with Realm version 1.0.0
>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample
```java
recyclerView.setAdapter(new RealmMessageLogAdapter(this,
                realm.where(Message.class).findAllSortedAsync("generatedDate", Sort.DESCENDING)));

```

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Nexus 5x

**Comment by Zhuinden** [comment] 2016-07-14 20:53
What do you mean not working? 

Also, you'll need to share a bit more code, you can't really determine the cause of the error here from this.

**Comment by Zhuinden** [comment] 2016-07-17 17:38
@Tej42 just so you know, RealmRecyclerViewAdapter works for me.

**Comment by Quarx2k** [comment] 2016-07-22 09:13
RealmRecyclerViewAdapter works for me too, using in production builds without any problems.

**Comment by stk1m1** [comment] 2016-07-25 02:51
@Tej42 

Have the comments above helped you? if not, could you share sample project with us for better description of the issue?

**Comment by stk1m1** [comment] 2016-07-28 02:31
Closing the issue due to no following feedback. Please open this again when the issue arises. Thanks!

**Closed by stk1m1** 2016-07-28 02:31 UTC
Labels: S:Waiting For User, T:Help
