### ISSUE TITLE
Querying a result with String array of values

### ISSUE THREAD

**Issue by bsmn99** [realm/realm-java#2972] opened 2016-06-09 10:33 UTC
Have a suggestion on querying in realm with array of values.

To query a list of values in a table column now,
```
 RealmResults<Tablename> realmResults = realm.allObjects(Tablename.class).where()
                .equalTo("Column1","Values1")
                .equalTo("Column1","Values2")
                .equalTo("Column1","Values3")
                .findAllAsync();
```
Instead like above, can array of values to be passed to get the same result like below?

```
String[] array=new String[]{"Values1","Values2","Values3"};

 RealmResults<Tablename> realmResults = realm.allObjects(Tablename.class).where()
                .equalTo("Column1",array)                
                .findAllAsync();
```

**Comment by kneth** [comment] 2016-06-09 11:10
I close the issue as it is more or less a duplicate of #809.

**Closed by kneth** 2016-06-09 11:10 UTC
