### ISSUE TITLE
Requested table is not in this Realm

### ISSUE THREAD

**Issue by alexustinovsm** [realm/realm-java#1017] opened 2015-04-07 16:21 UTC
I have the next crash

```logcat
Caused by: java.lang.IllegalStateException: Requested table is not in this Realm. Creating it requires a transaction: class_Chat
    at io.realm.internal.Group.getTable(SourceFile:220)
    at io.realm.Realm.getTable(SourceFile:330)
    at io.realm.RealmQuery.(SourceFile:75)
    at io.realm.Realm.where(SourceFile:1270)
    at io.chat.runner.db.a.a(SourceFile:105)
    at io.chat.runner.chat.ChatListFragment.m(SourceFile:227)
    at io.chat.runner.chat.ChatListFragment.onResume(SourceFile:188)
    at android.support.v4.app.Fragment.performResume(SourceFile:1829)
    at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:993)
    at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1136)
    at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1118)
    at android.support.v4.app.FragmentManagerImpl.dispatchResume(SourceFile:1937)
    at android.support.v4.app.FragmentActivity.onResumeFragments(SourceFile:444)
    at android.support.v4.app.FragmentActivity.onPostResume(SourceFile:433)
    at android.support.v7.app.ActionBarActivity.onPostResume(SourceFile:146)
    at android.app.Activity.performResume(Activity.java:6089)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
    ... 11 more
```

I ran ChatList screen several times and everything was okay.

**Comment by alexustinovsm** [comment] 2015-04-07 16:23
### Device 
Asus Nexus 7
Android 5.1

**Comment by bmunkholm** [comment] 2015-04-07 17:39
Could it be that you are making a query for the Chat class without having anything in the database?
Which version are you using?

**Comment by alexustinovsm** [comment] 2015-04-08 04:28
```
Could it be that you are making a query for the Chat class without having anything in the database?
```

No, It couldn't be. I ran app then came to this screen for several times before crash.

```
Which version are you using?
```

Version is 0.80.0 for Android.

**Comment by cmelchior** [comment] 2015-04-08 08:00
Hi @alexustinovsm 

Can you post the code at ```ChatListFragment:227``` and the content of your Chat class?

**Comment by alexustinovsm** [comment] 2015-04-08 14:43
```java
RealmResults<Chat> result = realm.where(Chat.class)
  .equalTo(ChatSpec.Column.USER_ID, userId, false)
  .findAll();

result.sort(
  ChatSpec.Column.ORDER, RealmResults.SORT_ORDER_DESCENDING,
  ChatSpec.Column.UPDATE_AT, RealmResults.SORT_ORDER_DESCENDING
);
```

**Comment by cmelchior** [comment] 2015-04-09 07:01
Hi @alexustinovsm 
That code looks OK, and I cannot reproduce this error. Can you provide a reproducible test project? Also, it looks like you are using ProGuard. What does your ProGuard configuration look like?

**Comment by alexustinovsm** [comment] 2015-04-14 09:20
Unfortunately, I can't provide you access for test project.

ProGuard rules is next
```
## App
-keepattributes Signature, *Annotation*
-keep class io.chat.db.model.** { *; }

### Realms
-keepnames public class * extends io.realm.RealmObject
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**
```

**Comment by cmelchior** [comment] 2015-04-16 07:27
Hi @alexustinovsm 
That proguard configuration looks fine. The error you are getting is a bit surprising as Realm verifies the schema when opening the file, so the error you are getting shouldn't really be possible?

Are you able to post the content of the file ```ChatListFragment```? Also are you using multiple Realm files?

**Comment by StefanoGR** [comment] 2015-04-22 11:44
I am getting the same error too. I am on new version 0.80.1. 
It worked pretty well, but I had to change the model and I have reinstalled the app. Now it gives me the "Requested table is not in this Realm".
Right now I can fix this creating an empty row, but It's not a clean solution.

**Comment by cmelchior** [comment] 2015-04-22 11:46
Hi @StefanoGR 
Are you able to share the code that produces this error or create a sample project?

**Comment by alexustinovsm** [comment] 2015-04-22 12:40
```
Are you able to post the content of the file ChatListFragment? Also are you using multiple Realm files?
```

Unfortunately, I can't provide ChatListFragment source code =/

I'm using single realm files, because I don't see any case for multiple files.

**Comment by cmelchior** [comment] 2015-06-02 08:16
As we cannot reproduce this error I am closing for now. Please reopen if you can reproduce it in a sample application.

**Comment by johnryan** [comment] 2016-05-06 16:22
I'm seeing this issue, although it's manifesting slightly differently.

I call 
```
Realm realm = Realm.getDefaultInstance();
realm.deleteAll();
realm.commitTransaction();
realm.close();
```

when a user logs out.

Once the user logs back in if I make a query before inserting something into the realm it crashes with this error:

```Requested` table is not in this Realm. Creating it requires a transaction: class_TWContact```

Is that expected / do I need to re-build the tables somehow after deleteAll()?

**Comment by gndps** [comment] 2016-05-08 09:32
I'm also facing a problem like @johnryan 
I'm clearing the app data programatically on user log out which deletes the realm file.
And when user tries to log in again, it throws:

`Caused by: java.lang.IllegalStateException: Requested table is not in this Realm. Creating it requires a transaction: class_EssentialInfo
at io.realm.internal.Group.getTable(Group.java:193)
at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:235)
at io.realm.RealmQuery.<init>(RealmQuery.java:136)
at io.realm.RealmQuery.createQuery(RealmQuery.java:85)
at io.realm.Realm.where(Realm.java:950)
at com.mypackage.gndp.util.RealmUtils.getEssentialInfo(RealmUtils.java:279)`

**Comment by johnryan** [comment] 2016-05-09 13:15
@cmelchior should I open a new issue for the issue I mentioned or does this belong here?

**Comment by johnryan** [comment] 2016-05-09 22:20
@gndps I found a realm instance that wasn't being closed properly and was still open when the deleteAll was happening. This seems to have locked the realm for further writes and thus probably prevented the tables from being re-created. Maybe a similar issue for you.

**Comment by BinarySatan** [comment] 2016-06-14 09:12
i have the same problem, when i   lock screen and then open it,and then use   `realm.where(clazz).equalTo(fieldName, (String) fieldValue).findFirst()`   it will crash

**java.lang.IllegalStateException: Requested table is not in this Realm. Creating it requires a transaction: class_DBShoppingCartInfo**

**Comment by cmelchior** [comment] 2016-06-14 09:33
Hi @johnryan Sorry for not responding. Closed issues tend to be missed :(
Can either you or @BinarySatan reproduce this? A sample project would be great.

**Comment by kneth** [comment] 2016-06-22 07:42
@johnryan `deleteAll()` should only delete objects and not the underlying data structure (table). Since we cannot reproduce it, we will be happy if you can.

**Comment by kneth** [comment] 2016-07-01 05:43
I am closing the issue. We cannot reproduce it. Please reopen or create a new issue if you encounter it again.

**Closed by kneth** 2016-07-01 05:43 UTC
Labels: Reproduction Required, S:P1 Backlog, S:Waiting For User, T:Bug-Crash
