### ISSUE TITLE
Exception while deleting query results

### ISSUE THREAD

**Issue by kakateeya** [realm/realm-java#4379] opened 2017-03-24 10:14 UTC
#### Goal
Query and delete entries from Realm. I am using transaction still getting this error that I don't understand. 

#### Expected Results

Entries deleted from Realm

#### Actual Results
```
03-24 15:33:23.750 E/REALM_JNI(23824): jni: ThrowingException 8, Must be in a write transaction in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 173, .
03-24 15:33:23.750 E/REALM_JNI(23824): Exception has been thrown: Must be in a write transaction in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 173
```

#### Code Sample

```java

        Realm realm = Realm.getInstance(realmConfig);

        long currentTime = System.currentTimeMillis();
        final RealmResults<RawEntry> rawEntriesToDelete = realm.where(RawEntry.class).greaterThan(ISavedEntry.FIELD_TIME, currentTime).findAll();
        final RealmResults<FilteredEntry> filteredEntriesToDelete = realm.where(FilteredEntry.class).greaterThan(ISavedEntry.FIELD_TIME, currentTime).findAll();
        final RealmResults<SentEntry> sentEntriesToDelete = realm.where(SentEntry.class).greaterThan(ISavedEntry.FIELD_TIME, currentTime).findAll();
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                filteredEntriesToDelete.deleteAllFromRealm();
                rawEntriesToDelete.deleteAllFromRealm();
                sentEntriesToDelete.deleteAllFromRealm();
            }
        });

        realm.close();

```

#### Version of Realm and tooling
Realm version(s): 3.0.0

Realm sync feature enabled: no

Android Studio version: 2.2

Which Android version and device: Any

**Comment by Zhuinden** [comment] 2017-03-24 10:45
realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                final RealmResults<RawEntry> rawEntriesToDelete = realm.where(RawEntry.class).greaterThan(ISavedEntry.FIELD_TIME, currentTime).findAll();
                final RealmResults<FilteredEntry> filteredEntriesToDelete = realm.where(FilteredEntry.class).greaterThan(ISavedEntry.FIELD_TIME, currentTime).findAll();
                final RealmResults<SentEntry> sentEntriesToDelete = realm.where(SentEntry.class).greaterThan(ISavedEntry.FIELD_TIME, currentTime).findAll();
                filteredEntriesToDelete.deleteAllFromRealm();
                rawEntriesToDelete.deleteAllFromRealm();
                sentEntriesToDelete.deleteAllFromRealm();
            }
        });

**Comment by zaki50** [comment] 2017-03-24 11:53
I couldn't find any mistakes in original code.

io_realm_internal_Collection.cpp line 173 is 
https://github.com/realm/realm-java/blob/v3.0.0/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp#L173

I'll write a test case to reproduce this.

**Comment by zaki50** [comment] 2017-03-24 12:24
I wrote a test but could not reproduce this issue.

https://github.com/realm/realm-java/commit/67df037616a5e118b8b77cf3654e46d5e3546e9a 

@kakateeya Can you see any difference with your code? And could you check if you are using correct `Realm` instance?

**Comment by kakateeya** [comment] 2017-03-24 12:45
Thanks @zaki50 Only diff I could see is that we are getting the Realm instance
`Realm realm = Realm.getInstance(realmConfig);`

**Comment by kakateeya** [comment] 2017-03-24 12:49
But I do see that the instance is being created in setUp(). So, I am not sure why its not happening.

**Comment by zaki50** [comment] 2017-03-24 12:50
@kakateeya Are you using multiple realm file in your app?

**Comment by kakateeya** [comment] 2017-03-24 12:52
No. Just one file. 
What does that error mean? How can I make the code to be in a `write transaction`?

**Comment by Zhuinden** [comment] 2017-03-24 12:54
@kakateeya have you tried my answer and see ifi t changes anything

**Comment by zaki50** [comment] 2017-03-24 12:55
All modification API calls are already in write transaction.
The code should work.

Could you make a small sample project to reproduce this?

**Comment by kakateeya** [comment] 2017-03-24 12:55
@Zhuinden sorry I overlooked. Will try that now. But I did something similar before
```
beginTransaction()
query
delete
endTransaction()
```

**Comment by kakateeya** [comment] 2017-03-24 13:05
@Zhuinden interesting when I made the change you suggested (query and delete within the transaction), I am getting a little different error
```
03-24 18:33:15.337 E/REALM_JNI(26073): jni: ThrowingException 8, The Realm is already in a write transaction in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 131, .
03-24 18:33:15.342 E/REALM_JNI(26073): Exception has been thrown: The Realm is already in a write transaction in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 131
```

**Comment by Zhuinden** [comment] 2017-03-24 13:10
@kakateeya okay that is super-duper interesting, do you have `realm.beginTransaction()` manually, instead of `realm.executeTransaction()` anywhere in your code?

What thread is this on?

**Comment by kakateeya** [comment] 2017-03-24 13:22
@Zhuinden No,  I don't have any `beginTransaction()` anywhere.
This part of the code runs in an RxObservable callback, which runs in an Android `HandlerThread`.

```
Observable..observeOn(AndroidSchedulers.from(getLooper())).subscribe() {
    //the code
}
```

**Comment by zaki50** [comment] 2017-03-24 13:27
@kakateeya Could you make a small sample project to reproduce this?

**Comment by kakateeya** [comment] 2017-03-24 13:51
Sure.. will do.

**Comment by Zhuinden** [comment] 2017-03-24 13:52
While I generally do my writes on a single-threaded non-looper executor and only keep the queries on handler thread, this is rather odd and definitely some sort of weird bug that needs reproducing

**Comment by kakateeya** [comment] 2017-03-24 15:03
This might be a cause.. 
the code I mentioned will run when device time is set. The case I am trying to fix is when user manually sets the time to future date and then changes back. I suspect this has something to do with this issue.

**Comment by beeender** [comment] 2017-03-27 03:53
My doubt is that the `beginTransaction` will trigger the listeners -- in the RxJava, it will fire some observables which has a callback to begin transaction again.

**Comment by beeender** [comment] 2017-03-27 03:53
It will be much clearer if you can post a full backtrace here.

**Comment by beeender** [comment] 2017-03-28 08:41
@SamTTaylor only one transaction is allowed for one same Realm db file, no matter it is one Dynamic Realm and on normal Realm.

**Comment by beeender** [comment] 2017-04-24 04:29
@kakateeya @SamTTaylor I am closing this issue now. If you still need help on this, please let us know.

**Closed by beeender** 2017-04-24 04:29 UTC
Labels: Reproduction Required, S:Waiting For User

**Comment by preyesm** [comment] 2017-07-27 08:15
Hey @beeender could you confirm if I can do this in a single executeTransaction:
 ApplicationDataHandler.getRealm().executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        realm.insertOrUpdate(agentProfile);
                        if (agentProfileCache.getRequirement() != null)
                            realm.insertOrUpdate(agentProfileCache.getRequirement());
                        if (agentProfile.getFeaturedProperties() != null) {
                            realm.insertOrUpdate(agentProfileCache.getFeaturedProperties());
                        }
                    }
                });

I have three 3 realm classes  and I am trying to update all the three of them one after the other in the same execute transaction block. - I was getting this error - Fatal Exception: java.lang.IllegalStateException: Changing Realm data can only be done from inside a transaction.
Though I a doing inside a transaction but I could not figure out why this issue cropped up in this block

**Comment by beeender** [comment] 2017-07-27 08:22
@preyesm please create a new issue with relevant code and the full backtrace.
