### ISSUE TITLE
ThrowingException 4, std::bad_alloc

### ISSUE THREAD

**Issue by mitchwongho** [realm/realm-java#4088] opened 2017-01-22 07:08 UTC
#### Goal

> Reliable long-term operating app.
#### Expected Results

> Sustained insert/update operations for a long period of operating.

#### Actual Results

The following error occurs which results in a force closed.

```
                                                --------- beginning of main
01-22 08:46:40.984 12429-19210/? W/System.err:     at com.snuza.picoconnect.communications.btle.PicoLeDevice$3.onCharacteristicChanged(PicoLeDevice.java:315)
01-22 08:46:40.984 12429-19210/? W/System.err:     at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:438)
01-22 08:46:40.984 12429-19210/? W/System.err:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
01-22 08:46:40.984 12429-19210/? W/System.err:     at android.os.Binder.execTransact(Binder.java:446)
01-22 08:46:40.987 12429-12056/? E/REALM_JNI: jni: ThrowingException 4, std::bad_alloc in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 124, .
01-22 08:46:40.987 12429-12056/? E/REALM_JNI: Exception has been throw: std::bad_alloc in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 124 
01-22 08:46:41.840 12429-19210/? E/REALM_JNI: jni: ThrowingException 4, std::bad_alloc in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 124, .
01-22 08:46:41.840 12429-19210/? E/REALM_JNI: Exception has been throw: std::bad_alloc in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 124 
01-22 08:46:41.843 12429-19210/? W/System.err: io.realm.internal.OutOfMemoryError: std::bad_alloc in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 124 
01-22 08:46:41.844 12429-19210/? W/System.err:     at io.realm.internal.SharedRealm.nativeCommitTransaction(Native Method)
01-22 08:46:41.844 12429-19210/? W/System.err:     at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:228)
01-22 08:46:41.844 12429-19210/? W/System.err:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:349)
01-22 08:46:41.844 12429-19210/? W/System.err:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:338)
01-22 08:46:41.844 12429-19210/? W/System.err:     at io.realm.Realm.commitTransaction(Realm.java:125)
01-22 08:46:41.845 12429-19210/? W/System.err:     at io.realm.Realm.executeTransaction(Realm.java:1300)
01-22 08:46:41.845 12429-19210/? W/System.err:     at com.snuza.picoconnect.util.db.RealmDAO.insertPicoStatData(RealmDAO.java:71)
01-22 08:46:41.845 12429-19210/? W/System.err:     at com.snuza.picoconnect.communications.btle.PicoLeDevice.picoPrimaryStatDataPulse(PicoLeDevice.java:448)
01-22 08:46:41.845 12429-19210/? W/System.err:     at com.snuza.picoconnect.util.DataExchangeUtil.processReceivedStatDataForPico(DataExchangeUtil.java:73)
01-22 08:46:41.845 12429-19210/? W/System.err:     at com.snuza.picoconnect.communications.btle.PicoLeDevice$3.onCharacteristicChanged(PicoLeDevice.java:315)
01-22 08:46:41.846 12429-19210/? W/System.err:     at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:438)
01-22 08:46:41.859 12429-19210/? W/System.err:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
01-22 08:46:41.861 12429-19210/? W/System.err:     at android.os.Binder.execTransact(Binder.java:446)
```

#### Steps & Code to Reproduce

> Unable to reproduce. Requires the app to be running for long durations of time.

#### Code Sample

```java

Unable to share at this point

```

#### Version of Realm and tooling
Realm version(s): 2.3.0-SNAPSHOT

Realm sync feature enabled: no

Android Studio version: 2.3 Beta 2

Which Android version and device: Nexus 5 (5.1)

**Comment by beeender** [comment] 2017-01-23 06:36
How big the realm db file is when the problem happens?

**Comment by beeender** [comment] 2017-01-23 06:39
Is there any difference of the reproduce steps compared with last time? #3821

**Comment by mitchwongho** [comment] 2017-01-23 07:20
Not that big. About 39MB.
I occasionally see `jni: ThrowingException 7, std::exception in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1297`, but it isn't fatal.

#3821 does appear to resolve the amount of `finalized` objects.

How does this `ThrowingException 4` differ to `ThrowingException 7`?

**Comment by beeender** [comment] 2017-01-23 07:25
`ThrowingException 4` is thrown when it cannot alloc native memory, `ThrowingException 7` is something related with async query.

Can you see the native memory usage when this problem happens? Do you store any really big Strings or binary into the database?

**Comment by mitchwongho** [comment] 2017-01-23 07:45
Unfortunately, I wasn't monitoring at the time of the crash (the had had been running for about 6 hours).

This issue seems intermittent, since the app has previously been able to operate (in the same state) for more that 24hrs.

The longest binary field is 22-bytes long. The longest String is a UUID.

**Comment by beeender** [comment] 2017-01-23 07:46
Do you use other libraries which have native libraries?

**Comment by mitchwongho** [comment] 2017-01-23 07:51
No.
The main libraries are:
- Retrofit
- RxJava/RxAndroid/RetroLamda
- Dagger2
- Butterknife
- Glide
- MPAndroidChart

**Comment by beeender** [comment] 2017-01-23 08:01
Is it possible that you have any leak in the Java side? `RealmObject`, `RealmList`, `RealmResults` and `RealmQuery` will consume some small amount of native memory as well. If you have those leaked in the java side for a really long time, OOM could happen in the native code.

**Comment by Zhuinden** [comment] 2017-01-23 08:31
The easiest way to leak Realm's objects is with a misuse of the `asObservable()` method, because RealmObservableFactory retains a strong reference to your results so that they don't die on the way.

**Comment by mitchwongho** [comment] 2017-01-23 08:55
The exception appear to occur during a Realm _write_ transaction.

On all our uses of `asObservable()` are use `Realm.copyFromRealm`.  Where I do experience bloat (and an OOM condition) when observing an ever-growing Realm. 

In our application, we're logging wearable metrics that need to be plotted on a chart. Our first implementation tried to observe the "metrics" realm to plot each metric sample (1/sec) on a chart. I found that I'd get an OoM because the `RealmResults` collection would become too big. We've since changed our implementation to only use that pattern for small/restricted for small ResultSets.

**Comment by Zhuinden** [comment] 2017-01-23 09:11
>  On all our uses of asObservable() are use Realm.copyFromRealm. 

Yeah that can't be right.

**Comment by mitchwongho** [comment] 2017-01-23 09:22
IO Thread

**Comment by beeender** [comment] 2017-01-24 09:49
Would you please help to confirm if there are any `RealmObject`/`RealmResults`/`RealmList` leaked in your app? including those objects created by observable?

**Comment by mitchwongho** [comment] 2017-01-24 13:09
I will check again. The only please it could occur is in the use of rx Subjects. My only reservations is that the occurrence of the OoM exception is inconsistent, while the operating conditions/state remain the same. i.e it happens after 4 hours or it happens after 48 hours.

**Comment by kneth** [comment] 2017-01-26 08:06
@mitchwongho Did you have a chance to check for leaking Realm objects?

**Comment by mitchwongho** [comment] 2017-01-26 08:36
@kneth Testing is ongoing. I'm not seeing any drastic. Mem Usage (allocated) remains below 64MB on the Nexus 5.

**Comment by Zhuinden** [comment] 2017-01-26 09:00
If you have any kind of `begin-commit` **inside a for loop**, then that can cause problems.

**Comment by mitchwongho** [comment] 2017-01-26 09:08
None of that.

**Comment by kneth** [comment] 2017-01-27 08:46
@mitchwongho Can you post your code because we are all just guessing at the moment.

**Comment by bmeike** [comment] 2017-01-30 23:59
@mitchwongho Do you have code to share w/us?  If not I think we'll close this ticket, ok?

**Comment by mitchwongho** [comment] 2017-01-31 09:35
@kneth @bmeike Please close the ticket. UnfortunateIy I'm unable to share the codebase with you (restricted access).

Haven't experienced since (memory usage is stable), but will continue to monitor.

**Comment by kneth** [comment] 2017-01-31 11:25
@mitchwongho I am happy to hear that you haven't seen it recently. Don't hesitate to either reopen or create new issue if you see it again.

**Closed by kneth** 2017-01-31 11:25 UTC
Labels: T:Help
