### ISSUE TITLE
Cannot invoke method hasAnnotation() on null object

### ISSUE THREAD

**Issue by fvillalbacar** [realm/realm-java#3167] opened 2016-07-10 19:00 UTC
Hello,

I've been developing and application using Git. On the branch _develop_ I created a model which extended from RealmObject, after that I switched to another branch to develop the entire feature. After coming back to the the branch _develop_ I got an issue as the file was renamed, it appeared on the project tree as a subclass from the original name, so I renamed it with the new name. 

When trying to compile I get: 
Error:Execution failed for task ':app:transformClassesWithRealmTransformerForDebug'.
> Cannot invoke method hasAnnotation() on null object

Could you please provide some info about how to fix this?

Edit : I tried downgrading the version from 1.1.0 to 0.90.1, it produced the same error. Downgrading to 0.87.5, the project compiles succesfully. No idea of why.

**Comment by Zhuinden** [comment] 2016-07-10 21:25
Technically 0.87.5 did not support custom methods in RealmObjects, and that was because it was JAR based and not AAR-based bundled with the Realm Gradle plugin. Essentially, this also means that 0.88.0 is the version that introduced the Realm-Transformer which seems to fail in your project for whatever reason.

Anyways, you seem to have surfaced some sort of issue with the Realm Transformer (if I know right, that is the bytecode weaver), which also means you'll have to send the project over to help[at]realm.io for them to reproduce this bug.

**Comment by beeender** [comment] 2016-07-11 05:28
I feels it is caused by some build outputs are not cleaned when switch back to *develop* branch and run build. Can you please try to clean it and build. And it would be helpful if you can get more logs with gradle's `--info --stacktrace` options. Thanks!

**Comment by beeender** [comment] 2016-07-21 01:40
Hope the issue is solved :) I am closing this issue now, let us know if you still need more support.

**Closed by beeender** 2016-07-21 01:40 UTC
Labels: S:Waiting For User, T:Help
