### ISSUE TITLE
Realm is not compatible with Galaxy one running Android 4.4.2

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#3072] opened 2016-06-26 08:04 UTC
Few of the users complained that my app is not compatible with their devices. One such user is running Galaxy one 4.4.2 and there is a message on the app store - "Your device isn't compatible with this version." Could you please confirm whether this issue because of Realm or not ?

**Comment by zaki50** [comment] 2016-06-26 09:49
@mihirjoshi21 Can you provide more detail information about `Galaxy one`?

**Comment by mihirjoshi21** [comment] 2016-06-26 16:55
Its is reported by users that the application is not compatible with galaxy one. I don't have the device with me so I couldn't verify it but as my app doesn't use anything that is specific to processor architecture so I guess it is caused due to Realm.

**Comment by emanuelez** [comment] 2016-06-26 20:58
I can't really find any information about a Galaxy One phone. Realm supports API >= 9 so the version of Android cannot be a problem. Realm also supports all kinds of ABI: ARM, ARMv7a, ARM64, x86, x86_64 and MIPS. So unless the Galaxy one uses a MIPS64 CPU (which would be a world first) I don't think Realm is the cause of the incompatibility.

**Comment by zaki50** [comment] 2016-06-26 23:50
@mihirjoshi21

I think @emanuelez answered this question.
I'll close this.

If you find more detail information, feel free to reopen this.

**Closed by zaki50** 2016-06-26 23:50 UTC
Labels: T:Help
