### ISSUE TITLE
Exception has been thrown: Out of range in /path/io_realm_internal_Collection.cpp line 133 (requested: 0 valid: 0)

### ISSUE THREAD

**Issue by RameshReddyKolla** [realm/realm-java#4433] opened 2017-04-05 06:32 UTC
Original title: Exception has been thrown: Out of range  in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 133(requested: 0 valid: 0)

#### Goal

Fetching all cities data from DB which have stored earlier.

#### Expected Results

realm results from DB

#### Actual Results

```
 java.lang.ArrayIndexOutOfBoundsException: Out of range  in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 133(requested: 0 valid: 0)
                                                                        at io.realm.internal.Collection.nativeGetRow(Native Method)
                                                                        at io.realm.internal.Collection.getUncheckedRow(Collection.java:386)
                                                                        at io.realm.OrderedRealmCollectionImpl.get(OrderedRealmCollectionImpl.java:106)
                                                                        at io.realm.RealmResults.get(RealmResults.java:53)
                                                                        at io.realm.OrderedRealmCollectionImpl.get(OrderedRealmCollectionImpl.java:19)
                                                                        at com.wisdomjobs.app.fragments.PDPreferredLocationsFragment.getCity(PDPreferredLocationsFragment.java:430)
                                                                        at com.wisdomjobs.app.fragments.PDPreferredLocationsFragment.onCitiesIdsSelection(PDPreferredLocationsFragment.java:449)
                                                                        at com.wisdomjobs.app.fragments.PDPreferredLocationsFragment.onCreateView(PDPreferredLocationsFragment.java:104)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

#### Code Sample

At below line:

```
mRealm.where(Cities.class).equalTo("CtyId", cityId).findAll();
```

#### Version of Realm and tooling

- Realm version(s): 3.0
- Realm sync feature enabled: no
- Android Studio version: 2.3
- Which Android version and device: 25 & emulator nexus 6

**Comment by RameshReddyKolla** [comment] 2017-04-05 06:34
Please help me for solving this issue

**Comment by Zhuinden** [comment] 2017-04-05 06:39
If you're inserting things on UI thread with local transaction instead of background thread, then Realm 3.1 will fix this.

Although generally the proper solution would have been to do the writes on a background thread, for example using `realm.executeTransactionAsync`

**Comment by RameshReddyKolla** [comment] 2017-04-05 10:25
Thanks! Appreciated your help.
But I don't know the reason, am not getting the exception now. Definitely, will take your points.

**Comment by beeender** [comment] 2017-04-06 03:08
Does `v3.1.0` solve your problem? The problems happens when the indices in `onCitiesIdsSelection` doesn't match your `RealmResults`. in the `v3.0.0`, the listener will be triggered in following UI loops which means if you are updating the city id selection, the UI may have a state that the selections have invalid index which is not in the already refreshed `RealmResults`.

`v3.1.0` changed this behavior, the listener will be called immediately if it is a local transaction.

**Comment by RameshReddyKolla** [comment] 2017-04-06 06:13
Now am using v3.1.0. But in earlier version v3.0.0, got the above problem at mRealm.where(Cities.class).equalTo("CtyId", cityId).findAll(); Here CtyId is my column name.Even with v3.0.0, am unable to replicate the issue.

**Comment by beeender** [comment] 2017-04-06 08:03
OK... So the problem is solved i think? Can we close this issue?

**Comment by RameshReddyKolla** [comment] 2017-04-06 09:01
The problem is solved temporarily, but sometimes am facing the problem like today also have faced the same.Actually am unable to replicate it.

**Comment by beeender** [comment] 2017-04-07 03:09
OK, let us know if you can reproduce the problem. With a minimal project to show the problem, we can help in a better way. I am closing this issue now to make our issue management easier. Feel free to reopen it.

**Closed by beeender** 2017-04-07 03:09 UTC
Labels: T:Help

**Comment by RameshReddyKolla** [comment] 2017-04-07 05:04
okay, sure. Thanks for your support.
