### ISSUE TITLE
Lint errors if minSdk < 11

### ISSUE THREAD

**Issue by grandstaish** [realm/realm-java#3356] opened 2016-08-27 02:13 UTC
Apparently Realm should work on Android all the way down to API 9 (https://realm.io/docs/java/latest/#prerequisites), but if your minSdk is below 11, you get a whole bunch of lint errors that break the build (even with a new Realm sample).

**Comment by zaki50** [comment] 2016-08-27 04:09
I couldn't reproduce this.

Could you share your build.gradle?

**Comment by grandstaish** [comment] 2016-08-27 04:51
Yeah I mean, it's pretty basic. I was just trying Realm out: 

``` groovy
apply plugin: 'com.android.application'
apply plugin: 'realm-android'

android {
  compileSdkVersion rootProject.ext.compileSdkVersion  // <-- this is 24
  buildToolsVersion rootProject.ext.buildToolsVersion  // <-- this is 24.0.2

  defaultConfig {
    applicationId "nz.bradcampbell.realmexample"
    minSdkVersion rootProject.ext.minSdkVersion // <-- this is 9
    targetSdkVersion rootProject.ext.targetSdkVersion // <-- this is 24
    versionCode 1
    versionName "1.0"
  }

  compileOptions {
    sourceCompatibility rootProject.ext.sourceCompatibilityVersion  // <-- this is 1.7
    targetCompatibility rootProject.ext.targetCompatibilityVersion // <-- this is 1.7
  }
}

dependencies {
  compile deps.supportAnnotations // latest
  compile deps.appCompat // latest
}
```

The errors were all to do with `JsonReader` APIs:

e.g.:
- Call requires API level 11 (current min is 9): `android.util.JsonReader#beginObject`
- Call requires API level 11 (current min is 9): `android.util.JsonReader#hasNext`
- Etc.

Are you suppressing your lint errors?

**Comment by kneth** [comment] 2016-08-29 07:55
The proxy classes have `@SuppressWarnings("cast")`.

**Comment by Zhuinden** [comment] 2016-08-29 12:13
@kneth this discussion reminds me of https://github.com/realm/realm-java/pull/489#issuecomment-60139219

**Comment by zaki50** [comment] 2016-08-29 17:47
@grandstaish Thank you for providing detailed information.

 I reproduced this issue.
`./gradlew :app:lint` reports errors of `NewApi: Calling new methods on older versions`.

Realm has a method that uses `JsonReader` in proxy classed but that method does not have `@TargetApi(Build.VERSION_CODES.HONEYCOMB)`. 
Because of this, lint reports errors even if the method is not used at all from user code.

It's a bug of Realm and should be fixed.

And we should update our documentation about limited support of `Realm#create*FromJson()` methods that take `InputStream` as a parameter.
Those methods only support Android 3.0 or later, but it is not mentioned in our documentation (those methods have a annotation of `@TargetApi(Build.VERSION_CODES.HONEYCOMB)` but the annotation is not shown in our API reference).

**Closed** 2016-08-30 04:29 UTC
Labels: S:Review, T:Bug

**Comment by zaki50** [comment] 2016-08-30 04:30
Fixed in `releases` branch.
This issue will be solved in next release.
