### ISSUE TITLE
realm-java and realm-cocoa have different default schemaModes?

### ISSUE THREAD

**Issue by rigdern** [realm/realm-java#6428] opened 2019-02-14 00:27 UTC
I noticed that the default `schemaMode` is inconsistent between realm-java and realm-cocoa:
  - realm-java uses `Manual` ([source](https://github.com/realm/realm-java/blob/f1bf0965f6288876d06872c39a5d786d3c72d658/realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java#L232))
  - realm-cocoa uses `Automatic`

Is this inconsistency intentional? I haven't encountered any adverse implications due to this. I just noticed it when experimenting with Realm. I expect to have very similar Realm code across my iOS and Android apps so this inconsistency stood out to me as being interesting.

#### Version of Realm and tooling

Realm version(s): v5.9.0

Realm Sync feature enabled: No

**Comment by cmelchior** [comment] 2019-02-14 06:56
It is mostly due to historical reasons. When those API's where designed the bindings where much more loosely coupled than they are today.

There are advantages and disadvantages to both approaches.

We probably do not want to completely break the current behaviour, but instead, offer the possibility to choose between which way the migrations are performed. You can see more information here: https://github.com/realm/realm-java/issues/2530

The issue is also being tracked here: https://github.com/realm/realm-java/issues/3999, so closing this as an duplicate.

**Closed by cmelchior** 2019-02-14 06:56 UTC
Labels: O:User, T:Duplicate

**Comment by Zhuinden** [comment] 2019-02-14 13:50
Technically the right way would be for both bindings to support both schema modes, but alas, they don't.
