### ISSUE TITLE
RealmResults not updated when contained objects changed

### ISSUE THREAD

**Issue by rimeissner** [realm/realm-java#2991] opened 2016-06-13 10:25 UTC
#### Goal

I have a list of cool friends and want to change their status to "not" cool (isCool = false).

#### Expected Results

In previous version the Realm Results where updated when an object changed. So the `size()` would always be up to date. Therefore I had a while loop that was just marking friend by friend as not cool until it was empty. After upgrading to Realm 1.0.0 this behaviour changed, but I couldn't find that anywhere documented.

#### Actual Results

Even if the containing results in the RealmResults change it is not updated anymore

#### Steps & Code to Reproduce

- Query Realm with condition
- Modify objects so that the condition doesn't apply anymore

#### Code Sample

```java

RealmResults<Friend> coolFriends = realm.where(Friend.class).equalTo("isCool", true).findAll();
realm.beginTransaction();
while (coolFriends.size() > 0) {
    coolFriends.get(0).setIsCool(false);
}
realm.commitTransaction();
```

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.1

Which Android version and device: Nexus 5, Android 6

Thanks
Richard

**Comment by cmelchior** [comment] 2016-06-13 10:34
This was changed in 0.89 https://realm.io/news/realm-java-0.89.0/ . The reason being that a lot people found the live-update behaviour un-intuitive when iterating over it. This means that RealmResult are still "live", but will only be updated on Looper events. So for the purpose of iterators, they should be considered "stable". This means that changing our code to:

```
for (Friend friend : coolFriends) {
  friend.setIsCool(false);
}
```

should work.
Going over the changelog I realise this isn't exactly clear there. We should update that.

**Comment by rimeissner** [comment] 2016-06-13 10:40
Ok, thanks for the update. I didn't find it, but if known that is understandable behaviour.

**Comment by rimeissner** [comment] 2016-06-13 10:51
@cmelchior One more question on that topic, does this also work with `removeFromRealm()` or will that throw a concurrent modification exception?

**Comment by cmelchior** [comment] 2016-06-13 11:04
Depending on how you do it. If you call it directly on the result it will be modified just like an normal array list: `result.deleteFromFrom(0)` will delete it from the results as well.  `results.get(0).deleteFromRealm()` will not, but leave an invalid object in the results, at least until next Looper event (this was an acceptable trade-off). 

This was also why we changed how change listeners are triggered. They are now only triggered on looper events, so we could guarantee that they will always contain consistent and valid data.

Also note that 0.89 added the RealmCollection interface. This meant we had to change the behaviour of a lot of methods. In general:

- `clear()/remove()` now only operate on the collection, not the underlying Realm data.
- All methods that also delete objects in the Realm are now called `delete*`

The general problem was that e.g. `clear()` worked differently on RealmResults/RealmList, which made it impossible to let them inherit from the same interface. So we had to change things quite a bit. 

We did release it would the migration between e.g 0.88 to 1.0 a bit painful, but it should make things easier to pick up for new projects as well as going forward.

**Comment by Zhuinden** [comment] 2016-06-13 14:11
Yeah, I ran into this issue too - while you're writing directly to the newest version of the Realm during the transaction, your RealmResults are not updated as you're directly writing to it. It's because some people tried to do things like

    RealmResults<Blah> blahs = realm.where(Blah.class).equalTo("blah", true).findAll();
    for(Blah blah : blahs) {
        blah.setBlah(false);
    }

And were in for a surprise that the RealmResults underneath changes.

The "all-round compatible with everything version" is the following

     for(int i = blahs.size()-1; i >= 0; i--) {
         blah.setBlah(false);
     }

**Comment by cmelchior** [comment] 2016-06-13 14:54
As this is working as intended, I'll close this issue.

**Closed by cmelchior** 2016-06-13 14:54 UTC
Labels: T:Help

**Comment by DanteAndroid** [comment] 2017-01-09 02:03
I can't understand, what's the difference? Aren't they just 2 different handwriting of one method?
```
 for(int i = blahs.size()-1; i >= 0; i--) {
     blah.setBlah(false);
 }
for(Blah blah : blahs) {
    blah.setBlah(false);
}
```

**Comment by Zhuinden** [comment] 2017-01-09 07:54
@DanteAndroid no, the iterator that is created by the enhanced for-loop doesn't like the underlying dataset being modified while iterating. 

But 0.89.0+ works with iterators and enhanced for loops
