### ISSUE TITLE
insert data into table will crash with  java.lang.IllegalStateException: Mutable method call during read transaction.

### ISSUE THREAD

**Issue by carl1990** [realm/realm-java#3225] opened 2016-07-29 09:34 UTC
use the version realm `1.0` and run on `xiaomi` device with `android 6.0`
 call this code 

```
    public boolean isValideToday( ) {
        boolean ret = false;
        RealmQuery<SDKInFoRealm> query = realm.where(SDKInFoRealm.class);

        if(query == null)
            return false;
        String dId = Md5Util.getMD5(did);
        query.equalTo("deviceId", dId);
        SDKInFoRealm result = query.findFirst();
        String nowDate = DateUtil.getDate();
        SDKInFoRealm dao = new SDKInFoRealm();
        dao.setDeviceId(dId);
        dao.setStartTime(nowDate);
        if (result == null) {
            dao.setTimes(1);
            ret = true;
        } else {
            String recordDate = result.getStartTime();
            if (recordDate.equals(nowDate)) {
                int toDayTimes = result.getTimes();
                toDayTimes++;
                if (toDayTimes < AllowTimesADay + 1) {
                    ret = true;
                }
                dao.setTimes(toDayTimes);
            } else {
                dao.setTimes(1);
            }
        }
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(dao);
        realm.commitTransaction();
        return ret;
    }
```

will make app crash and no print any info in console .  I debug the code and get the error info is 

 `java.lang.IllegalStateException: Mutable method call during read transaction.`

in method `  realm.copyToRealmOrUpdate()`

**Comment by stk1m1** [comment] 2016-07-29 10:02
Hi @carl1990 

Thanks for the detailed report. Could you add two more information for us to determine the cause of the issue?

1. Version of Realm you're using.
2. Detailed stacktrace.

We'll look forward! Thanks

**Comment by carl1990** [comment] 2016-08-01 03:14
Hi @stk1m1 

I use the realm version is `1.0.0`, and I said 

there is no print any info in console . I debug the code and get the error info is

`java.lang.IllegalStateException: Mutable method call during read transaction`.

in method `realm.copyToRealmOrUpdate()`

**Comment by beeender** [comment] 2016-08-01 07:34
@carl1990 What is the callstack when you debug it? Would you please share the logcat trace?

**Comment by carl1990** [comment] 2016-08-01 07:37
in `realm.copyToRealmOrUpdate()` run into Exception and this lib throw new exception.

now I update Realm to version `1.1.0` . app work well

**Comment by cmelchior** [comment] 2016-08-01 12:55
Hi @carl1990 Sounds like you found a solution. So I'll close this issue now. Feel free to re-open if that was not the case

**Closed by cmelchior** 2016-08-01 12:55 UTC
Labels: T:Help
