### ISSUE TITLE
Realm and RxJava2

### ISSUE THREAD

**Issue by dev-JE02** [realm/realm-java#4135] opened 2017-02-02 01:25 UTC
I would like to ask about Reactive support for Android. Right now we are using RxJava2, and have already found a way to make it Flowable:
```
private void trialRxJava2() {
    Flowable<RealmResults<Model>> flowable = Flowable.using(
            Realm::getDefaultInstance,
            new Function<Realm, Publisher<RealmResults<Model>>>() {
                @Override
                public Publisher<RealmResults<Model>> apply(Realm realm) throws Exception {
                    return Flowable.fromPublisher(realm.where(Model.class)
                            .findAllAsync()
                            .asObservable());
                }
            },
            realm -> realm.close());

    flowable
            .subscribe(new DefaultSubscriber<RealmResults<Model>>() {
                @Override
                public void onNext(RealmResults<Model> models) {
                    models.iterator();
                }

                @Override
                public void onError(Throwable t) {

                }

                @Override
                public void onComplete() {

                }
            });
} 
```

The only thing is, as described in issue #3497 is that the build breaks since `asObservable()` is using RxJava1. Is there a timeline already for this? 

Also, if you could check the DefaultSubscriber, it returns RealmResults<Model> as a whole. Is there a work around here for fine-grained notifications to know which objects have been added, updated, or removed? 

The Android project implements MVVM, and in my View interface, it has add, update, and remove methods so as to call the corresponding method on a FlexibleAdapter and play the desired animation. 

I am not using RealmResults<> in the adapter so as to properly separate View and Model implementations.

#### Version of Realm and tooling
Realm version(s): 2.2.2

Realm sync feature enabled: not yet

Android Studio version: 2.2.3

Which Android version and device: ?

**Comment by Zhuinden** [comment] 2017-02-02 08:35
Proper RxJava2 code based on the RealmObservableFactory would look like this

``` java
    private io.reactivex.Flowable<Realm> getRealm() {
        return io.reactivex.Flowable.create(new FlowableOnSubscribe<Realm>() {
            @Override
            public void subscribe(FlowableEmitter<Realm> emitter)
                    throws Exception {
                RealmConfiguration realmConfiguration = realm.getConfiguration();
                Realm observableRealm = Realm.getInstance(realmConfiguration);

                final RealmChangeListener<Realm> listener = _realm -> {
                    emitter.onNext(_realm);
                };
                emitter.setDisposable(Disposables.fromRunnable(() -> {
                    observableRealm.removeChangeListener(listener);
                    observableRealm.close();
                }));
                observableRealm.addChangeListener(listener);
                emitter.onNext(observableRealm);
            }
        }, BackpressureStrategy.LATEST)
```

Other `asObservable()` implementations can be mapped similarly by using `RealmObservableFactory` as reference

**Comment by cmelchior** [comment] 2017-02-02 09:16
@dev-JE02  RxJava1 is an optional dependency, so you can easily add RxJava 2 to your project as long as you do not call any of the `asObservable` methods. Instead you would just have make your own factory class like the one @Zhuinden describes.

Right now it looks like we will do the following going forward:

1) Create a `RxRealm` package with a `RxRealm` factory class for creating RxJava 2 types (Observable/Flowable/Completable/<others?>).  This also has the benefit that we can easier support more types.

2) Deprecate the `asObservable` methods, which will then be removed at a later release.

We do realize that the `asObservable()` methods are really convenient, but it is impossible to support both RxJava1 and 2 with them. Depending on community feedback I could be convinced to keep them, but we would not support two versions of RxJava, they would only support whatever version of RxJava has the biggest market share (which is v1 at the moment)

I'll close this as an duplicate of #3497

**Closed by cmelchior** 2017-02-02 09:16 UTC
