### ISSUE TITLE
Crash at Realm.getDefaultInstance() 

### ISSUE THREAD

**Issue by vianairan** [realm/realm-java#3934] opened 2016-12-20 20:15 UTC
I'm using Realm in one of my projects. It works great on almost all the phones I tested except for **Samsung GT-I8200 (Android 4.2.2).** 

The app crashes when requesting the default realm instance. Please note that I haven't encountered this crash on any other phones. My concern is that the same crash may exist on many other android devices that we haven't tested. 

I'm using realm 2.2.1. I also tested this use case against realm 2.0.2. The same issue exist on both versions. Further, I ran a couple of Realm sample apps (introExample and gridViewExample) on the same device. Both apps crash at the same line (Realm.getDefaultInstance()). 

While debugging, I found out that actual crash happens inside SharedRealm.java file - line 236 - nativeSetVersion(nativePtr, schemaVersion). 

Can you please any solution for this?

Thanks,
Iranga

**Comment by Zhuinden** [comment] 2016-12-20 20:19
This sounds eerily similar to https://github.com/realm/realm-java/issues/3651

**Comment by vianairan** [comment] 2016-12-20 20:40
@Zhuinden yes, thanks. Hope the issue will be fixed soon.

**Comment by Zhuinden** [comment] 2016-12-20 21:19
Same. Until then, I tend to recommend 1.2.0.

**Comment by vianairan** [comment] 2016-12-20 21:44
@Zhuinden thanks for the suggestion. Do you have any idea about how many devices are affected by this? Or what devices are affected.

**Comment by Zhuinden** [comment] 2016-12-20 22:31
@vianairan Samsung devices stuck between 4.1 and 4.2.2.

I wonder if it had crashed on my Samsung Note 1 with vanilla Samsung kernel. The EXYNOS series had a series bug which could cause such corruption, I think.

**Comment by vianairan** [comment] 2016-12-20 22:37
Thanks @Zhuinden. 

So far, we tested on these samsung phones before 4.2.2.
SGH-I200PP (Android 4.1.2)
GT-I8552 (Android 4.1.2)
Samsung GT-I8200 (Android 4.2.2)

The realm only crashes on Samsung GT-I8200.

**Comment by cmelchior** [comment] 2016-12-21 08:17
Hi @vianairan This is a duplicate of #3651, so I'll close this as an duplicate . We have acquired a device and @kneth  looking into it as we speak. Right now it looks like a case of "WFT Samsung", but we hopefully have something to share within the next couple of days.

**Closed by cmelchior** 2016-12-21 08:17 UTC

**Comment by Zhuinden** [comment] 2017-03-30 12:04
https://github.com/realm/realm-java/pull/4402 might fix this once it's merged
