### ISSUE TITLE
I want to reach realm object immediately written on Realm Thread from main Thread. It's not support new Version(1.2.0). 

### ISSUE THREAD

**Issue by dralexnumber** [realm/realm-java#4250] opened 2017-02-24 15:15 UTC
#### Goal

> I can write and read from Realm Database on same realm thread one by one. But I want to read data from Realm Database in different threads that not written same thread like a main thread.(Version 1.2.0 support but Version 2.3.1 doesn't support.) Just I can do on Version 2.3.1 when I use Thread.Sleep(). So I can read data from database, if I wait some times . But I don't have to stop thread when I use Version 1.2.0. Could you help me please ?

#### Expected Results

> I want to reach realm object immediately written on Realm Thread from main Thread.

#### Actual Results

>  I could do when I was using realm 1.2.0 version. But now on new version doesn't support that. What can I do ?

#### Steps & Code to Reproduce

1. Create realm object in realm Thread.
2. Send ID of Realm Object to another thread(Main Thread).
3. Get with Queries Realm Object from Realm Database 
4. Result gets null but It's written on short time ago.

#### Code Sample

```java
    public void newObject(final String text) {

        RealmRunnable realmRunnable = new RealmRunnable() {
            @Override
            public void run() {
                //REALM THREAD START 
                    Realm mRealm = getRealm();

                    if (text.length() != 0 && !TextUtils.isEmpty(text)) {

                        long currentTime = System.currentTimeMillis();

                        Text text1 = textCRUD.addText(serverId, currentTime,
                                currentTime, text, mRealm);//Realm Insert Object

                         addObjectToList1(text1.getObjectId);
                    }
                //REALM THREAD STOP
            }
        };

        MyApplication.getInstance().getRealmController().addRealmRunnable(realmRunnable);

    }


    public void addObjectToList1(final int objectId) {

            AndroidUtilities.runOnUIThread(new Runnable() {
                @Override
                public void run() {
                    //MAIN THREAD START 
                    Text text1 = new TextQueries().searchTextById(objectId, getRealm());//Realm Queries

                    if (text1 != null) {
                      Mylod.d("addObjectToList: ","text1!=null");
                    }
                    else{
                      Mylod.d("addObjectToList: ","text1==null");
                    }
                    //MAIN THREAD STOP 
                }
            });
    }



```

#### Version of Realm and tooling
Realm version(s): 2.3.1

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: Android 6.0.1 and Samsung SM-G920F

**Comment by Zhuinden** [comment] 2017-02-24 15:31
https://medium.com/@Zhuinden/basics-of-realm-a-guide-to-using-realm-1-2-0-634471c0fe8f

https://medium.com/@Zhuinden/how-to-use-realm-for-android-like-a-champ-and-how-to-tell-if-youre-doing-it-wrong-ac4f66b7f149

https://github.com/Zhuinden/simple-stack/blob/master/simple-stack-example-mvp/src/main/java/com/zhuinden/simplestackdemoexamplemvp/data/repository/TaskRepository.java#L197-L204

**Comment by cmelchior** [comment] 2017-02-26 21:13
Realm is an MVCC database, which means that each thread is locked to a specific version of the database. When a background thread writes to the DB we use the Looper to notify the UI thread that it can advance to the latest version. However sometimes it takes a while for this change to actually appear on the UI thread, since we e.g. need to rerun all async queries before advancing the version. 

This is the reason that you should use RealmChangeListeners to be notified about events like this, because they will be triggered when everything is in a consistent state.

So it is actually working as intended. Closing

**Closed by cmelchior** 2017-02-26 21:13 UTC

**Comment by Zhuinden** [comment] 2017-02-27 07:36
@cmelchior I kinda want to cite that the [docs don't really mention this until the linked issue is fixed](https://github.com/realm/realm-java/issues/4098)

**Comment by cmelchior** [comment] 2017-02-27 08:07
@Zhuinden Your right. Thanks for the reminder 😄
