### ISSUE TITLE
Inconsistent Realm Filename in Configuration

### ISSUE THREAD

**Issue by grahamsmith** [realm/realm-java#2698] opened 2016-04-28 08:59 UTC
#### Goal

I use a separate App to create a Realm file for use across multiple platforms.
#### Expected Results

The RealmConfiguration object has a name method that I provide the name of the file I want generated without a file extension.

Input: `foo`
Filename `foo.realm` (confirmed using an emulator and checking internal storage)
#### Actual Results

Using the same configuration in the App, with the same classes, the filename being accessed is `foo` not `foo.realm`.

As a result I have to change the name specified to `foo.realm`.
#### Steps & Code to Reproduce

Create a new App and use the configuration where the file name is `foo`. Create a Realm file by adding data per the docs. 

Copy the file into another App (Via Assets then copying into the working internal storage directory at runtime).

Use the same configuration as in the previous File Creation App. Try loading a known object. This should return null.

Update the configuration to include the `.realm` extension and rerun. The object should not be null.
#### Code Sample

``` java

RealmConfiguration supportRealmConfiguration = new RealmConfiguration.Builder(getContext().getApplicationContext())
                .name("support")
                .setModules(new SupportModule())
                .schemaVersion(1)
                .build();

```

``` java

RealmConfiguration supportRealmConfiguration = new RealmConfiguration.Builder(getContext().getApplicationContext())
                .name("support.realm")
                .setModules(new SupportModule())
                .schemaVersion(1)
                .build();

```
#### Version of Realm and tooling

Realm version(s): 0.88.2

Android Studio version: 2.0

Which Android version and device: 5.0+

**Comment by cmelchior** [comment] 2016-04-28 09:04
Hi @grahamsmith 
That is actually by design, the name parameter in the `RealmConfiguration` is the _full_ filename. There isn't any technical reason for us to force the the file extension to be `.realm`, so I would be reluctant to add that.

Perhaps using `name` as the parameter is confusing and we should change that to `filename` instead?

**Comment by grahamsmith** [comment] 2016-04-28 09:10
I think that's a good idea but it doesn't solve the issue.

I missed stating that if I used `foo.realm` as my name in the generation app, then the file name becomes `foo.realm.realm`. This still doesn't seem valid behaviour?

**Comment by cmelchior** [comment] 2016-04-28 09:15
@grahamsmith Ok thanks. I think I misunderstood the problem. I'll look into it.

**Comment by grahamsmith** [comment] 2016-04-28 09:17
Thanks for the quick turnaround. Still rename the method as described.

**Comment by cmelchior** [comment] 2017-01-30 14:26
Duplicate of #2699

**Closed by cmelchior** 2017-01-30 14:26 UTC
Labels: S:Idea Backlog
