### ISSUE TITLE
Warning in build on new AndroidStudio 3 Canary & Gradle 4

### ISSUE THREAD

**Issue by Ajtak** [realm/realm-java#4661] opened 2017-05-18 11:12 UTC
In new Android studio 3,0 & Gradle 4 is gradle console show warning message, as is:
![obrazek](https://cloud.githubusercontent.com/assets/4963819/26199757/81e98c22-3bcb-11e7-8481-fc2c2bd7aaa0.png)

#### Version of Realm and tooling
Realm version(s): 3.2.0

Realm sync feature enabled: no

Android Studio version: 3.0

**Comment by cmelchior** [comment] 2017-05-18 11:15
Duplicate of #4659

**Closed by cmelchior** 2017-05-18 11:15 UTC
