### ISSUE TITLE
Invalid top array (ref, [0], [1], [2]): 64043160, 0, 0, 1

### ISSUE THREAD

**Issue by JoyHong** [realm/realm-java#6990] opened 2020-07-07 06:42 UTC
➤ Christan Melchior commented:

We believe this should be fixed in 7.0.1 which was just released. Please reopen if that is not the case.

_Originally posted by @RealmBot in https://github.com/realm/realm-java/issues/6946#issuecomment-652490372_

**Comment by JoyHong** [comment] 2020-07-07 06:43
Dears, it still exist in 7.0.1

io.realm.exceptions.RealmFileException

Invalid top array (ref, [0], [1], [2]): 64043160, 0, 0, 1 Exception backtrace: <backtrace not supported on this platform> () in /Users/eduardo.lopez/git/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107

io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)

io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
io.realm.a.<init>(BaseRealm.java:137)
io.realm.a.<init>(BaseRealm.java:104)
io.realm.w.<init>(Realm.java:163)
io.realm.w.a(Realm.java:499)
io.realm.y.a(RealmCache.java:507)
io.realm.y.a(RealmCache.java:473)
io.realm.y.a(RealmCache.java:414)
io.realm.w.b(Realm.java:428)

**Comment by bmunkholm** [comment] 2020-07-07 13:41
It looks like your realm file is corrupt. Even when upgrading to a new version of Java, you will keep getting this message.
Is it something you see repeatedly? Locally or in production?

**Comment by JoyHong** [comment] 2020-07-08 03:58
in production, i get this error on bugly

**Comment by bmunkholm** [comment] 2020-07-08 10:49
How many times have you seen this?
Is it always the exact same Exception?

**Comment by JoyHong** [comment] 2020-07-09 02:30
about 500 times

**Comment by bmunkholm** [comment] 2020-07-14 07:35
@JoyHong
1) Is it always the same exception and numbers in the exception?
2) Do you know if it only occurs after upgrading to 7.0.1?

(cc @jedelbo @finnschiermer )

**Comment by JoyHong** [comment] 2020-07-14 09:29
@bmunkholm 

i only know after i upgrade to 7.0.1 from 6.+, i get much this crash from googleplay and bugly ...

i don't how to repreduce it..

**Comment by JoyHong** [comment] 2020-07-14 09:30
i have no idea how to fix, so please help.

**Comment by bmunkholm** [comment] 2020-07-14 12:19
@JoyHong What's the answer to my question "Is it always the same exception and numbers in the exception?"?

And additionally: I assume you can't obtain and give us one of the realms that are failing to open?

**Comment by JoyHong** [comment] 2020-07-15 09:12
@bmunkholm sorry for my poor understanding.

for the same user, it seems always the same exception and numbers in the exception.
i can't obtain the realms files since i doesn't upload user's realm file to server now.

**Comment by jedelbo** [comment] 2020-07-15 09:26
@JoyHong If the same user opens the same file again and again, then you will of course get the same error. But do you see the same numbers from different users?

**Comment by JoyHong** [comment] 2020-07-16 03:44
from bugly, it seems that they are difference numbers from difference users.

**Comment by cmelchior** [comment] 2020-08-14 12:05
We just released 7.0.2 which fixes a number of bugs. Including bugs of this type. Unfortunately we haven't been able to reproduce this, but I'm closing this with the assumption it has been fixed. 

If you still see this after upgrading to 7.0.2, feel free to reopen.

**Closed by cmelchior** 2020-08-14 12:05 UTC
Labels: O-Community, Reproduction-Required
