### ISSUE TITLE
App crashing on code line for obtaining Realm instance

### ISSUE THREAD

**Issue by Keshava11** [realm/realm-java#984] opened 2015-03-23 10:09 UTC
Hi I have created a sample app using realm 8.0.0. 
App was working perfectly fine till last friday but when I tried to run the same code app is crshing with the following exceptions. 

mRealmInstance = Realm.getInstance(this);

Following is the stacktrace from the logcat

03-23 15:30:20.716  16611-16611/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.realmplay/com.realmplay.RealmPlayActivity}: io.realm.exceptions.RealmException: Could not find io.realm.RealmJsonImpl
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2355)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
            at android.app.ActivityThread.access$600(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5520)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: io.realm.exceptions.RealmException: Could not find io.realm.RealmJsonImpl
            at io.realm.Realm.getRealmJson(Realm.java:268)
            at io.realm.Realm.<init>(Realm.java:164)
            at io.realm.Realm.createAndValidate(Realm.java:522)
            at io.realm.Realm.create(Realm.java:486)
            at io.realm.Realm.getInstance(Realm.java:404)
            at io.realm.Realm.getInstance(Realm.java:366)
            at io.realm.Realm.getInstance(Realm.java:347)
            at com.realmplay.base.BaseActionBarActivity.onCreate(BaseActionBarActivity.java:35)
            at com.realmplay.RealmPlayActivity.onCreate(RealmPlayActivity.java:26)
            at android.app.Activity.performCreate(Activity.java:5066)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
            at android.app.ActivityThread.access$600(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5520)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: io.realm.RealmJsonImpl
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at java.lang.Class.forName(Class.java:172)
            at io.realm.Realm.getRealmJson(Realm.java:263)
            at io.realm.Realm.<init>(Realm.java:164)
            at io.realm.Realm.createAndValidate(Realm.java:522)
            at io.realm.Realm.create(Realm.java:486)
            at io.realm.Realm.getInstance(Realm.java:404)
            at io.realm.Realm.getInstance(Realm.java:366)
            at io.realm.Realm.getInstance(Realm.java:347)
            at com.realmplay.base.BaseActionBarActivity.onCreate(BaseActionBarActivity.java:35)
            at com.realmplay.RealmPlayActivity.onCreate(RealmPlayActivity.java:26)
            at android.app.Activity.performCreate(Activity.java:5066)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
            at android.app.ActivityThread.access$600(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5520)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoClassDefFoundError: io/realm/RealmJsonImpl
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at java.lang.Class.forName(Class.java:172)
            at io.realm.Realm.getRealmJson(Realm.java:263)
            at io.realm.Realm.<init>(Realm.java:164)
            at io.realm.Realm.createAndValidate(Realm.java:522)
            at io.realm.Realm.create(Realm.java:486)
            at io.realm.Realm.getInstance(Realm.java:404)
            at io.realm.Realm.getInstance(Realm.java:366)
            at io.realm.Realm.getInstance(Realm.java:347)
            at com.realmplay.base.BaseActionBarActivity.onCreate(BaseActionBarActivity.java:35)
            at com.realmplay.RealmPlayActivity.onCreate(RealmPlayActivity.java:26)
            at android.app.Activity.performCreate(Activity.java:5066)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
            at android.app.ActivityThread.access$600(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5520)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: io.realm.RealmJsonImpl
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:217)
            at java.lang.Class.forName(Class.java:172)
            at io.realm.Realm.getRealmJson(Realm.java:263)
            at io.realm.Realm.<init>(Realm.java:164)
            at io.realm.Realm.createAndValidate(Realm.java:522)
            at io.realm.Realm.create(Realm.java:486)
            at io.realm.Realm.getInstance(Realm.java:404)
            at io.realm.Realm.getInstance(Realm.java:366)
            at io.realm.Realm.getInstance(Realm.java:347)
            at com.realmplay.base.BaseActionBarActivity.onCreate(BaseActionBarActivity.java:35)
            at com.realmplay.RealmPlayActivity.onCreate(RealmPlayActivity.java:26)
            at android.app.Activity.performCreate(Activity.java:5066)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
            at android.app.ActivityThread.access$600(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5520)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
            at dalvik.system.NativeStart.main(Native Method)
03-23 15:30:20.726      345-688/? E/EmbeddedLogger﹕ App crashed! Process: com.realmplay
03-23 15:30:20.726      345-688/? E/EmbeddedLogger﹕ App crashed! Package: com.realmplay v1 (1.0)
03-23 15:30:20.736      345-688/? E/EmbeddedLogger﹕ Application Label: RealmPlay

**Comment by kneth** [comment] 2015-03-23 15:58
For some reason, the class `RealmJsonImpl` hasn't been generated. Can you try to clean your project and rebuild it?

**Comment by Keshava11** [comment] 2015-03-24 11:50
I tried cleaning and rebuilding project multiple times but still getting the same crash on the same line for obtaining Realm instance.

**Comment by cmelchior** [comment] 2015-03-24 20:53
Hi @Keshava11 
Does any of your RealmObjects contain any custom getters and setters? We found a bug in our annotation processor that accidentally allowed those in previous releases, and this bug was fixed in 0.80.0 The error you are getting comes when the annotation processor isn't running or exited with a failure, which might be a result of this change.

**Comment by Keshava11** [comment] 2015-03-25 13:10
Hi @cmelchior Yes you were right. 

I did added a new modal class which was crashing the app crash. I removed it and all went well as earlier.

I am adding that modal class. I think issue must be with the Date type. 

import java.util.Date;

import io.realm.RealmObject;

/**
 * Simple bean class that holds variable to store patient's health data recorded at a particular time
 * Created by ravikumar on 23/3/15.
 */
public class PatientHealthData extends RealmObject {

    private float mWeight =0.0f;
    private int mBloodSugar = 0;
    private Date mRecordDate = null;

    public float getWeight() {
        return mWeight;
    }

    public void setWeight(float mWeight) {
        this.mWeight = mWeight;
    }

    public int getBloodSugar() {
        return mBloodSugar;
    }

    public void setBloodSugar(int mBloodSugar) {
        this.mBloodSugar = mBloodSugar;
    }

    public Date getRecordDate() {
        return mRecordDate;
    }

    public void setRecordDate(Date mRecordDate) {
        this.mRecordDate = mRecordDate;
    }
}


Can you please check and confirm the issue ?

Thanks for your help

**Comment by cmelchior** [comment] 2015-03-25 19:07
Hi @Keshava11 
The problem is in the naming of the getters and setters. Currently Realm has pretty strict requirements for then naming, which we are hoping to relax soon. If you replace you class with this, it should work:

```
public class PatientHealthData extends RealmObject {

    private float mWeight = 0.0f;
    private int mBloodSugar = 0;
    private Date mRecordDate = null;

    public float getmWeight() {
        return mWeight;
    }

    public void setmWeight(float mWeight) {
        this.mWeight = mWeight;
    }

    public int getmBloodSugar() {
        return mBloodSugar;
    }

    public void setmBloodSugar(int mBloodSugar) {
        this.mBloodSugar = mBloodSugar;
    }

    public Date getmRecordDate() {
        return mRecordDate;
    }

    public void setmRecordDate(Date mRecordDate) {
        this.mRecordDate = mRecordDate;
    }
}
```

**Comment by Kml55** [comment] 2015-03-30 09:47
I faced with same problem. Everything was working fine with one model class. Then I add a new model class this problem starts to occur. I found why it occurs by trying comment some pojo fields with its getter and setters. If I comment this field and its getter and setter,problem is resolved after rebuild project on android studio..

Commented field and its getter and setter
private int isActive;
public int getIsActive() {
        return isActive;
}
public void setIsActive(int isActive) {
        this.isActive = isActive;
}


Is it normal? I think the problem is that my pojo field name starts with "is" but its type is not boolean :)

Am I correct ?

**Comment by emanuelez** [comment] 2015-03-31 09:28
You are correct. To be on the safe side I would rename the field to `active` and the accessors to `getActive` and `setActive`

**Comment by Kml55** [comment] 2015-03-31 11:28
Thanks. I made them boolean. it works. boolean is the best practice.

**Comment by Keshava11** [comment] 2015-03-31 13:33
Hi @cmelchior 

Yes you are right . I tried it and it worked perfectly. 

Thanks

**Closed** 2015-04-01 10:02 UTC
Labels: support
