### ISSUE TITLE
RealmError: Unrecoverable error. mmap() failed: Bad file descriptor in io_realm_internal_SharedGroup.cpp line 113

### ISSUE THREAD

**Issue by GaborPeto** [realm/realm-java#3179] opened 2016-07-13 09:24 UTC
#### Goal

Get Realm Instance
#### Expected Results

Realm Instance is returned
#### Actual Results

Caused by io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Bad file descriptor in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:64)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
       at io.realm.BaseRealm.<init>(BaseRealm.java:76)
       at io.realm.Realm.<init>(Realm.java:138)
       at io.realm.Realm.createAndValidate(Realm.java:268)
       at io.realm.Realm.createInstance(Realm.java:248)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:213)
       at com.myapp,MyOperation.getRealm(MyOperation.java:79)
#### Steps & Code to Reproduce

Happened once for a user in production, was unable to reproduce
#### Version of Realm and tooling

Realm version(s): 0.88.3

Android Studio version: 2.1.1

Which Android version and device: Nexus 5X, Android N

**Comment by beeender** [comment] 2016-07-13 09:54
hello! this is the first time i saw this crash too. Not sure if it is caused by the user's hardware/android framework/kernel or we have a really deep bug :P 

I will keep this issue open for a little while to see if there are any others meet the same issue. But without more information/reproducible environment, we don't have a better answer for it :(

BTW, if possible, please switch to the latest version of Realm. We might have fixed the issue.

**Comment by Zhuinden** [comment] 2016-07-13 15:14
Please note the breaking changes in 0.89.0 if you update, it changes synchronous `commitTransaction()`, removes `refresh()` and changes the way `RealmResults<T>` works in transactions.

**Comment by cmelchior** [comment] 2019-11-27 16:10
Outdated. Closing since no other reports about this seems to have surfaced.

**Closed** 2019-11-27 16:12 UTC
Labels: O-Community, Pipeline-On-Hold, Reproduction-Required, T-Bug

**Comment by crescent7272** [comment] 2019-11-28 19:18
I have faced with the same issue!!! Why did that happen?? These are my dependencies.
```
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
```

I suspect from these lines :

```
Realm realmInstance = null;

        try {
            realmInstance = Realm.getDefaultInstance();
            realmInstance.beginTransaction();

            realmInstance.insertOrUpdate(objectToSave);
            realmInstance.commitTransaction();


            //T result = filter.call(realmInstance.where(clazz)).findFirst();
            //onResult.call(Result.getData(result));
            if(!realmInstance.isClosed()) {
                realmInstance.close();
                onSuccess.call();
            }

        } catch (Exception e) {
            if (realmInstance != null && !realmInstance.isClosed()) {
                realmInstance.close();
            }
            e.printStackTrace();
            onError.call(e);
        }
```

Thanks
