### ISSUE TITLE
Native Crash with Realm.getInstance(appContext)

### ISSUE THREAD

**Issue by HPIWicket** [realm/realm-java#810] opened 2015-02-02 10:48 UTC
Hey,
I just reinstalled our App on the S3 Mini (GTI8200N) and afterwards it is crashing when it tries to initialise the Realm instance.

It could be narrowed down to the invocation of the "initTableMethod" (Realm.java:505). The result is a native crash (log at the end). The class for which the Proxy is generated there has 2 fields, one int called "id" and a String called "name".

Deinstalling and reinstalling, as well as rebooting the device does not work. This error only occurred on one device until now, but the app is not recoverable in any way for this device.

The used Realm version is included with gradle using version 0.78.+ 

/dalvikvm( 5038): Trying to load lib /data/app-lib/x/libtightdb-jni.so 0x421fca50
D/dalvikvm( 5038): Added shared lib /data/app-lib/x/libtightdb-jni.so 0x421fca50
F/libc    ( 5038): Fatal signal 11 (SIGSEGV) at 0x5abdbffe (code=2), thread 5038 ()
I/DEBUG   (  106): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  106): Build fingerprint: 'samsung/goldenve3gxx/goldenve3g:4.2.2/JDQ39/I8200NXXUANI2:user/release-keys'
I/DEBUG   (  106): Revision: '3'
I/DEBUG   (  106): pid: 5038, tid: 5038, name: 
I/DEBUG   (  106): signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 5abdbffe
I/DEBUG   (  106):     r0 5abdbffe  r1 5abdc002  r2 5ac191ff  r3 5abdbffe
I/DEBUG   (  106):     r4 5bcc99f0  r5 00000008  r6 be840270  r7 00000000
I/DEBUG   (  106):     r8 5ac56400  r9 00000001  sl 00000000  fp be8403d4
I/DEBUG   (  106):     ip 00000000  sp be840250  lr 5f514471  pc 5f514450  cpsr 80000030
I/DEBUG   (  106):     d0  61545f7373616c63  d1  56d9319856d931f1
I/DEBUG   (  106):     d2  56d9320856d931c8  d3  56d9327856d9325a
I/DEBUG   (  106):     d4  5715036856d932b0  d5  571503d8571503a0
I/DEBUG   (  106):     d6  5715f12057150410  d7  5715f1905715f158
I/DEBUG   (  106):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  106):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  106):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  106):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  106):     d16 4040000000000000  d17 4040000000000000
I/DEBUG   (  106):     d18 0000000000000000  d19 0000000000000000
I/DEBUG   (  106):     d20 4008000000000000  d21 3fbc71c71c71c71c
I/DEBUG   (  106):     d22 3fcc7288e957b53b  d23 3fd24998d6307188
I/DEBUG   (  106):     d24 3fd99a27ad32ddf5  d25 3fe555b0aaeac752
I/DEBUG   (  106):     d26 0000000000000000  d27 0000000000000000
I/DEBUG   (  106):     d28 0000000000000000  d29 0000000000000000
I/DEBUG   (  106):     d30 0000000000000000  d31 0000000000000000
I/DEBUG   (  106):     scr 20000010
I/DEBUG   (  106): 
I/DEBUG   (  106): backtrace:
I/DEBUG   (  106):     #00  pc 00066450  /data/app-lib/x/libtightdb-jni.so (tightdb::ArrayString::set(unsigned int, tightdb::StringData)+183)
I/DEBUG   (  106):     #01  pc 00066501  /data/app-lib/x/libtightdb-jni.so (tightdb::ArrayString::insert(unsigned int, tightdb::StringData)+68)
I/DEBUG   (  106):     #02  pc 0008d70d  /data/app-lib/x/libtightdb-jni.so (tightdb::Spec::insert_column(unsigned int, tightdb::ColumnType, tightdb::StringData, tightdb::ColumnAttr)+30)
I/DEBUG   (  106): 
I/DEBUG   (  106): stack:
I/DEBUG   (  106):          be840210  4183d0e0  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (  106):          be840214  40a66e70  /system/lib/libdvm.so
I/DEBUG   (  106):          be840218  5f514365  /data/app-lib/x/libtightdb-jni.so (tightdb::ArrayString::CalcItemCount(unsigned int, unsigned int) const)
I/DEBUG   (  106):          be84021c  5f4e0449  /data/app-lib/x/libtightdb-jni.so (tightdb::Array::alloc(unsigned int, unsigned int)+172)
I/DEBUG   (  106):          be840220  00000073  
I/DEBUG   (  106):          be840224  40a66f23  /system/lib/libdvm.so
I/DEBUG   (  106):          be840228  40a66e99  /system/lib/libdvm.so
I/DEBUG   (  106):          be84022c  40a11f4f  /system/lib/libdvm.so
I/DEBUG   (  106):          be840230  5bcc99f0  
I/DEBUG   (  106):          be840234  5bcc99f0  
I/DEBUG   (  106):          be840238  00000008  
I/DEBUG   (  106):          be84023c  be840270  [stack]
I/DEBUG   (  106):          be840240  00000004  
I/DEBUG   (  106):          be840244  5bcc98e0  
I/DEBUG   (  106):          be840248  df0027ad  
I/DEBUG   (  106):          be84024c  00000000  
I/DEBUG   (  106):     #00  be840250  5bcc99f0  
I/DEBUG   (  106):          be840254  00000001  
I/DEBUG   (  106):          be840258  be840298  [stack]
I/DEBUG   (  106):          be84025c  00000004  
I/DEBUG   (  106):          be840260  5bcc98e0  
I/DEBUG   (  106):          be840264  00000002  
I/DEBUG   (  106):          be840268  00000000  
I/DEBUG   (  106):          be84026c  5f514505  /data/app-lib/x/libtightdb-jni.so (tightdb::ArrayString::insert(unsigned int, tightdb::StringData)+72)
I/DEBUG   (  106):     #01  be840270  5ac51778  
I/DEBUG   (  106):          be840274  00000004  
I/DEBUG   (  106):          be840278  be840298  [stack]
I/DEBUG   (  106):          be84027c  5bcc98e0  
I/DEBUG   (  106):          be840280  00000002  
I/DEBUG   (  106):          be840284  00000001  
I/DEBUG   (  106):          be840288  00000001  
I/DEBUG   (  106):          be84028c  5f53b711  /data/app-lib/x/libtightdb-jni.so (tightdb::Spec::insert_column(unsigned int, tightdb::ColumnType, tightdb::StringData, tightdb::ColumnAttr)+34)
I/DEBUG   (  106):     #02  be840290  00000000  
I/DEBUG   (  106):          be840294  00000000  
I/DEBUG   (  106):          be840298  5ac51778  
I/DEBUG   (  106):          be84029c  00000004  
I/DEBUG   (  106):          be8402a0  5ac32ad0  
I/DEBUG   (  106):          be8402a4  5bcc97c8  
I/DEBUG   (  106):          be8402a8  be8402c0  [stack]
I/DEBUG   (  106):          be8402ac  00000000  
I/DEBUG   (  106):          be8402b0  00000001  
I/DEBUG   (  106):          be8402b4  5f53c351  /data/app-lib//libtightdb-jni.so (tightdb::Table::do_insert_root_column(unsigned int, tightdb::ColumnType, tightdb::StringData)+40)
I/DEBUG   (  106):          be8402b8  00000000  
I/DEBUG   (  106):          be8402bc  40a861b0  /system/lib/libdvm.so
I/DEBUG   (  106):          be8402c0  5ac51778  
I/DEBUG   (  106):          be8402c4  00000004  
I/DEBUG   (  106):          be8402c8  00000001  
I/DEBUG   (  106):          be8402cc  00000001  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near r0:
I/DEBUG   (  106):     5abdbfdc 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5abdbfec 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5abdbffc 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc00c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5abdc01c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc02c 00000004 00040000 00000400 00080000  
I/DEBUG   (  106):     5abdc03c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc04c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5abdc05c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc06c 00000004 00040000 00000800 00040000  
I/DEBUG   (  106):     5abdc07c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc08c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5abdc09c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc0ac 00000004 00040000 00000400 00080000  
I/DEBUG   (  106):     5abdc0bc 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc0cc 00000004 00040000 00000400 04040000  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near r1:
I/DEBUG   (  106):     5abdbfe0 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5abdbff0 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5abdc000 00040000 00000400 00040000 00000004  
I/DEBUG   (  106):     5abdc010 00040000 00000400 04040000 00000000  
I/DEBUG   (  106):     5abdc020 00040000 00000400 00040000 00000004  
I/DEBUG   (  106):     5abdc030 00040000 00000400 00080000 00000000  
I/DEBUG   (  106):     5abdc040 00040000 00000400 00040000 00000004  
I/DEBUG   (  106):     5abdc050 00040000 00000400 04040000 00000000  
I/DEBUG   (  106):     5abdc060 00040000 00000400 00040000 00000004  
I/DEBUG   (  106):     5abdc070 00040000 00000800 00040000 00000000  
I/DEBUG   (  106):     5abdc080 00040000 00000400 00040000 00000004  
I/DEBUG   (  106):     5abdc090 00040000 00000400 04040000 00000000  
I/DEBUG   (  106):     5abdc0a0 00040000 00000400 00040000 00000004  
I/DEBUG   (  106):     5abdc0b0 00040000 00000400 00080000 00000000  
I/DEBUG   (  106):     5abdc0c0 00040000 00000400 00040000 00000004  
I/DEBUG   (  106):     5abdc0d0 00040000 00000400 04040000 00000000  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near r2:
I/DEBUG   (  106):     5ac191dc 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac191ec 00000004 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac191fc 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac1920c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5ac1921c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac1922c 00000004 00040000 00000400 00080000  
I/DEBUG   (  106):     5ac1923c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac1924c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5ac1925c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac1926c 00000004 00040000 00000800 00040000  
I/DEBUG   (  106):     5ac1927c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac1928c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5ac1929c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac192ac 00000004 00040000 00000400 00080000  
I/DEBUG   (  106):     5ac192bc 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5ac192cc 00000004 00040000 00000400 04040000  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near r3:
I/DEBUG   (  106):     5abdbfdc 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5abdbfec 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5abdbffc 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc00c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5abdc01c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc02c 00000004 00040000 00000400 00080000  
I/DEBUG   (  106):     5abdc03c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc04c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5abdc05c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc06c 00000004 00040000 00000800 00040000  
I/DEBUG   (  106):     5abdc07c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc08c 00000004 00040000 00000400 04040000  
I/DEBUG   (  106):     5abdc09c 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc0ac 00000004 00040000 00000400 00080000  
I/DEBUG   (  106):     5abdc0bc 00000000 00040000 00000400 00040000  
I/DEBUG   (  106):     5abdc0cc 00000004 00040000 00000400 04040000  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near r4:
I/DEBUG   (  106):     5bcc99d0 5ac79120 00000000 00000000 00000000  
I/DEBUG   (  106):     5bcc99e0 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5bcc99f0 5f5acf00 5ac56400 00001800 00000002  
I/DEBUG   (  106):     5bcc9a00 0000000f 00000004 00000000 5bcc98e0  
I/DEBUG   (  106):     5bcc9a10 00000001 5ac94590 5f4e4a8b 00000000  
I/DEBUG   (  106):     5bcc9a20 5f4e4b39 00000000 5f4e4b79 00000000  
I/DEBUG   (  106):     5bcc9a30 5f4e730b 00000000 5f4e9697 00000000  
I/DEBUG   (  106):     5bcc9a40 5f4ebd93 00000000 00000000 00000000  
I/DEBUG   (  106):     5bcc9a50 5f4ee457 00000000 00000000 00000000  
I/DEBUG   (  106):     5bcc9a60 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5bcc9a70 00000000 00000000 5f5aced0 5ac56480  
I/DEBUG   (  106):     5bcc9a80 00001880 00000001 ffffffff 00000000  
I/DEBUG   (  106):     5bcc9a90 00000000 5bcc98e0 00000002 5ac94590  
I/DEBUG   (  106):     5bcc9aa0 5f4e4a8b 00000000 5f4e4b39 00000000  
I/DEBUG   (  106):     5bcc9ab0 5f4e4b79 00000000 5f4e730b 00000000  
I/DEBUG   (  106):     5bcc9ac0 5f4e9697 00000000 5f4ebd93 00000000  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near r6:
I/DEBUG   (  106):     be840250 5bcc99f0 00000001 be840298 00000004  
I/DEBUG   (  106):     be840260 5bcc98e0 00000002 00000000 5f514505  
I/DEBUG   (  106):     be840270 5ac51778 00000004 be840298 5bcc98e0  
I/DEBUG   (  106):     be840280 00000002 00000001 00000001 5f53b711  
I/DEBUG   (  106):     be840290 00000000 00000000 5ac51778 00000004  
I/DEBUG   (  106):     be8402a0 5ac32ad0 5bcc97c8 be8402c0 00000000  
I/DEBUG   (  106):     be8402b0 00000001 5f53c351 00000000 40a861b0  
I/DEBUG   (  106):     be8402c0 5ac51778 00000004 00000001 00000001  
I/DEBUG   (  106):     be8402d0 00000000 5bcc97c8 00000001 5bcc97c8  
I/DEBUG   (  106):     be8402e0 00000002 5f540ac7 5ac51778 00000004  
I/DEBUG   (  106):     be8402f0 be840308 be840348 5abaf3e0 5f540b7d  
I/DEBUG   (  106):     be840300 00000000 0000001c 5ac51778 00000004  
I/DEBUG   (  106):     be840310 be840374 00000002 4175086c 00000000  
I/DEBUG   (  106):     be840320 be840348 00000001 5abaf3e0 00000002  
I/DEBUG   (  106):     be840330 4175086c 4183a460 be8403d4 5f5437bf  
I/DEBUG   (  106):     be840340 00000000 00000001 5ac51778 00000004  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near r8:
I/DEBUG   (  106):     5ac563e0 00040000 00000400 00040000 00000010  
I/DEBUG   (  106):     5ac563f0 00040000 00001000 0c100000 00000000  
I/DEBUG   (  106):     5ac56400 00060000 05000000 00000000 04000000  
I/DEBUG   (  106):     5ac56410 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac56420 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac56430 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac56440 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac56450 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac56460 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac56470 00000000 00000000 00800000 01000000  
I/DEBUG   (  106):     5ac56480 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac56490 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac564a0 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac564b0 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac564c0 00000000 00000000 00000000 00000000  
I/DEBUG   (  106):     5ac564d0 00000000 00000000 00000000 00000000  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near fp:
I/DEBUG   (  106):     be8403b4 409f62d4 00000002 d0d0001d 41750868  
I/DEBUG   (  106):     be8403c4 00000001 42200308 5e6d0fa6 4220023c  
I/DEBUG   (  106):     be8403d4 40a25455 41750868 5e6d0fa2 5f4d4019  
I/DEBUG   (  106):     be8403e4 4183a460 00000000 00000000 00000018  
I/DEBUG   (  106):     be8403f4 40118228 42200378 42200378 4183a7bc  
I/DEBUG   (  106):     be840404 42200378 00000003 4183a450 00000018  
I/DEBUG   (  106):     be840414 42200378 00000000 40a2ce65 42200378  
I/DEBUG   (  106):     be840424 00000000 40a861b0 00000018 42200378  
I/DEBUG   (  106):     be840434 40a01f38 00000003 4183a450 00000018  
I/DEBUG   (  106):     be840444 4183d950 00000004 00000001 40118228  
I/DEBUG   (  106):     be840454 40a3fcf5 40a861b0 00000018 42200358  
I/DEBUG   (  106):     be840464 40a01f38 00000000 421ed008 0000000c  
I/DEBUG   (  106):     be840474 d8517e17 4183a450 4174a858 4174a858  
I/DEBUG   (  106):     be840484 40a1d203 40a861b0 00337a8b 42200358  
I/DEBUG   (  106):     be840494 40a2cc5b 00000001 00000004 40a861b0  
I/DEBUG   (  106):     be8404a4 40a20c15 4183a450 40a2ceb7 42200358  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory near sp:
I/DEBUG   (  106):     be840230 5bcc99f0 5bcc99f0 00000008 be840270  
I/DEBUG   (  106):     be840240 00000004 5bcc98e0 df0027ad 00000000  
I/DEBUG   (  106):     be840250 5bcc99f0 00000001 be840298 00000004  
I/DEBUG   (  106):     be840260 5bcc98e0 00000002 00000000 5f514505  
I/DEBUG   (  106):     be840270 5ac51778 00000004 be840298 5bcc98e0  
I/DEBUG   (  106):     be840280 00000002 00000001 00000001 5f53b711  
I/DEBUG   (  106):     be840290 00000000 00000000 5ac51778 00000004  
I/DEBUG   (  106):     be8402a0 5ac32ad0 5bcc97c8 be8402c0 00000000  
I/DEBUG   (  106):     be8402b0 00000001 5f53c351 00000000 40a861b0  
I/DEBUG   (  106):     be8402c0 5ac51778 00000004 00000001 00000001  
I/DEBUG   (  106):     be8402d0 00000000 5bcc97c8 00000001 5bcc97c8  
I/DEBUG   (  106):     be8402e0 00000002 5f540ac7 5ac51778 00000004  
I/DEBUG   (  106):     be8402f0 be840308 be840348 5abaf3e0 5f540b7d  
I/DEBUG   (  106):     be840300 00000000 0000001c 5ac51778 00000004  
I/DEBUG   (  106):     be840310 be840374 00000002 4175086c 00000000  
I/DEBUG   (  106):     be840320 be840348 00000001 5abaf3e0 00000002  
I/DEBUG   (  106): 
I/DEBUG   (  106): code around pc:
I/DEBUG   (  106):     5f514430 6963d0c2 f8171e7a 1e417c01 443b1aeb  
I/DEBUG   (  106):     5f514440 3c01f800 1b406960 46034408 d002428b  
I/DEBUG   (  106):     5f514450 ab01f803 6963e7fa 0701f1c3 1bd24417  
I/DEBUG   (  106):     5f514460 d2e4429a b1221a83 46394618 ea30f7b1  
I/DEBUG   (  106):     5f514470 46184603 4540e7db 1e42d09e 5c01f800  
I/DEBUG   (  106):     5f514480 46031850 d0f64293 7b01f803 1c5de7fa  
I/DEBUG   (  106):     5f514490 d9b92d01 0353ea43 0393ea43 1313ea43  
I/DEBUG   (  106):     5f5144a0 e7b11c5d 87f0e8bd 466ab507 93002300  
I/DEBUG   (  106):     5f5144b0 f7ff9301 b003ff71 fb04f85d 4604b5f7  
I/DEBUG   (  106):     5f5144c0 4616460d fb08f7cc 462068e1 31016962  
I/DEBUG   (  106):     5f5144d0 ff64f7cb 1c686963 686168e2 1b524358  
I/DEBUG   (  106):     5f5144e0 1ac7435a 44394408 e9f2f7b1 0003e896  
I/DEBUG   (  106):     5f5144f0 466a68e3 0003e88d 46203301 462960e3  
I/DEBUG   (  106):     5f514500 ff4af7ff bdf0b003 4604b570 f7cc460d  
I/DEBUG   (  106):     5f514510 68e6fae3 429d1e73 6862d20a fb036963  
I/DEBUG   (  106):     5f514520 18c12005 2303fb06 d0011a5a e9d0f7b1  
I/DEBUG   (  106): 
I/DEBUG   (  106): code around lr:
I/DEBUG   (  106):     5f514450 ab01f803 6963e7fa 0701f1c3 1bd24417  
I/DEBUG   (  106):     5f514460 d2e4429a b1221a83 46394618 ea30f7b1  
I/DEBUG   (  106):     5f514470 46184603 4540e7db 1e42d09e 5c01f800  
I/DEBUG   (  106):     5f514480 46031850 d0f64293 7b01f803 1c5de7fa  
I/DEBUG   (  106):     5f514490 d9b92d01 0353ea43 0393ea43 1313ea43  
I/DEBUG   (  106):     5f5144a0 e7b11c5d 87f0e8bd 466ab507 93002300  
I/DEBUG   (  106):     5f5144b0 f7ff9301 b003ff71 fb04f85d 4604b5f7  
I/DEBUG   (  106):     5f5144c0 4616460d fb08f7cc 462068e1 31016962  
I/DEBUG   (  106):     5f5144d0 ff64f7cb 1c686963 686168e2 1b524358  
I/DEBUG   (  106):     5f5144e0 1ac7435a 44394408 e9f2f7b1 0003e896  
I/DEBUG   (  106):     5f5144f0 466a68e3 0003e88d 46203301 462960e3  
I/DEBUG   (  106):     5f514500 ff4af7ff bdf0b003 4604b570 f7cc460d  
I/DEBUG   (  106):     5f514510 68e6fae3 429d1e73 6862d20a fb036963  
I/DEBUG   (  106):     5f514520 18c12005 2303fb06 d0011a5a e9d0f7b1  
I/DEBUG   (  106):     5f514530 686268e3 60e33b01 f8020c19 f8023c01  
I/DEBUG   (  106):     5f514540 0a191c03 1c02f802 e92dbd70 1c5c4ff7  
I/DEBUG   (  106): 
I/DEBUG   (  106): memory map around fault addr 5abdbffe:
I/DEBUG   (  106):     5aba5000-5abdb000 
I/DEBUG   (  106):     5abdb000-5abdc000 
I/DEBUG   (  106):     5abdc000-5acb7000 
I/DEBUG   (  106): !@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 5038

**Comment by emanuelez** [comment] 2015-02-02 20:30
Hello Richard,

it would be interesting to know more about the context of when this is happening. You talked about reinstalling the app. Dis the old and current version share the same data model or did you use migrations to do the transition? The more information you can share the better of course :)

**Comment by bmunkholm** [comment] 2015-02-02 20:54
Hi Richard,
You mention it only occurs on this device. I assume when you uninstall/reinstall that the database is removed? Can you ensure that happens? But before that please copy out the database file. It could be very interesting to copy the file and place it in another device and test that if possible.

We would love to help you with that in case you are able to copy the database and send it to us along with your app if at all possible (privately at help@realm.io). Alternatively we need your help to troubleshoot this remotely.

**Comment by iflatness** [comment] 2015-02-21 00:57
I am also getting this issue on one of my devices, and only when running with an encrypted realm file. The device is a Droid X running android 4.4, so is notable in that the device is considered "low ram".

Hope this info helps.

**Comment by emanuelez** [comment] 2015-02-23 12:53
@iflatness Your error seems more specifically be related with encryption. Would you mind opening a new issue about it? It would be great if you were able to replicate the problem and provide some steps for us to be able to replicate it and fix it.

**Comment by emanuelez** [comment] 2015-02-23 12:54
Closing this since we cannot reproduce and the original poster is not answering.

**Closed by emanuelez** 2015-02-23 12:54 UTC
Labels: support
