### ISSUE TITLE
Crash in Realm due to lack of disk space

### ISSUE THREAD

**Issue by marcus-martins** [realm/realm-java#4667] opened 2017-05-18 18:01 UTC
At times I have been facing my corrupted Realm database. The problem begins to happen when the storage of the device is full (caused by downloading of files), where the first crash accuses lack of space and at the moment that starts the application again already appears the log below.

The doubts are, is a treatment possible to avoid crashes or even prevent the database from being broken down when there is no internal space in the device?

Thank you!

`05-18 16:36:42.114 20347-20347/br.com.application E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: br.com.application, PID: 20347
                                                                              io.realm.exceptions.RealmError: Unrecoverable error. Bad Realm file header (#1) (/data/data/br.com.application/files/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 549
                                                                                  at io.realm.internal.SharedRealm.nativeCompact(Native Method)
                                                                                  at io.realm.internal.SharedRealm.compact(Unknown Source)
                                                                                  at io.realm.BaseRealm.compactRealm(Unknown Source)
                                                                                  at io.realm.Realm.compactRealm(Unknown Source)
                                                                                  at br.com.application.AdaptaApplication.r(Unknown Source)
                                                                                  at br.com.application.AdaptaApplication.onCreate(Unknown Source)
                                                                                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5245)
                                                                                  at android.app.ActivityThread.access$1600(ActivityThread.java:181)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:145)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6134)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

Realm version: 3.1.2 #

**Comment by bmeike** [comment] 2017-05-18 19:56
Closing as a duplicate of #1467

**Comment by Zhuinden** [comment] 2017-05-18 20:09
@bmeike um. What?

**Comment by marcus-martins** [comment] 2017-05-18 20:56
I still do not understand it right, in the log it seems to me that this occurs in "compactRealm". On the database, it is very small, only 500 KB. The issue reported is this?

**Comment by Zhuinden** [comment] 2017-05-18 21:44
I tend to recommend compacting when your activity count goes from 1 to 0.

**Comment by marcus-martins** [comment] 2017-05-18 21:54
OK! But would it be normal for the database to corrupt during compression in this lack of disk space condition?

Thanx

**Comment by Zhuinden** [comment] 2017-05-18 22:42
Only if you have multiple processes doing it at the same time, which **is** possible in `CustomApplication.onCreate()`.

I'd rather move it to above `super.onCreate()` of a `BaseActivity` with a static boolean check to see if you've already tried restoring or not during this app process.

**Comment by marcus-martins** [comment] 2017-05-19 12:15
Right. I had the compactRealm in the onCreate of the Application class, besides it has also got migration when needed, should I also remove this code from the Application class?

I did some more testing and apparently the application only crashes due to lack of disk space. Is there a way for me to filter this exception triggered in Realm so that the crash does not occur and display an alert?

**Comment by bmeike** [comment] 2017-07-28 21:11
Closing this was clearly a mistake.

**Comment by bmeike** [comment] 2017-07-28 21:13
This may be related to https://github.com/realm/realm-java/issues/5011

**Comment by cmelchior** [comment] 2017-08-16 09:01
It appear that there might be an issue here, so I'm folding this issue into #5011

**Closed by cmelchior** 2017-08-16 09:01 UTC
Labels: T:Help

**Comment by cmelchior** [comment] 2017-08-16 09:13
@marcus-martins Can I kindly ask you to post a list of affected devices and android versions in #5011 This information would be really helpful when debugging this.

**Comment by marcus-martins** [comment] 2017-08-16 17:02
@cmelchior I apologize for the delay in answering. At the time the problem occurred because there was more than one open realm instance. I no longer had the problem after reviewing the entire I/O flow of the application.
