### ISSUE TITLE
Realm data deleted when app relaunches

### ISSUE THREAD

**Issue by sandeepkandra** [realm/realm-java#4163] opened 2017-02-09 11:25 UTC
I have an issue in realm. I am using  gradle  version '1.1.0' in android , saved data didn't appear when app relaunched in the device google pixels (Android 7.0 Nougat) after  app killed using task manager, I am not deleting realm and clearing cache.

**Comment by Zhuinden** [comment] 2017-02-09 11:36
Please put the issue inside the issue template, not into the question

also include code sample where you experience your problem

http://stackoverflow.com/questions/39250695/realm-database-is-always-empty-after-restart/39263327#39263327

**Comment by Zhuinden** [comment] 2017-02-09 14:10
Realm clear shouldn't happen unless you either do:

1.) deleteIfMigrationNeeded() and then modify the schema

2.) use inMemory() realm and your process died at some point

3.) call Realm.deleteAll() somewhere in your code

4.) you manually delete the Realm file

-----

Please find which applies to you, this is most likely an error in your code, or just not being aware of what `deleteIfMigrationNeeded()` does.

**Comment by sandeepkandra** [comment] 2017-02-09 14:31
OK will check, thank you

**Comment by bmeike** [comment] 2017-02-09 17:57
@sandeepkandra 
  Would you please fill out the issue template.  It is pretty nearly impossible for us to make any guess about how to fix your issue, when all we have to go on it "it doesn't work!".  We created that template exactly to help you give us enough information so that we can help you.

**Comment by bmeike** [comment] 2017-02-10 22:09
Hey @sandeepkandra !
  Do you have anything else for us?  If there is nothing else with which we can help you, we should close this ticket...

**Closed** 2017-02-11 07:52 UTC
Labels: S:Waiting For User, T:Help

**Comment by willf80** [comment] 2018-01-12 08:51
Hey @bmeike !
I have the same problem. When i commit data and relaunch app, realm delete all schema.
My Configuration 
```java
public class RealmApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);
    }
}
```
**After commit**
![image](https://user-images.githubusercontent.com/5347837/34866536-c65e06f2-f774-11e7-9014-0c25bd800503.png)

**When i restart my application**
![image](https://user-images.githubusercontent.com/5347837/34866801-b83b088a-f775-11e7-93de-ce8e4bd031ae.png)

**Comment by Zhuinden** [comment] 2018-01-12 09:58
https://github.com/realm/realm-java/issues/4163#issuecomment-278651028

This is either 3 or 4.

**Comment by willf80** [comment] 2018-01-12 10:32
It's version 4.3.1

**Comment by kainjinez** [comment] 2018-03-05 05:07
I have the same issue but it rarely happens

**Comment by chrislim** [comment] 2018-03-12 21:07
Just happened to me and I don't have any of the above mentioned lines in my codebase.

**Comment by TheLastClown** [comment] 2018-05-11 13:34
I have the same issue  +1

**Comment by sandeepkandra** [comment] 2018-05-11 14:01
Hi , sorry I forgot what i did, I think I did migration method

**Comment by dajbych** [comment] 2018-08-27 17:53
@Zhuinden It happened two times without changing the schema. I removed `deleteIfMigrationNeeded` to make sure it is not caused by this setting. Then it happened again.
