### ISSUE TITLE
Error:(44, 44) error: Builder(Context) is not public in Builder; cannot be accessed from outside package

### ISSUE THREAD

**Issue by NikhilRPatil** [realm/realm-java#5055] opened 2017-08-01 04:32 UTC
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

 private void addAction() {
        String what = mInputWhat.getText().toString();
        long now = System.currentTimeMillis();
        RealmConfiguration configuration = new RealmConfiguration.Builder(getActivity()).build();
        Realm.setDefaultConfiguration(configuration);
        Realm realm = Realm.getDefaultInstance();
        Drop drop =new Drop(what,now,0,false);
        realm.beginTransaction();
        realm.copyToRealm(drop);
        realm.commitTransaction();
        realm.close();

    }

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
 compile 'io.reactivex:rxjava:1.1.0'
classpath "io.realm:realm-gradle-plugin:3.5.0"

Realm sync feature enabled: yes/no
no

Android Studio version: ?
compileSdkVersion 25
    buildToolsVersion "25.0.3"

Which Android version and device: ?
onePluse 1

**Comment by Zhuinden** [comment] 2017-08-01 06:34
Ya, since Realm 2.0.0 you have to use `Realm.init()` with an application context, and that is re-used across other configuration builders so you don't need to pass context to the builder anymore.

**Comment by zaki50** [comment] 2017-08-01 13:15
About initializing Realm, please see https://realm.io/docs/java/latest/#initializing-realm

**Comment by cmelchior** [comment] 2017-08-16 09:16
The above should answer your question. That method is package protected by design. Closing.

**Closed by cmelchior** 2017-08-16 09:16 UTC
Labels: T:Help
