### ISSUE TITLE
Unrecoverable error. open() failed: Interrupted system call in io_realm_internal_SharedGroup.cpp line 113

### ISSUE THREAD

**Issue by HsiangLeekwok** [realm/realm-java#2376] opened 2016-03-02 02:49 UTC
```Java
io.realm.exceptions.RealmError: Unrecoverable error. open() failed: Interrupted system call in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.(SharedGroup.java:67)
	at io.realm.internal.SharedGroupManager.(SharedGroupManager.java:47)
	at io.realm.BaseRealm.(BaseRealm.java:76)
	at io.realm.Realm.(Realm.java:126)
	at io.realm.Realm.createAndValidate(Realm.java:246)
	at io.realm.Realm.createInstance(Realm.java:231)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
	at io.realm.Realm.getInstance(Realm.java:197)
	at com.test.realm.RealmConfig.getRealm(RealmConfig.java:75)
```

This is the config builder:
```Java
public class RealmConfig {

    private String TAG = "RealmConfig";
    private static RealmConfig instance = null;
    private static final String DFT_NAME = "dftname";
    private String _db_name = "";
    // get path of ex_sd: /sdcard/data/data/package/cache/database
    private String _db_path = Utility.getCachePath(Utility.DB_DIR);
    private RealmConfiguration config;

    public static RealmConfig getInstance() {
        if (null == instance) {
            instance = new RealmConfig();
        }
        instance.checkConfiguration();
        return instance;
    }

    public void checkConfiguration() {
        // different name has different realm instance
        String name = App.getInstance().LoginCode;
        if (TextUtils.isEmpty(name)) {
            name = DFT_NAME;
        }
        name = name + ".realm";
        if (TextUtils.isEmpty(_db_name) || !name.equals(_db_name)) {
            LogHelper.log(TAG, StringHelper.format("old: %s, new: %s, path: %s", _db_name, name, _db_path));
            _db_name = name;
        }
        if (null == config || !config.getPath().equals(_db_path + _db_name)) {
            configRealm();
        }
    }

    private void configRealm() {
        RealmConfiguration.Builder builder = new RealmConfiguration.Builder(new File(_db_path))
                .schemaVersion(2).migration(new Migration()).name(_db_name);
        //if (LxbgApp.getInstance().getResources().getInteger(R.integer.app_database_migration_delete) > 0) {
        //    builder.deleteRealmIfMigrationNeeded();
        //}
        config = builder.build();
    }

    public Realm getRealm() {
        return Realm.getInstance(config);
    }
}
```

And use it in Tasks:
```Java
    @Override
    protected Void doInBackground(Params... params) {
        Realm realm = RealmConfig.getInstance().getRealm();
        // ...... other steps
        return null;
    }
```

Some times works fine, but some times get this exception.
Has any advice? 
@cmelchior or any other hero?    : )

**Comment by beeender** [comment] 2016-03-02 02:53
Does the problem only happen on a specific device? Is the sd-card always inserted? Could it have any problem with the sd-card slot?

**Comment by HsiangLeekwok** [comment] 2016-03-02 03:13
It's looks like happen on many devices: HTC D820u, HUAWEI SC-CL00, Samsung GT-N7100......
Yes, the sd-card was inserted. I cached the memory info like below:

                            Storage: *********************************
                           external: mounted
                              total: 7.28GB
                          available: 5.42GB
                               free: 5.42GB

                           internal: mounted
                              total: 1.45GB
                          available: 298.89MB
                               free: 314.89MB

**Comment by beeender** [comment] 2016-03-02 04:34
1. What would the `db_name` could be? Is there any chance that name contains some special characters?
2. Can you please share the code of `Utility.getCachePath()`?
3. Does it only happen in the async task? Is it the first time for the app to open the Realm?
4. Do you have a chance to reproduce it by yourself? Can you share the apk?

PS. It seems the error message indicates error `EINTR`, http://www.gnu.org/software/libc/manual/html_node/Error-Codes.html Not sure when would it happen and how to handle it. This is the first time we met this issue, maybe it is related with the sd card.

**Comment by HsiangLeekwok** [comment] 2016-03-02 05:23
OK. 
1. The db_name is a character string(only include numbers or characters, like z, jia215, ac7c...)
2. This is the code of getCachePath method:
```Java
    public static String getExternalCacheDir() {
        String path = null;
        try {
            // save files in external storage cache dir default
            if (Environment.getExternalStorageState().equals(Environment.MEDIA_MOUNTED)) {
                path = App.getInstance().getContext().getExternalCacheDir().toString();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (TextUtils.isEmpty(path) || "null".equals(path)) {
            // save files in application cache dir
            path = App.getInstance().getContext().getCacheDir().toString();
        }
        return path;
    }

    public static String getCachePath(String dir) {
        StringBuilder sb = new StringBuilder();
        sb.append(getExternalCacheDir()).append("/").append(dir).append("/");
        String dirs = sb.toString();
        File file = new File(dirs);
        // create dirs
        if (!file.exists())
            file.mkdirs();
        return dirs;
    }
```
 3. This task running in a service to get some data from remote server when service received a network notification(ex. mqtt notification). So if UI was closed by user(or app was auto start by BootComplete) and network notification arrived, this realm instance in this task is the first time to open it.
 4. Sorry, I can not reproduce it by using my phone. My app has a crash handler to catch exceptions and report them to me by email.

**Comment by beeender** [comment] 2016-03-02 05:25
one more thing, what is the max length of the `db_name`? Since the sd-card might be formatted as FAT16/32, so the max allowed file name length could be very short.

**Comment by beeender** [comment] 2016-03-02 05:30
I am wondering this might happen because of the background service process gets killed by the system during opening Realm file.. Did you ever see this exception throws from any other places when the app is in the foreground?

**Comment by HsiangLeekwok** [comment] 2016-03-02 06:39
The length of _db_name is between 1 - 10(one of this exception variable is love507).
Other exception looks like same(**open()** or **fstat()**):
```Java
io.realm.exceptions.RealmError: Unrecoverable error. fstat() failed in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.(SharedGroup.java:67)
	at io.realm.internal.SharedGroupManager.(SharedGroupManager.java:47)
	at io.realm.BaseRealm.(BaseRealm.java:76)
	at io.realm.Realm.(Realm.java:126)
	at io.realm.Realm.createAndValidate(Realm.java:246)
	at io.realm.Realm.createInstance(Realm.java:231)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
	at io.realm.Realm.getInstance(Realm.java:197)
```

no other places throw this exception.
Maybe it throws when app just startup,
Or throws in background(when task first execution or several times(task execute success) after)

**Comment by beeender** [comment] 2016-03-02 07:04
@HsiangLeekwok Can you please share your apk with us? I want to do some testing with it. You can send it to help@realm.io if you want to share it privately.

**Comment by HsiangLeekwok** [comment] 2016-03-04 08:51
a new exception @beeender @cmelchior :
```Java
io.realm.exceptions.RealmError: Unrecoverable error. unlink() failed: Interrupted system call in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.(SharedGroup.java:67)
	at io.realm.internal.SharedGroupManager.(SharedGroupManager.java:47)
	at io.realm.BaseRealm.(BaseRealm.java:76)
	at io.realm.Realm.(Realm.java:126)
	at io.realm.Realm.createAndValidate(Realm.java:246)
	at io.realm.Realm.createInstance(Realm.java:231)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
	at io.realm.Realm.getInstance(Realm.java:197)
```

**Comment by beeender** [comment] 2016-03-04 10:11
@HsiangLeekwok Does it still crash in the background service? Can you share the apk?

**Comment by beeender** [comment] 2016-03-04 10:16
Got the apk, checking now.

**Comment by beeender** [comment] 2016-03-10 04:53
Got some trace on https://secure.helpscout.net/conversation/177896528/3272/?folderId=539748 .
Still no clue how to reproduce this. From the trace, it seems `EINTR` happens during open. And the Realm db exist on the SD card. Maybe it is caused by a slow SD card?

**Comment by beeender** [comment] 2016-03-10 09:40
Just created some stress testing to see if I can reproduce this:

A background thread keeps writing data to SD card,
Another thread keeps opening/closing the Realm on SD card.

Till now, no luck. Still need more information about this.

**Comment by beeender** [comment] 2016-03-18 08:40
We doubt this crash is caused by crappy SD-card. @HsiangLeekwok has changed the realm location to internal storage. Waiting for the feedback now.

**Comment by beeender** [comment] 2016-03-29 11:55
Checked with @HsiangLeekwok , after move Realm file to internal storage, the error hasn't been reported till now. Close this issue for now, please reopen it if the error still exists.

**Closed by beeender** 2016-03-29 11:55 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help

**Comment by beeender** [comment] 2016-06-01 17:43
I suddenly met this crash in the log with @HsiangLeekwok 's old version app once (db on the sd card)

I was not playing with the app at all. The app is installed and i haven't ran it for months. It just have this kind silent exception in the background. It does seem like the system did something wrong for IO of SD card (maybe?) in the background process.

```
shell@android:/sdcard $ df . -h
Filesystem             Size   Used   Free   Blksize
.                     1.48G   993M   522M   4096
```

[2376.log.zip](https://github.com/realm/realm-java/files/294005/2376.log.zip)

**Comment by HsiangLeekwok** [comment] 2016-06-02 02:23
Good!
Thank you!
