### ISSUE TITLE
Realm on change listener called erratically

### ISSUE THREAD

**Issue by teddywilson** [realm/realm-java#3114] opened 2016-07-02 20:16 UTC
#### Goal

> I want my realm on changed listener to fire every time the objects are updated.

#### Expected Results

> The realm on changed listener fires when the objects are updated.

#### Actual Results

>  The behavior seems erratic. Sometimes the listener works, other times it doesn't work at all.

#### Steps & Code to Reproduce

> I tried following the documentation on realm.io very meticulously, though the problem seems to persist. Since realm handles so much, it's hard for me to know what's really going on-- everything seems pretty straightforward.

#### Code Sample

When my activity is created I call the following method to instantiate a database query and apply and on changed listener.

```java
       private void initializeDatabaseQueries(){

        // Retrieve the default realm instance to make database queries to populate the realm recycler view.
        Realm realm = Realm.getDefaultInstance();

       // All of the expenses in the current roof.
        RealmResults<Expense> expenses = realm.where(Expense.class)
                .equalTo(QueryKey.roof_guid, Application.getInstance().retrieveCurrentRoofRealmObject().guid)
                .equalTo(QueryKey.erased, false)
                .findAll();

        expenses.addChangeListener(expensesListener);
    }

    private RealmChangeListener expensesListener = new RealmChangeListener<RealmResults<Expense>>() {
        @Override
        public void onChange(RealmResults<Expense> expenses) {
            Log.v("EXPENSES", "ON CHANGE");

            // If there are 2 or more expenses, this means the sample should be deleted if it's still being saved.
            if (expenses.size() > 1) {
                final RealmResults<Expense> sample = expenses
                        .where()
                        .equalTo(QueryKey.sample, true)
                        .findAll();

                // Delete the sample expense if it's found.
                Realm realm = Realm.getDefaultInstance();
                realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        sample.deleteAllFromRealm();
                    }
                });

            }

            // If there are no expenses, a sample should be created.
            else if(expenses.size() == 0){
                createSampleExpenseObject();
            }
        }
    };
```

In my logs "EXPENSES ON CHANGE" only seems to be getting called SOMETIMES after syncrhonizing data in the background from our server. 

This is my expense object. The updateOrCreateWhileSyncingWithJSON occurs in the doInBackground method of an async task.

```java
public class Expense extends RealmObject {

    @PrimaryKey
    public String guid;
    public int lastModified;
    public Roof roof;
    public User payer;
    public String description;
    public int amount;
    public RealmList<Splitter> splitters;
    public boolean erased;
    public boolean sample;

    public static void updateOrCreateWhileSyncingWithJSON(JSONObject jsonExpense, Realm realm){
        try{
            int lastModified = jsonExpense.getInt(JSONKey.lastModified);
            Application.getInstance().updateMostRecentModificationDate(lastModified);

            String guid = jsonExpense.getString(JSONKey.guid);
            String roofGUID = jsonExpense.getString(JSONKey.roof);
            String payer = jsonExpense.getString(JSONKey.payer);
            String description = jsonExpense.getString(JSONKey.description);
            int amount = jsonExpense.getInt(JSONKey.amount);
            JSONArray splitters = jsonExpense.getJSONArray(JSONKey.splitters);
            boolean erased = jsonExpense.getBoolean(JSONKey.erased);

            updateOrCreateWhileSyncingWithGUID(
                    guid,
                    lastModified,
                    roofGUID,
                    payer,
                    description,
                    amount,
                    splitters,
                    erased,
                    realm
            );

        } catch (JSONException e){
            e.printStackTrace();
        }
    }

    private static void updateOrCreateWhileSyncingWithGUID(
            final String guid,
            final int lastModified,
            final String roofGUID,
            final String payerGUID,
            final String description,
            final int amount,
            final JSONArray splitters,
            final boolean erased,
            Realm realm
    ){
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Expense expense = realm
                                    .where(Expense.class)
                                    .equalTo(QueryKey.guid, guid)
                                    .findFirst();

                if(expense == null){
                    expense = new Expense();
                }
                expense.guid = guid;
                expense.lastModified = lastModified;
                expense.description = description;
                expense.amount = amount;
                expense.erased = erased;
                expense.sample = false;

                Roof roof = realm.where(Roof.class).equalTo(QueryKey.guid, roofGUID).findFirst();
                if(roof == null){
                    roof = new Roof();
                    roof.guid = roofGUID;
                }
                expense.roof = roof;
                expense.splitters = new RealmList<Splitter>();

                realm.copyToRealmOrUpdate(expense);
                realm.copyToRealmOrUpdate(roof);

                User payer = realm.where(User.class).equalTo(JSONKey.guid, payerGUID).findFirst();
                if(payer == null){
                    payer = new User();
                    payer.guid = payerGUID;
                }
                expense.payer = payer;
                try {
                    for (int i = 0; i < splitters.length(); i++) {
                        JSONObject splitterJSONObject = splitters.getJSONObject(i);
                        String splitterGUID = splitterJSONObject.getString(JSONKey.guid);
                        int percentage = splitterJSONObject.getInt(JSONKey.percentage);
                        expense.splitters.add(Splitter.createWithExpense(splitterGUID, percentage, realm));
                    }
                } catch (JSONException e){
                    e.printStackTrace();
                }
                realm.copyToRealmOrUpdate(expense);
                ExpenseWrapperObject.createWithExpenseAndRoof(expense, roof, lastModified, realm);
            }
        });
    }
}
```

This is the method that actually calls updateOrCreateWhileSyncing -- also wrapped in an async task.

```java
void beginLocalSync(
            JSONObject documentsToSync
    ){
        // Set the documents which need to be synced from the server.

        Realm realm = null;
        try {
            // Retrieve realm instance.
            realm = Realm.getDefaultInstance();

            // Retrieve all JSON user model objects to save.
            JSONArray users = documentsToSync.getJSONArray(JSONKey.users);

            // Retrieve all JSON roof model objects to save.
            JSONArray roofs = documentsToSync.getJSONArray(JSONKey.roofs);

            // Retrieve all JSON expense model objects to save.
            JSONArray expenses = documentsToSync.getJSONArray(JSONKey.expenses);

            // Save all User json objects in the users json array.
            for(int i = 0; i < users.length(); i++){
                User.updateOrCreateWhileSyncingWithJSON(users.getJSONObject(i), realm);
            }

            // Save all Roof json objects in the roofs json array.
            for(int i = 0; i < roofs.length(); i++){
                Roof.updateOrCreateWhileSyncingWithJSON(roofs.getJSONObject(i), realm);
            }

            // Save all Expense json objects in the expenses json array.
            for(int i = 0; i < expenses.length(); i++){
                Expense.updateOrCreateWhileSyncingWithJSON(expenses.getJSONObject(i), realm);
            }
          
        } catch (JSONException e) {
            e.printStackTrace();
        } finally {
            if(realm!=null){
                realm.close();
            }
            syncListener.onSyncComplete();
        }
    }
```

If there's anything else I can provide, please let me know. This isn't the only problem i've had with the on changed listeners, and I would really like to know what I'm doing wrong.

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 1.0.1

Android Studio version: 2.2

Which Android version and device: Galaxy S4

**Comment by Zhuinden** [comment] 2016-07-02 20:36
I have a wild guess that this is probably a result of executing synchronous write transaction on the UI thread inside a Realm change listener.

**Comment by beeender** [comment] 2016-07-04 02:20
What do you mean by "erratically"? The change listener are NOT guaranteed to be called every time when the transaction committed, instead, it is guaranteed to be called after the lated transaction committed. For example, new obejects `Object1` and `Object2` have been created in two separated transactions one after another. Listener MAY NOT be called twice here, but Listener will surely be called after the second transaction called at which time `Object1` and `Object2` have been both created already.

**Comment by beeender** [comment] 2016-07-11 07:34
@teddywilson Hope the issue is cleared, I am closing this issue now. Feel free to reopen it if needed. Thanks!

**Closed by beeender** 2016-07-11 07:34 UTC
Labels: S:Waiting For User, T:Help
