### ISSUE TITLE
Fatal signal during Realm.getDefaultInstance()

### ISSUE THREAD

**Issue by mariniu** [realm/realm-java#5761] opened 2018-02-21 17:33 UTC
#### Expected Results

Get a valid Realm instance.

#### Actual Results

Fatal signal 6 (SIGABRT) every time the app is launched (on below device).

```
Fatal signal 6 (SIGABRT), code -6 in tid 11878 (in.nowr)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Lenovo/K10a40/K10a40:6.0/MRA58K/K10a40_S230_170517_ROW_WE:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 11878, tid: 11878, name: in.nowr  >>> in.nowr <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
r0 00000000  r1 00002e66  r2 00000006  r3 b6f4ae2c
r4 b6f4ae34  r5 b6f4ade4  r6 00000011  r7 0000010c
r8 00000182  r9 9f99ffdd  sl acd35008  fp 00000001
ip 00000006  sp beb10788  lr b6cadd7d  pc b6caf294  cpsr 400f0010

backtrace:
    #00 pc 00042294  /system/lib/libc.so (tgkill+12)
    #01 pc 00040d79  /system/lib/libc.so (pthread_kill+32)
    #02 pc 0001c7eb  /system/lib/libc.so (raise+10)
    #03 pc 0001999d  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 00017550  /system/lib/libc.so (abort+4)
    #05 pc 0012f62b  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #06 pc 0012f657  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #07 pc 0012f6af  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #08 pc 000f5ae1  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #09 pc 000f394d  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #10 pc 000f3b35  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #11 pc 000f4c65  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #12 pc 000827cb  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #13 pc 000762b1  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #14 pc 00078489  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #15 pc 00085323  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #16 pc 000760eb  /data/app/in.nowr-2/lib/arm/librealm-jni.so
    #17 pc 00030513  /data/app/in.nowr-2/lib/arm/librealm-jni.so (Java_io_realm_internal_SharedRealm_nativeGetSharedRealm+42)
    #18 pc 01c33729  /data/app/in.nowr-2/oat/arm/base.odex (offset 0x1003000)

Tombstone written to: /data/tombstones/tombstone_08
```

#### Steps & Code to Reproduce

The issue occurs for release build (from Play Store) every time the app is launched and sometimes also for debug one builded via Android Studio.

#### Code Sample

```java

    // Realm Initialization in Application class
    private void initializeRealm(final int schemaVersion) {
        Realm.init(Application.this);
        RealmConfiguration realmConfiguration;
        realmConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(schemaVersion)
                .migration(new Migration())
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }

    // Snippet which causes crash when call Realm.getDefaultInstance()
        [...]
    //check if Fabric is initialized
    if (Fabric.isInitialized()){
        try{
            //get a Realm instance, if exist Realm is initialized. If not catch the exception below
            Realm realm = Realm.getDefaultInstance();
            if (realm != null){
                //close Realm instance
                realm.close();
            }
            //start the FirstActivity
            Intent intent = new Intent(SplashActivity.this, FirstActivity.class);
            if (getIntent().getExtras() != null){
                intent.putExtras(getIntent().getExtras());
            }
            startActivity(intent);
            finish();
            overridePendingTransition(0, 0);
        }catch (IllegalStateException e){
            //Fabric is already initialized, log the exception to Crashlytics, and kill the Nowr process
            Crashlytics.logException(e);
            Process.killProcess(Process.myPid());
            System.exit(0);
        }
    }

```

#### Version of Realm and tooling
Realm version(s): 3.7.2

Which Android version and device: Android 6.0 - Lenovo K10a40 (K10a40_S230_170517_ROW_WE)

**Comment by Zhuinden** [comment] 2018-02-21 18:28
Is there any chance that you can upgrade to newer Realm?

The realm-core was updated a *lot* in the versions between 3.7.2 and 4.0.0 (and subsequently 4.3.4)

**Comment by cmelchior** [comment] 2018-02-22 13:18
Does the error only happen on that specific device or also on others? It sounds like you can reproduce this. Can you try upgrading to latest version (4.3.4) and see if that makes a difference?

**Comment by mariniu** [comment] 2018-02-22 14:11
We updated Realm to 4.3.3 but it doesn't resolve the issue.

Actually the error happens every time we try to retrieve Realm instance on a Lenovo K10a40 with Android 6.0. Following the log from console:

```
/home/jenkins/workspace/realm_realm-core_PR-2976-3RARHZ2SQIQNEZVWMWI66X6AMCHCV3HJJFRQ7LTSM4AQYK4NVZXQ/src/realm/group_writer.cpp:393: [realm-core-5.1.2] Assertion failed: ref + size <= after_ref with (ref, size, after_ref, ndx, m_free_positions.size()) =  [0, 8, 0, 0, 4]
IMPORTANT: if you see this error, please send this log to help@realm.io.
Fatal signal 6 (SIGABRT), code -6 in tid 20263 (in.nowr)
$===AEE===AEE===AEE===$
p 0 poll events 1 revents 0
not know revents:0
p 1 poll events 1 revents 0
not know revents:0
p 2 poll events 1 revents 1
aed_main_fork_worker: generator 0xb6c46090, worker 0xbeb6e8c8, recv_fd 0
handle_request(0)
check process 20263 name:in.nowr
tid 20263 abort msg address is:0x00000000, si_code is:0 (request from -6:20263)
aee handle:-1, cpu cores:4, online:4
p 3 poll events 1 revents 0
BOOM: pid=20263 uid=10107 gid=10107 tid=20263
not know revents:0
p 4 poll events 1 revents 0
not know revents:0
p 5 poll events 0 revents 0
not know revents:0
[OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 20263, tid: 20263, name: in.nowr  >>> in.nowr <<<

Build fingerprint: 'Lenovo/K10a40/K10a40:6.0/MRA58K/K10a40_S230_170517_ROW_WE:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 20263, tid: 20263, name: in.nowr  >>> in.nowr <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    r0 00000000  r1 00004f27  r2 00000006  r3 b6fe3e2c
    r4 b6fe3e34  r5 b6fe3de4  r6 00000011  r7 0000010c
    r8 00000189  r9 9fb225e5  sl a8cea008  fp 00000001
    ip 00000006  sp befc0768  lr b6d46d7d  pc b6d48294  cpsr 400f0010

backtrace:
    #00 pc 00042294  /system/lib/libc.so (tgkill+12)
        #01 pc 00040d79  /system/lib/libc.so (pthread_kill+32)
        #02 pc 0001c7eb  /system/lib/libc.so (raise+10)
        #03 pc 0001999d  /system/lib/libc.so (__libc_android_abort+34)
        #04 pc 00017550  /system/lib/libc.so (abort+4)
        #05 pc 0013ec5f  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #06 pc 0013ec8b  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #07 pc 0013ed51  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #08 pc 000fd40d  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #09 pc 000facc9  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #10 pc 000faeb7  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #11 pc 000fc389  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #12 pc 0008dd57  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #13 pc 0008034d  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #14 pc 00082583  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #15 pc 00090891  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #16 pc 000801ff  /data/app/in.nowr-2/lib/arm/librealm-jni.so
        #17 pc 00036a53  /data/app/in.nowr-2/lib/arm/librealm-jni.so (Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm+42)
        #18 pc 019f76e9  /data/app/in.nowr-2/oat/arm/base.odex (offset 0x1011000)
```

**Comment by regularRichi** [comment] 2018-03-07 17:24
Any update on this?

**Comment by cmelchior** [comment] 2018-06-15 17:14
Duplicate of #5300. Folding into that one.

**Closed by cmelchior** 2018-06-15 17:14 UTC
Labels: O:User, T:Help
