### ISSUE TITLE
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 1879048192 offset: 0 in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92

### ISSUE THREAD

**Issue by imidhuntv** [realm/realm-java#3761] opened 2016-11-09 09:06 UTC
This issue is probably the same as [#3264](https://github.com/realm/realm-java/issues/3264) and [#3064](https://github.com/realm/realm-java/issues/3064).
We have a device with release version of our app which crashes on each open because of this issue. So if you guys want any additional details we can provide.
Detailed crash log is posted below.
We are using realm 2.1.1.

Crashlytics - plaintext stacktrace downloaded by Midhun Vijayakumar at Wed, 09 Nov 2016 08:54:21 GMT
Organization: Talkoot
Platform: android
Application: Talkoot
Version: 0.51 (4000036)
Bundle Identifier: com.talkoot.android
Issue #: 294
Date: 2016-11-09T08:34:52Z
OS Version: 5.1.1
Device: MotoG3
RAM Free: 37.9%
Disk Free: 7.3%

#0. Crashed: main: 0 0 0x0000000000000000
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
       at io.realm.Realm.compactRealm(Realm.java:1564)
       at com.talkoot.android.App.initRealm(App.java:4221)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4638)
       at android.app.ActivityThread.access$1500(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

--

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 1879048192 offset: 0 in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
       at io.realm.Realm.compactRealm(Realm.java:1564)
       at com.talkoot.android.App.initRealm(App.java:4221)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4638)
       at android.app.ActivityThread.access$1500(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

#0. Crashed: main: 0 0 0x0000000000000000
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
       at io.realm.Realm.compactRealm(Realm.java:1564)
       at com.talkoot.android.App.initRealm(App.java:4221)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4638)
       at android.app.ActivityThread.access$1500(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

#1. HeapTrimmerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:311)
       at java.lang.Thread.run(Thread.java:818)

#2. main
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:496)
       at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4211)
       at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:249)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

#3. Answers Events Handler1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1060)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)

#4. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:400)
       at java.util.concurrent.FutureTask.get(FutureTask.java:162)
       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:47)
       at com.crashlytics.android.core.CrashlyticsCore.markInitializationStarted(CrashlyticsCore.java:8807)
       at com.crashlytics.android.core.CrashlyticsCore.doInBackground(CrashlyticsCore.java:60)
       at io.fabric.sdk.android.InitializationTask.doInBackground$532ebdd5(InitializationTask.java:1063)
       at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#5. ReferenceQueueDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:134)
       at java.lang.Thread.run(Thread.java:818)

#6. FinalizerWatchdogDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:240)
       at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:212)
       at java.lang.Thread.run(Thread.java:818)

#7. Crashlytics Exception Handler1
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:580)
       at java.lang.Thread.getAllStackTraces(Thread.java:522)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent$13f1f7ff(CrashlyticsUncaughtExceptionHandler.java:1024)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:23766)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:1238)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
       at java.lang.Thread.run(Thread.java:818)

#8. pool-4-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#9. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:1197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:4065)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#10. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:1197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:4065)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#11. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:1197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:4065)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#12. Measurement Worker
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:422)
       at com.google.android.gms.measurement.internal.zzw$zzd.run(Unknown Source)

#13. FinalizerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:422)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
       at java.lang.Thread.run(Thread.java:818)

#14. GCDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$GCDaemon.run(Daemons.java:344)
       at java.lang.Thread.run(Thread.java:818)

#15. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor(Thread.java:1220)
       at sun.misc.Unsafe.park(Unsafe.java:299)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:510)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.performOperation(DependencyPriorityBlockingQueue.java:1197)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(DependencyPriorityBlockingQueue.java:4065)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Zhuinden** [comment] 2016-11-09 10:22
I have this wild guess that you have Realm instances on background threads that you don't close.

**Comment by imidhuntv** [comment] 2016-11-09 12:54
I had heard this theory. So I have spawned 1000 threads each opened realm and doing some write operations and but not closing the realm instance. And I continued to use the app also. But I couldn't repro this.

**Comment by leisim** [comment] 2016-11-09 12:59
Check the size of the Realm files on the devices where your app crashes. It may be quite big and needs to be compacted ;)

**Comment by imidhuntv** [comment] 2016-11-09 13:30
I think it was big. Device was not able to calculate it. But why is it happening and how can I repro this? and What is the best solution for this?

**Comment by leisim** [comment] 2016-11-09 13:52
I have the same problem since a long time but I can not reproduce or fix it :'(

**Comment by imidhuntv** [comment] 2016-11-09 14:03
` private void initRealm() {
        Realm.init(this);
        realmConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(13)
                .migration(talkootMigration)
                .name("db")
                .build();
        inMemoryConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(1)
                .deleteRealmIfMigrationNeeded()
                .name("inMemory")
                .inMemory()
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
        try {
            Realm.compactRealm(realmConfiguration);
        } catch (RealmError e) {
            AnalyticsImpl.reportExceptionGeneral(new TalkootException("CompactRealm", e.getMessage(), null));
            Toast.makeText(_instance, R.string.realm_failure,
                    Toast.LENGTH_SHORT).show();
            Realm.deleteRealm(realmConfiguration);
            Prefs prefs = new PrefsImpl();
            prefs.setStockListUpdatedAt(0);
            PortfolioUtils.createPortfoliosIfRequired(prefs);
        }
    }`

**Comment by imidhuntv** [comment] 2016-11-09 18:20
```
 private void initRealm() {
        Realm.init(this);
        realmConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(13)
                .migration(talkootMigration)
                .name("db")
                .build();
        inMemoryConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(1)
                .deleteRealmIfMigrationNeeded()
                .name("inMemory")
                .inMemory()
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
        try {
            Realm.compactRealm(realmConfiguration);
        } catch (RealmError e) {
            AnalyticsImpl.reportExceptionGeneral(new TalkootException("CompactRealm", e.getMessage(), null));
            Toast.makeText(_instance, R.string.realm_failure,
                    Toast.LENGTH_SHORT).show();
            Realm.deleteRealm(realmConfiguration);
            Prefs prefs = new PrefsImpl();
            prefs.setStockListUpdatedAt(0);
            PortfolioUtils.createPortfoliosIfRequired(prefs);
        }
    }

```

This is what I'm doing now. This way after deleting the database I can help users recover the app. But I want to prevent this from happening.

**Comment by kneth** [comment] 2016-11-10 09:20
From your stack trace, it looks like you are compacting a very large Realm file. And the crash is when opening such a large file. 

@finnschiermer Do you know of any limitation of file size?

**Comment by imidhuntv** [comment] 2016-11-12 08:36
But how can a realm file grow so big in size suddenly? Can you give me an example like if I miss doing something this would happen?

**Comment by Zhuinden** [comment] 2016-11-12 08:39
@imidhuntv unclosed Realm instances on non-auto-updating (non-looper) background threads. Also, writing to the database with **many** transactions, like one transaction / object in a list of 1000+.

**Comment by imidhuntv** [comment] 2016-11-12 10:07
@Zhuinden I tried to create a bigger realm file using the first theory. I couldn't do it.  And what does your second theory mean? How should I write an arraylist of size 1000 to realm?

**Comment by cmelchior** [comment] 2016-11-14 09:53
Hi @imidhuntv You can read more about best practise for handling Realm life cycles here: https://realm.io/docs/java/latest/#closing-realm-instances and here: https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

If you follow these advice, you shouldn't see the file size explode like this. One question though: Are you saving binary blobs of data in Realm?

**Comment by Zhuinden** [comment] 2016-11-14 10:00
@imidhuntv  this is the right way of saving large lists: http://stackoverflow.com/a/39385985/2413303

**Comment by imidhuntv** [comment] 2016-11-14 15:01
@cmelchior No. I'm not saving large Binary Objects in Realm. 
@Zhuinden I'm already doing write operations the same way.

**Comment by cmelchior** [comment] 2016-11-18 15:39
@imidhuntv In that case there is probably not much we can do without some way of reproducing it.

**Comment by imidhuntv** [comment] 2016-11-18 18:48
@cmelchior We had an open realm instance in a non looper background thread. Hope That was the issue. You can close this for the time being. I'll come back if there are occurrences of the same again. Thank you.

**Closed** 2016-11-19 10:29 UTC
Labels: T:Help

**Comment by eduxavier** [comment] 2019-07-19 22:54
> @cmelchior We had an open realm instance in a non looper background thread. Hope That was the issue. You can close this for the time being. I'll come back if there are occurrences of the same again. Thank you.

please, tell me, it actually work or did you change to another database supplier?

**Comment by prasad-dot-ws** [comment] 2021-02-18 11:56
I'm shipping my app with 2 million records in it. And the ream file is 603MB. And I get the exception `Unrecoverable error. mmap() failed: Out of memory size: 603979776` at that time the free RAM was 505.14 MB. So does that means realm copies the entire ream DB to RAM when operating?
