### ISSUE TITLE
Permission denied in io_realm_internal_SharedGroup.cpp line 113

### ISSUE THREAD

**Issue by boybeak** [realm/realm-java#3166] opened 2016-07-10 11:10 UTC
```java
io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in io_realm_internal_SharedGroup.cpp line 113
at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
at io.realm.BaseRealm.<init>(BaseRealm.java:81)
at io.realm.Realm.<init>(Realm.java:140)
at io.realm.Realm.createAndValidate(Realm.java:240)
at io.realm.Realm.createInstance(Realm.java:220)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
at io.realm.Realm.getInstance(Realm.java:184)
at com.metis.base.manager.RealmManager.init(RealmManager.java:40)
at com.metis.base.manager.RealmManager.<init>(RealmManager.java:31)
at com.metis.base.manager.RealmManager.getInstance(RealmManager.java:21)
```
This happened when instance a Realm class.
```java
RealmConfiguration.Builder builder = new RealmConfiguration.Builder(getContext(),
                    CacheManager.getInstance(getContext()).getMyDataCacheDir());
            mRealm = Realm.getInstance(builder.build());
```
And the path I passed in is:/storage/emulated/0/Android/data/com.metis.meishuquan/cache/100058/data.

**Comment by Zhuinden** [comment] 2016-07-10 13:33
Is this on first install? Does it happen only on some devices? Are you sure the issue isn't insufficient privileges (marshmallow permission maybe?) 

A possibility is that you don't have the privilege in application, only in activity. Happens on some devices.

**Comment by boybeak** [comment] 2016-07-10 16:09
@Zhuinden This happened Nexus 5,android 6.0.1.And the folder is under my app's cache dir.No need for Storage Permission.

**Comment by Zhuinden** [comment] 2016-07-10 16:24
I see! The last question is, are you initiating your first realm in application onCreate?

**Comment by boybeak** [comment] 2016-07-11 02:03
@Zhuinden Not in application onCreate, but the getContext() method returns an Application Context.Does it matter?I also tried to use an activity,but also crashed.

**Comment by stk1m1** [comment] 2016-07-11 03:55
@boybeak 

Could you somehow specify what version of Realm you are using? Thanks!

**Comment by boybeak** [comment] 2016-07-11 04:03
@stk1m1 
Version 1.1.0.I tried like below:
```java
File file = new File(getExternalCacheDir(), "123456" + File.separator + "data");
        if (!file.exists()) {
            file.mkdirs();
        }
        RealmConfiguration.Builder builder = new RealmConfiguration.Builder(this, file);
        Realm.setDefaultConfiguration(builder.build());
        Realm realm = Realm.getDefaultInstance();
```
This crash also happened.But if the file value is getExternalCacheDir(),it works.So the problem because of the file?

**Comment by boybeak** [comment] 2016-07-11 04:39
@stk1m1 Just work fine once using getExternalCacheDir().I tried several times later,and not work.

**Comment by zaki50** [comment] 2016-07-11 08:38
@boybeak I confirmed this issue and found the root cause.

Realm creates named pipe file, but Android's security system(SELinux) prohibits to create it on external storage.
Current work-around is use internal storage for Realm files.

To solve this issue, we need to fix Realm core.

**Comment by zaki50** [comment] 2016-07-11 08:40
memo:

To set SELinux to permissive mode, execute following commands to rooted device.
```
$ adb root
adbd is already running as root
$ adb shell setenforce 0
```

**Comment by zaki50** [comment] 2016-07-11 08:46
I'll close this issue as a duplicate of #3140 
Please check that issue for further progress.

**Comment by zaki50** [comment] 2016-07-11 08:47
@boybeak thank you for reporting this!

**Closed by zaki50** 2016-07-11 08:46 UTC
Labels: Blocked On Core, T:Duplicate

**Comment by boybeak** [comment] 2016-07-11 09:10
@zaki50 Thanks bro.I try it in internal storage.
