### ISSUE TITLE
Unrecoverable error. Wrong transactional state 

### ISSUE THREAD

**Issue by atouchsimo** [realm/realm-java#2462] opened 2016-03-15 10:26 UTC
### i have the following  error apears some times in the log,
```
Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in io_realm_internal_SharedGroup.cpp line 157
```
#### Version of Realm and tooling
Realm version(s): ?
0.88

**Comment by cmelchior** [comment] 2016-03-15 10:36
Hi @atouchsimo Do you have more of the stack trace? The error message is most likely happening because you are either trying to write to a Realm outside a transaction.

**Comment by jcj52436999** [comment] 2016-03-15 10:39
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (124/100 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:43835 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmOB-001yCZ-Cr
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:39:47 -0400
Date: Tue, 15 Mar 2016 03:36:43 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458038203;
	bh=AliGKN/N28/l8eHcAervu5t8YA4Dy59dXfWB90Mg5NI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=VjlX2jWyQlnIThSwBRTLjzQk9Kp64/5WjjhTgFVg/oT5n3aX+4sdmItrtLmcEY9Wp
	 NQ3WU1hivEiVRsL7hRPa0DQGEqSB24oKtBNeAukVMv4GSSoQH/b3LhsufVPlN5Sjou
	 kOgsIC9q62FP41/pXsJq8D5GbbEmdhsrZIBk4rMc=

**Comment by atouchsimo** [comment] 2016-03-15 10:44
### the full stack trace
```
io.realm.exceptions.RealmError: Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in io_realm_internal_SharedGroup.cpp line 157
                   at io.realm.internal.SharedGroup.nativeAdvanceRead(Native Method)
                   at io.realm.internal.SharedGroup.advanceRead(SharedGroup.java:82)
                   at io.realm.internal.ImplicitTransaction.advanceRead(ImplicitTransaction.java:33)
                   at io.realm.internal.SharedGroupManager.advanceRead(SharedGroupManager.java:75)
                   at io.realm.HandlerController.realmChanged(HandlerController.java:339)
                   at io.realm.HandlerController.handleMessage(HandlerController.java:100)
                   at android.os.Handler.dispatchMessage(Handler.java:98)
                   at android.os.Looper.loop(Looper.java:135)
                   at android.app.ActivityThread.main(ActivityThread.java:5343)
                   at java.lang.reflect.Method.invoke(Native Method)
                   at java.lang.reflect.Method.invoke(Method.java:372)
                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by beeender** [comment] 2016-03-15 10:48
Did you forget to call `commitTransaction()` or `cancelTransaction()` after `beginTransaction()`?

**Comment by atouchsimo** [comment] 2016-03-15 11:11
in the activity where the error occurred i use ```executeTransactionAsync```

**Comment by beeender** [comment] 2016-03-15 11:22
What about other places (other activities/services/etc..) ? Realm instance is shared in the same thread.

**Comment by atouchsimo** [comment] 2016-03-15 11:36
### here's a snippet from the code
```java
usersApiHelper.getProfile(userId)
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(this::saveUser, Utils::log);
``` 

```java
private void saveUser(User currentUser) {
        realm.executeTransactionAsync(realm1 -> realm1.copyToRealmOrUpdate(currentUser1),
               () -> currentUser = realm.where(User.class)
                .equalTo("_id", userId)
               .findFirst(), Utils::log);
}
```

**Comment by beeender** [comment] 2016-03-15 14:01
Is it reproducible? Can you share you project or make a sample project which can reproduce this to help@realm.io ?

**Comment by atouchsimo** [comment] 2016-03-15 15:29
unfortunately no it's not i couldn't reproduce it,
the error occurs  only from time to time :/

**Comment by cmelchior** [comment] 2016-03-15 15:33
Did you only see this in `0.88` or also in previous versions?

**Comment by atouchsimo** [comment] 2016-03-15 15:45
The error started occurring from ```0.87.5```

**Comment by beeender** [comment] 2016-03-16 08:02
@atouchsimo 
In you code:

```
private void saveUser(User currentUser) {
        realm.executeTransactionAsync(realm1 -> realm1.copyToRealmOrUpdate(currentUser1),
               () -> currentUser = realm.where(User.class)
                .equalTo("_id", userId)
               .findFirst(), Utils::log);
}
```

How did you get the `currentUser1`? Is it a standalone object? or it belongs to a Realm instance which is created in UI thread?

**Comment by atouchsimo** [comment] 2016-03-16 09:30
@beeender sorry i misspelled  it should be ```currentUser``` that passed to the function,

**Comment by beeender** [comment] 2016-03-16 09:49
@atouchsimo Then the param `currentUser` is a standalone Object or not?

**Comment by emanuelez** [comment] 2016-03-24 19:04
@atouchsimo any news on this? If you solved the issue just close the issue, otherwise you can continue the conversation with @beeender

**Closed** 2016-03-29 11:34 UTC
Labels: S:Waiting For User, T:Help

**Comment by bupojung** [comment] 2017-06-15 18:26
have the same problems:

2017-06-16 02:25:29.883 FileMail[4079:5087972] [Bugly]  Trapped uncaught exception 'RLMException', reason: 'Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)' 
(
	0   CoreFoundation                      0x0000000112966b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011233c141 objc_exception_throw + 48
	2   Realm                               0x000000010fb6ab88 -[RLMRealm beginWriteTransaction] + 136
	3   RealmSwift                          0x0000000110446e6d _TFC10RealmSwift5Realm10beginWritefT_T_ + 45
	4   RealmSwift                          0x0000000110446d50 _TFC10RealmSwift5Realm5writefzFzT_T_T_ + 48
	5   FileMail                            0x000000010c0e2965 _TFC8FileMail17PersistentManager5writefFT_T_T_ + 165
	6   FileMail                            0x000000010c15075a _TZFC8FileMail9UserModelP33_A4CC45FB07B7C5F06A4E54BD31BADB507addUserfT4userS0__T_ + 330
	7   FileMail                            0x000000010c1505fe _TZFC8FileMail9UserModel9addFriendfS0_T_ + 46
	8   FileMail                            0x000000010c07983f _TZFC8FileMail12OutMailModel7addMailfS0_T_ + 175
	9   FileMail                            0x000000010c079da1 _TZFC8FileMail12OutMailModel8addMailsfGSaS0__T_ + 241
	10  FileMail                            0x000000010c0379eb _TFFFC8FileMail24MainTabbarViewController8sendFileFT_T_U0_FT_T_U_FGSaCS_12OutMailModel_T_ + 59
	11  FileMail                            0x000000010c0ab6e7 _TFZFC8FileMail19SendEmailRoutingNav21showAlbumFileSelectorFT12onControllerCSo16UIViewController11sendSuccessFGSaCS_12OutMailModel_T_5closeFS1_T__S0_U_FGSaS2__T_ + 151
	12  FileMail                            0x000000010c0960dd _TFFC8FileMail22SendMailViewControllerP33_87DE2D28678ADD1F7BF70F9076F6E5354sendFT_T_U_FTGSqGVs10DictionarySSP___GSqCSo7NSError__T_ + 6205
	13  FileMail                            0x000000010c01230c _TFC8FileMail17SendMailViewModel10ApiManagerfTC10XLSwiftKit14BaseApiManager20finishWithOriginDataP__T_ + 14044
	14  FileMail                            0x000000010c012c28 _TToFC8FileMail17SendMailViewModel10ApiManagerfTC10XLSwiftKit14BaseApiManager20finishWithOriginDataP__T_ + 88
	15  FileMail                            0x000000010c012cf9 _TTDFC8FileMail17SendMailViewModel10ApiManagerfTC10XLSwiftKit14BaseApiManager20finishWithOriginDataP__T_ + 105
	16  FileMail                            0x000000010c012c79 _TTWC8FileMail17SendMailViewModel10XLSwiftKit19ApiCallbackProtocolS_FS2_10ApiManagerfTCS1_14BaseApiManager20finishWithOriginDataP__T_ + 57
	17  XLSwiftKit                          0x0000000112111a9f _TFFC10XLSwiftKit14BaseApiManagerP33_788209EB54CD7C3D5F6D80B3BF14D43112successRouteFT_T_U_FT_T_ + 319
	18  XLSwiftKit                          0x0000000112111187 _TTRXFo___XFdCb___ + 39
	19  libdispatch.dylib                   0x00000001139f04a6 _dispatch_call_block_and_release + 12
	20  libdispatch.dylib                   0x0000000113a1905c _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x00000001139fa40b _dispatch_main_queue_callback_4CF + 411
	22  CoreFoundation                      0x000000011292b909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	23  CoreFoundation                      0x00000001128f1ae4 __CFRunLoopRun + 2164
	24  CoreFoundation                      0x00000001128f1016 CFRunLoopRunSpecific + 406
	25  GraphicsServices                    0x0000000115019a24 GSEventRunModal + 62
	26  UIKit                               0x000000011086f0d4 UIApplicationMain + 159
	27  FileMail                            0x000000010bfde567 main + 55
	28  libdyld.dylib                       0x0000000113a6565d start + 1
	29  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by ppamorim** [comment] 2017-10-20 15:27
Happening to me on 3.5.0. Any idea?

**Comment by beeender** [comment] 2017-10-23 02:57
@ppamorim create a new issue with the full stack trace please :)
