### ISSUE TITLE
[0.87.0] Realm should detect latest version

### ISSUE THREAD

**Issue by fernandodev** [realm/realm-java#1966] opened 2015-12-18 13:43 UTC
It's not a major bug, but ...

I'm using Realm 0.87.0 and every each compilation I got this message: (since 0.86.1)
Note: Version 0.86.0 of Realm is now available: http://static.realm.io/downloads/java/latest

**Comment by emanuelez** [comment] 2015-12-18 14:14
Thank you for pointing that out. It is now fixed.

**Comment by MGaetan89** [comment] 2016-01-23 20:23
I have the same error with version 0.87.2 saying that version 0.87.0 is available.

**Comment by cmelchior** [comment] 2016-01-23 20:50
Thanks for reporting this. We will look into it.

**Comment by cmelchior** [comment] 2016-01-26 12:07
I could reproduce this with  `0.87.3` as well:

```
dependencies {
    compile 'io.realm:realm-android:0.87.3'
}

Version 0.87.0 of Realm is now available: http://static.realm.io/downloads/java/latest
```

**Comment by MGaetan89** [comment] 2016-01-26 20:09
Is it really necessary to have this feature included in Realm?

**Comment by cmelchior** [comment] 2016-01-28 17:43
This should now be fixed, also we released 0.87.4
@MGaetan89 You can see the reasoning for including it here: https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmAnalytics.java

**Closed by cmelchior** 2016-01-28 17:43 UTC
Labels: bug, P2

**Comment by MGaetan89** [comment] 2016-01-28 18:44
Thanks for the information.
