### ISSUE TITLE
Upgrade to Realm Core 13.8.0

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#7790] opened 2023-03-21 13:52 UTC
Current Core is 13.3.0, we should upgrade to 13.8.0 before release.

**Comment by clementetb** [comment] 2023-03-31 09:28
Maybe will fix https://github.com/realm/realm-java/issues/7775

**Comment by sipersso** [comment] 2023-04-03 06:44
@clementetb I noticed that the Realm Kotlin lib is on 13.5.0 (Java is on 13.3.0). Do you know if these changes are included in 13.5.0? I was heavily affected by the compaction issues on Android, but have done migration work now and will switch over to the Kotlin Lib. Is there a chance I will get the same issues on Realm Kotlin 13.5.0?

**Comment by sipersso** [comment] 2023-04-13 14:06
@clementetb is there any way to validate that this change will fix the corruption issues? Updating to the java version from 10.12.0 to 10.14.0 will be very risky if I can't know for sure that this fixes the issue since the file format has changed and it won't be possible to revert the update. See more here https://github.com/realm/realm-java/issues/7779

**Comment by clementetb** [comment] 2023-04-13 14:14
Unfortunately, we have no way to validate that it fixes the issue because we have no reproduction steps.

**Comment by sipersso** [comment] 2023-04-13 14:20
This makes me extremely worried. I can't risk that my users get corrupted data, even if it is a low percentage. I guess I will have to wait and see if others complain or not :/ Isn't it possible to see what changes were made between 10.12.0 and 10.13.0 to try to identify what could have caused the corruptions?

**Comment by sipersso** [comment] 2023-04-14 12:11
I guess this should be closed as #7779  is resolved. However I am still blocked by #7775. It is very risky to update Realm without knowing that #7775 is resolved since the file format has changed and it won't be possible to revert the upgrade.

**Closed as completed** 2023-05-02 13:33 UTC
