### ISSUE TITLE
RealmFileException: Not a Realm file.

### ISSUE THREAD

**Issue by MikeKasperlik** [realm/realm-java#5432] opened 2017-10-17 07:48 UTC
#### Goal

Using realm.

#### Expected Results

No crash.

#### Actual Results

We see some very strange crash on some of our users devices (reported through fabric).
We had this crash since ages (minimum since realm 3.1.3), but since we use 3.5.0 upwards the frequency increased drastically.

Closing the app and relaunching does not help - the database is corrupt forever.

We understand this is quite hard to debug with actual way to reproduce. We do not know how to handle a error like this. Deleting the database is a very frustrating experience for our users as they have to sign in again, sync their data, pair with our accessory again ....

How to further track this down or maybe even recover from this?

```
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/our.app.package/files/db.v3.realm': Not a Realm file. (Not a Realm file) (/data/data/our.app.package/files/db.v3.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 91
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.<init>(SharedRealm.java:180)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:217)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:317)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
       at io.realm.Realm.getInstance(Realm.java:346)
       at our.app.package.sync.SyncAdapter.onPerformSync(SyncAdapter.java:131)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

#### Steps & Code to Reproduce

We do not know how to reproduce this, as this happens to only a small amount of users. Not yet happened during development.

What's a bit curious about this is that this seems to happen way more on huawai devices than on others:

![screen shot 2017-10-17 at 09 41 04](https://user-images.githubusercontent.com/1431474/31652475-8b8b0082-b31f-11e7-9964-691af4586fc5.png)
![screen shot 2017-10-17 at 09 41 17](https://user-images.githubusercontent.com/1431474/31652476-8ba6f814-b31f-11e7-99b9-dbf0ad4cc18b.png)

We actually have way more samsung users (todays user stats):
![screen shot 2017-10-17 at 09 43 07](https://user-images.githubusercontent.com/1431474/31652559-cce65bf8-b31f-11e7-833f-a3990465e1bf.png)

#### Code Sample

```java
public class PcSyncAdapter extends AbstractThreadedSyncAdapter {
 static RealmConfiguration REALM_CONFIG = new RealmConfiguration.Builder()
        .name("db.v3.realm")
        .compactOnLaunch()
        .modules(new Module())
        .schemaVersion(4)
        .migration(new Migration())
        .initialData(new InitialTransaction())
        .encryptionKey(SecurityUtils.getPersistent64BitKey())
        .build();
        
  @Override
  public void onPerformSync(Account account, Bundle extras, String authority,
                            ContentProviderClient provider, SyncResult syncResult) {
    Realm.init(getContext());
    Realm realm = Realm.getInstance(REALM_CONFIG); // Crash 
  }
}

@RealmModule(classes = {User.class})
public class Module { }
```

#### Version of Realm and tooling
Realm version(s): 3.1.3 - 3.7.2

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Multiple - see above.

**Comment by cmelchior** [comment] 2017-10-17 08:02
I see you are using `compactOnLaunch`. We found a bug that accidentally could corrupt the file is this functionality was used on a device that ran out of disk space: https://github.com/realm/realm-java/issues/5011

Can you see from your crash logs if that is a plausible cause?

**Comment by MikeKasperlik** [comment] 2017-10-20 06:33
I looked into a few crashes and all of these devices have at least 20% free disk space (most times more then 50%). So I fear this is not the cause. 

We will upgrade to realm 4.0 in our next release and report back if this changes anything.

**Comment by beeender** [comment] 2017-12-05 05:01
@MikeKasperlik Hope the new release fixed the crash. I am closing this issue now. Feel free to reopen it if the issue is still there.

**Closed by beeender** 2017-12-05 05:01 UTC
Labels: T:Help
