### ISSUE TITLE
Incorrect thread IllegalStateException while async altering RealmObject previously received using async method

### ISSUE THREAD

**Issue by mkoslacz** [realm/realm-java#2767] opened 2016-05-10 11:43 UTC
Hi,

I have encountered somehow confusing Realm behaviour. I can alter asynchronously fetched RealmObjects using sync methods, but when I try to do it using Realm async transaction, an IllegalStateException is thrown because of access from incorrect thread. Now I use workaround consisting of usage of copyToRealmOrUpdate method on Realm detached objects. It's presented on code sample below.

#### Goal

I want to asynchronically alter RealmObject previously received from db using asynchronous method.

#### Expected Results

I would like to see this process completes flawlessly ;)

#### Actual Results

An IllegalStateException is thrown. Message claims "Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created." Interesting thing is that I can access exactly the same object using sync methods, as it's presented in the code below.

#### Steps & Code to Reproduce

The simplest scenario to reproduce this issue is to asynchronously query for a RealmObject using any of findAsync() methods and try to alter it using executeTransactionAsync() in onChange callback method.

#### Code Sample

```java
        final Program asyncFetchedProgram = realmInstance.where(Program.class).findFirstAsync();
        asyncFetchedProgram.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange(Object element) {

                asyncFetchedProgram.getId(); // ok

                realmInstance.beginTransaction();
                asyncFetchedProgram.setRecommended(true);  // ok
                realmInstance.commitTransaction();

                final Program detachedProgram = realmInstance.copyFromRealm(asyncFetchedProgram);
                detachedProgram.setRecommended(true);
                realmInstance.executeTransactionAsync(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        realmInstance.copyToRealmOrUpdate(detachedProgram); // ok
                    }
                });

                realmInstance.executeTransactionAsync(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        asyncFetchedProgram.setRecommended(true); // fails: Realm access from incorrect thread. 
                    }
                });

            }
        });
```

#### Version of Realm and tooling

Realm version(s): 0.90.0

Android Studio version: 2.1 stable

Which Android version and device: any - last run performed on Nexus 5X emulator using api 23.

**Comment by beeender** [comment] 2016-05-10 11:46
in `executeTransactionAsync`, the `Transaction.execute()` runs in a different thread which is different from where the `asyncFetchedProgram` created. You need to query it again in `execute`.

This is not quite convenient, #2187 was created for this issue. For now, you need to query it in the asyc transaction thread.

**Comment by mkoslacz** [comment] 2016-05-10 11:56
Ok, thanks a lot, I’ll use your approach while looking forward to further improvements ;)

**Comment by beeender** [comment] 2016-05-10 12:05
I am closing this issue now.  Feel free to re-open it if necessary.
Thanks a lot for the feedback!

**Closed by beeender** 2016-05-10 12:05 UTC
Labels: S:Waiting For User, T:Help

**Comment by mkoslacz** [comment] 2016-05-10 13:01
One more thing - actually, querying for an object in `execute` method is problematic in most cases. If you have object that you want to alter, you have to extract ie. ID from it to redo a query, and this also throws an Exception: 

```java
        final Program asyncFetchedProgram = realmInstance.where(Program.class).findFirstAsync();
        asyncFetchedProgram.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange(Object element) {
                realmInstance.executeTransactionAsync(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        Program queriedAgainProgram = realmInstance.where(Program.class).equalTo(Program.C_ID_INT, asyncFetchedProgram.getId()).findFirst(); // fails: Realm access from incorrect thread.
                        asyncFetchedProgram.setRecommended(true); 
                    }
                });
            }
        });
``` 

I'll stick to my workaround using `copyFromRealm`.

**Comment by beeender** [comment] 2016-05-10 13:55
```
Program asyncFetchedProgram = realmInstance.where(Program.class).findFirstAsync();
final int id = asyncFetchedProgram.getId();
asyncFetchedProgram.addChangeListener(new RealmChangeListener() {
    @Override
    public void onChange(Object element) {
        realmInstance.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Program queriedAgainProgram = realmInstance.where(Program.class).equalTo(Program.C_ID_INT, id).findFirst(); // fails: Realm access from incorrect thread.
                asyncFetchedProgram.setRecommended(true); 
            }
        });
    }
});
```
The problem is `asyncFetchedProgram`belongs to the caller thread, `asyncFetchedProgram.getId();` cannot be accessed from the async transaction thread as well.

**Comment by mkoslacz** [comment] 2016-05-11 06:11
Yep, obviously, this approach also solves the problem.
