### ISSUE TITLE
Incompatible lock file. Info size doesn't match, 1112 1120.

### ISSUE THREAD

**Issue by vytautasgimbutas** [realm/realm-java#2928] opened 2016-06-02 09:42 UTC
The issue https://github.com/realm/realm-java/issues/2459 was closed, even though this problem still persists on 1.0.0 realm version.

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Incompatible lock file. Info size doesn't match, 1112 1120. in io_realm_internal_SharedGroup.cpp line 113
at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
at io.realm.internal.SharedGroup.(SharedGroup.java:64)
at io.realm.internal.SharedGroupManager.(SharedGroupManager.java:49)
at io.realm.BaseRealm.(BaseRealm.java:79)
at io.realm.Realm.(Realm.java:138)
at io.realm.Realm.createAndValidate(Realm.java:248)
at io.realm.Realm.createInstance(Realm.java:228)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
at io.realm.Realm.getInstance(Realm.java:192)

**Comment by beeender** [comment] 2016-06-02 09:47
@vytautasgimbutas Is there any chance you are using Realm in multi processes? like have some services with `android:process=":remote"`

**Comment by beeender** [comment] 2016-06-02 09:50
BTW, any more information you can give us? Like
1. what kind of devices, AOSP version, best if you can share a crashlytic link with us.
2. related call stack to your app? Is it ever the first time your app opening a Realm instance?
3. Is it possible to have some logcat log which is close the crash?

**Comment by vytautasgimbutas** [comment] 2016-06-02 12:18
@beeender regarding multi processes - no
1. http://crashes.to/s/f6a73a3aabd
2. yes, this happens on the first access to Realm
3. i'll try to reproduce this on 4.4.4 here in our office. I'll let you know about the results.

Thanks for looking so quickly into the issue. :)

**Comment by beeender** [comment] 2016-06-02 12:42
@vytautasgimbutas Some hint for reproducing. It might be because of the lock file update, we updated the lock file in realm-java 0.88.0. So you could install an old app which is using realm under version 0.88.0 , play with it then update the app at some random point. - I couldn't reproduce it till now :(

**Comment by beeender** [comment] 2016-06-03 08:29
@vytautasgimbutas I will dup and close this one to #2459 . If you have any updates, please comment on that issue. Thanks!!!

**Closed by beeender** 2016-06-03 08:29 UTC
Labels: Reproduction Required, S:P1 Backlog, T:Bug-Crash
