### ISSUE TITLE
Failure when computing UTF-16 size error_code = 1

### ISSUE THREAD

**Issue by tristangrichard** [realm/realm-java#4987] opened 2017-07-19 06:14 UTC
Running:

* Realm 3.5.0
* Android 5.0.2

No Encryption
All communication with Realm is performed with AsyncTasks.

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by io.realm.exceptions.RealmError: Unrecoverable error. Failure when computing UTF-16 size error_code = 5; retcode = 6; StringData.size = 2442; StringData.data =  in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 151
       at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:167)
       at io.realm.KeyValueObjectRealmProxy.realmGet$value(KeyValueObjectRealmProxy.java:116)
       at com.app.Cache.KeyValueObject.getValue(KeyValueObject.java:26)
       at com.app.Account.Account.loadArray(Account.java:192)
```

**Comment by cmelchior** [comment] 2017-07-19 08:09
Hi @trr-amsiq Is it something you can reproduce? Or what kind of phones are you seeing this on?

**Comment by trr-amsiq** [comment] 2017-07-19 08:12
No not yet.
Here some more data [http://crashes.to/s/44e3c052321](http://crashes.to/s/44e3c052321)

**Comment by cmelchior** [comment] 2017-07-19 09:39
Hi @trr-amsiq 

Thanks. It seems to affect 2 users repeatedly, which suggests that their data is indeed faulty somehow and isn't caused by a bug when reading the data. This was e.g. the case for similar errors we saw using encryption where we had a race condition that caused wrong data to be read from disk.

If the underlying data is indeed corrupted, it begs the question on how that happened. It could be a bug in Realm, the OS or disk corruption happening after the data was written.

I don't want to be pessimistic, but without any further to go on, we will probably not be able to solve this as historically it is a huge time sink to investigate these kinds of issues, and the chance of actually finding anything is extremely low unless we can reproduce the error.

I'll keep this issue open though as we definitely want to be able to track if others are seeing similar things.

Just to preserve history:
* Error happened to two users repeatedly
* SM-J110F (Android 4.4.4) 
* SM-G530H (Android 5.0.2)

**Comment by trr-amsiq** [comment] 2017-07-19 11:09
Hi @cmelchior 
I will get back to you if I am able to reproduce it myself.
Cheers

**Comment by bmeike** [comment] 2017-07-24 23:15
Adding Help and Waiting for User tags to assist tracking

**Comment by bmeike** [comment] 2017-07-24 23:16
Hey @trr-amsiq,
  Any progress/new info to share on this?

**Comment by bmeike** [comment] 2017-07-27 22:31
@trr-amsiq,
We have been unable to reproduce this.  I'm going to close the issue.  By all means, if you encounter it again, please open a new issue and we will jump on it.

Cheers!
  -blake

**Comment by trr-amsiq** [comment] 2017-08-07 11:54
@bmeike 
Sorry for the late response. I've been in vacation.
Yes it is still occurring

**Comment by vladimirfx** [comment] 2018-05-18 09:28
I have same issue:
Fatal Exception: io.realm.exceptions.RealmError
Unrecoverable error. Failure when computing UTF-16 size error_code = 1; retcode = 24; StringData.size = 104; StringData.data = ОТДЕЛОМ ЁAAAf in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 161

Massive 80+ crashes per day. I can't invent some workaround... Please help me.

**Comment by nhachicha** [comment] 2018-05-18 10:56
@vladimirfx ay chance you can reproduce this (maybe using the data in production?)

**Comment by vladimirfx** [comment] 2018-05-21 09:44
Sadly, I don't have DB file for reproducing this issues. Prod data contains personal information and not extractable from device. Attempts to reproduce in QA env are all failed. But we keep trying to get corrupted DB in QA.
Clearing app data or reinstalling is "fixes" the issue... at cost of customer data.
Application itself is single process. Realm configuration looks like this:
```
return new RealmConfiguration.Builder()
                .name(realmName)
                .schemaVersion(Constants.DB_VERSION)
                .directory(dbDir)
                .migration(MIGRATION)
                .encryptionKey(key)
                .initialData(initTx)
                .build();
```

May be you have some workaround or something similar?

**Comment by vladimirfx** [comment] 2018-06-13 08:14
> 650 crashes in last 90 days:
http://crashes.to/s/228b8d4c09c

Issue so critical for us that we consider database migration. May be reopen this issue? Any advice?

**Comment by bmunkholm** [comment] 2018-06-13 11:59
Adding the crash log from above crash:
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Failure when computing UTF-16 size error_code = 1; retcode = 12; StringData.size = 55; StringData.data = ЗАО ЁAAAf in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 161
       at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:157)
       at io.realm.ru_fcb_mobilefieldcollection_debt_DebtorRealmProxy.realmGet$organization(ru_fcb_mobilefieldcollection_debt_DebtorRealmProxy.java:411)
       at ru.fcb.mobilefieldcollection.debt.Debtor.hashCode(Debtor.java:219)
       at java.util.Collections.secondaryHash(Collections.java:3427)
       at java.util.HashMap.get(HashMap.java:300)
       at io.realm.ru_fcb_mobilefieldcollection_debt_DebtRealmProxy.update(ru_fcb_mobilefieldcollection_debt_DebtRealmProxy.java:3009)
       at io.realm.ru_fcb_mobilefieldcollection_debt_DebtRealmProxy.copyOrUpdate(ru_fcb_mobilefieldcollection_debt_DebtRealmProxy.java:2027)
       at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:431)
       at io.realm.Realm.copyOrUpdate(Realm.java:1608)
       at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1025)
       at ru.fcb.mobilefieldcollection.debt.RealmDebtsRepo.lambda$saveDebt$41(RealmDebtsRepo.java:541)
       at ru.fcb.mobilefieldcollection.debt.-$$Lambda$RealmDebtsRepo$qRiIiq5iyNozRDFgEb5XTehd64c.apply(lambda)
       at ru.fcb.mobilefieldcollection.realm.Block-CC.lambda$toFunction$0(Block.java:15)
       at ru.fcb.mobilefieldcollection.realm.-$$Lambda$Block$rxUy2qhKx6FrOVMDHmXqTRfzwqk.apply(lambda)
       at ru.fcb.mobilefieldcollection.realm.RealmTemplate.executeInRealm(RealmTemplate.java:90)
       at ru.fcb.mobilefieldcollection.realm.RealmTemplate.executeInRealm(RealmTemplate.java:80)
       at ru.fcb.mobilefieldcollection.debt.RealmDebtsRepo.saveDebt(RealmDebtsRepo.java:540)
       at ru.fcb.mobilefieldcollection.debt.DebtDataReceiver.processDebt(DebtDataReceiver.java:138)
       at ru.fcb.mobilefieldcollection.debt.DebtDataReceiver.process(DebtDataReceiver.java:61)
       at ru.fcb.mobilefieldcollection.server.MfcServerConnection$WebSocketListener.lambda$onMessage$2(MfcServerConnection.java:251)
       at ru.fcb.mobilefieldcollection.server.-$$Lambda$MfcServerConnection$WebSocketListener$9h2sSXgOqPaj6sBRQIA76EP9FIk.call(lambda)
       at ru.fcb.mobilefieldcollection.realm.RealmUnitOfWork.lambda$doWork$1(RealmUnitOfWork.java:43)
       at ru.fcb.mobilefieldcollection.realm.-$$Lambda$RealmUnitOfWork$GFV_q7dLAawcDKekC9SreLyZVCc.get(lambda)
       at ru.fcb.mobilefieldcollection.realm.RealmUnitOfWork.doWork(RealmUnitOfWork.java:61)
       at ru.fcb.mobilefieldcollection.realm.RealmUnitOfWork.doWork(RealmUnitOfWork.java:41)
       at ru.fcb.mobilefieldcollection.server.MfcServerConnection$WebSocketListener.onMessage(MfcServerConnection.java:248)
       at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by vladimirfx** [comment] 2018-06-18 12:58
@bmunkholm Yes, sure, we can use special version.

**Comment by tfatrifork** [comment] 2018-09-17 14:06
Get same crash with realm version 5.4.0. 
Hope this can help identifty the issue. We do not use encryption.
`
Caused by io.realm.exceptions.RealmError: Unrecoverable error. Failure when computing UTF-16 size error_code = 1; retcode = 3; StringData.size = 54; StringData.data = --X͎¢ /p
h젩n /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 161
       at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:157)
`

**Comment by 09ae9c** [comment] 2019-07-04 05:52
any progress? I got the same program with realm 5.8.0

**Comment by 09ae9c** [comment] 2019-07-04 05:52
any progress? I got the same crash with realm 5.8.0

**Comment by erikhuizinga** [comment] 2020-04-15 15:28
I have this same (or similar) issue on Realm 6.1.0. I use an encrypted Realm db.

One user reported the app crashing, but after cleaning app data, the issue is solved. This supports the hypothesis that the Realm file(s) are somehow corrupted.

All the 15 crash logs of this single user show the following pattern:

```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Failure when computing UTF-16 size error_code = $1; retcode = $2; StringData.size = $3; StringData.data = $4 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 161
```

In the above crash line, I've put numbered variables, which have the follwing values:

- `$1`: all have value `1`, except one has value `5`.
- `$2`: varies for some crashes, I'm not sure if there's a pattern.
- `$3`: in the range `600`–`617`.
- `$4`: all values start with a URL (`https://`...somethingsomething) but end with `AAAA`. One ends with `AAAAF`. That's possibly where some decoding breaks, maybe? One doesn't end with `AAAA` or `AAAAF`, but the URL suddenly stops halfway and I see a bunch of user-written text directly appended to the URL (this is the one with `$1` = `5`). This looks like either a middle part of the string is missing, or some other string field got appended suddenly.

This particular user uses:
- Realm 6.1.0
- Android 9
- Samsung Galaxy J5 with over 500 MB free RAM and over 4 GB free disk space

**Comment by bmunkholm** [comment] 2021-11-16 10:01
Closing as outdated. If anyone sees this again, please open a new issue. Thanks!

**Closed by bmunkholm** 2021-11-16 10:01 UTC
Labels: T-Bug-Crash, Reproduction-Required, O-Community, Pipeline-On-Hold
