### ISSUE TITLE
Realm file is currently open in another process which cannot share access with this process

### ISSUE THREAD

**Issue by mirceasotan** [realm/realm-java#7102] opened 2020-09-15 13:20 UTC
Hello Realm Team,

I have been struggling to fix an issue described by the stack trace below. I am using realm io.realm:realm-gradle-plugin:6.1.0

Can you provide more information on what might be the cause of it? We are opening realms from both main thread and looper threads for live queries.

Err: io.realm.exceptions.RealmFileException: Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. (Incompatible lock file. Shared info version doesn't match, 771 10.) (/data/data/org.vom8x8.sipua/files/VOM_DB) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: INCOMPATIBLE_LOCK_FILE.
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
at io.realm.BaseRealm.<init>(BaseRealm.java:136)
at io.realm.BaseRealm.<init>(BaseRealm.java:103)
at io.realm.Realm.<init>(Realm.java:163)
at io.realm.Realm.createInstance(Realm.java:499)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:360)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
at io.realm.Realm.getInstance(Realm.java:428)
at com.vom8x8.vom.model.dao.DatabaseService.configRealm(DatabaseService.kt:40)
at com.vom8x8.vom.callLog.CallLogDatabaseService.getMinCallLogTimestamp(CallLogDatabaseService.java:187)
at com.vom8x8.vom.callLog.FetchOldCallLogsRunnable.getEndTime(FetchOldCallLogsRunnable.java:61)
at com.vom8x8.vom.callLog.FetchOldCallLogsRunnable.fetchFullCallHistory(FetchOldCallLogsRunnable.java:86)
at com.vom8x8.vom.callLog.FetchOldCallLogsRunnable.run(FetchOldCallLogsRunnable.java:48)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
<img width="412" alt="Screenshot 2020-09-15 at 16 19 33" src="https://user-images.githubusercontent.com/17314290/93215604-49cfb100-f76f-11ea-9316-42de8ec12d93.png">
<img width="404" alt="Screenshot 2020-09-15 at 16 19 38" src="https://user-images.githubusercontent.com/17314290/93215607-4b00de00-f76f-11ea-8ddc-51624d7accb3.png">

**Comment by cmelchior** [comment] 2020-09-23 11:22
Hi @mirceasotan Sorry for the late reply. An Incompatile lock file in this context means that you are trying to access a Realm file using different architectures, like e.g. 32-bit and 64-bit.

Obviously, that should be impossible if everything runs on a single device, so it is a bit perplexing you run into this.

One problem could be if you are somehow shipping the app with an existing Realm file and by accident also copy our lock files. In that case you could run into something like this.

There are multiple of these files which are named `<filename>.lock` and a folder named `<filename>.management`.

**Comment by edualonso** [comment] 2020-10-05 10:57
Hello @mirceasotan. After reviewing this case, the most likely explanation is that the user has the "backup app data" setting enabled. This will back up all Realm-related files and these will be restored on new phones. If, for example, the source phone is a 32-bit phone and the user restores a backup on a 64-bit phone, the lock files will not match the architecture and this problem could manifest itself. Applications can keep certain files and directories from being backed up (see https://developer.android.com/guide/topics/data/autobackup#IncludingFiles). In this case, ignoring the `.management` directoy and `.lock` file could fix the issue.

**Comment by edualonso** [comment] 2020-10-06 10:22
This crash could also be caused by third-party backup applications that share app data across devices, as mentioned in https://github.com/realm/realm-java/issues/7144#issuecomment-704174133. Please let us know whether or not you can pinpoint which is the cause for the crash. Having a use that allows us to reproduce this issue would be of great help.

**Comment by rorbech** [comment] 2020-10-26 16:50
@mirceasotan Any luck reproducing or identifying the root cause of this?

**Comment by mirceasotan** [comment] 2020-10-26 17:04
> @mirceasotan Any luck reproducing or identifying the root cause of this?

@rorbech No, I was not able to reproduce this locally. In the end, we decided to drop realm and use something else.

**Comment by mirceasotan** [comment] 2020-10-26 17:15
> @mirceasotan Any luck reproducing or identifying the root cause of this?

<img width="634" alt="Screenshot 2020-10-26 at 19 11 16" src="https://user-images.githubusercontent.com/17314290/97204803-3af10b00-17bf-11eb-8fda-226ad8203ff4.png">
 We have aprox 100+ occurrences per day.

We do not have encryption enabled. We do have backup enabled, but the scenario above of a user restoring data between 32 and 64 bit devices seems unlikely, given this crash rate. We use realm opened on looper threads. Not sure if it helps.

**Comment by bmunkholm** [comment] 2021-11-16 10:21
Without further information on how to debug this, it's hard to get further. So I'll close this for now. If anyone else experiences a similar issue please open a new issue and refer to this as well. Thanks!

**Closed by bmunkholm** 2021-11-16 10:21 UTC
Labels: T-Bug-Crash, Reproduction-Required, O-Community
