### ISSUE TITLE
Core library load failing with "...jni.so" is too small to be an ELF executable

### ISSUE THREAD

**Issue by NirpE** [realm/realm-java#1049] opened 2015-04-18 04:59 UTC
Got couple crashes reported with following trace:

<code>
dlopen failed: "/data/app-lib/xxx-3/librealm-jni.so" is too small to be an ELF executable

    java.lang.Runtime.loadLibrary (Runtime.java:365)
    java.lang.System.loadLibrary (System.java:526)
    io.realm.internal.RealmCore.loadLibrary (RealmCore.java:144)
    io.realm.internal.SharedGroup. (SharedGroup.java:34)
    io.realm.Realm. (Realm.java:204)
    io.realm.Realm.createAndValidate (Realm.java:513)
    io.realm.Realm.create (Realm.java:486)
    io.realm.Realm.getInstance (Realm.java:404)
</code>

Devices are Samsung S3 and Samsung GT I9305, both running Android 4.4.4

I have no idea how to reproduce, but could you share some thoughts if you might know why this could happen?

**Comment by bmunkholm** [comment] 2015-04-20 11:46
Havn't heard about this before. Would be awesome if we could reproduce it.

**Comment by cmelchior** [comment] 2015-04-20 11:48
Hi @NirpE 
That sounds really odd. A initial idea would be that this is a result of a bug when installing/upgrading the APK resulting in the .so files being truncated to 0 bytes. This is apparently possible, see this: http://forums.livecode.com/viewtopic.php?f=53&t=21320, but it will require further debugging

A few follow up questions:
- How often do you see this bug?
- Does it only happen one those two devices?
- Does it only happen with that version of Android?

**Comment by NirpE** [comment] 2015-04-20 12:07
For now I have seen this with 2 users, 6 crashes. Only with these two devices running 4.4.4. Our previous version of application didn't have Realm in it.

**Comment by cmelchior** [comment] 2015-04-20 12:08
If you are able to talk the users, it would be interesting to know if removing the app and installing it again helps?

**Comment by NirpE** [comment] 2015-04-20 12:12
I will have to check about that, will keep you posted if I get new information.

**Comment by NirpE** [comment] 2015-04-21 04:39
The customer removed the application and tried to install it back from Google Play but the device said insufficient memory. According to him, there should be 7,2GB left, but I think thats for external storage and the internal storage is very low.

**Comment by NirpE** [comment] 2015-04-21 05:01
But still in that case the application update should have failed on the first place if the memory was low. Hard to figure out the actual reason for this error.

**Comment by bmunkholm** [comment] 2015-04-21 06:34
But his free memory could be less now for other reasons.
Could be interesting experimenting with the installation of the app on a device with almost enough memory. Maybe it can download the APK, but installing it fails by not being able to decompress the files, thus resulting in a lib files size 0? Just guessing.

**Comment by cmelchior** [comment] 2015-04-21 12:05
Hi @NirpE 
I have been able to reproduce this issue by manually adding a 0 byte ```librealm-jni.so``` file to the APK being installed. This of course shouldn't be possible when installing a APK, and you would probably have a lot more crashes if it was a problem with the APK itself. So I am suspecting the install process on the Samsung phone doing something wrong in a edge case.

My best guess so far is that the user should try to free up some space on his phone, try removing the app and installing it again. Note that it is probably important that he uninstalls the app it before installing it again, to ensure that the native libraries are installed correctly.

But I will continue to see if I can trigger this behaviour with a normal APK.

**Comment by cmelchior** [comment] 2015-04-29 09:06
Hi @NirpE 
I have not been able to trigger this behaviour outside manipulating the APK myself, which makes it difficult to move forward with this. Do you know if the users experiencing this issue are using stock versions of Android or if they are using a rooted device with possible Cyanogen or similar?

**Comment by NirpE** [comment] 2015-04-29 09:12
The crash has been seen for only 2 users, where other device has been rooted.

**Comment by cmelchior** [comment] 2015-04-29 09:15
Sorry, do you mean that those two users had rooted phones? or that you know of other users with rooted phones that hasn't seen this problem?

**Comment by NirpE** [comment] 2015-04-29 09:16
1 had rooted and 1 didn't have rooted phone. But we had to disable Realm totally because of the crashes with S6.

**Comment by bmunkholm** [comment] 2015-04-29 12:55
Really sorry to hear that. I can certainly understand the S6 issue is a dealbreaker.
I would be very grateful if you could please post an update here if you still see a user or two with that issue, where you are not using Realm.
Our best guess right now is that it's simply due to out of memory on the device, since Realm can't possibly change the size of the .so file.

**Comment by NirpE** [comment] 2015-04-30 05:39
Yes of course, and if/when you find the fix for S6 we can probably take Realm back into use and see if this occurs.

**Comment by bmunkholm** [comment] 2015-04-30 06:04
Awesome - we are definitely going to fix it (the S6 issue). It's just really really weird.
Thanks for your patience!

**Comment by cmelchior** [comment] 2015-05-05 06:54
Hi @NirpE 
With nothing more to go on, I will close it for now as there is not much we can do about it. If any new information appear please feel free to reopen this.

**Closed by cmelchior** 2015-05-05 06:54 UTC
Labels: Pending, support

**Comment by jozuasijsling** [comment] 2015-12-28 16:05
The guys at KeepSafe worked out what's causing this issue. Read their blog post about it: https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db#.hpom8xns2 

In summary, it's a known bug in the installation process that makes extracting native libraries from the .apk file fail silently. As a consequence either the library fails to update, meaning that your new installation runs an old version of the native library, or it fails to be written, leaving just a blank file. The bug occurs very infrequently, which is why it never got much attention.
