### ISSUE TITLE
Attempt to recreate a file for type io.realm.MY-PACKAGE_beans_ImageRealmProxy

### ISSUE THREAD

**Issue by NizarETH** [realm/realm-java#7562] opened 2021-09-09 10:45 UTC
### How frequently does the bug occur?

Sometimes

### Description

I update my realm Java using this version `  classpath 'io.realm:realm-gradle-plugin:10.8.0'`, then I start receiving this error, so after any modification in my code when I try to build, the first time I got the error but in the second build it works with no problem.

### Stacktrace & log output

```shell
Attempt to recreate a file for type io.realm.MY-PACKAGE_beans_ImageRealmProxy
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

If I modify my code I'll get it only in the first build.

### Version

10.8.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android

### Build environment

Android Studio Arctic Fox | 2020.3.1 Patch 1
Build #AI-203.7717.56.2031.7621141, built on August 7, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.dubreuia, com.tabnine.TabNine, org.sonarlint.idea, org.jetbrains.kotlin

buildToolsVersion = "30.0.0"
compileSdkVersion = 30
googlePlayServicesVersion = "17.0.0"
minSdkVersion = 28
supportLibVersion = "30.0.0"
targetSdkVersion = 30

**Comment by cmelchior** [comment] 2021-09-09 10:47
This seems to be the same as https://github.com/realm/realm-java/issues/7532

@NizarETH But in your case it also seems to happen on clean builds and not just incremental builds. Or am I misunderstanding when it happens?

Is your project one you can share so we can more effectively debug it? If not, can you share more details about your project (and especially module layout)

**Comment by NizarETH** [comment] 2021-09-09 11:01
It happens just on incremental builds, If I clean before the build, I don't get it.

my Java Class `Image` where I have the issue.

```
public class Image extends RealmObject {

    @PrimaryKey
    private String id;
    private String url;
    private Metadata metadata;

    public Image(String id, String url, Metadata metadata) {
        this.id = id;
        this.url = url;
        this.metadata = metadata;
    }

    public Image() {
    }

//getters and setters
```

**Comment by cmelchior** [comment] 2021-09-09 11:27
@NizarETH Thank you.

Can you try to describe your project structure in more details. What kind of modules do you have and what are the dependencies between them?

E.g. in #7532 There is `dynamic-feature` module that depends on the `app` module. Where all Realm classes are in the `app` module. Right now I'm suspecting that setup might be causing issues somewhere. So knowing how your setup is would be valuable.

**Comment by NizarETH** [comment] 2021-09-09 11:37
@cmelchior Thank you.

all my Realm classes in `beans` package 

![Capture d’écran 2021-09-09 à 12 29 22](https://user-images.githubusercontent.com/11196611/132677996-a8ec81a5-94f9-4e8f-b237-bf8f1fa0eaa4.png)

- In my class Application, I init Realm like that :


```
     Realm.init(this);
        RealmConfiguration config = new RealmConfiguration.Builder() 	 .deleteRealmIfMigrationNeeded().build();

        Realm.setDefaultConfiguration(config);
```
In my activities, fragments and adapters, I use Realm transaction to read and write data.

- This is the Build gradle (Module):

```
def verCode = 1
def verName = "1"
if (project.hasProperty("vcode")) {
    verCode = vcode as Integer
}
if (project.hasProperty("vname")) {
    verName = vname
}


apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'realm-android'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'kotlin-android'

android {

    def final myApplicationId = "MY_PACKAGE"


    def final ENV = envTask()
    def final googleApiKey = ENV['GOOGLE_API_KEY']
    def final host = ENV['HOST']
    def final schema = ENV['SCHEMA']
    def final qr = schema + "://" + host
    def final apiUrl = ENV['API_URL']


    defaultConfig {

        applicationId myApplicationId
        compileSdkVersion rootProject.ext.compileSdkVersion
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode verCode
        versionName verName
        multiDexEnabled true
        signingConfig signingConfigs.debug

        buildConfigField("String", "API_URL", "\"${apiUrl}\"")
        buildConfigField("String", "GOOGLE_API_KEY", "\"${googleApiKey}\"")
        buildConfigField("String", "HOST", "\"${host}\"")
        buildConfigField("String", "QR_LINK", "\"${qr}\"")
        manifestPlaceholders = [googleApiKey: googleApiKey, host: host, schema: schema]

    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    // For Kotlin projects
    kotlinOptions {
        jvmTarget = "11"
    }
    // To enable Crashlytics mapping file upload for specific build types:

    buildTypes {
        debug {
            debuggable true

            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled false

            // Enables resource shrinking, which is performed by the

            shrinkResources false
            // proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
            manifestPlaceholders = [crashlyticsCollectionEnabled: "false"]

        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            manifestPlaceholders = [crashlyticsCollectionEnabled: "true"]

            shrinkResources true

            firebaseCrashlytics {
                mappingFileUploadEnabled true
            }

        }
    }


    productFlavors {

        flavorDimensions "version"

        dev {
            applicationIdSuffix ".dev"
            dimension "version"
        }

        production {
            dimension "version"
        }

        staging {
            applicationIdSuffix ".staging"
            dimension "version"
        }
    }

    android.ndkVersion = "21.3.6528147"

}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:26.5.0')

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation "com.android.support:support-emoji:28.0.0"
    implementation "com.android.support:support-emoji-bundled:28.0.0"
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-perf'
    implementation 'com.caverock:androidsvg-aar:1.4'
    implementation "com.airbnb.android:lottie:3.4.0"
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-location:18.0.0'
    implementation 'com.google.maps.android:android-maps-utils:0.6.2'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'com.github.mumayank:AirLocation:1.3.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.amitshekhar.android:android-networking:1.0.2'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation 'me.everything:overscroll-decor-android:1.0.4'
    implementation 'com.google.firebase:firebase-config'
    implementation 'com.jakewharton.timber:timber:4.7.1'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

    devImplementation 'com.willowtreeapps.hyperion:hyperion-core:0.9.31'
    devImplementation 'com.willowtreeapps.hyperion:hyperion-crash:0.9.31'
    devImplementation 'com.willowtreeapps.hyperion:hyperion-phoenix:0.9.31'
    devImplementation 'com.willowtreeapps.hyperion:hyperion-shared-preferences:0.9.31'
    devImplementation 'com.github.chuckerteam.chucker:library:3.2.0'
    devImplementation 'com.willowtreeapps.hyperion:hyperion-timber:0.9.31'
    devImplementation 'com.willowtreeapps.hyperion:hyperion-recorder:0.9.31'

    stagingImplementation 'com.willowtreeapps.hyperion:hyperion-core:0.9.31'
    stagingImplementation 'com.willowtreeapps.hyperion:hyperion-crash:0.9.31'
    stagingImplementation 'com.willowtreeapps.hyperion:hyperion-phoenix:0.9.31'
    stagingImplementation 'com.willowtreeapps.hyperion:hyperion-shared-preferences:0.9.31'
    stagingImplementation 'com.github.chuckerteam.chucker:library:3.2.0'
    stagingImplementation 'com.willowtreeapps.hyperion:hyperion-timber:0.9.31'
    stagingImplementation 'com.willowtreeapps.hyperion:hyperion-recorder:0.9.31'

    productionImplementation "com.github.chuckerteam.chucker:library-no-op:3.2.0"
    productionImplementation 'com.willowtreeapps.hyperion:hyperion-core-no-op:0.9.31'


    implementation 'androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.0'
    implementation "androidx.browser:browser:1.3.0"
    implementation 'com.karumi:dexter:6.2.3'
    implementation 'androidx.security:security-crypto:1.1.0-alpha03'
    implementation 'com.google.android.gms:play-services-vision:20.1.3'
    implementation 'com.journeyapps:zxing-android-embedded:4.2.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'

    implementation 'co.bewifi.core:bewificore:0.6.0'
    implementation 'co.bewifi.wificonnect:wificonnect:0.20.2'


    implementation "androidx.camera:camera-camera2:1.1.0-alpha08"
    implementation "androidx.camera:camera-lifecycle:1.1.0-alpha08"
    implementation "androidx.camera:camera-view:1.0.0-alpha28"

    // qrcode reader
    implementation 'com.google.zxing:core:3.3.0'

}
```

**Comment by cmelchior** [comment] 2021-09-09 11:44
Thank you. So just to be sure. You only have an `app` module. Is that correct?

**Comment by NizarETH** [comment] 2021-09-09 11:47
Yes, only one module

**Comment by NizarETH** [comment] 2021-10-04 10:54
Hey @cmelchior another thing a little wired but when I build my project in my `Redmi note 9 Pro` I got the error above (only first build), but when I build it in my `Samsung A32` everything is Ok no error in first build.
I don't know if that can help you to debug the error.

**Comment by ruiyong-lee** [comment] 2021-11-08 03:51
Me too！Any modification in my code when I try to build, the first time I got the error but in the second build it works with no problem.

**Comment by miraclebg** [comment] 2021-11-08 07:58
Locally is not a huge deal but this started happening also on our CI machine... and every other build fails. :(

**Comment by cmelchior** [comment] 2021-11-08 08:17
@ruiyong-lee @miraclebg So far we haven't been able to reproduce this, but it is interesting that it also fails on CI. Are your projects open source by any chance, or are you able to share a project where this behavior can be reproduced? (It can also be private)

**Comment by miraclebg** [comment] 2021-11-08 08:53
Next time i see it i'll post / share some data.

It is a private project unfortunately - but i am happy to somehow help resolve this as it's bugging the hell out of me :)





Martin Kovachev - Head of IT,
Nimasystems Ltd,
Tel./Mobile: + 359 896 610 876
E-Mail: ***@***.***
Skype: miracle_bg
Web: https://www.nimasystems.com

**Comment by jorrdane** [comment] 2021-11-08 11:51
same problem here. only first build fails.

error: Attempt to recreate a file for type io.realm.PACKAGE_NAME_REALMOBJECTRealmProxy
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by sschirr** [comment] 2021-11-10 07:05
I have the same problem.
The project I am building is splitted into multiple projects which then are build and installed as a gradle dependency to the local gradle repo. The main project is using these dependencies.
I can always trigger the issue when I make changes to one of the projects and install it to the local repo with the same snapshot version and then try to run the main project again.

**Comment by jorrdane** [comment] 2021-11-12 08:25
> @ruiyong-lee @miraclebg So far we haven't been able to reproduce this, but it is interesting that it also fails on CI. Are your projects open source by any chance, or are you able to share a project where this behavior can be reproduced? (It can also be private)

hello, I added some info about this bug
it still happens

**Comment by egypttoc** [comment] 2021-11-12 20:11
It happens to me too. every time I make a change to class and do a build I get the same error and when I run the build again it works. only happens with incremental builds

**Comment by cmelchior** [comment] 2021-11-13 20:25
While investigating an unrelated issue, I stumbled upon a reproduction case. Our JsonExample is capable of reproducing this. So hopefully we can figure out what is going wrong now.

**Comment by cmelchior** [comment] 2021-11-14 15:57
After diving deeper into this, I can still not find anything wrong with the way we use our annotation processor. But I did find this issue in Gradle: https://github.com/gradle/gradle/issues/18840

With a fix being merged here: https://github.com/gradle/gradle/pull/18864

After upgrading to Gradle 7.3-rc-5, the problem seems to go away in our sample project.

Can you try to upgrade to that version and see if it fixes the problem?

**Comment by malte3d** [comment] 2021-11-14 20:32
I've had the same problem. The Gradle update to 7.3 worked for me! Haven't seen the error since then.  Were using Gradle 7.2 before.

**Comment by ruiyong-lee** [comment] 2021-11-15 03:05
Nice！！！Gradle 7.3

**Comment by miraclebg** [comment] 2021-11-15 07:59
I can also confirm that with Gradle 7.3 the issue seems to be gone! Thank you for spotting this!

**Comment by cmelchior** [comment] 2021-11-15 16:58
Great, I'll issume this issue is fixed then. Closing.

**Closed by cmelchior** 2021-11-15 16:58 UTC
Labels: T-Bug, O-Community

**Comment by jorrdane** [comment] 2021-11-23 09:27
> Great, I'll issume this issue is fixed then. Closing.

hello again!
one more related problem appeared on Gradle 7.3-rc-5/ 7.3-bin:

same error:

```
error: Attempt to recreate a file for type io.realm.com_PACKAGE_OBJECTRealmProxy
public class OBJECT extends RealmObject {
       ^
```

Appears if I add an svg in Drawable through Add Vector Asset.
Build -> Run doesn't help anymore.
Have to Clean Project -> Rebuild.

**Comment by midasdestroyer** [comment] 2022-07-16 21:19
I'm having the same issue but I'm trying the 10.10.1 version, how can i fix this? is just matter to update?
