### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x5f244ff2 (code=2), thread 26259 (pool-9-thread-1)

### ISSUE THREAD

**Issue by Kastr** [realm/realm-java#3863] opened 2016-11-30 20:27 UTC
App crashes when running the app in a Samsung Galaxy Tab 3 Lite (SM-T110) API 17.

Crashes on any realm versions tested (2.2.1, 2.2.0, 2.1.1)
On any other devices and emulators (with APIs as low as 16) we tested the app runs fine.
Unfortunately, we don't have another Samsung device to test.

Steps:
- Initialize the Realm in application
- getInstance anywhere in mainActivity (currently testing onCreate)
-> CRASH

**Comment by Zhuinden** [comment] 2016-11-30 20:36
duplicate of https://github.com/realm/realm-java/issues/3651

**Comment by Zhuinden** [comment] 2016-11-30 23:12
Do you have the device itself in your hands?

Because in that case, you can add `RealmLog.setLevel(ALL)` (I'm hazy on the API) which adds native logging.

**Comment by kneth** [comment] 2016-12-01 08:57
@Kastr If you can set the log level and post the log, we can better see what it going on.

**Comment by kneth** [comment] 2016-12-01 08:58
@Kastr I close the issue (duplicate). Please post log file in #3651.

**Closed by kneth** 2016-12-01 08:58 UTC

**Comment by Zhuinden** [comment] 2017-03-30 12:03
https://github.com/realm/realm-java/pull/4402 might fix this once it's merged
