### ISSUE TITLE
RealmResults in a function did not have value.

### ISSUE THREAD

**Issue by lengyue524** [realm/realm-java#3243] opened 2016-08-03 06:53 UTC
#### Goal

Use RealmResults in a function.
But RealmResults in a function did not have value.
#### Expected Results

> rspMember.boxId = 12560632
#### Actual Results

>  rspMember.boxId = 0
#### Steps & Code to Reproduce

> =============rspMember.boxId===============12560632
> =============members.get(i).boxId===============0
#### Code Sample

``` java

public class TribeMember extends RealmObject {
    @Ignore
    public static final int TRIBE_NOTHING = -1;
    @Ignore
    public static final int TRIBE_MASTER = 0;
    @Ignore
    public static final int TRIBE_MEMBER = 1;
    @Ignore
    public static final int TRIBE_MANAGER = 2;
    @Ignore
    public static final int SET_MANAGER = 0;
    @Ignore
    public static final int DEL_MANAGER = 1;
    @PrimaryKey
    public long boxId;
    public short identity;
    public String nickName;
    public int sex;
    public String avatarUrl;
    public int status;

public <E extends RealmObject> Observable<RealmResults<E>> getAllAsync(Class<E> clazz) {
        return mRealm.where(clazz).findAllAsync().asObservable().filter(RealmResults::isLoaded);
    }

tribeManager.getAllAsync(TribeMember.class).observeOn(AndroidSchedulers.mainThread())
                .subscribe(this::setMemberView, Throwable::printStackTrace);

private void setMemberView(List<TribeMember> rspMembers) {
        for (TribeMember rspMember : rspMembers) {
            LogUtils.e("=============rspMember.boxId==============="+rspMember.boxId);
        }
        getIdentity(rspMembers);
}

public static void getIdentity(List<TribeMember> members){
        for (int i=0;i<members.size();i++) {
LogUtils.e("=============members.get(i).boxId==============="+members.get(i).boxId);
        }
    }

```
#### Version of Realm and tooling

Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: android 6.0,nexus 6

**Comment by Zhuinden** [comment] 2016-08-03 08:36
`static` fields are ignored by default, no need to add `@Ignore`on them manually

By the way, the issue is that the Javassist bytecode manipulation transformer thing cannot resolve the fact that your `members.get(i)` is actually a `TribeMember`, so the actual field rewrite to use the proxy getter method doesn't happen.

Your code can easily be fixed with the following:


``` java
public static void getIdentity(List<TribeMember> members){
        for (int i=0;i<members.size();i++) {
             TribeMember member = members.get(i);
LogUtils.e("=============members.get(i).boxId==============="+member.boxId);
        }
    }
```

**Comment by lengyue524** [comment] 2016-08-03 09:58
@Zhuinden your code did't fix my problem.BoxId is still 0.

**Comment by Zhuinden** [comment] 2016-08-03 10:50
Hrmm, that's odd. What happens if you use `getBoxId()`?

**Comment by lengyue524** [comment] 2016-08-03 11:03
@Zhuinden getBoxId() works.I think this is a bug when using public member variables .@realm-ci

**Comment by Zhuinden** [comment] 2016-08-03 11:16
I see. Using my version of the code, does it fail if `getIdentity()` is _not static_?

**Comment by lengyue524** [comment] 2016-08-04 01:37
@Zhuinden static? TribeMember is java bean, no one make the method static.

**Comment by lengyue524** [comment] 2016-08-04 03:41
In the Method "setMemberView", "rspMember.boxId" call the "realmGet$boxId" method of class "TribeMemberRealmProxy".
But In the Method "getIdentity", "members.get(i).boxId" didn't call the "realmGet$boxId" method of class "TribeMemberRealmProxy".

How did Realm call the method "realmGet$boxId"?

**Comment by beeender** [comment] 2016-08-04 05:49
hmmm, our bytecode transformer seems not transform field accessor for collection elements. Thanks a lot for figuring that out!! I am not quite sure if it can be fixed easily.

For now, I think you need to use getters in this case to return the `boxid`.

**Comment by Zhuinden** [comment] 2016-08-04 06:20
@beeender he claimed it "didn't work", although I'm not sure why.

**Comment by lengyue524** [comment] 2016-08-04 06:42
methon "getIdentity" is in another class "TribeUtils".
I change method "getIdentity" non static and place it in the same class of "setMemberView" members.get(i).boxId works.
it not work in the class "TribeUtils" even it's non static.

**Comment by cmelchior** [comment] 2019-11-27 20:54
Outdated and closing due to inactivity.

**Closed** 2019-11-27 20:59 UTC
Labels: O-Community, Pipeline-Backlog, T-Bug
