### ISSUE TITLE
ANR in realm 0.84.1

### ISSUE THREAD

**Issue by bangarharshit** [realm/realm-java#1897] opened 2015-12-06 09:40 UTC
I am using realm 0.84.1 and it is giving frequent anr in getInstance. Strangely this is happening only on Lenovo phone.

Traces:
```
Cmd line: com.sandwich.chatclient
ABI: arm
Build type: optimized
Zygote loaded classes=3681 post zygote classes=1942
Intern table: 51339 strong; 1441 weak
JNI: CheckJNI is on; globals=830 (plus 1 weak)
Libraries: /data/app/com.sandwich.chatclient-1/lib/arm/librealm-jni.so /system/lib/libandroid.so /system/lib/libaudioeffect_jni.so /system/lib/libcompiler_rt.so /system/lib/libjavacrypto.so /system/lib/libjnigraphics.so /system/lib/libmedia_jni.so /system/lib/librs_jni.so /system/lib/libsoundpool.so /system/lib/libwebviewchromium_loader.so libjavacore.so (11)
Heap: 9% free, 14MB/16MB; 195177 objects
Dumping cumulative Gc timings
Start Dumping histograms for 476 iterations for concurrent mark sweep
ProcessMarkStack:	Sum: 9.191s 99% C.I. 0.012ms-55.962ms Avg: 6.436ms Max: 95.113ms
MarkConcurrentRoots:	Sum: 1.358s 99% C.I. 0.005ms-9.743ms Avg: 1.427ms Max: 11.098ms
UpdateAndMarkImageModUnionTable:	Sum: 944.328ms 99% C.I. 1.123ms-9.247ms Avg: 1.983ms Max: 16.995ms
ScanGrayZygoteSpaceObjects:	Sum: 235.793ms 99% C.I. 63us-2432.250us Avg: 504.910us Max: 3348us
MarkNonThreadRoots:	Sum: 186.673ms 99% C.I. 39.666us-1371.999us Avg: 196.085us Max: 2991us
MarkRootsCheckpoint:	Sum: 172.765ms 99% C.I. 46us-2323.999us Avg: 181.475us Max: 20080us
ImageModUnionClearCards:	Sum: 155.735ms 99% C.I. 116us-1323.999us Avg: 163.587us Max: 21011us
SweepMallocSpace:	Sum: 145.969ms 99% C.I. 5us-2895.999us Avg: 153.328us Max: 9921us
SweepZygoteSpace:	Sum: 113.907ms 99% C.I. 187us-883.250us Avg: 243.912us Max: 1472us
ZygoteModUnionClearCards:	Sum: 103.892ms 99% C.I. 66us-999.500us Avg: 111.233us Max: 1772us
ReMarkRoots:	Sum: 93.052ms 99% C.I. 61us-1282.749us Avg: 195.487us Max: 1928us
EnqueueFinalizerReferences:	Sum: 60.861ms 99% C.I. 9.153us-1083.999us Avg: 127.859us Max: 4025us
ScanGrayImageSpaceObjects:	Sum: 57.244ms 99% C.I. 91us-880.999us Avg: 120.260us Max: 7552us
ScanGrayAllocSpaceObjects:	Sum: 49.620ms 99% C.I. 1us-1659.999us Avg: 52.121us Max: 9971us
(Paused)ScanGrayImageSpaceObjects:	Sum: 46.069ms 99% C.I. 91us-333.749us Avg: 99.073us Max: 772us
SweepSystemWeaks:	Sum: 40.548ms 99% C.I. 24us-592.999us Avg: 85.184us Max: 2118us
FinishPhase:	Sum: 38.489ms 99% C.I. 54us-380.999us Avg: 80.859us Max: 498us
MarkAllocStackAsLive:	Sum: 36.448ms 99% C.I. 29us-780.999us Avg: 76.571us Max: 1763us
AllocSpaceClearCards:	Sum: 33.431ms 99% C.I. 1us-214.799us Avg: 17.558us Max: 825us
(Paused)ScanGrayZygoteSpaceObjects:	Sum: 26.631ms 99% C.I. 52us-167.999us Avg: 58.401us Max: 1182us
ProcessCards:	Sum: 23.219ms 99% C.I. 6us-199.209us Avg: 24.389us Max: 13220us
SwapBitmaps:	Sum: 21.624ms 99% C.I. 13us-146.833us Avg: 45.428us Max: 1069us
(Paused)PausePhase:	Sum: 13.026ms 99% C.I. 14us-90.499us Avg: 27.365us Max: 3772us
(Paused)ScanGrayObjects:	Sum: 12.979ms 99% C.I. 0.670ms-3.331ms Avg: 1.179ms Max: 3.404ms
(Paused)ScanGrayAllocSpaceObjects:	Sum: 11.212ms 99% C.I. 1us-49.911us Avg: 12.055us Max: 1465us
PreCleanCards:	Sum: 10.354ms 99% C.I. 15us-93.666us Avg: 21.752us Max: 644us
InitializePhase:	Sum: 9.328ms 99% C.I. 2us-86.199us Avg: 19.596us Max: 309us
MarkingPhase:	Sum: 9.134ms 99% C.I. 14us-49.959us Avg: 19.189us Max: 100us
RevokeAllThreadLocalAllocationStacks:	Sum: 6.474ms 99% C.I. 7us-98.642us Avg: 13.600us Max: 144us
ReclaimPhase:	Sum: 6.314ms 99% C.I. 10us-49.959us Avg: 13.264us Max: 422us
Sweep:	Sum: 5.717ms 99% C.I. 7us-49.959us Avg: 12.010us Max: 448us
ProcessReferences:	Sum: 4.304ms 99% C.I. 5us-90.142us Avg: 9.042us Max: 425us
MarkRoots:	Sum: 3.407ms 99% C.I. 4us-49.854us Avg: 7.157us Max: 78us
SweepLargeObjects:	Sum: 3.333ms 99% C.I. 1us-193.666us Avg: 7.002us Max: 824us
RecursiveMark:	Sum: 2.591ms 99% C.I. 4us-24us Avg: 5.443us Max: 24us
BindBitmaps:	Sum: 1.870ms 99% C.I. 2us-10us Avg: 3.928us Max: 10us
SwapStacks:	Sum: 1.239ms 99% C.I. 2us-36us Avg: 2.602us Max: 36us
UnBindBitmaps:	Sum: 664us 99% C.I. 1us-5us Avg: 1.394us Max: 5us
(Paused)ProcessMarkStack:	Sum: 584us 99% C.I. 1us-49.854us Avg: 1.226us Max: 74us
FindDefaultSpaceBitmap:	Sum: 523us 99% C.I. 1us-16us Avg: 1.098us Max: 16us
PreSweepingGcVerification:	Sum: 477us 99% C.I. 1us-2us Avg: 1.002us Max: 2us
Done Dumping histograms 
concurrent mark sweep paused:	Sum: 227.315ms 99% C.I. 236us-3309.999us Avg: 477.552us Max: 5724us
concurrent mark sweep total time: 13.240s mean time: 27.815ms
concurrent mark sweep freed: 427725 objects with total size 18MB
concurrent mark sweep throughput: 32305.5/s / 1430KB/s
Start Dumping histograms for 2 iterations for partial concurrent mark sweep
ProcessMarkStack:	Sum: 77.970ms 99% C.I. 0.007ms-34.100ms Avg: 12.995ms Max: 34.198ms
UpdateAndMarkImageModUnionTable:	Sum: 33.111ms 99% C.I. 10.960ms-22.151ms Avg: 16.555ms Max: 22.151ms
MarkRootsCheckpoint:	Sum: 17.463ms 99% C.I. 0.946ms-8.516ms Avg: 4.365ms Max: 8.516ms
ScanGrayAllocSpaceObjects:	Sum: 11.534ms 99% C.I. 0.010ms-8.764ms Avg: 2.883ms Max: 8.815ms
MarkConcurrentRoots:	Sum: 11.342ms 99% C.I. 0.008ms-6.520ms Avg: 2.835ms Max: 6.571ms
SweepMallocSpace:	Sum: 9.586ms 99% C.I. 0.044ms-5.618ms Avg: 2.396ms Max: 5.618ms
SweepLargeObjects:	Sum: 8.462ms 99% C.I. 0.911ms-7.534ms Avg: 4.231ms Max: 7.551ms
(Paused)ScanGrayObjects:	Sum: 7.101ms 99% C.I. 0.725ms-6.344ms Avg: 3.550ms Max: 6.376ms
ReMarkRoots:	Sum: 2.535ms 99% C.I. 0.868ms-1.667ms Avg: 1.267ms Max: 1.667ms
MarkAllocStackAsLive:	Sum: 1.550ms 99% C.I. 432us-1118us Avg: 775us Max: 1118us
EnqueueFinalizerReferences:	Sum: 1.226ms 99% C.I. 281us-943.500us Avg: 613us Max: 945us
AllocSpaceClearCards:	Sum: 1.121ms 99% C.I. 14us-490us Avg: 140.125us Max: 496us
SweepSystemWeaks:	Sum: 1.089ms 99% C.I. 136us-953us Avg: 544.500us Max: 953us
UpdateAndMarkZygoteModUnionTable:	Sum: 945us 99% C.I. 462us-483us Avg: 472.500us Max: 483us
ImageModUnionClearCards:	Sum: 699us 99% C.I. 128us-266us Avg: 174.750us Max: 266us
ScanGrayZygoteSpaceObjects:	Sum: 399us 99% C.I. 62us-337us Avg: 199.500us Max: 337us
ScanGrayImageSpaceObjects:	Sum: 367us 99% C.I. 112us-255us Avg: 183.500us Max: 255us
ZygoteModUnionClearCards:	Sum: 301us 99% C.I. 69us-87us Avg: 75.250us Max: 87us
FinishPhase:	Sum: 241us 99% C.I. 110us-131us Avg: 120.500us Max: 131us
MarkNonThreadRoots:	Sum: 238us 99% C.I. 49us-85us Avg: 59.500us Max: 85us
RevokeAllThreadLocalAllocationStacks:	Sum: 121us 99% C.I. 55us-66us Avg: 60.500us Max: 66us
ProcessReferences:	Sum: 100us 99% C.I. 21us-79us Avg: 50us Max: 79us
MarkingPhase:	Sum: 77us 99% C.I. 29us-48us Avg: 38.500us Max: 48us
PreCleanCards:	Sum: 75us 99% C.I. 23us-52us Avg: 37.500us Max: 52us
(Paused)PausePhase:	Sum: 47us 99% C.I. 23us-24us Avg: 23.500us Max: 24us
ProcessCards:	Sum: 43us 99% C.I. 9us-14us Avg: 10.750us Max: 14us
SwapBitmaps:	Sum: 42us 99% C.I. 19us-23us Avg: 21us Max: 23us
ReclaimPhase:	Sum: 34us 99% C.I. 16us-18us Avg: 17us Max: 18us
Sweep:	Sum: 32us 99% C.I. 15us-17us Avg: 16us Max: 17us
MarkRoots:	Sum: 20us 99% C.I. 9us-11us Avg: 10us Max: 11us
RecursiveMark:	Sum: 10us 99% C.I. 4us-6us Avg: 5us Max: 6us
InitializePhase:	Sum: 8us 99% C.I. 4us-4us Avg: 4us Max: 4us
SwapStacks:	Sum: 7us 99% C.I. 3us-4us Avg: 3.500us Max: 4us
BindBitmaps:	Sum: 6us 99% C.I. 3us-3us Avg: 3us Max: 3us
UnBindBitmaps:	Sum: 5us 99% C.I. 2us-3us Avg: 2.500us Max: 3us
(Paused)ProcessMarkStack:	Sum: 4us 99% C.I. 2us-2us Avg: 2us Max: 2us
FindDefaultSpaceBitmap:	Sum: 2us 99% C.I. 1us-1us Avg: 1us Max: 1us
Done Dumping histograms 
partial concurrent mark sweep paused:	Sum: 12.709ms 99% C.I. 4.538ms-8.171ms Avg: 6.354ms Max: 8.171ms
partial concurrent mark sweep total time: 187.919ms mean time: 93.959ms
partial concurrent mark sweep freed: 40546 objects with total size 3MB
partial concurrent mark sweep throughput: 216824/s / 19MB/s
Start Dumping histograms for 6 iterations for sticky concurrent mark sweep
MarkRootsCheckpoint:	Sum: 149.594ms 99% C.I. 0.136ms-110.368ms Avg: 12.466ms Max: 116.361ms
ScanGrayAllocSpaceObjects:	Sum: 70.975ms 99% C.I. 0.004ms-25.584ms Avg: 2.957ms Max: 26.096ms
ProcessMarkStack:	Sum: 41.441ms 99% C.I. 0.002ms-23.078ms Avg: 1.973ms Max: 24.520ms
ScanGrayImageSpaceObjects:	Sum: 29.454ms 99% C.I. 0.093ms-12.308ms Avg: 2.454ms Max: 12.750ms
FreeList:	Sum: 16.627ms 99% C.I. 6us-384us Avg: 167.949us Max: 384us
MarkConcurrentRoots:	Sum: 13.414ms 99% C.I. 0.007ms-3.742ms Avg: 1.117ms Max: 3.824ms
SweepArray:	Sum: 10.557ms 99% C.I. 0.421ms-4.503ms Avg: 1.759ms Max: 4.503ms
ReMarkRoots:	Sum: 3.414ms 99% C.I. 97us-1067us Avg: 569us Max: 1067us
(Paused)ScanGrayObjects:	Sum: 3.186ms 99% C.I. 0.579ms-1.374ms Avg: 1.062ms Max: 1.374ms
(Paused)ScanGrayImageSpaceObjects:	Sum: 3.035ms 99% C.I. 0.092ms-2.850ms Avg: 1.011ms Max: 2.850ms
MarkingPhase:	Sum: 2.510ms 99% C.I. 355us-538us Avg: 418.333us Max: 538us
AllocSpaceClearCards:	Sum: 2.265ms 99% C.I. 3us-332us Avg: 94.375us Max: 332us
ImageModUnionClearCards:	Sum: 2.141ms 99% C.I. 120us-450us Avg: 178.416us Max: 450us
EnqueueFinalizerReferences:	Sum: 862us 99% C.I. 10us-290us Avg: 143.666us Max: 290us
MarkNonThreadRoots:	Sum: 700us 99% C.I. 23us-157us Avg: 58.333us Max: 157us
ZygoteModUnionClearCards:	Sum: 592us 99% C.I. 66us-158us Avg: 98.666us Max: 158us
ScanGrayZygoteSpaceObjects:	Sum: 589us 99% C.I. 53us-221us Avg: 98.166us Max: 221us
SweepSystemWeaks:	Sum: 540us 99% C.I. 26us-181us Avg: 90us Max: 181us
ResetStack:	Sum: 385us 99% C.I. 43us-122us Avg: 64.166us Max: 122us
FinishPhase:	Sum: 265us 99% C.I. 31us-65us Avg: 44.166us Max: 65us
ProcessReferences:	Sum: 244us 99% C.I. 5us-100us Avg: 40.666us Max: 100us
(Paused)ScanGrayAllocSpaceObjects:	Sum: 180us 99% C.I. 2us-56us Avg: 30us Max: 56us
RevokeAllThreadLocalAllocationStacks:	Sum: 175us 99% C.I. 10us-51us Avg: 29.166us Max: 51us
(Paused)PausePhase:	Sum: 135us 99% C.I. 15us-38us Avg: 22.500us Max: 38us
PreCleanCards:	Sum: 132us 99% C.I. 15us-29us Avg: 22us Max: 29us
ProcessCards:	Sum: 114us 99% C.I. 6us-14us Avg: 9.500us Max: 14us
ReclaimPhase:	Sum: 83us 99% C.I. 12us-16us Avg: 13.833us Max: 16us
MarkRoots:	Sum: 55us 99% C.I. 7us-16us Avg: 9.166us Max: 16us
UnBindBitmaps:	Sum: 32us 99% C.I. 2us-18us Avg: 5.333us Max: 18us
InitializePhase:	Sum: 27us 99% C.I. 3us-9us Avg: 4.500us Max: 9us
BindBitmaps:	Sum: 24us 99% C.I. 2us-8us Avg: 4us Max: 8us
RecordFree:	Sum: 18us 99% C.I. 2us-5us Avg: 3us Max: 5us
SwapStacks:	Sum: 17us 99% C.I. 2us-4us Avg: 2.833us Max: 4us
FindDefaultSpaceBitmap:	Sum: 13us 99% C.I. 1us-3us Avg: 2.166us Max: 3us
(Paused)ProcessMarkStack:	Sum: 10us 99% C.I. 1us-2us Avg: 1.666us Max: 2us
PreSweepingGcVerification:	Sum: 6us 99% C.I. 1us-1us Avg: 1us Max: 1us
Done Dumping histograms 
sticky concurrent mark sweep paused:	Sum: 10.346ms 99% C.I. 0.299ms-3.115ms Avg: 1.724ms Max: 3.115ms
sticky concurrent mark sweep total time: 353.876ms mean time: 58.979ms
sticky concurrent mark sweep freed: 92894 objects with total size 5MB
sticky concurrent mark sweep throughput: 263156/s / 16MB/s
Total time spent in GC: 13.781s
Mean GC size throughput: 2047KB/s
Mean GC object throughput: 44036.2 objects/s
Total number of allocations 802084
Total bytes allocated 42MB
Free memory 1577KB
Free memory until GC 1577KB
Free memory until OOME 113MB
Total memory 16MB
Max memory 128MB
Total mutator paused time: 250.370ms
Total time waiting for GC to complete: 1.087ms

DALVIK THREADS (50):
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x7439b000 self=0xb4427400
  | sysTid=16433 nice=0 cgrp=default sched=0/0 handle=0xb6fa5bec
  | state=S schedstat=( 3186589058 421835166 2294 ) utm=278 stm=40 core=0 HZ=100
  | stack=0xbe790000-0xbe792000 stackSize=8MB
  | held mutexes=
  at io.realm.Realm.create(Realm.java:244)
  - waiting to lock <0x0cf4373e> (a java.lang.Class<io.realm.Realm>) held by thread 39
  at io.realm.Realm.getInstance(Realm.java:219)
  at io.realm.Realm.getInstance(Realm.java:182)
  at com.sandwich.chatclient.ui.fragments.SandwichMessagesScreen.onCreate(SandwichMessagesScreen.java:110)
  at android.app.Activity.performCreate(Activity.java:6092)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
  at android.app.ActivityThread.access$800(ActivityThread.java:178)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5624)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

"Heap thread pool worker thread 2" prio=5 tid=2 Native (still starting up)
  | group="" sCount=1 dsCount=0 obj=0x0 self=0xaf84a400
  | sysTid=16441 nice=0 cgrp=default sched=0/0 handle=0xb4c17000
  | state=S schedstat=( 3895922 7819922 22 ) utm=0 stm=0 core=3 HZ=100
  | stack=0xb3b35000-0xb3b37000 stackSize=1020KB
  | held mutexes=
  native: #00 pc 000138e8  /system/lib/libc.so (syscall+28)
  native: #01 pc 000a93b7  /system/lib/libart.so (art::ConditionVariable::Wait(art::Thread*)+74)
  native: #02 pc 002369ef  /system/lib/libart.so (art::ThreadPool::GetTask(art::Thread*)+50)
  native: #03 pc 00236999  /system/lib/libart.so (art::ThreadPoolWorker::Run()+52)
  native: #04 pc 002371c1  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+52)
  native: #05 pc 00017373  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #06 pc 000153df  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

"Heap thread pool worker thread 0" prio=5 tid=3 Native (still starting up)
  | group="" sCount=1 dsCount=0 obj=0x0 self=0xb4427800
  | sysTid=16438 nice=0 cgrp=default sched=0/0 handle=0xb4c19000
  | state=S schedstat=( 5195154 10233308 21 ) utm=0 stm=0 core=1 HZ=100
  | stack=0xb3d35000-0xb3d37000 stackSize=1020KB
  | held mutexes=
  native: #00 pc 000138e8  /system/lib/libc.so (syscall+28)
  native: #01 pc 000a93b7  /system/lib/libart.so (art::ConditionVariable::Wait(art::Thread*)+74)
  native: #02 pc 002369ef  /system/lib/libart.so (art::ThreadPool::GetTask(art::Thread*)+50)
  native: #03 pc 00236999  /system/lib/libart.so (art::ThreadPoolWorker::Run()+52)
  native: #04 pc 002371c1  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+52)
  native: #05 pc 00017373  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #06 pc 000153df  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)

"Heap thread pool worker thread 1" prio=5 tid=4 Native (still starting up)
  | group="" sCount=1 dsCount=0 obj=0x0 self=0xaf84b400
  | sysTid=16440 nice=0 cgrp=default sched=0/0 handle=0xb4c18000
  | state=S schedstat=( 8434308 9012384 22 ) utm=0 stm=0 core=0 HZ=100
  | stack=0xb3c35000-0xb3c37000 stackSize=1020KB
  | held mutexes=
  native: #00 pc 000138e8  /system/lib/libc.so (syscall+28)
  native: #01 pc 000a93b7  /system/lib/libart.so (art::ConditionVariable::Wait(art::Thread*)+74)
  native: #02 pc 002369ef  /system/lib/libart.so (art::ThreadPool::GetTask(art::Thread*)+50)
  native: #03 pc 00236999  /system/lib/libart.so (art::ThreadPoolWorker::Run()+52)
  native: #04 pc 002371c1  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+52)
  native: #05 pc 00017373  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #06 pc 000153df  /system/lib/libc.so (__start_thread+6)
  (no managed stack frames)
```

**Comment by bangarharshit** [comment] 2015-12-06 13:16
Also adding some more log. I am ok about moving write to another thread. But it is stuck for a long time.

```
DALVIK THREADS (49):
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x7439b000 self=0xb4427400
  | sysTid=5154 nice=0 cgrp=default sched=0/0 handle=0xb6fa5bec
  | state=S schedstat=( 7400305190 2172078871 6027 ) utm=662 stm=78 core=2 HZ=100
  | stack=0xbe790000-0xbe792000 stackSize=8MB
  | held mutexes=
  native: #00 pc 000138e8  /system/lib/libc.so (syscall+28)
  native: #01 pc 00017c3f  /system/lib/libc.so (__futex_wait_ex+42)
  native: #02 pc 00017fcd  /system/lib/libc.so (pthread_mutex_lock+308)
  native: #03 pc 00051f37  /data/app/com.sandwich.chatclient-1/lib/arm/librealm-jni.so (???)
  native: #04 pc 000551df  /data/app/com.sandwich.chatclient-1/lib/arm/librealm-jni.so (???)
  native: #05 pc 0008ee53  /data/app/com.sandwich.chatclient-1/lib/arm/librealm-jni.so (Java_io_realm_internal_SharedGroup_nativePromoteToWrite+90)
  native: #06 pc 004df52b  /data/dalvik-cache/arm/data@app@com.sandwich.chatclient-1@base.apk@classes.dex (Java_io_realm_internal_SharedGroup_nativePromoteToWrite__JJ+110)
  at io.realm.internal.SharedGroup.nativePromoteToWrite(Native method)
  at io.realm.internal.SharedGroup.promoteToWrite(SharedGroup.java:95)
  at io.realm.internal.ImplicitTransaction.promoteToWrite(ImplicitTransaction.java:51)
  at io.realm.internal.SharedGroupManager.promoteToWrite(SharedGroupManager.java:111)
  at io.realm.BaseRealm.beginTransaction(BaseRealm.java:297)
  at io.realm.Realm.beginTransaction(Realm.java:113)
  at com.sandwich.chatclient.model.ConversationHelper.generateNewConversationWithUser(ConversationHelper.java:34)
  at com.sandwich.chatclient.ui.fragments.SandwichMessageComposer$4.onClick(SandwichMessageComposer.java:177)
  at android.view.View.performClick(View.java:4848)
  at android.view.View$PerformClick.run(View.java:20260)
  at android.os.Handler.handleCallback(Handler.java:815)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5624)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)


```

**Comment by emanuelez** [comment] 2015-12-06 18:53
Hello. As a first thing I would like to suggest you to use the latest version of the plugin, which right now is 0.86.0. That is because:
 1) we might have already fixed the specific problem
 2) if we didn't we would not release a fix for the 0.84 release

That being said, you can now take advantage of async transactions, which allow you to very easily offload writes to another thread.

Also, be aware that write are mutually blocking so you if you have a long running transaction in a background thread, no other transaction will be able to start a new transaction until the previous one is committed.

**Comment by beeender** [comment] 2015-12-07 02:43
When this ANR happens, what does other thread do with Realm? Can you reproduce this issue with the new release?

**Comment by bangarharshit** [comment] 2015-12-07 07:06
I was using realm in another thread in service to write the incoming messages. But it was hanged for a very long time which shouldn't be the case. Currently we are not using any batch i.e. as soon as any data arrives we insert it and commit. We don't have much data also.  I have wrapped one of the suspect in try finally and move the commit to finally. Ever since it's not reproduced but anyways it occurred only few times.

Give me a day or two I will update realm to 0.86.0 and stress test this scenario.

**Comment by cmelchior** [comment] 2015-12-07 09:21
If you are able to reproduce this, we would be very interested in a sample project

**Comment by kneth** [comment] 2016-01-04 10:53
@bangarharshit I'll close the issue. If you are able to reproduce it, we'll be happy to reopen.

**Closed by kneth** 2016-01-04 10:53 UTC
Labels: Help, Pending
