### ISSUE TITLE
Upgrading Synced Realms breaks existing clients

### ISSUE THREAD

**Issue by ericmaxwell2003** [realm/realm-java#4658] opened 2017-05-18 00:27 UTC
### Problem
Changing the Realm Schema (e.g. Adding a new property on an object) breaks existing clients.  

### Steps to reproduce using [RealmTasks](https://github.com/realm-demos/realm-tasks) Android project.
1. Clone RealmTasks
1. Open the Android Project
1. Open `UserManager.java` and add `.schemaVersion(1)` to the SyncConfiguration.
1. Install RealmTasks onto 2 device simulators. (I used a Nexus 6 and 6P)
1. Exit the app on both simulators.
1. Add a property to the `Task.java` Realm object.
1. Open `UserManager.java` and change the schema version to 2, i.e. `.schemaVersion(2)`.
1. Build and run on the 1st simulator
1. Just launch the old version of the app on the 2nd simulator.  (do not install the new version)

### Actual Result
The updated client (1st simulator) - Runs with the new schema.
The old client (2nd simulator) - Crashes after a sync happens with ROS and then every time you launch the app with the exception `IllegalArgumentException: The schema was changed but the schema version was not updated.  The configured schema version (1) must be greater than the version in the Realm file (2) in order to update the schema`

### Expected Result
The updated client (1st simulator) - Runs with the new schema.
The old client (2nd simulator) - Runs with the old schema just fine.

Would also be nice not to need to supply the schema version, but failure to do so prevents the upgrade.  You wouldn't be able to install the new version on the 1st simulator.  This also might be a bug in the Java binding, because the other platforms don't require schema version numbers.

**Comment by ericmaxwell2003** [comment] 2017-05-18 00:30
Tested on 3.2.0 and 2.3.0

**Comment by bmeike** [comment] 2017-05-18 00:45
This code says to do exactly that:
https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/Realm.java#L506

**Comment by cmelchior** [comment] 2017-05-18 08:27
@ericmaxwell2003 I can reproduce the issue, thanks.

This is slightly complicated. We added that check to avoid users accidentially forcing a migration. So the idea was that locally you would need to provide a different version number than the local one. 

That logic is probably slightly flawed thought because right now we cannot tell the difference between a local migration and a remote one, which is what causes this.

I'm slightly confused by this though, because last I talked to Cocoa about this, I was under the impression that Cocoa required schema versions as well to trigger migrations, but that clearly doesn't seem to be the case anymore, and as this case also demonstrate. It isn't possible anyway. No idea how this slipped past testing 😞

**Comment by cmelchior** [comment] 2017-05-18 08:34
This is the original issue for the current implementation: https://github.com/realm/realm-java/issues/3982

From the looks of the description in that issue, the OS require a schema version bump to actually migrate. What might be causing the issue is that the v1 app actually doesn't need to migrate because another Client already did that. Possible it is the `realm.sharedRealm.requiresMigration(schema.getNativePtr())` check that returns the wrong value.

**Comment by Zhuinden** [comment] 2017-05-18 09:15
Object store schema migration might be becoming kinda urgent, but I wonder if the DynamicRealm API works with it?

I'm probably just rambling.

**Comment by cmelchior** [comment] 2017-05-18 09:18
Ok, it seems I was correct. When we compare the two schemas we assume that any change would require a migration. This is not true. It should be allowed if the local schema is a subset of the one on disk.

**Comment by cmelchior** [comment] 2017-05-19 09:39
Should be fixed in 3.2.1

**Closed** 2017-05-19 09:40 UTC
Labels: P:0 EXPEDITE, S:Current Iteration Backlog, T:Bug
