### ISSUE TITLE
Expose an iterator on RealmQuery

### ISSUE THREAD

**Issue by MkazemAkhgary** [realm/realm-java#6311] opened 2018-11-24 12:12 UTC
#### Describe your problem or use case
RealmQuery is very rigid. Not flexible at all. I write my own linq queries. I need at least an iterator as source of my queries.

RealmQuery doesnt have select operation. With all respect, that really truly sucks. I know there are some concerns like live objects dont work anymore after select. But thats not my concern at all.

I am fully aware of that but currently i have to call findAll, eliminate advantage of lazy evaluation in order to get iterable source for my own queries.

also applying filters with complex conditions in to RealmQuery is hard. (pretty much impossible)

#### Describe the solution you'd like

Please provide an iterator.

**Comment by Zhuinden** [comment] 2018-11-24 13:33
I don't see how easily eager-evaluating the dataset even before the query is executed would solve any of the aforementioned problems.

Please note I'm not a member of Realm, but I've used it enough that I don't see what you're trying to achieve. 😛

**Comment by cmelchior** [comment] 2018-11-28 10:56
`findAll()` is effectively the `SELECT` of SQL. It sounds like what you want is some custom filter method which is already tracked here: https://github.com/realm/realm-java/issues/2744 

We could relatively easy make that lazy-evaluted, but it would be extremely slow as you would have to round-trip between C++ and Java for every element every time the query result is updated

Closing as a duplicate of #2744

**Closed** 2018-11-28 10:56 UTC
Labels: O:User, T:Duplicate
