### ISSUE TITLE
IllegalStateException: Primary key property 'Obj._id' has duplicate values after migration

### ISSUE THREAD

**Issue by ankursharma234** [realm/realm-java#6221] opened 2018-10-08 06:44 UTC
#### Goal
Crash Fix

#### Actual Results
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{.activity.MainActivity}: java.lang.IllegalStateException: Primary key property 'Obj._id' has duplicate values after migration.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

#### Steps & Code to Reproduce
Cant be reproduced on my side

#### Version of Realm and tooling

Realm version(s): 5.4.1

Realm Sync feature enabled: Yes

Android Studio version: Yes

Android Build Tools version: 27.0.3

Gradle version: 3.4.1

Which Android version and device(s): All

**Comment by cmelchior** [comment] 2018-10-11 13:31
Apparently, you are modifying the `_id` property or objects inside a migration which causes duplicate primary key values to appear. My guess is that you are changing the type/nullability of the field and something goes wrong while transforming values. We need to see your migration class to guess what that might be.

**Comment by ankursharma234** [comment] 2018-10-11 13:50
@cmelchior where can i drop you my migration class if not here

**Comment by cmelchior** [comment] 2018-10-11 13:51
cm@realm.io

**Comment by cmelchior** [comment] 2018-10-11 14:05
It does not appear you have any class named "Obj" in your migration, so I'm not sure where that is coming from?

**Comment by ankursharma234** [comment] 2018-10-11 14:34
No the obj was just for reference. As i was not comfortable sharing any info. But now when you my migration class i can tell you. The errors come for random objects like Invoice, CostCategory etc

**Comment by mehulsutariya** [comment] 2018-10-17 12:55
Could this be a duplicate of https://github.com/realm/realm-java/issues/5983?

**Comment by mehulsutariya** [comment] 2018-10-21 08:12
@cmelchior Any updates on this one?

**Comment by vladimirfx** [comment] 2018-10-26 10:31
Realm Java has race condition in initialization code that open native connection. I've posted example threads dump on some issues in this tracker. 
Workaround is forcibly synchronize access to Realm.getInstance() method. There is no real scalability issue on Android.

**Comment by idok595** [comment] 2018-11-04 14:09
it is also happend to 
`Caused by java.lang.IllegalStateException
Primary key property 'ProductRanking.productId' has duplicate values after migration.
io.realm.internal.OsSharedRealm.nativeGetSharedRealm (Unknown Source)
io.realm.internal.OsSharedRealm. (Unknown Source:49)
io.realm.internal.OsSharedRealm.getInstance (Unknown Source:13)
io.realm.BaseRealm. (Unknown Source:76)
io.realm.BaseRealm. (Unknown Source:4)
io.realm.Realm. (Unknown Source:12)
io.realm.Realm.createExpectedSchemaInfo (Unknown Source:2)
io.realm.RealmCache.doCreateRealmOrGetFromCacheAsync (Unknown Source:101)
io.realm.RealmCache.getCache (Unknown Source:9)
io.realm.Realm.getInstance (Unknown Source:4)`

**Comment by cmelchior** [comment] 2019-03-19 13:14
Closing due to inactivity. If this is still a problem, please an example project we can debug as all current information indicates this is a user error somewhere.

**Closed by cmelchior** 2019-03-19 13:14 UTC
Labels: O:User, Reproduction Required, T:Help
