### ISSUE TITLE
Reset password always responds with invalid token data

### ISSUE THREAD

**Issue by MarcelBreska** [realm/realm-java#7116] opened 2020-09-18 14:56 UTC
#### Goal
Reset Password with App.emailPassword.resetPasswordAsync(token, tokenId, newPassword)

#### Actual Results
Fails with the response "invalid token data". The HTTP Request show,
HTTP Request = 
    POST \*\*\*\*/auth/providers/local-userpass/reset
    Accept: application/json
    Content-Type: application/json;charset=utf-8
    Accept: application/json
    Content-Type: application/json;charset=utf-8
    {"password":"***(my_token)","token":"my_tokenId","token_id":"my_password"}

BAD_REQUEST(realm::app::ServiceError:48): invalid token data

#### Steps & Code to Reproduce
By resetting  the password the server response is alway " invalid token data". The console also shows, that the data gets mixed up. The function is declared as resetPasswordAsync(token, tokenId, newPassword) but the HTTP Request is showing, that the newPassword is set as tokenId, the token is set as password and the tokenId is the new password.
Even trying on shuffling the function values to  --- App.resetPasswordAsync(**newPassword, token, tokenId**) --- the result ist the same. Except that the HTTP Request is correct.

Request is:
{"password":"***(my_token)","token":"my_tokenId","token_id":"my_password"}

should be:

{"password":"***(my_password)","token":"my_token","token_id":"my_tokenId"}

#### Version of Realm and tooling

Realm version(s): io.realm:realm-gradle-plugin:10.0.0-BETA.7

Realm Sync feature enabled: Yes

**Comment by cmelchior** [comment] 2020-09-22 10:08
Hi @MarcelBreska Thank you. I can reproduce the problem, but there seems to be two issues here. The order of arguments are wrong as you pointed out, but even after fixing that I'm also getting "Invalid token data".

**Comment by MarcelBreska** [comment] 2020-09-22 10:25
I had the same result by switching the arguments manually. The whole authentication seems a little bit off at the moment ;) Also the login with GoogleSignIn does not work properly. See issue #7119. Facebook-Signin is working though. Looking forward for BETA.8 ;)

Thanks for looking into the issue!

**Comment by cmelchior** [comment] 2020-09-22 13:55
We discovered the root cause for this as well. We will ship a BETA.8 with fixes shortly (probably tomorrow)

**Comment by cmelchior** [comment] 2020-09-23 09:42
10.0.0-BETA.8 has been released with a fix.

**Closed by cmelchior** 2020-09-23 09:42 UTC
Labels: O-Community
