### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92

### ISSUE THREAD

**Issue by zhangningfang** [realm/realm-java#6570] opened 2019-07-29 03:51 UTC
#### Version of Realm and tooling

Realm version(s): 2.2.0

Realm Sync feature enabled: Yes/No

Android Studio version: 3.4.2

Android Build Tools version: 25.0.0

Gradle version: 2.2.2

Which Android version and device(s): Android Q

**Comment by cmelchior** [comment] 2019-07-29 06:43
Can you provide more information? Can you reproduce this?

**Comment by zhangningfang** [comment] 2019-07-29 08:42
@cmelchior 
Ok, thank you, what information do you need?

**Comment by zhangningfang** [comment] 2019-07-30 05:55
@cmelchior 
io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/Nabil/Dev/realm/master4/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:136)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:355)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
        at io.realm.Realm.getInstance(Realm.java:428)

**Comment by Zhuinden** [comment] 2019-07-30 13:07
What devices, and how?

**Comment by zhangningfang** [comment] 2019-08-26 09:33
@Zhuinden 
Sorry, for some reason, the device name is currently unavailable. I can only say that the current application is a pre-installed application, the system is Android Q, I am not sure because Q's new features or realm compatibility issues, so you need your help, thank you.

**Comment by Zhuinden** [comment] 2019-08-26 13:07
Well I'm still waiting for a Realm-Java release that includes Realm Core 5.23.2: https://github.com/realm/realm-core/blob/master/CHANGELOG.md#5232-release-notes

**Comment by zhangningfang** [comment] 2019-08-27 02:42
@Zhuinden Hi, If I integrate version 'io.realm:realm-gradle-plugin:5.14.0', does it already contain the changes in Realm Core 5.23.2 above? Thank you.

**Comment by cmelchior** [comment] 2019-09-05 13:15
Most likely this was fixed in Realm Java 5.15.0 which was just released. See https://realm.io/docs/java/latest/#huawei-permission-denied for more details.

**Closed by cmelchior** 2019-09-05 13:15 UTC
Labels: O-Community, T-Help

**Comment by zhangningfang** [comment] 2019-09-09 03:12
@cmelchior Sorry, I have used 5.15.0, it seems to have no effect, and there will still be the same problems as before.

**Comment by cmelchior** [comment] 2019-09-09 06:14
@zhangningfang Did you read the FAQ and reset the management files as suggested?

**Comment by Zhuinden** [comment] 2019-09-09 14:31
Can you actually delete the Realm management files if you don't have process-level permission to them? 🤔

**Comment by cmelchior** [comment] 2019-09-09 18:06
That is actually a good question 🤦‍♂ I should probably test that. In any case, renaming the Realm file should definitely work.

**Comment by mcydes** [comment] 2019-09-23 13:34
I have tried all three suggested solutions and none work.  Even clearing data manually still results in a crash on start up.  This is a pre-loaded application (if that helps at all).

**Comment by Zhuinden** [comment] 2019-09-23 13:36
@mcydes is it using the latest version of Realm? Because with latest, clearing data then recreating the Realm file *should* create it with correct permissions.

**Comment by mcydes** [comment] 2019-09-23 13:41
Yes, this is 5.15.

**Comment by mcydes** [comment] 2019-09-23 13:43
I also had help from the OEM who changed the file permissions to 666, but the crash persisted when trying that.

**Comment by cmelchior** [comment] 2019-09-23 13:52
Exactly what do you mean by the app being pre-loaded? Is it as systems app? or Just a normal app that is pre-installed? It sounds like something you can reproduce consistently when pre-installed?

**Comment by mcydes** [comment] 2019-09-23 14:06
pre-installed application living in the priv-app folder.  It is reproducible on some devices.

**Comment by Zhuinden** [comment] 2019-09-23 14:34
I actually just got an email to my private email asking about how on Android 10, a preinstalled app is having permission denied problems. I've redirected them over to support[at]realm.io instead.

**Comment by sarlia197** [comment] 2020-10-30 10:40
Sorry to reopen the topic. We are having the same issue with an Android TV 10 device (I cannot disclose the name). The app is also a preinstalled one with system privileges.

We are on al old version of Realm but I have tried with 5.15.0 and the issue is still present. Is there any other fix I could try? 

Regards

**Comment by andrew-samara** [comment] 2022-01-14 11:26
Hi there! Facing the same issue with realm when using this library it in priv-app signed platform key. Tested 5.15.0 and 10.5.1 versions of realm.

**Comment by andrew-samara** [comment] 2022-01-14 11:35
Hi there! 
Facing the same issue with realm when using this library it in priv-app signed platform key. 
Tested 5.15.0 and 10.5.1 versions of realm. We trying to use realm in custom Android 8.1 system build.
Steps to reproduce:
1) add realm in dependency of any application which must be system and has system privileges.
2) this application must be defined as platform in mk file:
`LOCAL_CERTIFICATE := platform
LOCAL_PRIVILEGED_MODULE := true`
3) build, and install custom Android image on a target device
4) if app launches automatically (in our case we using it in launcher, so in our case yes it launches automatically) you will get next crash:
`1-01 00:10:35.018 3415 3415 E AndroidRuntime: Process: com.watchingu.launcher, PID: 3415
01-01 00:10:35.018 3415 3415 E AndroidRuntime: io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:332)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at io.realm.Realm.getInstance(Realm.java:428)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.lokalise.sdk.Lokalise.newRealmInstance(Lokalise.kt:204)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.lokalise.sdk.Lokalise.init(Lokalise.kt:184)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.lokalise.sdk.Lokalise.init(Lokalise.kt:157)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.lokalise.sdk.Lokalise.init$default(Lokalise.kt:148)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.watchingu.nickwatch.App.initLokalise(App.kt:48)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.watchingu.nickwatch.App.onCreate(App.kt:21)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5926)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at android.app.ActivityThread.-wrap2(Unknown Source:0)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1717)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:164)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6747)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
01-01 00:10:35.018 3415 3415 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-01 00:10:35.019 3415 3415 D HprofFactory: Create HprofDebugEx
01-01 00:10:35.031  647 1839 W ActivityManager:  Force finishing activity com.watchingu.launcher/com.watchingu.launcher.activities.main.MainActivity`

**Comment by abdulhanan19** [comment] 2023-04-05 10:08
io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/jasonflax/Development/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
at io.realm.BaseRealm.<init>(BaseRealm.java:136)
at io.realm.BaseRealm.<init>(BaseRealm.java:103)
at io.realm.Realm.<init>(Realm.java:163)
at io.realm.Realm.createInstance(Realm.java:499)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:355)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
at io.realm.Realm.getDefaultInstance(Realm.java:407)
at com.app.sms.repository.ConversationRepositoryImpl.getConversations(ConversationRepositoryImpl.kt:58)
at com.app.sms.repository.ConversationRepository$DefaultImpls.getConversations$default(ConversationRepository.kt:29)
at com.app.sms.feature.main.MainViewModel.<init>(MainViewModel.kt:73)
at com.app.sms.feature.main.MainViewModel_Factory.provideInstance(MainViewModel_Factory.java:189)
at com.app.sms.feature.main.MainViewModel_Factory.get(MainViewModel_Factory.java:122)
at com.app.sms.feature.main.MainViewModel_Factory.get(MainViewModel_Factory.java:28)
at com.app.sms.feature.main.MainActivityModule_ProvideMainViewModelFactory.provideInstance(MainActivityModule_ProvideMainViewModelFactory.java:31)
at com.app.sms.feature.main.MainActivityModule_ProvideMainViewModelFactory.get(MainActivityModule_ProvideMainViewModelFactory.java:26)
at com.app.sms.feature.main.MainActivityModule_ProvideMainViewModelFactory.get(MainActivityModule_ProvideMainViewModelFactory.java:9)
at com.app.sms.common.ViewModelFactory.create(ViewModelFactory.kt:28)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:164)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:130)
at com.app.sms.feature.main.MainActivity$viewModel$2.invoke(MainActivity.kt:152)
at com.app.sms.feature.main.MainActivity$viewModel$2.invoke(MainActivity.kt:82)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.app.sms.feature.main.MainActivity.getViewModel(Unknown Source:2)
at com.app.sms.feature.main.MainActivity.onCreate(MainActivity.kt:177)
at android.app.Activity.performCreate(Activity.java:8000)
at android.app.Activity.performCreate(Activity.java:7984)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3457)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3648)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7723)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
----------------------------------------------------------------------------------------------------------------------------------------------------------------


I'm working on system default app like Messages App and all the data is sync with Realm DB. When I make my app as system default app in Custom Android OS it throws me this error every time. 

**Please Suggest me a solution for this error ?**

**Comment by abdulhanan19** [comment] 2023-04-05 10:15
### io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/jasonflax/Development/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.(OsSharedRealm.java:171)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
at io.realm.BaseRealm.(BaseRealm.java:136)
at io.realm.BaseRealm.(BaseRealm.java:103)
at io.realm.Realm.(Realm.java:163)
at io.realm.Realm.createInstance(Realm.java:499)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:355)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
at io.realm.Realm.getDefaultInstance(Realm.java:407)
at com.app.sms.repository.ConversationRepositoryImpl.getConversations(ConversationRepositoryImpl.kt:58)
at com.app.sms.repository.ConversationRepository$DefaultImpls.getConversations$default(ConversationRepository.kt:29)
at com.app.sms.feature.main.MainViewModel.(MainViewModel.kt:73)
at com.app.sms.feature.main.MainViewModel_Factory.provideInstance(MainViewModel_Factory.java:189)
at com.app.sms.feature.main.MainViewModel_Factory.get(MainViewModel_Factory.java:122)
at com.app.sms.feature.main.MainViewModel_Factory.get(MainViewModel_Factory.java:28)
at com.app.sms.feature.main.MainActivityModule_ProvideMainViewModelFactory.provideInstance(MainActivityModule_ProvideMainViewModelFactory.java:31)
at com.app.sms.feature.main.MainActivityModule_ProvideMainViewModelFactory.get(MainActivityModule_ProvideMainViewModelFactory.java:26)
at com.app.sms.feature.main.MainActivityModule_ProvideMainViewModelFactory.get(MainActivityModule_ProvideMainViewModelFactory.java:9)
at com.app.sms.common.ViewModelFactory.create(ViewModelFactory.kt:28)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:164)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:130)
at com.app.sms.feature.main.MainActivity$viewModel$2.invoke(MainActivity.kt:152)
at com.app.sms.feature.main.MainActivity$viewModel$2.invoke(MainActivity.kt:82)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.app.sms.feature.main.MainActivity.getViewModel(Unknown Source:2)
at com.app.sms.feature.main.MainActivity.onCreate(MainActivity.kt:177)
at android.app.Activity.performCreate(Activity.java:8000)
at android.app.Activity.performCreate(Activity.java:7984)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3457)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3648)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7723)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

I'm working on system default app like Messages App and all the data is sync with Realm DB. When I make my app as system default app in Custom Android OS it throws me this error every time.

Please Suggest me a solution for this error ?
