### ISSUE TITLE
service thread realm not update realm object

### ISSUE THREAD

**Issue by tonyshare** [realm/realm-java#3375] opened 2016-09-01 01:12 UTC
background:
     app save the realm object in activity  occasionally, and found the object was saved.
     in android service class, there is a timer, every minute get an realm instance  and check whether the realm object has been saved, if there is new, send it to web server, and close the realm instance. waiting for next turn.

problem:
        in  service class first get the realm instance and found five realm object. next turn  will also be the first time found five object, even if the activity saved ten new realm object.

**Comment by zaki50** [comment] 2016-09-01 02:38
Hi @tonyshare 

Does Your thread in the `Service` have a `Looper`?
If yes, you can see the changes from UI thread in next looper event.
And if you are using `IntentService` (worker thread of `IntentService` has a `Looper`),
you can't get updated data since there is no *Next* looper event in `IntentService#onHandleIntent()`.

If your thread does not have a `Looper`, please invoke `Realm#waitForChange()` before checking the data.

**Comment by tonyshare** [comment] 2016-09-01 02:50
Thanks for your help, the service does not have looper, if i use the waitforchage() manner, it does get the new object ,but it will block my service thread , in service i also have other things to do, in realm doc, it says that in thread instance you can read the new data without worry about any thing, why every time i get a new instance but it can not get the update objcet?
realm says:"The key takeaway here is that Realm makes it effortless to work with data on multiple threads without having to worry about consistency or performance because objects and queries are auto-updating at all times."

**Comment by Zhuinden** [comment] 2016-09-01 03:56
Do you guarantee that you **always** close the Realm instance in your Service?

Opening an instance of the Realm on the service pins the version unless you close it.

**Comment by tonyshare** [comment] 2016-09-01 06:14
in my `service` program, there is only one time i opening the instance ,after that  i closed the instance.

**Comment by zaki50** [comment] 2016-09-01 06:19
Realm's data is versioned and each thread is managing which version to be seen.

When the Realm instance is created on each thread, it points to the latest version at that time.
After that, Realm advances the version in following cases.

* between Looper events
* `waitForChange()`
* opening the transaction
* some other sync API

So, I think you can take one of two ways.

One is that you open and close Realm each time you check the latest data. This is recommended way but it works only if you don't open and keep other Realm instance in the thread.

Another way that you execute empty transaction every time before you check the data.

**Comment by tonyshare** [comment] 2016-09-01 06:23
thanks for your help ,i will try the empty transaction, after that i will feedback the result.

**Comment by Zhuinden** [comment] 2016-09-01 06:40
Personally what I would do in your case is begin transaction to force seeing the latest version with `realm.beginTransaction()`, and at the end of what you're doing call `realm.cancelTransaction()`.

Or [force refresh with this workaround  (works for 1.1.1 and 1.2.0) after `Realm.getInstance()`](http://stackoverflow.com/a/38839808/2413303)

**Comment by beeender** [comment] 2016-09-01 06:47
@tonyshare It is really strange that reopen Realm instance doesn't move the version to the latest. If you can reproduce is with a sample project, i'd be happy to take a look.

Also, if reopening doesn't work, mostly it means some Realm instance is leaked. instead of hacking with a empty transaction, better to figure out the root cause.

**Comment by Zhuinden** [comment] 2016-09-01 06:58
Personally I think the issue is that the Realm instance was opened BEFORE the Activity added the new items, so beginning and canceling a transaction should override this race condition.

**Comment by beeender** [comment] 2016-09-01 07:01
"Realm instance was opened BEFORE the Activity added the new items" if that is the case, empty transaction won't really solve it since the `beginTransaction` could still be called before the activity change the data ...

@tonyshare To make sure, your service is not running on the main thread, right? (I saw you mentioned it doesn't have a loop, i just want to double check it :) )

**Comment by tonyshare** [comment] 2016-09-01 07:30
my `service class` is used to connect to the web server , it extends from the android `service`,  i used `AIDL` to communicate between `activity` and `service`, i try to use `isautorefresh()`, the system tell me that the service is not in the `looper` thread.

**Comment by beeender** [comment] 2016-09-01 07:52
@tonyshare One question, how do you notify the service when the data changed in the activity?

**Comment by tonyshare** [comment] 2016-09-01 07:54
@beeender  In the `service` has a `Timer`, it run the task every minute.

**Comment by beeender** [comment] 2016-09-01 07:57
@tonyshare So it means, it will NOT be guaranteed when the timeout happens, the data is changed, right?

**Comment by tonyshare** [comment] 2016-09-01 08:01
@beeender yes i hope if data was change i can send it to web server, and also if there is new data from server , it can auto download from the web service.

**Comment by beeender** [comment] 2016-09-01 08:10
@tonyshare I would like to handle the receiving/sending in two thread. And the sending thread can have a looper(or maybe `waitForChange()` for non-looper thread) then you can benefit from Realm's notifications.

But if you really want to handle receiving/sending in the same thread with a timer, consider to use the lock comes with Realm's transaction and an additional flag object in Realm, something like:

// In your service
```
realm.beginTransaction(); // Transaction will be blocked in other thread
Flag flag = realm.where(Flag.class).findFirst();
if (flag.getChanged() == true) {
    flag.setChanged(false);
    // Send your data to server.
}
realm.commitTransaction();
```


// In your activity
```
realm.beginTransaction(); // Transaction will be blocked in other thread
// Change your data here.
Flag flag = realm.where(Flag.class).findFirst();
flag.setChanged(false);
realm.commitTransaction();
```

But, yeah, it would be much convenient if there is a `Realm.isChanged()` and `Realm.refresh()` in this case.

**Comment by tonyshare** [comment] 2016-09-01 08:26
@beeender thanks for you help. i can use `AIDL` to communicate between `acitive` and `service`, that is very convenient. but the service run all the time, so i can use it to automatically manage data  for app, even if the activity has gone.

**Comment by beeender** [comment] 2016-09-01 08:30
"i can use AIDL to communicate between acitive and service" in this case, after activity notify service that data changes, reopen the Realm should just get the latest data.

So I am closing this issue now. Feel free to reopen it if you still have further questions about this.

**Comment by tonyshare** [comment] 2016-09-01 08:32
the studio in not in my hand now , after several hour i will feedback the result

**Comment by beeender** [comment] 2016-09-01 08:34
OK, then i can just keep it open for a longer time :)

**Comment by tonyshare** [comment] 2016-09-01 10:03
@zaki50 after an empty transaction 👍 
```
realm.beginTransaction();
realm.commitTransaction();
```
i solve the problem,

@Zhuinden the [solution](http://stackoverflow.com/a/38839808/2413303) you mentioned, i tried the studio said that the `realm.handlerController` is not public can not be accessed.

@beeender if really interested in this example i will make an example after a week.

thanks all of you.

**Comment by Zhuinden** [comment] 2016-09-01 10:41
The `package io.realm;` part was kinda important in that answer

**Comment by tonyshare** [comment] 2016-09-01 11:35
@zaki50 I put  code in the  `package io.realm` , and this solution can also solve my problem thanks

**Comment by Zhuinden** [comment] 2016-09-01 11:40
I think it's a cleaner solution than committing an empty transaction. 

We'll need to adapt some changes when 2.0.0. comes out though, but hey :smile:

**Comment by zaki50** [comment] 2016-09-01 12:15
I don't recommend to touch internal thing.
Please note that internal implementation might change without prior notie.
Anyway I'll close this issue.

Please feel free to reopen this if you have further questions.

**Closed by zaki50** 2016-09-01 12:15 UTC
Labels: T:Help

**Comment by Zhuinden** [comment] 2016-09-01 12:17
Personally I think it's strange that even after closing and then re-opening the Realm, the instance on that given thread doesn't update its version, and that manual refresh is required.

Shouldn't it update version if you open all realms, close all realms, and then open a new realm?

**Comment by Zhuinden** [comment] 2016-09-01 12:32
In that case I'm not entirely sure that this is solved. Manual refresh is a work-around, a sample that reproduces the issue would be needed.
