### ISSUE TITLE
a NullPointerExpection came out when I call Realm.close

### ISSUE THREAD

**Issue by eeoa** [realm/realm-java#1241] opened 2015-06-25 07:18 UTC
My Realm version is 0.81.1 and the log is 

java.lang.NullPointerExcepiton
at io.realm.Realm.close(REalm.java:243)
at com.cdv.myshare.uploadservice.PreUploadService.commonCommand(PreUploadService.java:413)

The I call Realm.getDefaultInstance() to get the Realm object and it worked fine.But when I closed it , a 
NullPointerExpection would come out occasionally.

**Comment by eeoa** [comment] 2015-06-25 07:40
In my Application class ,I have set default configuration like 

	public void onCreate() {

		RealmConfiguration config = new RealmConfiguration.Builder(this)
				.build();
		Realm.setDefaultConfiguration(config);

		super.onCreate();
	}

**Comment by beeender** [comment] 2015-06-26 02:25
Hi!
Is there any chance you created Realm instance in ThreadA but tried to close it in Thread B?

**Comment by eeoa** [comment] 2015-06-26 03:07
I create and close Realm instance in a function and I don't pass it to another thread exactly.

**Comment by beeender** [comment] 2015-06-26 03:10
Would you mind to share the function code you create/close the realm?

**Comment by eeoa** [comment] 2015-06-26 04:28
A few days ago I updated Realm to  0.81.1  and these NullPointerExpection came out. Before the upadating ,my functions worked well .

Now the NullPointerExpection came out in more than one function occasionally. one of these functions is 

		private boolean refreshProgress(Realm db) {

			boolean changed = false;
			boolean alive = false;

			DataProvider dataProvider = DataProvider.getInstance(activity);

			Map<String, Task> tasks = new HashMap<String, Task>();

			for (Task task : dataProvider.getTasks()) {
				tasks.put(task.getWorkID(), task);
			}

			RealmResults<Link> linkResults = null;
			
			if (TextUtils.isEmpty(activityID)) {
				linkResults = db.where(Link.class).equalTo("failure", false)
						.findAllSorted("timeStamp");
			} else {
				linkResults = db.where(Link.class).equalTo("failure", false)
						.equalTo("activityID", activityID)
						.findAllSorted("timeStamp");
			}

			for (int i = 0; i < linkResults.size(); i++) {

				Link link = linkResults.get(i);

				if (!link.isValid()) {
					continue;
				}

				Task task = tasks.get(link.getLinkID());

				if (task == null) {
					continue;
				}

				if (Link.isFailure(link)) {
					if (!task.isFailure()) {
						changed = true;
					}
					task.setFailure(true);
					continue;
				}
				
				alive = true;

				int newProgress = Link.getProgress(link);

				if (newProgress != task.getProgress()) {
					task.setProgress(newProgress);
					changed = true;
				}
			}

			if (!alive) {
				CDVLog.d(tag, "timer stop!");
				stop();
			}

			return changed;
		}

		@Override
		public void run() {

			CDVLog.d(tag, "timer start!");

			Realm db = Realm.getInstance(activity);

			boolean changed = refreshProgress(db);

			db.close();

			if (changed) {
				activity.runOnUiThread(new Runnable() {
					@Override
					public void run() {
						adapter.notifyDataSetChanged();
					}
				});
			}
		}

**Comment by eeoa** [comment] 2015-06-26 04:33
The  static Link.getProgress(Link link) function is 

	private static class WorkCapacity {
		public WorkCapacity(long totalWorkCapacity, long finishedWorkCapacity) {
			this.totalWorkCapacity = totalWorkCapacity;
			this.finishedWorkCapacity = finishedWorkCapacity;
		}

		public long totalWorkCapacity;
		public long finishedWorkCapacity;
	}

	private static WorkCapacity getWorkCapacity(Link link) {

		RealmList<Asset> list = link.getAssetList();

		long totalWorkCapacity = 0;
		long finishedWorkCapacity = 0;

		Asset thumb = link.getThumbAsset();
		Asset bgm = link.getBgm();

		if (thumb != null) {
			totalWorkCapacity += thumb.getPreUploadTotalWorkCapacity()
					+ thumb.getUploadTotalWorkCapacity();
			finishedWorkCapacity += thumb.getPreUplaodFinishedWorkCapacity()
					+ thumb.getUploadFinishedWorkCapacity();
		}
		if (bgm != null) {
			totalWorkCapacity += bgm.getPreUploadTotalWorkCapacity()
					+ bgm.getUploadTotalWorkCapacity();
			finishedWorkCapacity += bgm.getPreUplaodFinishedWorkCapacity()
					+ bgm.getUploadFinishedWorkCapacity();
		}
		for (Asset asset : list) {

			if (asset.getAssetID().equals(thumb.getAssetID())) {
				continue;
			}

			totalWorkCapacity += asset.getPreUploadTotalWorkCapacity()
					+ asset.getUploadTotalWorkCapacity();
			finishedWorkCapacity += asset.getPreUplaodFinishedWorkCapacity()
					+ asset.getUploadFinishedWorkCapacity();
		}

		return new WorkCapacity(totalWorkCapacity, finishedWorkCapacity);

	}

	public static int getProgress(Link link) {

		int progress = 0;

		if (!link.isValid()) {
			progress = 0;
		} else {

			if (link.getState() == Utilities.LinkState.REGESTING) {
				progress = +4;
			}

			WorkCapacity capacity = getWorkCapacity(link);

			if (capacity.totalWorkCapacity != 0) {
				progress += (int) ((92 * capacity.finishedWorkCapacity) / capacity.totalWorkCapacity);
			}

			if (link.getViewType().equalsIgnoreCase(
					PlatformAPI.ViewType.USERONLY) == false) {
				progress /= 2;
			}
		}

		return progress;
	}

**Comment by eeoa** [comment] 2015-06-26 04:40
I changed Realm.getDefaultInstance() to Real.getInstance(Context) but it can't stop the NullPointerExpection.

**Comment by eeoa** [comment] 2015-06-26 07:07
I will update to 0.81.2 and give you more feedback.

**Comment by beeender** [comment] 2015-06-26 07:11
@eeoa It might not fix your problem. But if you do have multiple instances on different threads, it might worth a try. 
If you have time, no need waiting for the release, the Realm is quite easy to compile the Realm.
You can find a README in the root of realm-java repo.

Thanks!

**Comment by eeoa** [comment] 2015-06-26 07:15
I got your point. I will add this cheking in close() and watch whether a INCORRECT_THREAD_CLOSE_MESSAGE will be throwed.

**Comment by eeoa** [comment] 2015-06-26 07:18
I am in windows and develop with eclispe android bundle. I don't sure I can buid Realm. I will try anyway.

**Comment by ahmedre** [comment] 2015-06-26 19:15
also have the same problem, i filed #1247 earlier (before seeing this), but perhaps devs can take a look at it in case it provides any additional information. in my case, i am opening and closing on the same thread (code provided in #1247 which i closed as a dup of this one).

**Comment by beeender** [comment] 2015-06-28 15:36
We still cannot reproduce this problem.
@eeoa Is this problem 100% reproducible to you?
 Is it possible to share your project privately to help@realm.io ?

**Comment by eeoa** [comment] 2015-06-29 01:39
The problem is not 100% reproducible, just reproducible.
Sorry I can not give my project because it's a huge one and it is belong to the company which employs me.

I will try to compile Realm, test more and give you more feedback.

Thank you.

**Comment by beeender** [comment] 2015-06-29 13:07
#1245 has been merged, would you please help to verify if it can fix your problem?
Thanks!

**Comment by eeoa** [comment] 2015-06-30 03:14
I'm so sorry but I am in China mainland and there are many limitations about internet. I try to build Realm in many ways in these two days but I must admit I can not get it . I can't access google.com gradle.org and even realm.io smoothly  so can't get necessary files.

So could you help me build a new version Realm?  I 've run out of ideas!
Thank you!

**Comment by beeender** [comment] 2015-06-30 03:22
@eeoa Can you please send your contact information to my email? mc@realm.io . I would be very happy to help and talk to users from China mainland!

**Comment by eeoa** [comment] 2015-07-01 01:21
I have updated Realm to latest version. I need some time to test it and if I have some result I will give you feedback.

**Comment by ypresto** [comment] 2015-07-02 02:43
Same issue with realm-android:0.81.1.

```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.concurrent.atomic.AtomicInteger.decrementAndGet()' on a null object reference
            at io.realm.Realm.close(Realm.java:243)
            ... (our classes) ...
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by beeender** [comment] 2015-07-02 05:17
@ypresto A fix #1245  has been merged. If you want, you can test it with our snapshot or compile from the master.
Thanks!

**Comment by eeoa** [comment] 2015-07-06 06:25
Hi . I have tested the version that you give to me for a few days .Although I'm not sure whether this fix can fix this bug , but these days such problems didn't came out again. I think the fix should be useful any way.

**Comment by beeender** [comment] 2015-07-06 06:50
Thanks a lot for your feedback again!

I am closing this bug now. If it happened again, feel free to reopen it.

**Closed by beeender** 2015-07-06 06:50 UTC
Labels: bug
