### ISSUE TITLE
Many crashes for 4.2.0

### ISSUE THREAD

**Issue by youbing** [realm/realm-java#5932] opened 2018-05-08 08:13 UTC
#### Actual Results

io.realm.exceptions.RealmError: 
  at io.realm.internal.OsSharedRealm.nativeGetSharedRealm (Native Method)
  at io.realm.internal.OsSharedRealm.<init> (SourceFile:172)
  at io.realm.internal.OsSharedRealm.getInstance (SourceFile:219)
  at io.realm.internal.OsSharedRealm.getInstance (SourceFile:209)
  at io.realm.m.b (SourceFile:319)
  at io.realm.m.a (SourceFile:282)
  at io.realm.Realm.getDefaultInstance (SourceFile:332)
  at com.easilydo.mail.dal.DB.open (SourceFile:132)
  at com.easilydo.mail.dal.DB.<init> (SourceFile:89)
  at com.easilydo.mail.dal.EmailDB.<init> (SourceFile:32)
  at com.easilydo.mail.contact.GmailContactSyncOp.preProcess (SourceFile:62)
  at com.easilydo.mail.core.BaseOperation.start (SourceFile:154)
  at com.easilydo.mail.core.OperationEngine$3.run (SourceFile:352)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)

#### Steps & Code to Reproduce

It is hard to reproduce. But our users report it many times and Google Play records the log many times.

#### Version of Realm and tooling
Realm version(s): 
4.2.0

Realm sync feature enabled: 
no

Android Studio version: 
3.1.0

Which Android version and device:
Samsung Galaxy S8+ (dream2qltesq), 4096MB RAM, Android 8.0

**Comment by cmelchior** [comment] 2018-05-08 09:38
Duplicate of #5933

**Closed by cmelchior** 2018-05-08 09:38 UTC
