### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#2640] opened 2016-04-22 01:34 UTC
```
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.dante.knowledge-2/lib/arm/librealm-jni.so" has unexpected e_machine: 40
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:988)
	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:117)
	at io.realm.internal.SharedGroup.<clinit>(SharedGroup.java:42)
	at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:43)
	at io.realm.BaseRealm.<init>(BaseRealm.java:76)
	at io.realm.Realm.<init>(Realm.java:126)
	at io.realm.Realm.createAndValidate(Realm.java:246)
	at io.realm.Realm.createInstance(Realm.java:231)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
	at io.realm.Realm.getDefaultInstance(Realm.java:181)
	at com.dante.knowledge.ui.BaseActivity.initViews(BaseActivity.java:44)
	at com.dante.knowledge.MainActivity.initViews(MainActivity.java:55)
	at com.dante.knowledge.ui.BaseActivity.onCreate(BaseActivity.java:33)
	at android.app.Activity.performCreate(Activity.java:5990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
I don't even know why Realm has so many bugs...(I still love to use it, however)

**Comment by DanteAndroid** [comment] 2016-04-22 01:36
Here is [BaseActivity#line-44](https://github.com/DanteAndroid/Knowledge/blob/master/app/src/main/java/com/dante/knowledge/ui/BaseActivity.java#line-44)

**Comment by beeender** [comment] 2016-04-22 02:10
I guess you are running the app on the x86 based tablet? If yes, check this answer
http://stackoverflow.com/questions/27754468/running-android-native-code-is-causing-java-lang-unsatisfiedlinkerror

> I don't even know why Realm has so many bugs...(I still love to use it, however)
If you consider all your questions as Realm's bugs, that would hurt us a lot :cry:

**Comment by DanteAndroid** [comment] 2016-04-22 02:15
@beeender I'm not sure, what I received is the device information:
` android 5.1 (22)，generic:Google Nexus 5 - 5.1.0 - API 22 - 1080x1920:armeabi-v7a`
Maybe that is just an emulator?
I recall my word. Love you guys. Maybe just because my code sucks :P

**Comment by beeender** [comment] 2016-04-22 02:18
Google's arm emulator? Is it something you can reproduce or it is a crash has been seen in the crash log server? Did you exclude some of the Realm's so in your gradle file? On that device, it should look for `armeabi-v7a` so first.

**Comment by beeender** [comment] 2016-04-22 02:25
Also check those thread
https://code.google.com/p/android/issues/detail?id=82207

Can you see more information about the device? That could be a Relinker's issue or the emulator reporting a wrong ABI.

**Comment by DanteAndroid** [comment] 2016-04-22 02:45
1. It's in the log server
2. No
3. 
```
 android 5.1 (22)，generic:Google Nexus 5 - 5.1.0 - API 22 - 1080x1920:armeabi-v7a
FreeSpace：1696.00MB，Used：308.38MB
"WiredSSID"
 0%，Unplugged
Rooted
```

**Comment by stk1m1** [comment] 2016-04-22 02:55
Hi @DanteAndroid 

Could you share us a sample that leads to the problem you're experiencing please?

**Comment by DanteAndroid** [comment] 2016-04-22 03:39
@stk1m1 I'm sorry, I just received from the server, don't know how to reproduce.

**Comment by stk1m1** [comment] 2016-04-22 07:56
Hi @DanteAndroid 

I've just checked your repository, and there are two noticible patterns demonstrated in your codebase.

1. **`DB` and `ZhihuModel` still create a Realm instance on their own**. Please remove those instantiations, and follow the lifecycle guideline we prepared for you.
2. **In `FetchService`, there is a static realm instance that could be referred from any thread**. Realm is very carefully designed to provide maximum performance in a multi-threaded environment. One realm instance is allowed per a thread and It is not a promoted practice to share a Realm instance across threads. It is clear that you're trying to save data to Realm in background `FetchService`. If that's the case, please create a realm instance only when it is necessary, then close it as soon as save task is completed.

I would encourage you to read our document and follow the best practices. :smiley:

**Comment by DanteAndroid** [comment] 2016-04-22 08:04
@stk1m1 
1. what do you mean "DB and ZhihuModel still create a Realm instance on their own", I have deleted Realm instance in DB, did I do that in dream? :(
2. FetchService, **I forget realm in it :P** I don't know what to say, you're so warm-hearted.

**Comment by stk1m1** [comment] 2016-04-22 08:12
Hi @DanteAndroid 

[Here](https://github.com/DanteAndroid/Knowledge/blob/d4d257a42771890de285665ca145f1d063304809/app/src/main/java/com/dante/knowledge/net/DB.java#L42) in `DB.java`, and [there](https://github.com/DanteAndroid/Knowledge/blob/6916db5d51aa3539ff51871d3e18ac9e31375bc0/app/src/main/java/com/dante/knowledge/mvp/model/ZhihuModel.java#L78) in `ZhihuModel.java`.

Hope this helps.

**Comment by DanteAndroid** [comment] 2016-04-22 08:23
@stk1m1 I finally realize my fault is trying to make realm simple, but obviously realm is not designed to be static as you said that, 
>Realm is very carefully designed to provide maximum performance in a multi-threaded environment
Could realm be accessed in multi-threaded more easy to use?How much impact would be on realm's efficiency?

**Comment by stk1m1** [comment] 2016-04-22 10:26
@DanteAndroid 

[Realm Java](https://github.com/realm/realm-java) has evolved based on our core value and feedback from community. Although we appreciate your input and it will be considered carefully, what you're pointing isn't something we can put in our production pipeline right away. I encourage you to consider the fact that there are many who have unspoken but happily provided Realm to millions of their users.

I will close this issue as of now.

**Comment by beeender** [comment] 2016-04-22 10:41
UH, let's talk something related with the original topic of this thread.

@DanteAndroid I could reproduce your issue on genymotion. Genymotion has some feature called ARM translation, it would translate ARM code to x86 code on x86 device. Install instructions can be found here http://www.techbae.com/download-install-arm-translation-v1-1-zip-genymotion/

To reproduce the issue, create a project with Realm, and exclude x86 so by:
```
packagingOptions {
        exclude "lib/x86_64/librealm-jni.so"
        exclude "lib/x86/librealm-jni.so"
    }
```

Then Genymotion will try to load the ARM lib since it thinks it could translate it. But however, it has bug which will throw the excpetion "has unexpected e_machine: 40". I would say it is the ARM translation bug :smiley:  

Similar bug can be see here https://groups.google.com/forum/#!topic/android-x86/xyTpnuSy8rI

The solution is just pack the x86 so with you apk if you want to support this kind of case.

**But if your case is different from what I described above, please let me know. I will check if it is an different issue.**

______________________

BTW, about the "Realm instance has already been closed." issue, i reopened #2594, let's discuss there since too much discussion here will pollute this thread :grin: Please let me know how to reproduce the issue and i will check.

**Comment by DanteAndroid** [comment] 2016-04-22 12:40
@beeender Do you mean realm running on Genymotion MUST throw that exception? Coz I run it perfectly before.

**Comment by beeender** [comment] 2016-04-24 06:08
@DanteAndroid No. As I said above, i could reproduce this issue on genymotion with two preconditions:
1. Install ARM translation on Genymotion
2. Excluding Realm x86 libs in the gradle file

**Closed** 2016-04-27 07:57 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help

**Comment by beeender** [comment] 2016-05-05 04:48
One more note, after installing ARM translation on genymotion, the apk split doesn't install the proper apk to genymotion in AS. It should just install x86 apk, but arm apk will be installed instead which will cause this issue as well. Might be an AS bug or Genymotion reporting a wrong arch in this case.

**Comment by DanteAndroid** [comment] 2016-05-05 05:21
@beeender That helps a lot. I don't encounter this problem anymore.
