### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by adaonder** [realm/realm-java#7765] opened 2023-02-08 20:10 UTC
### How frequently does the bug occur?

Always

### Description

Download https://jcenter.bintray.com/io/realm/realm-gradle-plugin/10.13.2-transformer-api/realm-gradle-plugin-10.13.2-transformer-api.pom, took 383 ms (2.38 kB)
Download https://jcenter.bintray.com/io/realm/realm-gradle-plugin/10.13.2-transformer-api/realm-gradle-plugin-10.13.2-transformer-api.module, took 323 ms (4.68 kB)
Download https://jcenter.bintray.com/io/realm/realm-transformer/10.13.2-transformer-api/realm-transformer-10.13.2-transformer-api.pom, took 265 ms (2.73 kB)
Download https://jcenter.bintray.com/io/realm/realm-transformer/10.13.2-transformer-api/realm-transformer-10.13.2-transformer-api.module, took 404 ms (4.76 kB)
Download https://jcenter.bintray.com/io/realm/realm-annotations/10.13.2-transformer-api/realm-annotations-10.13.2-transformer-api.pom, took 217 ms (1.76 kB)
Download https://jcenter.bintray.com/io/realm/realm-annotations/10.13.2-transformer-api/realm-annotations-10.13.2-transformer-api.module, took 223 ms (3.68 kB)
Download https://jcenter.bintray.com/io/realm/realm-gradle-plugin/10.13.2-transformer-api/realm-gradle-plugin-10.13.2-transformer-api.jar, took 259 ms (16.09 kB)
Download https://jcenter.bintray.com/io/realm/realm-annotations/10.13.2-transformer-api/realm-annotations-10.13.2-transformer-api.jar, took 287 ms (5.25 kB)
Download https://jcenter.bintray.com/io/realm/realm-transformer/10.13.2-transformer-api/realm-transformer-10.13.2-transformer-api.jar, took 525 ms (75.4 kB)
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Download https://jcenter.bintray.com/io/realm/realm-gradle-plugin/10.13.2-transformer-api/realm-gradle-plugin-10.13.2-transformer-api-sources.jar, took 335 ms (4.73 kB)
Download https://jcenter.bintray.com/io/realm/realm-transformer/10.13.2-transformer-api/realm-transformer-10.13.2-transformer-api-sources.jar, took 251 ms (24.94 kB)
Download https://jcenter.bintray.com/io/realm/realm-annotations/10.13.2-transformer-api/realm-annotations-10.13.2-transformer-api-sources.jar, took 316 ms (13.92 kB)
Download https://jcenter.bintray.com/io/realm/realm-android-library/10.13.2-transformer-api/realm-android-library-10.13.2-transformer-api.pom, took 409 ms (2.7 kB)
Download https://jcenter.bintray.com/io/realm/realm-android-library/10.13.2-transformer-api/realm-android-library-10.13.2-transformer-api.aar, took 38 s 623 ms (11.89 MB)
Download https://jcenter.bintray.com/io/realm/realm-android-library/10.13.2-transformer-api/realm-android-library-10.13.2-transformer-api-sources.jar, took 1 s 174 ms (547.5 kB)
Download https://jcenter.bintray.com/io/realm/realm-android-library/10.13.2-transformer-api/realm-android-library-10.13.2-transformer-api-javadoc.jar, took 2 s 778 ms (1.23 MB)
Download https://jcenter.bintray.com/io/realm/realm-annotations/10.13.2-transformer-api/realm-annotations-10.13.2-transformer-api-javadoc.jar, took 1 s 168 ms (309.15 kB)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 2s

### Stacktrace & log output

```shell
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
```

### Can you reproduce the bug?

Always

### Version

10.13.2-transformer-api

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

android 9

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by cmelchior** [comment] 2023-02-13 09:52
Hi @adaonder. Thank you for the report.  We are aware that Gradle 8 is bringing some breaking changes and we will make sure that our plugin also works with Gradle 8, but we do not have a deadline for that work to be complete just yet.

**Comment by adaonder** [comment] 2023-02-13 09:57
@cmelchior Thank you for the answer. Waiting for New Update :)

**Comment by edualonso** [comment] 2023-02-20 11:35
We have created an umbrella ticket for all things related to Gradle 8.0. Please track progress here https://github.com/realm/realm-java/issues/7773

**Comment by rorbech** [comment] 2023-03-23 10:00
@adaonder I tried doing a new android project with the referenced Realm Java version, but I am not able to reproduce the warnings that you are listing. Would you be able to share some more details of the setup triggering this, especially:
- Gradle version
- Android Build Tools version
- And other important configuration that is needed to trigger this.

**Comment by BlueCobold** [comment] 2023-03-29 06:20
It's surely happening to as well using
```
 distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
 
classpath 'com.android.tools.build:gradle:7.3.1'
```

**Comment by rorbech** [comment] 2023-03-29 07:54
@BlueCobold There has been a major update to the transformer API in the Android Gradle Plugin and the old APIs will be deleted from AGP 8.x. We have created a feature release (`transformer-api`) that supports the new API from AGP 7.4, but will have to drop backward compatibility below AGP 7.4 when we promote this as the main release. So we wont fix the warnings in the non-transformer-api releases.

But, that said, I also cannot reproduce the issue with the Gradle and Android Gradle Plugin versions that you are supplying, so maybe I am missing something in my setup. Do you mind sharing a sample project that reproduces the issue or at least 
- The realm version used, and
- And the configuration that is needed to trigger this.

**Comment by BlueCobold** [comment] 2023-03-29 08:07
Realm version is 10.13.1. Did you try building an AAB? That's when I receive this and similar warnings, even after upgrading gradle and the plugin to 7.4.x.

**Comment by rorbech** [comment] 2023-03-29 08:28
@BlueCobold I also don't see any of the mentioned warnings when I build a bundle. The only warnings I get when using your versions are the ones about using the deprecated transform APIs which is address by the `transformer-api` release.

Again, it would be very helpfull if you could supply a configuration that exhibits this.

**Comment by BlueCobold** [comment] 2023-03-29 08:47
I will see if I can provide a minimal sample, but it's not my personal priority and I'm not the OP, so can't predict any date or time yet.

**Closed** 2023-05-30 00:18 UTC
Labels: T-Bug, Reproduction-Required, O-Community, More-information-needed, Waiting-For-Reporter, Frequency:Always, Repro:Always, SDK-Use:Local, Encryption:Off
