### ISSUE TITLE
How to watch my realm data as with stetho implementation i reach till inspect data but realm db not open.How to check my complete data in windows

### ISSUE THREAD

**Issue by devvishal06** [realm/realm-java#3465] opened 2016-09-19 09:27 UTC
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment] 2016-09-19 09:30
Duplicate of https://github.com/realm/realm-java/issues/3463

**Comment by kneth** [comment] 2016-09-29 09:27
@devvishal06 Did you get it to work by following the instructions?

**Comment by zaki50** [comment] 2016-10-03 11:39
I've released `Stetho-Realm 2.0.0` which supports Realm-Java 2.0.0.
If you are using Realm Java 2.0.0, please try the latest version of `Stetho-Realm`.
If you are using Realm Java 1.2.0 or older, please use `Stetho-Realm 0.9.0`.

**Closed** 2016-10-11 10:44 UTC
Labels: S:Waiting For User, T:Help

**Comment by Shubhampatni86** [comment] 2017-03-22 11:27
I tried this but it simply showing me same old view for SQlite DB, nothing related with Realm DB. PFA. Any suggestion ?
<img width="502" alt="stetho_realm" src="https://cloud.githubusercontent.com/assets/825165/24195634/8278fee8-0f20-11e7-9d11-eb04bb7b66b4.png">

**Comment by kneth** [comment] 2017-03-22 13:07
@Shubhampatni86 You might have more luck opening an issue at https://github.com/uPhyca/stetho-realm.

@zaki50 Do you have any suggestions?
