### ISSUE TITLE
Using the same model name in app and library causes ClassCastException: io.realm.UserRealmProxy

### ISSUE THREAD

**Issue by MariusBoepple** [realm/realm-java#4299] opened 2017-03-08 08:02 UTC
#### Goal

Using two different models with the same name (e.g. `User`) in a library and in the app itself.

#### Expected Results

There is no problem.

#### Actual Results

There is just one proxy class generated for the app's model (`UserRealmProxy`). So I get the following exception if I try creating a new `User` in the library:
```
Process: com.example.app:remote, PID: 32686
    java.lang.ClassCastException: io.realm.UserRealmProxy cannot be cast to com.example.library.model.User
    at java.lang.Class.cast(Class.java:1511)
    at io.realm.LibraryModuleMediator.newInstance(LibraryModuleMediator.java:163)
    at io.realm.BaseRealm.get(BaseRealm.java:499)
    at io.realm.Realm.createObjectInternal(Realm.java:915)
    at io.realm.Realm.createObject(Realm.java:891)
    at com.example.library.data.DataBaseController$9.execute(DataBaseController.java:445)
    at io.realm.Realm.executeTransaction(Realm.java:1325)
    at com.example.library.data.DataBaseController.createOrUpdateCar(DataBaseController.java:436)
    at com.example.library.MyService$1$30.run(MyService.java:1069)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

#### Version of Realm and tooling
Realm version(s): `3.0.0`

Realm sync feature enabled: no

Android Studio version: `2.3`

**Comment by MariusBoepple** [comment] 2017-03-08 08:15
Same thing for Modules I guess.

**Comment by MariusBoepple** [comment] 2017-03-08 08:21
Wouldn't it be better to include the package in the generated class names? At least for libraries.

**Comment by cmelchior** [comment] 2017-03-08 09:11
Yes, that is unfortunately a limitation right now. I can see it isn't listed under current limitations, so we should fix that. We are tracking a request that allows you to specify a different name used by Realm: https://github.com/realm/realm-java/issues/2476. This would also solve your issue.

The underlying problem is that the class name is also the name used in the underlying tables to store data and the name there has to be cross-platform compatible. So prefixing with the package name is not really an option.

I'll close this as an duplicate of #2476

**Closed** 2017-03-08 09:12 UTC

**Comment by Zhuinden** [comment] 2017-03-08 13:00
The underlying schema table name is `class_{ClassSimpleName}` therefore User and User will map to the same schema table

**Comment by MariusBoepple** [comment] 2017-03-08 13:23
Yeah I renamed one of them but that could not be the solution in the long run...
