### ISSUE TITLE
Realm is probably triggering off a lot of blocking GCs

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1925] opened 2015-12-10 06:08 UTC
I am seeing a lot of explicitly triggered blocking GCs in Logcat in my app when inserting new items to the database. 

    12-10 11:33:25.874 7555-7555/com.tattva.app I/art: Starting a blocking GC Explicit
    12-10 11:33:25.955 7555-7561/com.tattva.app W/art: Suspending all threads took: 47.502ms
    12-10 11:33:25.961 7555-7555/com.tattva.app I/art: Explicit concurrent mark sweep GC freed 54692(2MB) AllocSpace objects, 30(1512KB) LOS objects, 40% free, 18MB/30MB, paused 1.205ms total 79.991ms

Is this normal? I can clearly see my app stuttering whenever they're triggered.

Blocking GCs are incredibly bad. What's the reason for triggering them?

**Comment by cmelchior** [comment] 2015-12-10 07:15
Yes, bulk insert is not that well optimized yet unfortunately. We have an issue tracking it here: https://github.com/realm/realm-java/issues/1684

2 things you can do to work around it

1) Make sure all writes are on a background thread
2) Batch the writes in smaller portions, that will enable the GC to better keep up.

It also depends on how you actually insert the objects. If you use something like GSON, it will also create a lot of objects which will trigger the GC.

**Comment by Saketme** [comment] 2015-12-10 08:04
No no, it's happening when I'm only inserting 1 item. This is without GSON.

**Comment by cmelchior** [comment] 2015-12-10 08:07
That sounds a bit strange then. It is also blocking for an extremely long time. 

- Is it happening on a specific dev?
- Does it happen every time?
- What kind of object is it?

**Comment by Saketme** [comment] 2015-12-10 08:41
> Is it happening on a specific dev?

Specific version do you mean? I'm on Realm 0.87 Snapshot version.

> Does it happen every time?

Yes, every time I'm inserting an item in a specific table. 

> What kind of object is it?
It's a messaging app. The object contains one message. Contains about 15 primitive types and 1 RealmObject.

**Comment by cmelchior** [comment] 2015-12-10 08:58
Sorry, meant specific device. 
If your RealmObject object contains references to other RealmObjects they will all be inserted. Do you have a big object graph even though it is only one top object?

Also posting your RealmObject model class might give us a better idea what might be triggering this.

**Comment by Saketme** [comment] 2015-12-10 09:08
Device is Moto G3. And the graph is small. The linked Object only contains a few primitive types. Here are the RealmObjects: 

https://gist.github.com/Saketme/85efdd8bbb07501acaa4
https://gist.github.com/Saketme/381143f25b861a29513e

**Comment by cmelchior** [comment] 2015-12-10 09:12
How are you inserting the object? Also You can try to use the IntelliJ memory analyzer to see if something else is taking up a lot of memory (which will trigger GC's more often).

**Comment by Saketme** [comment] 2015-12-10 17:30
Using the normal `Realm.execute` method. Does it have anything to do with how much processing goes inside a transaction?

Additionally, why is `realm.HandlerController.deleteWeakReferences` so aggressive?

**Comment by kneth** [comment] 2015-12-11 10:40
It depends on what you mean by processing. Inserting a single object will probably trigger GC but if you pass the JSON file within the transaction, it isn't hard to image that many objects are created during that.

**Comment by Saketme** [comment] 2015-12-11 17:06
Right, sorry for not making it more clear. So while inserting a new message to the database, I do a couple of extra processing like finding and linking the message with its sender before inserting it, finding if a conversation exists for the message or not, updating the conversation list upon inserting the message, etc.

**Comment by kneth** [comment] 2015-12-14 10:56
A "Suspending all threads" situation can happen if you do a synchronous call to some network code (see for example http://stackoverflow.com/questions/33114036/android-application-hangs-and-suspends-all-threads). Besides that, since you do more than just creating a Realm object, all the temporary objects must be garbage-collected, and that can trigger GC.

**Comment by Saketme** [comment] 2015-12-14 11:11
For the past 2 days, I've been trying to optimize my code for creating as less objects as possible. I'm using Android's DDMS tool for this, but it doesn't seem to help. Writing an item to the main Realm triggers a GC everytime. 

Let me try optimizing the code further and get back to you :)

**Comment by kneth** [comment] 2015-12-16 08:22
I'll close the issue but don't hesitate to create an issue if you have questions.

**Comment by Saketme** [comment] 2015-12-17 17:27
Update: I was unable to find any solution. Writing the `Message` item into Realm and committing the transaction triggers an explicit GC. This doesn't happen with other `RealmObject` items so I'm unable to understand what's wrong the the `Message` item.

Any ideas?

**Comment by kneth** [comment] 2015-12-18 09:02
You probably can't reopen, so let me do it.

**Comment by kneth** [comment] 2015-12-18 09:03
Please make a reproducible test case so we can debug it.

**Comment by Saketme** [comment] 2015-12-18 09:25
Okay, let me try cloning my project, stripping off everything that's not relevant and sharing the project with you so that you can debug it. Please keep this issue opened until then.

**Comment by diegomontoya** [comment] 2015-12-24 01:10
@saketime Use ddms to track the allocations of just the object insert operation. This way, you can see just how much and what is used by this single update.

I would also try testing on android 6, 5, and 4. All 3 versions have different plans for when to GC. See if your problem is version or device related.

**Comment by Saketme** [comment] 2015-12-24 02:51
@diegomontoya Yes I did try testing with ddms. The problem I'm seeing is that it seems to be reporting multiple times for the same allocations. Anyway, I did minimize object creation in a lot of areas in my app, but couldn't solve the GC issue. They're always triggered by Realm. 

I also remember seeing a lot of Collection objects (probably HashMap) created by Realm when accessing RealmResults. Will have to check again for the exact stacktrace.

**Comment by beeender** [comment] 2015-12-24 03:40
@Saketme Is there any long string in your Object? for example, how long is the `MessageItem.body` when this problem happens?

**Comment by Saketme** [comment] 2015-12-24 04:01
It's a messaging app. So `body` mostly contains Strings of length anywhere between 50-300.

**Comment by Saketme** [comment] 2015-12-24 20:12
Phew, this took a lot of hours. Sample project emailed. Please look into it once Christmas is over :)

**Comment by Saketme** [comment] 2015-12-25 10:47
Update: I managed to reproduce GCs by simply creating a new project and inserting a few items asynchronously.

    getRealm().executeTransaction(bgRealm -> {

            int i = 0;
            for (; i < 4; i++) {
                bgRealm.copyToRealmOrUpdate(new ClearTaxMember(i, "Member #" + i));
            }

            Log.i(TAG, i + " items inserted into Realm");

        }, null);

RealmObject: https://gist.github.com/Saketme/e0842adab486a758d13b

**Comment by beeender** [comment] 2015-12-25 11:01
@Saketme I just tried above code, on my Genymotion and a Huawei hornor 7, it didn't trigger GC when transaction executed...

Does it only happen to Moto G3?

**Comment by beeender** [comment] 2015-12-25 11:09
@Saketme Hmm, i can see 
```
I/art     ( 7037): Explicit concurrent mark sweep GC freed 775(35KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 16MB/27MB, paused 255us total 8.891ms
```

Is it what you saw?

**Comment by Saketme** [comment] 2015-12-25 11:25
Yes!

**Comment by cmelchior** [comment] 2016-01-08 16:27
0.87.2 has been released with a fix for this.

**Closed by cmelchior** 2016-01-08 16:27 UTC
Labels: bug, P1
