### ISSUE TITLE
Login not working with email-credentials (token contains an invalid number of segments)

### ISSUE THREAD

**Issue by MarcelBreska** [realm/realm-java#7117] opened 2020-09-21 10:56 UTC
#### Goal
Login user with with email and password -> 
val credentials = Credentials.emailPassword(email, password)
app.loginAsync(credentials)

#### Actual Results
Failing with result: SERVICE_UNKNOWN(realm::app::ServiceError:-1): token contains an invalid number of segments, false

#### Steps & Code to Reproduce
Login with email and password is not working anymore in Beta 7. With Beta 6 the login is working without a problem.

#### Version of Realm and tooling

Realm version(s): io.realm:realm-gradle-plugin:10.0.0-BETA.7

Realm Sync feature enabled: Yes

**Comment by cmelchior** [comment] 2020-09-21 10:59
So if you downgrade to BETA.6 it works against the exact same endpoint?

**Comment by MarcelBreska** [comment] 2020-09-21 11:02
Yes, switching back to BETA.6 "solved" the problem. I switched already 3x between the versions. Always with the same result:
BETA.6 -> no Problem
BETA.7 -> SERVICE_UNKNOWN(realm::app::ServiceError:-1): token contains an invalid number of segments, false

**Comment by cmelchior** [comment] 2020-09-21 11:03
Hmm, interesting. What URL are you logging in against?

**Comment by cmelchior** [comment] 2020-09-21 11:04
Note, this problem was reported Friday internally as well, and I can reproduce it.

**Comment by MarcelBreska** [comment] 2020-09-21 11:09
What URL do you mean? I'm using the Android-SDK and the URL is setup with -- def mongodbRealmUrl = "https://realm.mongodb.com" -- as described in the docs. I can send you my Project-Id in a private message if it helps.

**Comment by cmelchior** [comment] 2020-09-21 11:10
No, that should be enough. Thanks 👍

**Comment by cmelchior** [comment] 2020-09-22 10:27
We found the root cause for this. By mistake, we are sending HTTP headers twice which apparently trips the server up.

**Comment by cmelchior** [comment] 2020-09-23 09:40
10.0.0-BETA.8 has been released with a fix.

**Closed by cmelchior** 2020-09-23 09:40 UTC
Labels: O-Community
