### ISSUE TITLE
Getter in RealmObject return other field's data.

### ISSUE THREAD

**Issue by hohnamkung** [realm/realm-java#3262] opened 2016-08-05 05:12 UTC
#### Expected Results

Getter in RealmObject should return assigned field's data, not nearby field's data in same RealmObject.

#### Actual Results

RMessageView(class that have this problem) looks like below
```
public class RMessageView extends RealmObject {
    private Integer statusOrd;

    private Long index;

    private String readStatus;

    private String syncState;

    private Integer bubbleType;

    private RMessage model;

    private String status;

    private String localID;

    @PrimaryKey
    @Required
    private String key;

    ...
}

public class RMessage extends RealmObject {
    ....
    @PrimaryKey
    @Required
    private String id;

    private String content;
    ....
}

public enum CReadStatus {
    SENDING,
    SEND,
    READ,
    UNKNOWN;
}
```

`readStatus` field is used as a enum for sending status (`CReadStatus`).
According to user's report and screenshot, every value from `RMessageView.getMessage.getContent()` is `SEND` that i think it is loaded from `readStatus`.

    
![pasted_image_at_2016_08_05_09_47_am_720](https://cloud.githubusercontent.com/assets/1873136/17423639/30c5ac64-5af7-11e6-9b94-1a78aaac8f85.jpg)

#### Steps & Code to Reproduce

I can't reproduce it. According to user, this problem was fixed after they re-installed application.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Which Android version and device: ?

**Comment by beeender** [comment] 2016-08-05 05:49
> this problem was fixed after they re-installed application.

What if user restart the process, will it solve the issue?

**Comment by beeender** [comment] 2016-08-05 10:28
I am asking because i want to understand if it just a memory corruption or it is a db corruption.

**Comment by hohnamkung** [comment] 2016-08-06 03:15
I asked it to user, but i'm not sure i'll get a answer.
I'll comment if i get a feedback.

**Comment by kneth** [comment] 2016-08-16 07:04
@hohnamkung I assume you haven't heard from the user, right? And you still cannot reproduce it?

**Comment by hohnamkung** [comment] 2016-08-17 09:51
According to our CS team, we haven't received any feedback from this user.
I also still cannot reproduce it.

**Comment by kneth** [comment] 2016-10-03 08:58
@hohnamkung I'm closing the issue. If you get any feedback from the user - or can reproduce it - please either reopen or create a new issue.

**Closed by kneth** 2016-10-03 08:58 UTC
Labels: S:Waiting For User, T:Help
