### ISSUE TITLE
App Bundle: MissingLibraryException

### ISSUE THREAD

**Issue by Jeff11** [realm/realm-java#5977] opened 2018-05-28 10:29 UTC
#### Goal

To find a solution for ABI related problems

#### Expected Results

To run all split versions of app successfully

#### Actual Results

```
Fatal Exception: java.lang.RuntimeException: Unable to create application my.app.AppMain: com.b.a.b: lib/armeabi/librealm-jni.so
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4715)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
```

```
Caused by com.b.a.b: lib/armeabi/librealm-jni.so
       at com.b.a.a.a(ApkLibraryInstaller.java:85)
       at com.b.a.d.a(ReLinkerInstance.java:180)
       at com.b.a.d.a(ReLinkerInstance.java:136)
       at com.b.a.c.a(ReLinker.java:1070)
       at io.realm.internal.m.a(RealmCore.java:60)
       at io.realm.v.a(Realm.java:258)
       at my.app.AppMain.onCreate(AppMain.java:256)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
```

#### Version of Realm and tooling
Realm version(s): 5.1.0
Android Studio version: 3.2 canary 15

Which Android version and device: Nexus 5X tries to load x86, but most reported devices try armeabi
[Many different devices are affected](https://pasteboard.co/HnfKNkL.png)
[App is not using other so files than Realm.](https://pasteboard.co/HnfOOMw.png)

From the Google Play dashboard I can see that no armeabi version is generated, only the 5 that Realm uses. 

Edit: removed the x86 from the stacktrace, that was confusing

**Comment by Jeff11** [comment] 2018-05-29 14:21
That was confusing from my side, sorry. Of course, either x86 or armeabi was loaded per device, not both.

This crash happens on <0.2% of devices.

**Comment by chriswiesner** [comment] 2018-06-04 08:57
I have a similar issue using Android App Bundle.

```
Caused by com.getkeepsafe.relinker.MissingLibraryException
lib/x86/librealm-jni.so
arrow_right
com.getkeepsafe.relinker.ApkLibraryInstaller.a (Unknown Source)
com.getkeepsafe.relinker.ReLinkerInstance.b (Unknown Source)
com.getkeepsafe.relinker.ReLinkerInstance.a (Unknown Source)
com.getkeepsafe.relinker.ReLinker.a (Unknown Source)
io.realm.internal.RealmCore.a (Unknown Source)
io.realm.Realm.a (Unknown Source)
```
and
```
Caused by com.getkeepsafe.relinker.MissingLibraryException
lib/armeabi/librealm-jni.so
com.getkeepsafe.relinker.ApkLibraryInstaller.a (Unknown Source)
com.getkeepsafe.relinker.ReLinkerInstance.b (Unknown Source)
com.getkeepsafe.relinker.ReLinkerInstance.a (Unknown Source)
com.getkeepsafe.relinker.ReLinker.a (Unknown Source)
io.realm.internal.RealmCore.a (Unknown Source)
io.realm.Realm.a (Unknown Source)
```

Filed an issue on Google side to check if it's a fault on the bundle system itself: https://issuetracker.google.com/issues/109448556

**Comment by nhachicha** [comment] 2018-06-09 15:51
@Jeff11  Are you using another library which uses `armeabi`, my guess is the bundle created an APK based on this configuration (CPU = armeabi) but as you know Realm stopped supporting armeabi since 2.x (Following Google deprecation on this ABI).

You can now double check the generated APK locally using [bundletool](https://developer.android.com/guide/app-bundle/test) as described by the official doc & see if you can reproduce the issue before pushing to Play

**Comment by Jeff11** [comment] 2018-06-11 08:51
I have no other libraries that use armeabi. Realm is the only native library in use.

After uploading the AAB to the play store, I am able to download the APKs by device and they worked fine.

**Comment by sdeff** [comment] 2018-06-14 20:53
I'm experiencing the same issue with Android App Bundle:

```
Caused by com.getkeepsafe.relinker.MissingLibraryException: lib/armeabi/librealm-jni.so
       at com.getkeepsafe.relinker.a.a(ApkLibraryInstaller.java:85)
       at com.getkeepsafe.relinker.c.c(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.c.a(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.b.a(ReLinker.java:70)
       at com.getkeepsafe.relinker.b.a(ReLinker.java:57)
       at io.realm.internal.l.a(RealmCore.java:60)
       at io.realm.v.a(Realm.java:258)
```

Strangely only on devices which use MediaTek chipsets like:

Quantum MUV PRO - MediaTek MT6753
Lenovo PHAB 2 Plus - MediaTek MT8783
Xperia XA  - MediaTek MT6755 Helio P10
Sony Xperia XA1 Ultra Dual - MediaTek MT6757 Helio P20

<img width="850" alt="bildschirmfoto 2018-06-14 um 22 50 51" src="https://user-images.githubusercontent.com/2885756/41437719-865f799e-7025-11e8-9fe7-a53f459db9cc.png">

**Comment by cmelchior** [comment] 2018-06-28 13:36
From the comments in https://issuetracker.google.com/issues/109448556 It seems that this is related to side-loaded APK's. Before, if you didn't manually use ABI split, the APK would contain all the code needed for all CPU architectures. With App Bundle a split is happening automatically and if people are distributing the APK to devices with a different architecture, the app will crash with the above message.

I have been told this is behaviour is quite common in areas where data traffic might be expensive.

Unfortunately, there isn't much we can do about this as it is a "user error". The best we can do is probably having a better check if we cannot match the CPU architecture with the native code found. If that happens we can throw a better exception. App developers can then use this exception to show a dialogue to the user saying the app doesn't work on their device.

I'll keep this issue open as it hasn't been closed on Googles side yet, so we cannot yet rule out a bug on their end.

**Comment by philippb** [comment] 2018-07-09 18:15
It looks like the our ReLinker has problems loading native libs from AppBundles as we only look in the base APK for the native library.
https://github.com/KeepSafe/ReLinker/issues/44 Sums this up.

We would be very happy about a PR on this, as we don't use AppBundles our selfs. The following comment from a [google issue](https://issuetracker.google.com/issues/109448556#comment11) sums it up quite well:

> ReLinker loads the native library directly from the APK file, without using the OS' System.load() or System.loadLibrary() methods. The issue is that it searches for the native libraries in the base APK, whereas with the App Bundle, the native libraries are in config splits (i.e. ReLinker searches in base.apk whereas the native libraries are actually in base-x86.apk, base-armeabi.apk, etc.).

> Source:
> https://github.com/KeepSafe/ReLinker/blob/master/relinker/src/main/java/com/getkeepsafe/relinker/ApkLibraryInstaller.java#L55
> Instead of searching in "sourceDir", ReLinker should be searching over the different directories under "splitSourceDirs".

**Comment by cmelchior** [comment] 2018-07-16 07:59
A PR is currently in review that should fix this: https://github.com/KeepSafe/ReLinker/pull/46
Once this PR has been approved and merged we will upgrade the Relinker version used.

**Comment by cmelchior** [comment] 2018-08-31 13:18
Support for App Bundles has been merged to Relinker `master` branch. It seems that only https://github.com/KeepSafe/ReLinker/pull/51 needs to be merged before a release is made.

**Comment by tamtom** [comment] 2018-09-03 07:51
@cmelchior  when it will be released?

**Comment by nhachicha** [comment] 2018-09-12 11:44
@cmelchior It looks like ReLinker released `1.3.0` with the fix, we should test it & release a minor

**Comment by amatsegor** [comment] 2018-09-20 14:39
Waiting for a 5.5.1 version really much, it's the only obstacle for us to make an APK almost three times smaller.
Are the any estimates for this release?

**Comment by cmelchior** [comment] 2018-09-21 10:34
Yes, the plan is to release it next week. Our SNAPSHOT uploads have been broken, but should work again, so you can also test it by using our `5.6.0-SNAPSHOT` release: https://github.com/realm/realm-java#using-snapshots

**Comment by roberhofer** [comment] 2018-09-26 23:03
@cmelchior : I believe that Realm Java 5.6.0 has been released with a fix for this ticket. Can you verify and close?

**Comment by MeinLieberScholli** [comment] 2018-10-19 14:42
Unfortunately, I still get the same issue with Realm version 5.7.0.

Samsung SM-G965F
LGE Nexus 5X

<img width="320" alt="relinker issue" src="https://user-images.githubusercontent.com/9082911/47225071-6d402480-d3bd-11e8-9d5b-97794184befa.png">

**Comment by engi2nee** [comment] 2018-11-07 14:44
@MeinLieberScholli ,Do you have any idae if Is this problem has been solved in 5.8.0?

**Comment by MeinLieberScholli** [comment] 2018-11-08 07:57
> @MeinLieberScholli , Do you have any idea if Is this problem has been solved in 5.8.0?
> We are getting such crashes from those models on 5.7.1:
> ANE-LX1,CLT-L09,CLT-L29,SM-N910C,SM-N920C,SM-N960F

i will update in a few days and report if it occurs again.

**Comment by cmelchior** [comment] 2018-11-08 08:04
I'm reopening this issue as we are seeing some reports of there perhaps still being problems with App Bundle

**Comment by cmelchior** [comment] 2018-11-08 08:13
Note that with App Bundle, if users are sharing their APK manually there is a very real possibility that the user receiving the APK is not able to use it due to ABI incompatibility. That is probably hard to tell from Crashlytics though :/

**Comment by engi2nee** [comment] 2018-11-08 08:55
@cmelchior we ordered one of the reported devices so we can test it locally, I will update you as soon as I receive them.
For your second question, I don't think that is the case as we are getting around 500 unique crash per week from this bug, we will know better when I test it locally.
Thanks for your help.

**Comment by cmelchior** [comment] 2018-11-08 08:58
Yes, that probably means we can rule that out in that case.

**Comment by engi2nee** [comment] 2018-11-12 08:36
ok, so I got my hands on 2 of the devices I mentioned, unfortunately, couldn't reproduce locally, tried both devices with the app installed from play store:/
I was checking fabrics reports, so decided to check Google Play Console for more info about the crashes (it has an option to check if the app was installed from play store), here is what I have for now.

1- I am getting 2 crash reports with the same bug "com.getkeepsafe.relinker.MissingLibraryException"
one coming from Samsung devices and one from Huawei (mostly)
![screen shot 2018-11-12 at 11 20 19](https://user-images.githubusercontent.com/34459465/48334827-071d8900-e66d-11e8-9194-6b24fedca548.png)
![screen shot 2018-11-12 at 11 20 26](https://user-images.githubusercontent.com/34459465/48334856-18669580-e66d-11e8-91b5-f57a665c87df.png)

2- both have the same crash report posted earlier by @MeinLieberScholli.

3- If I select the "installed from anywhere" option, the crash numbers triples ( @cmelchior  you were right about this possibility)

Hope this info help fixing this bug.
The problem is we can't roll back to apk way of publishing after signing for the bundle, so we have nothing to do but to limit the bug cause with you guys.

**Comment by cmelchior** [comment] 2018-11-20 12:31
Update from: https://issuetracker.google.com/issues/109448556

> The source of the install can unfortunately be faked quite easily with "adb" and it looks like a bunch of users have learnt to do that (for reasons that I'm not entirely sure of yet). We haven't received any end-user report either that an install from Play was failing for them. A few other developers are facing the same issue and none of them have been able to reproduce the issue either.
All of this seems to confirm that the issue is indeed sideloading (with for some users faking the source of the install) so I will close this bug for now. If you have any end-user reporting that the install is failing when installing from Play store, feel free to re-open this bug providing the details. Note that we are also actively working on a solution to avoid the crashes on the users having installed only a subset of the required APKs. This should help remove those crashes from your reports altogether . Stay tuned.

Unfortunately, it seems at this point in time that the only way to avoid this issue is to avoid using AppBundle. Note that if users are indeed installing the wrong bundle, they will probably also experience other issues, like images having the wrong size or localization not working correctly.

**Comment by Jonty800** [comment] 2019-01-29 22:23
This has been an ongoing issue within the app I've been working on since we switched to a Bundle instead of an APK.

https://i.imgur.com/FLwmukH.png

The crash ranges between Android 5 - Android 9, rooted and unrooted devices. More interestingly, it occurred today during a 30% rollout of an app update. 

Does anyone have any information relating to the direct source of this issue? Or any advice on discovering what could be causing it?

**Comment by KimiChiu** [comment] 2019-02-26 17:24
Fresco had this issue before. But they fixed it 22 days ago.
[When building via App Bundle, Fresco fails to find "libimagepipeline.so"](https://github.com/facebook/fresco/issues/2253#issuecomment-446089907 )
Maybe you can ask them about how to resolve this problem.

**Comment by Ramzi-Alqrainy** [comment] 2019-02-26 22:15
@cmelchior any update on this bug? We can use this feature for reducing the size of our build.

**Comment by Zhuinden** [comment] 2019-02-26 22:47
If that is the case, then the bug would be in Relinker

**Comment by JenyaKirmizaTripTop** [comment] 2019-03-06 12:33
Any news? i'm thinking of using apk split for now

**Comment by diegomontoya** [comment] 2019-03-06 13:18
Note that users in India, Africa have much higher tendency to "share" apk files due to the cost and speed of bandwidth there. 

We have zero reports of this issue with users that installed from offiial Play store via bundle split apks. I do not believe this can be solved by relinker or any so loader since if you manually install the wrong apk, you are missing .so files period. No ammount of wrangling will let your app open realm files. 

Note that if you use realm with relinker 1.3.0+, there is absolutely no issue barring human error.

**Comment by Jonty800** [comment] 2019-03-06 16:42
> Note that users in India, Africa have much higher tendency to "share" apk files due to the cost and speed of bandwidth there.
> 
> We have zero reports of this issue with users that installed from offiial Play store via bundle split apks. I do not believe this can be solved by relinker or any so loader since if you manually install the wrong apk, you are missing .so files period. No ammount of wrangling will let your app open realm files.
> 
> Note that if you use realm with relinker 1.3.0+, there is absolutely no issue barring human error.

I've been working on an app with a 700k+ user base. We recently switched to bundle, and since then we had been receiving reports of this error during a rollout for an update. This means that the user had got the update from the play store and the APK was determined by Google. 

We ignored the issue for a while until a user contacted us to complain. The user confirmed that they had installed the app through the play store and not from any other source (such as sharing APKs). 

Reasons why Google would supply an incorrect APK are unconfirmed. Regardless, we resolved the issue by deploying an APK instead of a bundle

**Comment by diegomontoya** [comment] 2019-03-07 06:57
@Jonty800 You can track the google issue here https://issuetracker.google.com/issues/111233819

If the user installed custom roms that didn't support split apks, they need to wait for Google Play update which will auto detect this on their phone. You need to check to see if those users are using a) custom mods b) rooting and installed custom kernels.

**Comment by JenyaKirmizaTripTop** [comment] 2019-03-07 10:06
> > Note that users in India, Africa have much higher tendency to "share" apk files due to the cost and speed of bandwidth there.
> > We have zero reports of this issue with users that installed from offiial Play store via bundle split apks. I do not believe this can be solved by relinker or any so loader since if you manually install the wrong apk, you are missing .so files period. No ammount of wrangling will let your app open realm files.
> > Note that if you use realm with relinker 1.3.0+, there is absolutely no issue barring human error.
> 
> I've been working on an app with a 700k+ user base. We recently switched to bundle, and since then we had been receiving reports of this error during a rollout for an update. This means that the user had got the update from the play store and the APK was determined by Google.
> 
> We ignored the issue for a while until a user contacted us to complain. The user confirmed that they had installed the app through the play store and not from any other source (such as sharing APKs).
> 
> Reasons why Google would supply an incorrect APK are unconfirmed. Regardless, we resolved the issue by deploying an APK instead of a bundle
> 
> More details here: #6418

have you tried deploying with apk-splits? Currently, I'm having the same choice, 200k+ users. Considering dev's feedbacks i think that this issue still exists

**Comment by cmelchior** [comment] 2019-03-19 14:19
It seems that Google thinks this issue is also related to https://issuetracker.google.com/issues/111233819 and they are working on a fix for that.

Unfortunately, this means that the advice in https://github.com/realm/realm-java/issues/5977#issuecomment-440257246 still stands and AppBundle should probably be avoided until Google can fix the underlying issue.

**Comment by HungTDO** [comment] 2019-07-08 03:02
Any update or new information about this issues?
My Crashlytics received many errors:
`Caused by com.getkeepsafe.relinker.MissingLibraryException
lib/x86/librealm-jni.so
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:85)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:57)
io.realm.internal.RealmCore.loadLibrary (RealmCore.java:60)
io.realm.Realm.init (Realm.java:200)
com.BestPhotoEditor.VideoMaker.VideoEditorApplication.onCreate (VideoEditorApplication.java:59)`

**Comment by ankuryadav7** [comment] 2019-07-12 11:47
Have just update the classpath to classpath "io.realm:realm-gradle-plugin:5.11.0"

**Comment by lucasrafagnin** [comment] 2019-07-15 14:21
Does this issue still happen? Or can I update my app to use the app bundle?

**Comment by berkayturanci** [comment] 2019-07-16 06:05
This problem doesn't related to library Realm. It can occurs due to  any of library that you used.

Google has already released a fix for this; https://developer.android.com/guide/app-bundle/sideload-check 

It checks if apk that user installed is suitable for his/her device, otherwise it shows a dialog for installing the right one from the play store.

So, yes you can use app bundle by having this fix in your app.

**Comment by RJFares** [comment] 2019-07-18 18:33
+1

@lucasrafagnin unfortunately still does for a random small percentage of users

**Comment by andrelramos** [comment] 2019-08-05 19:01
+1

**Comment by zmunm** [comment] 2019-08-06 03:58
+1

**Comment by diegoaces** [comment] 2019-08-09 15:07
+1

**Comment by Zhuinden** [comment] 2019-08-10 09:53
You are most likely missing this check on YOUR side: https://developer.android.com/guide/app-bundle/sideload-check#application_class_check

You should make sure that the APK installed by the user has the library variant in Realm.

If you are using Android App Bundle, then you should have this check in your Application class.

This is not a problem with Realm.

**Comment by Jeff11** [comment] 2019-08-14 11:03
@Zhuinden the `MissingSplitsManager` didn't work for me when I tried an APK with `ndk { abiFilters "mips" }` on a x86 emulator.

Instead I'm catching the `RuntimeException` and show a toast.

**Comment by Zhuinden** [comment] 2019-08-14 11:25
@jeff11 hmm I thought `abiFilters` requires you to specify what to keep (and Realm doesn't support MIPS), and not what to exclude.


Maybe try 

```
abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'
```

**Comment by Jeff11** [comment] 2019-08-14 11:43
My intention was to build an APK that is not compatible and therefore `disableAppIfMissingRequiredSplits()` is `true` and the app won't start.

But `disableAppIfMissingRequiredSplits()` was `false`.

**Comment by Zhuinden** [comment] 2019-08-14 11:55
But was it actually an Android App bundle, and not an APK?

**Comment by Jeff11** [comment] 2019-08-14 12:31
An APK. When using the App Bundle, you would first have to extract an APK with a single ABI from it. That I didn't test.

**Comment by Zhuinden** [comment] 2019-08-14 13:10
missing required splits should only be relevant when Android App Bundle is used.

**Comment by Mihir3646** [comment] 2019-08-16 10:31
Try this, might be helpful. 
https://realm.io/docs/java/latest/#faq-librealm-jni 
For detail: 
https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html

**Comment by Mihir3646** [comment] 2019-08-16 10:31
Try this, might be helpful. 
https://realm.io/docs/java/latest/#faq-librealm-jni 
For detail: 
https://corbt.com/posts/2015/09/18/mixing-32-and-64bit-dependencies-in-android.html

**Comment by koichi-ozaki** [comment] 2019-09-06 09:15
https://realm.io/docs/java/latest/#faq-librealm-jni

I tried this method and it crashed.
Is there no solution?

```
Device Information:
Device: Nexus 5X
Android Version: 6.0.1

Realm Version: 5.14.0

Logcat:
Caused by e.f.a.b: librealm-jni.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary + 123(ApkLibraryInstaller.java:123)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal + 180(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary + 136(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary + 70(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary + 57(ReLinker.java:57)
       at io.realm.internal.RealmCore.loadLibrary + 60(RealmCore.java:60)
       at io.realm.Realm.initializeRealm + 322(Realm.java:322)
       at io.realm.Realm.init + 265(Realm.java:265)
```

**Comment by koichi-ozaki** [comment] 2019-09-06 09:32
https://fabric.io/gmo-media-inc/android/apps/jp.gmomedia.android.prcm/issues?time=last-thirty-days&event_type=crash&subFilter=state&state=open&build%5B0%5D=8.6.1%20%28360%29
https://fabric.io/gmo-media-inc/android/apps/jp.gmomedia.android.prcm/issues?time=last-thirty-days&event_type=crash&subFilter=state&state=open&build%5B0%5D=8.6.1%20%28362%29
https://fabric.io/gmo-media-inc/android/apps/jp.gmomedia.android.prcm/issues?time=last-thirty-days&event_type=crash&subFilter=state&state=open&build%5B0%5D=8.6.3%20%28363%29
https://fabric.io/gmo-media-inc/android/apps/jp.gmomedia.android.prcm/issues?time=last-thirty-days&event_type=crash&subFilter=state&state=open&build%5B0%5D=8.6.4%20%28364%29


このクラッシュをみるかぎり、

- Nexus5X でしか出ていない
- Nexus5X は、Android Studio のエミュレーターのデフォルトの端末
- クラッシュが出るのがリリースして早すぎる

上記のことから、Google が自動検証みたいなことをやっている気がしてきた

**Comment by drofnnuD** [comment] 2019-09-10 10:56
https://realm.io/docs/java/latest/#faq-librealm-jni

This happens every time I try to run my app on a device, without fail.

I've also tried this method and it made no difference, it's still crashing on `Realm.init()` in my Application Class.

All of this started after trying to update the application `build.gradle` with the latest version of Braintree 3D secure, it wouldn't build so I migrated the project to use androidx, now the project builds, and the app will install, it just falls down on `Realm.init()` constantly.

> Device Information:
>   Device: Google Pixel 3 XL
>   Android Version: 9
> 
>   Realm Version: 
> 
> 5.14.0

Logcat output

```

2019-09-10 11:47:13.735 29660-29660/com.companyname.androidapps.companyname E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.companyname.androidapps.skiddle, PID: 29660
    java.lang.RuntimeException: Unable to create application com.companyname.androidapps.companyname.ApplicationController: com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5758)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:123)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
        at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
        at io.realm.Realm.initializeRealm(Realm.java:322)
        at io.realm.Realm.init(Realm.java:265)
        at com.companyname.androidapps.companyname.ApplicationController.onCreate(ApplicationController.java:39)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5755)
```

**Comment by dotrinhdev** [comment] 2019-10-19 10:52
> Have just update the classpath to classpath "io.realm:realm-gradle-plugin:5.11.0"

the same me, i upgraded to 6.0.0. It works.

**Comment by ilexbor** [comment] 2019-11-13 15:41
Android 6.0.1 Nexus 4

```
Fatal Exception: java.lang.RuntimeException: Unable to create application Application: com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4714)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

```
Caused by com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:123)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
       at io.realm.Realm.initializeRealm(Realm.java:322)
       at io.realm.Realm.init(Realm.java:265)
       at epayservice.kotlin.controller.RealmController.create(RealmController.java:23)
       at epayservice.kotlin.controller.App.onCreate(App.java:63)
       at epayservice.kotlin.controller.Application.onCreate(Application.java:21)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1022)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by cmelchior** [comment] 2019-11-27 14:52
Folding this into https://github.com/realm/realm-java/issues/6673

**Closed** 2019-11-27 14:56 UTC
Labels: O-Community, Pipeline-On-Hold, T-Duplicate
