### ISSUE TITLE
Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by plugin 'realm-android'

### ISSUE THREAD

**Issue by NelzkieCoder** [realm/realm-java#7374] opened 2021-03-23 22:34 UTC
Getting this error any fix for this? 
`Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by plugin 'realm-android'`

Thanks

**Comment by AniketSK** [comment] 2021-03-29 10:27
@NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.

Replace the line:
`repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)`
with
`repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`

That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.

Out of curiosity were you using the Android Studio Canary?

**Comment by mohit-sharma-87** [comment] 2021-03-30 15:32
@NelzkieCoder : You can try moving to the latest version i.e. "10.4.0", which should resolve your issue as we have migrated from JCenter to mavenCentral.

I am also suspecting as @AniketSK  mentioned, changes in setting.gradle file which has been introduced in latest Android Studio Canary.

**Comment by AniketSK** [comment] 2021-04-04 02:57
@mohit-sharma-87 I was on Realm 10.4.0 and the (2020.3.1 canary 12) Android Canary and this is still an issue.

**Comment by cmelchior** [comment] 2021-04-29 10:49
This a duplicate of https://github.com/realm/realm-java/issues/7365#issuecomment-816672104, So I'll merge it into that one.

Unfortunately fixing it would require breaking change, but there is a work-around described in the comment I linked to.

**Closed by cmelchior** 2021-04-29 10:49 UTC
Labels: O-Community

**Comment by evan766** [comment] 2021-08-05 15:29
> PREFER_SETTINGS
thx, solve my problam

**Comment by NueeKip** [comment] 2021-08-13 07:27
@AniketSK It worked like a charm, Thank you 🤣🤣.

**Comment by mohit-sharma-87** [comment] 2021-08-28 07:29
@eugenegrib : I don't think so you need this anymore as the root issue as been fixed. 

https://github.com/realm/realm-java/issues/7365

**Comment by sharsad** [comment] 2021-09-20 13:28
In settings.gradle just comment out the whole block

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {`enter code here`
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}

**Comment by sharsad** [comment] 2021-09-20 13:29
In settings.gradle you can add the repositories you want to add to the project

dependencyResolutionManagement {
   repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
   repositories {
      google()
      mavenCentral()
      jcenter()
      maven { url "https://maven.xyz.com" }
    }
}

**Comment by attamunim** [comment] 2021-09-22 07:58
i deleted the lines
repositories{
maven()
}
from gradle
and it worked

**Comment by traiyani** [comment] 2021-09-27 06:35
remove

**Comment by pedrofsn** [comment] 2021-09-30 00:38
Thanks @sharsad!

**Comment by SurajBahadur** [comment] 2021-12-01 20:40
> @NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.
> 
> Replace the line: `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` with `repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`
> 
> That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.
> 
> Out of curiosity were you using the Android Studio Canary?

IT WORKED

**Comment by Hasims2001** [comment] 2021-12-27 09:56
Thank you so much

**Comment by tihiydo** [comment] 2022-01-22 13:51
> In settings.gradle you can add the repositories you want to add to the project
> 
> dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) repositories { google() mavenCentral() jcenter() maven { url "https://maven.xyz.com" } } }

Only this works, idk why :)

**Comment by AlexanderCop1983** [comment] 2022-08-02 16:42
это не работает(

**Comment by Ohior** [comment] 2022-08-22 09:59
> 
If `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` generates error why was it been used?
`

**Comment by ozZ-Y** [comment] 2022-11-07 18:28
Thank you, bug fixed
@AniketSK  ♥

**Comment by ezzeldin01010** [comment] 2023-01-20 21:10
> @NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.
> 
> Replace the line: `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` with `repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`
> 
> That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.
> 
> Out of curiosity were you using the Android Studio Canary?

You saved me, thank you

**Comment by Sarat-1997** [comment] 2023-03-06 06:38
> @NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.
> 
> Replace the line: `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` with `repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`
> 
> That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.
> 
> Out of curiosity were you using the Android Studio Canary?

Thanks a lot brother. It works!!!

**Comment by neha01mittal** [comment] 2023-05-10 01:57
Did the trick! Ty!
