### ISSUE TITLE
Updating realm to 0.89.0 throw owIndex > available rows.

### ISSUE THREAD

**Issue by szaman12** [realm/realm-java#2659] opened 2016-04-24 19:25 UTC
Hi. After updating real libraly from version 0.88.3 to 0.89.0.

My app throw this exception:  `owIndex > available rows: 0 > 0`

Exception is throwed after remove element from recyclerView list when is called `notifyItemRemoved('position')`; in RecyclerAdapter class.

```java
...
private RealmResults<ListaModel> mList;
...
    public ListaAdapterR(Context context, RealmResults<ListaModel> List, Fragment parrentFragment) {

        mContext = context;
        mList = List; // data showed in list
        mRealmHelper = new RealmHelper(context); //helper class
        mFragmentManager = ((MainActivity) context).getSupportFragmentManager();
        mParrentFragment = parrentFragment;
    }
...
    @Override
    public void onBindViewHolder(ViewHolder holder, final int position) {

        mList.sort("id");

        final ListaModel currentLista = mList.get(position); // logcat show error in this line
...
```
I do not know if the problem lies on the side of my application, but in version 0.88.3 and earlier, everything worked as it should. The exception is thrown when list has one element when more error changes to: `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 2(offset:2).state:.`

Thank you in advance for your help.

**Comment by cmelchior** [comment] 2016-04-24 20:44
Hi @szaman12 
That error means you are trying to access an index in an empty RealmResults. You need to handle the case where the RecyclerView is empty. I am not entirely sure why the RecyclerView is calling onBindViewHolder on an empty result though.

**Comment by Zhuinden** [comment] 2016-04-25 08:20
The error is somewhere in where you modify the RealmResults, and your `getItemCount()` method.

**Comment by szaman12** [comment] 2016-04-26 12:35
I was able to discover the problem lies when list is updating. At the time of the call `notifyDataSetChanged()` the adapter does not see the item has been removed, the same problem is when I add the item to the list and  `getItemCount()` returns value before adding or delete. 
For example when i add element to list, element doesn't appear but when I add second element, item added earlier shows up, but last is not showing until I add the next element.


`   
    public int getItemCount() {
        return mList.size();
    }
`

**Comment by szaman12** [comment] 2016-04-26 19:12
Keiji it is not that same bug my exception is throwed when I remove element from list and use `notifyItemRemoved(position)`. I tried to use as a substitute `notifyDataSetChanged()` but then is throwing `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 2(offset:2).state:3`

**Comment by zaki50** [comment] 2016-04-30 14:06
Delaying `notify*()` by `Handler` like below solves the problem?

From `0.89` , updating `RealmResults` is delayed to the next event loop.

```
new Handler().post(new Runnable() {
    public void run() {
        recyclerView.notifyDataSetChanged();
    }
});
```

**Comment by beeender** [comment] 2016-05-09 02:52
@szaman12 I hope above comment helps. I am closing this issue now, feel free to let us know if you still need help on this.

**Closed by beeender** 2016-05-09 02:52 UTC
Labels: S:Waiting For User, T:Help

**Comment by szaman12** [comment] 2016-05-13 15:40
Yes this help, thank

**Comment by Sutirth** [comment] 2016-05-19 08:44
@cmelchior , @beeender  This bug exists on 0.90.1 as well. It was horrifying for me to know the root cause because it crash every single time. However @zaki50  Solution works perfectly
