### ISSUE TITLE
Cannot compile Android app with the gradle plugin 3.6.1

### ISSUE THREAD

**Issue by Maikals** [realm/realm-java#6775] opened 2020-03-11 10:24 UTC
#### Goal
Compile the Android project

#### Actual Results
When I compile the project with the latest version of the Gradle plugin version (3.6.1), the app cannot be build due an error with the RealmTransformer:
Caused by: org.gradle.tooling.BuildException: 
Failed to process /build/intermediates/transforms/RealmTransformer/dev/debug/0
#### Steps & Code to Reproduce
Update the Android project gradle plugin to 3.6.1.

#### Version of Realm and tooling

Realm version(s): realm java 6.0.1

Realm Sync feature enabled: No

Android Studio version: 3.6.1

Android Build Tools version: 29.0.2

Gradle version: 6.0.1 and plugin version 3.6.1

Which Android version and device(s): all versions

**Comment by iamsardorbek** [comment] 2020-03-17 04:40
Hi, I have a problem with building my project as well. Although the problem is not just like yours, but i think it is related. So any help will be appreciated.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Could not resolve com.android.tools.build:aapt2:3.6.1-6040484.
     Required by:
         project :app
      > No cached version of com.android.tools.build:aapt2:3.6.1-6040484 available for offline mode.
      > No cached version of com.android.tools.build:aapt2:3.6.1-6040484 available for offline mode.

**Comment by cmelchior** [comment] 2020-03-17 06:42
Hi @Maikals We have internally upgraded to Gradle Plugin 3.6.1 and haven't experienced such errors. Have you tried doing a complete clean build from the commandline? `./gradlew clean assemble`

If the problem still persists. It would be nice if you could provide an example project demonstrating the issue.

@iamsardorbek Your problem is not related to Realm, but to the fact that it appears your computer was not connected to the Internet.

**Comment by NeilHoggZA** [comment] 2020-03-20 08:14
Had the exact same problem as @Maikals when I was using android studio 3.6.1, reverting back to android 3.5.3 resolved the issue for me.

**Comment by Maikals** [comment] 2020-03-20 08:28
I've found the solution. I had the R8 classpath in the parent gradle project:
        classpath 'com.android.tools:r8:1.5.68'
After removing it, it worked with the latest Gradle Plugin

**Comment by NeilHoggZA** [comment] 2020-03-20 09:10
Removing the R8 classpath fixed it for me as well. Thanks

**Comment by iamsardorbek** [comment] 2020-03-22 10:54
@cmelchior Thank you. Exactly, the problem was that Gradle offline mode was turned on. I turned it on and everything started working.

**Comment by Marcos-M** [comment] 2020-04-21 01:14
@iamsardorbek could you tell me how it's done please.

**Comment by drumvas021** [comment] 2020-05-06 23:32
> Removing the R8 classpath fixed it for me as well. Thanks

where that?

**Comment by cmelchior** [comment] 2020-05-07 17:54
See here https://stackoverflow.com/questions/55065976/how-to-use-latest-r8-shrinker-version

In the meantime it sounds like this issue has been resolved. So will close for now.

**Closed by cmelchior** 2020-05-07 17:54 UTC
Labels: O-Community, T-Help
