### ISSUE TITLE
Realm 7.0.8 native crash - EncryptedFileMapping::get_local_index_of_address

### ISSUE THREAD

**Issue by sdex** [realm/realm-java#7145] opened 2020-10-05 11:50 UTC
#### Goal
To use realm.

#### Actual Results
Crashes.

#### Steps & Code to Reproduce
These reports are taken from the developer console. I have neither access to the devices nor the database.
It seems like the app crashes immediately after launch when tries to open the realm. 
This is my config:
```
new RealmConfiguration.Builder()
                .name(Realm.DEFAULT_REALM_NAME)
                .schemaVersion(DbMigration.SCHEMA_VERSION)
                .migration(new DbMigration())
                .rxFactory(new RealmObservableFactory(false))
                .compactOnLaunch((totalBytes, usedBytes) -> {
                    sharedPrefsHelper.putRealmTotalBytes(totalBytes);
                    sharedPrefsHelper.putRealmUsedBytes(usedBytes);
                    return false;
                })
                .build();
```

#### Version of Realm and tooling

Realm version(s): 7.0.8

Realm Sync feature enabled: No

Android Studio version: 4.0.1

Android Build Tools version: 30.0.4

Gradle version: 5.6.1

Which Android version and device(s): 
Samsung Galaxy Note9 (crownqltesq), 5632MB RAM, Android 10
Samsung Galaxy Note20 Ultra (c2s), 7680MB RAM, Android 10

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.myapp.android <<<

backtrace:
  #00  pc 00000000002a449c  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #01  pc 000000000011a324  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #02  pc 000000000011a25c  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #03  pc 0000000000241e3c  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #04  pc 0000000000247c60  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #05  pc 0000000000247f50  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #06  pc 0000000000247ac4  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #07  pc 000000000024c78c  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #08  pc 00000000001a8e74  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #09  pc 00000000001a3588  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #10  pc 000000000029c3ac  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #11  pc 00000000001a360c  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #12  pc 0000000000193384  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #13  pc 000000000018d3a0  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #14  pc 000000000018cf84  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #15  pc 000000000019a8f4  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #16  pc 000000000019aa6c  /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #17  pc 00000000000e28e0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #18  pc 000000000008503c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.myapp.android <<<

backtrace:
  #00  pc 00000000002a449c  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #01  pc 000000000011a324  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #02  pc 000000000011a25c  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #03  pc 000000000024802c  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #04  pc 0000000000247f0c  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #05  pc 0000000000247ac4  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #06  pc 000000000024c7e4  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #07  pc 0000000000170124  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #08  pc 000000000016ebb8  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #09  pc 000000000016ea50  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
  #10  pc 0000000000118324  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000) (Java_io_realm_internal_OsResults_nativeGetRow+28)
  #11  pc 000000000017ee00  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (art_jni_trampoline+160)
  #12  pc 00000000005c2dbc  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (io.realm.internal.OsResults.a+76)
  #13  pc 000000000053f2cc  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (io.realm.internal.OsResults$b.a+60)
  #14  pc 000000000053f560  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (io.realm.internal.OsResults$b.next+128)
  #15  pc 0000000002004990  /memfd:/jit-cache (com.myapp.app.sync.image.ImageDownloadService.e+2512)
  #16  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #17  pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #18  pc 00000000002e3730  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
  #19  pc 00000000002de990  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+892)
  #20  pc 00000000005a3500  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+424)
  #21  pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
  #22  pc 0000000000463cbc  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.vdex (com.myapp.app.sync.image.ImageDownloadService.b+256)
  #23  pc 00000000005a75e8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1292)
  #24  pc 0000000000135594  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
  #25  pc 0000000000463476  /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.vdex (com.myapp.app.sync.image.d.run+16)
  #26  pc 00000000002b4a44  /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.987302922385293720)+240)
  #27  pc 0000000000592740  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032)
  #28  pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
  #29  pc 00000000007f0dbc  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+76)
  #30  pc 00000000007f4498  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+1448)
  #31  pc 00000000007f2e04  /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+548)
  #32  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #33  pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #34  pc 00000000004b0dd8  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #35  pc 00000000004b1eec  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
  #36  pc 00000000004f2e58  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
  #37  pc 00000000000e6f10  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #38  pc 00000000000850c8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

**Comment by edualonso** [comment] 2020-10-05 11:56
First stack trace:
```
********** Crash dump: **********
#00 0x00000000002a449c /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::util::EncryptedFileMapping::get_local_index_of_address(void const*, unsigned long) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/util/encrypted_file_mapping.hpp:149:90
                                                                                                                        realm::util::EncryptedFileMapping::read_barrier(void const*, unsigned long, unsigned long (*)(char const*))
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/util/encrypted_file_mapping.cpp:793:0
#01 0x000000000011a324 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::util::do_encryption_read_barrier(void const*, unsigned long, unsigned long (*)(char const*), realm::util::EncryptedFileMapping*)
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/distribution/realm-core/core-5.0.28/include/realm/util/file_mapper.hpp:133:14
#02 0x000000000011a25c /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::Allocator::translate(unsigned long) const
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/distribution/realm-core/core-5.0.28/include/realm/alloc.hpp:515:9
#03 0x0000000000241e3c /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ArrayUnsigned::init_from_ref(unsigned long)
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/array_unsigned.hpp:42:32
#04 0x0000000000247c60 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterNodeInner::init(realm::MemRef)
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:256:16
#05 0x0000000000247f50 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterNodeInner::try_get(realm::ObjKey, realm::ClusterNode::State&) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:0:0
#06 0x0000000000247ac4 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterNode::get(realm::ObjKey, realm::ClusterNode::State&) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:222:16
#07 0x000000000024c78c /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterTree::get(realm::ObjKey) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:1968:13
#08 0x00000000001a8e74 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::Table::get_object(realm::ObjKey) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/table.hpp:299:27
                                                                                                                        realm::IntegerNode<realm::ArrayIntNull, realm::Equal>::index_based_aggregate(unsigned long, realm::util::FunctionRef<bool (realm::ConstObj&)>)
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/query_engine.hpp:782:0
#09 0x00000000001a3588 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::Query::find_all(realm::ConstTableView&, unsigned long, unsigned long, unsigned long) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/query.cpp:1325:23
#10 0x000000000029c3ac /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ConstTableView::do_sync()
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/table_view.cpp:602:17
#11 0x00000000001a360c /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::Query::find_all(unsigned long, unsigned long, unsigned long)
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/query.cpp:1380:9
#12 0x0000000000193384 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::_impl::ResultsNotifier::run()
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/object-store/src/impl/results_notifier.cpp:160:25
#13 0x000000000018d3a0 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::_impl::RealmCoordinator::run_async_notifiers()
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/object-store/src/impl/realm_coordinator.cpp:1048:19
#14 0x000000000018cf84 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::_impl::RealmCoordinator::on_change()
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/object-store/src/impl/realm_coordinator.cpp:836:5
#15 0x000000000019a8f4 /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::_impl::ExternalCommitHelper::DaemonThread::listen()
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/object-store/src/impl/epoll/external_commit_helper.cpp:289:38
#16 0x000000000019aa6c /data/app/com.myapp.android-zVSkAPPK6m4fSJ_fnyR83g==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::_impl::ExternalCommitHelper::DaemonThread::DaemonThread()::$_0::operator()() const
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/object-store/src/impl/epoll/external_commit_helper.cpp:197:13
                                                                                                                        decltype(std::__ndk1::forward<realm::_impl::ExternalCommitHelper::DaemonThread::DaemonThread()::$_0>(fp)()) std::__ndk1::__invoke<realm::_impl::ExternalCommitHelper::DaemonThread::DaemonThread()::$_0>(realm::_impl::ExternalCommitHelper::DaemonThread::DaemonThread()::$_0&&)
                                                                                                                        /usr/local/Caskroom/android-sdk/4333796/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/type_traits:3501:0
                                                                                                                        void std::__ndk1::__thread_execute<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, realm::_impl::ExternalCommitHelper::DaemonThread::DaemonThread()::$_0>(std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, realm::_impl::ExternalCommitHelper::DaemonThread::DaemonThread()::$_0>&, std::__ndk1::__tuple_indices<>)
                                                                                                                        /usr/local/Caskroom/android-sdk/4333796/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/thread:273:0
                                                                                                                        void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, realm::_impl::ExternalCommitHelper::DaemonThread::DaemonThread()::$_0> >(void*)
                                                                                                                        /usr/local/Caskroom/android-sdk/4333796/ndk/21.0.6113669/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/thread:283:0
#17 0x00000000000e28e0 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
#18 0x000000000008503c /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

**Comment by edualonso** [comment] 2020-10-05 11:57
Second stack trace:
```
********** Crash dump: **********
#00 0x00000000002a449c /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::util::EncryptedFileMapping::get_local_index_of_address(void const*, unsigned long) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/util/encrypted_file_mapping.hpp:149:90
                                                                                                                        realm::util::EncryptedFileMapping::read_barrier(void const*, unsigned long, unsigned long (*)(char const*))
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/util/encrypted_file_mapping.cpp:793:0
#01 0x000000000011a324 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::util::do_encryption_read_barrier(void const*, unsigned long, unsigned long (*)(char const*), realm::util::EncryptedFileMapping*)
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/distribution/realm-core/core-5.0.28/include/realm/util/file_mapper.hpp:133:14
#02 0x000000000011a25c /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::Allocator::translate(unsigned long) const
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/distribution/realm-core/core-5.0.28/include/realm/alloc.hpp:515:9
#03 0x000000000024802c /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterNodeInner::find_child(realm::ObjKey, realm::ClusterNodeInner::ChildInfo&) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:172:38
#04 0x0000000000247f0c /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterNodeInner::try_get(realm::ObjKey, realm::ClusterNode::State&) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:365:0
#05 0x0000000000247ac4 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterNode::get(realm::ObjKey, realm::ClusterNode::State&) const
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:222:16
#06 0x000000000024c7e4 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::ClusterTree::get(realm::ObjKey)
                                                                                                                        /mnt/jenkins/workspace/realm_realm-core_release_6.1.3@3/build-android-arm64-v8a-Release/../src/realm/cluster.cpp:1975:13
#07 0x0000000000170124 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::Table::get_object(realm::ObjKey)
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/distribution/realm-core/core-5.0.28/include/realm/table.hpp:295:27
                                                                                                                        realm::TableView::get(unsigned long)
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/distribution/realm-core/core-5.0.28/include/realm/table_view.hpp:696:0
#08 0x000000000016ebb8 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::util::Optional<realm::Obj> realm::Results::try_get<realm::Obj>(unsigned long)
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/object-store/src/results.cpp:311:33
#09 0x000000000016ea50 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000)
                                                                                                                        realm::Obj realm::Results::get<realm::Obj>(unsigned long)
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/object-store/src/results.cpp:320:20
#10 0x0000000000118324 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/split_config.arm64_v8a.apk!librealm-jni.so (offset 0x24a000) (Java_io_realm_internal_OsResults_nativeGetRow+28)
                                                                                                                        Java_io_realm_internal_OsResults_nativeGetRow
                                                                                                                        /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp:95:42
#11 0x000000000017ee00 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (art_jni_trampoline+160)
#12 0x00000000005c2dbc /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (io.realm.internal.OsResults.a+76)
#13 0x000000000053f2cc /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (io.realm.internal.OsResults$b.a+60)
#14 0x000000000053f560 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.odex (io.realm.internal.OsResults$b.next+128)
#15 0x0000000002004990 /memfd:/jit-cache (com.myapp.app.sync.image.ImageDownloadService.e+2512)
#16 0x0000000000137334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
#17 0x0000000000145fec /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
#18 0x00000000002e3730 /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384)
#19 0x00000000002de990 /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+892)
#20 0x00000000005a3500 /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+424)
#21 0x0000000000131914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
#22 0x0000000000463cbc /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.vdex (com.myapp.app.sync.image.ImageDownloadService.b+256)
#23 0x00000000005a75e8 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1292)
#24 0x0000000000135594 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
#25 0x0000000000463476 /data/app/com.myapp.android-pfcB6ThCsuAij6NifS787w==/oat/arm64/base.vdex (com.myapp.app.sync.image.d.run+16)
#26 0x00000000002b4a44 /apex/com.android.runtime/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.987302922385293720)+240)
#27 0x0000000000592740 /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032)
#28 0x0000000000140468 /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
#29 0x00000000007f0dbc /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+76)
#30 0x00000000007f4498 /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+1448)
#31 0x00000000007f2e04 /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+548)
#32 0x0000000000137334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
#33 0x0000000000145fec /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
#34 0x00000000004b0dd8 /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
#35 0x00000000004b1eec /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
#36 0x00000000004f2e58 /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
#37 0x00000000000e6f10 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
#38 0x00000000000850c8 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

**Comment by edualonso** [comment] 2020-10-05 12:42
@jedelbo can you have a look at this? It seems to be the same problem @sdex already reported in https://github.com/realm/realm-java/issues/7118#issuecomment-696592984 and it is still causing issues.

**Comment by ganfra** [comment] 2020-10-16 09:29
Any news on that? got the same issue

**Comment by clementetb** [comment] 2020-10-16 11:42
@ganfra Could you share more details about the issue you experienced? It would really help us to find the cause.

Do you have any stack trace? What Realm and tooling versions did you use? Can you reproduce the issue?

**Comment by jedelbo** [comment] 2020-11-04 09:54
Seems to be another instance of memory mapping problem. Assigning to @finnschiermer

**Comment by finnschiermer** [comment] 2021-06-02 14:35
Fixed by https://github.com/realm/realm-core/pull/4417 and https://github.com/realm/realm-core/pull/4415

**Closed by finnschiermer** 2021-06-02 14:35 UTC
Labels: O-Community, T-Bug-Crash
