### ISSUE TITLE
Problem with distinct in realmresults 1.20

### ISSUE THREAD

**Issue by michaelbukachi** [realm/realm-java#3411] opened 2016-09-07 13:38 UTC
I've noticed some strange behaviour with the distinct method of a RealmResults object. Whenever I fetch data sorted in descending descending order and call the distinct value on the results, it seems the last distinct value is selected instead of the first e.g:
AA
AA
AA

in the situation above, the last AA would be selected instead of the first. In realm 1.1.1 it used to be the first. Was there a change made to realm cause I checked the changelog and didn't see anything

**Comment by Zhuinden** [comment] 2016-09-07 13:41
Well it **does** say that the selected element by `distinct()` can be pretty much any element that has that value as its value, and order is undefined... although the sort speed optimization could have changed it.

I don't really know about what happened there because that's in the Core.

**Comment by michaelbukachi** [comment] 2016-09-07 13:44
Well before it was random, it was always the first distinct element. So I built my query based on that and it has always worked till now

**Comment by Zhuinden** [comment] 2016-09-07 14:06
Okay wait a second, the docs say

distinct
> public RealmResults<E> distinct(String fieldName)
> Returns a distinct set of objects of a specific class. If the result is sorted, the first object will be returned in case of multiple occurrences, otherwise it is undefined which object is returned.
> Parameters:
> fieldName - the field name.
> Returns:
> a non-null RealmResults containing the distinct objects.
> Throws:
> IllegalArgumentException - if a field is null, does not exist, is an unsupported type, is not indexed, or > points to linked fields.

You **should** get the first element in case of sorted results.

Are you sure it no longer returns the first element consistently? Because that'd be quite the bug. :|

**Comment by michaelbukachi** [comment] 2016-09-07 14:13
`realm.where(Memo.class).equalTo("isFile", false).findAllSortedAsync("date", Sort.DESCENDING);`
This is the query for fetching data so the data should be sorted in descending order.

`private RealmChangeListener<RealmResults<Memo>> listener = new RealmChangeListener<RealmResults<Memo>>() {
        @Override
        public void onChange(RealmResults<Memo> element) {
            if (!element.isEmpty()) {
                adapter.updateData(element.distinct("connection"));
                adapter.notifyDataSetChanged();
            }
            empty.setVisibility(adapter.getItemCount() == 0 ? View.VISIBLE : View.GONE);
        }
    };`
Here the query results are filtered out. I've confirmed that the results are in descending order. but the last element in the results is selected instead of the first

**Comment by beeender** [comment] 2016-09-08 06:24
@michaelbukachi Can you please list the values of `RealmResults<Memo> element` and values of the `element.distinct("connection")` here?

**Comment by michaelbukachi** [comment] 2016-09-08 10:47
test3
test2
test1

but the output for distinct is 
test1

**Comment by beeender** [comment] 2016-09-08 11:59
Sorry, i didn't ask this clearly. Can you share all the fields of `RealmResults<Memo> element` and results of the `element.distinct("connection")`?? If you can reproduce the problem with a sample project, that will be great. You can send the project to help@realm.io if you want to share it privately.

**Comment by michaelbukachi** [comment] 2016-09-08 12:03
```
public class Memo extends RealmObject {
    @Ignore
    public static final int SENT = 1;
    @Ignore
    public static final int UNREAD = 2;
    @Ignore
    public static final int READ = 3;
    @Ignore
    public static final int PENDING = 4;
    private static final String TAG = Memo.class.getName();
    @PrimaryKey
    public String id = "";
    @Index
    public String connection = "";
    public String subject = "";
    public String body = "";
    public int status = 0;
    public Date date;
    @Index
    public Boolean latest = false;
    public Boolean sentByMe = false;
    public String remoteId = "";
    public Boolean isFile = false;
    public String filepath = "";
}
```
Lemme try to recreate the bug in a new project

**Comment by Zhuinden** [comment] 2016-09-08 12:05
This RealmObject is [eerily familiar](http://stackoverflow.com/a/39378844/2413303)...

**Comment by michaelbukachi** [comment] 2016-09-08 12:07
I created that question on stackoverflow. I thought my query was the problem at first. but it wasn't

**Comment by Zhuinden** [comment] 2016-09-08 12:11
I'm not sure how Realm is supposed to tell which one is "newer" in its sort when their values are all the same, though. :|

**Comment by michaelbukachi** [comment] 2016-09-08 12:19
the memos are fetched in descending order according to the date field which is different for all of them. but i only need the first memo in the list returned

**Comment by kneth** [comment] 2016-09-28 12:14
Similar to #3503.

**Comment by michaelbukachi** [comment] 2016-10-09 13:09
So I've upgraded to Realm 2.0.1 but the issue is still persistent

**Comment by Zhuinden** [comment] 2016-10-09 13:31
Yeah, they know. I've seen the pull request about it. The fix is in the works. Apparently distinct has its own sort parameter, but it always sends down ASCENDING in the JNI layer. So they're fixing that.

**Comment by cmelchior** [comment] 2017-01-24 08:26
Folding this issue into #3503

**Closed by cmelchior** 2017-01-24 08:26 UTC
Labels: S:P1 Backlog, T:Bug
