### ISSUE TITLE
Add @Generated("realm") annotation to generated classes

### ISSUE THREAD

**Issue by maoueh** [realm/realm-java#4329] opened 2017-03-15 20:26 UTC
#### Goal

Be able to suppress ErrorProne warnings on Realm generated classes.

#### Expected Results

Right now, generated classes miss a lot of `@Overidde` annotation which makes warnings (and error when treating warnings as errors) when compiler process Realm generated classes (like ModelRealmProxy).

ErrorProne has a way to ignore any validations for classes that are generated. But to work, the generated classes must have a `@Generated(<value>)` annotation.

I request that the code generator project adds the `@Generated("realm")` annotation to all generated classes.

I checked `JavaWriter` class and it should in theory simple as adding `emitAnnotation("Generated", "realm")` at right location, like at top of class. For `RealmProxy`, it would be around here probably: https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java#L97

I maybe would have time to propose a PR, is it possible to only recompile realm-annotation-processor and replace it in my project to test it? I would like to avoid having to compile everything.

**Comment by beeender** [comment] 2017-03-16 01:57
I think we should fix the warning instead of suppressing them. @realm/java your thoughts?

BTW, to use a local build of Realm in your project:
1. clone the realm-java repo
2. `./gradlew installRealmJava`
3. add `mavenLocal()` to your root project `build.gradle`. there are two places need to be added in. See https://github.com/realm/realm-java/blob/master/examples/build.gradle
4. change your realm version to the version you build in the `build.gradle`. see `version.txt` under realm-java repo.
5. after modify the processor, you need run `./gradlew installRealmJava` again to install it to the maven local.

PS.: It will be easier if you debug it with annotation processor's unit tests.

**Comment by cmelchior** [comment] 2017-03-16 07:19
Yes, fixing the warning is a better approach IMO, but If I remember correctly, there is a technical reason for not marking the methods as overridden, perhaps @emanuelez  remembers?

It also looks like the `@Generated` annotation lives under the javax package, which might also be problematic? http://stackoverflow.com/questions/37046649/pojos-generated-by-jsonschema2pojo-have-annotation-which-android-studio-doesnt

**Comment by beeender** [comment] 2017-03-16 07:57
The `@Override` is not added during annotation processing is because of those methods will be added later in the parent class when doing byte code transforming.

**Comment by cmelchior** [comment] 2017-03-16 08:01
Ah, yeah, it is because we the the interface through JavaAssist and without the interface, there is nothing to override.

**Comment by emanuelez** [comment] 2017-03-16 08:04
See? I thought of everything! :-P

**Comment by cmelchior** [comment] 2017-03-16 08:21
It looks like the `@Generated` annotation has SOURCE retention, so the annotation will be stripped from the model class files, but I am not 100% sure how we can add those `javax` annotations so they are available for the annotation processor/app, but won't be packaged in the app. Perhaps just adding it as a `provided` dependency is good enough.

Given that it is a standard annotation, I wouldn't be totally against us doing that.

**Comment by zaki50** [comment] 2017-03-17 06:41
I think we can add `Override` annotations because we already have interfaces and overriding methods at compile time (adding `Override` annotation to methods that implement a method defined in a interface is completely valid). So we should fix those warnings.

At the same time, I think we should also add `Generated` annotations to generated classes.

**Comment by zaki50** [comment] 2017-03-17 08:51
Ah, I didn't know that `java.annotation.Generated` is not included in android.

Adding that annotation needs to require for all Realm users to include `javax.annotation:javax.annotation-api:1.2` as a provided dependency.

Now I think adding `Override` annotation is enough.

**Comment by zaki50** [comment] 2017-03-17 11:42
@maoueh I've added following code to `app/build.gradle` in order to reproduce the warngins, but no success. How do you configure your project to get the warnings?

```
afterEvaluate {
    tasks.withType(JavaCompile) {
        options.compilerArgs << '-Xlint:all'
    }
}
```

**Comment by zaki50** [comment] 2017-03-17 12:45
I've got expected warnings with error prone plugin!

**Comment by maoueh** [comment] 2017-03-17 14:02
@zaki50 Yeah warnings are given by ErrorProne, not normal Java.

The best solution would be to have both indeed. It's generated code so having the annotation would make perfect sense.

But I understand that it may have unintended consequences that we might not want. Specially since 1, I did not see Android projects using it (from what I use at least) and 2, it seems to also cause some dependency problems.

So, If you just fix the warnings, that would be good for now. I will report other warnings if they come around later :)

**Comment by zaki50** [comment] 2017-03-17 19:17
@maoueh I've created PRs that fix warnings in generated classes.

After the merge of #4338, #4341 and #4342, we should not see any warnings from `ErrorProne`.

**Comment by cmelchior** [comment] 2017-03-20 10:57
#4338 has been merged. Closing

**Closed by cmelchior** 2017-03-20 10:57 UTC
Labels: S:In Progress, T:Enhancement
