### ISSUE TITLE
Note: Processing class xxx messages should be optional

### ISSUE THREAD

**Issue by WonderCsabo** [realm/realm-java#4332] opened 2017-03-16 09:28 UTC
#### Goal

The build is cluttered with *Note: Processing class xxx* messages. These messages may help sometimes, but normally they are not interesting at all, and adding too much noise to the build log.

#### Expected Results

The messages should not be printed, or an annotation processing option should be introduced to control their behavior.

#### Actual Results

The messages are always printed, adding lots of noise to the build.

#### Version of Realm and tooling
Realm version: 2.3.0.
Android Studio version: 2.3

**Comment by kneth** [comment] 2017-03-16 14:54
I don't think it is a good idea to suppress them at all times. #4333 is an example where you need to see them. But a way to opt out might be useful in some cases.

**Comment by pvegh** [comment] 2018-06-07 07:09
I want these messages gone. Make them appear with --debug if needed, or add 1 line of hint to do so, but please keep my build output clean!

**Comment by cmelchior** [comment] 2020-08-20 19:57
Duplicate of #5713

**Closed by cmelchior** 2020-08-20 19:57 UTC
Labels: O-Community, T-Enhancement
