### ISSUE TITLE
Large transaction on background thread

### ISSUE THREAD

**Issue by rimeissner** [realm/realm-java#2036] opened 2016-01-06 10:57 UTC
Hey,

when we get data from our servers we parse the response on a background thread and in the same step we insert it into our Realm. In some case we get an OOM when we try to change some Realm objects. 

I assume that this is due to the fact, that there is no auto-refresh on the background thread and therefore Realm might use up a lot of memory to keep the diff.

We already split up all big transactions to multiple small transactions and we call refresh to minimise the diff that has to be kept.

Can you recommend more improvements to avoid OOMs?

(Another use case of us is a long running background that that is accessing the Realm from time to time. In this case we are currently closing the realm and reopening it to a later point to avoid a large diff. Also we moved the models that are accessed by the background thread to a different Realm so that changes on other models don't affect the diff size.)

**Comment by kneth** [comment] 2016-01-06 15:15
Having a long-lived transaction can increase the size of your Realm file: see https://realm.io/docs/java/latest/#faq under *Large Realm file size*.

Splitting into smaller transactions might help you but you have already realized that.

If you can close all Realm instances, you can compact the Realm file. During compaction, free space and  old versions will be removed.

**Comment by rimeissner** [comment] 2016-01-06 15:54
Is `.refresh()`also helpful in this case? Currently we try to call `.refresh()` fairly often so that Realm can discard old version.

**Comment by cmelchior** [comment] 2016-01-06 16:16
Hi @rimeissner Is it an OOM message coming from Realm or from normal Java. In the former case, `refresh()` will help, but given the amount of native memory available, it sounds more like the problem is elsewhere.

- Background threads are normally 1-shot jobs, so opening a Realm when starting the job and closing when done should be enough to combat any memory leaks. The overhead is negligible compared to any network I/O. 

- Depending on your size of data coming in from the network, you might want to avoid any JSON API's that map to proper Java objects first as that puts a lot of pressure on Java heap. Using something like the Jackson streaming API or Realms JsonReader methods allow you to input JSON using streams.

Can you provide some more information about what your background threads do and how much data they handle as that will make it easier to see if there is something we can do to avoid hitting OOM.

**Comment by beeender** [comment] 2016-01-06 16:22
The old version will consume memory if the Realm in a thread is still holding reference to it. And i don't think you need to call refresh manually, because of:

1. Realm will be automatically refreshed if the owner thread has a Looper.
2. Realm (point to the same file) will share one instance in the same thread.
3. Realm instance itself doesn't consume too much memory unless you have lots of RealmObject/RealmResults/RealmQuery created from it and they are not GCed.
4. Normally i don't think a long live Realm (typical use case in UI thread) (in looper thread which can always be updated) will consume too much memory as long as it doesn't have too many RealmObject/RealmResults/RealmQuery to it. So just remember to not hold the reference to RealmObject/RealmResults/RealmQuery when you don't need them anymore just like normal java object.

**Comment by rimeissner** [comment] 2016-01-06 23:36
@cmelchior Our largest request returns a 22421bytes json file. This are about 40 objects in a list. (In some rare cases this count might increase, to more than 200 entries worst case). Each object has 20+ attributes. We do the following steps:

* parse a JsonArray from the result String
* loop through each JsonObject in the array
  * start transaction
  * create or update object from JsonObject
  * commit transaction (or cancel in error case)
* cleanup of old unused objects in realm (actually this is split up in multiple transaction, no json parsing here)

Between each of the steps we perform a `.refresh()` on the Realm so that possible changes from another thread (should only be UI thread) are synced to the Realm of this thread.

@beeender We have some RealmResults that queried at a very early stage and stored in a local variable. As local variables are kept until the end of the scope I would either have to scope this in a block or null the variable that stores the RealmResults (correct?)

**Comment by beeender** [comment] 2016-01-07 01:43
@rimeissner The memory alloced in natvie code for `RealmResults` will be freed when the `RealmResults` gets GCed. So I don't think local variable and scope it in a block will have too much differences.

And as @cmelchior asked, where does the OOM message come from? Is it from Realm native code or a normal java OOM message? Can you post the message here?

**Comment by rimeissner** [comment] 2016-01-07 08:41
The error is always a RealmError, but only in some cases it is also with the following message:
```
Fatal Exception: io.realm.exceptions.RealmError
Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188
```

The idea with the scope is, that it cannot be freed by a GC cycle when we sill have a local reference, when we scope it, then it should be possible to free it in the next GC cycle (that should occur when the system is under memory pressure)

**Comment by beeender** [comment] 2016-01-07 08:49
Hi, that usually caused when the Realm file is too large. 

Check this similar issues https://github.com/realm/realm-java/search?q=mmap+Out+of+memory&type=Issues&utf8=%E2%9C%93

And find a right timing (like starting of the app) to call `Realm.compactRealm` will also help.

**Comment by rimeissner** [comment] 2016-01-07 09:16
I think in our case that also might have been due to another thread that kept a Realm instance open for way too long.

I will try out `compactRealm`. Is this a time consuming operation or can it be performed on the UI Thread (in out case that would be in `onCreate` of the Application class)?

Thanks for the help.

**Comment by cmelchior** [comment] 2016-01-07 12:07
`compactRealm` is potentially time-consuming, so I wouldn't recommend running it on the UI thread.

**Comment by rimeissner** [comment] 2016-01-07 12:31
ok thanks for the info

**Comment by phearme** [comment] 2016-01-11 05:42
I am also experiencing the same exception and currently investigating on it:
```Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188```
In this project, all read operations can come from different threads but each read thread getting a realm instance does close it immediately after use. All write transactions are handle by the same looper thread.
Does this OOM exception gets thrown only when realm file is "too large" or also when the device is low on memory? What is the realm file size for which this exception can be thrown? Thanks!

**Comment by kneth** [comment] 2016-01-11 09:11
Out-of-memory can occur in different situations. Realm use `mmap()` in the C++ layers, and thereby Realm doesn't use the Java heap. A large Realm file can lead to out-of-memory if the device is low on memory or the file system is full. See also https://realm.io/docs/java/latest/#faq ("What to do about our-of-memory exceptions?" and "Large Realm file size").

**Comment by cmelchior** [comment] 2016-01-21 08:46
The original questions seems to be answered, so i'll close this issue now. Please reopen if that is not the case.

**Closed by cmelchior** 2016-01-21 08:46 UTC
Labels: Help, Pending

**Comment by rimeissner** [comment] 2016-06-10 12:11
We are currently in the progress of updating realm (huge jump from 0.88.3 to 1.0.0) and realised that `.refresh()` has been replaced with `.waitForChange()` which is blocking the Thread. We still have some fairly long-running background threads that access the realm and used `.refresh()` to minimise the diff that was necessary. What is the recommended way for that without blocking that background thread by using `.waitForChange()`

**Comment by cmelchior** [comment] 2016-06-10 12:13
Closing the Realm and opening it again will also work. I assume you don't refresh in the middle of some code executing, but at the start of some loop?

**Comment by rimeissner** [comment] 2016-06-10 12:26
We do something like

beginTransaction
-> loop over old objects and delete them
commitTransaction

*refresh*

beginTransaction
-> loop over new object and insert them
commitTransaction

**Comment by rimeissner** [comment] 2016-06-10 13:28
@cmelchior Is there no other alternative than closing the realm instance and opening a new one? ... on iOS the `refresh()` method is still present.

**Comment by kneth** [comment] 2016-06-10 14:04
`beginTransaction` will bring the instance up-to-update.

**Comment by spl** [comment] 2016-06-10 14:13
> `beginTransaction` will bring the instance up-to-update.

@kneth Ooh, that's good to know. Is that a global invariant that you promise to never change (as opposed to a coincidence of implementation)? Is it documented somewhere? (I certainly may have missed it.) If not, can I suggest it be added to your wonderful documentation? Thanks!

(Sorry to sidetrack the conversation. Just wanted to jump on that note with some questions.)

**Comment by cmelchior** [comment] 2016-06-10 14:23
@spl Yes, it is documented as part of `beginTransaction`. Although it could be more clear there. It is especially important if you query outside the transaction and start accessing the object inside. If another thread deleted the object in between, you get an IllegalStateException.

**Comment by rimeissner** [comment] 2016-06-10 14:25
this will solve my problem since I only to that in combinations with transactions. ty

**Comment by spl** [comment] 2016-06-10 15:22
@cmelchior Cool. Thanks! I see [it](https://realm.io/docs/java/1.0.0/api/io/realm/Realm.html#beginTransaction--) now:

> Before beginning the transaction, `BaseRealm.beginTransaction()` updates the Realm in the case of pending updates from other threads.

Is it true that you could do this to force a refresh for queries on a given `realm` (assuming that's all you needed)?

```java
// 1. Refresh the realm.
realm.beginTransaction();
realm.endTransaction();
// or
realm.executeTransaction(new Realm.Transaction() {@Overridepublic void execute(Realm realm) {}});

// 2. Query from updated realm.
Blah blah = realm.where(Blah.class).equalTo("name", "Blah");
```

**Comment by rimeissner** [comment] 2016-06-13 07:25
@cmelchior We are running an espresso ui test where we mock data in realm and check afterwards if the data has changed. Now that `.refresh()` is not available anymore the test fail, because the data is not updated. Can I use the method mentioned by @spl to get around that problem?

**Comment by Miger88** [comment] 2016-11-08 10:21
Hello, 
for me it works to open and close the realm database at beginning and end of all my methods working with the database. 
At the beginning I open it with this code 
`Realm.init(Context ctx);
realm = Realm.getDefaultInstance();
`
and at the end I call 

`realm.close();`

I didn't get oom Exceptions since using this.

**Comment by Zhuinden** [comment] 2016-11-08 11:45
@rimeissner you can [force a refresh through the `handlerController`](http://stackoverflow.com/a/38839808/2413303)
