### ISSUE TITLE
How update pojos only with specific IDs?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6225] opened 2018-10-09 12:14 UTC
In my Android application I has pojo:

```
public class Product extends RealmObject {
    @PrimaryKey
    private long id;
    private float price;
    private boolean favorite;
}

```

Suppose in Realm table I has 100 products. Nice.
Now I want to update property `favorite = true` only of 5 products with `id`= **1, 14, 38, 78, 90**.

I need something like this:

`UPDATE Product SET favorite = true WHERE id in [1, 14, 38, 78, 90]`

How I can do this?

Thanks.

**Comment by Zhuinden** [comment] 2018-10-09 12:48
realm.executeTransaction { realm ->
        for(long id in ids) {
            val product = realm.where<Product>().equalTo("id", id).findFirst()
            product.isFavorite = true
        }
    }

**Comment by cmelchior** [comment] 2018-10-10 21:12
Yeah, I really hope I get a chance to finish that up soon 😢 
Closing as a duplicate of #762

**Closed by cmelchior** 2018-10-10 21:12 UTC
Labels: O:User

**Comment by lmdic** [comment] 2018-10-11 07:43
> Yeah, I really hope I get a chance to finish that up soon 😢
> Closing as a duplicate of #762

it would be great.
