### ISSUE TITLE
Crash - didn't find class "io.realm.internal.network.NetworkStateReceiver"

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#3505] opened 2016-09-27 21:19 UTC
Hi, with the new Realm 2.0 I am getting crash as below:
```
java.lang.RuntimeException: Unable to instantiate receiver io.realm.internal.network.NetworkStateReceiver: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver"
```

**Comment by Zhuinden** [comment] 2016-09-27 21:22
Did you do a Clean + Rebuild?

**Comment by zaki50** [comment] 2016-09-28 05:23
I reproduced this.

conditions:
`syncEnabled` is `false`.
`android.net.conn.CONNECTIVITY_CHANGE` broadcast is fired.

The easiest way to reproduce is to execute `adb shell am broadcast -a android.net.conn.CONNECTIVITY_CHANGE`

**Comment by peterbetos** [comment] 2016-09-28 10:37
This is reproducible.

**Comment by mikelis-kaneps** [comment] 2016-09-28 13:01
Yes, I have the same problem. Is there a way how to fix this?

**Comment by Zhuinden** [comment] 2016-09-28 13:10
2.0.1 will fix it

**Comment by phearme** [comment] 2016-09-28 15:40
++;

**Comment by mishindmitriy** [comment] 2016-09-28 16:16
I have the same problem

**Comment by RJFares** [comment] 2016-09-28 16:38
+1

**Comment by smoonsf** [comment] 2016-09-29 00:51
+1

**Comment by lizixian18** [comment] 2016-09-29 01:33
I have also encountered this problem

**Comment by zaki50** [comment] 2016-09-29 01:36
already fixed in `releases` branch.
please wait a bit

**Comment by status-development** [comment] 2016-09-29 09:17
Same here, when can we expect 2.0.1?

**Comment by neetrath** [comment] 2016-09-29 10:26
+1

**Comment by Dimous** [comment] 2016-09-29 12:28
Why realm listen to network state?

**Comment by cmelchior** [comment] 2016-09-29 12:34
@Dimous Only our Mobile Platform Extension does that. Mostly because it allows us to do more intelligent error handling. 

We hope to be able to ship 2.0.1 today with a fix for this.

**Comment by Domacoski** [comment] 2016-09-29 20:05
+1

**Comment by samvanderhyden** [comment] 2016-09-29 21:57
+1

**Comment by GulajavaMinistudio** [comment] 2016-09-29 22:04
Same here, when can we a bug fix release ?

**Comment by Tingmo-Tingspo** [comment] 2016-09-30 05:16
+ 1

**Comment by hateum** [comment] 2016-09-30 15:42
is there any way to prevent the crash ?

**Comment by Zhuinden** [comment] 2016-09-30 15:43
Well until 2.0.1 is released, you **can** add a broadcast receiver by the same name in the same package and all that.

**Comment by hateum** [comment] 2016-09-30 16:17
I added this class to my project with the same package Realm and now there is no crash.
https://github.com/realm/realm-java/blob/1062d2462eaf841c215d7962dea979f65032fb5a/realm/realm-library/src/objectServer/java/io/realm/internal/network/NetworkStateReceiver.java
Thanks

**Comment by pauloleitemoreira** [comment] 2016-09-30 20:37
+1

**Comment by takke** [comment] 2016-10-01 15:18
+1

**Comment by avalenzuelac** [comment] 2016-10-02 13:44
+1

**Comment by shahrukhamd** [comment] 2016-10-03 03:47
I shipped my app to production with Realm 2.0.0 and because of this issue my **crash free users are at 17.5% only** (down from 99.8%). **Please fix that issue ASAP**.

**Comment by pratamawijaya** [comment] 2016-10-03 03:54
+1

**Comment by neetrath** [comment] 2016-10-03 03:56
I have to temporary revert back to version 1.2.0

**Comment by cchcc** [comment] 2016-10-04 01:15
+1

**Comment by ezanetta** [comment] 2016-10-04 01:16
+1

**Comment by jsadovskaya** [comment] 2016-10-04 08:12
+1

**Comment by fuwaneko** [comment] 2016-10-04 09:35
I also shipped an app like @shahrukhamd, and it's horrible now. We depend on third-party libraries and expect releases to be stable and well-tested. This is critical issue and it can potentially destroy your reputation since it's been 7 days already. Also my app now is never closed by the system since Realm listens to network changes. This is totally unacceptable. I understand you want to make money, but it should not interfere with my application in a way that changes it's behaviour. That was the reason I dropped Firebase Crashes in favour of Fabric, since Firebase launched separate process to track crashes which is what I totally don't want.

**Comment by cmelchior** [comment] 2016-10-04 09:44
Hi @fuwaneko 
We are sorry that this error got shipped in 2.0, and we actually wanted to ship a fix last week, but ran into some problems with our build systems unfortunately. Those should be fixed now and we plan to ship 2.0.1 today.

**Comment by fuwaneko** [comment] 2016-10-04 09:46
@cmelchior thank you. I also hope with syncEnabled = false Realm will not listen to network changes.

**Comment by cmelchior** [comment] 2016-10-04 10:07
It will not, it was a mistake it was in the base library. It will only be included in the sync part.

**Comment by Zhuinden** [comment] 2016-10-04 10:32
The snapshot I tried out didn't have this issue, I think this got merged in from realm-java-private ¬¬

**Comment by estebanlagord** [comment] 2016-10-04 12:45
+1 waiting for 2.0.1

**Comment by hisankaran** [comment] 2016-10-04 12:52
Same here, waiting for 2.0.1 :(

**Comment by ahmadalibaloch** [comment] 2016-10-04 12:55
Waitinggggggggggggggggg 🗡

**Comment by tux-world** [comment] 2016-10-04 15:14
+1 and i have same error

**Comment by JSONValidator** [comment] 2016-10-04 18:06
+1

**Comment by Zhuinden** [comment] 2016-10-04 18:22
It's going to happen eventually.

**Comment by kristakrebs** [comment] 2016-10-04 20:52
+1 2.0.1

**Comment by readytopark** [comment] 2016-10-05 01:02
+1

**Comment by allentcm** [comment] 2016-10-05 01:22
+1

**Comment by ahmadalibaloch** [comment] 2016-10-05 03:38
Where is the Realm team sleeping. Recently the have been boasting to release new features and this fatal bug is not resolved after weeks 👎

**Comment by Zhuinden** [comment] 2016-10-05 05:51
@ahmadalibaloch ...man, they **do** know about it. Realm 2.0 has been barely out for a week.

If you wanted to create a quick fix for this problem in the meantime, you would have just added the missing class and released a new version of your app.

https://github.com/realm/realm-java/blob/1062d2462eaf841c215d7962dea979f65032fb5a/realm/realm-library/src/objectServer/java/io/realm/internal/network/NetworkStateReceiver.java

(I am still not an official Realm person).

**Comment by pc-bszabo** [comment] 2016-10-05 06:16
Quick and dirty solution : put this into your launcher activity =>

**Comment by Zhuinden** [comment] 2016-10-05 06:41
I actually didn't know you could do that. Cool.

**Comment by hisankaran** [comment] 2016-10-05 08:20
awesome @pc-bszabo! I have added the following code to Application onCreate

`try {
            ComponentName componentName = new ComponentName(
                    getApplicationContext(),
                    "io.realm.internal.network.NetworkStateReceiver"
            );
            getPackageManager()
                    .setComponentEnabledSetting(
                            componentName,
                            PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
                            PackageManager.DONT_KILL_APP);
        } catch (Exception ignored) {}`

and it works!

Someone has written a blog on [http://www.grokkingandroid.com/enabling-and-disabling-broadcastreceivers/](disabling BroadcastReceivers)

**Comment by ahmadalibaloch** [comment] 2016-10-05 08:24
@pc-bszabo Thanks a lot.

**Comment by cmelchior** [comment] 2016-10-05 08:31
2.0.1 has just been released fixing this bug. The network receiver is now only added if you enable Sync as well.

I could list all the technical and process difficulties involved in getting this release out the door, but in reality we just dropped the ball on this, and I'm very sorry for those of you that got affected by this. We can only strive to do better in the future.

Closing.

**Closed by cmelchior** 2016-10-05 08:31 UTC
Labels: S:P1 Backlog, T:Bug-Crash

**Comment by ahmadalibaloch** [comment] 2016-10-05 08:58
We appreciate your hard work. 👍

**Comment by XabierGoros** [comment] 2016-10-05 13:49
Indeed we appreciate the work of the Realm team. On the other side, IMHO we should be more cautious when criticising and hurrying up a team like this whose software is open sourced for us.

Once again, thanks!
