### ISSUE TITLE
Native crash in TableQuery.cpp line 1543

### ISSUE THREAD

**Issue by raminbbt** [realm/realm-java#1851] opened 2015-11-28 11:40 UTC
im currently using latest snapshot version. i also used latest release version but same error.
```
D/REALM﹕ REALM_CHANGED realm:io.realm.HandlerController@41f9e5a0 no async queries, advance_read
D/REALM﹕ REALM_CHANGED realm:io.realm.HandlerController@41bc2690 updating async queries, total: 3
D/REALM﹕ REALM_UPDATE_ASYNC_QUERIES realm:io.realm.HandlerController@41bc2690 caller is behind  advance_read
D/REALM﹕ REALM_UPDATE_ASYNC_QUERIES realm:io.realm.HandlerController@41bc2690 updating RealmResults java.lang.ref.WeakReference@41bc9e88
D/REALM﹕ jni: ThrowingException 11, std::exception in io_realm_internal_TableQuery.cpp line 1543, .
D/REALM﹕ Exception has been throw: Unrecoverable error. std::exception in io_realm_internal_TableQuery.cpp line 1543
D/AndroidRuntime﹕ Shutting down VM
W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4168ace0)
W/System.err﹕ io.realm.exceptions.RealmError: Unrecoverable error. std::exception in io_realm_internal_TableQuery.cpp line 1543
W/System.err﹕ at io.realm.internal.TableQuery.nativeImportHandoverTableViewIntoSharedGroup(Native Method)
W/System.err﹕ at io.realm.internal.TableQuery.importHandoverTableView(TableQuery.java:508)
W/System.err﹕ at io.realm.RealmResults.swapTableViewPointer(RealmResults.java:708)
W/System.err﹕ at io.realm.HandlerController.completedAsyncQueriesUpdate(HandlerController.java:222)
W/System.err﹕ at io.realm.HandlerController.handleMessage(HandlerController.java:312)
W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5158)
W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
```

all 3 asyncQueries are active and listening for changes and i also call `results.removeChangeListeners()` properly when closing fragments

**Comment by beeender** [comment] 2015-11-30 04:39
Hi would you please let us know how to reproduce this issue? Is it possible for you to create a sample project to reproduce this and share with us? Or if you want, you can share your project privately to help@realm.io .

**Comment by raminbbt** [comment] 2015-11-30 15:44
I think i found out why is this happening.
my application is a messaging app with delivery report feature.

# Not crashing in this situation:
``` 
user A sends message to user B
user B sees the message and sends back delivery report
user A receives the delivery and updates the message table and ui
```

# Crashing situation:
```
user A sends message to user B
user B is busy [ dont want to see the message now ]
user A sends message again and aging ....
user B have for example 10 unread message from user A
user B opens chat with user A and sends back all 10 unread message delivery report
user A receives 10 delivery reporsts [ updates messages table ] AND CRASH happens here.
```

**Comment by nhachicha** [comment] 2015-11-30 16:34
Hi @raminbbt 
could you please activate the shared library log  `io.realm.internal.Util.setDebugLevel(5)` and attach a Realm verbose log `RealmLog.add(new DebugAndroidLogger());` so we can investigate more?

Cheers

**Comment by raminbbt** [comment] 2015-11-30 20:10
Hi @nhachicha .
i attached two log files with options `io.realm.internal.Util.setDebugLevel(5)` and 
 `RealmLog.add(new DebugAndroidLogger());` enabled.
log   --> crashed because of `Fatal signal 11`
log2 --> crashed because of `TableQuery.cpp line 1543`
[Log.txt](https://github.com/realm/realm-java/files/47727/Log.txt)
[Log2.txt](https://github.com/realm/realm-java/files/47728/Log2.txt)

**Comment by franciscojrp** [comment] 2015-12-02 18:27
I'm also getting this error every time the app is syncing phone contacts from scratch to the data base.
I open and commit a transaction per contact because the number of contacts may be very high and the process could take a lot of time and block other threads that may want to save to the data base.
In the meantime when this happens there is a query in an UI fragment waiting for a contact with some fields filled:
```
mContactResults = mRealm.where(Contact.class).isNotNull("cover").isNotNull("picture").findAllAsync();
mContactResults.addChangeListener(
        new RealmChangeListener() {
                    @Override
                    public void onChange() {
                        Log.d(TAG, "mContactResults updated. Let's change bg image");
                        changeBackgroundImage();
                    }
       });
```
So, background thread creating Contacts without those fields filled (I don't get why the listener should be fired everytime) and after a few contacts I get the crash
```
io.realm.exceptions.RealmError: Unrecoverable error. std::exception in io_realm_internal_TableQuery.cpp line 1543
```
I'm using version 0.85.1
[log.txt](https://github.com/realm/realm-java/files/50031/log.txt)

**Comment by beeender** [comment] 2015-12-03 02:57
Look likes a bug, we are trying to reproduce it. I will report here if we have any progress.

**Comment by beeender** [comment] 2015-12-03 04:24
Could be the same issue with #1645

**Comment by beeender** [comment] 2015-12-03 07:47
We can reproduce this issue now. We are working on the solution.

**Comment by vikas-fueled** [comment] 2015-12-03 08:49
I also encountered this issue when I am syncing contents from server in different thread and at the same time app is displaying contents.

Attaching my logs for Nexus 5 running M preview 3
[crash_log.txt](https://github.com/realm/realm-java/files/50593/crash_log.txt)

**Comment by slidenerd** [comment] 2015-12-03 10:41
@franciscojrp  did you try removing the realmchangelistener right after adding it?

**Comment by franciscojrp** [comment] 2015-12-03 10:47
That is what I normally do, I remove the change listener from the onChange method after I find some contact that meets the conditions.
Testing this problem I simply not added the listener and the problems was still there.

**Comment by slidenerd** [comment] 2015-12-03 16:03
I got the same issue @franciscojrp  but I have not been able to reproduce it on API 21 and later, what about you?

**Comment by Kistamushken** [comment] 2015-12-10 09:46
Same problem here. Any updates when this issue is going to be fixed?

**Comment by raminbbt** [comment] 2015-12-10 13:02
this crash happens only when i update table inside a thread without looper.
try updating tables inside `android.os.HandlerThread`

**Comment by Kistamushken** [comment] 2015-12-10 14:29
@raminbbt Well i usually update my tables like this
``` 
public void performBatchWrite(RealmList<?> objects, Realm realm, Realm.Transaction.Callback callback) {
        realm.executeTransaction(bgRealm ->
                bgRealm.copyToRealmOrUpdate(objects), callback);
    }
``` 
And I always open Realm in the Main Thread, so looks like the looper is not a main problem here.

**Comment by raminbbt** [comment] 2015-12-10 15:02
`bgRealm` is not opened inside looper thread. `Looper.myLooper()` returns null in `executeTransaction`.
use WorkerThread.java i uploaded and see if crash happens again

example usage:
````
public static void exampleInsertPerson(final String name, final int age){
        final WorkerThread wt=new WorkerThread("someThreadName");
        wt.start();
        wt.postJob(null, new RealmJOB() {
            @Override
            public void doJob(Realm realm) throws Exception {
                Person person=new Person();
                person.setName(name);
                person.setAge(age);
                realm.copyToRealm(person);
            }
        });
    }
````

**Comment by Kistamushken** [comment] 2015-12-10 15:08
@raminbbt I will try this. By the way, for me this issue is pretty hard to reproduce, I can't figure out 100% scenario to make it happen. The code I provided above gives me like 4 crashes out of ten. I will follow your advice and provide info on how it affected stuff

**Comment by Kistamushken** [comment] 2015-12-10 15:56
@raminbbt performing writes inside a looper thread actually helped. Thanks!

**Comment by cmelchior** [comment] 2015-12-10 19:42
Fixed by https://github.com/realm/realm-java/pull/1895

**Closed by cmelchior** 2015-12-10 19:42 UTC
Labels: bug, Review
