### ISSUE TITLE
 java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by LiuDeng** [realm/realm-java#2139] opened 2016-01-23 07:14 UTC
java.lang.IllegalAccessError: Illegal class access ('io.realm.UserRealmProxy' attempting to access 'io.realm.BaseRealm') in attempt to invoke virtual method void io.realm.BaseRealm.checkIfValid() (declaration of 'io.realm.UserRealmProxy' appears in /data/data/com.qiuduanribao.joke/files/studio-fd/dex/slice_9_e1a298d6ec3d810f745aca6360a4b217f65d0196-classes.dex)
at io.realm.UserRealmProxy.get_id(UserRealmProxy.java:107)

**Comment by cmelchior** [comment] 2016-01-23 16:00
Please seehttps://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when creating issues. That way it is a lot easier for us to help you.

**Comment by PaoloRotolo** [comment] 2016-01-30 19:14
I can confirm it too. It happens when reading from RealM with build tools version 2.0.0-alpha9.

**Comment by bmunkholm** [comment] 2016-02-02 09:37
@paolorotolo: Can you please provide more details so we can reproduce and fix this?

**Comment by degill** [comment] 2016-02-03 15:41
I am sorry that I cant contribute any code to reproduce the error since the error does not comes always. I also use 'com.android.tools.build:gradle:2.0.0-alpha9'.

I first thought that it had something to do with clearing app data (I regularly need to do it). But that doesnt seem to be always the case.

I can provide the Stacktrace:
````
 Caused by: java.lang.IllegalAccessError: Method 'io.realm.RealmObject io.realm.Realm.createObject(java.lang.Class, java.lang.Object)' is inaccessible to class 'io.realm.UserRealmProxy' (declaration of 'io.realm.UserRealmProxy' appears in /data/data/*******/files/studio-fd/dex/slice-slice_9_0695850c2a5f63a0dccccaf96c4308c8a3370ad1-classes.dex)
                                                                                                       at io.realm.UserRealmProxy.createOrUpdateUsingJsonObject(UserRealmProxy.java:501)
                                                                                                       at io.realm.DefaultRealmModuleMediator.createOrUpdateUsingJsonObject(DefaultRealmModuleMediator.java:378)
                                                                                                       at io.realm.Realm.createOrUpdateObjectFromJson(Realm.java:506)
                                                                                                       at io.realm.Realm.createOrUpdateObjectFromJson(Realm.java:565)
                                                                                                       at ************ApiLogin.loadInBackground(ApiLogin.java:90)
````

I am running this on a Nexus 5 with Android 6.0.1 on an Mac with OSX 10.11.3 and Android Studio 2.0.0.-Preview9

**Comment by cmelchior** [comment] 2016-02-03 15:43
@degill Are you using Instant Run? Other people have been reporting problems with preview9 as well. A clean build should solve it in that case.

**Comment by degill** [comment] 2016-02-03 15:47
Yes I am using Instant Run and yes, a clean build solves the problem *termporarily*.

I am using Instant Run for just a couple of days and I think (but don’t remember exactly) that it also happened before I was using it. I will turn off Instant Run now and see if the error persists.

**Comment by marklochrie50265** [comment] 2016-02-03 15:56
I also realised that by turning off the whole instant run featured worked for me

**Comment by mmeister1203** [comment] 2016-02-05 18:02
I'm experiencing this issue as well.It occurs sometimes when I try to read a property from a realm object. Attached is a gist. https://gist.github.com/mmeister1203/2b0c6d459443bd1e575f

**Comment by kneth** [comment] 2016-02-08 10:45
@mmeister1203: Did you try to turn off instant run? Or is your issue different?

**Comment by mmeister1203** [comment] 2016-02-08 15:21
@kneth I have tried turning off instant run and still get this error.

**Comment by skhaz** [comment] 2016-02-08 17:59
I have the same issue.

**Comment by cmelchior** [comment] 2016-02-09 10:20
@mmeister1203 @skhaz You might have to uninstall the app on the device after disabling Instant Run in order to clear the bytecode changes make by Instant Run.

**Comment by meierjan** [comment] 2016-02-09 13:32
```                                      Caused by: java.lang.IllegalAccessError: Method 'io.realm.RealmObject io.realm.Realm.createObject(java.lang.Class, java.lang.Object)' is inaccessible to class 'io.realm.MarkersEntityRealmProxy' (declaration of 'io.realm.MarkersEntityRealmProxy' appears in /data/data/XXX/files/studio-fd/dex/slice-slice_2_95fcf4c09d7463390b898208001821a8686b9ee6-classes.dex)
```

Same for me. Disabling solves it

**Comment by DenisLaboureyras** [comment] 2016-02-09 13:51
Same here.
I'm far from an expert in Android Developments (just a few weeks of development), but maybe adding a proguard rule can help to fix this issue...

**Comment by mmeister1203** [comment] 2016-02-09 15:40
@cmelchior Thanks Christian, uninstalling the app on the device worked, although this seems like a temporary fix. Are you guys working on something more permanent? I think if I had to choose between having instant run and using realm, long-term I would get rid of realm and go with instant run and simply use some other orm. Please let me know what you guys are thinking on this issue.

**Comment by cmelchior** [comment] 2016-02-09 16:24
Instant Run is still very much a preview feature (it just left alpha a few days ago). From what we know Instant Run doesn't put any restrictions on what you can do in libraries which means that all these errors are really bugs in Instant Run and not something we can do much about from the Realm side.

We are of course keeping close track of it, but ideally anything you find currently should really be reported to the Android Tools team.

**Comment by mmeister1203** [comment] 2016-02-09 16:39
@cmelchior Sounds good, I've created an issue on the Android site, please add any comments you think may help. https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=200635

**Comment by skhaz** [comment] 2016-02-09 17:32
@cmelchior thank you!

**Comment by cmelchior** [comment] 2016-02-11 08:55
@mmeister1203 Discussion seems to happening in the Google Issue tracker, so hopefully this will be solved soon.

I'm closing this issue as it is outside our control, but I'll keep taps on it as well.

**Closed by cmelchior** 2016-02-11 08:55 UTC
Labels: Reproduction Required, S:Waiting For User, T:Bug

**Comment by cmelchior** [comment] 2016-02-24 09:15
Just a note here. It seems a fix for this will be released in 2.0.0-beta6.

**Comment by wjboogerd** [comment] 2016-03-08 19:25
Not fixed in release 2.0.0-beta6 :(

**Comment by douglasjunior** [comment] 2016-06-22 13:04
*Only reporting.* 

I'm having problem with instant run in `Android Studio 2.2 Preview` and `com.android.tools.build:gradle:2.2.0-alpha3`.

When I have Realm plugin configured in my Gradle, instant run not work. The build happens in slow mode.

I'm using `Realm 1.0.1`.

**Comment by douglasjunior** [comment] 2016-06-28 12:26
Working fine with Android Studio 2.2 Preview 4 and `com.android.tools.build:gradle:2.2.0-alpha4`.

I'm using `Realm 1.0.1`.

**Comment by kneth** [comment] 2016-06-28 14:40
@douglasjunior Thanks for reporting!
