### ISSUE TITLE
Handle adding search index twice properly

### ISSUE THREAD

**Issue by yakivmospan** [realm/realm-java#1385] opened 2015-08-13 04:46 UTC
Guys please take a look on this one, we got it for some users on `2.3.3`

```
java.lang.RuntimeException: Unable to create application.android.YaloApp: java.lang.ArrayIndexOutOfBoundsException: columnIndex is less than 0.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3279)
       at android.app.ActivityThread.access$2200(ActivityThread.java:117)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3687)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.ArrayIndexOutOfBoundsException: columnIndex is less than 0.
       at io.realm.internal.Table.nativeAddSearchIndex(Table.java)
       at io.realm.internal.Table.addSearchIndex(Table.java:1156)
       at .android.model.Migration.execute(Migration.java:69)
       at io.realm.Realm.migrateRealm(Realm.java:1636)
       at io.realm.Realm.create(Realm.java:569)
       at io.realm.Realm.getDefaultInstance(Realm.java:521)
       at .model.RealmManager.getInstance(RealmManager.java:42)
       at .model.CountryDao.init(CountryDao.java:19)
       at .model.CountryDao.init(CountryDao.java:15)
       at .android.YaloApp.onCreate(YaloApp.java:66)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3276)
       at android.app.ActivityThread.access$2200(ActivityThread.java:117)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3687)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

It crashes on `userTable.addSearchIndex(userTable.getColumnIndex("appId"));`

```
public class Migration implements RealmMigration {
    @Override
    public long execute(Realm realm, long version) {
        .....

        // in 0.82 version @PrimaryKey fields become indexed. Older schemas require a migration.
        if (version == 6) {
            userTable.addSearchIndex(userTable.getColumnIndex("appId"));
            version++;
        }

        return version;
    }
```

Thanks,
Yakiv

**Comment by cmelchior** [comment] 2015-08-13 04:49
That error message indicate that the field "appId" doesn't exist on the `userTable`. Could that be the case? I.e. is `appId` added by another migration step? 

If it has been present all along, can you post the your `User` model class?

**Comment by yakivmospan** [comment] 2015-08-13 04:52
I don't think so as it does crash only few times on `2.3.3` and I do have`aapId` param as well. Here is `User.class`

```
public class User extends RealmObject {
    @PrimaryKey
    private String appId;

    private String region;
    private int countryCode;
    private String phoneNumber;
    private String e164Number;
    private String accessToken;
    private String email;
    private String name;
    private String password;
    private String gcmRegistrationId;
    private int currentAppVersionCode;
    private String gcmSenderIds;
    private String intercomHash;
    private boolean isEmailValidated;
    private String roles;
    private int registrationState;
    private long createdAt;
    private String campaign;
    private boolean isAdmin;

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String mRegion) {
        this.region = mRegion;
    }

    public int getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(int mCountryCode) {
        this.countryCode = mCountryCode;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String mPhoneNumber) {
        this.phoneNumber = mPhoneNumber;
    }

    public String getE164Number() {
        return e164Number;
    }

    public void setE164Number(String e164Number) {
        this.e164Number = e164Number;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String mAccessToken) {
        this.accessToken = mAccessToken;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String mEmail) {
        this.email = mEmail;
    }

    public String getName() {
        return name;
    }

    public void setName(String mName) {
        this.name = mName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String mPassword) {
        this.password = mPassword;
    }

    public String getGcmRegistrationId() {
        return gcmRegistrationId;
    }

    public void setGcmRegistrationId(String mGcmRegistrationId) {
        this.gcmRegistrationId = mGcmRegistrationId;
    }

    public int getCurrentAppVersionCode() {
        return currentAppVersionCode;
    }

    public void setCurrentAppVersionCode(int mCurrentAppVersionCode) {
        this.currentAppVersionCode = mCurrentAppVersionCode;
    }

    public String getGcmSenderIds() {
        return gcmSenderIds;
    }

    public void setGcmSenderIds(String mGcmSenderIds) {
        this.gcmSenderIds = mGcmSenderIds;
    }

    public String getIntercomHash() {
        return intercomHash;
    }

    public void setIntercomHash(String mIntercomHash) {
        this.intercomHash = mIntercomHash;
    }

    public boolean isEmailValidated() {
        return isEmailValidated;
    }

    public void setEmailValidated(boolean isEmailValidated) {
        this.isEmailValidated = isEmailValidated;
    }

    public String getRoles() {
        return roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }

    public int getRegistrationState() {
        return registrationState;
    }

    public void setRegistrationState(int registrationState) {
        this.registrationState = registrationState;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(long createdAt) {
        this.createdAt = createdAt;
    }

    public String getCampaign() {
        return campaign;
    }

    public void setCampaign(String campaign) {
        this.campaign = campaign;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
}
```

Thanks,
Yakiv

**Comment by beeender** [comment] 2015-08-13 04:56
Your `appId` is `String`, if it is `@PrimaryKey` before, it was indexed already. In the new version, you only need to add index if the primary key field is int/long.

Has the type of `appId` changed in the new version?

**Comment by yakivmospan** [comment] 2015-08-13 05:06
Oh, I've missed that, thanks! 

But anyway should it crash with `columnIndex is less than 0.`? Maybe you can throw some sort of `UnsupportedOperationException("Index already added")` ?

Thanks,
Yakiv

**Comment by cmelchior** [comment] 2015-08-13 05:07
Yes, that we definitely need to check up on. The error message seems very out of place.

**Comment by yakivmospan** [comment] 2015-08-13 05:18
Thanks guys!

**Comment by bmunkholm** [comment] 2015-08-26 07:42
@cmelchior : Will you update the title to describe what should be done?

**Comment by kneth** [comment] 2015-08-26 07:52
Please notice that `addSearchIndex()` is idempotent.

**Comment by cmelchior** [comment] 2015-08-31 10:03
Hi @yakivmospan 
I tried to reproduce the error you got and cannot seem to do that. My was was this:

```
      Realm.migrateRealm(config, new RealmMigration() {
            @Override
            public long execute(Realm realm, long version) {
                Table table = realm.getTable(PrimaryKeyAsString.class);
                table.addSearchIndex(table.getColumnIndex("name"));
                return 1;
            }
        });
```

Which seemed to mirror the structure in your code. So it still looks like the field ```appId``` isn't in your table for some reason. Can you provide a minimal case project that reproduces this?

**Comment by cmelchior** [comment] 2015-10-01 12:06
Hi @yakivmospan Have you been able to reproduce this?

**Comment by kneth** [comment] 2015-10-07 13:47
I have added a test to reproduce the issue. As it is not possible to reproduce, I close this issue. @yakivmospan if the issue still persist, please open a new issue.

**Closed by kneth** 2015-10-07 13:47 UTC
Labels: bug, P1
