### ISSUE TITLE
Realm cannot be configured when all test classes are run in an Android project

### ISSUE THREAD

**Issue by Villason** [realm/realm-java#4757] opened 2017-06-05 13:47 UTC
#### Goal

> Run all tests in an Android project.

#### Expected Results

> All tests run and pass.

#### Actual Results

>  When the tests in a class are run independently, they pass. When the full suite is launched, Realm cannot be configured. The exception:

```
06-05 13:38:20.764 21665-21692/com.example.sampleapp I/TestRunner: io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/com.example.sampleapp/files/7db689c6-b5e7-4f59-a5f0-33a2701b4120.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.
                                                                     at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                     at io.realm.internal.SharedRealm.<init>(SharedRealm.java:190)
                                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:237)
                                                                     at io.realm.BaseRealm.<init>(BaseRealm.java:80)
                                                                     at io.realm.Realm.<init>(Realm.java:141)
                                                                     at io.realm.Realm.createAndValidate(Realm.java:342)
                                                                     at io.realm.Realm.createInstance(Realm.java:321)
                                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:145)
                                                                     at io.realm.Realm.getInstance(Realm.java:284)
                                                                     at com.example.sampleapp.port.adapter.query.model.realm.RealmPassQueryRepositoryTest.setUp(RealmPassQueryRepositoryTest.java:41)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                                                                     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                                                                     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
                                                                     at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
                                                                     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                                                                     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                                                                     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                                                                     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                     at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                     at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                     at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                     at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                                     at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                                                                     at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                                                                     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
```

#### Steps & Code to Reproduce

> Run all tests in project: failure. Run test in a class: pass.

#### Code Sample

```
    @Before
    public void setUp()  {
        Context context = InstrumentationRegistry.getTargetContext();
        Realm.init(context);
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                .name(UUID.randomUUID().toString() + ".realm")
                .inMemory()
                .deleteRealmIfMigrationNeeded()
                .build();
        realm = Realm.getInstance(realmConfiguration);
        repository = new RealmPassQueryRepository(realm);
        realm.beginTransaction();
    }

    @After
    public synchronized void tearDown() {
        realm.commitTransaction();
        realm.close();
    }
```
(I create a random realm in order to avoid further problems during testing)

#### Version of Realm and tooling
Realm version(s): 3.1.4

Realm sync feature enabled: yes/no. No idea. All defaults.

Android Studio version: 2.3.2

Which Android version and device: Emulator. Pixel with Nougat 7.1.

**Comment by Zhuinden** [comment] 2017-06-05 14:17
Do you close the Realm as tear down (or even maybe delete them)?

**Comment by Villason** [comment] 2017-06-05 14:24
Yes, @Zhuinden. I updated the code sample.

**Comment by nhachicha** [comment] 2017-06-05 14:41
@Villason 
1- Why using `deleteRealmIfMigrationNeeded` since you generate a unique Realm for each test using `UUID` 
2- I would avoid opening a transaction in the `setup` it's part of each test logic. 
3- Using `inMemory` will delete (on disk) the Realm file if  you close all instances of the Realm

Having said that, there's nothing funny with the configuration you build on the `setup`. we need to see the full test suite (ex: what's happening inside `RealmPassQueryRepository`)

You can share your code (privately if you want) at help@realm.io

**Comment by Villason** [comment] 2017-06-05 15:12
@nhachicha 

1- Desperation. If I remove that statement it fails as well.
2- I just moved the transaction statements to the test methods. Same result.
3- I removed the inMemory statement and it fails as well.

The repository class is just a wrap for realm queries and a couple of realm.createObject calls. There is no configuration inside.

May the problem be related with multithreading testing in Android Studio? I don't understand why it works if I test each class independently but it fails if I run the full suite.

**Comment by nhachicha** [comment] 2017-06-06 00:18
I don't think it's related to Android Studio, since AS uses Gradle to run the tests.

You could try it yourself;
## Run one Test 
```shell 
adb shell am instrument -w -r   -e debug false -e class com.example.sampleapp.RealmPassQueryRepositoryTest#test1 com.example.sampleapp.test/android.support.test.runner.AndroidJUnitRunner
```

## Run all the tests
```shell
adb shell am instrument -w -r   -e debug false com.example.sampleapp.test/android.support.test.runner.AndroidJUnitRunner

```

Your use case might be an indication of a side effect from another test (not cleaning the state correctly between tests for example).

It could be helpful to send both the APK & test APK, or the complete code to try to reproduce.

Another alternative is to replace the `UUID` and use the `JUnit4` [TemporaryFolder](http://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html) rule to create a temporary directory then remove it for each test. We do use this rule internally for our unit tests, here is an [example](https://github.com/realm/realm-java/blob/d25e6da5ace009129f1888d7a14508a7f64312aa/realm/realm-library/src/androidTest/java/io/realm/rule/TestRealmConfigurationFactory.java) if you want to use it

**Comment by beeender** [comment] 2017-06-19 03:00
@Villason Is the issue solved? I am just closing this issue. Please let us know if we need to reopen this.

**Comment by Villason** [comment] 2017-06-19 05:05
No, it is not solved. I will try the TemporaryFolder method and report back.

**Comment by Villason** [comment] 2017-06-19 16:24
Hello again,

I don't know how to use the TemporaryFolder rule. It is more complicated to use than the normal @Before annotation.

I tried this and still fails:

>         Realm.init(context);
>         RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
>                 .directory(new File(context.getCacheDir() + "/" + UUID.randomUUID().toString()))
>                 .build();

The exception is:

> io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/com.example.sampleapp/cache/66f1c447-f879-4c68-9187-002f8d2c5ae9/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.

It works when I run the test class alone and not within all the project tests. The problem must be some threading madness behind the scenes.

**Comment by Villason** [comment] 2017-06-19 16:32
Another question. If I use the inMemory option why Realm raises file-related exceptions? The exceptions raised make no sense.

**Comment by Zhuinden** [comment] 2017-06-19 16:37
`inMemory` Realms still have management files or something like that

**Comment by beeender** [comment] 2017-06-20 01:54
@Villason this dir doesn't exist.
Try:
```java
Realm.init(context);
File dir = new File(context.getCacheDir(), UUID.randomUUID().toString());
dir.mkdir();
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
        .directory(dir)
        .build()
```

**Comment by Villason** [comment] 2017-06-20 15:22
@beeender it fails too:

```
io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/com.example.sampleapp/cache/4a887b9f-3a03-45ed-a4b0-b2f332ac69ca/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.
at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.SharedRealm.<init>(SharedRealm.java:190)
at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:237)
at io.realm.BaseRealm.<init>(BaseRealm.java:80)
at io.realm.Realm.<init>(Realm.java:141)
at io.realm.Realm.createAndValidate(Realm.java:342)
at io.realm.Realm.createInstance(Realm.java:321)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:145)
at io.realm.Realm.getInstance(Realm.java:284)
```
Passes when I run the test class only, fails when I run all the tests in the project.

**Comment by beeender** [comment] 2017-06-21 02:15
Can you set a breakpoint at `Realm.getInstance()` and check why the directory (`/data/data/com.example.sampleapp/cache/4a887b9f-3a03-45ed-a4b0-b2f332ac69ca/`) was not created by `dir.mkdir()`?

**Comment by Villason** [comment] 2017-06-21 14:47
@beeender 

The directory exists. It crashes here:

```
06-21 14:44:30.595 4822-4885/com.pepeware.wallet I/TestRunner: io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/com.example.sampleapp/cache/8aff9131-1f58-4e2d-9f7f-507ed05c55ba/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.
                                                                   at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                   at io.realm.internal.SharedRealm.<init>(SharedRealm.java:190)
                                                                   at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:237)
                                                                   at io.realm.BaseRealm.<init>(BaseRealm.java:80)
                                                                   at io.realm.Realm.<init>(Realm.java:141)
                                                                   at io.realm.Realm.createAndValidate(Realm.java:342)
                                                                   at io.realm.Realm.createInstance(Realm.java:321)
                                                                   at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:145)
                                                                   at io.realm.Realm.getInstance(Realm.java:284)
                                                                   at com.pepeware.wallet.application.pass.PassDetailAssemblerTest.setUp(PassDetailAssemblerTest.java:83)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                                                                   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                                                                   at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
                                                                   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
                                                                   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                                                                   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                                                                   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                                                                   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                   at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                   at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
```

**Comment by Zhuinden** [comment] 2017-06-21 17:35
@Villason you might want to set `RealmLog.setLevel(TRACE)` or something similar to get more info

**Comment by beeender** [comment] 2017-06-22 02:22
@Villason can you share your project with us and let us know how to reproduce it? you can send it to help@realm.io if you can share it privately.

**Comment by Villason** [comment] 2017-06-22 03:21
@beeender I cannot as I am not the owner of the project.

**Comment by Villason** [comment] 2017-06-22 03:23
@Zhuinden 

```

06-22 03:18:19.689 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCreateConfig
06-22 03:18:19.690 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm -1561241664
06-22 03:18:19.692 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeSetAutoRefresh -1561190136
06-22 03:18:19.692 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCloseConfig -1561241664
06-22 03:18:19.692 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeHasTable -1561190136
06-22 03:18:19.692 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCloseSharedRealm -1561190136
06-22 03:18:19.693 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCreateConfig
06-22 03:18:19.693 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm -1561241664
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190168
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190152
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190144
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190176
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190184
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190072
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190192
06-22 03:18:19.693 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561189992
06-22 03:18:19.694 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190008
06-22 03:18:19.694 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190016
06-22 03:18:19.694 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190024
06-22 03:18:19.694 4954-4972/? V/REALM_JNI:  --> finalize_shared_realm -1561190032
06-22 03:18:19.695 4954-4969/? V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCloseConfig -1561241664
06-22 03:18:19.695 4954-4969/? I/TestRunner: failed: test_handles_coupon_created(com.sampleapp.application.RedactedTest)
06-22 03:18:19.695 4954-4969/? I/TestRunner: ----- begin exception -----
06-22 03:18:19.695 4954-4969/? I/TestRunner: io.realm.exceptions.RealmFileException: No such file or directory () (/data/data/com.sampleapp/cache/40edd7f4-0945-432b-8764-e790bade2201/default.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.
                                                 at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                 at io.realm.internal.SharedRealm.<init>(SharedRealm.java:190)
                                                 at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:237)
                                                 at io.realm.BaseRealm.<init>(BaseRealm.java:80)
                                                 at io.realm.Realm.<init>(Realm.java:141)
                                                 at io.realm.Realm.createAndValidate(Realm.java:342)
                                                 at io.realm.Realm.createInstance(Realm.java:321)
                                                 at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:145)
                                                 at io.realm.Realm.getInstance(Realm.java:284)


```

**Comment by beeender** [comment] 2017-06-22 03:58
@Villason It feels you tried to get the Realm instance again after temp dir `40edd7f4-0945-432b-8764-e790bade2201` is deleted. Maybe something not right in your `tearDown()` method?

can you reproduce it with a sample project so we can take a look? it is hard to tell what is wrong with current information.

**Comment by Villason** [comment] 2017-06-22 18:22
@beeender I just do a realm.close(). I am creating a new project but I cannot reproduce the problem. I am trying to add complexity (dagger, repositories encapsulating the realm, etc).

**Comment by Villason** [comment] 2017-06-23 14:46
Well the problem was one of the tests resets the app and deletes all the files in the tearDown method. Are the test classes run in parallel? If not I still don't understand why it crashes.

I think you can close the issue.

**Comment by beeender** [comment] 2017-06-26 02:18
No, tests should be run sequentially **by default**. A `ParallelRunner` was introduced recently but i guess you are not using it.

From our experience, that normally happened when you start some thread and didn't wait for termination before teardown called.

Anyway, good to know the issue has been solved!

**Closed by beeender** 2017-06-26 02:18 UTC
Labels: T:Help
