### ISSUE TITLE
Realm query on array size

### ISSUE THREAD

**Issue by mgohin** [realm/realm-java#5989] opened 2018-06-05 15:31 UTC
Hi,

I'm not quite sure you are still monitoring Stackoverflow Realm tags, so I'll link it to you here : https://stackoverflow.com/questions/50524201/realm-query-on-array-size

I can remove the Stackoverflow question if you want and continue the discussion here.

Thanks ;)

**Comment by Zhuinden** [comment] 2018-06-05 15:41
Duplicate of https://github.com/realm/realm-java/issues/1598#issue-111482267 and it'd be nice if it were supported

**Comment by mgohin** [comment] 2018-06-05 15:47
Thanks, I see that's a request for almost 3 years :/

**Comment by Zhuinden** [comment] 2018-06-05 15:49
What's lame is that the Realm Core supports it, it's just that the Realm-Java query api doesn't :p

**Comment by mgohin** [comment] 2018-06-05 15:50
What ??? WE NEED IT !!!!! :)

**Comment by Zhuinden** [comment] 2018-06-06 07:56
yeah, but no one could figure out what it should look like so it was never added

**Comment by cmelchior** [comment] 2018-06-06 09:39
Hi @mgohin 
It is something we want to add as well but we haven't been able to nail the exact API yet, so I don't have any timeline to share, unfortunately.

But if you can provide your use case in #1598 that would help a lot. Also any input you have on the exact API you like would help guide the process. 

I'm folding this into #1598

**Closed by cmelchior** 2018-06-06 09:39 UTC
Labels: O:User, T:Duplicate

**Comment by mgohin** [comment] 2018-06-06 09:42
My use case is the same as you describe in #1598 in your first message ;)
