### ISSUE TITLE
SIGSEGV signal 11

### ISSUE THREAD

**Issue by BWMuller** [realm/realm-java#3431] opened 2016-09-13 11:41 UTC
Getting a sigsegv signal 11 when attempting to open the app on a Xiaomi Redmi Note 2

#### Goal

> Use the library

#### Expected Results

> No sigsegv

#### Actual Results

>  09-13 13:30:34.252 12167-12167/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-13 13:30:34.252 12167-12167/? I/DEBUG: Build fingerprint: 'Xiaomi/hermes/hermes:5.0.2/LRX22G/V8.0.1.0.LHMMIDG:user/release-keys'
09-13 13:30:34.252 12167-12167/? I/DEBUG: Revision: '0'
09-13 13:30:34.252 12167-12167/? I/DEBUG: ABI: 'arm64'
09-13 13:30:34.252 12167-12167/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x0   0000000000000000  x1   00000000186a3793  x2   00000055797cc018  x3   00000055797cc0e8
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x4   0000000000000000  x5   00000000000010f0  x6   0000000000000006  x7   0000007f7d712000
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x8   00000000000010f0  x9   0000000000000090  x10  0000007f7d712e18  x11  0000000000000001
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x12  0000000000000001  x13  0000000000000000  x14  0000000000000000  x15  0000007f7d712e18
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x16  0000007f7d70bb08  x17  0000007f7d68cee0  x18  0000000000000000  x19  0000000000070000
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x20  00000055797cac08  x21  00000000186a3793  x22  00000000000000d6  x23  00000055797cac08
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x24  0000000000000000  x25  0000000000000000  x26  0000000000000000  x27  0000000000000002
09-13 13:30:34.270 12167-12167/? I/DEBUG:     x28  0000000000000001  x29  0000007ff6088e90  x30  0000007f62f6b3a4
09-13 13:30:34.270 12167-12167/? I/DEBUG:     sp   0000007ff6088e90  pc   0000007f62f9066c  pstate 0000000060000000
09-13 13:30:34.271 12167-12167/? I/DEBUG: backtrace:
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #00 pc 000000000006866c  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #01 pc 00000000000433a0  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #02 pc 0000000000071ac0  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #03 pc 00000000000ba1b4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #04 pc 0000000000121cd4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #05 pc 00000000000ba7a4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #06 pc 0000000000121cd4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #07 pc 00000000000ba7ec  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #08 pc 0000000000121cd4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #09 pc 00000000000ba7ec  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #10 pc 0000000000121cd4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #11 pc 00000000000ba7a4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #12 pc 0000000000121cd4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #13 pc 00000000000ba7a4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #14 pc 0000000000121cd4  /data/app/.../lib/arm64/librealm-jni.so
09-13 13:30:34.271 12167-12167/? I/DEBUG:     #15 pc 000000000003ee00  /data/app/.../lib/arm64/librealm-jni.so (Java_io_realm_internal_Group_nativeGetTableNativePtr+420)

#### Steps & Code to Reproduce

> Open the app

#### Version of Realm and tooling
Realm version(s): 1.2.0

Android Studio version: 2.1.3

Which Android version and device: Xiaomi Redmi Note 2, Android 5.0.2, Api 21

**Comment by Zhuinden** [comment] 2016-09-13 12:38
Did this happen on first install? If not, it might be corruption, in which case it'd be nice to have the Realm file

**Comment by BWMuller** [comment] 2016-09-13 12:55
This happens on first install as well as later on. Our realm file is encrypted

**Comment by kneth** [comment] 2016-09-15 10:42
Does it work if you disable encryption?

**Comment by denis-stepushchik** [comment] 2016-09-19 14:15
Hi. I have the same issue.

**Comment by Zhuinden** [comment] 2016-09-19 14:16
@denis-stepushchik this looks like a crash related to audio recording, and not Realm

**Comment by denis-stepushchik** [comment] 2016-09-19 14:19
@Zhuinden but I don't use audio recording anywhere in the app. 
BTW on android 4.2, 4.4, 6.0.1 my app work well

**Comment by denis-stepushchik** [comment] 2016-09-19 14:24
@Zhuinden Is it possible that this issue is related with the Android 7.0?

**Comment by Zhuinden** [comment] 2016-09-19 15:08
@denis-stepushchik well I'm pretty sure Realm doesn't record audio :smile: 

```
09-19 09:25:36.101 26300-26300/? A/DEBUG: #16 pc 000000000001d9fc /system/lib64/libc.so (__start_thread+16)
09-19 09:25:36.150 517-26306/? E/audio_route: unable to find path 'set-capture-format-default'
09-19 09:25:36.845 21801-24945/? E/AudioRecord-JNI: Error -4 during AudioRecord native read
```

And this is quite specifically "AudioRecord-JNI".

**Comment by denis-stepushchik** [comment] 2016-09-20 07:07
@Zhuinden sorry fir this

**Comment by Zhuinden** [comment] 2016-09-20 07:09
That's okay

**Comment by beeender** [comment] 2016-09-21 04:36
@denis-stepushchik It seems the problem is not related with Realm. I am closing this issue now. Feel free to reopen it if needed.

**Comment by Zhuinden** [comment] 2016-09-21 05:32
@beeender technically we were waiting for the original poster to answer if it works without encryption, but that never happened

**Comment by beeender** [comment] 2016-09-21 05:38
HA, OK. Then i will just reopen this and continue waiting.

**Comment by BWMuller** [comment] 2016-09-21 06:13
Currently waiting to get the device again on which it happened to test a unencrypted version. Should be at last on Tuesday.

**Comment by phearme** [comment] 2016-09-27 08:12
+1

crash:
SIGSEGV SEGV_MAPERR 0x0000000000000008
	librealm-jni.so	
Java_io_realm_internal_Group_nativeGetTableNativePtr

We do use encryption, and don't want to disable it for obvious reasons.

**Comment by BWMuller** [comment] 2016-09-27 12:34
Retested. Even when running the app without encryption enabled it still crashes.

**Comment by kneth** [comment] 2016-09-28 09:56
Do you only see the crash on Xiaomi Redmi Note 2? It is possible to share your code or apk with? You can do it privately by sending an email to help@realm.io.

**Comment by phearme** [comment] 2016-09-28 10:07
I noticed this crash on other devices (SM-G920V). I cannot share my code/apk unfortunatly.

**Comment by kneth** [comment] 2016-09-29 08:39
Is it possible for you to upgrade to version 2.0.0 and report back. Many of the native calls have been changed, and we would like to know if the changes are for the better.

**Comment by phearme** [comment] 2016-09-29 08:43
We upgraded to 2.0.0 and reverted back to 1.2.0 because there is a crash on connectivity change. Will wait for it to be fixed before upgrading, and then let you know.

**Comment by BWMuller** [comment] 2016-09-29 08:45
Upgraded to 2..0.0, not getting the connectivity crash myself. Will do another test once I have the crashing device again

**Comment by cmelchior** [comment] 2016-09-29 08:49
@BWMuller We haven't released the fix for the connectivity crash yet. So it it still there

**Comment by BWMuller** [comment] 2016-09-29 08:53
@cmelchior I am aware of this, all I get in reference to the network state receiver not being there is the added error, but it hasn't caused a crash for me


UALib: ManifestUtils - Unable to find class: io.realm.internal.network.NetworkStateReceiver
                                                                           java.lang.ClassNotFoundException: io.realm.internal.network.NetworkStateReceiver
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.Class.forName(Class.java:308)
                                                                               at java.lang.Class.forName(Class.java:272)
                                                                               at com.urbanairship.util.ManifestUtils.validateManifest(ManifestUtils.java:81)
                                                                               at com.urbanairship.UAirship.executeTakeOff(UAirship.java:348)
                                                                               at com.urbanairship.UAirship.access$000(UAirship.java:42)
                                                                               at com.urbanairship.UAirship$2.run(UAirship.java:304)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver" on path: DexPathList[[zip file "/data/app/me.kalido.android.staging-1/base.apk"],nativeLibraryDirectories=[/data/app/me.kalido.android.staging-1/lib/arm, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at java.lang.Class.classForName(Native Method) 
                                                                               at java.lang.Class.forName(Class.java:308) 
                                                                               at java.lang.Class.forName(Class.java:272) 
                                                                               at com.urbanairship.util.ManifestUtils.validateManifest(ManifestUtils.java:81) 
                                                                               at com.urbanairship.UAirship.executeTakeOff(UAirship.java:348) 
                                                                               at com.urbanairship.UAirship.access$000(UAirship.java:42) 
                                                                               at com.urbanairship.UAirship$2.run(UAirship.java:304) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
                                                                           	Suppressed: java.lang.ClassNotFoundException: io.realm.internal.network.NetworkStateReceiver
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                               		... 9 more
                                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by kneth** [comment] 2016-10-07 08:20
@BWMuller Please try to upgrade to 2.0.1 and see if your issue is solved.

**Comment by kneth** [comment] 2016-10-24 12:28
If upgrading to latest version didn't help you, please reopen the issue.

**Closed by kneth** 2016-10-24 12:28 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help
