### ISSUE TITLE
insertOrUpdate(Collection) does not handle empty list properly

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3103] opened 2016-07-01 09:06 UTC
#### Goal

> What do you want to achieve?

Save empty list

#### Expected Results

Ignore it considering it's empty

#### Actual Results

     07-01 10:56:02.262 9258-9364/E/BasePersistDbTaskImpl: Error during saving [CompletedRecordsXML].
        java.util.NoSuchElementException
        at java.util.AbstractList$SimpleListIterator.next(AbstractList.java:59)
        at io.realm.internal.modules.CompositeMediator.insertOrUpdate(CompositeMediator.java:121)
        at io.realm.Realm.insertOrUpdate(Realm.java:853)

On this line

        RealmProxyMediator mediator = getMediator(Util.getOriginalModelClass(Util.getOriginalModelClass(objects.iterator().next().getClass())));

#### Steps & Code to Reproduce

Try to save an empty RealmList.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.1 but it's irrelevant

Which Android version and device: 6.0.2, Nexus 5X

**Comment by cmelchior** [comment] 2016-07-01 09:07
Hmm, looks like a bug to me. Your right that providing the empty list should just be a no-op.

**Comment by zaki50** [comment] 2016-07-01 11:31
This issue can be reproduced when `CompositeMediator` or `FilterableMediator` is used in the `RealmConfiguration`.

**Comment by zaki50** [comment] 2016-07-05 12:42
fixed in releases `branch`

**Comment by zaki50** [comment] 2016-07-05 12:43
I'll close this issue.
If you find some problems in next release, feel free to reopen this.

**Closed by zaki50** 2016-07-05 12:43 UTC
Labels: T:Bug-Crash
