### ISSUE TITLE
Notifications for a specific model

### ISSUE THREAD

**Issue by lucamtudor** [realm/realm-java#523] opened 2014-11-02 10:14 UTC
The notifications API is a great idea, thanks for that!
But I would like to filter notifications for a specific model. Let's say my realm has Users and Emails. I want to be able to listen for email changes only, not to be notified by user changes.

**Comment by cmelchior** [comment] 2015-04-15 16:37
This is a duplicate of #989, so closing this one.

**Closed by cmelchior** 2015-04-15 16:37 UTC
Labels: enhancement
