### ISSUE TITLE
Is there any plans for querying exact amount of objects ? 

### ISSUE THREAD

**Issue by XDXO** [realm/realm-java#3649] opened 2016-10-18 06:35 UTC
#### Goal

> As far as I know, Realm lacks of an option for limit / paging.
> Most ORMs as well as various databases support the option.
> This feature will be needed in case that I want to get only 5 newest feeds.
> realm.between(String fieldName, ..., ... ) does not guarantee querying exact amount of objects.
> Although Realm uses lazy loading, I think this feature enhances readability and productivity for programming.

#### Expected Results

```java

> // TODO : Get only 10 event objects.
> Realm realm = Realm.getDefaultInstance();
> List<Event> query = realm.where(Event.class).greaterThan(Event.FIELD_CREATED_AT, oldest).limit(10);

```

**Comment by Zhuinden** [comment] 2016-10-18 06:39
Duplicate of https://github.com/realm/realm-java/issues/544

**Comment by cmelchior** [comment] 2016-10-18 06:40
Hi @XDXO 
This is already being tracked here #544. Note that since Realm lazy load all data you don't have the same memory concerns as seen in normal ORM's.

I'll close this as an duplicate and let discussion continue in #544

**Closed by cmelchior** 2016-10-18 06:40 UTC

**Comment by Zhuinden** [comment] 2016-10-18 06:50
Really though, this is easily solved by returning a maximum of `Math.min(5, results.size())` in your RecyclerView's Adapter
