### ISSUE TITLE
realm.commitTransation takes extremely long up to ANR after migrating from 3.0.0

### ISSUE THREAD

**Issue by ursusursus** [realm/realm-java#4802] opened 2017-06-17 23:07 UTC
With updating realm plugin from 3.0.0 to current my writing to database performance degrades very badly from couple of seconds with hundreds of items to ANRs when given table has 4000 rows.

From my examining I found that any subsequent commiting a editing transation to realm hangs up, but queries are fine, also inserts are fine. Also, if I insert to different table, it works, so only that one with larger amount of data has this problem.
However it doesnt seem to be a deadlocking type of situation, as where I wait for a minute and dont close the app on anr dialog, the operation actually completes eventually.

Use case of my app is that upon pull to refresh it add new rows to given Ads table. I am adding them via 1 transation, so this hopefully is not the issue
```
public ArrayList<Long> addAdsToFilter(Filter filter, LinkedHashMap<String, Ad> remoteAds) {
        ArrayList<Long> newAdIds = new ArrayList<>();
        mRealm.executeTransaction(realm -> {
            AtomicLong idCounter = RealmUtils.getIdCounter(realm, Ad.class);
            for (String key : remoteAds.keySet()) {
                Ad ad = remoteAds.get(key);
                long id = idCounter.incrementAndGet();
                ad.setId(id);
                ad.setFilter(filter);
                filter.addAd(ad);
                newAdIds.add(id);
            }
        });
        return newAdIds;
    }
```

**However the weird thing about simulating this bug is that it only shows its self after 2nd pull to refresh inserts. Before that even with 4000 items transations commit fine.**

So the simulation is: 1 pull to refresh; editing any object - OK, 2. pull to refresh, now edit any object from that table and operation hangs up .
(.. however only updates seem to be problem, inserts work, so if I dont edit any object after 2nd refresh, I can insert data with 3rd refresh no problem)

Thank you for your help, let me know if you need me to provide you with more info

Realm version(s): 3.3.2
Realm sync feature enabled: no
Android Studio version: 2.3.2
Which Android version and device: any

**Comment by Zhuinden** [comment] 2017-06-18 00:20
Most likely caused by https://github.com/realm/realm-java/issues/4544#issuecomment-296967988

Solution is to update to Realm 3.4.0-SNAPSHOT and replace some of your bidirectional links with unidirectional link and an inverse `@LinkingObjects`.

**Comment by ursusursus** [comment] 2017-06-18 14:46
It helped, thanks

**Comment by ursusursus** [comment] 2017-06-18 15:25
your workaround does help in a major way, now updating (commitTransation) an object doesnt lock up the thread.

But updating is still very slow in general. When Im doing "trash" operation, which is settings isTrashed = true on a large dataset
```
public void trashAds(List<Ad> ads, boolean trashed) {
        mRealm.executeTransaction(realm -> {
            for (int i = ads.size() - 1; i >= 0; i--) {
                ads.get(i).setTrashed(trashed);
            }
        });
    }
```

each `ads.get(i).setTrashed(trashed);` takes around 150ms, which on a 2500 item dataset take 6+minutes!

**Comment by Zhuinden** [comment] 2017-06-18 21:26
That's odd, because you are running a single transaction, and that is already the right way of doing things :(

I'm not sure about the solution, is there a chance you can make a sample with similar numbers and schema?

**Comment by zaki50** [comment] 2017-06-19 01:06
What is the actual class of `ads`?

**Comment by ursusursus** [comment] 2017-06-19 01:12
`@Accessors(prefix = "m")
public class Ad extends RealmObject {

    @Getter @Setter @PrimaryKey private long mId;
    @Getter @Setter private String mTitle;
    @Getter @Setter private String mUrl;
    @Getter @Setter private String mImageUrl;
    @Getter @Setter private String mPrice;
    @Getter @Setter private String mCategory;
    @Getter @Setter private String mBodytype;
    @Getter @Setter private String mTransmission;
    @Getter @Setter private boolean mSeen;
    @Getter private boolean mWatched;
    @Getter @Index private boolean mTrashed;
    @Getter @Setter private AdDetail mAdDetail;
    @Getter @Setter private long mTimestamp;
    @Getter @Setter private long mWatchedTimestamp;
    @Getter @Setter private long mTrashedTimestamp;

    @LinkingObjects("mAds") private final RealmResults<Filter> mFilter = null;
    @Getter @Setter private RealmList<Message> mMessages;

    public boolean isExternal() {
        return getUrl() != null && getUrl().contains(".php?");
    }

    public boolean hasDetails() {
        return mAdDetail != null;
    }

    public String getFormattedTimestamp() {
        return Utils.DATE_FORMATTER_2.format(getTimestamp());
    }

    public boolean hasImage() {
        return !TextUtils.isEmpty(mImageUrl);
    }

    public void addMessage(Message m) {
        mMessages.add(m);
    }

    public Filter getFilter() {
        return mFilter != null ? mFilter.first() : null;
    }

    public void setWatched(boolean watched) {
        mWatched = watched;
        mWatchedTimestamp = watched ? System.currentTimeMillis() : 0;
    }

    public void setTrashed(boolean trashed) {
        mTrashed = trashed;
        mTrashedTimestamp = trashed ? System.currentTimeMillis() : 0;
    }

    public void cascadeDeleteFromRealm() {
        if (mAdDetail != null) mAdDetail.deleteFromRealm();
        if (mMessages != null) mMessages.deleteAllFromRealm();
        deleteFromRealm();
    }
}`

The whole class for now, I will to try to isolate in a example project later hopefully

**Comment by zaki50** [comment] 2017-06-19 01:42
Ah sorry, I mean `List<Ad> ads`.

**Comment by ursusursus** [comment] 2017-06-19 01:44
Downcasted RealmResults<Ad>

**Comment by beeender** [comment] 2017-06-19 02:43
@ursusursus 

> each ads.get(i).setTrashed(trashed); takes around 150ms, which on a 2500 item dataset takes 6+minutes! in sql this would be a single update statement taking for sure taking no more than 150ms

How did you measure this? as @Zhuinden said, if they happen in a single transaction, the setter takes 150ms is very strange.

Actually, the transaction should be fast. The thing is, the transaction will trigger all listeners on the same thread and compute the changes for fine grained notifications which will take time if you have a large set of data, and bidirectional links between them.

When this problem happens, how many listeners do you have on the same thread? Will the transaction be much faster if there is no listeners on the same thread?

A sample project will be very helpful. thanks

**Comment by beeender** [comment] 2017-06-26 02:23
@ursusursus have you solved this issue?

**Comment by ursusursus** [comment] 2017-06-26 21:14
Sorry I am currently busy, I will get back to you asap

**Comment by kneth** [comment] 2017-07-05 08:51
@ursusursus Any news to share?

**Comment by cmelchior** [comment] 2017-07-07 12:30
If you still have this issue and can reproduce in a sample project, feel free to re-open @ursusursus.

Closing for now

**Closed by cmelchior** 2017-07-07 12:30 UTC
Labels: S:Waiting For User, T:Help
