### ISSUE TITLE
Add java.time to Realm field support

### ISSUE THREAD

**Issue by b12kab** [realm/realm-java#6476] opened 2019-03-26 21:27 UTC
#### Describe your problem or use case
[Currently](https://realm.io/docs/java/latest/) only these fields are supported:
Realm supports boolean, byte, short, int, long, float, double, String, Date and byte[] field types. The integer types byte, short, int, and long are all mapped to long within Realm. In addition to those standard field types, Realm supports subclasses of RealmObject and RealmList<? extends RealmObject> to model relationships.

#### Describe the solution you'd like
java.time class support should be added, so that better date / time handling can be supported.

#### Additional context
Java 8 java.time package summary [here](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html).

**Comment by cmelchior** [comment] 2019-04-02 13:24
Yes, this is already being tracked here: https://github.com/realm/realm-java/issues/5104, so I'll close this as a duplicate.

How Realm represents time is actually identical to how `Instant` does it, but the problem is that the API's have only been added recently, which complicates the build a bit.

**Closed by cmelchior** 2019-04-02 13:24 UTC
Labels: O:User, T:Duplicate

**Comment by b12kab** [comment] 2019-04-02 22:35
@cmelchior Thanks for the follow up.

Theoretically, https://github.com/JakeWharton/ThreeTenABP could be used as an easier alternative.

**Comment by Zhuinden** [comment] 2019-04-02 23:18
Honestly, all we really need for this stuff is type adapters.
