### ISSUE TITLE
Async callbacks not invoked on android 12 emulator

### ISSUE THREAD

**Issue by hardysim** [realm/realm-java#7321] opened 2021-02-24 10:24 UTC
#### Goal
View data in the example projects (I've tested `architectureComponentsExample` and `coroutinesExample`).

#### Actual Results
On a android 12 emulator, no data is shown. It works fine on a Pixel 3 with Android 12 DP1 though. I have the same problem with my actual app but it seems like a general problem when the examples are not working either.

#### Steps & Code to Reproduce
Checkout this repo at dfbf7977981e0eee9ca501568325f7400fbbf6f4 (tag `v10.3.1`) and run the examples `architectureComponentsExample` and `coroutinesExample` on an emulator. I'm using the `Android API S x86x64 (Google Play)` (and `(Google APIs)` as well) image for the emulator (the only ones available).

When running he examples, they both show an empty content. Running on a real device shows a list with the data.

#### Version of Realm and tooling

Realm version(s): 10.3.1
Realm Sync feature enabled: No
Android Studio version: 4.2 Beta 4
Android Build Tools version: 29.0.3
Gradle version: 6.5
Which Android version and device(s): Android S DP 1

**Comment by rorbech** [comment] 2021-02-25 07:38
Thanks for the report. I managed to reproduce it locally, but will have to investigate to find a root cause.

**Comment by rorbech** [comment] 2021-02-25 12:21
Seems to be caused by the async operations not working properly. Will investigate further.

**Comment by cmelchior** [comment] 2021-03-05 12:56
I have been testing this further. @rorbech attempted to modify how we use `epoll` in #7328 which makes it behave better, but we still see sporadic failures indicating it isn't the correct fix. 

We also have tested on various versions of the emulator, the latest being `30.5.1`, so if this is a bug in the emulator, it is also present in the latest version.

**Comment by cmelchior** [comment] 2021-03-09 07:44
For reference. Android Looper uses a similar mechanism https://cs.android.com/android/platform/superproject/+/master:system/core/libutils/Looper.cpp;drc=1406207e6798252fe7e89f288c0f4d5add1dd1bd;l=239 which indicates the problem is on our end somewhere.

**Comment by cmelchior** [comment] 2021-03-09 11:43
A potential fix is under review here: https://github.com/realm/realm-core/pull/4507

**Comment by VicMikhailau** [comment] 2021-03-16 19:06
The same problem on a real project where dependency **io.realm:android-adapters:4.0.0** is used. Doesn't matter is the project targeted to android S or lower - on emulator (not checked on real devices) data in lists don't appear.

**Comment by cmelchior** [comment] 2021-03-17 08:07
Hi @VicMikhailau Thanks for the reporting. The underlying bug will affect all changelisteners including the android-adapters.

As far as we know the bug is only on the emulator which points to a problem there, but we still haven't discovered the root cause. Unfortunately, the bugfix in https://github.com/realm/realm-core/pull/4507 was discovered to also break notifications across processes, so we are investigating other solutions right now.

**Comment by cmelchior** [comment] 2021-05-04 14:11
We tracked the problem down to a change in the Linux Kernel: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6a965666b7e7475c2f8c8e724703db58b8a8a445 and are currently looking into workarounds. Unfortunately, this has a lot of implications on how our current notification system is designed.

**Comment by cmelchior** [comment] 2021-06-17 08:10
This has been fixed in 10.5.1

**Closed by cmelchior** 2021-06-17 08:10 UTC
Labels: O-Community

**Comment by mannodermaus** [comment] 2021-06-18 10:59
Can confirm that Realm access works correctly for my apps after updating beyond 10.5.1. It didn't sound like a trivial fix, so many thanks to y'all for the hard work! 🎉
