### ISSUE TITLE
realm can user annotation replace column name or table name

### ISSUE THREAD

**Issue by liyuyitong** [realm/realm-java#5278] opened 2017-09-19 03:02 UTC
realm can user annotation replace column name or table name?

**Comment by Zhuinden** [comment] 2017-09-19 07:38
The class name is used for table name, and the field name is used for column name.

**Comment by cmelchior** [comment] 2017-09-19 09:48
Yes, this is a duplicate of #2476. So lets keep the discussion there.
I actually have a prototype for this, but I need to find the time to prioritize it. You can see it here: https://github.com/realm/realm-java/pull/5280

Let me know if that doesn't support your use case.

**Closed by cmelchior** 2017-09-19 09:48 UTC
Labels: T:Duplicate
