### ISSUE TITLE
Realm crashing in Samsung Note 2 due to "Encrypted interprocess sharing" is currently unsupported

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#2762] opened 2016-05-10 06:47 UTC
```
Fatal Exception: io.realm.exceptions.RealmError
Unrecoverable error. /data/data/com.conem.app/files/file.realm: Encrypted interprocess sharing is currently unsupported in io_realm_internal_SharedGroup.cpp line 113
 Raw
io.realm.internal.SharedGroup.createNativeWithImplicitTransactions (SharedGroup.java)
io.realm.internal.SharedGroup. (SharedGroup.java)
io.realm.internal.SharedGroupManager. (SharedGroupManager.java)
io.realm.BaseRealm. (BaseRealm.java)
io.realm.Realm. (Realm.java)
io.realm.Realm.createAndValidate (Realm.java:269)
io.realm.Realm.createInstance (Realm.java:249)
io.realm.RealmCache.createRealmOrGetFromCache (RealmCache.java:118)
io.realm.Realm.getDefaultInstance (Realm.java:195)
```

#### Version of Realm and tooling
Realm version(s): 0.90.0

Android Studio version: 2.1

Which Android version and device: Samsung Note 2

Native Platform : armeabi-v7a

**Comment by beeender** [comment] 2016-05-10 06:51
@mihirjoshi21 Are you using Realm in multi processes? Multi-process is not supported yet.

**Comment by mihirjoshi21** [comment] 2016-05-10 06:54
No separate process is defined in manifest file

**Comment by mihirjoshi21** [comment] 2016-05-10 18:53
@beeender I checked this on one other Galaxy note 2 device and I guess the error is specific to it, in other devices, it is working just fine. Please tell me what I can do to resolve it before I get any more 1 star reviews :( .

**Comment by beeender** [comment] 2016-05-11 02:06
@mihirjoshi21 can you share the apk link with us?

**Comment by mihirjoshi21** [comment] 2016-05-11 03:49
Yes

**Comment by beeender** [comment] 2016-05-11 04:23
@mihirjoshi21 
> I checked this on one other Galaxy note 2 device ..

Does that mean you can reproduce it on Galaxy note 2?

**Comment by mihirjoshi21** [comment] 2016-05-11 04:26
yes. The logcat is from the same device

**Comment by beeender** [comment] 2016-05-11 04:32
@mihirjoshi21 
Can you send below information to help@realm.io

1. the apk (easier to get it from you)
2. AndroidManifest.xml (I can decompile from 1 as well)
3. Full stacktrace of crash
4. Related source code of the crash
5. Any instant message account? If you get some time right now, instant message might make things faster.

**Comment by mihirjoshi21** [comment] 2016-05-11 04:34
Please ping me on hangouts on mihir.jagger@gmail.com

**Comment by beeender** [comment] 2016-05-13 02:28
User haven't seen the crash after updating to `0.90.0`. Closing this issue for now. Feel free to reopen it if it happens again.

**Comment by beeender** [comment] 2016-05-17 13:40
User is still seeing this crash on Samsung Galaxy Tab 4 7.0 SM-T230NU  4.4.2 with `0.90.0`. Reopen this.

**Comment by AllenVork** [comment] 2016-06-27 07:08
I got the same error on different devices. I don't know how to solve it.

**Comment by cmelchior** [comment] 2016-06-27 07:10
@AllenVork Upgrading to the latest version of Realm should solve this. Our old encryption relied on Unix signals which were broken on some vendor specific versions of Android. We moved away from this in later releases.

**Comment by AllenVork** [comment] 2016-06-27 07:13
@cmelchior thx.I'll try it.

**Comment by cmelchior** [comment] 2016-06-27 07:42
@AllenVork Sorry, I was a bit hasty there. This error has nothing to do with the encryption example. It would be easier if you created a new issue with any information you have. Especially the content of your `AndroidManifest.xml`. Thanks

**Comment by cmelchior** [comment] 2016-10-27 13:06
Closing since this issue hasn't been seen after 1.0

**Closed by cmelchior** 2016-10-27 13:06 UTC
Labels: S:P1 Backlog, T:Bug-Crash

**Comment by amols-iprogrammer** [comment] 2016-11-29 09:02
I am facing same issue on Lenovo A6000

**Comment by Zhuinden** [comment] 2016-11-29 09:03
@amols-iprogrammer yes, but what Realm version?

**Comment by amols-iprogrammer** [comment] 2016-11-29 09:05
On realm 1.2.0

**Comment by adjulbic** [comment] 2017-01-25 21:32
The issue is still present in Realm 1.0.1 - but only on Samsung devices (tested so far on SM-N9005 and SM-N910C). I suppose other Samsung devices will be affected as well.

`Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. /data/data/com.xxx/files/xx.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 11838. Current pid is 19243. in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
       at io.realm.BaseRealm.<init>(BaseRealm.java:81)
       at io.realm.Realm.<init>(Realm.java:139)
       at io.realm.Realm.createAndValidate(Realm.java:250)
       at io.realm.Realm.createInstance(Realm.java:230)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
       at io.realm.Realm.getInstance(Realm.java:194)
       at com.xxx.ZApplication.xx(ZApplication.java:xx)
       at com.xxx.xxx.XApplication.onCreate(XApplication.java:xx)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5113)
       at android.app.ActivityThread.access$1600(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)`

From the log, the error happens on app startup (application onCreate method). This is first and only Realm initialisation (Realm.getInstance(configuration)) and I don't see how it is possible to be called twice (from two different processes) in any case during application startup.

But, maybe I'm overseeing something, so any sort of help/hint is more than welcomed.

**Comment by beeender** [comment] 2017-01-26 03:20
@kneth If this happens on Sumsung device a lot, maybe it has the same root cause with #3651  ?

**Comment by kneth** [comment] 2017-01-30 09:01
@beeender I doubt it but since we have a Samsung device at the office, it might be worth testing.
