### ISSUE TITLE
java.lang.NoClassDefFoundError: io.realm.RealmConfiguration$Builder after gradle plugin update

### ISSUE THREAD

**Issue by RuiMochila** [realm/realm-java#1832] opened 2015-11-25 15:31 UTC
I'm trying Android Studio 2.0 preview, the app was working great, then I wanted to try the Instant Run feature so AS asked me to update the gradle plugin and the build tools to 23.0.2, after the update I can't run the app, I'm getting a java.lang.NoClassDefFoundError: io.realm.RealmConfiguration$Builder when trying to initialise Realm.
I've tried cleaning and rebuilding the project.
I have multidex enabled, if that's relevant.

**Comment by RuiMochila** [comment] 2015-11-25 15:40
Also worth noting that going back to Android Studio 1.5, but still using buildToolsVersion '23.0.2' and  'com.android.tools.build:gradle:2.0.0-alpha1' I am able to run the app successfully.

**Comment by kneth** [comment] 2015-11-26 14:17
I finally upgraded to Android Studio 2.0 preview. I created a small app, and I can't reproduce your issue.

My `build.gradle` files are:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-alpha1'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

and 

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "net.zigzak.as20"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'io.realm:realm-android:0.85.0'
}
```

In my activity's `onCreate()` I do

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(getApplicationContext()).build();
        Realm realm = Realm.getInstance(realmConfiguration);
        realm.beginTransaction();
        Person person = realm.createObject(Person.class);
        realm.commitTransaction();

How does my app differ from yours?

**Comment by roughboy** [comment] 2015-11-26 19:23
I had similar issue - switching gradle plug-in from `classpath 'com.android.tools.build:gradle:1.5' `
to `classpath 'com.android.tools.build:gradle:2.0.0-alpha1'` helped.

**Comment by kneth** [comment] 2015-11-30 08:14
@roughboy Thanks for sharing.
@RuiMochila Is it fine to stay at 2.0.0-alpha1?

**Comment by eduardocucharro** [comment] 2015-12-23 17:24
Hi guys,  I'm still having this problem. I'm using com.android.tools.build:gradle:2.0.0-alpha3 . Is really the plugin a problem?

**Comment by eduardocucharro** [comment] 2015-12-23 17:44
To let you know I tried 2.0.0-alpha(1, 2, 3). It happened in all versions. @kneth

**Comment by kneth** [comment] 2015-12-28 07:22
@eduardocucharro Can you share a small app which demonstrate the issue?

**Comment by eduardocucharro** [comment] 2015-12-29 11:42
I've taken a look to other issues and everything points to a multidex problem @kneth ! I started developing to lollipop and it was ok until I tried Jelly Bean. :)

**Comment by kneth** [comment] 2016-01-04 08:27
@eduardocucharro Thanks for the update.

**Comment by tajchert** [comment] 2016-02-02 23:02
I have same problem with 'com.android.tools.build:gradle:2.0.0-alpha9' - I cannot run as I get "XYZ is not part of the schema for this Realm."
I cannot go to alpha4 (or lower) as I get "plugin is too old" message (AS canary build 2.0 Preview 9).

Problem seems to occur when I add any other object to exisiting one, example:
```
public class Foo extends RealmObject {
   private Baa baa;
}

public class Baa extends RealmObject {
}
```
Or same with RealmList.

**Comment by cmelchior** [comment] 2016-02-12 09:37
Are you still seeing this problem with `2.0.0-beta3` ?

**Comment by avenwu** [comment] 2016-02-26 07:45
Similar exception  while using 2.0.0-beta5

java.lang.IllegalAccessError: Method 'void io.realm.Realm.checkIfValid()' is inaccessible to class 'io.realm.UserInfoRealmProxy' (declaration of 'io.realm.UserInfoRealmProxy' appears in /data/data/package name/files/instant-run/dex/slice-slice_9_7c81990a9272e50f79d25c2c16b10bad810e7cd5-classes.dex)

**Comment by cmelchior** [comment] 2016-02-26 07:49
@avenwu That problem is because of Instant Run. It should apparently be fixed in beta6. You can see more here: https://github.com/realm/realm-java/issues/2139

Since we haven't been able to reproduce this issue and it should apparently be fixed in beta6, I'll close this issue now. Feel free to reopen if you see it again using beta6 and above

**Closed by cmelchior** 2016-02-26 07:49 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help

**Comment by avenwu** [comment] 2016-02-27 07:32
@cmelchior thx for your reply

**Comment by Hakosuka** [comment] 2016-07-01 10:42
Hi, I've come across this problem too, but I'm calling:
`realmConfig = new RealmConfiguration.Builder(getActivity().getApplicationContext()).build();`
in the onCreate() method of a Fragment.

I've seen Gradle get mentioned, I'm currently using:
`classpath 'com.android.tools.build:gradle:2.1.2'`

**Comment by kneth** [comment] 2016-07-01 12:37
As I recall, this was related to Instant Run. Since Instant Run and Android Studio are moving targets at the moment, we will need to know what version of Android Studio you are using.

**Comment by Hakosuka** [comment] 2016-07-01 14:32
Hi kneth, I've since switched off Instant Run and now my app works fine. I'm using Android Studio 2.1.2.

**Comment by kneth** [comment] 2016-07-04 07:15
@Hakosuka Great to hear that it works now. Looking at the change log for Android Studio for the last few preview releases, Instant Run is still work-in-progress :-(

**Comment by centerback** [comment] 2016-08-02 19:40
I recently updated Android Studio from 1.5 to 2.1.2.
My project does not use Realm, and i got the same error.  Switching off Instant Run solved the issue.
Go to Settings > Build > InstantRun

**Comment by hassanabidpk** [comment] 2016-08-06 09:39
@centerback  Just encountered the same problem and did what you suggested. It is working fine! Thanks
