### ISSUE TITLE
How to get a sorted RealmResult based on the query string position in index fields string?

### ISSUE THREAD

**Issue by razon30** [realm/realm-java#6501] opened 2019-04-26 00:28 UTC
> When performing query, I want to get a RealmResult where the search field  starts with query text will be added first, then the strings that contains the query string somewhere in the search field except start and end. And at last there will be objects whose search fields ends with search query.

> For example, I have `data = {"razon", "zebra", "fixar",  "razib", "furan"}` . Now, if I query with "ra", I want the realm result to return data in this order, `result = {"razon", "razib" , "furan",  "zebra"}`

> In the example, "razon" and "razib" starts with "ra", so they are in the front, then comes "furan" as ra is in somewhere in the string except start and end. And at the last "zebra" is added cause it ends with "ra".
How can I do it with a single query or in a efficient way?

**Comment by Zhuinden** [comment] 2019-04-26 08:32
Realm sort by string is lexicographical, so that would mean you'd need to do this transformation yourself on detached instances.

**Comment by cmelchior** [comment] 2019-04-26 08:48
Yes, this unfortunately not something you can express directly in our sorting logic. 
Being able to do it is a duplicate of https://github.com/realm/realm-java/issues/2744

For now, you would need to use `copyFromRealm` and do custom sorting.

**Closed by cmelchior** 2019-04-26 08:48 UTC
Labels: O:User, T:Duplicate
