### ISSUE TITLE
Unable to store string array to RealmList

### ISSUE THREAD

**Issue by Poojan31** [realm/realm-java#3747] opened 2016-11-04 13:51 UTC
Hi,
I am working on one project where i have to fetch json object from server and store it to realm. I am using retrofit to fetch json object from server. I have created a model class for that json object. So i can easily get data.The problem is that whenever there is an array of string in object, retrofit is unable to fetch it.

json sample:

```
{ 
"data1": [
    {
      "temp1": "abc",
      "temp2": "abc",
      "temp3": "abc",
      "temp4": "abc"
    },
    {
      "temp1": "abc",
      "temp2": "abc",
      "temp3": "abc",
      "temp4": "abc"
    },

"data2": {
    "temp1": ["1","2" ],
    "temp2": ["1","2","3" ],
    "temp3": ["1","2","3","4","5","6" ]
  }
}
```

Model Class for data2:

```
public class data2 extends RealmObject {

    private RealmList<BaseStringModel> temp1;
    private RealmList<BaseStringModel> temp2;
    private RealmList<BaseStringModel> temp3;

//getter-setter with default and parameterised
}
```

BaseStringModel class has one string variable and its getter-setter with default and parameterised constructor and it implements RealmModel and it extends to RealmObject.

Model class for Retrofit:

```
public class RetrofitModel extends RealmObject {
    private data2 data;

//getter-setter with default and parameterised
}
```

Retrofit is giving me this error:
`java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 10 path $.data2.temp1[0]  `

But when i comment private data2 data line in RetrofitModel, It just works fine. I get all other data except data2.

How do i solve this error?
NEED HELP!!

**Comment by Zhuinden** [comment] 2016-11-04 13:57
Duplicate of https://github.com/realm/realm-java/issues/575

**Comment by Zhuinden** [comment] 2016-11-04 19:34
Have you tried http://stackoverflow.com/a/30014833/2413303 ?

**Closed** 2016-11-05 08:07 UTC
Labels: T:Duplicate

**Comment by Zhuinden** [comment] 2016-11-05 08:35
(Honestly, I would just consider joining the strings, and storing them in a single field.)
