### ISSUE TITLE
Can't load my own xxx.so file if add realm to my module

### ISSUE THREAD

**Issue by 468122151** [realm/realm-java#2222] opened 2016-02-03 01:53 UTC

**Comment by 468122151** [comment] 2016-02-03 01:58
I add "  compile 'io.realm:realm-android:0.87.4' " in build.gradle, after I run my app , it gives an exception that couldn't find "libvoiceRecog.so"., and  libvoiceRecog.so is in src->main->jniLibs folder. If I remove realm it works well again. Any solutions?

**Comment by beeender** [comment] 2016-02-03 02:23
Take a look at https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso

Is your problem only on 64 bit device?

**Comment by 468122151** [comment] 2016-02-03 02:53
I'v tried this  https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso ,it doesn't work on both -bit and   32-bit devices. When app runs on 32-bit device, it gives "findLibrary returned null". The exception is system can't load my .so file ,not realm.so.

**Comment by beeender** [comment] 2016-02-03 02:54
Check the generated apk file, does the `.so` file exist in the apk?

**Comment by 468122151** [comment] 2016-02-03 03:05
in build->intermediates->jniLIbs->debug, I can find my .so file.

**Comment by beeender** [comment] 2016-02-03 03:08
Yes, but what about the generated apk file? It should be in `./app/build/outputs/apk/`. Use any unzip tool to decompress it and check.

**Comment by 468122151** [comment] 2016-02-03 03:38
Maybe I've already known the reason.In fact, in  **debug.apk** ,system generate some folders in **lib**,they are **arm64-v8a **, **armeabi**, **armeabi-v7a** ,*mips**, **x86** and **x86_64**. In my module, I only use **armeabi** ann **x86**, so I can't find my **.so** in **armeabi-v8a** and  **armeabi-v7a** .However, my device is **arm64-v8a** and  **armeabi-v7a**  , then I add **exclude "lib/arm64-v8a/librealm-jni.so"**  and **exclude "lib/armeabi-v7a/librealm-jni.so"** in **build.gradle**, then it works,problem is resolved ! Thank you very much !

**Comment by beeender** [comment] 2016-02-03 03:39
Yes, that is exactly the reason! Good to hear the problem is solved. I am closing this issue now. Let us know if you have further questions!

**Closed by beeender** 2016-02-03 03:39 UTC
Labels: S:Waiting For User, T:Help
