### ISSUE TITLE
DB file size is too big

### ISSUE THREAD

**Issue by AliTarhini** [realm/realm-java#6600] opened 2019-08-29 09:21 UTC
#### Goal
I want to use SD card to save and load Realm data.

My db file size is too big, I keep getting out of memory exception.

**Comment by bmunkholm** [comment] 2019-08-29 10:50
I'm not sure how we can help you if your database file is too big?
You will need to provide a lot more details for us to be in any position to help. Including using the issue full template.

**Comment by AliTarhini** [comment] 2019-08-29 12:04
the size of the file reaches 1.5 GB and I only have 2 GB free storage on the phone.

So I'm thinking of a way to save my data on an external sd card instead of the phone storage

**Comment by bmunkholm** [comment] 2019-08-29 13:49
For the phone to open such a big file, it does require you have memory for it. And you are running of of memory, not disk space.
It's a huge file for a mobile. Perhaps you can divide the data into multiple files?
What are you storing in the file? Hopefully not pictures or movies :-)

**Comment by cmelchior** [comment] 2019-11-27 13:27
Closing as as a duplicate of https://github.com/realm/realm-java/issues/6667
That issue also contains links to our FAQ with descriptions of what might cause a Realm file to grow to much in size.

**Closed** 2019-11-27 13:32 UTC
Labels: O-Community, Pipeline-Waiting-for-User, T-Duplicate
