### ISSUE TITLE
Missing armebi native fro 2.1.1 ?

### ISSUE THREAD

**Issue by kuno** [realm/realm-java#3734] opened 2016-11-02 07:30 UTC
For some reasons, our project required an `armebi` native binary, but I was surprised to find out the v2.1.1 of realm-javs seems dont ship with `armebi` native , only `arm-v7a`,`armv8a`,`x86`,`x86_64`,`mips`.

Can someone kindly explain to me why ?

**Comment by MGaetan89** [comment] 2016-11-02 07:35
From the [changelog](https://github.com/realm/realm-java/blob/master/CHANGELOG.md):
> armeabi is not supported anymore.

As for the why, I think it's because they moved JNI build to CMake (still from the changelog). I think I read in an other issue that they may reintroduce support in a future version.

**Comment by Zhuinden** [comment] 2016-11-02 07:41
In fact, it's marked with "in progress" because the lack of armeabi is causing more troubles than anticipated.

**Comment by cmelchior** [comment] 2016-11-02 08:13
Hi @kuno The issue is being tracked here #3506 . Closing this as an duplicate.

**Closed by cmelchior** 2016-11-02 08:13 UTC
Labels: T:Duplicate

**Comment by kuno** [comment] 2016-11-02 08:18
sorry been duplicated.
