### ISSUE TITLE
Unrecoverable error. Decryption failed

### ISSUE THREAD

**Issue by jason-gogolook** [realm/realm-java#6151] opened 2018-09-05 08:17 UTC
#### Goal

I want to execute commitTraction normally.

#### Expected Results

execute transaction normally

#### Actual Results

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Decryption failed () in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 144
       at io.realm.internal.SharedRealm.nativeCommitTransaction(SharedRealm.java)
       at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:251)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:400)
       at io.realm.Realm.commitTransaction(Realm.java:15134)

#### Steps & Code to Reproduce

I saw this error keep occurring on crashlytics when executing "commitTraction" then I saw this error, but I couldn't reproduce this issue on my own.

#### Code Sample

```java

            for (int i = 0; i < length; i++) {
                tmpObject = jsonArray.getJSONObject(i);

                name = tmpObject.getString(JSON_KEY_CALLER);
                number = tmpObject.getString(JSON_KEY_PHONE_NUMBER);

                realmJsonObject = new JSONObject();
                realmJsonObject.put(RealTimeSpamNumber.COL.NAME, name);
                realmJsonObject.put(RealTimeSpamNumber.COL.NUMBER, number);
                realmJsonObject.put(RealTimeSpamNumber.COL.E164, UtilsTelephony.parseE164Number(number));
                realmJsonObject.put(RealTimeSpamNumber.COL.ID, idx++);

                realmJsonArray.put(realmJsonObject);
                if (Log.DEBUG) {
                    Log.d(LOGTAG, "[parseDatabase] caller = " + name + ", number = " + number + ", e164 = " + realmJsonObject.getString(RealTimeSpamNumber.COL.E164));
                }

                if (realmJsonArray.length() >= 500) {
                    realm.beginTransaction();
                    realm.createOrUpdateAllFromJson(RealTimeSpamNumber.class, realmJsonArray);
                    realm.commitTransaction();

                    realmJsonArray = new JSONArray();
                }
            }

```

#### Version of Realm and tooling
Realm version(s): ? 
io.realm:realm-gradle-plugin:4.1.0

Realm sync feature enabled: 
no

Android Studio version: ? 
3.1.4

Which Android version and device: ? 
Most device : Galaxy Note2
Most Os version : 4.4.2

**Comment by cmelchior** [comment] 2019-03-19 13:45
Outdated, so closing. If this is still a problem please re-open but we really need a sample project demonstrating the issue so we can debug it.

**Closed by cmelchior** 2019-03-19 13:45 UTC
Labels: O:User, Reproduction Required, T:Bug-Crash

**Comment by saeedmozaffari** [comment] 2019-07-01 12:12
I have following error also i can't reproduce it just see at fabric.

```java
Unrecoverable error. Decryption failed () 
in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
```
