### ISSUE TITLE
Android studio 2.1.2 and jdk1.8.0_92 i used this error help me

### ISSUE THREAD

**Issue by DineshkumarDevarasu** [realm/realm-java#3136] opened 2016-07-05 13:02 UTC
Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV132300Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAppindexing810Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement810Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE

**Comment by Zhuinden** [comment] 2016-07-05 15:08
Duplicate of https://github.com/realm/realm-java/issues/3134 except this doesn't really have any info

**Comment by stk1m1** [comment] 2016-07-05 15:19
Like @Zhuinden says, this is duplicated without much information. I'm closing this issue.

**Closed by stk1m1** 2016-07-05 15:19 UTC
