### ISSUE TITLE
"Delete Realm if migration needed" always needed if version goes up

### ISSUE THREAD

**Issue by shidobecker** [realm/realm-java#5946] opened 2018-05-11 21:09 UTC
#### Goal

> Be able to upgrade Realm Schema Version without deleteRealmIfMigrationNeeded() being called every time.

#### Expected Results

> No Data Loss since no RealmObject has been changed, only the realm schema version number has increased

#### Actual Results

>  Every time a Realm schema version is updated, even without realm object changes, a migration or a deleteRealmIfMigrationNeeded() is called. (My RealmSchemaVersion follows the versionCode of my application), which i think it's not the best behavior, since all realm tables /properties are the same.

#### Steps & Code to Reproduce

>Realm Schema version is the same as the app versionCode
 Build and install the application with the versionCode like `40` 
Log-in, save user data.
Rebuild and change my versionCode to `41` then on app class
deleteRealmIfMigrationNeeded() is called.

#### Code Sample
**This is my App class:**

```java

  Realm.init(this);
        realmConfiguration = new RealmConfiguration.Builder()
            .schemaVersion(BuildConfig.REALM_SCHEMA_VERSION)
            .migration((realm, oldVersion, newVersion) -> RealmAutoMigration.migrate(realm))
            .deleteRealmIfMigrationNeeded()
            .build();

        Realm.setDefaultConfiguration(realmConfiguration);

```

#### Version of Realm and tooling
Realm version(s): 5.1.0

Realm sync feature enabled:  no

Android Studio version: 3.0

Which Android version and device: any, 5.0, 6.0, 7.0 ,8.0

Reference:
I already opened a similar issue last year, @Zhuinden  Help-me me a lot with his RealmAutoMigration helper class, but still this same issue persists, so I created a new one to specify easily the new issue I'm facing:
https://github.com/realm/realm-java/issues/5542

**Comment by tgoyne** [comment] 2018-05-11 21:31
Incrementing the schema version is how you ask Realm to perform a migration. If you don't want a migration to happen every time you increase your application's version number, then it makes no sense to use that as your schema version.

**Comment by Zhuinden** [comment] 2018-05-12 01:13
If you define `deleteIfMigrationNeeded()` then migration will be ignored, I think.

To initiate a migration, you need to remove `deleteIfMigrationNeeded()` and bump schema version number.

**Comment by cmelchior** [comment] 2018-05-12 20:38
Hi @shidobecker 
This is working as intended as others have mentioned above. You should really decouple your schema version from the version code of the app.

Closing

**Closed by cmelchior** 2018-05-12 20:38 UTC

**Comment by shidobecker** [comment] 2018-05-12 21:43
@tgoyne  @cmelchior  I see, I misunderstood how Realm is suppose to react to changes. Already created a new buildVariable to control Realm version. Thank you for the answers.

@Zhuinden The power of reflection indeed !
That class is just amazing
