### ISSUE TITLE
Realm.getInstance hangs forever (using Bolts).

### ISSUE THREAD

**Issue by tspecht** [realm/realm-java#610] opened 2014-11-24 15:34 UTC
Hi,

I'm currently trying to use Realm in conjunction with bolds to do an asynchronous search of a huge dataset. When trying to fetch an Realm instance at the beginning of the search using 

```
Realm realm = Realm.getInstance(mContext, false);
```

The first couple of times it works but after some time the method simply is not returning at all. Is there anything I could do to fix this on my side?

**Comment by cmelchior** [comment] 2015-04-16 09:31
Hi @tspecht 
Are you still seeing this bug?
Also, Bolts is a pretty big framework, and if you are still seeing the bug it is most likely caused by some synchronisation issue somewhere, making it impossible for us to debug. Are you able to reproduce this in a sample project we can look at?

**Comment by beeender** [comment] 2017-03-24 10:15
@tspecht I am just closing this issue now since the similar issue has not been reported for a long time. Probably it is fixed :) please just let me know if this needs to be reopened.

**Closed by beeender** 2017-03-24 10:15 UTC
Labels: S:Idea Backlog

**Comment by Zhuinden** [comment] 2017-03-24 10:46
This was most likely fixed with 0.83.0 when `getInstance()` no longer hangs if there is an open write transaction on any threads.

**Comment by cmelchior** [comment] 2017-03-24 10:48
@Zhuinden you remember our changelog better than we do 👏 ❤️
