### ISSUE TITLE
Opening Realm files of format version 0 is not supported by this version of Realm

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-java#7013] opened 2020-08-01 16:01 UTC
#### Goal
Run the app and does not crash on startup, similar issues here:

 - https://github.com/realm/realm-js/issues/3002
 - https://github.com/realm/realm-java/issues/6889
 - https://github.com/realm/realm-cocoa/issues/6638

#### Actual Results
```
Fatal Exception: io.realm.exceptions.RealmFileException: Opening Realm files of format version 0 is not supported by this version of Realm (Database has an unsupported version and cannot be upgraded
Exception backtrace:
<backtrace not supported on this platform>) (/data/data/com.my.app/files/default.realm) in /Users/eduardo.lopez/git/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
       at io.realm.BaseRealm.<init>(BaseRealm.java:137)
       at io.realm.BaseRealm.<init>(BaseRealm.java:104)
       at io.realm.Realm.<init>(Realm.java:163)
       at io.realm.Realm.createInstance(Realm.java:499)
       at io.realm.RealmCache.createInstance(RealmCache.java:507)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:473)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:414)
       at io.realm.Realm.getDefaultInstance(Realm.java:407)
       at com.my.app.rules.foo.Bar.getRealm(BarImpl.java:31)
       at com.my.app.rules.foo.Bar.sync(BarImpl.java:76)
       at com.my.app.ui.activity.MainActivity$sync$$inlined$fez$1.onSuccess(MainActivity.java:1383)
       at com.my.app.ui.activity.MainActivity$fez$1.onSuccess(MainActivity.java:115)
       at com.my.app.ui.activity.MainActivity$sync$$inlined$fez$1.onSuccess(MainActivity.java:115)
       at com.google.android.gms.tasks.zzm.run(zzm.java:4)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.google.android.gms.internal.tasks.zzb.dispatchMessage(zzb.java:6)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

#### Steps & Code to Reproduce
Possibly related to encrypted Realm + migration + Realm file version.

#### Version of Realm and tooling

Realm version(s): 7.0.1

Realm Sync feature enabled: No

Android Studio version: 4.0

Android Build Tools version: 29.0.3

Gradle version: 6.4.1

Which Android version and device(s): Around 12 different devices, crashing on:

 - Samsung S7
 - Samsung  Galaxy Note10+
 - Samsung Galaxy S20+ 5G
 - Samsung Galaxy S10 
 - Samsung A series
 - Sony Xperia XA1 
 - Huawei P20 Pro

**Comment by cmelchior** [comment] 2020-08-04 14:01
Duplicate of https://github.com/realm/realm-java/issues/6889, so merging it into that one.

**Closed by cmelchior** 2020-08-04 14:01 UTC
Labels: O-Community, T-Duplicate
