### ISSUE TITLE
TimeoutException - timed out after 10 seconds

### ISSUE THREAD

**Issue by lawloretienne** [realm/realm-java#1390] opened 2015-08-14 18:10 UTC
I am getting these crashes in Fabric

```
java.util.concurrent.TimeoutException: io.realm.internal.Context.finalize() timed out after 10 seconds
       at java.lang.Object.equals(Object.java:205)
       at java.util.ArrayList.remove(ArrayList.java:418)
       at io.realm.internal.Context.cleanRows(Context.java:69)
       at io.realm.internal.Context.executeDelayedDisposal(Context.java:61)
       at io.realm.internal.Context.finalize(Context.java:113)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
       at java.lang.Thread.run(Thread.java:818)
```

```
java.util.concurrent.TimeoutException: io.realm.internal.Context.finalize() timed out after 10 seconds
       at java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:47)
       at io.realm.internal.Context.cleanRows(Context.java:70)
       at io.realm.internal.Context.executeDelayedDisposal(Context.java:61)
       at io.realm.internal.Context.finalize(Context.java:113)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
       at java.lang.Thread.run(Thread.java:841)
```

What could be causing the timeout?  Also I have a try catch block around the realm transaction but the exception is not being caught.

**Comment by cmelchior** [comment] 2015-08-14 18:34
Yes, that is a bug in our code that cleans up the native resources. It was unfortunately slower than it should have been which has the effect you see there. We merged a fix to our master today: https://github.com/realm/realm-java/pull/1379 So it is available in our SNAPSHOT or the next release.

**Closed by cmelchior** 2015-08-14 18:34 UTC
Labels: support

**Comment by cmelchior** [comment] 2015-08-17 06:20
Just to update. We apparently had a problem with our CI server, so the SNAPSHOT was never released. It should be available now with this fix.

**Comment by lawloretienne** [comment] 2015-08-17 06:35
When is v 0.83 slated to be released?

**Comment by lawloretienne** [comment] 2015-08-17 06:35
When is v 0.83 slated to be released?

On Sun, Aug 16, 2015 at 11:20 PM, Christian Melchior <
notifications@github.com> wrote:

> Just to update. We apparently had a problem with our CI server, so the
> SNAPSHOT was never released. It should be available now with this fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/1390#issuecomment-131692075>.
>



-- 
-Etienne Lawlor (Software Developer)

**Comment by cmelchior** [comment] 2015-08-17 06:38
We don't have a set timeline, but a good guess would be in a couple of week.s

**Comment by lawloretienne** [comment] 2015-09-04 20:56
@cmelchior Is this resolved in v0.82.2 ?

**Comment by lawloretienne** [comment] 2015-09-04 21:27
I noticed the changelog references v0.83
https://github.com/realm/realm-java/blob/master/changelog.txt

Is that available yet?

**Comment by sumitnaharia** [comment] 2017-12-08 09:57
Session 0: Exception while stopping repeating: 
                                                                                            android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): cancelRequest:272: Camera device no longer alive
                                                                                                at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:633)
                                                                                                at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926)
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378)
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:514)
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:228)
                                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                             Caused by: android.os.ServiceSpecificException: cancelRequest:272: Camera device no longer alive
                                                                                                at android.os.Parcel.readException(Parcel.java:1697)
                                                                                                at android.os.Parcel.readException(Parcel.java:1636)
                                                                                                at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:350)
                                                                                                at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:93)
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:926) 
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:378) 
                                                                                                at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:514) 
                                                                                                at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:228) 
                                                                                                at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                                at android.os.HandlerThread.run(HandlerThread.java:61) 
12-08 15:19:36.070 17309-17319/com.example.android.rippleeffectdemo E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
                                                                                      Process: com.example.android.rippleeffectdemo, PID: 17309
                                                                                      java.util.concurrent.TimeoutException: com.opentok.android.Publisher.finalize() timed out after 10 seconds
                                                                                          at com.opentok.android.PublisherKit.finalizeNative(Native Method)
                                                                                          at com.opentok.android.PublisherKit.finalize(PublisherKit.java:512)

**Comment by sumitnaharia** [comment] 2017-12-08 09:58
any one can give me solution how to handle this bugs

**Comment by Zhuinden** [comment] 2017-12-08 10:15
Update to a version that is 2.3.0 or higher

**Comment by anujjpandey** [comment] 2018-02-22 07:07
@Zhuinden Update to 4.3.4 but it is still there

**Comment by cheshingchun** [comment] 2018-03-15 08:39
@Zhuinden Using the Gradle plug-in, it is still there.
