### ISSUE TITLE
java.io.FileNotFoundException: 

### ISSUE THREAD

**Issue by cwangkkb** [realm/realm-java#1824] opened 2015-11-25 07:14 UTC
Error:Execution failed for task ':common:transformNative_libsWithSyncJniLibsForRelease'.
> java.io.FileNotFoundException: /Users/cwang/workspace/AS/work/Mobile-Android/common/build/intermediates/bundles/release/jni/lib/armeabi/librealm-jni.so (No such file or directory)

Help to see what's going onJust finished to update the Android studio 2.0

**Comment by kneth** [comment] 2015-11-26 08:32
What version of Realm do you use?

**Comment by cwangkkb** [comment] 2015-11-26 08:48
I have been solved, is not the cause of the Realm, is a question of grade configuration。

After I upgrade Android Studio 2.0, I gradle plugin upgrade into 2.0.0, lead to the problem.

Excuse me！
Thank you!

**Comment by kneth** [comment] 2015-11-26 09:09
Happy to hear it's not caused by Realm. I close the issue. If you continue to experience the issue, don't hesitate to either reopen or create a new issue.

**Closed by kneth** 2015-11-26 09:09 UTC
Labels: Help, Pending
