### ISSUE TITLE
Fatal Exception: java.util.concurrent.TimeoutException io.realm.internal.TableView.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by arenaq** [realm/realm-java#2989] opened 2016-06-13 08:53 UTC
**Realm version**: 0.90.1

Android Studio version: 2.1.1

Happens on various Android versions (from 4.2.2 to 5.0.1) and devices.

**Comment by cmelchior** [comment] 2016-06-13 10:38
Hi @arenaq 

Are you able to reproduce this yourself? We have made continous improvements in how we handle native resources and the above should only be possible if you iterate over extremely large datasets. Is that something you are doing somewhere?

**Comment by arenaq** [comment] 2016-06-13 11:42
Hello @cmelchior 

Unfortunatelly I am not able to reproduce the error. What numbers do you have in mind when you talking about "extremely large datasets"?

**Comment by cmelchior** [comment] 2016-06-13 11:43
It depends on the phone, but 10000+ and even then it is most likely something you have to do repeatedly

**Comment by arenaq** [comment] 2016-06-13 11:49
Well, we dont have that many, but I'll check for any loops etc. Can you think of any other way that could produce this exception?

**Comment by stk1m1** [comment] 2016-06-13 18:26
Hi @arenaq 

Here's one suggest we can make. Althought it might not that obvious from users' prospective, we've done alot of bug fixes in version 1.0.0. It would be great if you can give a try to the latest version to check if your error persists.

**Comment by narayank** [comment] 2016-06-14 10:00
Hello - I work on the Android Platform. I came here to file a bug but saw this issue and thought I'd comment. Most such issues we've seen in the past have been due to incorrectly written finalizers. If you have a finalizer that performs native "cleanup" and deallocation, you should take care to clear out the pointer to native memory. This is required because application (or other classes) that hold a reference to this finalized object might have their finalizers run *after* the object's finalizer has run. In other words, there's no specified order in which finalizers on collected objects are run.

We've been working around this by using PhantomReferences (see https://android-review.googlesource.com/#/c/175765/10).

**Comment by cmelchior** [comment] 2016-06-14 10:14
Hi @narayank 
Thanks for the input. We are actually already using PhantomReferences for our native object references: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/internal/Context.java, however we haven't migrated all native objects yet, which we should.

The primary reason for migrating has not been the risk of resurrecting objects though, but more that objects with finalisers are really slow to be reclaimed, which is what has historically caused these errors for us.

**Comment by cmelchior** [comment] 2016-06-14 10:33
Replacing everything with phantom references is being tracked here: https://github.com/realm/realm-java/issues/2496

**Comment by kneth** [comment] 2016-06-24 09:40
Closing issue. We wish to use phantom references to solve it.

**Closed by kneth** 2016-06-24 09:40 UTC
Labels: S:Waiting For User, T:Help
