### ISSUE TITLE
Document difference between copyToRealm and createFromJson

### ISSUE THREAD

**Issue by cgcgbcbc** [realm/realm-java#1483] opened 2015-09-19 10:19 UTC
currently the copyToRealmOrUpdate will update unset fields to default value, which differs from the json api.

test:
```java
//FooUpdate.java
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
public class FooUpdate extends RealmObject {
    @PrimaryKey
    private int id;
    private int a;
    private int b;

    public int getA() {
        return a;
    }

    public void setA(int a) {
        this.a = a;
    }

    public int getB() {
        return b;
    }

    public void setB(int b) {
        this.b = b;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}

//UpdateTestModule.java
import io.realm.annotations.RealmModule;
@RealmModule(library = true, classes = {FooUpdate.class})
public class UpdateTestModule {
}

//RealmUpdateTest.java
import android.support.test.InstrumentationRegistry;
import android.support.test.runner.AndroidJUnit4;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import io.realm.Realm;
import io.realm.RealmConfiguration;
import io.realm.RealmResults;
@RunWith(AndroidJUnit4.class)
public class RealmUpdateTest {

    private RealmConfiguration configuration;

    @Before
    public void setUp() throws Exception {
        configuration = new RealmConfiguration.Builder(InstrumentationRegistry.getContext())
            .name("realm.update.test")
            .schemaVersion(0)
            .setModules(new UpdateTestModule())
            .build();
        Realm.deleteRealm(configuration);

    }
    @Test
    public void testRealmUpdate() throws Exception {
        Realm realm = Realm.getInstance(configuration);
        final FooUpdate foo = new FooUpdate();
        foo.setId(1);
        foo.setA(1);
        foo.setB(2);
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(foo);
        realm.commitTransaction();
        RealmResults<FooUpdate> results = realm.where(FooUpdate.class).equalTo("id", 1).findAll();
        Assert.assertEquals(1, results.size());
        Assert.assertEquals(1, results.get(0).getA());
        Assert.assertEquals(2, results.get(0).getB());

        final FooUpdate other = new FooUpdate();
        other.setId(1);
        other.setA(2);
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(other);
        realm.commitTransaction();

        realm.refresh();

        results = realm.where(FooUpdate.class).equalTo("id", 1).findAll();
        Assert.assertEquals(1, results.size());
        Assert.assertEquals(2, results.get(0).getA());
        Assert.assertEquals(2, results.get(0).getB()); // fail
    }
}
```

**Comment by cmelchior** [comment] 2015-09-21 07:27
Hi @cgcgbcbc 
Yes, that is by design. The reason is that in a normal object we cannot tell the difference between an value not being set and being set to the default value, e.g. if you have an `int` with value `0` we don't know if you actually set the value to `0`. So if you are using normal objects we have to copy all properties.

That is different with JSON where it is possible to tell the difference as that field is then missing all together.

However that difference is not described in the JavaDoc for either method which should probably be done to avoid misunderstandings.

**Comment by cgcgbcbc** [comment] 2015-09-21 08:01
> e.g. if you have an int with value 0 we don't know if you actually set the value to 0

How about supporting a boxing type, e.g. `Interger`? Though the difference behaviours between `Integer` and `int` may lead confusion...

**Comment by cmelchior** [comment] 2015-09-21 08:03
We will add support for `Integer` when we add Null support, however that won't fix the underlying problem as you might want to specifically set the field to `null` also.

**Comment by cgcgbcbc** [comment] 2015-09-21 08:23
> We will add support for Integer when we add Null support, however that won't fix the underlying problem as you might want to specifically set the field to null also.

Yep.. I mistake.. Then seems the only approach is to add a spy in the proxy setter, which may cause performance issues..

**Comment by cmelchior** [comment] 2015-09-21 08:31
Yes, and while we could do it for our proxy objects. It would be impossible for your stand-alone objects. So if you desire this functionality, I am afraid the only option is representing your data as JSON or create custom helper classes/methods..

**Closed** 2016-02-18 14:36 UTC
Labels: S:In Progress, T:Doc
