### ISSUE TITLE
Database Migration Issue

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2513] opened 2016-03-24 15:18 UTC
#### Goal

Update Realm tables and Migration

#### Expected Results

Tables should be updated and migrated automatically

#### Actual Results

03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime: FATAL EXCEPTION: main
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime: Process: com.workoutguru.workoutcash, PID: 22111
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.workoutguru.workoutcash/com.workoutguru.workoutcash.DrawerActivity}: java.lang.IllegalArgumentException: Field already exists in 'TeamInfoDB': teamDescription
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:175)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:  Caused by: java.lang.IllegalArgumentException: Field already exists in 'TeamInfoDB': teamDescription
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.RealmObjectSchema.checkFieldNameIsAvailable(RealmObjectSchema.java:498)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.RealmObjectSchema.checkNewFieldName(RealmObjectSchema.java:484)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.RealmObjectSchema.addField(RealmObjectSchema.java:142)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.realmDB.Migration.migrate(Migration.java:27)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.BaseRealm$2.onResult(BaseRealm.java:604)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:242)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.BaseRealm.migrateRealm(BaseRealm.java:591)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.Realm.migrateRealm(Realm.java:1224)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.Realm.migrateRealm(Realm.java:1213)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.Realm.createInstance(Realm.java:237)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.Realm.getDefaultInstance(Realm.java:181)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.DrawerActivity.exportDatabase(DrawerActivity.java:268)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.DrawerActivity.onCreate(DrawerActivity.java:207)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5451)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:175) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
03-24 13:09:53.191 22111-22111/com.workoutguru.workoutcash E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 

#### Code Sample

This Is my current configuration for realm migration

RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                                            .schemaVersion(2)
                                            .migration(new Migration())
                                            .build();

public class Migration implements RealmMigration {

        @Override
        public void migrate(final DynamicRealm realm, long oldVersion, long newVersion){

            RealmSchema schema = realm.getSchema();

            if(oldVersion == 1){
                RealmObjectSchema sweatPointSchema = schema.get("UserInfoDB");
                        sweatPointSchema.addField("sweatPoints",Integer.class);

                oldVersion++;
            }

            if(oldVersion == 2){
                RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                        teamInfoSchema.addField("teamDescription",String.class);

                oldVersion ++;
            }

        }
    }

Now I need to update some particular table for next migration So I update my realm configuration and migration as follows

RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                                            .schemaVersion(3)
                                            .migration(new Migration())
                                            .build();

 public class Migration implements RealmMigration {

        @Override
        public void migrate(final DynamicRealm realm, long oldVersion, long newVersion){

            RealmSchema schema = realm.getSchema();

            if(oldVersion == 1){
                RealmObjectSchema sweatPointSchema = schema.get("UserInfoDB");
                        sweatPointSchema.addField("sweatPoints",Integer.class);

                oldVersion++;
            }

            if(oldVersion == 2){
                RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                        teamInfoSchema.addField("teamDescription",String.class);

                oldVersion ++;
            }

            if(oldVersion == 3){
                RealmObjectSchema leaderboardInfoSchema = schema.get("LeaderBoardDb");
                            leaderboardInfoSchema.addField("displayName",String.class);

                oldVersion ++;

            }

        }
    }

public class LeaderBoardDb extends RealmObject {
    private String percentile;

    private String rank;

    private String details;

    private String email;

    @PrimaryKey
    private String userId;

    private String name;

    private String rewards;

    private String sweatPointEarned;

    private String photoUrl;

    private String note;

    private String displayName;
}

**Comment by nhachicha** [comment] 2016-03-24 17:46
Hi @Sutirth 
like the error message suggests, the problem is within `teamDescription` that is already part of the schema, but somehow you manage to run into this block again
```java
if(oldVersion == 2){
            RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                    teamInfoSchema.addField("teamDescription",String.class);

            oldVersion ++;
        }
```
 and insert it, hence the error.

Can you confirm this behaviour using a break point?

Also what was the first version ever you've used to open your Realm? because if I suppose you didn't specify a version we should default to `0`, in this case your migration code should be as the follow.

```java
//  ***********************************************************
//  **** This will migrate from version 0 to version 1 ****
//  ***********************************************************
if (oldVersion == 0) { 
            RealmObjectSchema sweatPointSchema = schema.get("UserInfoDB");
                    sweatPointSchema.addField("sweatPoints",Integer.class);
            oldVersion++;
}

//  ***********************************************************
//  **** This will migrate from version 1 to version 2 ****
//  ***********************************************************
  if(oldVersion == 1) {
            RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                    teamInfoSchema.addField("teamDescription",String.class);

            oldVersion ++;
        }

//  ***********************************************************
//  **** This will migrate from version 2 to version 3 ****
//  ***********************************************************
        if(oldVersion == 2) {
            RealmObjectSchema leaderboardInfoSchema = schema.get("LeaderBoardDb");
                        leaderboardInfoSchema.addField("displayName",String.class);
            oldVersion ++;
        }
```

Cheers

**Comment by Sutirth** [comment] 2016-03-25 07:03
@nhachicha  Hi so I have debugged and checked when I insert version as 3 it crashes at old version reason explained by you is appropriate. Now I am in fix how should I resolve this issue ?? because according to docs and migration example I had read whenever you need to do changes in realm tables you need to specify in migration and file and in your class file.   Could let me know how should I proceed now?? Will my app on other devices will crash ??

**Comment by Sutirth** [comment] 2016-03-25 09:54
cc @beeender , @cmelchior

**Comment by Sutirth** [comment] 2016-03-26 13:00
So I did another update

 if(oldVersion == 3){

                RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                sweatPointFitnessSchema.addField("badgeSweatPoints",int.class);
                sweatPointFitnessSchema.setNullable("badgeSweatPoints",true);

                RealmObjectSchema userInfoSchema = schema.get("UserInfoDB");
                userInfoSchema.addField("profileImageUpdatedAt",String.class);

                oldVersion++;
            }

added   private int badgeSweatPoints in the class file I end up getting this stack trace.
 Caused by: io.realm.exceptions.RealmMigrationNeededException: Field 'badgeSweatPoints' does support null values in the existing Realm file. Use corresponding boxed type for field 'badgeSweatPoints' or migrate using io.realm.internal.Table.convertColumnToNotNullable().

With config set as:
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                                            .schemaVersion(4)
                                            .migration(new Migration())
                                            .build();

**Comment by Sutirth** [comment] 2016-03-26 13:01
cc @nhachicha

**Comment by nhachicha** [comment] 2016-03-31 05:32
Hi @Sutirth 

```java
sweatPointFitnessSchema.addField("badgeSweatPoints",int.class);
sweatPointFitnessSchema.setNullable("badgeSweatPoints",true);
```
primitive type `badgeSweatPoints` [can not be null](https://realm.io/docs/java/latest/#required-fields-and-null-values) 

try removing `sweatPointFitnessSchema.setNullable("badgeSweatPoints",true);` from the migration block.

Cheers

**Comment by nhachicha** [comment] 2016-04-06 13:54
Hi,
I'm closing this one since the issue if followed here now #2534

**Closed by nhachicha** 2016-04-06 13:54 UTC
Labels: S:Waiting For User, T:Help

**Comment by hadighasemian** [comment] 2018-11-21 09:03
i have this error

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: srf.com.hasebu, PID: 29180
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{srf.com.hasebu/srf.com.hasebu.controller.splashScreen.SplashActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.RealmObjectSchema io.realm.RealmObjectSchema.addField(java.lang.String, java.lang.Class, io.realm.FieldAttribute[])' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2841)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.RealmObjectSchema io.realm.RealmObjectSchema.addField(java.lang.String, java.lang.Class, io.realm.FieldAttribute[])' on a null object reference
        at srf.com.hasebu.orm.realm.RealmMigrate.migrate(RealmMigrate.java:23)
        at io.realm.BaseRealm$6.onMigrationNeeded(BaseRealm.java:781)
        at io.realm.internal.OsSharedRealm.runMigrationCallback(OsSharedRealm.java:533)
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:135)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at srf.com.hasebu.orm.realm.RealmManager$Companion.getNewInstance(RealmManager.kt:20)
        at srf.com.hasebu.orm.classes.UserManager$Companion.getUser(UserManager.kt:14)
        at srf.com.hasebu.controller.splashScreen.SplashActivity.<init>(SplashActivity.kt:21)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1180)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `


my migration

`
public class RealmMigrate implements RealmMigration {
    @Override
    public void migrate( DynamicRealm realm, long oldVersion, long newVersion) {
        // DynamicRealm exposes an editable schema
        RealmSchema schema = realm.getSchema();
        Log.v("old:",Long.toString(oldVersion));
        Log.v("new:",Long.toString(oldVersion));
//        try {
            if (oldVersion == 0) {
                oldVersion++;
            }
            if (oldVersion == 1) {
                RealmObjectSchema alarmSchema = schema.get("AlarmTime");
                alarmSchema.addField("alarmSt", int.class);
//            alarmSchema.transform(obj -> obj.setInt("alarmSt", 1));

                RealmObjectSchema settingSchema = schema.get("Settings");
                settingSchema.addField("pass", Boolean.class);
//            settingSchema.transform(obj -> obj.setBoolean("pass", false));

                settingSchema.addField("pass_key", String.class);
//            settingSchema.transform(obj -> obj.setString("pass_key", ""));
                oldVersion++;
            }
//        }catch (Exception e){
//            e.printStackTrace();
//        }
    }
    @Override
    public int hashCode() {
        return 37;
    }

    @Override
    public boolean equals(Object o) {
        return (o instanceof RealmMigrate);
    }
}`


my new instance

` fun getNewInstance(): Realm {
            val config = RealmConfiguration.Builder()
                    .name("hasebu.realm")
                    .schemaVersion(2)
//                    .deleteRealmIfMigrationNeeded()
//                    .compactOnLaunch()
                    .migration( RealmMigrate())
                    .build()
            Realm.setDefaultConfiguration(config)
            return Realm.getInstance(config)
        }

    }`

**Comment by hadighasemian** [comment] 2018-11-21 09:06
> ddfgfg

**Comment by Zhuinden** [comment] 2018-11-21 10:22
You are getting an object schema that was not created at all ever

**Comment by hadighasemian** [comment] 2018-11-21 13:31
what have i do now?

**Comment by Zhuinden** [comment] 2018-11-21 14:04
Properly formatted code:

``` kotlin
    fun getNewInstance(): Realm {
        val config = RealmConfiguration.Builder().name("hasebu.realm")
            .schemaVersion(2).migration(RealmMigrate()).build()
        Realm.setDefaultConfiguration(config)
        return Realm.getInstance(config)
    }
```

-----

``` java
    public class RealmMigrate implements RealmMigration {
        @Override
        public void migrate(DynamicRealm realm, long oldVersion, long newVersion) { // DynamicRealm exposes an editable schema 
            RealmSchema schema = realm.getSchema();
            Log.v("old:", Long.toString(oldVersion));
            Log.v("new:", Long.toString(oldVersion));
            if(oldVersion == 0) {
                oldVersion++;
            }
            if(oldVersion == 1) {
                RealmObjectSchema alarmSchema = schema.get("AlarmTime");
                alarmSchema.addField("alarmSt", int.class);
                alarmSchema.transform(obj -> obj.setInt("alarmSt", 1));
                RealmObjectSchema settingSchema = schema.get("Settings");
                settingSchema.addField("pass", Boolean.class);
                settingSchema.transform(obj -> obj.setBoolean("pass", false));
                settingSchema.addField("pass_key", String.class);
                settingSchema.transform(obj -> obj.setString("pass_key", ""));
                oldVersion++;
            }
        }

        @Override
        public int hashCode() {
            return 37;
        }

        @Override
        public boolean equals(Object o) {
            return (o instanceof RealmMigrate);
        }
    }
```

This means that there is a possibility that 

                RealmObjectSchema alarmSchema = schema.get("AlarmTime");

Returns `null` meaning that `AlarmTime` does not exist.

So what you can do is

        RealmObjectSchema alarmSchema = schema.get("AlarmTime");
        if(alarmSchema == null) {
              alarmSchema = schema.create("AlarmTime");
        }

Or in Kotlin

    val alarmSchema = schema.get("AlarmTime") ?: schema.create("AlarmTime")
