### ISSUE TITLE
Realm Crash On redeployment of apk

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#4203] opened 2017-02-20 16:21 UTC
Bug: Realm crash when redeployment of APK

Goal: App should start as a normal process

Expected Result: Values should be fetched from database and execute it properly

Actual Result: On redeployment of APK sometimes realm crashes with null pointer exception

Devices crash occurring: Nexus 6p Operating system= 7.1.1

Realm Version: 2.3.0

Android Studio Intant run disabled, Studio version 2.2

Steps were taken to reproduce: Say the first instance of my debug/release build I deploy build on mobile it executed perfectly now I perhaps change something in code and rebuild the project and execute it. It would crash on the first instance of realm used in my project with null pointer exception.

Realm Intialization in application class

    public class Myclass extends Application {
        
        @Override
        public void onCreate() {
           
          
    
    
            Realm.init(this);
    
            RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                    .schemaVersion(45)
                    .migration(new Migration(getApplicationContext()))
                    .build();
    
            Realm.setDefaultConfiguration(realmConfiguration);
          
            
    }

Added in manifest file as well

First Instance where Realm is used in Application

        public class ProfileActivity extends AppCompatActivity {
            Realm realm;
        
            @Override
            public void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_profile_update_layout);
                ButterKnife.bind(this);
                
                realm = Realm.getDefaultInstance();
                checkCredentialsExist();
        }
    
    
    private void checkCredentialsExist() {
            UserInfoDB userInfoDB = realm.where(UserInfoDB.class).findFirst();
    
      
    //Code written to retrieve  values
              
            }
        }

Here realm returns null as per debugging. Unable to proceed ahead with it

**Comment by beeender** [comment] 2017-02-21 06:23
the exception back trace please?

**Comment by Sutirth** [comment] 2017-02-21 06:25
W: No container asset found in /assets/containers. Checking top level /assets directory for container assets.
    E: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.workoutguru.workoutcash.stage/com.workoutguru.workoutcash.OnboardProfileActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.workoutguru.workoutcash.realmDB.UserInfoDB.getDisplayName()' on a null object reference
           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
           at android.app.ActivityThread.-wrap12(ActivityThread.java)
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
           at android.os.Handler.dispatchMessage(Handler.java:102)
           at android.os.Looper.loop(Looper.java:154)
           at android.app.ActivityThread.main(ActivityThread.java:6119)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.workoutguru.workoutcash.realmDB.UserInfoDB.getDisplayName()' on a null object reference
           at com.workoutguru.workoutcash.OnboardProfileActivity.checkCredentialsExist(OnboardProfileActivity.java:517)
           at com.workoutguru.workoutcash.OnboardProfileActivity.onCreate(OnboardProfileActivity.java:234)
           at android.app.Activity.performCreate(Activity.java:6679)
           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
           at android.os.Handler.dispatchMessage(Handler.java:102) 
           at android.os.Looper.loop(Looper.java:154) 
           at android.app.ActivityThread.main(ActivityThread.java:6119) 
           at java.lang.reflect.Method.invoke(Native Method) 
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by beeender** [comment] 2017-02-21 06:28
So `userInfoDB` is `null`? `findFirst()` could return null if there is no object match he query conditions.

**Comment by Sutirth** [comment] 2017-02-21 06:29
Realm object me null. UserInfoDB has all the entries I am just redeploying my apk

**Comment by Sutirth** [comment] 2017-02-21 07:00
I have even tried and exported database file to see if it contains any data. All the tables in database does not contains any value

**Comment by beeender** [comment] 2017-02-21 07:30
so maybe you need to set a breakpoint to where you write data to the db to see why it is not saved?

**Comment by Sutirth** [comment] 2017-02-21 07:33
So I did use breakpoint and saw data is saved perfectly in realm async transaction but sometimes on redeployment from studio it gives me null and sometimes it works perfectly. I have no clue to as what is going wrong

**Comment by beeender** [comment] 2017-02-21 07:41
does it work if you change the async transaction into a sync transaction?
After the async transaction committed, you will get the new version of data when the UI thread receives the changed notification. You can rely on the async transaction callback or the change listeners callback.

**Comment by Sutirth** [comment] 2017-02-21 07:44
I haven't tried changing my async transaction into sync because I am Using async transaction all over the app. But just a query Realm should just work perfectly on redeployment of build right??

**Comment by beeender** [comment] 2017-02-21 07:51
I am trying to help you to locate the problem. What i suggested is not asking you to change the async transaction all over the place. It is just about changing one specific transaction (the one initializing your data for `checkCredentialsExist`) to a synced transaction in order to figure out if it is a problem caused by timing.

> But just a query Realm should just work perfectly on redeployment of build right??

Yes, it should. If all the timing is right.

**Comment by Sutirth** [comment] 2017-02-21 08:13
So scenario of testing
1) If a user has freshly installed he has to enter all the details and password etc and upon success, I store the entire details in userInfoDB. Which goes ahead and works fine.
2) User has logged so I just do a check in an activity if checkCredentialsExist just move ahead no need to re-login. (This is the scenario where it crashes mostly).

**Comment by diegomontoya** [comment] 2017-02-22 04:55
@Sutirth Do what @beeender  suggests and just make the transaction that inserts/modifies UserInfoDB table sync instead of async and retry your code. Async means future  which means another activity can go to onCreate() BEFORE your async write executes or completes.

**Comment by Sutirth** [comment] 2017-02-22 07:06
@beeender  I tried moving the insert transaction into sync transaction with begin and commit transaction the scenario is still reproducible

**Comment by beeender** [comment] 2017-02-22 08:18
On which thread you are doing that "insert transaction", UI thread?

**Comment by Sutirth** [comment] 2017-02-22 08:20
@beeender  I tried it on AsyncTask Of android

**Comment by cmelchior** [comment] 2017-02-22 08:26
@Sutirth Can you please try to create a sample project that reproduces this. Since this involves a lot moving parts it is hard to guess what could be wrong without a working sample.

**Comment by Sutirth** [comment] 2017-02-22 08:28
@cmelchior  I even tried making a sample before posting here but it doesn't reflect over there

**Comment by zaki50** [comment] 2017-02-23 07:51
To fix a bug, we need to reproduce the bug.
Please let us know if you find a way to reproduce.

**Comment by Sutirth** [comment] 2017-02-23 08:43
@zaki50 Yes definitely I am trying to reproduce the exact case why and when its occuring

**Comment by kneth** [comment] 2017-03-06 11:49
@Sutirth Did you succeed in reproducing it?

**Comment by Sutirth** [comment] 2017-03-06 11:50
@kneth  nope but I am still getting crashes on redeployment

**Comment by kneth** [comment] 2017-03-06 12:28
@Sutirth I'll leave it open and hoping that you will be able to reproduce it soon.

**Comment by Sutirth** [comment] 2017-03-07 06:58
Update: I wrote migration code for some of my tables and due to this as well it caused crash on the same line as before. (Note: Migration code is perfect there no changes.)

**Comment by kneth** [comment] 2017-03-08 08:42
@Sutirth We do need a sample project which can reproduce the crash. Otherwise we are in the dark.

**Comment by kneth** [comment] 2017-03-30 10:26
I am closing the issue for now. If you are able to create a sample project which reproduce the error, we will reopen the issue.

**Closed by kneth** 2017-03-30 10:26 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help
