### ISSUE TITLE
Encrypted Realm database causes memory violation on Samsung S6 (and other ARM64 devices)

### ISSUE THREAD

**Issue by NirpE** [realm/realm-java#1037] opened 2015-04-16 08:09 UTC
With simple code like this running on Samsung S6 Edge, the application just closes, not crashes.

Edit: Samsung S6 uses Android Lollipop 5.0.2 with TouchWiz

<code>

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        final String dbName = "realm_crash";
        final String key = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

        Realm.deleteRealmFile(this, dbName);
        Realm r = Realm.getInstance(this, dbName, key.getBytes());
        r.close();
    }
</code>

4971-4971/? E/audit﹕ type=1701 msg=audit(1429171517.861:222): auid=4294967295 uid=10192 gid=10192 ses=4294967295 subj=u:r:untrusted_app:s0 pid=16358 comm="om.test.testing" reason="memory violation" sig=11

Force removing ActivityRecord{334a375a u0 com.test.testing/.MainActivity t141}: app died, no saved state

**Comment by cmelchior** [comment] 2015-04-16 08:53
Hi @NirpE 
That doesn't sound good. Is that the only thing you application does or is there other code running at the same time?

**Comment by NirpE** [comment] 2015-04-16 08:58
Hi @cmelchior 
That's the only thing, it's a hello world project.

**Comment by bmunkholm** [comment] 2015-04-16 20:22
Does it work in the simulator or other devices? Can you share the exact app, so we can verify if it's a device specifc issue?

**Comment by NirpE** [comment] 2015-04-17 04:04
Shared sample app source code with help@realm.io

We have not seen this with other devices, that sample project reproduces the issue with Samsung S6, also heard that Samsung S6 Edge behaves same way. Not tested with emulator.

**Comment by NirpE** [comment] 2015-04-20 04:29
Have you been able to reproduce this crash?

**Comment by cmelchior** [comment] 2015-04-20 06:55
Not yet. Mostly because we havn't been able to find a S6 to test on. It doesn't crash on the emulator.

**Comment by NirpE** [comment] 2015-04-20 10:27
Can you go and buy one ?

**Comment by bmunkholm** [comment] 2015-04-20 10:28
Sure - we did this morning, and can replicate the issue. We will look into it.

**Comment by NirpE** [comment] 2015-04-20 10:35
That's great, if you are able to find a fix it would be great if snapshot could be available in http://oss.jfrog.org/artifactory/oss-snapshot-local

**Comment by emanuelez** [comment] 2015-04-20 12:48
I was able to replicate the error on the following devices:
 * Samsung Galaxy S6 (Android 5.0.2)
* HTC Nexus 9 (Android 5.0.1)

So it looks like it's something related to the ARM64 architecture

Some findings so far:
 * It only fails in app. The same code works fine in a unit test.
 * It only fails with encryption enabled
 * It only fails if `Realm.deleteRealmFile()` is called before the Realm instantiation

Can you confirm such findings on your device?

We are trying to figure out what might cause the problem, inside or outside of Realm.

As a workaround, is it a possibility in your app not the delete the Realm file?
If not, would it be possible to delete all the data inside the Realm instead?

**Comment by NirpE** [comment] 2015-04-20 12:59
The memory violation error happens on our S6 even if the deleteRealmFile is not called in the example code.

**Comment by NirpE** [comment] 2015-04-21 04:43
Any updates on this? Unfortunately we got our S6 too late to verify this before shipping our update, so kinda annoying situation to be in having massive update on our app and making it unusable for customers with certain device.

**Comment by cmelchior** [comment] 2015-04-21 08:18
Hi @NirpE 
We are still trying to figure out the root cause for this issue. The lack of any sort of stacktrace/core dump is a bit concerning as it could indicate the crash is happening because of something out of the apps control. We will keep you posted.

**Comment by bmunkholm** [comment] 2015-04-30 23:25
Good news is we finally figured out that the Bionic libc has a bug for 64 bit in a method related to signal handling. We have found a workaround and expect to make a release Monday.

**Comment by emanuelez** [comment] 2015-05-04 14:34
We just pushed a release (0.80.2) with a fix for this bug.
Sorry it took so long, but we had to work around a bug in the Android libc implementation (Bionic)
Please let us know how this works for you.

**Closed** 2015-05-05 13:52 UTC
Labels: bug, P1

**Comment by zwebie** [comment] 2015-07-16 12:48
Can you please elaborate on the bug you found?
I've encountered the same problem.

**Comment by zwebie** [comment] 2015-07-19 15:31
@emanuelez Can you please elaborate on the bug you found?
I've encountered the same problem.

**Comment by jgonfer** [comment] 2015-07-30 13:51
I found the same problem. When I run the app, it crashes in my Galaxy S6 due to a memory violation. I'm using Realm version 0.81.1. 

If it's helpful, I can send you the crash log.

**Comment by Takhion** [comment] 2015-08-05 15:21
We've also found this issue, can you please share in detail the problem and solution?

**Comment by bmunkholm** [comment] 2015-08-06 09:44
@jgonfer : If you are using 0.81.1 it's not the same issue as that was fixed in 0.80.2. So it would be great if you can create a new github issue with all the details. Thanks!

**Comment by ArbaazDossani** [comment] 2016-03-04 04:56
Hi Bmunkholm,
We pulled the latest repository from git and the app still crashes on Samsung S6 edge due to memory voilation
Is this issue still open or do you have a fix?

**Comment by beeender** [comment] 2016-03-04 06:50
@ArbaazDossani Does the app crash on any other devices? Could you please share the crash log?

**Comment by bmunkholm** [comment] 2016-03-04 06:55
@ArbaazDossani and @beeender  It's better to create a new issue (and reference this) so we can separately track debugging and resolution. It's only a coincidence when we discover comments to already closed issues. Thanks!

**Comment by guptasanchit90dev** [comment] 2016-03-14 10:33
Hi
Just got the same exception on Samsung galaxy S4 with Android 5.0.1, will appreciate any resolution/workaround on this.

**Comment by cmelchior** [comment] 2016-03-14 10:38
Hi @guptasanchit90dev Please create a new issue as that will make it easier for us to help you. The bug discussed above is not the same as yours as we since then have changed the underlying implementation.
