### ISSUE TITLE
We are still seeing the Invalid Group file format exception on 0.80.1

### ISSUE THREAD

**Issue by roms** [realm/realm-java#1074] opened 2015-04-28 20:25 UTC
My understanding (based on searching the issues list) was that this was fixed in in 0.80.1 (https://github.com/realm/realm-java/issues/961)  , but we are still seeing in 0.80.1 when calling Realm.getInstance(...) : 

Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid Group file format.
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:58)
       at io.realm.Realm.<init>(Realm.java:204)
       at io.realm.Realm.createAndValidate(Realm.java:513)
       at io.realm.Realm.create(Realm.java:486)
       at io.realm.Realm.getInstance(Realm.java:404)
       at io.realm.Realm.getInstance(Realm.java:366)

We are calling this in our Android app's onCreate() method and suspect its only happening to users that are upgrading our app from a version that had a different version of the Realm library.

**Comment by cmelchior** [comment] 2015-04-29 09:02
Hi @roms 
We need some more information to be able to dig into this.
- Can you reproduce the issue or is it only showing up on user phone?
- Does it only happen if you upgrade the app from a previous version?

Also, can you share your onCreate method so we get a better idea of what is happening?

**Comment by roms** [comment] 2015-04-30 14:43
We haven't been able to reproduce this internally and are only seeing it in the wild with users. We strongly suspect its only happening to users who upgraded from a previous version.

In the code below, the above exception in this Issue is thrown on the following line:
Realm realm = Realm.getInstance(applicationContext(), realmDBName);

This is the Realm initialization method we call inside our onCreate method:

private void configureRealmDatabase() {
        String realmDBName = (String) getMetaData("ROUTING_AND_TAX_REALM_NAME");
        try {
            // TODO realmDB version checking against version # to be stored in sharedPrefs

            // check if file exists, if not copy from package
            File dbFile = new File(applicationContext().getFilesDir() + realmDBName);
            if (!dbFile.exists()) {
                copyPackagedRealmFile(getAssets().open(realmDBName), realmDBName);
            }

            Realm realm = Realm.getInstance(applicationContext(), realmDBName);
            if (realm == null) {
                // Log error
                throw new RuntimeException("No realm DB found");
            }
        } catch (IOException ioe) {
            throw new RuntimeException(ioe);
        }
    }

**Comment by cmelchior** [comment] 2015-05-05 06:57
Hi @roms 
Sorry for the late reply. There is nothing inherently wrong with with that approach to opening a Realm. Do you monitor which devices and/or versions of Android you are seeing problems? It might help debugging this.

**Comment by roms** [comment] 2015-05-05 16:21
Hi Christian,

We ended up catching that exception and just reloading the original realmDB file that was included in our apk instead of the corrupted one already on the phone.

The exception was happening across a wide variety of phones and OSs, including 5.0, 5.01, 4.1.2, 4.4.2, and 4.4.4 .

**Comment by cmelchior** [comment] 2015-05-11 07:36
Hi @roms 
Ok thanks. We have another issue that looks like it sometimes trigger this. Do you by any chance run Realm in many different background threads?

**Comment by roms** [comment] 2015-05-11 16:02
We do call it in a background thread for search filtering, but I wouldn't call it many threads. There are only two screens in our app where we do this, but its extremely unlikely that they both would be executing concurrently.

**Comment by cmelchior** [comment] 2015-05-13 12:51
Hi @roms 
We might have found a bug that in some cases could trigger this: https://github.com/realm/realm-java/pull/1117

Basically it is related to working with RealmList's outside a write transaction. If that is done it could lead to corrupted files if very unlucky.

Once we merge this fix it is easy to see if this could be the reason as you app will start to fail on runtime when trying to manipulate the Realm data.

**Comment by roms** [comment] 2015-05-13 15:59
@cmelchior , 
Thanks for the update. We currently only use Realm in read only mode, so it will be interesting to see if this does fix our issue.

**Comment by kneth** [comment] 2015-05-19 07:31
@roms #1117 has been merged so you can try the fix using our snapshot release (see the `README.md` for details).

**Comment by cmelchior** [comment] 2015-06-02 07:56
Closing as this is presumably fixed. Please reopen if any new information surfaces.

**Closed by cmelchior** 2015-06-02 07:56 UTC
Labels: Pending
