### ISSUE TITLE
Support for RealmList<String>

### ISSUE THREAD

**Issue by dadino** [realm/realm-java#1652] opened 2015-10-23 13:10 UTC
A typical case using JSON is a list of Strings. Right now Realm can't handle this case and we have to use this horrible hack to make it work:

```java
    public class RealmString extends RealmObject {

 	 public static final String VALUE = "value";
	 private String value;
	 public RealmString() { }

	 public String getValue() {
		return this.value;
	 }
	 public void setValue(String value) {
	 	this.value = value;
	 }
    }
```
And in MyRealmObject:

```java
    private RealmList<RealmString> strings;
```
This prevent a direct mapping from JSON (or at least, I don't know a way to do it).

1. Are you planning to support RealmList<String>? 
2. Are you planning to support lists of privimite (int, long, etc)?
3. Is there a better way to solve this problem with the current library?
4. Is there a way to map a JSON to the above structure (using Gson or Jackson)?

**Comment by cmelchior** [comment] 2015-10-23 13:22
Hi @dadino 
Yes we definitely want to support lists of primitives as well. You can track progress on that here: #575 
In this Gist here you can see how you can write a custom adapter for GSON to get the functionality required until then: https://gist.github.com/cmelchior/1a97377df0c49cd4fca9

I'm closing this as an duplicate of #575

**Closed by cmelchior** 2015-10-23 13:22 UTC
