### ISSUE TITLE
[0.88.0-SNAPSHOT] IllegalStateException: Caller thread behind the worker thread

### ISSUE THREAD

**Issue by njovy** [realm/realm-java#2115] opened 2016-01-19 15:59 UTC
http://crashes.to/s/d9d24a52572
This exception is thrown after I migrated my codebase from synchronous to asynchronous realm calls using observables. The stacktrace doesn't show where it went wrong from my code.
```
messagesSubscription = realm.where(Message.class)
        .equalTo("conversationId", conversationId)
        .findAllSortedAsync("updated")
        .asObservable()
        .filter(RealmResults::isLoaded)
        .subscribe((messages) -> {
          if (adapter != null) {
            adapter.call(messages);
          }
        });
```
The above is the only asynchronous call in that problematic activity. Any ideas why the exception is thrown?

**Comment by cmelchior** [comment] 2016-01-19 18:36
It is happening because our worker thread is somehow ahead of the thread receiving the result. This should not be possible since we strictly control the worker thread, but it looks like you perhaps have caught a corner case. A few questions:

- Is this something you can reproduce? We would be extremely interested in something that can reproduce this.
- Are you doing any writes on the UI thread?
- Also, I assume you are subscribing on the UI thread, but just to be sure?

**Comment by njovy** [comment] 2016-01-20 04:40
* Is this something you can reproduce? We would be extremely interested in something that can reproduce this.
  * Yes I can reproduce this bug on my app but I am not sure if I can provide a sample code 
* Are you doing any writes on the UI thread?
  * The app adds a realm object in a background thread.
* Also, I assume you are subscribing on the UI thread, but just to be sure?
  * Yes. I am subscribing this on the UI thread.

I forgot to mention that there was one more asynchronous query in the activity.
```
     blockedUserSubscription = realm.where(BlockedUser.class)
              .equalTo("id", peerId)
              .findFirstAsync()
              .asObservable()
              .subscribe(blocked -> {
                if (blocked.isValid()) {
                  blockMenuItem.setTitle(R.string.menu_unblock);
                } else {
                  blockMenuItem.setTitle(R.string.menu_block);
                }
              });
```
If I get rid of the above part, the exception isn't thrown in the same condition.

**Comment by cmelchior** [comment] 2016-01-20 09:00
@njovy You can share your app with us privately though help@realm.io if you wish

**Comment by njovy** [comment] 2016-01-20 14:37
@cmelchior I changed back to synchronous queries and it doesn't throw this exception anymore. In order to reproduce the exception, I sent many push notifications to android clients with 10 threads. The client validates a new message then it writes a realm object to persist the new message on a working thread in AsyncTask.THREAD_POOL_EXECUTOR. While it's receiving many messages at the same time, I navigate back and forth over my app and the exception is thrown on where the app reads realm objects asynchronously.

**Comment by luhui** [comment] 2016-01-27 12:48
I have encounter this problem either.

In my project, all writing operation use `realm.executeTransaction`, and most of the reading operation use `findAsync.asObservable`, and subscribe on main thread like @njovy 's code

And all realm instance get from `Real.getDefaultInstance`

Any suggest that writing or fetching in background thread, reading and observing change in main thread?

**Comment by njovy** [comment] 2016-01-27 13:14
@luhui I eventually got rid of every ```findAllAsync().asObservable()```. It's tough to detect this exception in a dev mode but I can reproduce it with concurrent transactions in a working thread while observing changes for realm objects. It seems like there's no way to avoid it at the moment. I won't switch until it's stable as I spent too much time on this.
http://crashes.to/s/43d4b2a7f4c

**Comment by cmelchior** [comment] 2016-01-28 15:34
We have just released 0.87.4 with a potential fix for this. We still haven't been able to reproduce the exact error you are reporting here, but upon investigation found something that appeared to be the root cause. So if you can test with 0.87.4 that would be much appreciated.

**Comment by luhui** [comment] 2016-01-29 03:14
@cmelchior  I have just update and have a test, no exception throw anymore, seems it is being fixed

**Comment by cmelchior** [comment] 2016-01-29 12:24
Thank you for the update @luhui. I'll close this issue then. Feel free to reopen if you see it again.

**Comment by ganfra** [comment] 2016-02-08 09:23
Hello @cmelchior 
I've just got this error with the 0.88.0-SNAPSHOT
Same configuration : Writing on background thread, Rx observing on main thread
The error isn't always occurring, but is reproductible

**Comment by cmelchior** [comment] 2016-02-08 09:26
Hi @ganfra Can you share the code? If you want it private you can send it to help@realm.io.

**Comment by luhui** [comment] 2016-02-16 09:23
@cmelchior Finally reproduce the problem.
[Here](https://github.com/luhui/RealmExample) is the sample project

Just install the app and run, it will crash with `BadVersionException` or `Caller thread behind the worker thread` exception. If run without crash, kill the app manually and retry.

The core operation is in `FirstFragment.java`, update two table's data in background at the same time.
```java
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        realm = Realm.getDefaultInstance();

        //1、update game and event at the same time
        updateGame();
        updateEvent();
    }

//assume updateGame data
    private void updateGame() {
        Log.e("lh", "begin updateGame first");
        new RealmAsyncTransaction().executeTransactionObservable(realm1 -> {
            Log.e("lh", "updating first");
            String updateJson = "{\n" +
                    "  \"id\": \"id1\",\n" +
                    "  \"name\": \"Hello World\",\n" +
                    "  \"games\": [\n" +
                    "    {\n" +
                    "      \"id\": \"id1\",\n" +
                    "      \"name\": \"games1\"\n" +
                    "    },\n" +
                    "    {\n" +
                    "      \"id\": \"id2\",\n" +
                    "      \"name\": \"games2\"\n" +
                    "    },\n" +
                    "    {\n" +
                    "      \"id\": \"id3\",\n" +
                    "      \"name\": \"games3\"\n" +
                    "    }\n" +
                    "  ]\n" +
                    "}";
            realm1.createOrUpdateAllFromJson(Users.class, updateJson);
        });
    }

    private void updateEvent() {
        String id = UUID.randomUUID().toString();
        new RealmAsyncTransaction().executeTransactionObservable(realm1 -> {
            Event games = new Event();
            games.setId(id);
            games.setName("test-name!!");
            realm1.copyToRealmOrUpdate(games);
        }).subscribe(aBoolean -> {
            Log.e("lh", "save " + id + " " + aBoolean + " result ...." + Realm.getDefaultInstance().allObjects(Event.class));
        });
    }
```

And listen data change in onResume method

```java
@Override
    public void onResume() {
        super.onResume();
        textView.setText("");
        //2、listen all data change

        /**
         *high reproducibility
                io.realm.internal.async.BadVersionException: std::exception in io_realm_internal_TableQuery.cpp line 1094
                or java.lang.IllegalStateException: Caller thread behind the worker thread
                will throw
         */
        subscription = realm.where(Games.class).findAllAsync().asObservable().subscribe(games -> {
            for (Games g :
                    games) {
                textView.append("first - game name: " + g.getName());
            }
        });

        //low reproducibility
//        subscription = realm.where(Games.class).findFirstAsync().asObservable().filter(RealmObject::isLoaded).cast(Games.class).subscribe(games -> {
//            textView.setText(games.getName());
//        });
    }
```

**Comment by cmelchior** [comment] 2016-02-16 10:09
Hi @luhui 
Thank you very much. I can reproduce the crash on Genymotion with 5.1.0

**Comment by luhui** [comment] 2016-02-17 03:10
In this case, query in realm.executeTransaction success callback will failed to get the data recently been saved. See #2292

**Comment by luhui** [comment] 2016-02-17 03:28
in success callback,  call `realm.refresh()` can fix this issue...But I'm not sure it is the correct answer

**Closed** 2016-02-24 12:46 UTC
Labels: S:In Progress, T:Bug-Crash
