### ISSUE TITLE
Destruction of mutex in use

### ISSUE THREAD

**Issue by shrikantsonar** [realm/realm-java#6708] opened 2020-01-03 09:21 UTC
I am getting this log when using realm in my app during development.
 
E/REALM: /home/jenkins/workspace/m_realm-core_release_5.10.2-JLYB4463STYEHDZYG5MCNCHSR6P7KGQAINRPSTQDTS37Q72ZT66Q@6/src/realm/util/thread.cpp:185: [realm-core-5.10.2] Destruction of mutex in use
    <backtrace not supported on this platform>!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.
2019-11-27 19:24:09.369 2779-2831/com.fhs A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 2831 (RealmFinalizing), pid 2779.
 
I am using following configurations for Realm.
 
App level Gradle
kapt 'androidx.databinding:databinding-compiler:3.5.1'
kapt "io.realm:realm-annotations:6.0.1"
kapt "io.realm:realm-annotations-processor:6.0.1"
 
Project level Gradle
classpath "io.realm:realm-gradle-plugin:6.0.1"
 
I would like to know what causes this issue to reproduce not everytime, but after heavy usage of app,  & steps with which we can handle this?

**Comment by Zhuinden** [comment] 2020-01-03 12:43
This is fixed in Realm Core 5.23.7

If you ask nicely, maybe @cmelchior will update Realm Core version in the next release, because that's not yet released on Realm-Java side unfortunately

**Comment by tgoyne** [comment] 2020-01-03 16:47
5.23.7 introduces a regression (sorting properties which have negative floats is broken) so we actually need a 5.23.8 release, which has been delayed by the holidays.

**Comment by shrikantsonar** [comment] 2020-01-06 05:23
So we have Realm version 7.0.0-beta out now. Reading some other answers for same issue, I am sure Realm version 7.0 would include 5.23.8 release of Realm-core which would ideally fix this issue (Correct me if I am wrong here). When can we expect this new release.

**Comment by cmelchior** [comment] 2020-01-06 12:40
The part of the code resulting in this error has been completely rewritten in `7.0.0`, but hopefully, we can have a `6.1` release out by the end of this week.

**Comment by Prateek943** [comment] 2020-01-13 14:56
Facing similar  issue. It will be great help if we get  release as soon as possible.  Appreciate all your efforts and great product!

**Comment by shrikantsonar** [comment] 2020-01-14 06:42
@cmelchior @Zhuinden One thing I have observed is, this bug which causes above crash does not get logged to Google Crashlytics. Also the app is not fully closed, it throws user to last screen (activity in my case). How can we log this issue to Google crashlytics & can we close the app altogether once this exception occurs ?

**Comment by cmelchior** [comment] 2021-01-04 15:18
This is assumed to have been fixed with 10.1.1 . If this is still happening, please reopen this issue.

**Closed** 2021-01-04 15:19 UTC
Labels: O-Community, Reproduction-Required, T-Bug-Crash
