### ISSUE TITLE
RealmPrimaryKeyConstraintException when copyToOrUpdateRealm

### ISSUE THREAD

**Issue by mhgk** [realm/realm-java#2324] opened 2016-02-23 17:26 UTC
Hey guys. I get the exception in the bottom when trying to copyToOrUpdate realm.
When using RealmObjects which have a Realmlist. Is it necessary to commit RealmList-objects to the db individually, before adding them to the RealmList?  Or can you create the whole RealmObject including RealmLists and then commiting?  

```
 java.lang.RuntimeException: 
An error occured while executing doInBackground()
     at android.os.AsyncTask$3.done(AsyncTask.java:304)
     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818) Caused by: io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 221
      at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:636)
      at io.realm.internal.Table.checkIntValueIsLegal(Table.java:630)
      at io.realm.internal.UncheckedRow.setLong(UncheckedRow.java:208)
      at io.realm.LikeEntityRealmProxy.setLikedById(LikeEntityRealmProxy.java:88)
      at io.realm.LikeEntityRealmProxy.copy(LikeEntityRealmProxy.java:249)
      at io.realm.LikeEntityRealmProxy.copyOrUpdate(LikeEntityRealmProxy.java:242)
      at io.realm.NewsEntityRealmProxy.update(NewsEntityRealmProxy.java:1210)
      at io.realm.NewsEntityRealmProxy.copyOrUpdate(NewsEntityRealmProxy.java:1042)
     at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:166)
       at io.realm.Realm.copyOrUpdate(Realm.java:1166)
     at io.realm.Realm.copyToRealmOrUpdate(Realm.java:714)
      at dk.miracle.grapevine.realm_db.NewsDAO.createNewsObject(NewsDAO.java:132)
      at dk.miracle.grapevine.realm_db.NewsDAO.access$000(NewsDAO.java:29)
      at dk.miracle.grapevine.realm_db.NewsDAO$1.doInBackground(NewsDAO.java:106)
      at dk.miracle.grapevine.realm_db.NewsDAO$1.doInBackground(NewsDAO.java:98)
      at android.os.AsyncTask$2.call(AsyncTask.java:292)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
     at java.lang.Thread.run(Thread.java:818)
```

**Comment by stk1m1** [comment] 2016-02-24 04:17
@mhgk you can store a `RealmObject` with `RealmList` fields in one commit. The exception is related to **PrimaryKey** though. Could you somehow show us your object to store? Bare object code would suffice for us to help you.

**Comment by mhgk** [comment] 2016-02-24 08:01
Ofc, and thx for the fast reply.

public class NewsEntity extends RealmObject {

    @PrimaryKey
    private int id;
    private int channelId;
    private String title;
    private String body;
    private int authorId;
    private String authorName;
    private String authorPictureUrl;
    private Date created;
    private RealmList<CommentEntity> commentsList;
    private RealmList<LikeEntity> likedByUserIds;
    private Date serviceAnnouncementEnd;
    private Date serviceAnnouncementStart;
    private boolean likedByMe;
    private boolean deleteMediaContent;
    private boolean commentedByMe;
    private MediaContentEntity mediaContentEntity;

    @Index
    private boolean isSynchronized;

----
getters and setters
---

}



public class LikeEntity extends RealmObject {


    private int ownerId;

    private int likedById;

    @Index
    private boolean isSynchronized;

----
getters and setters
---

}


public class CommentEntity extends RealmObject {
    @PrimaryKey
    private int id;
    private int parentId;
    private String body;
    private int authorId;
    private String authorName;
    private String authorPictureUrl;
    private Date created;

    @Index
    private boolean isSynchronized;

----
getters and setters
---

}

**Comment by stk1m1** [comment] 2016-02-24 11:01
@mhgk Thanks for your input. We'll investigate the issue according to the API guide and let you know promptly.

**Comment by mhgk** [comment] 2016-02-24 11:19
Using this version if it matters: 'io.realm:realm-android:0.87.2'

**Comment by stk1m1** [comment] 2016-02-25 14:05
@mhgk Since you're using `AsyncTask` and `LikeEntity` without a **PrimaryKey**, it is mostly likely that the background `Realm` instance does not have `LikeEntity` object with `likedById = 221`, and the `Realm` is therefore not updating an existing `LikeEntity`.

In this case, I'd recommend you 
1) setup a **PrimaryKey** field on `LikeEntity` (`likedById`, likely?), and 
2) create a standalone `LikeEntity` rather than through `Realm.createObject()`. 
    <sup>*</sup> I see this line `dk.miracle.grapevine.realm_db.NewsDAO.createNewsObject(NewsDAO.java:132)` up there.

Hope this resolve your issue.

**Comment by mhgk** [comment] 2016-02-29 09:58
Hi again. sry for late reply, had a prolonged weekend.

So adding a primaryKey is not possible before a weeks-time or so. You think this is causing the error however?

This is how i persist the object.

 localTransAction.beginTransaction();
        NewsEntity newsEntity = createNewsRealm(news);
        RealmList<LikeEntity> likeList = new RealmList<>();
        if (news.getLikedByUserIds() != null && !news.getLikedByUserIds().isEmpty()) {
            for (int item : news.getLikedByUserIds()) {
                likeList.add(new LikeEntity(item));
            }
            newsEntity.setLikedByUserIds(likeList);
        }
        newsEntity = localTransAction.copyToRealmOrUpdate(newsEntity);
        localTransAction.commitTransaction();


private NewsEntity createNewsRealm(News from) {

        NewsEntity to = new NewsEntity();
        if (from.hasChannel()) {
            to.setChannelId(from.getChannel().getChannelId());
        }
        to.setDeleteMediaContent(from.isDeleteMediaContent());
        to.setId(from.getId());
           ------ just copying values from one to another ----
        return to;
    }

**Comment by stk1m1** [comment] 2016-02-29 14:49
@mhgk I've slightly re-formatted your comments for better review. I've also escalated this issue as a bug, and I need your help to resolve it. 

Could you create a sample project regarding the crash you are facing, and send a link to us? I've created a PR just for this to rapid resolution. I will strongly look into it.

**Comment by mhgk** [comment] 2016-02-29 14:58
I've left work but will look into it tomorrow.  What would you need included in the sample?

**Comment by stk1m1** [comment] 2016-03-01 02:35
@mhgk Three entities you posted above, and object persistent code path that causes the exception should suffice. Basically, we need as little amount of code as it is necessary to recreate the crash.

I tried to reproduce your case by copying code-by-code, but was not able to.

**Comment by mhgk** [comment] 2016-03-01 09:42
Hello again, after some contemplating, i find that its not so simple to create a sample project, as we use authentication in order to get data from the backend, and i dont much like to share our keys.

I could share the whole class which persist the data if you like, and all relevant entitites?

**Comment by cmelchior** [comment] 2016-03-01 09:43
Hi @mhgk That would be great.

**Comment by mhgk** [comment] 2016-03-01 10:32
No problem, i hope you can find the error. If it happens again, il will send stacktrace and so on.

**Comment by mhgk** [comment] 2016-03-01 11:01
forgot something. https://github.com/mhgk/realm.sample.git

**Comment by emanuelez** [comment] 2016-03-16 09:48
Thank you. We're currently working on it so we'll let you know soon.

**Comment by stk1m1** [comment] 2016-03-16 12:50
@mhgk According to your sample, we've created an Android app to reproduce the crash, but has not been successful. You can check out our example [here](https://github.com/stk1m1/BuggyApp).

It generates random values to populate database. You can re-insert the same value as many times as you'd want.

Could you please take a look and see if it matches your situation for the problematic encounter? If you could help us to recreate the crash with our sample app, we could further help you. We've added you to the sample app repository that you can commit there as well.

Here's library we've used.
> Realm 0.88.1
> Hugo 1.2.1
> Gson 2.6.2

**Comment by kneth** [comment] 2016-03-18 13:12
I'm closing the issue after direct communications with the user.

**Closed by kneth** 2016-03-18 13:12 UTC
Labels: Reproduction Required, S:Waiting For User, T:Bug
