### ISSUE TITLE
Weird crash only on Samsung A5 Android 6.0.x

### ISSUE THREAD

**Issue by aouledissa** [realm/realm-java#6201] opened 2018-09-26 11:03 UTC
We have a really weird crash upon app launching that only happens on a Samsung A5 with android 6.0.x

the stack trace is the following:
```java
Caused by java.lang.IllegalStateException: Call `Realm.init(Context)` before calling this method.
       at io.realm.Realm.getDefaultInstance(Unknown Source)
       at com.b.g.controllers.UsersController.(Unknown Source)
       at com.b.g.activities.MainActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6272)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5525)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```
We understand that we have to init Realm with a context in order to get this done but it's already there. It only crash on Samsung A5. We have tested it with over 10 devices and it never crashed. 

Please advise! 

#### Version of Realm and tooling
Realm version(s): io.realm:realm-gradle-plugin:3.7.1

Realm sync feature enabled: yes/no

Android Studio version: 2.3

Which Android version and device: Samsung A5 Android 6.0.x (1 and 0)

**Comment by cmelchior** [comment] 2018-09-26 11:11
Is it something you can reproduce?

Also, where are you calling `Realm.init(context)` ?

**Comment by andromedcodes** [comment] 2018-09-26 11:27
@cmelchior Thank you for you fast response.

We are calling `Realm.init(context)` at the application class level as following :
```@Override
  public void onCreate() {
      super.onCreate();
      instance = this;
      Realm.init(this);
      final RealmConfiguration migrationConfig = new RealmConfiguration.Builder()
              .schemaVersion(BuildConfig.REALM_SCHEMA_VERSION)
              .migration(new MigratorController())
              .build();
      Realm.setDefaultConfiguration(migrationConfig);
      Realm.getInstance(migrationConfig);
  }`

**Comment by cmelchior** [comment] 2018-09-26 11:32
Note that in some cases `Application.onCreate` is not the first thing called, e.g. ContentProviders are created before: https://stackoverflow.com/questions/21484285/android-application-oncreate-method-does-it-always-get-called-first

**Comment by cmelchior** [comment] 2018-09-26 11:34
While really sad, we have also seen indications that some devices have bugs in the app startup process (looking at you Samsung), so if this is something you see a lot, it might help to wrap your calls to `getDefaultInstance()` in a retry mechanism that will call `Realm.init()` if it wasn't before.

Calling `Realm.init(context)` multiple times should be safe as subsequent calls does nothing.

**Comment by andromedcodes** [comment] 2018-09-26 11:43
@cmelchior Thank you for this detailed response!

We don't have a content provider used at our app. The only provider we use the a `FileProvider` just to access the device files when we seek their `URI` 

I'll try to use your suggested answer and get back with a feedback. It would be nice from your if you don't close this issue until we get a positive result.

Many thank again :)

**Comment by rorbech** [comment] 2021-03-01 09:59
Closing due to inactivity and as the underlying implementation have changed drastically since then.

**Closed by rorbech** 2021-03-01 09:59 UTC
Labels: O-Community, Pipeline-On-Hold, Reproduction-Required, T-Help
