### ISSUE TITLE
NullPointerException on Realm.java (v 0.81.1)

### ISSUE THREAD

**Issue by elikohen** [realm/realm-java#1266] opened 2015-07-06 10:16 UTC
Hello. 
We're getting a random crash on Realm.java 

Here's the stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.concurrent.atomic.AtomicInteger.decrementAndGet()' on a null object reference
       at io.realm.Realm.close(Realm.java:243)
       at com.ztory.datastore.news.NewsDataStore.doQueryObject(NewsDataStore.java:88)
       at com.ztory.datastore.news.NewsDataStore.doQuery(NewsDataStore.java:68)
       at com.ztory.datastore.news.NewsDataStore.dsOperation(NewsDataStore.java:34)
       at com.ztory.support.datastore.StDataStore.execOperation(StDataStore.java:242)
       at com.ztory.support.datastore.StDataStore.access$000(StDataStore.java:17)
       at com.ztory.support.datastore.StDataStore$3.r(StDataStore.java:158)
       at com.ztory.support.app.beacon.AppBeacon$5.r(AppBeacon.java:407)
       at com.ztory.support.app.beacon.AppBeacon.sendEvent(AppBeacon.java:427)
       at com.ztory.support.app.beacon.AppBeacon.sendEvent(AppBeacon.java:333)
       at com.ztory.support.datastore.StDataStore.eventSend(StDataStore.java:51)
       at com.ztory.support.datastore.StDataStore.eventSend(StDataStore.java:26)
       at com.ztory.datastore.activities.ActivityPojo.getNewsData(ActivityPojo.java:479)
       at com.ztory.datastore.activities.ActivityPojo.access$1100(ActivityPojo.java:39)
       at com.ztory.datastore.activities.ActivityPojo$8.r(ActivityPojo.java:369)
       at com.ztory.support.app.async.AppAsyncStack$1.run(AppAsyncStack.java:78)
       at java.lang.Thread.run(Thread.java:818)
```

And here's the call we're performing:
```
        Realm realm = Realm.getDefaultInstance();
        NewsRealm result = realm.where(NewsRealm.class).equalTo("id", objectId).findFirst();
        if (result != null) {
            //NewsPojo is a simple data object where we copy all the values from the realm object
            objects.add(new NewsPojo(result)); 
        }
        realm.close();
```
The crash is happening on `realm.close();`

**Comment by beeender** [comment] 2015-07-06 10:35
#1245 has been merged to fix a similar/same issue.
Maybe you can try to verify it with our latest SNAPSHOT or build the java lib from our master branch?

Thanks!

**Comment by elikohen** [comment] 2015-07-06 11:06
As it happened randomly and lately I could not reproduce it even with 0.81.1 I cannot assure you that the current snapshot code fixed it. But at least never happened in the 0.82.0-SNAPSHOT

**Comment by kneth** [comment] 2015-07-06 11:39
I'll close the issue as you cannot reproduce it. If you see the issue again, don't hesitate to open a new issue.

**Closed by kneth** 2015-07-06 11:39 UTC
Labels: Pending
