### ISSUE TITLE
Is it possible to export .realm file to .csv file?

### ISSUE THREAD

**Issue by abdulgaffar291** [realm/realm-java#3063] opened 2016-06-24 05:25 UTC
> How can i achieve exporting a realm file into csv format.

> Before the user closes the app the entire database file should be exported.

#### Version of Realm and tooling
Realm version(s): 1.0.1
Android Studio version: 2.1.2
Which Android version and device: 4.4.2

**Comment by zaki50** [comment] 2016-06-24 06:04
Currently, we don't have a feature to export database.
We understand that there are huge demand on this and it is tracked by #2880

Realm Objective-C and Realm Swift have Realm Cocoa Converter.
 https://realm.io/news/announcing-realm-cocoa-converter/
We'd like to add something like that.

I'll close this as a duplicate of #2880. Sorry for inconvenience.

**Closed by zaki50** 2016-06-24 06:04 UTC
