### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException rowIndex > available rows

### ISSUE THREAD

**Issue by donnguyen** [realm/realm-java#3337] opened 2016-08-23 09:23 UTC
#### Expected Results

> No crash
#### Actual Results

> ``` java
> Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 4 > 4
>        at io.realm.internal.TableView.nativeRemoveRow(TableView.java)
>        at io.realm.internal.TableView.remove(TableView.java:405)
>        at io.realm.RealmResults.deleteFromRealm(RealmResults.java:246)
>        at removed.SavedMediaRecyclerViewAdapter$8.onClick(SavedMediaRecyclerViewAdapter.java:288)
>        at cn.pedant.SweetAlert.SweetAlertDialog.onClick(SweetAlertDialog.java:372)
>        at android.view.View.performClick(View.java:4240)
>        at android.view.View$PerformClick.run(View.java:17721)
>        at android.os.Handler.handleCallback(Handler.java:730)
>        at android.os.Handler.dispatchMessage(Handler.java:92)
>        at android.os.Looper.loop(Looper.java:137)
>        at android.app.ActivityThread.main(ActivityThread.java:5199)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:525)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>        at dalvik.system.NativeStart.main(NativeStart.java)
> ```
#### Steps & Code to Reproduce

> I am using `RealmBasedRecyclerViewAdapter` (https://github.com/thorbenprimke/realm-recyclerview - but I think this kind of issue should in Realm not the lib so I am posting it here) for my RecyclerView, I just override `onItemSwipedDismiss` to show confirm dialog before actual deleting object from Realm. So can you please take a look. Thanks
#### Code Sample

``` java

@Override
    public void onItemSwipedDismiss(final int position) {
        new SweetAlertDialog(mContext, SweetAlertDialog.WARNING_TYPE)
                .setTitleText(mContext.getString(R.string.delete_confim_prompt))
                .setContentText(mContext.getString(R.string.wont_recover))
                .setConfirmText(mContext.getString(R.string.yes_delete))
                .setCancelText(mContext.getString(R.string.no_cancel))
                .showCancelButton(true)
                .setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                    @Override
                    public void onClick(SweetAlertDialog sDialog) {
                        Realm realm = Realm.getDefaultInstance();
                        realm.beginTransaction();
                        realmResults.deleteFromRealm(position);
                        realm.commitTransaction();
                        notifyItemRemoved(position);
                        realm.close();
                        sDialog.dismissWithAnimation();
                    }
                })
                .setCancelClickListener(new SweetAlertDialog.OnSweetClickListener() {
                    @Override
                    public void onClick(SweetAlertDialog sDialog) {
                        sDialog.dismissWithAnimation();
                        notifyItemChanged(position);
                    }
                })
                .show();
    }

```
#### Version of Realm and tooling

Realm version(s): 1.1.0, 1.1.1, 1.2.0

Android Studio version: 2.2 beta

Which Android version and device: C6530N (4.3), GT-I9300 (4.3), JAX QS (4.4.2)...

**Comment by Zhuinden** [comment] 2016-08-23 10:34
realmResults.deleteFromRealm(position);
                        realm.commitTransaction();
                        notifyItemRemoved(position);
                        realm.close();

The `RealmResults` is updated only on the next looper event in order to enable proper iteration behavior.

When you're calling

                        notifyItemRemoved(position);

The item is not removed yet from the RealmResults. Only when `RealmChangeListener` runs.

Note the [breaking changes in 0.89.0](https://github.com/realm/realm-java/blob/master/CHANGELOG.md):

    RealmObject and RealmResults are always updated on the next event loop.

**Comment by Zhuinden** [comment] 2016-08-23 12:49
(if you want to be hardcore and redefine the inner workings, what you can do is create a package-internal method

     package io.realm;

     public class RealmResultSync {
          public static <T extends RealmModel> void syncResults(RealmResults<T> results) {
               results.syncIfNeeded(); 
               results.notifyChangeListeners(false);
          }
     }

And then do

                    realm.commitTransaction();
                    RealmResultSync.syncResults(realmResults);
                    notifyItemRemoved(position);
                    realm.close();

)

**Comment by donnguyen** [comment] 2016-08-23 13:24
@Zhuinden thanks for your solution. But I have a question if you don't mind. Are there any reasons for that issue just happened on some devices? If you're right about the root of the issue, I guess the app'd crashed when I delete the second item, am I right?

**Comment by Zhuinden** [comment] 2016-08-23 13:29
Hmm... maybe I was slightly off though because it's kind of as if the RealmResults you are modifying wasn't the same as the one shown in the adapter.

That is odd. I think I might have been wrong at my initial assessment of what the error is.

Did you enable `automaticUpdate` on your adapter?

**Comment by donnguyen** [comment] 2016-08-23 13:41
Yes I did, 'automaticUpdate' is in by default?

**Comment by Zhuinden** [comment] 2016-08-23 13:49
Hmm.. This is an odd scenario. I don't know why it breaks.

I can't help but feel like it's related to writing on the UI thread though. You should use your global UI Realm instance with `realm.executeTransactionAsync()` for the delete operation, but instead of by position, it should be done by querying the RealmObject in the transaction too by its ID.

**Comment by donnguyen** [comment] 2016-08-23 14:04
@Zhuinden but on this https://github.com/realm/realm-java/issues/2842, it seems 'deleteFromRealm' does the work?

**Comment by Zhuinden** [comment] 2016-08-23 14:29
`RealmResults` updates delayed. `RealmList` updates immediate.

**Comment by Zhuinden** [comment] 2016-08-25 09:59
@kneth  I'm actually not sure why this one is happening. >.>

**Comment by kneth** [comment] 2016-08-29 10:56
@donnguyen Can you elaborate a bit? You mention that it only happens on some devices? So it works on other devices? Is the a pattern (Android version, vendor)?

**Comment by donnguyen** [comment] 2016-08-31 04:30
@kneth yes, it only happens on some devices. Below is the list of some devices that the issue happened on:
- Nexus 9 (7.0)
- Samsung SM-G360T1 (5.1.1)
- Samsung SM-G355M (4.4.2)
- Nexus 7 (6.0.1)
- Samsung GT-N7100 (4.4.2)
- Lenovo A6000 (4.4.4)
etc

**Comment by donnguyen** [comment] 2016-08-31 04:34
I used Zhuinden's suggestion above `RealmResultSync` also, but no luck 😞

**Comment by beeender** [comment] 2016-08-31 04:35
It looks like the issue we fixed in https://github.com/realm/realm-java/pull/2990 . But if you confirmed that happens to `1.1.1` and `1.2.0` as well, then probably there is a corner case we missed :(

**Comment by donnguyen** [comment] 2016-08-31 04:38
@beeender it still happens on `1.1.1` and `1.2.0` :|

**Comment by beeender** [comment] 2016-08-31 04:42
Do you ever delete object from other thread?

**Comment by donnguyen** [comment] 2016-08-31 04:50
@beeender On my app, users can delete objects in only one activity so I don't think so. 
But on another activity, I re-launch the app this way
```java
Intent launchIntent = getPackageManager().getLaunchIntentForPackage(getPackageName());
                launchIntent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                startActivity(launchIntent);
                finish();
```
Do you think this can be related to thread issue?

**Comment by beeender** [comment] 2016-09-01 06:04
@donnguyen Does that mean the only place could remove this object is in `onItemSwipedDismiss` you mentioned? Is that possible there are duplicated `SweetAlertDialog` ? Also, do you call `Realm.delete(class)` or `Realm.deleteAll()` anywhere?

**Comment by donnguyen** [comment] 2016-09-02 02:23
@beeender 
1. Yes, that is the only place.
2. I thought about that too but it seems that case can't happen :|
3. No, I don't.

The thing is I can't reproduce the issue on my side also :(

**Comment by diegomontoya** [comment] 2016-11-17 10:11
@donnguyen It not inconceivable to imagine a user clicking really fast cause 2 identical OnClickListener() callbacks with same var position value. If that's the case, the second callback will crash just like your log.

**Comment by diegomontoya** [comment] 2016-11-17 10:15
To add to the above. We have observed that android touch event queue is missed up when it comes to executing callbacks (onclick(), ontouch(), etc) even when the context/parent (activity/fragment) has been destroyed/finished. Never assume the actual timing on the execution of the OnClick/OnUi() callbacks.

**Comment by beeender** [comment] 2017-03-27 13:57
Actually combining new fine grained notification recyclerviewadpater, and plus #4368 should fix this. Please try with realm-android-adapters `v2.0.0+` and realm-java `3.1.0` or `3.0.2` (which are not released right now, but the snapshot includes the fix.)

**Closed by beeender** 2017-03-27 13:57 UTC
Labels: Reproduction Required, S:P2 Backlog, T:Bug-Crash
