### ISSUE TITLE
 java.lang.IllegalStateException:  Object is no longer valid to operate on. was it has been deleted by another thread?

### ISSUE THREAD

**Issue by shaunty21** [realm/realm-java#6180] opened 2018-09-22 10:03 UTC
Realm object delete on RecyclerAdapter Android?

java.lang.IllegalStateException: Object is no longer valid to operate on. was it has been deleted by another thread?

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

   DatabaseManager.getInstance().deleteSymptomDatebyId(symptomsDbModels.get(position).getDatevalue(), symptomsDbModels.get(position).getId());
                symptomsDbModels.remove(position);
                notifyItemRemoved(position);
                notifyItemRangeChanged(position, symptomsDbModels.size());
                notifyDataSetChanged();
             

```java





#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment] 2018-09-22 22:37
```
symptomsDbModels.remove(position);
notifyItemRemoved(position);
notifyItemRangeChanged(position, symptomsDbModels.size());
notifyDataSetChanged();
```

out of the box, **all** of this is unnecessarily called if you are using [RealmRecyclerViewAdapter](https://github.com/realm/realm-android-adapters)

**Comment by cmelchior** [comment] 2018-09-24 10:59
Duplicate of #6182

**Closed by cmelchior** 2018-09-24 10:59 UTC
Labels: O:User
