### ISSUE TITLE
Instant App with Android 10 has thrown "Permission denied in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101"

### ISSUE THREAD

**Issue by chungngailun** [realm/realm-java#6670] opened 2019-11-26 04:23 UTC
#### Goal
Run Instant App successfully in Android 10 with realm

#### Actual Results
Exception is thrown when launching Instant App with Android 10. The error message is "E/REALM_JNI: Exception has been thrown: Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101"

Precisely, it happens only on Android 10 devices when running Instant App but other Android OS are working fine. However, it works fine on Android 10 with FULL version app.

By the way, we're using dynamic feature modules in our app and submitting our app using Android App Bundle.

#### Steps & Code to Reproduce
1. Go to Google Play
2. Launch our instant app with "Try now" button
3. The mentioned error will be thrown

#### Version of Realm and tooling

Realm version(s): 5.9.1

Realm Sync feature enabled: No

Android Studio version: 3.5.2

Android Build Tools version: 29.0.2

Gradle version: 3.5.1

Which Android version and device(s): Android 10, Tested Devices include One Plus 7, Pixel 2, Pixel 3

**Comment by cmelchior** [comment] 2019-11-26 19:59
That error isn't related to Instant App or App Bundles. There should be some more information after the error message specifying a reason for the permission error

**Comment by chungngailun** [comment] 2019-11-27 04:34
@cmelchior Here is the stack after the error message.
`
io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:9)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:2)
`

Although this error is not caused by Instant App or App Bundles directly, it somehow triggered the error. I have no idea what the main causes is, because it work totally fine on Android 9 or lower. It also works perfectly on full installed app even running on Android 10.

For more information, we init realm instance like this: 

`private fun initRealm(): Realm {

    Realm.init(this)
    val config = RealmConfiguration.Builder()
            .schemaVersion(0)
            .name(realmDataStore)
            .deleteRealmIfMigrationNeeded()
            .build()
    Realm.setDefaultConfiguration(config)
    return Realm.getDefaultInstance()
}`

It'll be called in application's onCreate().

**Comment by wooyukit** [comment] 2019-12-06 10:00
@cmelchior Any suggestions for this error?

**Comment by cmelchior** [comment] 2020-08-14 13:22
We believe this class of errors was fixed in 5.15.0 and above: https://github.com/realm/realm-java/blob/master/CHANGELOG.md#fixed-7

Closing as outdated. If this is still an issue, feel free to reopen.

**Closed by cmelchior** 2020-08-14 13:22 UTC
Labels: O-Community, Pipeline-Waiting-for-User, Reproduction-Required

**Comment by andriy-goryachok** [comment] 2020-09-14 10:02
@cmelchior 

#### Goal
Instant app with realm should work properly on all versions of Android.

#### Actual Results
Instant app with realm crashes on Android 10

Stack trace:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: \<appname\>, PID: 18743
    io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
        at io.realm.BaseRealm.<init>(BaseRealm.java:137)
        at io.realm.BaseRealm.<init>(BaseRealm.java:104)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.createInstance(RealmCache.java:507)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:473)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:414)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)

#### Related issues:

- https://github.com/realm/realm-core/issues/3204
- https://github.com/realm/realm-java/issues/6670

#### Steps & Code to Reproduce

// Realm initialising

Realm.init(context)
val config = RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .build()
Realm.setDefaultConfiguration(config)

// Here application crashes

this.mRealm = Realm.getDefaultInstance();

#### Version of Realm and tooling

Realm version(s): 6.0.1, 7.0.5

Realm Sync feature enabled: Yes/No

Android Studio version: 4.0.1

Gradle version: 6.6.1

Which Android version and device(s): Pixel 3a API 30 (emulator), Samsung A50 API 29

**Comment by cmelchior** [comment] 2020-09-14 12:39
@andriy-goryachok This sounds like something you can reproduce? Is that correct? 

Are you 100% sure you are using the default configuration? E.g. what is the output of `RealmConfiguration.getPath()`? Because my initial guess is that you might be hitting the new Scope Storage restrictions in Android 11: I suspect you are hitting the new Scoped Storage changes. At least those are automatically applied on API 30, not 100% sure about API 29. See https://developer.android.com/about/versions/11/privacy/storage

**Comment by andriy-goryachok** [comment] 2020-09-14 16:30
@cmelchior Here are realm configuration paths from different devices:
- API 30 Pixel 3a: (emulator) /data/user/0/<appname>/files/default.realm (crash)
- API 29 Pixel 3a: (emulator) /data/data/<appname>/files/default.realm (crash)
- API 28 Xiaomi Mi A1: /data/data/<appname>/files/default.realm (without crash)

**Comment by sarlia197** [comment] 2020-11-04 10:45
Is there any solution for this error? 
We are also facing this error in a new Android TV 10 device. For us the error is systematic. We were using Realm in older devices (Android TV N) without problem.  

First we had an old Realm version but we have tried also with 5.15.0 and 7.0.8 and the error is still present.
io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 

the configuration path is   /data/data/tvapp/files/library.epg.realm

The error raised when we try to instantiate the database. 

  private static final String REALM_FILE_NAME = "library.epg.realm";
 ...
   private static RealmConfiguration.Builder getBuilder() {
        return new RealmConfiguration.Builder()  
                .name(REALM_FILE_NAME)                 
                .modules(new EventsModule(),          
                        new ChannelsModule(),
                        new FavouriteListModule(),
                        new ChannelIdModule(),
                        new ChannelLockedModule(),
                        new SearchsModule())
                .schemaVersion(BuildConfig.VERSION_CODE)
                .deleteRealmIfMigrationNeeded();

  }

...

 realmConfig = getBuilder().build();
 realm = Realm.getInstance(realmConfig);  <<< At this point

We have tried each solution proposed here https://realm.io/docs/java/latest/#huawei-permission-denied and also perform a factory reset but the error is still present each time we try to boot our app. Any suggestions? Is this issue going to be reopen?

**Comment by SubhasmithThapa77** [comment] 2021-01-04 13:32
Hi i am still facing the same error on API 29. please suggest something.

**Comment by PriyaSindkar** [comment] 2022-03-07 06:35
I am facing this issue too. I wonder if there is a workaround somewhere for this issue as this bug is very old..!? And yet we are unable to find a workaround for it.

**Comment by PriyaSindkar** [comment] 2022-03-07 10:56
Ok. Thanks @clementetb . Is there a way I can use some other destination to save the realm file to make this working? Or maybe init realm in the activity I need it in when instant app is being used?

**Comment by clementetb** [comment] 2022-03-07 11:04
@PriyaSindkar I am afraid there is no workaround to get Realm to work on InstantApps.
