### ISSUE TITLE
mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp

### ISSUE THREAD

**Issue by thorbenprimke** [realm/realm-java#1123] opened 2015-05-14 23:50 UTC
It's from a Crashlytics crash report. I have only seen this crash from this particular device.

Device: RIM Z10
Android OS: 4.3
Realm: 0.79
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.superco.app/me.superco.app.SuperAppActivity}: java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 100
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5116)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 100
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:58)
       at io.realm.Realm.<init>(Realm.java:199)
       at io.realm.Realm.createAndValidate(Realm.java:516)
       at io.realm.Realm.create(Realm.java:480)
       at io.realm.Realm.getInstance(Realm.java:397)
       at io.realm.Realm.getInstance(Realm.java:359)
       at me.superco.data.RealmInstanceHelper.getInstance(RealmInstanceHelper.java:13)
       at me.superco.data.RealmUIQueryHelper.maybeInitRealmInstance(RealmUIQueryHelper.java:63)
       at me.superco.data.RealmUIQueryHelper.onStart(RealmUIQueryHelper.java:40)
       at me.superco.app.SuperAppActivity.onStart(SuperAppActivity.java:122)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
       at android.app.Activity.performStart(Activity.java:5219)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5116)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by zaki50** [comment] 2015-05-15 09:00
same issue as #619 and https://groups.google.com/forum/#!msg/realm-java/ANYti8pWNX4/7nTAJ260ZG4J

**Comment by kneth** [comment] 2015-05-18 06:48
As @zaki50 says, this is a duplicate of already reported issue. The real issue is that QNX does not implement `mermaid()` which Realm Core is using.

**Closed by kneth** 2015-05-18 06:48 UTC
