### ISSUE TITLE
Unable to use a realm database file created with realm 0.80.0 with 0.80.1

### ISSUE THREAD

**Issue by shanus** [realm/realm-java#1059] opened 2015-04-21 14:00 UTC
I have a realm database file created using realm 0.80.0 that works fine under that version.  After changing gradle to pull in 0.80.1 I get an exception thrown that a migration is needed.  Using the following I create a migration:

		try {
			realm = Realm.getInstance(context);
		} catch (RealmMigrationNeededException ex) {
			Log.i(TAG, "migration needed");
			Realm.migrateRealmAtPath(new File(context.getFilesDir(), "default.realm").getAbsolutePath(), new Migration());
			Log.i(TAG, "migration complete");
		}

the next error occurred was that I need a primary key which was already defined in the models but I made the migration set the primary key using the following on all of the database tables

			Table personTable = realm.getTable(Person.class);
			personTable.setPrimaryKey("id");

where the id attribute for the Person class is a long;

After the migration has completed and I attempt to open the realm I get  an error

    Expected columnType 0, but got 2.
    jni: ThrowingException 3, ColumnType invalid., .
    Exception has been throw: Illegal Argument: ColumnType invalid.

It would be helpful if the column type error would actually state what table the error was in to help with debugging. However, the real problem is that I cannot use the realm file.  All of the tables "id" field are defined as longs so I am unable to determine why the ColumnType.STRING (2) factors in anywhere.

**Comment by cmelchior** [comment] 2015-04-21 17:35
Hi @shanus 

Can you post your Person.java class as well as the stacktrace around the last error message? That will make reproducing this a lot easier.

**Comment by shanus** [comment] 2015-04-21 17:40
Unfortunately not, There is not actually a person class as that was done for obfuscating.  However, we have over 13 classes that all exhibit the same behavior.  The gist of them is as such.  They are all pretty straight forward.

		import java.util.Date;

		import io.realm.RealmObject;
		import io.realm.annotations.PrimaryKey;

		public class Person  extends RealmObject {
			@PrimaryKey
			private long id;
			private String name;
			private Date createdAt;
			private Date updatedAt;

			public long getId() {
				return id;
			}

			public void setId(long id) {
				this.id = id;
			}

			public String getName() {
				return name;
			}

			public void setName(String name) {
				this.name = name;
			}

			public Date getCreatedAt() {
				return createdAt;
			}

			public void setCreatedAt(Date createdAt) {
				this.createdAt = createdAt;
			}

			public Date getUpdatedAt() {
				return updatedAt;
			}

			public void setUpdatedAt(Date updatedAt) {
				this.updatedAt = updatedAt;
			}
		}

**Comment by shanus** [comment] 2015-04-21 17:56
Here is a stack trace.  

		04-21 13:50:28.534  19040-19040/example.master I/class example.helpers.ContentDataSource﹕ migration needed
		04-21 13:50:28.554  19040-19040/example.master I/class example.helpers.Migration﹕ migrated to version 1
		04-21 13:50:28.581  19040-19040/example.master D/REALM﹕ Expected columnType 0, but got 2.
		04-21 13:50:28.581  19040-19040/example.master D/REALM﹕ jni: ThrowingException 3, ColumnType invalid., .
		04-21 13:50:28.581  19040-19040/example.master D/REALM﹕ Exception has been throw: Illegal Argument: ColumnType invalid.
		04-21 13:50:28.582  19040-19040/example.master D/AndroidRuntime﹕ Shutting down VM
		04-21 13:50:28.582  19040-19040/example.master W/System.err﹕ java.lang.RuntimeException: Unable to start activity ComponentInfo{example.master/example.master.BootstrapActivity}: io.realm.exceptions.RealmMigrationNeededException
		04-21 13:50:28.582  19040-19040/example.master W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
		04-21 13:50:28.582  19040-19040/example.master W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
		04-21 13:50:28.582  19040-19040/example.master W/System.err﹕ at android.app.ActivityThread.access$800(ActivityThread.java:151)
		04-21 13:50:28.582  19040-19040/example.master W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
		04-21 13:50:28.582  19040-19040/example.master W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5254)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ Caused by: io.realm.exceptions.RealmMigrationNeededException
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at io.realm.Realm.initializeRealm(Realm.java:631)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at io.realm.Realm.createAndValidate(Realm.java:531)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at io.realm.Realm.create(Realm.java:486)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at io.realm.Realm.getInstance(Realm.java:404)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at io.realm.Realm.getInstance(Realm.java:366)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at io.realm.Realm.getInstance(Realm.java:347)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at example.helpers.ContentDataSource.<init>(ContentDataSource.java:48)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at example.master.BootstrapActivity.onCreate(BootstrapActivity.java:24)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5990)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ ... 10 more
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ Caused by: java.lang.reflect.InvocationTargetException
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ at io.realm.Realm.initializeRealm(Realm.java:627)
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ ... 20 more
		04-21 13:50:28.583  19040-19040/example.master W/System.err﹕ Caused by: java.lang.IllegalArgumentException: Illegal Argument: ColumnType invalid.
		04-21 13:50:28.584  19040-19040/example.master W/System.err﹕ at io.realm.internal.Row.nativeGetLong(Native Method)
		04-21 13:50:28.584  19040-19040/example.master W/System.err﹕ at io.realm.internal.Row.getLong(Row.java:93)
		04-21 13:50:28.584  19040-19040/example.master W/System.err﹕ at io.realm.internal.Table.getPrimaryKey(Table.java:680)
		04-21 13:50:28.584  19040-19040/example.master W/System.err﹕ at io.realm.ContentAreaRealmProxy.validateTable(ContentAreaRealmProxy.java:229)
		04-21 13:50:28.584  19040-19040/example.master W/System.err﹕ ... 23 more
		    --------- beginning of crash
		04-21 13:50:28.590  19040-19040/example.master E/AndroidRuntime﹕ FATAL EXCEPTION: main
		    Process: example.master, PID: 19040
		    java.lang.RuntimeException: Unable to start activity ComponentInfo{example.master/example.master.BootstrapActivity}: io.realm.exceptions.RealmMigrationNeededException
		            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
		            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
		            at android.app.ActivityThread.access$800(ActivityThread.java:151)
		            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
		            at android.os.Handler.dispatchMessage(Handler.java:102)
		            at android.os.Looper.loop(Looper.java:135)
		            at android.app.ActivityThread.main(ActivityThread.java:5254)
		            at java.lang.reflect.Method.invoke(Native Method)
		            at java.lang.reflect.Method.invoke(Method.java:372)
		            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
		            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
		     Caused by: io.realm.exceptions.RealmMigrationNeededException
		            at io.realm.Realm.initializeRealm(Realm.java:631)
		            at io.realm.Realm.createAndValidate(Realm.java:531)
		            at io.realm.Realm.create(Realm.java:486)
		            at io.realm.Realm.getInstance(Realm.java:404)
		            at io.realm.Realm.getInstance(Realm.java:366)
		            at io.realm.Realm.getInstance(Realm.java:347)
		            at example.helpers.ContentDataSource.<init>(ContentDataSource.java:48)
		            at example.master.BootstrapActivity.onCreate(BootstrapActivity.java:24)
		            at android.app.Activity.performCreate(Activity.java:5990)
		            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
		            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
		            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
		            at android.app.ActivityThread.access$800(ActivityThread.java:151)
		            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
		            at android.os.Handler.dispatchMessage(Handler.java:102)
		            at android.os.Looper.loop(Looper.java:135)
		            at android.app.ActivityThread.main(ActivityThread.java:5254)
		            at java.lang.reflect.Method.invoke(Native Method)
		            at java.lang.reflect.Method.invoke(Method.java:372)
		            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
		            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
		     Caused by: java.lang.reflect.InvocationTargetException
		            at java.lang.reflect.Method.invoke(Native Method)
		            at java.lang.reflect.Method.invoke(Method.java:372)
		            at io.realm.Realm.initializeRealm(Realm.java:627)
		            at io.realm.Realm.createAndValidate(Realm.java:531)
		            at io.realm.Realm.create(Realm.java:486)
		            at io.realm.Realm.getInstance(Realm.java:404)
		            at io.realm.Realm.getInstance(Realm.java:366)
		            at io.realm.Realm.getInstance(Realm.java:347)
		            at example.helpers.ContentDataSource.<init>(ContentDataSource.java:48)
		            at example.master.BootstrapActivity.onCreate(BootstrapActivity.java:24)
		            at android.app.Activity.performCreate(Activity.java:5990)
		            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
		            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
		            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
		            at android.app.ActivityThread.access$800(ActivityThread.java:151)
		            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
		            at android.os.Handler.dispatchMessage(Handler.java:102)
		            at android.os.Looper.loop(Looper.java:135)
		            at android.app.ActivityThread.main(ActivityThread.java:5254)
		            at java.lang.reflect.Method.invoke(Native Method)
		            at java.lang.reflect.Method.invoke(Method.java:372)
		            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
		            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
		     Caused by: java.lang.IllegalArgumentException: Illegal Argument: ColumnType invalid.
		            at io.realm.internal.Row.nativeGetLong(Native Method)
		            at io.realm.internal.Row.getLong(Row.java:93)
		            at io.realm.internal.Table.getPrimaryKey(Table.java:680)
		            at io.realm.ContentAreaRealmProxy.validateTable(ContentAreaRealmProxy.java:229)
		            at java.lang.reflect.Method.invoke(Native Method)
		            at java.lang.reflect.Method.invoke(Method.java:372)
		            at io.realm.Realm.initializeRealm(Realm.java:627)
		            at io.realm.Realm.createAndValidate(Realm.java:531)
		            at io.realm.Realm.create(Realm.java:486)
		            at io.realm.Realm.getInstance(Realm.java:404)
		            at io.realm.Realm.getInstance(Realm.java:366)
		            at io.realm.Realm.getInstance(Realm.java:347)
		            at example.helpers.ContentDataSource.<init>(ContentDataSource.java:48)
		            at example.master.BootstrapActivity.onCreate(BootstrapActivity.java:24)
		            at android.app.Activity.performCreate(Activity.java:5990)
		            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
		            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
		            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
		            at android.app.ActivityThread.access$800(ActivityThread.java:151)
		            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
		            at android.os.Handler.dispatchMessage(Handler.java:102)
		            at android.os.Looper.loop(Looper.java:135)
		            at android.app.ActivityThread.main(ActivityThread.java:5254)
		            at java.lang.reflect.Method.invoke(Native Method)
		            at java.lang.reflect.Method.invoke(Method.java:372)
		            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
		            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by cmelchior** [comment] 2015-04-22 09:02
Hi @shanus 
That looks really odd. Your code crashes when trying to validate the model class ContentArea, but it crashes when trying to lookup info in our Primary key metadata table. Are you able to send a copy of a Realm database that has this crash, as that would be really helpful? If you want to keep it private you can send it to help@realm.io

**Comment by cmelchior** [comment] 2015-04-23 11:58
Hi @shanus 

Thank you for the database. I have looked at it and something is not right.
Primary keys info is saved internally in a table called "pk", which has a String (class) and Integer (fieldIndex), but in your case this table has (String, String). So the error actually makes sense, we expect a Integer field but a String field is found.

How the database has ended up in this stage is very puzzling though. All classes are saved in the database using a "class_" prefix so there shouldn't be any name classes. That said, the migration API currently gives access to manipulate these tables in the migration code so is there chance you have been running other migration code that could effect this?

**Comment by shanus** [comment] 2015-04-23 12:45
No, there is not a chance because that database is just created by default, it is migration level 0 and no migrations have been run on it.

**Comment by cmelchior** [comment] 2015-04-23 13:41
Do you also experience this problem when starting from a fresh install?

**Comment by shanus** [comment] 2015-04-23 14:46
I am not sure I understand the question.  We have the problem when accessing that database.  That database is already resident on the device because it has been copied into the location from the application bundle.  We had tried to bootstrap the data into a fresh database on the initial launch by reading in json files but that is not practical because it could take up to 2 minutes to process.

Even if we were able to create a new database that works in 0.80.1 and use it then we still have the issue with preexisting realms in place from previous installs.

**Comment by cmelchior** [comment] 2015-04-23 14:51
When you say you bootstrapped the data into the database, how exactly did you do that? Because as I wrote above, the database isn't in a valid state as the primary key table is wrong, which could indicate that something has gone wrong when you added the bootstrapped data to the Realm.

**Comment by shanus** [comment] 2015-04-23 15:01
We created a desktop application using the swift version of realm to read in the json and populate the database.  Do you think the realm databases created by using different API's are structurally different?  If so that will be a large problem for us as we can't have the user wait 2 minutes for the database to populate on android.  Is there another way to create the database and populate it?

**Comment by cmelchior** [comment] 2015-04-23 15:53
That is probably the most likely source yes. Realm files should be compatible between platforms, so what you are doing should work, but I will double check with our Cocoa team to see if we have any issues in this area.

A Android only alternative could be to create a test android app only created to populate the database, then pull it using ADB (http://stackoverflow.com/questions/28478987/how-to-view-my-realm-file-in-the-realm-browser/28486297#28486297) and use that as you bootstrap.

**Comment by shanus** [comment] 2015-04-23 19:20
We thought of the android only solution before but it has a serious drawback in that our automated build system would not be able to create the database that easily since it would have to build that app, run an emulator, then pull data off the emulator.  With the android version taking up to 2 minutes and the desktop version creating the database in about 20 seconds it just did not seem the route to go.  Thanks for the suggestion though.

**Comment by creativepsyco** [comment] 2015-04-24 17:53
Maybe this helps: https://gist.github.com/creativepsyco/c45789e59a943fc5bf78, I use a `BaseMigration` class to keep track of the addition/deletion of columns, also you cannot use any queries until the migration is complete, because the column indices need to be rebuilt and the models would fail validation.

**Comment by zsavely** [comment] 2015-04-28 19:25
Hi @cmelchior
I probably have the same issue. I get the following Exception after the following steps: 
1.  Upgrade Realm from `0.80.0` to `0.80.1`.
2.  Add another standalone Realm class that contains a `String` field with `@Index` property.
3.  Migrate it. (The migration goes allright)
3.  Try to populate it. Unfortunately, it throws this Exception on this step.

PS. If I do not use the `@Index` property, I get no Exception and this Class is filled smoothly.
```java
 D/REALM(4446): Expected columnType 2, but got 0.
 D/REALM(4446): jni: ThrowingException 3, ColumnType invalid., .
 D/REALM(4446): Exception has been throw: Illegal Argument: ColumnType invalid.
 W/System.err(4446): io.realm.exceptions.RealmException: Error during transaction.
 W/System.err(4446): 	at io.realm.Realm.executeTransaction(Realm.java:1519)
 W/System.err(4446): 	at com.example.backup.RealmRawSmsHelper.insert(RealmRawSmsHelper.java:132)
 W/System.err(4446): 	at com.example.backup.RealmRawSmsHelper.access$3(RealmRawSmsHelper.java:124)
 W/System.err(4446): 	at com.example.backup.RealmRawSmsHelper$1.run(RealmRawSmsHelper.java:78)
 W/System.err(4446): 	at java.lang.Thread.run(Thread.java:856)
 W/System.err(4446): Caused by: java.lang.IllegalArgumentException: Illegal Argument: ColumnType invalid.
 W/System.err(4446): 	at io.realm.internal.Row.nativeSetString(Native Method)
 W/System.err(4446): 	at io.realm.internal.Row.setString(Row.java:217)
 W/System.err(4446): 	at io.realm.RealmRawSmsRealmProxy.setMessage(RealmRawSmsRealmProxy.java:136)
 W/System.err(4446): 	at com.example.backup.RealmRawSmsHelper$3.execute(RealmRawSmsHelper.java:143)
 W/System.err(4446): 	at io.realm.Realm.executeTransaction(Realm.java:1515)
 W/System.err(4446): 	... 4 more
```

* Tested on Samsung Galaxy S3

**Comment by cmelchior** [comment] 2015-04-30 04:43
Hi @zsavely 
Yes, that looks very much as the same issue. Once we get the pull request above merged in, this should be fixed. But if you want to build Realm yourself from that branch you can try it already now.

**Comment by cmelchior** [comment] 2015-05-19 12:48
Hi @zsavely 
Sorry for the wait. A fix for this has been merged into master and should be available in our SNAPSHOT release (within 15 minutes).

**Closed** 2015-05-19 12:47 UTC
Labels: bug, PR

**Comment by zsavely** [comment] 2015-05-19 12:50
Hi @cmelchior 
Thank you for the fix!
