### ISSUE TITLE
read only query require a transaction, exception is Objects cannot be changed outside a transaction; see beginTransaction() for details

### ISSUE THREAD

**Issue by eboudrant** [realm/realm-java#917] opened 2015-03-01 23:05 UTC
I am doing a simple query and Realm complain about write transaction :
```
  public List<Installed> getInstalled(Realm realm, String pid) {
    RealmResults<Installed> packageQuery = realm.where(Installed.class)
        .equalTo("pid", pid)
        .findAll();
    return packageQuery;
  }
```
Exception is
```
java.lang.IllegalStateException: Objects cannot be changed outside a transaction; see beginTransaction() for details.
       at io.realm.internal.Group.throwImmutable(Group.java:320)
       at io.realm.internal.Group.getTable(Group.java:220)
       at io.realm.Realm.getTable(Realm.java:323)
       at io.realm.RealmQuery.(RealmQuery.java:75)
       at io.realm.Realm.where(Realm.java:1279)
       at n.e.a.realm.RealmDatasource.getInstalled(RealmDatasource.java:247)
```

**Comment by cmelchior** [comment] 2015-03-02 07:27
Hmm, it seems our error message in that place is a bit wrong. That exception is actually thrown because Realm doesn't know about your Installed class.

Does it extend RealmObject?

**Comment by eboudrant** [comment] 2015-03-02 15:19
Yes, it extend RealmObject.

**Comment by cmelchior** [comment] 2015-03-06 11:26
Hi @eboudrant 
Looking into this, I cannot reproduce it. So I have a few follow up questions?

- Can you reproduce this behaviour if you try to uninstall the app and then reinstall it.
- Are you manually doing a RealmMigration when starting the app?
- Is your Installed class part of the app code or part of a library project?

**Comment by cmelchior** [comment] 2015-03-12 19:03
Better error reporting has been merged. @eboudrant Are you still seeing this behavior on 0.80?

**Comment by cmelchior** [comment] 2015-03-17 16:40
Closing this due to no response. Please add additional information if the problem stil persists.

**Closed by cmelchior** 2015-03-17 16:40 UTC
Labels: support

**Comment by eboudrant** [comment] 2015-03-22 18:19
Hello, I just updated from 0.79 t0 0.80 and it crash instantly : https://github.com/realm/realm-java/issues/982
