### ISSUE TITLE
RealmConfiguration: name method not found

### ISSUE THREAD

**Issue by Maxxan** [realm/realm-java#4728] opened 2017-05-30 12:29 UTC
#### Goal

> I want to create two realm databases with different names for a unit test.

#### Expected Results

> The two databases should be created.

#### Actual Results

>  E.g. full stack trace with exception
java.lang.NoSuchMethodError: No virtual method name(Ljava/lang/String;)Lio/realm/RealmConfiguration$Builder; in class Lio/realm/RealmConfiguration$Builder; or its super classes (declaration of 'io.realm.RealmConfiguration$Builder' appears in /data/app/com.test.test-1/base.apk)
                                                                           at com.test.test.RealmTests.testSyncRealms(RealmTests.java:136)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                                                                           at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                                           at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                                                                           at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                                                                           at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
                                                                           at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
                                                                           at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                                                                           at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                                                                           at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                                                                           at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                           at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                           at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                           at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                           at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                           at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                           at org.junit.runners.Suite.runChild(Suite.java:128)
                                                                           at org.junit.runners.Suite.runChild(Suite.java:27)
                                                                           at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                                           at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                                           at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                                           at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                                           at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                                           at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                                           at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                                           at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                                           at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                                                                           at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                                                                           at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
#### Steps & Code to Reproduce

> It crashes every time I try. My suspicion is that it has something to do with syncing enabled, but I'm not sure. I still think it should be possible to create named local realm databases even if syncing is enabled in the gradle file.

I've tried to rebuild the project, reinstall the application etc., but same result.

#### Code Sample

```java
Realm.init(InstrumentationRegistry.getContext());
RealmConfiguration.Builder builder = new RealmConfiguration.Builder();
        RealmConfiguration config1 = builder.name("realm1.realm").build(); // Crashes here when "name" is called
        RealmConfiguration config2 = new RealmConfiguration.Builder().name("realm2.realm").build();

```

#### Version of Realm and tooling
Realm version(s): 3.3.1

Realm sync feature enabled: yes enabled in the build.gradle file, but not used in the unit test

Android Studio version: 2.3.2

Which Android version and device: Testing on an emulator, Android version 7.0

**Comment by cmelchior** [comment] 2017-05-30 12:31
It sounds like you are somehow including an older version of Realm somewhere. Do you see multiple versions of Realm if you run `./gradlew dependencies` ?

**Comment by Maxxan** [comment] 2017-05-30 12:43
The only realm related dependencies I see are:
\--- io.realm:realm-android-library-object-server:3.3.1
     +--- com.squareup.okhttp3:okhttp:3.4.1
     |    \--- com.squareup.okio:okio:1.9.0
     +--- io.realm:realm-annotations:3.3.1
     \--- com.getkeepsafe.relinker:relinker:1.2.2
and
+--- io.realm:realm-annotations:3.3.1

In my project gradle file I've got this one classpath "io.realm:realm-gradle-plugin:3.3.1" and when I've updated realm, I've just changed those numbers and synced the project. Do I need to manually delete something when upgrading to a new version of Realm?

**Comment by cmelchior** [comment] 2017-05-30 12:46
No, that should be fine. In that case it sounds like a packaging issue somewhere. Have you tried to delete all build directories locally and the apk on the device and then do a clean build?

**Comment by Maxxan** [comment] 2017-05-30 12:56
Now I have, I deleted all build files, selected in Android studio to invalidate caches and restart, selected Clean all, uninstalled the app from the emulator, rebuilt everything, but with the same problem. Could it be a ProGuard problem, since I've got that turned on for debug builds due to the 65k method limit?

**Comment by cmelchior** [comment] 2017-05-30 12:59
No, hitting the dex limit is pretty unmistakable. It will say something like  `com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]`

Can you post your `build.gradle` files?

**Comment by Maxxan** [comment] 2017-05-30 13:21
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
        classpath "io.realm:realm-gradle-plugin:3.3.1"
        classpath 'com.google.gms:google-services:3.0.0'

    }


    ext.compileSdkVersion=24
	ext.buildToolsVersion='25.0.3'
	ext.minSdkVersion=10
	ext.targetSdkVersion=24


    ext.supportLibraryVersion='com.android.support:support-v4:25.3.1'
    ext.playServicesVersionMaps='com.google.android.gms:play-services-maps:9.8.0'
    ext.playServicesVersionAnalytics='com.google.android.gms:play-services-analytics:9.8.0'
    ext.playServicesVersionLocation='com.google.android.gms:play-services-location:9.8.0'
    ext.playServicesVersionAuth='com.google.android.gms:play-services-auth:9.8.0'
    //ext.playServicesVersionIdentity='com.google.android.gms:play-services-identity:8.1.0'
    ext.supportCompatVersion='com.android.support:appcompat-v7:25.3.1'
    ext.supportGridVersion='com.android.support:gridlayout-v7:25.3.1'
    ext.supportPercentVersion='com.android.support:percent:25.3.1'
   // ext.supportDesignLibrary='com.android.support:design:23.1.0'

}

and

buildscript {
    repositories {
      //  mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
        jcenter()

    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.21.6'
        classpath 'com.ofg:uptodate-gradle-plugin:1.6.2'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'com.ofg.uptodate'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'realm-android'


repositories {
 //   mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
    jcenter()
    maven { url "https://jitpack.io" }
}

configurations.all {
    resolutionStrategy {
        force 'com.google.code.findbugs:jsr305:1.3.9', 'com.google.code.findbugs:jsr305:2.0.1'
    }
}
dependencies {

    compile fileTree(include: '*.jar', dir: 'libs')
    compile project(':libraries:NumberPicker')
    compile project(':libraries:TimePicker')
    compile project(':libraries:TreeViewList')
    compile project(':libraries:CardsUILib')
    compile project(':libraries:FileChooser')
    compile project(':libraries:TimesSquareLibrary')
    compile project(':libraries:ColorPicker')
    compile project(':libraries:DragSortList')
    compile project(':libraries:LockPattern')
    compile project(':libraries:Floatinghintedittext')
    compile project(':libraries:DateTimePicker')
    compile project(':libraries:QuickReturnHeader')
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile rootProject.supportLibraryVersion
    compile rootProject.supportCompatVersion
    compile('com.crashlytics.sdk.android:crashlytics:2.6.5@aar') {
        transitive = true
    }
    compile 'com.cocosw:undobar:1.8.1'
    compile 'com.readystatesoftware.systembartint:systembartint:1.0.4'
    compile 'com.github.gabrielemariotti.changeloglib:library:1.5.2'
    compile 'com.github.shell-software:fab:1.1.1'
    compile ('de.keyboardsurfer.android.widget:crouton:1.8.5@aar') {
    exclude group: 'com.google.android', module: 'support-v4'
    }

    compile 'com.github.PhilJay:MPAndroidChart:v2.1.4'

    compile rootProject.playServicesVersionMaps
    compile rootProject.playServicesVersionAnalytics
    compile rootProject.playServicesVersionLocation
    compile rootProject.playServicesVersionAuth
    compile files('libs/ez-vcard-0.9.7.jar')

    compile 'com.balysv.materialmenu:material-menu-toolbar:1.5.5'

    compile 'com.fasterxml.jackson.core:jackson-core:2.8.6'
    compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.8.6'


    // Google drive
    compile ('com.google.apis:google-api-services-drive:v3-rev61-1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    compile ('com.google.api-client:google-api-client-android:1.22.0'){
        exclude group: 'org.apache.httpcomponents'
    }

    compile 'com.github.hotchemi:permissionsdispatcher:2.1.3'
    apt 'com.github.hotchemi:permissionsdispatcher-processor:2.1.3'
    compile 'com.acappelli:TextDrawable:1.0'
    compile ('com.github.PierfrancescoSoffritti:WebBasedOAuth:0.7') { exclude module: 'appcompat-v7' }

    compile ('uk.co.samuelwall:material-tap-target-prompt:1.9.3') { exclude module: 'appcompat-v7' }
    compile project(path: ':libraries:SimpleNumberPicker')

    compile 'org.parceler:parceler-api:1.1.6'
    apt 'org.parceler:parceler:1.1.6'

    // Required -- JUnit 4 framework
    testCompile 'junit:junit:4.12'
    // Optional -- Mockito framework
    testCompile 'org.mockito:mockito-core:1.10.19'
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestCompile('com.android.support.test:runner:0.5') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }

    // Set this dependency to use JUnit 4 rules
    androidTestCompile ('com.android.support.test:rules:0.5'){
        exclude group: 'com.android.support', module: 'support-annotations'
    }

}

apply plugin: 'com.google.gms.google-services'

android {

    dexOptions {
        javaMaxHeapSize "3g"
    }

    lintOptions {
        disable "ResourceType"
    }


    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion
    enforceUniquePackageName = false
    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        applicationId = "com.test.test"
        testApplicationId  "com.test.test.matests"
        versionCode 273
        versionName '2.6.7'  // Update LogToSD!

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    sourceSets {

        androidTest {
            java.srcDirs = ['androidTest/java']
        }
        test {
            java.srcDirs = ['test/java']
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
    // Enable Realm syncing
    realm {
        syncEnabled = true;
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/services/com.fasterxml.jackson.core.JsonFactory'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src', 'tests/java']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }

  
    buildTypes {
        release {
            minifyEnabled true
            //shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.release
        }

        debug {
            minifyEnabled true
			useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

}

**Comment by Maxxan** [comment] 2017-05-31 16:36
Here is a project that reproduces the problem if you run the unit test.. https://drive.google.com/file/d/0B-f1Ysy8g4meTklobXJhM2hkaDA/view?usp=sharing

**Comment by beeender** [comment] 2017-06-02 09:26
I can reproduce your issue, checking now.

**Comment by beeender** [comment] 2017-06-02 09:40
Hi, it will pass if you disable `minifyEnabled = true` in the `debug` for build.gradle:
```
        debug {
            //minifyEnabled true
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```

Looks like a bug with minify and anroidTest? Do you have to enable it for `androidTest`? The proguard works fine with the release build though.

**Comment by Maxxan** [comment] 2017-06-02 15:13
Hi!
The problem is that I do need to have minify enabled. If I turn it off I get the dex limit error:
Error:Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

**Comment by Zhuinden** [comment] 2017-06-02 16:05
I mean technically you can use multidex support lib for debug

**Comment by Maxxan** [comment] 2017-06-02 16:09
Thanks, I will probably end up with something like that as a solution.

**Comment by beeender** [comment] 2017-06-05 02:58
@Maxxan please try with multidex first, i am closing this issue now. thanks!

**Closed by beeender** 2017-06-05 02:58 UTC
Labels: T:Help
