### ISSUE TITLE
Internal crash while trying to build a synced config

### ISSUE THREAD

**Issue by jhonnyinstacart** [realm/realm-java#7847] opened 2023-10-03 14:20 UTC
### How frequently does the bug occur?

Sometimes

### Description

An existing crash has been intensified after we upgraded our Realm Java SDK version from `10.14.0` to `10.16.1`, it consists of the realm java SDK crashing internally while trying to build a synced config. I don't really know how to reproduce this but from our crashlitics reports it is happening a lot more since we upgraded the SDK.

### Stacktrace & log output

```shell
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'byte io.realm.internal.objectstore.OsSyncUser.getState()' on a null object reference
       at io.realm.mongodb.User.getState(User.java:207)
       at io.realm.mongodb.User.isLoggedIn(User.java:266)
       at io.realm.mongodb.sync.SyncConfiguration$Builder.validateAndSet(SyncConfiguration.java:742)
       at io.realm.mongodb.sync.SyncConfiguration$Builder.<init>(SyncConfiguration.java:726)
       at io.realm.mongodb.sync.SyncConfiguration$Builder.<init>(SyncConfiguration.java:664)
       at ai.caper.catalog_sync.realm.RealmCatalogHelper.createSyncRealmConfig(RealmCatalogHelper.kt:137)
       at ai.caper.catalog_sync.realm.RealmCatalogHelper.getOrCreateRealmConfig(RealmCatalogHelper.kt:92)
       at ai.caper.catalog_sync.realm.RealmCatalogHelper.configureAndSynchronizeMaybe$lambda$1(RealmCatalogHelper.kt:54)
       at ai.caper.catalog_sync.realm.RealmCatalogHelper.$r8$lambda$EmQmbldCp3DackRkSXl2A8wwTig()
       at ai.caper.catalog_sync.realm.RealmCatalogHelper$$ExternalSyntheticLambda3.run(:4)
       at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableToFlowable.subscribeActual(CompletableToFlowable.java:32)
       at io.reactivex.Flowable.subscribe(Flowable.java:14935)
       at io.reactivex.Flowable.subscribe(Flowable.java:14882)
       at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.subscribeNext(FlowableRetryPredicate.java:124)
       at io.reactivex.internal.operators.flowable.FlowableRetryPredicate.subscribeActual(FlowableRetryPredicate.java:42)
       at io.reactivex.Flowable.subscribe(Flowable.java:14935)
       at io.reactivex.Flowable.subscribe(Flowable.java:14882)
       at io.reactivex.internal.operators.completable.CompletableFromPublisher.subscribeActual(CompletableFromPublisher.java:32)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableResumeNext.subscribeActual(CompletableResumeNext.java:41)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
       at io.reactivex.Completable.subscribe(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

### Can you reproduce the bug?

No

### Version

10.16.1

### What Atlas App Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

Android 7.1.1 and Android 10

### Build environment

Android Studio version: Android Studio Hedgehog | 2023.1.1 Canary 15
Android Build Tools version: 33.0.2
Gradle version: 7.6.2

**Comment by cmelchior** [comment] 2023-10-09 11:50
Hi @jhonnyinstacart Thank you for the report. This is indeed a bit strange. The error is happening inside our code when we check for a valid user when creating the SyncConfiguration, but that particular shouldn't be able to hit a NullPointer 🤔.  

 Exactly how are you passing in the user to the SyncConfiguration? And where are you getting the user from?

**Comment by jhonnyinstacart** [comment] 2023-10-10 15:42
Hey @cmelchior so the code I use to pass the user to the config builder is written in kotlin, so there's no way we are passing it as `null`, this is how we do login the  user:
```  kotlin
val user = app.login(Credentials.apiKey(apiKey))
```
And then this is how the config is built:

```  kotlin
  private fun createSyncRealmConfig(user: User, partitionValue: String) =
      SyncConfiguration.Builder(user, partitionValue)
          .name(DB_NAME)
          .schemaVersion(SCHEMA_VERSION)
          .modules(CatalogSyncModule())
          .syncClientResetStrategy(RealmCatalogHelper::createClientResetStrategy)
          .errorHandler { _, error -> Timber.i(error, "Realm config error") }
          .build()
```
Let me know if that helps, thanks in advance 🙏

**Comment by jhonnyinstacart** [comment] 2023-10-10 19:09
Update: we were looking at the SDK code a bit and noticed that the `User` can contain a `null` `osUser`:
* `App.login` uses `OsApp.login` internally:
<img width="698" alt="Screenshot 2023-10-10 at 12 04 35 PM" src="https://github.com/realm/realm-java/assets/98788087/0037129f-7af7-4109-b194-c96349981941">

* `osApp.login` uses `resultOrThrow`:
<img width="663" alt="Screenshot 2023-10-10 at 12 05 38 PM" src="https://github.com/realm/realm-java/assets/98788087/55865409-ede9-41bd-8355-fe03b3ece886">

* `resultOrThrow` can return `null` (instead of throwing) when `success != null` and `error.get()` is null:
<img width="842" alt="Screenshot 2023-10-10 at 12 06 30 PM" src="https://github.com/realm/realm-java/assets/98788087/6d8d08a2-1dfe-4d00-a664-52c9e744c1fb">

Sorry for all the screenshots, just wanted to make my case clear.

**Comment by cmelchior** [comment] 2023-10-10 19:17
Thanks for finding this. You are correct. This does indeed look problematic.

**Comment by cmelchior** [comment] 2023-10-11 09:43
I have been able to reproduce a flow that causes this crash. It looks like it could happen if you are calling `App.loginAsync()` and then cancel the task, depending on the exact timing, the `latch.await()` might throw, but instead of signaling an error it ends up returning `null`.

**Comment by cmelchior** [comment] 2023-10-12 17:12
10.16.2 was released with a fix for this.

**Closed by cmelchior** 2023-10-12 17:12 UTC
Labels: T-Bug, O-Community, Needs-Attention, Encryption:Off, Frequency:Sometimes, Repro:No, SDK-Use:Sync

**Comment by jhonnyinstacart** [comment] 2023-10-16 20:46
Hey @cmelchior SDK version 10.16.2 don't seem to be available on maven central yet, do you have an estimate on when it will be released?
