### ISSUE TITLE
Duplicate Nested realm object

### ISSUE THREAD

**Issue by RanZellerGit** [realm/realm-java#2918] opened 2016-06-01 09:04 UTC
Hi 

i have the same problem as described in the following link.
http://stackoverflow.com/questions/30258351/android-realm-copytorealmorupdate-creates-duplicates-of-nested-objects

one of your developers mentioned that there is no solution for this issue but it was a year ago so i wondering if something changed?

thanks 
Ran
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by nhachicha** [comment] 2016-06-01 10:10
Hi @RanZellerGit 
As @cmelchior mentioned, we can't update an object without a PK. If you don't want to provide a Primary Key, you can use a work around similar to the following (_based on the [SO OP model](http://stackoverflow.com/questions/30258351/android-realm-copytorealmorupdate-creates-duplicates-of-nested-objects)_)
```java
for (Note note: notes) {
    realm.where(Note.class)
    .equalTo("id", note.getId())
    .findFirst()
    .getTemplate()
    .deleteFromRealm();
}
realm.copyToRealmOrUpdate(notes);
```

Cheers,

**Comment by RanZellerGit** [comment] 2016-06-01 17:33
i'm running the following code which base on what you suggested 
and the Template instances do not been deleted 



	private void fetchNotesAndSave() {
		InputStream stream;
		try {
			stream = getAssets().open("notes.json");
		} catch (IOException e) {
			return ;
		}

		Gson gson = new GsonBuilder().create();

		JsonElement json = new JsonParser().parse(new InputStreamReader(stream));
		Note note = gson.fromJson(json, Note.class);

		realm.beginTransaction();
		realm.where(Note.class).findAll().deleteAllFromRealm();
		realm.copyToRealmOrUpdate(note);
		realm.commitTransaction();

		String text = "" + realm.where(Template.class).findAll().size();
		Log.d("MainActivity",text);
		Toast.makeText(this,text,Toast.LENGTH_LONG);
	}

you can see the code https://github.com/RanZellerGit/RealmTest/tree/master/app/src/main/java/com/example/ranzeller/realmtest

Thanks

**Comment by nhachicha** [comment] 2016-06-02 13:18
Hi @RanZellerGit 

`realm.where(Note.class).findAll().deleteAllFromRealm();` does not perform a cascade delete, this is something in our [backlog](https://github.com/realm/realm-java/issues/1104) btw.

To remove the `Template` you can either use the [provided code](https://github.com/realm/realm-java/issues/2918#issuecomment-222950343), or add another delete 
`realm.where(Template.class).findAll().deleteAllFromRealm();` 

Cheers,

**Comment by kneth** [comment] 2016-06-10 08:27
@RanZellerGit I am closing the issue as I believe @nh has provided answers for you. Don't hesitate to either reopen or create a new issue.

**Closed by kneth** 2016-06-10 08:27 UTC
Labels: S:Waiting For User, T:Help

**Comment by divakar1234** [comment] 2019-08-05 13:10
I am using the Realm Object Server which automatic data sync feature .The issue arises when i use the above approach and try to edit the same module from 2 devices logged in with same account simultaneously.The duplicate data gets generated and after that the application in both the phones crashes after 4-5 seconds.But this Fix works fine in case of a single device.
Need suggestions on this problem as i am stuck on this since many days.
Could there be a bug in the realm version i am using .Its 3.3.2.
Thanks in advance

**Comment by bmunkholm** [comment] 2019-08-05 13:46
@divakar1234 Please create a new issue with full description and hopefully a way to reproduce the issue. Thanks. (in general, don't expect anyone monitors closed issues :-) )
