### ISSUE TITLE
Get information from inner realm object as list 

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5425] opened 2017-10-15 09:30 UTC
Android POJO:

```
public class Company extends RealmObject {
    @PrimaryKey
    private long id;
    @Required
    private String avtarURL;
    private String logo_url_string;
    private RealmList<News> news;
}

public class News extends RealmObject {
    @PrimaryKey
    private long id;
    @Required
    private Date date;
    private String title;
    private String subtitle;
}
```

If I want to get all news for company with specific **id** I do next:

```
public static List<News> getNews(long companyId) {
        Realm realm = Realm.getDefaultInstance();
        try {
            Company company = realm.where(Company.class)
                    .equalTo(Company.ID, companyId)
                    .findFirst();
            RealmList<News> companyNewsRealmResults = company.getNews();
            List<News> companyNewsList = new ArrayList<News>();
            companyNewsList.addAll(companyNewsRealmResults);
            return companyNewsList;
        } finally {
            realm.close();
        }
}
```

OK. It's work fine.

But I need to get list of titles (as `List<String>`) of all news for specific company.
I can do this like this:

```
List<String> newsTitle = new ArrayList<String>();
for (News news : companyNewsList) {
   newsTitle.add(news.getTitle())
}
```

But I wan't to get this list manualy by iterate `companyNewsList`.
Is is it possible Realm to give me this information.
I mean query to Realm that return list of news's title as `List<String>` for specific company?

**Comment by Zhuinden** [comment] 2017-10-15 11:33
https://github.com/realm/realm-java/issues/5421#issuecomment-336540625

**Comment by cmelchior** [comment] 2017-10-15 15:21
Like @Zhuinden said, the above would be the way to do it if you do not want to rely on Realm's lazy-loading.

For other use cases you would need support for projections. I added an issue here https://github.com/realm/realm-java/issues/5426 describing how it might look like in Realm.

In the meantime I'll close this issue as an duplicate of #5426

**Closed by cmelchior** 2017-10-15 15:21 UTC
