### ISSUE TITLE
RealmChangeListener never called inside RealmResults

### ISSUE THREAD

**Issue by mshusek** [realm/realm-java#1894] opened 2015-12-04 21:09 UTC
Hi, i use realm for a lot of time but today i want to try use new feature called "Async query".  I would be grateful for tell me what I'm doing wrong.
 
realm version:     compile 'io.realm:realm-android:0.86.0'
empty main activity snippet:

     @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_activity);
        RealmResults< MyRealmObject> realmResults = Realm.getInstance(this).where(MyRealmObject.class).findAllAsync();
        realmResults.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                System.out.println("Never called...");
            }
        });
}

If i attached debbuger it stay on notifyChangeListeners and listener is not called because "this.currentTableViewVersion != version". RealmQuery is loaded because after few moment i have acces to data inside list.
![realmresult](https://cloud.githubusercontent.com/assets/13273387/11601329/a0f1f7a8-9ad2-11e5-95f6-573076c58dfc.png)

**Comment by cmelchior** [comment] 2015-12-07 09:43
Hi @mshusek 
I cannot reproduce the behaviour you are describing. Can you reproduce it in a sample project you can send us or provide some details on what your code is doing. When are you e.g. closing your Realm?

**Comment by slidenerd** [comment] 2015-12-07 16:23
Same issue here, in my case, the listeners are never triggered
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mRealm = Realm.getInstance(mContext);
        mAdmin = mRealm.where(Admin.class).findFirstAsync();
        mGroups = mRealm.where(Group.class).findAllSortedAsync(GROUP_NAME);

        //Add change listener to be notified when the objects are loaded asynchronously
        mAdmin.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                addHeaderToDrawer(mAdmin);
                mAdmin.removeChangeListener(this);
            }
        });
        mGroups.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                addGroupsToDrawer(mGroups);
                mGroups.removeChangeListener(this);
            }
        });
    }

I am on 0.86.0 of Realm

**Comment by slidenerd** [comment] 2015-12-07 16:31
private RealmChangeListener mListener = new RealmChangeListener() {
        @Override
        public void onChange() { // called once the query complete and on every update
            // use the result
            if (mAdmin.isLoaded()) {
                addHeaderToDrawer(mAdmin);
            }
            if (mGroups.isLoaded()) {
                addGroupsToDrawer(mGroups);
            }
        }
    };

Made an instance variable that has the listener 


    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mRealm = Realm.getInstance(mContext);
        mAdmin = mRealm.where(Admin.class).findFirstAsync();
        mGroups = mRealm.where(Group.class).findAllSortedAsync(GROUP_NAME);

        //Add change listener to be notified when the objects are loaded asynchronously
        mAdmin.addChangeListener(mListener);
        mGroups.addChangeListener(mListener);
    }


    @Override
    public void onDestroy() {
        super.onDestroy();
        mAdmin.removeChangeListener(mListener);
        mGroups.removeChangeListener(mListener);
        mRealm.close();
    }

This is not firing the listener either, let me see what I can do from my end, would appreciate any suggestions on your end @cmelchior

**Comment by vlonjatg** [comment] 2015-12-08 00:31
Yep same here, in v0.86.0 ```onChange``` is not firing. The same code works perfectly on Realm v0.85.1.

```java
gallery = realm.where(Gallery.class).findFirstAsync();
gallery.addChangeListener(new RealmChangeListener() {
    @Override
    public void onChange() {
               
    }
});
```

**Comment by vikas-fueled** [comment] 2015-12-08 08:57
I can confirm this too. listeners working on v0.85.1 are not working on v0.86.0

**Comment by kneth** [comment] 2015-12-14 08:45
@vlonjatg @vikas-fueled Can you upgrade to 0.86.1 and see if the fix (#1927) helps you?

**Comment by vikas-fueled** [comment] 2015-12-15 06:04
@kneth Awesome, `0.86.1` does fix the issue for me.

**Comment by kneth** [comment] 2015-12-15 08:12
@vikas-fueled Great to hear. Thanks for the feedback!

**Comment by mshusek** [comment] 2015-12-15 10:28
Thank you for fast fix, this bug can be closed.

**Comment by kneth** [comment] 2015-12-15 11:15
@mshusek Thanks for the update.

**Comment by vickychijwani** [comment] 2015-12-25 23:49
I'm seeing this exact issue under different conditions (namely, only when opening the Realm for the first time) with all versions since async queries were added: 0.84.2, 0.85.1, 0.86.1, and 0.87.1. It is easily reproducible in my project. The relevant code that demonstrates the issue is [here][code]. If you run the app and [follow these steps to reproduce it][issue], you'll notice that the first log appears but the others from inside the `RealmChangeListener` never do. This happens like 6 out of 10 times with 0.87.1.

One thing you'll need to build it is a TMDb API key. I'm sorry for this minor hassle but this app is quite small and simple to build anyway. For the API key you can sign up [here](https://www.themoviedb.org/account/signup), grab an API key from `https://www.themoviedb.org/account/<username>/api/details`, and put that in Model.java line 62.

Let me know if any other details are needed.

[issue]: https://github.com/vickychijwani/udacity-p1-p2-popular-movies/issues/18
[code]: https://github.com/vickychijwani/udacity-p1-p2-popular-movies/blob/a214b53c1d4c4c06684c3df9b8142048ef559a9d/app/src/main/java/me/vickychijwani/popularmovies/model/Database.java#L79-L103

**Comment by vickychijwani** [comment] 2015-12-30 22:53
Ok, I tested this again today with 0.87.1 and it works fine! Apparently Android Studio 2.0 (which is in Preview) wasn't building my app correctly after changing 0.86.0 => 0.87.1. I've had stale build issues on 2.0 Preview more than once since re-opening this (not to mention quite a few other weird issues). So I thought *maybe* if I go back to Studio 1.5... and it worked. I apologize for the false alarm. This can be closed.

**Comment by kneth** [comment] 2016-01-04 08:44
@vickychijwani Thanks!

**Closed by kneth** 2016-01-04 08:44 UTC
Labels: bug

**Comment by m4xp1** [comment] 2017-05-15 17:40
classpath "io.realm:realm-gradle-plugin:3.1.4"

Called in 80% of cases. Obviously there is a race of streams. If it manages to load before subscribing, it is not called.

```
 getRealm().where(Foo.class).equalTo(Foo.FIELD_NAME, name).findFirstAsync()
.addChangeListener(new RealmChangeListener<Foo>() {
            @Override
            public void onChange(Foo foo) {
                Log.d("TEST", "update ui");
                foo.removeChangeListener(this);
            }
        });
```

**Comment by Zhuinden** [comment] 2017-05-15 17:49
You need to keep a strong reference to the RealmResults otherwise it'll be eaten alive by the GC

**Comment by m4xp1** [comment] 2017-05-15 18:12
It is really! Thank you!

**Comment by semenoh** [comment] 2017-06-02 10:55
I have the same issue. But I'm using a separate thread:

```Kotlin
class Worker : Thread() {

    @Volatile var handler: Handler? = null

    lateinit var scheduler: Scheduler
    lateinit var results: RealmResults<Punch>
    lateinit var query: RealmQuery<Punch>
    val cm = App.instance.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager

    override fun run() {
        setUncaughtExceptionHandler { _, e ->
            val query = Realm.getDefaultInstance()
                    .where<Punch>(Punch::class.java)
                    .equalTo(Punch.Field.syncState, SyncState.PUSHED.intValue)
                    .findAll()

            setSyncState(query, SyncState.DIRTY)
            scheduleSyncJob()
            Logger.e("WORKER", e)
        }

        Looper.prepare()
        val looper = Looper.myLooper()

        scheduler = AndroidSchedulers.from(looper)
        query = Realm.getDefaultInstance()
                .where<Punch>(Punch::class.java)
                .equalTo(Punch.Field.syncState, SyncState.DIRTY.intValue)

        results = query.findAll()
        results.addChangeListener { collection, _ ->
            if (isNetworkAvailable()) {
                post(collection, {})
            } else {
                scheduleSyncJob()
            }
        }

        handler = object : Handler(looper) {
            override fun handleMessage(msg: Message) {
                // nothing so far
                // punches synchronization is triggered by the listener
            }
        }

        Looper.loop()
    }
}
```

**Comment by semenoh** [comment] 2017-06-02 10:58
I have the same issue. But I'm using separate thread:

```kotlin
class Worker : Thread() {
    lateinit var scheduler: Scheduler
    lateinit var results: RealmResults<Punch>
    lateinit var query: RealmQuery<Punch>

    override fun run() {
        Looper.prepare()
        val looper = Looper.myLooper()

        scheduler = AndroidSchedulers.from(looper)
        query = Realm.getDefaultInstance()
                .where<Punch>(Punch::class.java)
                .equalTo(Punch.Field.syncState, SyncState.DIRTY.intValue)

        results = query.findAll()
        results.addChangeListener { collection, _ ->
            if (isNetworkAvailable()) {
                post(collection, {})
            } else {
                scheduleSyncJob()
            }
        }

        Looper.loop()
    }
```

**Comment by beeender** [comment] 2017-06-02 11:03
@semenoh which realm-java version are you using? 
`Realm.getDefaultInstance()` created an anonymous Realm instance which might be closed by finalizer (I couldn't remember the previous behaviours clearly). But it is strongly suggested that in your case, keep the Realm instance as a member var and close it at the proper time. If the realm instance is closed, the listener won't be triggered as well.
