### ISSUE TITLE
Transaction atomicity not guaranteed in synchronized DML

### ISSUE THREAD

**Issue by changxiangzhong** [realm/realm-java#3657] opened 2016-10-19 11:37 UTC
## Background

We are using realm 1.1.1 in our production environment. But occasionally we get error report as following. A few months ago, we were using an older version (~0.88), and **NEVER** experienced this at all.

**Object is no longer managed by Realm. Has it been deleted?** The full stack can be found [here](http://crashes.to/s/1ce0d5e6a30) 
## Details

Here are the code for **models**

```
public class Campaign extends RealmObject {
    @PrimaryKey
    private String id;

    private RealmList<PositionedSection> sections;// PositionedSection is a RealmObject as well, and it has RealmObject properties as well

    @Index
    private Date updatedAt;
```

When this page opened, we'll use local cache to render the campaign list and issue a request to the backend to get the latest data models. Here's what happens when the response comes

```
    public void onGetCampaigns(GetCampaignsEvent event) {

        if (!event.isSuccess()) {
            handleError(event);
        } else {
            List<Campaign> campaigns = event.getCampaigns(); // This is the server response
            campaignDAO.save(campaigns); // Save to the realm, will be explained later
            if(adapter != null) {
                adapter.notifyDataSetChanged();
            }

        }

    }
```

Here's the persistence layer code. A few things are accomplished
- Preserve the local states
- Remove and cascade-remove all the revelant properties objects.
- Save the new stuff in cascade.

```
    public void save(final List items) {
        Map<String, Campaign> campaignMap = new HashMap<>();
        RealmResults result = list();
        Iterator<Campaign> iter = result.iterator();
        while (iter.hasNext()) {
            Campaign temp = iter.next();
            campaignMap.put(temp.getId(), temp);
        }

        for (int i = 0; i < items.size(); i++) {
            Campaign c = (Campaign) items.get(i);
            c.saveLocalState(campaignMap.get(c.getId()));
        }

        realm.executeTransaction(new Realm.Transaction() {

            @Override
            public void execute(Realm realm) {
                for(Class temp: cascadeRemoval) {
                    realm.delete(temp);
                }
                realm.delete(type);
                realm.copyToRealmOrUpdate(items);

            }
        });

    }
```

Concerning the Adapter, we are using a standard RealmBaseAdapter. 

Thanks in advance.
## Updates on 2016/11/24

Here's the code for the adapter

```
        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            ViewHolder holder;
            if (convertView == null) {
                convertView = LayoutInflater.from(parent.getContext()).inflate(R.layout.view_campaign_item, parent, false);
                holder = new ViewHolder();
                holder.campaignStatusIcon = (ImageView) convertView.findViewById(R.id.campaign_status_icon);
                holder.campaignName = (TextView) convertView.findViewById(R.id.campaign_name);
                holder.campaignPeriod = (TextView) convertView.findViewById(R.id.campaign_period);
                holder.campaignStatusText = (TextView) convertView.findViewById(R.id.campaign_status_text);
                holder.statusLayout = (FrameLayout) convertView.findViewById(R.id.status_layout);
                convertView.setTag(holder);
            } else {
                holder = (ViewHolder) convertView.getTag();
            }

            if (!getAdapterData().isValid()) { // Countermeasure for the exception
                return convertView;
            }

            Campaign c = getItem(position);
            if (!c.isValid()) { // Countermeasure for the exception
                return convertView;
            }

            bind(convertView.getContext(), holder, c);


            return convertView;
        }
```

Here's the full logs:
```
Fatal Exception: java.lang.IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
       at io.realm.internal.InvalidRow.getStubException(InvalidRow.java:177)
       at io.realm.internal.InvalidRow.getString(InvalidRow.java:88)
       at io.realm.CampaignRealmProxy.realmGet$status(CampaignRealmProxy.java:288)
       at no.hyper.campaign.datamodel.Campaign.getStatus(Campaign.java:133)
       at no.hyper.campaign.ui.fragment.CampaignListFragment$CampaignListAdapter.bind(CampaignListFragment.java:234)
       at no.hyper.campaign.ui.fragment.CampaignListFragment$CampaignListAdapter.getView(CampaignListFragment.java:227)
       at android.widget.AbsListView.obtainView(AbsListView.java:2929)
       at android.widget.ListView.makeAndAddView(ListView.java:1945)
       at android.widget.ListView.fillSpecific(ListView.java:1379)
       at android.widget.ListView.layoutChildren(ListView.java:1712)
       at android.widget.AbsListView.onTouchMove(AbsListView.java:5746)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:5612)
       at android.view.View.dispatchTouchEvent(View.java:9998)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2828)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2499)
       at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5549)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2816)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2777)
       at android.view.View.dispatchPointerEvent(View.java:10233)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5397)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5233)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4834)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4891)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7359)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7237)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7198)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7469)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:143)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Zhuinden** [comment] 2016-10-19 12:23
Because you are calling `adapter.notifyDataSetChanged()` manually, instead of letting the RealmChangeListener in RealmBaseAdapter handle it.

**Comment by changxiangzhong** [comment] 2016-10-19 12:47
@Zhuinden In that case, can we add a deprecated annotation/throw an exception to prevent people making mistakes.

**Comment by Zhuinden** [comment] 2016-10-19 12:51
@changxiangzhong it's not technically deprecated because it's the adapter's method, and you did receive an exception from the adapter. At best, what there *could* be is a compile-time LINT error, but that was never added.

Don't forget, I'm not an official Realm person, I'm just a passing community member.

> 0.89.0
> 
> Breaking changes
> //...
> Realm.refresh() and DynamicRealm.refresh() on a Looper no longer have any effect. 
> 
> RealmObject and RealmResults are always updated on the next event loop. <---- this one

Just don't call `adapter.notifyDataSetChanged()` after a local commit on the UI thread.

**Comment by changxiangzhong** [comment] 2016-10-19 13:02
@Zhuinden. An assumption is the _view refreshing_ triggered by **notifyDataSetChanged** happens in the same loop or it happens before the RealmResult updating loop.

In case of not inheriting RealmBaseAdapter, should I register a **RealmChangeListener** and notify the adapter when it's changed. Does that sound good?

**Comment by Zhuinden** [comment] 2016-10-19 13:03
Yes, just make sure you retain a field reference to the `RealmResults<T>` you're using as the dataset.

**Comment by changxiangzhong** [comment] 2016-10-19 13:05
Cool, thanks a lot 👍 , let's keep this open a little bit and see if we get more discussions.

**Comment by changxiangzhong** [comment] 2016-10-24 05:22
@zaki50 Can you confirm that remove the notifyDatasetChanged is the way to go?

**Comment by Zhuinden** [comment] 2016-10-24 06:49
At the very least, it should be called from `RealmChangeListener` (but Realm's adapters do that already).

**Comment by changxiangzhong** [comment] 2016-10-24 07:55
Even though the notifyDatasetChanged listener was removed, it still happens.

**Comment by Zhuinden** [comment] 2016-10-24 08:54
Can you add the new relevant code? This should have fixed it.

**Comment by changxiangzhong** [comment] 2016-10-24 09:06
@Zhuinden I have updated the question. But I can't figure out what else to add. Like I said, I just remove the 
```
            if(adapter != null) {
                adapter.notifyDataSetChanged();
            }

```

**Comment by beeender** [comment] 2016-10-31 19:09
@changxiangzhong Sorry for the late response. Are you still seeing the crashes? the link of the stacktrace in your question cannot be opened anymore. Can you please share the crash log you have for current version? And the related code pieces. Thanks!

**Comment by changxiangzhong** [comment] 2016-10-31 19:17
@beeender Thank you for your reply and I've appended my logs. All the substantial code are there. It feels like this issue happens when a user fling the listview and quickly quite the current view.

**Comment by beeender** [comment] 2016-10-31 19:25
@changxiangzhong how does your `getItem(position);` look like? Are you able to reproduce the issue? If you cannot reproduce the issue, try to delete the item and scroll the list view at the same time. I am not sure what happen to it, but if it can be reproduced, it will be easier to analyzing. How does your adapter look like? So you are not calling `notifyDataSetChanged` anymore, right?

**Comment by changxiangzhong** [comment] 2016-11-01 09:40
@beeender 
The following code is the saving part, when we get a server response, the following part will be invoked.
```
    public <T extends RealmObject & IModel> void save(final List<T> items, final boolean clear, final boolean filter) {
        realm.executeTransaction(new Realm.Transaction() {

            @Override
            public void execute(Realm realm) {
                if (clear) {
                    cascadeClear(realm); // clear property RealmObject instance
                    realm.delete(type); // wipe out all existing data
                }

                List<T> saved = realm.copyToRealmOrUpdate(items);
                //...
            }
        });
    }
```

The following part is the code for adapter
```
        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            ViewHolder holder = null;

            if (convertView == null) {
                holder = new ViewHolder();
                convertView = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_wall_notification_view, parent,false);
                holder.userAvatar = (ImageView) convertView.findViewById(R.id.participant_avatar);
                holder.updatedTime = (TextView) convertView.findViewById(R.id.happen_time);
                holder.message = (TextView) convertView.findViewById(R.id.notification_message);
                holder.root = convertView;
                convertView.setTag(holder);
            }
            holder = (ViewHolder) convertView.getTag();

            bind(convertView.getContext(), holder, getItem(position));

            return convertView;
        }
```
According to the log there the crash happens when the ```Adapter::getView()``` executes **right after** the saving. If you have a look at ```save``` method, it feels like there's a very small window between **clear all** and **saveOrUpdate** and the Adapter get notified before the **saveOrUpdate** takes effect. So my question is **Is the transaction atomicity guaranteed?**

**Comment by Zhuinden** [comment] 2016-11-01 09:46
> it feels like there's a very small window between clear all and saveOrUpdate and the Adapter get notified before the saveOrUpdate takes effect.

That is impossible, the other thread is notified when there has been a committed transaction, which means there is a new version of Realm to sync to.

> So my question is Is the transaction atomicity guaranteed?

Yes.

------------

I've been doing this clear -> re-insert thing before and it's a mess, I prefer this solution: http://stackoverflow.com/a/39352718/2413303

**Comment by changxiangzhong** [comment] 2016-11-01 10:08
@Zhuinden so it's not only me that experiencing this issue, and this "wipe and re-insert" thing doesn't work for you either. But I don't see much difference between your approach and mine. In your approach, the following steps get executed. 
1. InsertOrUpdate
2. Remove all non-updated items.

Actually I have a bulletproof solution "mark as remove" i.e. only mark items as ```_removed```. The deletion only happens when there's no UI operations (such as quitting)

**Comment by Zhuinden** [comment] 2016-11-01 10:57
@changxiangzhong my biggest issue with clearing all data was the invalidation of object links.

Although in my latest project, I just cleared things and reinserted them, and it worked just fine.

Anyways, it's all transactional, so it *should* work. I did have some trouble with scrolling and `notifyDataSetChanged()` though.

**Comment by changxiangzhong** [comment] 2016-11-01 11:02
@Zhuinden By "object links", do you mean references? I don't have any references to those models. All the instances are fetched through ```Adapter::getItem()```. Let's see how do the authors response. :)

**Comment by changxiangzhong** [comment] 2016-11-01 12:26
Tried to make a simplified sample to reproduce this issue. It's not reproduciable in the small project.

**Comment by cmelchior** [comment] 2016-11-01 15:24
These sorts of errors can happen if you do a synchronous transaction using e.g `realm.beginTransaction` or `realm.executeTransaction`. In that case there is a small chance that the cached size of the adapter gets out of sync, which causes this. As long as all updates are done async and any `notifyChange` is called from inside a RealmChangeListener it should not crash.

**Comment by changxiangzhong** [comment] 2016-11-01 15:30
@cmelchior In that case, will simply ```RealmObject::isValid()``` checking suffice? Because the view gets updated/corrected in the next loop.

**Comment by cmelchior** [comment] 2016-11-01 15:32
Yes, that should work

**Closed** 2016-11-01 15:37 UTC
Labels: T:Help
