### ISSUE TITLE
Case insensitivesearch doesn't work with UTF-8 cyrillic symbols 

### ISSUE THREAD

**Issue by tseglevskiy** [realm/realm-java#719] opened 2015-01-07 01:11 UTC
My database contains word "Лиза". Method .contains("description", "Лиз", false) founds the record, but  .contains("description", "лиз", false) founds nothing.

**Comment by cmelchior** [comment] 2015-01-07 05:42
Hi @tseglevskiy 

It is a known limitation caused by differences in UTF-8 implementations. We are tracking it here: https://github.com/realm/realm-java/issues/581

Closing this a duplicate.

**Closed by cmelchior** 2015-01-07 05:42 UTC
