### ISSUE TITLE
Bump minSDK to API 15

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#3623] opened 2016-10-12 02:00 UTC
We need to bump the`minSDK` to 11 as the lib is not usable under API < 11

`createAllFromJson` target an API 11 which is fine to avoid compile/install error under lower SDK but the implementation of Dalvik on lower API fails when the dependencies fails during classloading 
(even if this deps is not used). This issue is highlighted by _CommonWare_ 
[here](http://stackoverflow.com/questions/13444255/could-not-find-method-from-the-newer-api-with-using-targetapi-annotation#comment18382184_13444505)

**Comment by Zhuinden** [comment] 2016-10-12 05:58
Huh? The lib does work on API < 11, the referenced post said that API level 4 didn't allow it but API level 8 did. [Otherwise I'm sure this would have come up a long time ago.](https://github.com/realm/realm-java/pull/489#issuecomment-60139219)

Don't forget, API level 8 is Froyo. It worked for him on Froyo.

**Comment by nhachicha** [comment] 2016-10-12 21:13
Here is a sample project that demonstrate the issue. https://www.dropbox.com/s/wnkgbrfpzxu9hr6/RealmHelloWorld.zip?dl=0

Trying to run this under Genymotion 2.3.7 API 10 will fail

**Comment by Zhuinden** [comment] 2016-11-07 09:34
I'm pretty sure we could run 0.82.2 which already had the JSON API on a Genymotion 2.3.7 emulator.

I think this issue is bogus, and the issue is the armeabi support: https://github.com/realm/realm-java/issues/3506

**Comment by beeender** [comment] 2016-12-28 03:59
The API 10 crash is because of #3726 . And I am fixing it. Close this now.

**Comment by beeender** [comment] 2016-12-28 10:26
Although with #3726 fix, our tests don't run well on API 10 devices. It could be another issue than #3726. Reopen this for tracking it.

**Comment by cmelchior** [comment] 2017-01-26 14:20
API 9 is now gone from https://developer.android.com/about/dashboards/index.html
API 10 is still at 1%, after that we can bump to 15

**Comment by cmelchior** [comment] 2019-11-27 20:58
This is part of #6460

**Comment by cmelchior** [comment] 2020-08-20 17:51
With NDK 21 MinSdk is now 16

**Closed by cmelchior** 2020-08-20 17:51 UTC
Labels: Breaking, T-Enhancement
