### ISSUE TITLE
RealmChangeListener not called for RealmList of RealmObject

### ISSUE THREAD

**Issue by jpmcosta** [realm/realm-java#5507] opened 2017-11-03 11:46 UTC
#### Goal

After adding a `RealmChangeListener` to a `RealmList`, if the number of its elements changes, the listener should be called.

#### Expected Results

`RealmChangeListener` should always be called when the number of elements of a `RealmList` changes.

#### Actual Results

`RealmChangeListener` is not always called when the number of elements of a `RealmList` changes.

#### Steps & Code to Reproduce

I created a simplified Android project to reproduce the issue's workflow:
https://github.com/jpmcosta/RealmTestProject/tree/9375194c255977ae944fde292b7ca5b9ba845f5a

The workflow of the issue:
- `MainActivity` opens a `CreateActivity` that starts `CreateIntentService` to add or remove items from a `RealmList` (then, `CreateActivity` is finished)
- when the `MainActivity` starts again, it adds a `RealmChangeListener` to the `RealmList` and logs its current number of items
- the listener's `onChange()` method is not called, despite the number of items being changed (this is the issue)

To reproduce:
- run the app
- click on the floating action button to open `CreateActivity` and change the number of elements of the list
  - if the list is empty, it should fill the list with 10 items
  - if the list has items, it should clear all items
- logs are created when (log_tag: `ItemListAdapter`)
  - the `RealmChangeListener` is added: `add listener <current number of items>`
  - the `RealmChangeListener` is removed: `remove listener`
  - the `RealmChangeListener.onChange()`: `onChange() <current number of items>`
- to understand the issue:
  - notice the number of items when the listener is added, and compare it to the list's actual number of items
  - notice whether or not `onChange()` was called (usually, it's not called).
- you can also long press the floating action button to add a single item, to make sure the listener is working (it should work and a `onChange()` log should be created)

I'm reproducing the issue consistently, but not 100% of the time (maybe 99%).
If you can't reproduce the issue, try to change the `Don't keep activities` setting in Android's Developer options.

#### Version of Realm and tooling
Realm version: 4.1.0

Android Studio version: 3.0

Which Android version and device: 7.1.2

**Comment by Zhuinden** [comment] 2017-11-03 11:55
``` java
    @Override
    protected void onStart() {
        super.onStart();

        App app = getRealm().where(App.class).findFirst();
        ItemListAdapter mAdapter = new ItemListAdapter(app.items);
        mRecyclerView.setAdapter(mAdapter);
    }

    @Override
    protected void onStop() {
        super.onStop();

        mRecyclerView.setAdapter(null);
    }
```

what if this is in `onCreate()/`/`onDestroy()`?

**Comment by jpmcosta** [comment] 2017-11-03 12:11
Older listeners are called without any issues. So, the :
- if the activity is recreated (e.g., `Don't keep activities` is enabled), the listener is not called for the first time
- if the activity is not recreated, there wouldn't be any issues

**Comment by jpmcosta** [comment] 2017-11-03 12:18
It is not tested in the project I shared, but the `RealmChangeListener` of the `RealmObject` `App` should get called without any issues. At least, that's what I was able to reproduce in my main application.

**Comment by cmelchior** [comment] 2017-11-03 12:19
I'm not sure I fully understand your description. What I'm observing is:

```
11-03 08:08:05.752 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: remove listener
11-03 08:08:06.318 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 10
11-03 08:08:12.004 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 11
11-03 08:08:13.871 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 12
11-03 08:08:15.417 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 13
11-03 08:08:18.372 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: remove listener
11-03 08:08:18.785 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 13
<!-- Screen is still empty here for some reason
11-03 08:08:22.609 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: remove listener
11-03 08:08:23.116 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 0
11-03 08:08:23.119 1924-1924/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 10
```

But I wouldn't expect the `onChange` Listener to be called because you are removing it when exiting the screen and re-adding it when coming back, so Realm might have finished notifying observers when your return.

That said, there might be some timing involved I don't fully understand yet.

**Comment by jpmcosta** [comment] 2017-11-03 12:27
These are my use cases:

```
11-03 12:25:39.642 3479-3479/com.jpmcosta.test.realmtestproject I/ItemListAdapter: remove listener
11-03 12:25:40.304 3479-3479/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 0
<!-- Fab long click -->
11-03 12:25:44.101 3479-3479/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 11
```

or:
```
11-03 12:26:06.176 3479-3479/com.jpmcosta.test.realmtestproject I/ItemListAdapter: remove listener
11-03 12:26:06.826 3479-3479/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 11
<!-- Fab long click -->
11-03 12:26:09.377 3479-3479/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 1
```

Your logs seem fine. Have you tried changing the `Don't keep activities` setting in the developer options?

**Comment by cmelchior** [comment] 2017-11-03 12:28
Yes, I enabled that. 
What kind of device or emulator are you seeing this on? It sounds like it is timing related

**Comment by jpmcosta** [comment] 2017-11-03 12:29
I would say timing is indeed key. It seems the listener is added before the change, but too late to be notified.

**Comment by jpmcosta** [comment] 2017-11-03 12:30
I'm testing on a Xiaomi Mi A1, Android 7.1.2.

**Comment by jpmcosta** [comment] 2017-11-03 12:31
@cmelchior on the test project I can reproduce the issue without the `Don't keep activities`. I mentioned it, because on my main app, I only started seeing the issue after I enabled it.

**Comment by jpmcosta** [comment] 2017-11-03 12:34
@cmelchior just reproduced the issue in an emulator, Google Pixel Android 26, `Don't keep activities` disabled (the normal case).

**Comment by cmelchior** [comment] 2017-11-03 12:53
I still cannot reproduce it, but looking at your code and logs I'm pretty sure it is a race condition when listeners are being added in your code.

Your IntentService is running on another thread while your FAB is executing on the UI thread, and the `create` action returns as soon as the Intent is fired, not when it is actually is done executing. Note that Realm will trigger thread local listeners at the end of a `commitTransaction()` on the same thread.

I just need to convince myself of that by finding some interleaving of events that match what your seeing.

**Comment by cmelchior** [comment] 2017-11-03 13:04
@jpmcosta Can you try to change the FAB from synchronous to asynchronous instead? 

```
                getRealm().executeTransactionAsync(new Realm.Transaction() {

                    @Override
                    public void execute(@NonNull Realm realm) {
                        Random random = new Random();
                        final Item item = realm.copyToRealm(Item.create(random.nextInt()));
                        realm.where(App.class).findFirst().items.add(item);
                    }
                });
```

**Comment by Zhuinden** [comment] 2017-11-03 13:07
I always kinda wonder if https://github.com/realm/realm-java/issues/4878 is ever related. But I never know.

There is a tricky thing though which is that it is possible to navigate back in such a way that Realm has not yet refreshed the UI thread.

in iOS, we had a case where *sometimes* the `initial` change set returned an old value, and the write was then provided as `insertion`; but in some cases this was just done in one `initial`.

But I don't think it is possible to add a change listener with the event being already evaluated but the Realm being on an outdated version...

**Comment by jpmcosta** [comment] 2017-11-03 13:09
@cmelchior yes, but I don't understand what should I be looking for. Could you please further explain what I should report back? The FAB is not part of the issue.

**Comment by cmelchior** [comment] 2017-11-03 13:14
After thinking some more, this might be a bug in Realm after all:

```
11-03 12:35:32.577 5321-5321/com.jpmcosta.test.realmtestproject I/ItemListAdapter: remove listener
11-03 12:35:33.124 5321-5321/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 0
<!-- Fab long click. -->
11-03 12:35:37.554 5321-5321/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 11
```

The FAB is triggering an asynchronous transaction. These are inherently a little annoying when it comes to listeners as starting a transaction means we need to notify all listeners on the thread as the version is bumped to the latest at the beginning of a write, but we also need to notify all listeners when the write is committed to avoid UI components caching wrong sizes.

This means that the above scenario should have been:
```
remove listener
add listener, size 0
<!--- Intent Service runs, bumping items to 10
press_fab
begin_transaction
<!-- This should trigger `onChange(), size 10`. This is not happening
add_extra_item
commit_transaction
onChange(), size 11
```

**Comment by cmelchior** [comment] 2017-11-03 13:18
> yes, but I don't understand what should I be looking for. Could you please further explain what should I report back? The FAB is not part of the issue.

Forcing everything into asynchronous API's serializes the notifications on the Looper. In the current code there is a mix of asynchronous and synchronous notifactions.

Also, can you try upgrading to Realm Java 4.1.1. We had a few bugs with notifications in 4.0.0 and 4.1.0 with notifications. Although that was mostly about adding/removing listeners inside another listener, which your code isn't doing. But we did change a few code paths you are hitting.

**Comment by jpmcosta** [comment] 2017-11-03 13:19
>Forcing everything into asynchronous API's serializes the notifications on the Looper. In the current code there is a mix of asynchronous and synchronous notifactions.
The issue is not related to the FAB. `onChange()` is not called even if the FAB is not clicked.

**Comment by jpmcosta** [comment] 2017-11-03 13:23
As I see it, this is a bug or limitation:
```
11-03 12:35:33.124 5321-5321/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 0
<!-- Fab long click. -->
11-03 12:35:37.554 5321-5321/com.jpmcosta.test.realmtestproject I/ItemListAdapter: onChange() called 11
```

Expected results:
Intent service ends before we add the listener.
```
<!-- Intent service ends. -->
ItemListAdapter: add listener 10
<!-- Fab long click. -->
ItemListAdapter: onChange() called 11
```

Intent service ends after we add the listener
```
ItemListAdapter: add listener 10
<!-- Intent service ends. -->
ItemListAdapter: onChange() called 10
<!-- Fab long click. -->
ItemListAdapter: onChange() called 11
```

**Comment by cmelchior** [comment] 2017-11-03 13:27
It is working as intended from what I can tell? You are exiting the `CreateActivity` before knowing what happened to the IntentService. This means that the IntentService might be completely done when coming back to `MainActivity`, so the `onChange` listener will not trigger because everything is up to date.

**Comment by jpmcosta** [comment] 2017-11-03 13:28
Just tested in Realm 4.1.1, Android Emulator Google Pixel API 26, same issue:
- I receive this log `11-03 13:26:44.775 4143-4143/com.jpmcosta.test.realmtestproject I/ItemListAdapter: add listener 0` -> the list has 0 items when the listener is added
- the list shows 10 items
- onChange() is not called

**Comment by jpmcosta** [comment] 2017-11-03 13:30
>This means that the IntentService might be completely done when coming back to MainActivity, so the onChange listener will not trigger because everything is up to date.

But if everything is up to date, when add the listener, the number of items should be correct, and it is not.

**Comment by cmelchior** [comment] 2017-11-03 13:30
Ah, now I finally understand the issue 🤕 ... I see the same behaviour

**Comment by cmelchior** [comment] 2017-11-07 07:09
I finally had a chance to look more into this today. It definitely looks like a bug in Realm. If you add a `RealmChangeListener` to the realm itself, then it gets correctly notified when the list is updated, but the listener on the List itself is not.

I'm still looking for the root cause.

**Comment by Zhuinden** [comment] 2017-11-07 09:07
@cmelchior is `OrderedRealmCollectionChangeListener` notified correctly?

**Comment by cmelchior** [comment] 2017-11-07 09:49
It doesn't appear so, no, but so far I failed to reproduce in a unit test while I can consistently reproduce it in the example app.

**Comment by cmelchior** [comment] 2017-11-07 10:15
On observation. If you replace the IntentService with an async transaction, then everything works as expected:

```
        mFab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Random random = new Random();
                getRealm().executeTransactionAsync(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        Random random = new Random();
                        App app = realm.where(App.class).findFirst();
                        if (app.items.isEmpty()) {
                            for (int i = 0; i < 10; i++) {
                                final Item item = realm.copyToRealm(Item.create(random.nextInt()));
                                app.items.add(0, item);
                            }
                        } else {
                            app.items.clear();
                        }
                    }
                });
//                startActivity(new Intent(MainActivity.this, CreateActivity.class));
            }
        });
```
In that case, you are never leaving the Activity though, which means that a lot of the tearDown/setup logic isn't triggered, so I suspect there is something there when adding/removing listeners.

**Comment by jpmcosta** [comment] 2017-11-07 12:02
When creating the test project, I tried to play with async transactions with sleeps and and adding and removing listeners. 
I wasn't able to reproduce the apparent bug that way, so I settled to recreate the workflow of my main app, where I was experiencing the issue.

**Comment by cmelchior** [comment] 2017-11-07 17:40
So I managed to isolate the problem further. Everything in Java seems to work as expected. All listeners are registered correctly in the Java data structures, but our underlying C++ notification subsystem does not seem to trigger the listener.

I'm guessing because the reference to the Java object is removed for some reason, but unfortunately figuring out exactly what is a bit tricky as long as I cannot isolate the problem in a unit test. 

But at least we know where to look now.

**Comment by Zhuinden** [comment] 2017-11-07 17:57
Guys, if you kept the adapter initialization in  in `onStart()` and its destruction in `onStop()`, then the fact that the RealmList can get GC'd and the adapter gets recreated is completely obvious.

**Comment by cmelchior** [comment] 2017-11-07 18:05
Yes, but the problem is not the recreation of the adapter as far as I can see. What I'm seeing is that a `RealmListener` on the Realm is triggered due to the background write, but the more specialized listener on realmlist is not.

This indicate that the problem is not around the adapter, but how the listeners work.

```
11-07 10:55:27.625 13292-13292/com.jpmcosta.test.realmtestproject I/REALM_JAVA: MainActivity: onStart()
11-07 10:55:27.625 13292-13292/com.jpmcosta.test.realmtestproject I/REALM_JAVA: Size of list: 10
11-07 10:55:27.663 13292-13292/com.jpmcosta.test.realmtestproject I/REALM_JAVA: onChange() called on Realm. Size: 0
<!-- The List specific  Listener should have been triggered here
11-07 10:55:27.759 13292-13292/com.jpmcosta.test.realmtestproject I/REALM_JAVA: getItemCount(): 0
```

**Comment by beeender** [comment] 2017-11-17 10:34
Test case to reproduce the issue:

```java
    @Test
    @RunTestInLooperThread
    public void addChangeListener_bug5507() throws InterruptedException {
        Realm realm = looperThread.getRealm();
        realm.beginTransaction();
        Owner owner = realm.createObject(Owner.class);
        realm.commitTransaction();

        //RealmList<Dog> dogs = owner.getDogs();
        RealmResults<Dog> dogs = realm.where(Dog.class).findAll();
        RealmChangeListener<RealmResults<Dog>> listener1 = new RealmChangeListener<RealmResults<Dog>>() {
            @Override
            public void onChange(RealmResults<Dog> dogs) {
                fail();
            }
        };
        assertEquals(0, dogs.size());
        dogs.addChangeListener(listener1);

        Thread bgThread = new Thread(new Runnable() {
            @Override
            public void run() {
                Realm realm = Realm.getInstance(looperThread.getConfiguration());
                realm.beginTransaction();
                Dog dog = realm.createObject(Dog.class);
                Owner owner = realm.where(Owner.class).findFirst();
                owner.getDogs().add(dog);
                realm.commitTransaction();
                realm.close();
            }
        });
        bgThread.start();
        bgThread.join();
        try {
            dogs.get(0);
        } catch (Exception e){
        }
        dogs.removeChangeListener(listener1);
        dogs.addChangeListener(new RealmChangeListener<RealmResults<Dog>>() {
            @Override
            public void onChange(RealmResults<Dog> dogs) {
                assertEquals(1, dogs.size());
                looperThread.testComplete();
            }
        });
        assertEquals(0, dogs.size());
    }
```

checking now

**Comment by VenomVendor** [comment] 2017-12-26 18:14
@cmelchior is this supposed to be closed?

**Comment by trr-amsiq** [comment] 2018-04-09 07:39
Hi guys,

Just migrated all my adapters to realm-adapters and started getting these crashes. 
Any updates on this issue?

Thanks

**Comment by Zhuinden** [comment] 2018-04-09 08:31
If you have custom item types in your Adapter then Realm doesn't know about those. We ran into this by using `getItemViewType` for showing empty views, but that is not Realm bug ofc.

**Comment by trr-amsiq** [comment] 2018-04-10 07:14
I'll look into that

**Comment by ggajews** [comment] 2020-09-11 15:04
Is this issue still present? I run into a similar problem. I'm removing the object in the background (async transaction) when exiting the activity, and in the Activity I'm returning to in `OnStart` I'm making new query with `findAll` which is still returning the object that was deleted, and I'm adding change listener to the result but it doesn't trigger.

**Comment by Zhuinden** [comment] 2020-09-11 16:29
1.) keep the RealmResults as a field reference
2.) if you are adding RealmChangeListener to a RealmList, you also need to keep a field reference to the RealmList
3.) you theoretically shouldn't need to "create new query" to get new results, Realm will update your Results accordingly. Just make sure you keep a reference to the RealmResults

**Comment by ggajews** [comment] 2020-09-11 20:53
that is exactly what I do already:
```
class ActivityA: Activity {
   var realmResults: RealmResults<Model>? = null
   val realmChangeListener ...

   override fun onStart() {
       realmResults = realm.where(Model::class).findAll()
       realmResults.addChangeListener(realmChangeListener)
   }

   override fun onStop() {
      reportsResults?.removeChangeListener(realmChangeListener)
   }
}
```

I start `ActivityB` from `ActivityA`, where I start deleting async transaction right before finishing.
After adding some logs it looks like transaction finishes before ActivityA onStart but realmQuery still returns the deleted object, and no change listener is triggered after that.

I was able to fix it, by replacing `findAll()` with `findAllAsync()`. (Which should be like that from the beginning :)). But it looks like reported issue is still present

**Comment by Zhuinden** [comment] 2020-09-11 22:03
If you use findAll(), the evaluation is immediate and you won't get a call to the change listener unless your transaction is updating with a delay.

**Comment by cmelchior** [comment] 2021-01-05 09:16
This should have been fixed by https://github.com/realm/realm-java/pull/5574. Closing.

**Closed by cmelchior** 2021-01-05 09:16 UTC
Labels: O-Community, T-Bug
