### ISSUE TITLE
Startup Crash - Debug build with latest gradle build tool (2.3.1) on Android 5.1

### ISSUE THREAD

**Issue by dekrandroid** [realm/realm-java#4562] opened 2017-04-26 15:03 UTC
On Android with Android 5.1 device, the build fails to start up with debuggable build.
With the same code, we do not have the problem with the release build.

#### Actual Results

```java

 java.lang.RuntimeException: Unable to instantiate application com.technogym.mywellness.Application: java.lang.ClassNotFoundException: Didn't find class "com.technogym.mywellness.Application" on path: DexPathList[[zip file "/data/app/com.technogym.mywellness.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.technogym.mywellness.debug-1/lib/arm64, /vendor/lib64, /system/lib64]]
       at android.app.LoadedApk.makeApplication(LoadedApk.java:581)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4875)
       at android.app.ActivityThread.access$1500(ActivityThread.java:182)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5690)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.technogym.mywellness.Application" on path: DexPathList[[zip file "/data/app/com.technogym.mywellness.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.technogym.mywellness.debug-1/lib/arm64, /vendor/lib64, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at android.app.Instrumentation.newApplication(Instrumentation.java:985)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:576)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4875) 
       at android.app.ActivityThread.access$1500(ActivityThread.java:182) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554) 
       at android.os.Handler.dispatchMessage(Handler.java:111) 
       at android.os.Looper.loop(Looper.java:194) 
       at android.app.ActivityThread.main(ActivityThread.java:5690) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
                                                                                	Suppressed: java.lang.ClassNotFoundException: com.technogym.mywellness.Application
       at java.lang.Class.classForName(Native Method)
       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
       ... 13 more
    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

#### Steps & Code to Reproduce

Start the app and crash every time.

#### Version of Realm and tooling
Realm version(s): 3.1.3

Realm sync feature enabled: yes/no

Android Studio version:  2.3.1 - com.android.tools.build:gradle:2.3.1

ANDROID_BUILD_TARGET_SDK_VERSION=25
ANDROID_BUILD_TOOLS_VERSION=25.0.2
ANDROID_BUILD_SDK_VERSION=25

Which Android version and device:  
Android 5.1 - Huwaei P8 Lite Smart TAG-L01
Android 5.1 - Wiko ALPS.L1.MP6.V2

**Comment by Zhuinden** [comment] 2017-04-26 15:05
Is instant run disabled?

Is multidexing enabled?

**Comment by dekrandroid** [comment] 2017-04-26 15:13
InstanRun is enabled.
Multidexing is enabled.

**Comment by Zhuinden** [comment] 2017-04-26 15:30
Disable instant run.

**Comment by dekrandroid** [comment] 2017-04-26 15:42
Do we have any way to use instant run in this case?

**Comment by Zhuinden** [comment] 2017-04-26 15:47
No

**Comment by llPorZall** [comment] 2017-04-26 18:19
Hi Guy.
I'm always faced this issue all time.
My InstanRun and multidexing are disable. 
Do you have any suggestion to solve this problem?

My  Project gradle
`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath "io.realm:realm-gradle-plugin:3.1.3"
    }
}`

My App gradle
`
apply plugin: 'com.android.application'
apply plugin: 'realm-android'
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.holy.live"
        minSdkVersion 18
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            resValue "string", "base_url", ""
        }
        debug {
            debuggable true
            applicationIdSuffix ".debug"
            resValue "string", "base_url", "https://192.168.1.100:4000/"
            resValue "string", "facebook_app_id", ""
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(path: ':library')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.google.firebase:firebase-core:10.2.1'
    compile 'com.google.firebase:firebase-messaging:10.2.1'
    compile 'com.google.firebase:firebase-auth:10.2.1'
    compile 'com.google.firebase:firebase-database:10.2.1'
    compile 'com.google.firebase:firebase-crash:10.2.1'
    compile 'com.google.firebase:firebase-storage:10.2.1'
    compile 'com.google.android.gms:play-services-auth:10.2.1'
    compile 'com.jakewharton:butterknife:8.5.1'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.android.support:design:25.3.1'
    compile 'com.github.hotchemi:permissionsdispatcher:2.3.2'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.2'
}
apply plugin: 'com.google.gms.google-services'
`

**Comment by kneth** [comment] 2017-04-27 07:51
@llPorZall Is it only when testing or in general?

**Comment by llPorZall** [comment] 2017-04-27 08:07
@kneth Thanks, Let me check and get feedback to you soon.

**Comment by zaki50** [comment] 2017-04-28 07:09
@llPorZall Could you share the stack trace with us?

**Comment by OmkarAmberkar** [comment] 2017-04-30 02:37
@dekrandroid you are probably building the apk for you debugging device in which case this happens. Instead of hitting the run button, try building your apk from Build-> Build apk and it should be good.

**Comment by jemshit** [comment] 2017-05-12 08:21
`
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:2.3.2.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.jar
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.jar
     Required by:
         project :
   > Could not find com.android.tools.build:gradle:2.3.2.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.jar
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom
         https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.jar
     Required by:
         project : > io.realm:realm-gradle-plugin:3.1.4
         project : > io.realm:realm-gradle-plugin:3.1.4 > io.realm:realm-transformer:3.1.4
`
gradle version 3.3
android gradle build tool 2.3.2
realm 3.1.4

**Comment by kneth** [comment] 2017-05-15 07:02
Just checked the existence of https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/. Maybe you need to refresh the dependencies?

**Comment by jemshit** [comment] 2017-05-15 07:37
@kneth it started to work, did nothing

**Comment by bmeike** [comment] 2017-05-15 23:07
Hey @jemshit , this really has nothing at all to do with Realm.  Your problem is here:
```
   > Could not find com.android.tools.build:gradle:2.3.2.
```
It could be caused by being off-line, having something screwy in your gradle cache (`~/.gradle`) or having the `buildscript.repositories` clause set up wrong in your top level `build.gradle`.

I'm going to close this ticket as off-topic.  Feel free to re-open it if you have a Realm related problem.

**Closed by bmeike** 2017-05-15 23:07 UTC
Labels: T:Help
