### ISSUE TITLE
.sum(ListItem.PRICE).doubleValue() returns 359.65000000000000003 when it should just return 359.65

### ISSUE THREAD

**Issue by Muddz** [realm/realm-java#4251] opened 2017-02-25 13:20 UTC
This problem is freaknig strange and only happends randomly sometimes. 
The aim is to get the sum of all prices from a `RealmList`

When I add the following numbers to a `RealmList<ListItem> itemList;` and gets the sum value of them all  I get this huge double value:

+10
+10.10
+69
+250
+20.55

I have debugged the value the whole way from edittext to the realm transaction and nothing is wrong there. Its only when I want to get the double sum value from Realm

This is the following code that I use to get the sum of a specific member variable of a `RealmObject`

    private void onListItemChangedListener() {
        realm.addChangeListener(new RealmChangeListener<Realm>() {
            @Override
            public void onChange(Realm element) {

               shoplist.getItemList().sum(ListItem.PRICE).doubleValue();

            }
        });
    }

`Shoplist` here is just an RealmObject containg af title and a `RealmList<ListItem>`

**Comment by cmelchior** [comment] 2017-02-26 21:43
This is not related to Realm, but how floating point math works. Adding double values can lead to cases like this which is why you should always round to the specific number of decimals you want.

See e.g.:
https://en.wikipedia.org/wiki/Floating_point
http://stackoverflow.com/questions/588004/is-floating-point-math-broken

This pure Java unit test will also fail
```
    @Test
    public void doubleTest() {
        double d = 0;
        d += 10;
        d += 10.10;
        d += 69;
        d += 250;
        d += 20.55;
        assertEquals(359.65d, d, 0.0d);
    }
```

Closing this as working as intended.

**Closed** 2017-02-26 21:44 UTC
