### ISSUE TITLE
Getting "Native crash at /data/app-lib/<package_name>-2/libtightdb-jni.so"

### ISSUE THREAD

**Issue by ImGauravC** [realm/realm-java#791] opened 2015-01-24 22:18 UTC
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/jfltexx/jflte:4.4.2/KOT49H/I9505XXUGNG8:user/release-keys'
Revision: '11'
pid: 31444, tid: 31498, name: MESSAGING >>> <package_name> <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 32af6378
r0 7af756a8 r1 7af756a0 r2 00000000 r3 72631090
r4 7af756a8 r5 32af6374 r6 7af756a0 r7 7af757f0
r8 000001af r9 00000001 sl 00000002 fp 77d501d8
ip 7b7054ff sp 7af75680 lr 7b7023c5 pc 7b699fe6 cpsr 200d0030
d0 0000000000000000 d1 0000000000000000
d2 0000000000000000 d3 0000000000000000
d4 b1c4636148206e65 d5 3263313420000309
d6 3163343234323638 d7 6636343263633836
d8 414d46c600000000 d9 414d46c600000000
d10 414d46c600000000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 0b970105010b9700 d17 0b9702051795cb8d
d18 0b97030517b4d8d6 d19 97040505a68fddb4
d20 97050501ea9b8c0b d21 97060501e9b1c20b
d22 77170b970709400b d23 74276e6f64207968
d24 4162e41380000000 d25 0000000000000000
d26 0000000000000000 d27 0000000000000000
d28 0100010001000100 d29 0100010001000100
d30 416312d000000000 d31 4024000000000000
scr 20000012

backtrace:
#00 pc 00031fe6 /data/app-lib/[package_name]-2/libtightdb-jni.so (tightdb::Array::init_from_mem(tightdb::MemRef)+7)
#01 pc 0009a3c1 /data/app-lib/[package_name]-2/libtightdb-jni.so (tightdb::ArrayBigBlobs::set(unsigned int, tightdb::BinaryData, bool)+60)
#02 pc 0009efcf /data/app-lib/[package_name]-2/libtightdb-jni.so (tightdb::ArrayBigBlobs::set_string(unsigned int, tightdb::StringData)+12)
#03 pc 0009d68b /data/app-lib/[package_name]-2/libtightdb-jni.so ((anonymous namespace)::SetLeafElem::update(tightdb::MemRef, tightdb::ArrayParent*, unsigned int, unsigned int)+396)

code around pc:
7b699fc4 2904ba31 f004d101 2908ba63 f004d101 
7b699fd4 2940ba95 f004d1ea b5f8bac9 680d4604 
7b699fe4 792b460e 760309db f3c3792b 76431380 
7b699ff4 f3c3792b 76831340 f0034628 6160ffac 
7b69a004 46284607 ffaff003 68736a62 685260e0 
7b69a014 d3084293 f0034628 6823ffae 695b463a 
7b69a024 46204601 68734798 61203508 60654620 
7b69a034 696160a3 40f8e8bd b538e7ae 69c04604 
7b69a044 6a21460d 68db6803 68a24798 46014290 
7b69a054 42a8d101 4620d304 fee6f7f8 bd382001 
7b69a064 bd382000 4ff0e92d 6a46b087 f8dd4607 
7b69a074 468a8040 4614461d f8dd4630 46419044 
7b69a084 ff59f003 3004f990 2b004683 f8d9db09 
7b69a094 a9043000 9004689b f8cd4648 47988014 
7b69a0a4 f003e024 3802ff60 d9072801 46414638 
7b69a0b4 febaf7f8 f0034638 e017ff77 21004658 

code around lr:
7b7023a4 f77f940c 4605ff37 4629980d 695b6803 
7b7023b4 95034798 a902ad04 46289002 fe0df797 
7b7023c4 46214628 f8cd970b f7988030 6872f953 
7b7023d4 99074628 e88d6833 460a0204 ff64f7ff 
7b7023e4 e8bdb027 bf0083f0 00063856 41f0e92d 
7b7023f4 4698b0a4 46164b11 6a422400 9403447b 
7b702404 94094605 940a3308 460fac24 f844920b 
7b702414 46203d88 f91af000 99056872 68334620 
7b702424 0104e88d f7ff460a 4628ff3f 9a044639 
7b702434 f7982300 b024fb07 81f0e8bd 000637ec 
7b702444 43f8e92d 9d08461c 46894606 1c6b684f 
7b702454 68c5bf08 f107b112 e0140801 e01246b8 
7b702464 46214630 fed6f77f 6a704601 69526802 
7b702474 79824790 02127941 4201eb02 440a79c1 
7b702484 d0034542 42ac3401 e008d1ea f8d93008 
7b702494 463a1000 e96cf77d d1f32800 f04fe003 

Other details:
Android Version 4.4
Device: Galaxy S4 (jflte)

**Comment by emanuelez** [comment] 2015-01-24 22:25
Hello Gourav. Would you mind sharing more info about what you are trying to achieve, how you were doing it and how Realm failed? Seeing this wall of text does not help too much without proper context :smiley:

**Comment by ImGauravC** [comment] 2015-01-24 22:31
I'm trying to build a message caching layer using Realm. Since I use realm at multiple places and there is no stack trace since it's a native exception, it's difficult to know exactly what caused this. All I can tell is I've seen this exception only on Android 4.4 till now.

**Comment by emanuelez** [comment] 2015-01-24 23:03
Is there any way you can share the code? Even in a private way?

**Comment by ImGauravC** [comment] 2015-01-25 21:07
Sorry Emanuele, it's not possible for me to share the code. :(

**Comment by bmunkholm** [comment] 2015-01-27 10:02
@ImGauravC:
Which version of Realm are you using?
Was this from your own testing or a user report?
Have you only seen this once? Is it reproducible in any way?

**Comment by ImGauravC** [comment] 2015-01-27 15:55
I'm using Realm version 0.77.0.
This is from developer console's error reports. 
This is happening a lot in production. The sad part is that I can't reproduce this on any of our test devices.

**Comment by bmunkholm** [comment] 2015-01-27 18:28
It's very likely this could have been fixed in the latest release 0.78 where the core was updated with some important fixes. Could you try that and report back? It would be very interesting to know if it fixes your users errors.

Thanks!

**Comment by ImGauravC** [comment] 2015-01-31 20:07
It's still throwing native crashes.

**Comment by emanuelez** [comment] 2015-02-09 09:17
Did making your transactions shorter (as we discussed in another Github issue) solve this problem for you?

**Comment by ImGauravC** [comment] 2015-02-09 21:00
Nope.

**Comment by kneth** [comment] 2015-03-20 00:02
Just wondering if you have tried with the latest version of Realm.

**Comment by cmelchior** [comment] 2015-04-15 17:29
Closing due to no response. Please reopen if you are still seeing issues with this.

**Closed by cmelchior** 2015-04-15 17:29 UTC
Labels: bug
