### ISSUE TITLE
Cannot add primary key of ObjectId type in migration

### ISSUE THREAD

**Issue by fredpedersen** [realm/realm-java#7189] opened 2020-11-09 20:50 UTC
#### Goal
Migration to a primary key which is an ObjectId

#### Actual Results
schema.addPrimaryKey("_id");

Where _id is an ObjectId results in:

Illegal Argument: This field cannot be indexed - Only String/byte/short/int/long/boolean/Date fields are supported.

#### Version of Realm and tooling

Realm version(s): 10.0.1

Realm Sync feature enabled: Yes

**Comment by edualonso** [comment] 2020-11-11 09:32
Hi @fredpedersen. Thanks for the bug report. We have got a fix for this crash and will be shipped in v10.0.2.

**Comment by edualonso** [comment] 2020-11-12 12:40
We have merged the fix. It will be available for 10.0.2.

Closing ticket, please reopen if the issue is still present.

**Closed by edualonso** 2020-11-12 12:40 UTC
Labels: O-Community, T-Bug-Crash
