### ISSUE TITLE
What's the "INSTALL_FAILED_DEXOPT" means when upgrade to 1.1.0?

### ISSUE THREAD

**Issue by HsiangLeekwok** [realm/realm-java#3124] opened 2016-07-05 04:45 UTC
Hi, guys:
I got an issue when upgrade realm from 1.0.1 to 1.1.0 and choose run button in Android Studio 2.1.2(app running perfect with 1.0.1):

> Installation failed since the device possibly has stale dexed jars that don't match the current version(dexopt error).
> In order to proceed, you have to uninstall the existing application.

errors in AS run history:

> Failure [INSTALL_FAILED_DEXOPT]

After uninstall the existing app, AS ask to uninstall existing app again(the app has already uninstalled), and got another error _DELETE_FAILED_INTERNAL_ERROR_ 

This uninstall dialog appears every time when running app and got the same error _INSTALL_FAILED_DEXOPT_

When I back to realm 1.0.1 and sync the project, the app running perfect.

I have tried to _clean the project_, or _delete all build directory_, or _invalidate caches/restart AS_, but can not fix it.
is there any other advice?
Thanks!
#### Version of Realm and tooling

> Realm version(s): 1.1.0
> Android Studio version: 2.1.2
> Which Android version and device: Samsung Note3, Android 5.0

**Comment by HsiangLeekwok** [comment] 2016-07-05 05:00
![20160705120105](https://cloud.githubusercontent.com/assets/9763167/16574336/5b4f1a7e-42b0-11e6-93b3-078a53fdd890.png)

**Comment by stk1m1** [comment] 2016-07-05 06:23
Hi @HsiangLeekwok,

I believe this might not be Realm specific issue. In case you are facing an issue with upgrading here are few tips I can suggest.

1. Restart your test device and develop machine.
2. Clean project from Android Studio (henceforth AS) (and remove **build** directory if possible).
3. Uninstall the specific projects and delete all its residue with `adb rm -rf /data/data/<package path>` command.
4. In case you have multiple projects installed on your test device, uninstalling all of them.
5. Disable **Insta Run** as well.

Then see if this issue persists.

**Comment by HsiangLeekwok** [comment] 2016-07-05 06:31
Sorry @stk1m1 
I have tried to do all your steps(as i said in my issue), but has not effects.
Thanks!

**Comment by beeender** [comment] 2016-07-05 06:49
internal note: relevant apk can be found at https://secure.helpscout.net/conversation/223136058/5190/?folderId=366141

**Comment by stk1m1** [comment] 2016-07-05 08:29
Hi @HsiangLeekwok 

The apk works fine with me. It asks three permissions and then shows a splash screen. It then moves to login page.

**Comment by beeender** [comment] 2016-07-06 01:18
internal notes: more information(gradle logs,proxy source code) https://secure.helpscout.net/conversation/223218504/5196/?folderId=366141

**Comment by stk1m1** [comment] 2016-07-07 03:58
Hi @HsiangLeekwok

I've sent you a feedback. Could you please check if it works out? We'll keep looking into this. Thanks!

**Comment by HsiangLeekwok** [comment] 2016-07-08 13:44
Hi, @stk1m1 
Sorry to reply you too late.
I have tried to follow your steps and add command line "dex.force.jumbo=true", the error still exist.

**Comment by stk1m1** [comment] 2016-07-09 14:55
@HsiangLeekwok 

We've tested your apk on following devices and they all generated INSTALL_FAILED_DEXOPT.
- Samsung Note 3, Android 5.0
- Samsung Galaxy S4, Android 5.0.1
- Samsung Galaxy S6 edge, Android 5.1.1

On Samsung device with Android 6.0, this issue does not appear. I can only say this is very much a device + version specific issue at this point. We are still looking into it and see what's the root cause of it. Meanwhile, I'd suggest to reduce the field for now. Thanks!

**Comment by HsiangLeekwok** [comment] 2016-07-09 16:04
Thanks!

**Comment by stk1m1** [comment] 2016-07-11 04:51
@HsiangLeekwok 

Could you please make a small sample project (with code) that produces the same error you've experienced? We are trying to generate same issue with our examples but it has not been successful. I'd really appreciate it.

**Comment by HsiangLeekwok** [comment] 2016-07-13 06:11
Hi, @stk1m1 
This is the sample project:
https://github.com/HsiangLeekwok/Realm110FailedDexopt

**Comment by stk1m1** [comment] 2016-07-14 09:59
@HsiangLeekwok 

Thanks for the sample. We'll look into it!

**Comment by stk1m1** [comment] 2016-07-19 06:29
I'm moving this to P2 as it requires more investigation.

**Comment by stk1m1** [comment] 2016-07-28 19:49
**Internal Note**

dex2oat issue testing is summarized [here](https://github.com/realm/realm-wiki/wiki/Android-dex2oat-compilation-process) in wiki.

**Comment by AmirMehr** [comment] 2017-11-03 15:41
what happened at last? I have same issue, What is the solution?

**Comment by HsiangLeekwok** [comment] 2017-11-05 00:50
@AmirMehr 
Let your properties count less than 64(or 62) would be ok(Samsung devices).

**Comment by cmelchior** [comment] 2018-04-05 08:10
Closing as this is a device specific issue, that can only be solved by reducing the number of properties in the class.

**Closed by cmelchior** 2018-04-05 08:10 UTC
Labels: T:Bug-Crash

**Comment by thanhnhutkmt** [comment] 2018-09-06 14:01
defaultConfig {
        applicationId "software.nhut.personalutilitiesforlife"
        minSdkVersion 16
        targetSdkVersion 22//17==========================> set this number less then or equal to the version of Android OS on devices might help
        versionCode 5
        versionName "1.26"
        // Enabling multidex support.
        multiDexEnabled true
    }

**Comment by Praveenvermatech** [comment] 2019-03-06 11:04
I saw how much space the emulator had and was almost nothing so I deleted some apps and with this, my problem was resolved.!!

**Comment by Zhuinden** [comment] 2019-03-06 11:31
Ah yeah you can actually change the amount of space available for the poor Emulator device in the Emulator settings. It starts out with 800 MB I think which is maxed out by *absolutely nothing*.

**Comment by kzotin** [comment] 2020-04-29 14:51
> dex2oat issue testing is summarized [here](https://github.com/realm/realm-wiki/wiki/Android-dex2oat-compilation-process) in wiki.

Hi @stk1m1 we're having the same issue with Android 5.0 devices and Kotlin coroutines update.

Could you please share dex2oat investigation? The link is not working anymore...

**Comment by xxrlzzz** [comment] 2021-06-10 12:56
> > **Internal Note**
> > dex2oat issue testing is summarized [here](https://github.com/realm/realm-wiki/wiki/Android-dex2oat-compilation-process) in wiki.
> 
> Hi @stk1m1 I am also seeing this issue happen on a few of my devices, and the link you posted does not work anymore. Can you please share?

same happens to me, did you find any solution ?

**Comment by dustinmcafee** [comment] 2021-06-10 14:38
> > > **Internal Note**
> > > dex2oat issue testing is summarized [here](https://github.com/realm/realm-wiki/wiki/Android-dex2oat-compilation-process) in wiki.
> > 
> > 
> > Hi @stk1m1 I am also seeing this issue happen on a few of my devices, and the link you posted does not work anymore. Can you please share?
> 
> same happens to me, did you find any solution ?

Only solution I found was to either upgrade your Android OS to 5.1 or above, or to comb through your project and make sure there are no classes with over 61 member variables. It seems the large amount of member variables is not compatible with the installation on an Android 5.0 device.
