### ISSUE TITLE
not compatible with aspectj

### ISSUE THREAD

**Issue by rfrost77** [realm/realm-java#1869] opened 2015-12-02 07:56 UTC
I applied aspectj for logging by AOP but It occurs build error with realm.
Below is error message.

```
Error:Execution failed for task ':app:compileDebugAspectj'.
> Internal compiler error: java.lang.NullPointerException at io.realm.processor.ModuleMetaData.getClassMetaDataFromModule(ModuleMetaData.java:120)
```

I tested it in a new project which set only aspectj and realm.
Plugin for aspectj with android gradle I'm using is below.

https://github.com/uPhyca/gradle-android-aspectj-plugin

Here is my versions for your information.

Android studio : 2.0 preview
Gradle : 2.9
Android Gradle Tools : 2.0.0 alpha1
Realm : 0.85.1
Aspectj : 1.8.7
Aspectj plugin : 0.9.14

**Comment by zaki50** [comment] 2015-12-02 08:18
Hi @rfrost77 

Thank you for reporting.
I'll try to reproduce this.

**Comment by zaki50** [comment] 2015-12-04 09:03
I'm sorry to have kept you waiting.

I tried this with my usual project and got following error.

```
:app:compileDebugAspectj
cannot generate view binders java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    android/databinding/tool/ExpressionVisitor.visitStringLiteral(Landroid/databinding/parser/BindingExpressionParser$StringLiteralContext;)Landroid/databinding/tool/expr/Expr; @2: invokespecial
  Reason:
    Type 'android/databinding/parser/BindingExpressionParser$StringLiteralContext' (current frame, stack[1]) is not assignable to 'com/google/repacked/antlr/v4/runtime/ParserRuleContext'
```

It's because my project uses DataBindings and there seems to be another problems.
I'll try again without DataBindings.

**Comment by zaki50** [comment] 2015-12-08 08:39
I couldn't reproduce this issue.

I set up my project with Realm Java 0.85.1 and AspectJ plugin.
Then I made a following Activity.

That works fine.
```
package com.example.zaki.myapplication;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;

import com.example.zaki.myapplication.model.User;

import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;

import io.realm.Realm;
import io.realm.RealmConfiguration;

@Aspect
public class MainActivity extends AppCompatActivity {

    @Before("execution(void com.example.zaki.myapplication.MainActivity.onCreate(Bundle))")
    public void printLog() {
        Log.d("AJLOG", "log by AspectJ");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Realm.setDefaultConfiguration(new RealmConfiguration.Builder(this).deleteRealmIfMigrationNeeded().build());
        final Realm realm = Realm.getDefaultInstance();
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                final User user = new User();
                user.setName("John" + realm.where(User.class).findAll().size());
                user.setAge(123);
                realm.copyToRealm(user);
            }
        });
    }
}
```

Can you provide a sample project which reproduce this issue?

**Comment by rfrost77** [comment] 2015-12-11 08:01
We are now doing without aspectj. Later, I'll reproduce the issue and show you. Thanks.

**Comment by zaki50** [comment] 2015-12-11 08:11
I attached the archive of my project which is working with Realm and AspectJ.

I hope this will help.

[issue_1869.zip](https://github.com/realm/realm-java/files/59131/issue_1869.zip)

**Comment by zaki50** [comment] 2015-12-11 08:14
I'll close this issue. But if you'll have any question or problem, feel free to reopen this!

**Closed by zaki50** 2015-12-11 08:14 UTC
Labels: Help, Pending
