### ISSUE TITLE
Realm repeating lines on realm adapter?

### ISSUE THREAD

**Issue by gelbertgel** [realm/realm-java#6018] opened 2018-06-14 07:32 UTC
I used realm last version : 5.3.0

I have customAdapter which extends of realm adapter. It shows the data repeatedly even if I didn't call.

I have `Player` model that has `Person` and `Header` types. I want to show those who play with volleyball and don't play.

> My model :

    @RealmClass
    public class Player extends RealmObject {
    
        private Person person;
    
        @Index
        private String indexedName = "";
    
        public static final int VOLLEYBALL_PLAYER = 0;
        public static final int OTHER_PLAYER = 1;
    }

> PlayerCRUD:

    void getPersonsAndHeaders(){
                    RealmResults<Person> allPersons = 
                 mRealm.where(Person.class)
                .sort("indexedName", Sort.ASCENDING)
                .distinct("indexedName")
                            .findAll();
    
                    RealmResults<Person> volleyballPlayers = allPersons
                            .where()
                            .isNotNull("volleyballPlayers.person.id")
                            .sort("nameLowerCase")
                            .distinct("nameLowerCase")
                            .findAll();
    
                    RealmResults<Person> normalPlayers = allPersons
                            .where() 
                            .not()
                            .isNotNull("volleyballPlayers.person.id")                                                           
                            .sort("nameLowerCase")
                            .distinct("nameLowerCase")
                            .findAll();
    }

> PlayerListAdapter:

    public class PlayerListAdapter extends  PlayerRealmRecyclerViewAdapter<Player, RecyclerView.ViewHolder> {
   
        private String TAG = PlayerListAdapter.class.getSimpleName();
    
        public PlayerListAdapter(OrderedRealmCollection<Player> data,
                                @Nullable ItemClickListener clickListener) {
    
            super(data);
    
            this.clickListener = clickListener;
            this.realm = openRealm();
    
            setHasStableIds(true);
        }
    
         public Realm openRealm() {
    
            Realm realm = getRealmController().getRealm();
    
            if (realm.isClosed()) {
                realm = Realm.getDefaultInstance();
            }
    
            return realm;
        }
    
        public static class PersonViewHolder extends RecyclerView.ViewHolder {
            protected TextView textView;
    
            PersonViewHolder(View itemView) {
                super(itemView);
                textView = ViewUtil.findById(itemView, R.id.person);
            }
    
            public void setText(CharSequence text) {
                textView.setText(text);
            }
        }
    
        public static class HeaderViewHolder extends RecyclerView.ViewHolder {
            protected TextView textView;
    
            HeaderViewHolder(View itemView) {
                super(itemView);
                textView = ViewUtil.findById(itemView, R.id.header);
            }
    
            public void setText(CharSequence text) {
                textView.setText(text);
            }
        }
    
        @Override
        public PersonViewHolder onCreatePersonViewHolder(ViewGroup parent, int viewType) {
    
            final V itemView = ViewUtil.inflate(LayoutInflater.from(parent.getContext()), parent, getLayoutForViewType(viewType));
    
            return new PersonViewHolder(itemView);
        }
    
        @Override
        public HeaderViewHolder onCreateHeaderViewHolder(ViewGroup parent, int viewType) {
    
            View itemView = ViewUtil.inflate(LayoutInflater.from(parent.getContext()), parent, getLayoutForViewType(viewType));
    
            itemView.setOnClickListener(null);
            itemView.setOnLongClickListener(null);
    
            return new HeaderViewHolder(itemView);
        }
    
        @Override
        public void onBindPersonViewHolder(RecyclerView.ViewHolder viewHolder, @NonNull Person person) {
    
            Mylog.i(TAG, "onBindPersonViewHolder");
    
            PersonViewHolder personViewHolder = (PersonViewHolder) viewHolder;
            personViewHolder.getView().bind(person, batchSelected, getRealm());
    
        }
    
        @Override
        public void onBindHeaderHolder(RecyclerView.ViewHolder viewHolder, String indexedName) {
    
            Mylog.i(TAG, "onBindHeaderHolder");
    
            HeaderViewHolder headerViewHolder = (HeaderViewHolder) viewHolder;
    
            if (indexedName == null) {
                return;
            }
    
            String header = indexedName.equals("" + VOLLEYBALL_PLAYERS) ? context.getString(R.string.volleyball_players) : context.getString(R.string.other_users);
            headerViewHolder.setText(header);
    
        }
    
        private void initializeAdapter() {
    
            updateData(new PlayerQueries().getAllPlayers(getRealm()));
        }
    
        public boolean realmControl() {
    
            if (realm == null || realm.isClosed()) {
    
                realm = openRealm();
                initializeAdapter();
    
                return true;
            } else {
                return false;
            }
        }
    }

    

> PlayerRealmRecyclerViewAdapter:

    abstract class PlayerRealmRecyclerViewAdapter<T extends Player, VH extends RecyclerView.ViewHolder>
            extends RealmRecyclerViewAdapter<Player, VH> {
    
        protected Context context;
        protected Realm realm;
    
        private final OrderedRealmCollectionChangeListener listener;
    
        private static final int INVALID_TYPE = 4;
        private static final int PERSON_TYPE = 5;
        private static final int HEADER_TYPE = 6;
    
        private String TAG = PlayerRealmRecyclerViewAdapter.class.getSimpleName();
    
        PlayerRealmRecyclerViewAdapter(@Nullable OrderedRealmCollection<T> data) {
    
            super((OrderedRealmCollection<Player>) data, true, true);
    
            if (data != null && !data.isManaged())
                throw new IllegalStateException("Only use this adapter with managed RealmCollection, " +
                        "for un-managed lists you can just use the BaseRecyclerViewAdapter");
    
            this.context = getContext();
            this.listener = createListener();
        }
    
        private OrderedRealmCollectionChangeListener createListener() {
            return new OrderedRealmCollectionChangeListener() {
                @Override
                public void onChange(@NonNull Object collection, @NonNull OrderedCollectionChangeSet changeSet) {
    
                    OrderedCollectionChangeSet.Range[] insertions = changeSet.getInsertionRanges();
                    if (insertions.length > 0) {
                        notifyDataSetChanged();
                    }
                }
            };
        }
    
        @LayoutRes
        int getLayoutForViewType(int viewType) {
    
            switch (viewType) {
                case PERSON_TYPE:
                    return R.layout.person_list_item;
                case HEADER_TYPE:
                    return R.layout.header_list_item;
                default:
                    throw new IllegalArgumentException("unsupported item view type given to ConversationAdapter");
            }
        }
    
        @Override
        public final void onBindViewHolder(@NonNull VH viewHolder, int position) {
    
            Mylog.i(TAG, " onBindViewHolder position : " + position);
    
            Player player = getItem(position);
    
            if (player != null && player.isValid()) {
    
                if (player.getPerson() != null) {
                    onBindPersonViewHolder(viewHolder, player.getPerson());
    
                } else if (player.getIndexedName() != null) {
                    onBindHeaderHolder(viewHolder, player.getIndexedName());
                }
            }
        }
    
        public abstract void onBindPersonViewHolder(VH viewHolder, @NonNull Person person);
    
        public abstract void onBindHeaderHolder(VH viewHolder, String indexedNumber);
    
        @NonNull
        @Override
        public final VH onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
    
            Mylog.i(TAG, " onCreateViewHolder");
    
            switch (viewType) {
                case PERSON_TYPE:
                    return onCreatePersonViewHolder(parent, viewType);
                case HEADER_TYPE:
                    return onCreateHeaderViewHolder(parent, viewType);
                default:
                    throw new IllegalArgumentException("unsupported item view type given to Adapter");
            }
        }
    
        @Override
        public final int getItemViewType(int position) {
    
            Mylog.i(TAG, " getItemViewType position : " + position);
    
            Player player = getItem(position);
    
            if (player != null && player.isValid()) {
    
                if (player.getPerson() != null) {
                    return PERSON_TYPE;
    
                } else if (player.getIndexedName() != null) {
                    return HEADER_TYPE;
    
                }
            }
    
            new PlayerCRUD().deletePlayer(player, getRealm());
            notifyDataSetChanged();
    
            return INVALID_TYPE;
        }
    
        public abstract VH onCreatePersonViewHolder(ViewGroup parent, int viewType);
    
        public abstract VH onCreateHeaderViewHolder(ViewGroup parent, int viewType);
    
        public Realm getRealm() {
    
            if (realm == null || realm.isClosed()) {
                realm = openRealm();
            }
    
            return realm;
        }
    
    
        @Override
        public void onAttachedToRecyclerView(final RecyclerView recyclerView) {
            super.onAttachedToRecyclerView(recyclerView);
            if (isDataValid()) {
                //noinspection ConstantConditions
                addListener((OrderedRealmCollection<T>) getData());
            }
        }
    
        @Override
        public void onDetachedFromRecyclerView(final RecyclerView recyclerView) {
            super.onDetachedFromRecyclerView(recyclerView);
            if (isDataValid()) {
                //noinspection ConstantConditions
                removeListener((OrderedRealmCollection<T>) getData());
            }
        }
    
        private void addListener(@NonNull OrderedRealmCollection<T> data) {
            if (data instanceof RealmResults) {
                RealmResults<T> results = (RealmResults<T>) data;
                //noinspection unchecked
                results.addChangeListener(listener);
            } else if (data instanceof RealmList) {
                RealmList<T> list = (RealmList<T>) data;
                //noinspection unchecked
                list.addChangeListener(listener);
            } else {
                throw new IllegalArgumentException("RealmCollection not supported: " + data.getClass());
            }
        }
    
        private void removeListener(@NonNull OrderedRealmCollection<T> data) {
            if (data instanceof RealmResults) {
                RealmResults<T> results = (RealmResults<T>) data;
                //noinspection unchecked
                results.removeChangeListener(listener);
            } else if (data instanceof RealmList) {
                RealmList<T> list = (RealmList<T>) data;
                //noinspection unchecked
                list.removeChangeListener(listener);
            } else {
                throw new IllegalArgumentException("RealmCollection not supported: " + data.getClass());
            }
        }
    
        private boolean isDataValid() {
            return getData() != null && getData().isValid();
        }
    
        @Override
        public long getItemId(final int index) {
            return index;
        }

I don't want to repeating lines in my list. List look like this:
[![enter image description here][1]][1]

How can I do that?

  [1]: https://i.stack.imgur.com/vSkLm.png

**Comment by cmelchior** [comment] 2018-06-29 08:05
Duplicate of https://github.com/realm/realm-android-adapters/issues/149. Closing

**Closed by cmelchior** 2018-06-29 08:05 UTC
Labels: O:User
