### ISSUE TITLE
Bad Version exception. (Please stop send error to internal handler.)

### ISSUE THREAD

**Issue by rfrost77** [realm/realm-java#2391] opened 2016-03-05 20:15 UTC
Bad version exception still happens and you seem don't have solution about this.

It happens in findAllAsync or findAllSortedAsync.

So, I do try-catch to all usage of the methods.

But bad version exception fires again and kill app cause the methods don't allow send exception to us, just kill app! (why???)

We release our app with realm recently and bad version exception is most number of crash ever, very ever.

We have more than 1 million users in our app, and it is now giving users very bad experience.

I think you should fix it or for temporal solution, do not just throw exception in your sdk to kill app.
(If you can't, we have to change DB to another... But I don't want it and I think you too.)

One more, it is very bad exception and we get some upset about you haven't solved this bug even though this issue happened at Dec, 2015.

Please look at this issue seriously.

**Comment by cmelchior** [comment] 2016-03-05 20:21
Hi @rfrost77 
We do take this problem very seriously, but currently we haven't been able to reproduce it. So it is mostly guesswork unfortunately. If you have a way to reproduce it, we would be very interested in seeing a project. You can also share it privately with help@realm.io. We do have some ideas about the root cause though, which we hope to have a fix for as part of the next release.

A temporal solution would be to either switch back to just `findAll` or `findAllSorted`. If you don't have large dataset that would be just as efficient as doing async queries.

**Comment by cmelchior** [comment] 2016-03-05 20:24
We have a potential fix for the root cause of this merged to Realm Core in https://github.com/realm/realm-core/pull/1534. We will try to get it released and merged into Realm Android as fast as possible.

**Comment by rfrost77** [comment] 2016-03-06 14:53
I also really want to know how to reproduce it, but I can't too. At start of our app, we run 3 thread async work, so it very hard to know where and when the situation happens. If I find it, I would be pleasure to give you the case for the solution.

I alternate all async methods to sync methods as your advice by a temporal solution. But, for some users who have many data set, it took about 0.5sec, that causes users feel stuck of UI while realm is loading. So, I hope the solution will be merged ASAP.

**Comment by kneth** [comment] 2016-03-09 13:21
We have merged #2397, and we hope to be able to do a release very soon.

**Comment by cmelchior** [comment] 2016-03-15 19:58
@rfrost77 0.88.2 has been released with a fix for this.

**Closed by cmelchior** 2016-03-15 19:58 UTC
Labels: S:In Progress, T:Bug-Crash
