### ISSUE TITLE
Unrecoverable error. mmap() failed: Out of memory

### ISSUE THREAD

**Issue by zayfal** [realm/realm-java#7083] opened 2020-09-06 11:28 UTC
#### Goal
Having lot of crashes in production while users starting the app. Usually once this crash occurs, the app require reinstalling, loosing any data not "saved" to server. The app is very data intensive and there are lot of data getting "written" on background.

The goal is to not get the crash in the first place, or to be able to repair data (check below about compact) if this occurs. 

#### Actual Results
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 738197504 offset: 0 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:332)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
       at io.realm.Realm.getInstance(Realm.java:428)

#### Steps & Code to Reproduce
We were able to reproduce in an external app sample we create on emulator (Emulator is assigned initially 1.5GB of RAM space)
a- the app would insert around 1.25GB of data to realm
b- we then decrease RAM allocated to emulator down to 1GB
c- Now, running the app again would give same crash as above.

* It seems realm works by putting all "data" into RAM on initialization, so obviously compacting realm will not work once the file become large to exceed free RAM, since compacting realm appears to require opening realm and moving data to RAM first.

#### Version of Realm and tooling

Realm version(s): 6.0.0

Realm Sync feature enabled: No

Android Studio version: 4.0.1

Android Build Tools version: 28.0.3

Gradle version: 5.4.1

Which Android version and device(s): All android version. For devices, wide range of tablets: Galaxy Tab S2, Galaxy Tab A (2017),  Galaxy Tab A (2016), Galaxy Tab A...

**Comment by clementetb** [comment] 2020-09-08 17:33
Today we released Realm Java version 7.0.4, it addresses several memory issues. Would you mind checking if you can reproduce this issue on it?

**Comment by zayfal** [comment] 2020-09-11 09:13
There are 2 parts of the issue:
1. the 1st part is the reason of the realm file becoming very large, this was fixed in 7.0.x; basically what was happening a 5MB string was taking around 80MB size when just inserted, I am not sure which realm core issue fix this ?
2. The second part is that once the file becoming big, realm will crash on opening it, as my testing goes, it seems like realm needs to put the whole file in RAM to open it (Am I wrong ?)

So the main issue, is there is no way to compact a realm file once it become large on device, and it becomes large for many reasons other than 1.

**Comment by finnschiermer** [comment] 2020-09-18 07:35
We memory map the entire database. This means that we need to be able to allocate virtual address space for the entire file when we open it. So technically, you're not running out of RAM, it's the allocation of virtual address space that fails.

For realm-core versions before v10 we need to memory map the entire file as a *contiguous* range of virtual addresses when we open it. This is what fails in your case. So you are perhaps not running out of RAM, and not running out of virtual address space either, it's just that there is no room in the apps virtual address space for a 704 Mb *contiguous* mapping. This can easily happen on a 32 bit device.

The requirement to have a contiguous memory mapping is lifted in realm-core v10. With v10, the mapping may be non-contiguous (multiple 64 Mb ranges), which adds some flexibility to the allocation process. But we still need to map the entire file.

It is a long term goal to also lift the requirement that *everything* has to be memory mapped. But we have not been able to prioritize this work yet.

**Comment by zayfal** [comment] 2020-09-20 17:40
> t

This clarify point 2. But also this means that the only "approach" to tackle issues would be to "force" compact "periodically, it would be very hard to achieve this for apps that heavy in data usage; like we need to wait for any data access on background thread to finish on a blocking HUD, then kind do my compact after closing any opened realm.

**Comment by bmunkholm** [comment] 2020-09-21 11:09
@zayfal Could you also have options to model your data differently? Do you e.g. store any bigger binary data?
Could you split the data perhaps?

**Comment by zayfal** [comment] 2020-09-21 12:08
> @zayfal Could you also have options to model your data differently? Do you e.g. store any bigger binary data?
> Could you split the data perhaps?

We have related data in the database, thus this will be very hard. The thing the file is approximitaly 10-15MB compacted, mostly the data is string based, no "binary data" is included. The issue is that the same 15MB file will stretch to 600MB in rare case, when lot of 5MB insertion occur (as explained in 1. https://github.com/realm/realm-java/issues/7083#issuecomment-690975159)

I guess, this will be minimized when we upgrade realm as @finnschiermer indicated, but also I think I am missing something and we need to monitor usage of RAM on client to get what exactly is going on.

I was trying mainly to check if there is a way to "repair" these large files and compact them without opening them first, but it looks this isn't possible, right ?

**Comment by cmelchior** [comment] 2020-09-21 12:43
If your Realm file can be reduced that much in size from compacting it sounds like you are holding on to Realm versions for way to long.

I would recommend reading: https://realm.io/docs/java/latest/#realm-instance-lifecycle and https://realm.io/docs/java/latest/#closing-realms

In Realm Java 7.0.6 there is also a new method on RealmConfiguration called `maxNumberOfActiveVersions`. Try enabling that with a relatively small number like 8 or 16. If you trigger the assertion from that it could point to you keeping too many versions alive.

**Comment by edualonso** [comment] 2020-11-10 13:29
Closing due to inactivity. If the issue still persists please reopen.

**Closed by edualonso** 2020-11-10 13:29 UTC
Labels: O-Community
