### ISSUE TITLE
Support com.android.feature plugin

### ISSUE THREAD

**Issue by ibrahimkarahan** [realm/realm-java#4820] opened 2017-06-20 15:24 UTC
Android Studio 3.0 introduced com.android.feature plugin. Because Realm explicitly checks for the existence of com.android.application or com.android.library plugins, applying realm-android in a feature causes an exception.

See the following line at Realm.groovy:

https://github.com/realm/realm-java/blob/7dbacb438f8f1130155eacf06347fce703c8f1a8/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy#L34

```groovy
void apply(Project project) {
    // Make sure the project is either an Android application or library
    def isAndroidApp = project.plugins.withType(AppPlugin)
    def isAndroidLib = project.plugins.withType(LibraryPlugin)
    if (!isAndroidApp && !isAndroidLib) {
        throw new GradleException("'com.android.application' or 'com.android.library' plugin required.")
}
```

**Comment by beeender** [comment] 2017-06-21 03:21
And we need to verify how does the NDK work with instant app~

**Comment by Zhuinden** [comment] 2017-06-21 07:43
And how to fit in the 4 MB APK size limit

**Comment by Zhuinden** [comment] 2017-09-01 19:47
No luck with this one yet, huh? Apparently people are looking for it, see https://stackoverflow.com/questions/45995593/kotlin-use-realm-module-in-android?noredirect=1#comment78974747_45995593

**Comment by cmelchior** [comment] 2017-09-01 19:49
Also according to this answer https://stackoverflow.com/questions/45878257/instant-app-and-splits-abi Instant Apps do not support ABI splits yet, which would also be a requirement to get below the 4MB limit.

**Comment by phillipao** [comment] 2017-10-17 15:38
ABI splits are now supported: https://android-developers.googleblog.com/2017/10/introducing-android-instant-apps-sdk-11.html?m=1. We're happy to offer any support in using the feature.

**Comment by Zhuinden** [comment] 2017-11-20 10:11
Beep boop any luck?

**Comment by avlasov1** [comment] 2018-01-06 06:14
Has this been resolved, or at least being worked on? Wondering if I should just give up trying to integrate into my new instant app.

**Comment by Eido95** [comment] 2018-10-15 12:44
7 months later... any news about this issue?

It's currently not possible to use Realm database on another module besides android app module right?

**Comment by Zhuinden** [comment] 2018-10-15 12:57
the only way is with App Bundle, but i don't think that is compatible with Instant Apps?

**Comment by Zhuinden** [comment] 2019-04-09 22:17
Good news guys, it's deprecated: https://android-developers.googleblog.com/2019/04/google-play-instant-feature-plugin.html

**Comment by chadschultz** [comment] 2019-09-17 18:21
From reading the thread, it sounds like Realm is NOT compatible with Android App Bundles in that it cannot be used in a feature module. Anyone wanting to use Android App Bundles has the following options:

- Don't use Realm
- Use only one module (the base module) and have zero feature modules
- Have all code that interacts with Realm be in the base module. Feature modules cannot use Realm at all. (The repository pattern may help with this.)

And it sounds like the cause of this is a check in Realm.groovy enforcing the library/application limitation, which needs to be updated since Android App Bundles came out in early 2018. Is this correct? Or am I missing something?

**Comment by cmelchior** [comment] 2019-11-27 21:22
Closing since Instant Apps have been deprecated in favor of App Bundle

**Closed** 2019-11-27 21:24 UTC
Labels: O-Community, Pipeline-Idea-Backlog, T-Feature
