### ISSUE TITLE
Android Studio throws a null pointer on incremental builds pointing back to Realm

### ISSUE THREAD

**Issue by tfrysinger** [realm/realm-java#7473] opened 2021-05-14 13:51 UTC
I have documented the problem on [this SO entry](https://stackoverflow.com/questions/67438562/android-studio-4-2-throws-a-null-pointer-exception-on-incremental-builds).

Essentially, an incremental build will fail (not always, maybe two-thirds of the time), then a subsequent build will succeed. Complete builds always succeed.

Btw - I have reproduced this after updating to Android Studio 4.2.1 and Realm 10.5.0

**Comment by cmelchior** [comment] 2021-06-30 08:55
Hi @tfrysinger Sorry for the late reply. This does indeed look like a bug on our end, I would suspect the problem to be intermittent though as it should only happen when iterating on Realm model classes. But obviously, it should still work as expected. We will investigate further.

**Comment by tfrysinger** [comment] 2021-06-30 14:08
Hi - it seems to occur not only when model classes are updated, but any class that depends on them. If I only change files that do not reference or indirectly reference Realm at all, then the build always succeeds.

Also still a problem with 10.6

**Comment by uwine-fr** [comment] 2021-07-01 08:17
On our side, it breaks exactly every two builds, even when changing a class not depending on realm at all.

**Comment by uwine-fr** [comment] 2021-07-01 08:54
Please find attached a minimal sample project reproducing the issue. 

[TestRealm.zip](https://github.com/realm/realm-java/files/6746836/TestRealm.zip)

**Comment by tfrysinger** [comment] 2021-07-01 13:03
I can confirm that in the TestRealm sample app, I changed the Log.d line in MainActivity and did a make (Ctrl-F9), which succeeded, then changed it back to the original Log.d line and did a new make and the build broke in exactly the same way it breaks for me in my project.
![realm_error](https://user-images.githubusercontent.com/11542040/124128814-5db47d00-da3a-11eb-8046-2dc037219f10.png)

**Comment by tfrysinger** [comment] 2021-07-03 20:28
Realm team - I notice that nobody is yet assigned to this. It is becoming a real problem. With AS 4.2.2, now sometimes the build will appear to succeed, but in fact the build has not completed accurately (resource IDs are being incorrectly assigned, particularly with strings). A full build always corrects this.

**Comment by nguyencongbinh** [comment] 2021-07-19 03:16
I got the same issue. realm 10.6.1

**Comment by rorbech** [comment] 2021-07-19 13:04
The incremental compilation triggered by the "Apply change ..." action when there is no update to the model classes will consider the previously internally generated _default module_ as a user supplied `@RealmModule`. The NPE is caused by this automatically generated module not to have any annotation arguments. 

The reason why this is always working for the build following the specific build error is that the build error itself is triggering the full rebuild:
```
Task ':app:compileDebugJavaWithJavac' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':app:compileDebugJavaWithJavac'.
```

So, I guess the quick resolution is to not use the "Apply changes ..." actions to build your app. 

I have included a check against the specific NPE in #7524, but I am a bit uncertain if this is sufficient to make the "Apply change ..." work. Maybe the module should be filter out in some other way. @tfrysinger do you care sharing a bit more details on your observation:

> With AS 4.2.2, now sometimes the build will appear to succeed, but in fact the build has not completed accurately (resource IDs are being incorrectly assigned, particularly with strings). A full build always corrects this.

Ideally as steps to reproduce. Maybe in the already references `TestRealm.zip`-project.

**Comment by tfrysinger** [comment] 2021-07-19 17:28
I tried to re-create the issues I've seen with resource IDs not being
correctly assigned using the test project, and cannot get that one to fail.
It absolutely has happened in my main project though. Perhaps there are
other issues associated with that one that are not in the small sample,
like being multi-module, or deployed as an .aab file, or what-not.

When I have seen the problem occur, it is after I do an incremental build
which appears to succeed, but in fact has not (the resource IDs are
scrambled in the strings.xml file). But every change I am making in the
small test project results in the known NPE. The only way the build
succeeds on that one after any sort of change (change in resource file,
source file) is to do the incremental build again (because of the behavior
noted above) or a rebuild.

Tad

**Comment by rorbech** [comment] 2021-07-20 07:45
@tfrysinger Thanks. Issues with resource IDs doesn't sound like something related to our plugin, so I will just try to push my update through the pipeline. At least it seems like various updates (outside/inside model, etc.) does the right thing now.

**Comment by tfrysinger** [comment] 2021-08-01 21:09
@rorbech - thanks for the merge, I am not seeing the same problem I had been, which is great. However, I still get two problems from time to time - 1) Android Studio thinks that it can't delete the build directory when I request a full build. Doing a full build the second time always works (and in fact the build directory was deleted from the first action). Second, when I do an incremental build, it appears to succeed but sometimes it is clear that various resource IDs have gotten scrambled. 

Does this ring any bells? I'm sure you will ask for a reproducible example, which is proving tough. I am happy to share time with you or someone else at Realm in a live session with the project where I am seeing this in order to help nail down what may be causing it.

**Comment by rorbech** [comment] 2021-08-02 07:09
@tfrysinger This doesn't sound related to the realm plugin so I will close this issue. If you think that these other observations relates to our plugin, please create a new issue and put the indications there.

**Closed by rorbech** 2021-08-02 07:09 UTC
Labels: O-Community
