### ISSUE TITLE
RealmResults<Foo> change listener not called after adding new Foo objects to Realm.

### ISSUE THREAD

**Issue by Kistamushken** [realm/realm-java#1802] opened 2015-11-19 14:03 UTC
Hey, guys, currently I am enjoying 0.84.2 version of Realm. And I must say, RealmResults ChangeListener, is kinda confusing. 

Let's take RealmResults<Foo> for example. It works as expected whenever:
1) I do async find from Realm(listener gets notified when the query completes)
2) I update existing object in Foo.class table

But it doesn't get called after I put new new objects of type Foo to Realm.

As your documentation states:
"This listener will be called every time the RealmResults is updated to reflect the latest changes in the Realm (usually after a commit)".

So is it a bug or I am missing something?

Thanks in advance.

**Comment by nhachicha** [comment] 2015-11-19 23:51
Hi @Kistamushken 
I tried to write a unit test according to your scenario, but couldn't reproduce your issue

```java
public void testIssue1802() throws InterruptedException {
        final AtomicInteger numberOfCallbackInvocation = new AtomicInteger(0);
        final CountDownLatch signalTestFinished = new CountDownLatch(1);

        final HandlerThread handlerThread = new HandlerThread("handlerThread");
        handlerThread.start();
        final Handler handler = new Handler(handlerThread.getLooper());

        handler.post(new Runnable() {
            @Override
            public void run() {
                final Realm realm = Realm.getInstance(getContext());
                realm.beginTransaction();
                final Dog dog = realm.createObject(Dog.class);
                realm.commitTransaction();

                RealmResults<Dog> dogs = realm.where(Dog.class).findAllAsync();
                dogs.addChangeListener(new RealmChangeListener() {
                    @Override
                    public void onChange() {
                        if (numberOfCallbackInvocation.incrementAndGet() == 3) {
                            signalTestFinished.countDown();
                        }
                    }
                });

                // update existing RealmObject should re-run the query
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        realm.beginTransaction();
                        dog.setName("Akamaru");
                        realm.commitTransaction();
                    }
                }, 16);

                // adding a new RealmObject should re-run the query
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        realm.beginTransaction();
                        realm.createObject(Dog.class);
                        realm.commitTransaction();
                    }
                }, 32);
            }
        });

        assertTrue(signalTestFinished.await(7, TimeUnit.SECONDS));
    }
```
Does your query involve a link? we do have an existing issue #1717 regarding async query with link

Cheers,

**Comment by Kistamushken** [comment] 2015-11-22 13:17
Yep, seems, like it's link issue. Give me time till tomorrow, I will test everything on 0.85 version, and if it's okay I'll let you know.

**Comment by kneth** [comment] 2015-11-23 08:03
@kishikawakatsumi thanks - looking forward to your report ;-)

**Comment by Kistamushken** [comment] 2015-11-23 10:36
Hey guys, I've created small app to test things out. It uses 0.85. Still no luck in firing RealmChangleListener when adding object to Realm. Listener fires only when query is completed. Important note is that the query doesn't seem to have any links involved.

You are welcome to check the code here: https://github.com/Kistamushken/RealmTests/blob/master/app/src/main/java/com/kistamushken/realmtests/MainActivity.java

Regards,

**Comment by nhachicha** [comment] 2015-11-23 10:56
Hi @Kistamushken 
thx for the example, this seems to be related to the fact that your listener is created via an anonymous class, even though you're storing `simpleEntities` as a class attribute, your listener will be garbage collected, since we're storing it as a `WeakReference`.

There is a PR to fix this https://github.com/realm/realm-java/pull/1725 this will keep a strong reference to your listeners, but you need to remember to calling 
```java 
realm.removeChangeListener(listener); // to remove a non-anonymous listener
```
or 
```java
realm.removeAllChangeListeners(); // to remove all listeners (including anonymous one)
```
For the time being you can keep a strong reference to your listener to prevent the GC from collecting it. For example by implementing `RealmChangeListener` in `MainActivity`, then calling `removeChangeListener` when you're done (inside a `onDestroy`/`onStop`)

Cheers,

**Comment by nhachicha** [comment] 2015-11-23 13:42
Hi @Kistamushken 
thanks for the example, there is a PR to fix this bug https://github.com/realm/realm-java/pull/1809. 
basically, the current implementation doesn't notify callbacks if you mix in the same thread async queries & commits. 
In the meantime you can do your commits in a worker thread as well.

please note also that in your example you're using an anonymous class to register a listener, the listener will be garbage collected since we don't hold a strong reference to it. This behaviour will change in the next release https://github.com/realm/realm-java/pull/1725, we will start holding a strong reference to your listeners, but it's your responsibility to remove them when you think it's appropriate (inside onDestroy/onStop for example). This will prevent any memory leak.
```java 
realm.removeChangeListener(listener); // to remove a non-anonymous listener
```
or 
```java
realm.removeAllChangeListeners(); // to remove all listeners (including anonymous one)
```
Here is your example with the suggested modifications
```java
public class MainActivity extends AppCompatActivity implements RealmChangeListener {

    Realm realm;
    RealmResults<SimpleEntity> simpleEntities;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        realm = Realm.getInstance(this);

        simpleEntities = realm.where(SimpleEntity.class).findAllAsync();
        simpleEntities.addChangeListener(this);

        SimpleEntity simpleEntity;
        realm.beginTransaction();
        for (int i = 0; i < 20; i++) {
            simpleEntity = new SimpleEntity();
            simpleEntity.setSomeInt(i);
            realm.copyToRealmOrUpdate(simpleEntity);
        }
        realm.commitTransaction();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        realm.removeChangeListener(this);
        realm.close();
    }


    public void addToSimpleResults(View view) {
        if (simpleEntities == null) return;

        final SimpleEntity simpleEntity = new SimpleEntity();
        simpleEntity.setSomeInt(simpleEntities.size());

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.copyToRealmOrUpdate(simpleEntity);
            }
        }, null);
    }

    @Override
    public void onChange() {
        Toast.makeText(MainActivity.this, "SimpleEntity change listener fired, size = " + simpleEntities.size(), Toast.LENGTH_SHORT).show();
    }
}

```

Cheers,

**Comment by Kistamushken** [comment] 2015-11-23 14:19
I see. Thanks for such detailed answer :)

**Comment by kneth** [comment] 2015-11-25 10:17
@Kistamushken May we close the issue?

**Closed** 2015-12-01 11:39 UTC
Labels: Help, Pending

**Comment by Kistamushken** [comment] 2015-12-02 09:45
@kneth Yeah thanks.
