### ISSUE TITLE
Duplicate items in RealmList with sync

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#4159] opened 2017-02-09 07:02 UTC
I'm already aware that the RealmList doesn't give support to avoid duplicate entries, and is up to the creating / modification logic of each case to avoid introducing duplicate elements on a RealmList.
In my application, the first time an user opens a Realm I use the initialData method to populate basic data.
I'm using primarykeys all over the objects.

The problem is when I'm starting to use the Sync mechanism with a Realm Mobile Platform in place.

- Device 1 initialize the realm and it is synchronized on the platform.

- Device 2 initialize the realm again with the basic data that is the same as the one of the Device 1. While (or after, doesn't matter here) it is creating this data it receives the synchronized data that should be the same (I use a mechanism to make sure that the primarykeys are the same every time I generate the basic data), the problem is that all the RealmList of the basic data, have now twice elements (two copies of the same objects).

- Device 1 receive the synchronized data of the Device 2 through the platform and it has now also double elements on the basic data lists (the rest of elements are unique and correctly created)

I don't know what is the best approach here to ensure that the basic data is created / retrieved the first time a device is synchronized with the platform. 
Maybe the conflict resolver for the RealmList content is not the right one as I guess I'm not the only one that have this problem.
Any suggestions?

**Comment by cmelchior** [comment] 2017-02-09 13:45
Yes, the problem is that `RealmList` is just an ordered collection, but doesn't provide Set semantics. We are tracking `Set` as a feature here: #759 

In our RealmTask app we use this workaround for deleting duplicates currently: https://github.com/realm/RealmTasks/blob/master/RealmTasks%20Android/app/src/main/java/io/realm/realmtasks/TaskListActivity.java#L81

**Comment by gpulido** [comment] 2017-02-09 13:58
Thank you for the tip.
I hope that the set could be implemented soon as my basic data have a lot of list, and to traverse all the list checking for duplicates is cumbersome.
Just for be sure, this problem will appear anytime two clients add an element to a one shared list, is there any way to be notified when sync data is being received?
If I add a changelistener, I'm receiving all notifications, local and remote and It is imposible to filter them.
In fact, the finegrainednotification issue (#989) become more important with sync.

**Comment by bmeike** [comment] 2017-02-09 18:26
@gpulido:

> I hope that the set could be implemented soon
Yep.  Working on it!

> this problem will appear anytime two clients add an element to a one shared list
Yes, in your implementation, that is true.  The issue is more general than that, of course.  A single client could add the same initialization data, twice, thrice, or many times, creating duplicate records.  One suggestion is that you consider a design in which initialization data is obtained from the server, not generated on the client.  If it is not generated multiple times, the duplication problem will go away.

> If I add a changeListener, I receive all notifications, local and remote, and It is impossible to filter them.
Yes, that is true.

> Fine-grained Notification, issue (#989), becomes more important with sync
Yes.  We're working on it!

I am going to go ahead and close this ticket.  Please feel absolutely free to re-open it, or to open a new one, if there is more that we can do for you!

**Closed by bmeike** 2017-02-09 18:26 UTC
Labels: S:Review, T:Help

**Comment by gpulido** [comment] 2017-02-10 11:18
@bmeike thank you for the answer.
I have a question regarding this use case.

You suggest  to use an initialization data from the server. However the server is just the Realm Mobile Platform, so I need a "first" client to generate this data to be synchronized. On local realms, I used to  review if there are any data and if not, just create it. 

But now, when a client is first connected to the RMP it doesn't have the realm copy created when he ask if there any data and hence he creates the data without knowing that is being synchronized. 
It would be nice to have any way to know that the client is receiving data and when the local data is completely in sync. This of course doesn't solve the problem of several clients connected at the same time for the first time when the server data is empty. This is an extreme use case that could be managed if the first connection to a sync realm could notify if the realm exist or not. 
a) If it doesn't exist this client knows that is the first client that is accesing such realm (it is the creator of it after all) and can create the data. 
b) If a client connects to a synchronized realm that already has been created, he can assume that the data will appear at some point in the future.
Being said this, the best solution is to have sets and fine-grained notification :) The rest are just workarounds.
Thank you all for your amazing work and support.
