### ISSUE TITLE
querying on RealmResults: unexpected behavior

### ISSUE THREAD

**Issue by grigoryfedorov** [realm/realm-java#2263] opened 2016-02-11 20:39 UTC
Hi! I have some unexpected (as I think) behavior:

I created RealmResults with some condition and another RealmResults with other condition on other field, based on first RealmResults:
```
RealmResults<Message> allMessagesToNameA = realm.where(Message.class).equalTo("contact", "nameA").findAllAsync();
RealmResults<Message> unSentMessagesToNameA = allMessagesToNameA.where().equalTo("isSend", false).findAllAsync();
```

And I have several pairs of such queries. When I add objects, second queries return wrong results (not matching to condition of first RealmResults, which they are based on). 
Is it a kind of bug, or do I miss something?

Here is all code (synthetic sample)
http://pastebin.com/MJy2VUsB

**Comment by nhachicha** [comment] 2016-02-12 01:16
Hi @grigoryfedorov 
Thanks for providing the sample code, that was helpful.

The problem is when using async queries, what you get in return is a _promise_ and you're using this to refine your query by selecting another field.
what you can do is make sure your async query is loaded (has completed) `unSentMessagesToNameB.isLoaded()` before using it as a base for another query. (you can alternatively start refining your query inside the callback). Or in your use case, you can simplify your query like this 
```java
final RealmResults<Message> unSentMessagesToNameA = realm.where(Message.class).equalTo("contact", "nameA").equalTo("isSend", false).findAllAsync();
        unSentMessagesToNameA.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {

                printMessages(unSentMessagesToNameA, "onChange unSentMessagesToNameA");
            }
        });

        final RealmResults<Message> unSentMessagesToNameB = realm.where(Message.class).equalTo("contact", "nameB").equalTo("isSend", false).findAllAsync();
        unSentMessagesToNameB.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                printMessages(unSentMessagesToNameB, "onChange unSentMessagesToNameB");
            }
        });
```

Cheers

**Comment by grigoryfedorov** [comment] 2016-02-12 05:30
Thanks for fast answer!
I understand what can I do to get correct solution.
The only thing not clear to me is why I get _all_ data from first query instead of none perhaps (if it is not loaded)

**Comment by nhachicha** [comment] 2016-02-12 12:27
Because the second query run against the entire table rather than the filtered messages

when you do this 
```java
RealmResults<Message> allMessagesToNameA = realm.where(Message.class).equalTo("contact", "nameA").findAllAsync();
    final RealmResults<Message> unSentMessagesToNameA = allMessagesToNameA.where().equalTo("isSend", false).findAllAsync();
```
since `allMessagesToNameA` didn't complete yet, the second query `unSentMessagesToNameA` is _like_ querying  on  the entire table `Message` instead of querying on the previously selected messages

**Comment by beeender** [comment] 2016-03-16 02:57
@grigoryfedorov I hope your issue is solved. To make it easier for us to tracking the issue, i am closing this now. Feel free to reopen it if needed. Thanks!

**Closed by beeender** 2016-03-16 02:57 UTC
Labels: S:Waiting For User, T:Help
