### ISSUE TITLE
FindFirst returns null

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-java#1409] opened 2015-08-20 18:59 UTC
Hi everyone.
I've a problem with this method, I'm using the last version of the library. If you can review: 

After login, the server returns the data and I create the account (of AccountManager) and save these data at the database of the application, like this (at an AsyncTask, of course):

```java
UserRealm userRealm = new UserRealm();
//setter of the userRealm...
    
Realm realm = Realm.getInstance(context);
realm.beginTransaction();
realm.copyToRealmOrUpdate(userRealm);
realm.commitTransaction();
realm.close(); //No effect
```
After, I close the LoginActivity and at the onResume of the MainActivity, I try to load the user, like this(at an AsyncTask, again...):
```java
public static UserRealm getUser(Context context) {
  try {
    return Realm.getInstance(context).where(UserRealm.class).findFirst(); //Sometimes return null, sometimes not...
    } catch (Exception e) {
       if(DebugUtil.DEBUG) { //enabled
         e.printStackTrace();
       }
    }
  return null;
}
```
But this returns null, no exceptions or warnings, I don't know what happens with it.

UserRealm: https://gist.github.com/ppamorim/88f2553a6ff990876bc6

http://stackoverflow.com/questions/32107880/findfirst-returns-null?noredirect=1#comment52112039_32107880

**Comment by ppamorim** [comment] 2015-08-20 20:16
Workaround <3

```java
public static UserRealm getUser(Context context) {
    try {
      Realm realm = Realm.getInstance(context);
      realm.refresh();
      UserRealm userRealm;
      do {
        userRealm = realm.where(UserRealm.class).findFirst();
      } while (userRealm == null);
      
      return userRealm;
    } catch (Exception e) {
      if(DebugUtil.DEBUG) {
        e.printStackTrace();
      }
    }
    return null;
  }
```

**Comment by beeender** [comment] 2015-08-21 03:59
How does your AsyncTask for loading look like? I noticed you have `realm.refresh()` in the second comments.

In `Realm.commitTransaction()`, Realm will try to notify other threads **who has a looper**, and those threads's Realm will get update in **next event loop**.

For threads who don't have a looper, `Realm.refresh()` needs to be called to get the latest realm.

Check this [doc](https://realm.io/docs/java/latest/#auto-refresh)

**Comment by ppamorim** [comment] 2015-08-21 11:40
@beeender I've added the realm.refresh() soon and don't have any effect. I'll add this method at the end of the code and try to test.

**Comment by beeender** [comment] 2015-08-21 11:41
@ppamorim Or maybe simply share you project with us, if it is possible? to help@realm.io or any other place you like.

**Comment by ppamorim** [comment] 2015-08-21 11:42
@beeender I can't share the project at all, but I can share some classes that I use.

**Comment by beeender** [comment] 2015-08-21 11:43
Your ayncs tack (for loading data) is running all the time or it is just started when you need to load data?

**Comment by ppamorim** [comment] 2015-08-21 12:21
@beeender Only when I need the data.

**Comment by beeender** [comment] 2015-08-21 12:38
What does `<3` mean in your second comment?

**Comment by ppamorim** [comment] 2015-08-21 13:32
Love.

**Comment by ppamorim** [comment] 2015-08-21 13:33
@beeender , you need to be more human and less robot.

**Comment by beeender** [comment] 2015-08-21 13:34
@ LoL I thought it means "it works when the RealmResults.size() < 3" 

So `realm.refresh()` doesn't work? Are you using the realm across process?

**Comment by ppamorim** [comment] 2015-08-24 14:59
@beeender No, I reinstance (using Realm.getInstance()) the realm on every start of task.

**Comment by cmelchior** [comment] 2015-08-26 06:40
Hi @ppamorim 
I think the problem here is that you are saving your data in a AsyncTask. Because if you just start the task and return to the activity, that data might not be available when you hit `onResume`

Have you tried just saving the object on the UI thread? Saving one object shouldn't be a problem. Otherwise you can add a `RealmChangeListener` in `onResume` so you get notified when the data is available.

**Comment by ppamorim** [comment] 2015-08-26 12:20
@cmelchior I use MVP on my applications and I don't do any another interaction on the UI unless interactions with views. Always I do it on the an "AsyncTask".

**Comment by ppamorim** [comment] 2015-08-26 12:21
@cmelchior You MUST use an AsyncTask to do long interaction like saving, retrieving or binding data.

**Comment by kneth** [comment] 2015-08-28 06:58
@ppamorim We are working on async support e.g., #1224 and it sounds like you could benefit from that work.

**Comment by ppamorim** [comment] 2015-08-28 13:36
@kneth I don't need the async support because I create my async tasks manually. But it's an amazing feature if has an good implementation.

**Comment by beeender** [comment] 2015-08-28 13:39
@ppamorim I tried hard to reproduce this, but i couldn't ... Is it possible for you to share you current or make a small project can reproduce this issue? :slot_machine:

**Comment by ppamorim** [comment] 2015-08-28 13:42
@beeender You would create an activity, save an new object and return to the base activity, on the onResume method, try to get this object.

**Comment by beeender** [comment] 2015-08-28 14:09
@ppamorim Well... it works fine https://github.com/beeender/ReturnFirstTest

**Comment by ppamorim** [comment] 2015-08-28 15:19
@beeender, do it on an Async Task... Or let me try it.

**Comment by beeender** [comment] 2015-08-28 16:09
@ppamorim better you try, just make a pr on my repo

**Comment by zaki50** [comment] 2015-09-07 14:06
@ppamorim One solution is delaying finish() of LoginActivity until finishing background task.
It means to put finish() in AsyncTask#onPostExecute().

**Comment by ppamorim** [comment] 2015-09-08 00:55
finish() is always called when the async task ends.

**Comment by kneth** [comment] 2015-09-09 08:25
@ppamorim Did you try to modify @beeender's app?

**Comment by kneth** [comment] 2015-09-23 12:34
I will close the issue. If you have further questions or comments, don't hesitate to either reopen this issue or create a new.

**Closed by kneth** 2015-09-23 12:34 UTC
Labels: Help, Pending
