### ISSUE TITLE
Invalid realm.refresh() behaviour?

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#2681] opened 2016-04-26 17:28 UTC
I've spotted that the in Realm 0.89 behavior of Realm.refresh() has significantly changed compared to 0.88.3. In 0.89 RealmResults are refreshed only when autoRefresh is disabled, in 0.88.3 there was no such limitation. Is it intended behaviour? 

Current implementation of refresh assumes refreshing only when isAutoRefreshEnabled() returns false:

    if (!handlerController.isAutoRefreshEnabled()) {
        // non Looper Thread, just advance the Realm
        // registering listeners is not allowed, hence nothing to notify
        sharedGroupManager.advanceRead();
        handlerController.refreshSynchronousTableViews();
    } else {
        handlerController.notifyCurrentThreadRealmChanged();
    }

**Comment by zaki50** [comment] 2016-04-27 07:25
Hi @roughboy 

Yes, it's an intended change
.
If auto refresh is enabled, `RealmResults` is automatically refreshed on Looper events.
And if you need to update `RealmResults` immediately, please invoke `Realm.refresh()`.

Please see https://realm.io/news/realm-java-0.89.0/#stable-iterators for more detail.

We should state that change in `CHANGELOG.md` as well.

**Comment by zaki50** [comment] 2016-04-27 07:30
@roughboy I'll double check this. Please wait.

**Comment by zaki50** [comment] 2016-04-27 07:38
@roughboy I confirmed that the behavior change of `refresh()` is intended.

Is there a use-case which requires immediate update on Looper thread?

**Comment by roughboy** [comment] 2016-04-27 08:14
Hi @zaki50. Actually I've already described my use case it in #2650 and hoped i may somehow workaround it using refresh. Of course i could do something like:

    realm.seatAutoRefresh(false);
    realm.refresh();
    realm.setAutoRefresh(true).

however it looks ugly IMHO.

**Comment by cmelchior** [comment] 2016-04-27 08:20
Hi @roughboy 
It sounds like you are trying to use a RealmResults for something it was not really intended. A RealmResults is a "view" into the underlying data, it is not a datastructure that is intended to be manipulated directly. 

You use-case as described in #2650 sounds like an sorted list to me. If you could convert it into a `RealmList` instead it would probably fit your use case better. It has methods like `move()` you can use to swap positions as well.

**Comment by roughboy** [comment] 2016-04-27 09:04
In that case I have to rething my approach - thanks for help!

**Comment by zaki50** [comment] 2016-04-27 12:39
@roughboy I'll close this issue. Feel free to reopen this if you have further questions.

**Closed by zaki50** 2016-04-27 12:39 UTC
Labels: S:Waiting For User, T:Doc
