### ISSUE TITLE
Crash on deleting realm after migrating to 4.1.1 from 3.3.1

### ISSUE THREAD

**Issue by AamirAbro** [realm/realm-java#5570] opened 2017-11-27 08:32 UTC
We are using below code to to open realm instance. It used to work fine for version 3.1.1
Idea is that we have some migrations for last two three versions but for version before that we dont so it throws exception or in case migration fails we delete that current realm and open again.

this used to work fine in 3.1.1 how ever we just upgraded to 4.1.1 last sprint and after it we are seeing a-lot of crashes.
```
            Realm.init(context);
            RealmConfiguration configuration = new RealmConfiguration.Builder()
                    .schemaVersion(<version>)
                    .migration(<migrator>)
                    .build();

            try {
                defaultInstance = Realm.getInstance(configuration );
            } catch (IllegalArgumentException | IllegalStateException | RealmMigrationNeededException ex) {
                Realm.deleteRealm(configuration);
                defaultInstance = Realm.getInstance(configuration);
            }
```

#### Expected Results

>it should not crash

#### Actual Results

This is the exception we are getting
```
Caused by java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file: /data/data/com.x.x/files/default.realm
       at io.realm.Realm.io.realm.BaseRealm.deleteRealm(SourceFile:14624)
       at com.x.x.x.RealmManager.getDefaultInstance(SourceFile:52)
```

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: yes/no

Android Studio version: 3.0.0

Which Android version and device: no specific version happening on almost every os

**Comment by Zhuinden** [comment] 2017-11-27 13:34
This is the same code as in https://github.com/realm/realm-java/issues/4552#issuecomment-297079623

And now that you mention it, question to @beeender - is it possible that `Realm.getInstance()` opens a Realm (and a shared realm) instance, but when exception occurs, the shared realm remains open (and you cannot close it because the instance opening failed)?

**Comment by AamirAbro** [comment] 2017-11-27 15:34
yes I did not knew about that thread sorry. I found out about it after already creating this and that is already closed. So we can open that or close this issue. Apologies for inconvenience.

Yes thats my understanding too that when this migration exception is thrown that instance remains open and therefore we can not delete it. `Realm.deleteRealm(configuration);`

However this is some regression I can confirm this used to work on version `3.3.1`

**Comment by Zhuinden** [comment] 2017-11-27 15:52
I think the real "regression" is the fact that it used to work at all!

If the shared Realm is opened but not closed after a failed `getInstance()` call, then that's bad!

There was an improvement that guarantees that the Realm file is not open by any threads in any processes, which is why this surfaced

**Comment by AamirAbro** [comment] 2017-11-27 16:54
@Zhuinden the above DynamicRealm thing did not solved it for me :(
still getting the same exception while calling `Realm.deleteRealm(configuration);` after it.

**Comment by Zhuinden** [comment] 2017-11-27 17:01
That's a shame, that means the problem is more intricate than I thought.

In that case I can recommend opening a DynamicRealm instead of a typed Realm in the meantime so you can check the schema version to see if you want to delete it (after closing dynamic Realm), instead of listening for the migration exception

**Comment by beeender** [comment] 2017-11-28 02:45
> this used to work fine in 3.1.1 how ever we just upgraded to 4.1.1 last sprint and after it we are seeing a-lot of crashes.

Before 4.1.0, when calling `deleteRealm()`, we don't check if there are Realm instances in other processes. So it may not throw at that point, but it could crash badly in the future, because of Realm file should never be deleted while there are instances still opened.

After 4.1.0, `deleteRealm()` is a process-safe API. It will throw if it detect un-closed Realm instance.

So, please check if you have any other Realm instances opened in other threads/process.

**Comment by AamirAbro** [comment] 2017-11-28 06:47
I can confirm there are no other instances open. this is the only instance.
I still the believe the instance is leaked from the `Realm.getInstance(configuration);` which is throwing Exception.

**Comment by cmelchior** [comment] 2017-11-28 06:51
I just tried to write the following unit test:

```
    @Test
    public void deleteRealm_afterMigrationFailed() {
        RealmConfiguration config = configFactory.createConfigurationBuilder()
                .assetFile("default0.realm")
                .build();

        // First open Realm in dynamic mode to ensure that it is copied to disk
        DynamicRealm.getInstance(config).close();

        try {
            // Then attempt to open Realm normally which should throw
            Realm.getInstance(config);
            fail();
        } catch (RealmMigrationNeededException e) {
            assertTrue(Realm.deleteRealm(config));
        }
    }
```

It parses. Have you tried printing the values of `Realm.getGlobalInstanceCount(config)` as the first thing in your `try/catch`?

**Comment by RemyTabardel** [comment] 2017-11-28 11:09
I have exactly same problem, i test your code @cmelchior but it's not working.
I tried to close SharedRealm too but not working.

I call getGlobalInstanceCount in catch before deleteRealm, it's return 0.

```
        RealmConfiguration config = Utils.getRealmConfiguration();
        DynamicRealm.getInstance(config).close();
        SharedRealm.getInstance(config).close();

        try {
            Realm.getInstance(config);
        } catch (Exception e) {
            Log.d("realm","process open : "+Realm.getGlobalInstanceCount(config)); //return 0
            Realm.deleteRealm(config);
            Realm.getInstance(config);
        }

**Comment by cmelchior** [comment] 2017-11-28 11:23
It would be nice with a reproducible project for this @AamirAbro or @RemyTabardel ?

**Comment by RemyTabardel** [comment] 2017-11-28 12:11
@cmelchior I created a project where i reproduce this problem:
https://github.com/RemyTabardel/RealmMigrationTest

I added library module because i use RealmModels inside, maybe the problem comes from there.
To test migration, i uncomment surname field in User class, and i increment schemaVersion.

**Comment by beeender** [comment] 2017-11-28 13:57
@RemyTabardel I can reproduce the issue. I will make a fix for it.

**Closed** 2017-11-29 13:57 UTC
Labels: T:Bug

**Comment by baboog** [comment] 2017-12-04 06:52
hey guys sorry to barge in ... 
in which version will this fix be out , @beeender 
thanks for the help

**Comment by RemyTabardel** [comment] 2017-12-04 08:28
in 4.2.1, no date at the moment, i'm waiting for that too =p
https://github.com/realm/realm-java/blob/master/CHANGELOG.md
