### ISSUE TITLE
Android component: RealmCursor

### ISSUE THREAD

**Issue by loosemoose** [realm/realm-java#438] opened 2014-10-01 13:16 UTC
Realm for Android looks awesome; however there are some Android specific use cases where certain elements work better when backed by a Cursor (http://developer.android.com/reference/android/database/Cursor.html) and when using a CursorLoader (http://developer.android.com/reference/android/content/CursorLoader.html). Is there any plans for supporting this interface?

**Comment by phu** [comment] 2015-01-13 10:52
Another +1 here for ContentProvider support. I'd assumed this would be possible without really thinking carefully about it when I picked Realm for a project that needs to sync often with a server, the plan being to put all data access behind a single CP so any widget/view querying the data can do so the same way and receive updated data when necessary.

I'm not a fan of the way ContentProvider works, but it does, and as mentioned it's what a lot of people are used to (plus, in the same vein, there's plenty of doc and discussion out there for it).

For now I'll probably just go with a couple of custom adapters based on the example in the codebase, but it would definitely be nice (and, for more complex projects, perhaps necessary) to either provide a RealmContentProvider or facilitate reasonably painless creation of such a beast. A RealmCursor might be a good middle ground with perhaps more diverse potential applications.

**Comment by FunMiles** [comment] 2015-02-01 18:35
+1 for cursor and ContentProvider support.

**Comment by bangarharshit** [comment] 2015-02-13 15:53
+1. Android provides minor things such as retained cursor in CursorLoader across configuration change. It is a big deal. Though this functionality can be achieved just by replacing cursors with RealmResults.

**Comment by sharathp** [comment] 2015-02-15 21:05
+1

**Comment by baolongnt** [comment] 2015-03-20 22:00
+1 for cursor and ContentProvider support

**Comment by rpgobjects** [comment] 2015-03-31 16:08
+ 1 for cursor support.  if you want to use realm with a searchview your only options is to give it a cursoradapter.

**Comment by comfreeze-impekable** [comment] 2015-04-28 20:00
+1

Realm looks interesting, but it's exclusion of this feature chain preventing my use of Cursors have completely discounted it from an option in my toolkit.  Cursor and the related ContentProviders allow for a broader scope of drop-in implementation and event notifications than Realm has presently exhibited in my testing.  On a tablet, for example, I have one application that shows four parallel list views with different renders of some shared items, and allows dragging and dropping these items between some of the components [ (A) -> (B), (A) -> (C), (B, C) -> (D) ] but all objects are the same and feed from the same table, evolving through states and triggering implicit changes/actions on update.  Using the native cursor loader I had to write almost zero logic for that action completed and updated all visible lists as well as a background network broadcaster which communicated the change to a subordinate network link for subscribed children as well.  I can also easily register individual view elements to listen for a specific content URI record and update accordingly.  Incidentally this also blocks the use of my library which exposes the ContentProvider as a direct network REST service which I sometimes use to inject data live into an application from a browser or another on-device application (self-contained server app style).  All of these are features I have come to expect from Cursor and ContentProviders for more than a year, so losing these features to a reduced feature set is not an option.  So far, this implementation seems quite bulky and cumbersome to implement in Realm without a lot more work to wrap and adapt the necessary components.

I was also surprised to see the use of private properties recommended in the model with generated virtual methods as that is not the recommended method for properties in Android (http://developer.android.com/training/articles/perf-tips.html#GettersSetters).

**Comment by itrethan** [comment] 2015-05-15 09:29
+1

**Comment by manuel-sejourne** [comment] 2015-05-21 15:23
+1

**Comment by FlorangOutang** [comment] 2015-05-27 13:55
+1

**Comment by vitalyraevsky** [comment] 2015-06-03 13:17
+1

**Comment by bcorso** [comment] 2015-06-05 23:22
+1 
I'd point out that besides using the ContentProvider for sharing data between apps, it is also a convenient way to sync data with remote servers using Android's SyncAdapter (which requires a ContentProvider to exist). 

The ContentProvider typically calls ContentResolver.notifyChange(...), which will automatically queue a SyncAdapter to get called through a Service -- so no worries about lifecycle. Also, the Android OS  takes care of batching your SyncAdapter requests with others from multiple apps to conserver battery.

**Comment by Renascienza** [comment] 2015-06-08 01:13
Hi, bmunkholm.

Beyond allow abstract the database layer (as the same can be accomplished by some sort of DAO pattern), there so many other reasons to implement a ContentProvider on an Android app:

a) Secure sharing data across apps is a celebrated feature on Android. 3th party apps expect share data through ContentProvider interface.

b) Support easily the data acqusition for App Widgets.

c) Support easily In-App searches

d) Make use of SyncAdapters

e) ContentProviders is part of Android culture. Existing apps already have impemented the pattern.

f) All dependent ContentProvider classes and frameworks are older and more thoroughly tested then Realm itself.

**Comment by rajuashok** [comment] 2015-06-08 19:45
+1 for Cursor support

**Comment by LOG-TAG** [comment] 2015-06-16 05:35
Great news ! Thanks for enhancement tag!

I agree with @Renascienza  +1,  ContentProviders are very much needed!

if we compare realm and GreenDAO based on  features people will point out mainly on ContentProviders feature!, building a ContentProviders is a developer pain point ! @bmunkholm mentioned  people stay as far away from Content Providers as possible for various reasons! 

But GreenDAO allows us create ContentProviders generators thats makes dev life easier !!  if realm gives the support for Content Providers i'm going start contributing building Content Providers generator for Realm :)

**Comment by LOG-TAG** [comment] 2015-06-16 05:46
if realm integrates Content Provider "Realm files cannot be accessed by concurrent processes"  problem will be solved ?  http://stackoverflow.com/questions/5248319/database-handling-with-2-processes   I'm not sure, it's a highly debatable thing I guess!

**Comment by cmelchior** [comment] 2015-06-16 05:51
Hi @LOG-TAG 
We already have a simple implementation of a Cursor working: #1090. However, as you point out, access across processes and threads are normally fundamental to how Cursors are used (e.g. in ContentProviders), so we are hesitant to release it without these features. We have some ideas for fixing that, but we are currently working on more high prioritised features like Null support, migrations and Async queries.

**Comment by IgorGanapolsky** [comment] 2015-07-08 20:29
For the proponents of Loaders and CursorAdapters here, I say try RxJava instead.  You will be amazed how much more you can accomplish with RX, with less code.

**Comment by phu** [comment] 2015-07-08 23:57
Igor: Thanks for the link, but the point for many of us is compatibility with Android's native data providers, both within and between apps. Does Rx address that? It seems cool but I'm not seeing how it's related.

**Comment by IgorGanapolsky** [comment] 2015-07-09 00:04
ContentProviders and Loaders are completely unnecessary if you use RxJava.

**Comment by LOG-TAG** [comment] 2015-07-09 09:01
@IgorGanapolsky thanks!,  You mean use storio https://github.com/pushtorefresh/storio ,  sqlbrite https://github.com/square/sqlbrite  like Rxyfied SQLite    or use Rxyfied realm !! expecting more explanation from you!

**Comment by emanuelez** [comment] 2015-07-09 09:03
Well, ContentProviders are the only way to share data among apps so those are still needed for that particular use.
We are huge fans of RxJava and are working hard to make Realm work seamlessly with it :)

**Comment by IgorGanapolsky** [comment] 2015-07-09 13:07
A loader is only necessary to load data on a background thread and return
it to the main thread.  RXJava does the same thing - except much better and
with less code.

**Comment by Renascienza** [comment] 2015-07-09 22:43
@IgorGanapolsky 

RxJava can share my data with another preexisting applications as the default Android supported architecture, like a Content Provider?

RxJava can seamslessly take advantage of preexisting Android Framework syncing solutions supported by Google, like Loaders?

I don't think so... Standards may not always be the fancy and latest possible solution, but all there for good reason: compatibility.

**Comment by IgorGanapolsky** [comment] 2015-07-09 22:46
@Renascienza. Some standards are falsely there because Google developed a
partially lousy sdk.  Just look as how terrible AsyncTask api is for
example, and ask yourself - is it truly a good standard that is set by
Google?

**Comment by Renascienza** [comment] 2015-07-09 22:59
@IgorGanapolsky 

Thinking with compatibility in mind, doesn't matter if Google make a so good or so bad sdk. The fact here is that applications and frameworks expect a contract to work together. This contract need be satisfied.

About AsyncTasks, you can replace it with anything you like, because applications doesn't expose it, and no frameworks expect it. 

But about Services, Content Providers, Loaders and BroadcastReceivers, for example, is another matter.

Yes, you and I don't decide so much about Google Android patterns. Why? Because when there was a good mobile solution, we didn't create one. They did.

**Comment by aercanozcan** [comment] 2015-08-07 11:16
I agree with @Renascienza.
But I am also open to other solutions to share data between apps using Realm.(other than parcelable, Bundle,Intent because of 1mb data cap)

**Comment by cmelchior** [comment] 2015-08-07 11:21
We are working on process support as well: https://github.com/realm/realm-java/issues/1091
It will only work for apps where they both are using Realm. If that is acceptable, it will be transparent which app edited the data. It will just look like a background thread was doing it.

If you want to share data with arbitrary other apps there is no way around the ContentProvider/Cursor interface unfortunately.

**Comment by nishad358** [comment] 2015-08-12 12:39
+1
Waiting for this feature. Will use Realm as soon as they add Cursor support.

**Comment by bmunkholm** [comment] 2015-08-12 19:25
Great to hear @nishad358. Could you also please elaborate your use case?

**Comment by nishad358** [comment] 2015-08-13 07:36
Use case is same as what others have discussed. We use Content providers for syncing and as a layer between UI and data.

**Comment by petersnoopy** [comment] 2015-10-24 12:11
+1

**Comment by guillermomuntaner** [comment] 2015-10-29 08:12
+1 because of the smaller memory footprint & because cursor is the only way to support some basic default Android features like searchView.

**Comment by cmelchior** [comment] 2015-10-29 08:17
@guillermomuntaner A `RealmResults` or `RealmList` has the same Java heap memory footprint as a `Cursor` as a `RealmResult` also lazy-load its data the same way a cursor does, and it has an even better native memory footprint as we don't copy data to `CursorWindows` first.

We do however still want to support cursors though, because as you point out, some Android API's only work on Cursors.

**Comment by zayo** [comment] 2015-12-30 21:14
+1

**Comment by badboyhb** [comment] 2016-02-04 07:02
Two suggestions:
1,Move "io.realm.internal.Row" and "io.realm.internal.Table" to package "io.realm".
2,Add method "public Row getRow()" to "RealmObject"

**Comment by badboyhb** [comment] 2016-02-04 07:06
Now I get the row for RealmObject by reflection.

Field f = RealmObject.class.getDeclaredField("row");
f.setAccessible(true);
Row r = (Row) r.get(RealmObject);
r.getLong(columnIndex1);
r.getString(columnIndex2);

**Comment by cmelchior** [comment] 2016-02-04 07:21
Hi @badboyhb 
The `Row` and `Table` classes are not really intended to be public. If you want a more dynamic access to Realm data you can use our new Dynamic API which will give you methods like `obj.getString()` and `obj.getLong(): https://realm.io/docs/java/latest/#dynamic-realms

Regarding Cursors we have a PR here that adds it but there still is some corner cases we need to find solutions for: https://github.com/realm/realm-java/pull/1090

**Comment by nolsigan** [comment] 2016-04-28 03:49
+1 for cursor

**Comment by cmelchior** [comment] 2016-05-04 12:08
We are splitting all Android specific components into their own repo. So this issue has been transferred to here: https://github.com/realm/realm-android-adapters/issues/6

**Closed by cmelchior** 2016-05-04 12:08 UTC
Labels: S:P2 Backlog, T:Feature

**Comment by droidahmed** [comment] 2016-11-30 10:11
+1 for cursor and ContentProvider support

**Comment by Zhuinden** [comment] 2016-11-30 10:55
I wonder if it's possible to share managed objects between processes. O_o

**Comment by beeender** [comment] 2016-11-30 10:55
@Zhuinden :no_mouth: it is actually possible ....

**Comment by Marchuck** [comment] 2017-01-08 13:12
+1 for cursor and ContentProvider support

**Comment by petersnoopy** [comment] 2017-01-16 13:19
Any news?

**Comment by cmelchior** [comment] 2017-01-16 13:25
@petersnoopy This has pretty low priority at the moment, sorry. The issue is being tracked here now: https://github.com/realm/realm-android-adapters/issues/6

**Comment by Zhuinden** [comment] 2017-01-16 15:53
@petersnoopy it's low prio because ContentProvider assumes multi-process safety.

But `RealmResults<T>` works like a cursor anyways, with lazy-load and reading a row you index only

**Comment by a9595** [comment] 2017-05-19 09:50
+1
