### ISSUE TITLE
Bulk update native crash

### ISSUE THREAD

**Issue by Chesteer89** [realm/realm-java#6478] opened 2019-04-01 12:53 UTC
#### Goal
Set delivered date on multiple objects
https://github.com/realm/realm-java/issues/762

#### Actual Results
```
java.lang.ArrayIndexOutOfBoundsException: Out of range  in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 334(requested: 1 valid: 1)
        at io.realm.internal.OsResults.nativeSetTimestamp(Native Method)
        at io.realm.internal.OsResults.setDate(OsResults.java:435)
        at io.realm.RealmResults.setDate(RealmResults.java:405)
```

#### Steps & Code to Reproduce
```
fun setReadAll() {
        val readAtDate = Date()
        realm.executeTransaction {
            it.where(Message::class.java).isNull(Message::readAt.name).findAll()
                    .setDate(Message::readAt.name, readAtDate)
        }
    }
```
`setReadAll()` method is called:
- after change (RealmChangeListener, ignoring objects with set **readAt** field)
- after scroll to bottom
depends on current state.

This crash happens when I scroll to bottom, there're 2 unread messages.

I've added print into foreach. I've got 4 objects to update, but crash like this happend:
```REALM_JNI: jni: ThrowingException 2, Out of range  in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 334(requested: 2 valid: 2), .```

#### Version of Realm and tooling

Realm version(s): 5.10.0

Realm Sync feature enabled: Yes

Android Studio version: 3.3.2

Android Build Tools version: 28.0.3

Gradle version: 4.10.1

Which Android version and device(s): Samsung Galaxy Tab Active2, Android 8.1.0

**Comment by Zhuinden** [comment] 2019-04-01 13:02
A wild guess, but I think this is a bug in ObjectStore because [this line is forward iteration instead of reverse iteration](https://github.com/realm/realm-object-store/commit/772cbc99f1199d4b17439a9f0231bd57721c21b2#diff-0e5d63df6af62a3554f908a742039368R350), but `set*` methods are only defined on RealmResults but not on RealmCollection and therefore not accessible on snapshots. 😞 

@cmelchior  ?

**Comment by cmelchior** [comment] 2019-04-02 15:09
Yes, this looks like a bug.  I'll investigate further.

**Comment by cmelchior** [comment] 2019-04-05 07:37
I can reproduce it with the following test:
```
    @Test
    public void setDate_updateRemovesObjectFromQuery() {
        realm.beginTransaction();
        realm.deleteAll();
        for (int i = 0; i < 5; ++i) {
            AllJavaTypes obj = realm.createObject(AllJavaTypes.class, i);
            obj.setFieldDate(i % 2 == 0 ? null : new Date(YEAR_MILLIS * (i - 5 / 2)));
        }
        realm.commitTransaction();
        realm.beginTransaction();
        RealmResults<AllJavaTypes> collection = realm.where(AllJavaTypes.class)
                .isNull(AllJavaTypes.FIELD_DATE)
                .findAll();

        collection.setDate(AllJavaTypes.FIELD_DATE, new Date(10000));
        realm.commitTransaction();
        assertTrue(collection.isEmpty());
    }
```

I suspect it is related to the objects part of the query being removed from the result when updated.

**Comment by Chesteer89** [comment] 2019-04-05 09:46
Well, in my scenario those objects are not deleted - they're updated. Right now I've got two independent updates on objects - setDeliveredDate and setReadDate. Is it possible that the update of another field in the object caused such an error?

**Comment by Zhuinden** [comment] 2019-04-05 09:53
Would `for (size_t i = size - 1; i >= 0; --i) {` fix it?

**Comment by cmelchior** [comment] 2019-04-05 10:04
Possible, the code is in Object Store. I'm looking through it now.

@Chesteer89 The deletions in my test are not related to it failing. It is caused by the `isNull` clause. When you set the date on the object it is no longer part of the query result.

**Comment by Zhuinden** [comment] 2019-04-05 10:30
(but this scenario _should_ work 😛 )

**Comment by cmelchior** [comment] 2019-04-05 12:10
A fix is being made by https://github.com/realm/realm-java/issues/6482

In the meantime, you can work around by doing it manually.

```
fun setReadAll() {
        val readAtDate = Date()
        realm.executeTransaction {
            it.where(Message::class.java)
              .isNull(Message::readAt.name)
              .findAll()
              .createSnapshot()
              .forEach( it.name = readAtDate); 
        }
    }
``

**Comment by bmunkholm** [comment] 2019-04-30 11:34
@cmelchior I assume you can close this now?

**Closed** 2019-04-30 11:50 UTC
Labels: O:User, Reproduction Required, T:Bug-Crash
