### ISSUE TITLE
Failure when converting short string to UTF-16 error_code = 7; retcode = 0;

### ISSUE THREAD

**Issue by BeeFrog** [realm/realm-java#6636] opened 2019-10-17 14:06 UTC
We're getting a number or exceptions similar to the one below.
We can't replicate the issue even if we log in at the user experiencing the issue.

#### Actual Results

> Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Failure when converting short string to UTF-16 error_code = 7; retcode = 0; StringData.size = 18; StringData.data = No knownAAAAf in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 161
> 
>        at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)
> 
>        at io.realm.internal.UncheckedRow.getString + 157(UncheckedRow.java:157)
> 
>        at io.realm.iCareHealth_PointOfCare_persistence_models_ResidentDBModelRealmProxy.realmGet$allergies + 411(iCareHealth_PointOfCare_persistence_models_ResidentDBModelRealmProxy.java:411)
> 
>        at io.realm.iCareHealth_PointOfCare_persistence_models_ResidentDBModelRealmProxy.createDetachedCopy + 2438(iCareHealth_PointOfCare_persistence_models_ResidentDBModelRealmProxy.java:2438)
> 
>        at io.realm.iCareHealth_PointOfCare_persistence_models_FacilityDBModelRealmProxy.createDetachedCopy + 1325(iCareHealth_PointOfCare_persistence_models_FacilityDBModelRealmProxy.java:1325)
> 
>        at io.realm.DefaultRealmModuleMediator.createDetachedCopy + 1038(DefaultRealmModuleMediator.java:1038)
> 
>        at io.realm.Realm.createDetachedCopy + 1714(Realm.java:1714)
> 
>        at io.realm.Realm.copyFromRealm + 1419(Realm.java:1419)
> 
>        at io.realm.Realm.copyFromRealm + 1391(Realm.java:1391)
> 
>       at iCareHealth.PointOfCare.persistence.repositories.local.FacilityLocalRepository.fetchFacility + 55(FacilityLocalRepository.java:55)
> 
>        at iCareHealth.PointOfCare.persistence.repositories.local.FacilityLocalRepository.bridge$lambda$0$FacilityLocalRepository(FacilityLocalRepository.java)
> 
>        at iCareHealth.PointOfCare.persistence.repositories.local.FacilityLocalRepository$$Lambda$1.apply()
> 
>        at iCareHealth.PointOfCare.utils.RealmTransaction.executeWithReturn + 39(RealmTransaction.java:39)
> 
>        at iCareHealth.PointOfCare.persistence.repositories.local.FacilityLocalRepository.getItems + 49(FacilityLocalRepository.java:49)
> 
>        at iCareHealth.PointOfCare.presentation.ui.views.presenters.MainPresenter.updateLocationSpinner + 242(MainPresenter.java:242)
> 
>        at iCareHealth.PointOfCare.presentation.ui.views.activities.MainActivity.setUpMenuLoggedIn + 401(MainActivity.java:401)
> 
>        at iCareHealth.PointOfCare.presentation.ui.views.presenters.MainPresenter.refreshMenu + 269(MainPresenter.java:269)
> 
>        at iCareHealth.PointOfCare.presentation.ui.views.activities.MainActivity.onBackStackChanged + 274(MainActivity.java:274)
> 
>        at android.support.v4.app.FragmentManagerImpl.reportBackStackChanged + 2704(FragmentManager.java:2704)
> 
>        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether + 2411(FragmentManager.java:2411)
> 
>        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 2338(FragmentManager.java:2338)
> 
>        at android.support.v4.app.FragmentManagerImpl.execPendingActions + 2245(FragmentManager.java:2245)
> 
>        at android.support.v4.app.FragmentManagerImpl$1.run + 703(FragmentManager.java:703)
> 
>        at android.os.Handler.handleCallback + 836(Handler.java:836)
> 
>        at android.os.Handler.dispatchMessage + 103(Handler.java:103)
> 
>        at android.os.Looper.loop + 203(Looper.java:203)
> 
>        at android.app.ActivityThread.main + 6251(ActivityThread.java:6251)
> 
>        at java.lang.reflect.Method.invoke(Method.java)
> 
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1063(ZygoteInit.java:1063)
> 
>        at com.android.internal.os.ZygoteInit.main + 924(ZygoteInit.java:924)

#### Version of Realm and tooling

Realm version(s): 5.8.0 (we're about to try 6.0.0)

Realm Sync feature enabled: Yes/No

Android Studio version: 3.5

Android Build Tools version: 27

Gradle version: 

Which Android version and device(s): Android Pie, Samsung J3

**Comment by Zhuinden** [comment] 2019-10-17 15:37
Is encryption enabled?

**Comment by BeeFrog** [comment] 2019-10-18 12:02
> Is encryption enabled?

yes, encryption is enabled. is it something we're doing wrong?

**Comment by Zhuinden** [comment] 2019-10-18 12:08
No, but it could be related: https://github.com/realm/realm-java/issues/6152

**Comment by cmelchior** [comment] 2019-10-22 08:39
Yes, this is probably the same root cause as #6152 

A fix has been merged into Core and we will be making a release and the end of this week or the beginning of next week.

In the meantime, I'll be folding this into #6152

**Closed by cmelchior** 2019-10-22 08:39 UTC
Labels: O-Community, T-Duplicate
