### ISSUE TITLE
Help diagnose slow transaction commit

### ISSUE THREAD

**Issue by benj56** [realm/realm-java#6698] opened 2019-12-18 14:43 UTC
Please advise on how I could debug an apparently slow commit. 
I'm looking at a 500-1000ms delay between the finishing of my 25ms transaction using `realm.executeTransactionAsync` and the execution of the `OnSuccess` callback.

There isn't a lot of data in the commit, just 2 objects, but we're talking about objects with 50+ fields and other linked objects of similar complexity, but no large lists or anything like that, as far as I can judge. 

As I can't easily provide a minimal example, I am asking for advice on how I could pinpoint the source of the delay. As I feel that question would not be suitable for StackOverflow, I hope it is acceptable to submit this here. 

What I have tried now is finding whether this delay is caused by ChangeListeners that are triggered before the OnSuccess callback. I placed a breakpoint in `RealmNotifier.didChange`, there no callbacks other than the `OnSuccess` callback is executed, didChange itself is executed after the delay already.  

I also tried `OsResults.notifyChangeListeners` and only found change listeners firing after the OnSuccess callback. 

At this point I tend to think there might be something about the few linked objects that cause this commit to be slow, rather than change listeners blocking. Is there anything that comes to mind that could help me find out whether some change listeners, other transactions or something like that is causing the delay or the actual insert being slow despite the transaction block executing quickly?

**Comment by cmelchior** [comment] 2019-12-18 14:49
Most likely it is caused by our changelistener algorithm. It has some edge cases where it can become slow, especially if the object graph contains cycles. I don't know if that is the case for you?

If that is the case. It can help to break up the cycle through the use of `@LinkingObjects` (if possible).

**Comment by benj56** [comment] 2019-12-18 14:57
There are cycles, precisely I have an eg. Event which could have an EventChangeRequest attached, which in turn has the Event. But in this transaction, the field is null, there is no ChangeRequest. Could that still be the issue and can I somehow profile this in general?

**Comment by cmelchior** [comment] 2019-12-18 15:04
All of that logic is happening in C++ on a background thread (if I remember correctly it is also a pure C++ thread). So it probably won't show up in a Java performance analysis.

I haven't actually tested this specifically in Systrace. It might show up here.

**Comment by cmelchior** [comment] 2020-08-14 13:28
Closing as outdated. If this is still an inssue, feel free to reopen.

**Closed by cmelchior** 2020-08-14 13:28 UTC
Labels: O-Community, T-Help
