### ISSUE TITLE
[WARNING] DO NOT update to 3.2.1 (Invalid query: table 'Name' not found in this schema.)

### ISSUE THREAD

**Issue by FrancescoCapari** [realm/realm-java#4687] opened 2017-05-23 07:14 UTC
This is a warning for everyone, do **NOT** update to realm.io 3.2.1. This version contains a major bug that basically destroyed rating of my application because it destroyed all data for tens of thousands of my users. The exception is "java.lang.IllegalArgumentException: Invalid query: table 'Name' not found in this schema." and was already reported by more users. I upgraded from 2.2.2 to 3.2.1 with no schema changes.

Version of Realm and tooling

Realm version(s): 3.2.1
Android Studio version: 2.3.2
Which Android version and device: 7.1.2, Nexus 5X, Pixel XL

**Comment by cmelchior** [comment] 2017-05-23 07:41
Hi @FrancescoCapari 
While we do understand that any bug can be extremely annoying and should be fixed as fast as possible (and we are working on that). Creating this kind of issue is not really helping us narrow down what could be wrong.

1) Data hasn't been destroyed. This is most likely a bug with either ProGuard or our query parser.
2) It is a duplicate of https://github.com/realm/realm-java/issues/4673, so please add any details to that issue instead.

I'm closing this issue as a duplicate, but please chime in in #4673 with any extra details.

**Closed by cmelchior** 2017-05-23 07:41 UTC
Labels: T:Duplicate

**Comment by FrancescoCapari** [comment] 2017-05-23 07:52
1) Data has been destroyed because there were major changes between 2.2.2 and non-functional 3.2.1, migration happened and users can not now move back to 2.2.2. Although I used only 10% of production channel, this affected tens of thousands of users. You guys should really think more about quality before releasing new versions. This is not the first MAJOR issue I am reporting to you.

2) That issue is not even marked as bug although it makes realm.io basically unusable.

**Comment by cmelchior** [comment] 2017-05-23 07:58
@FrancescoCapari It is marked a bug (albeit 30 minutes ago), but please add your `build.gradle` file + proguard setup + Realm Model class to that issue.

**Comment by Zhuinden** [comment] 2017-05-23 08:46
Saying "it destroyed data" is an overstatement, adding proguard rule `-keepnames public class * extends io.realm.RealmObject` fixes the issue for now.
