### ISSUE TITLE
Out of memory when opening a Realm

### ISSUE THREAD

**Issue by brntsw** [realm/realm-java#3581] opened 2016-10-06 21:41 UTC
Hello,

I have an app that is in the Google Play already and some users are reporting the app crashed after the update. I am using a RealmMigration class to add some stuff to schema and add old data from some table and add it to a new added table.

The following error is happening (Got the stacktrace from Crashlytics):

`Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 805306368 offset: 0 in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
       at io.realm.BaseRealm.<init>(BaseRealm.java:81)
       at io.realm.Realm.<init>(Realm.java:140)
       at io.realm.Realm.createAndValidate(Realm.java:240)
       at io.realm.Realm.createInstance(Realm.java:220)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
       at io.realm.Realm.getInstance(Realm.java:184)
       at br.gov.sp.educacao.leitorresposta.MainApplication.onCreate(MainApplication.java:26)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5245)
       at android.app.ActivityThread.access$1600(ActivityThread.java:181)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6134)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`

The line 26 is below:

`Realm.getInstance(realmConfiguration);`

As the error suggests, the out of memory error must be from the RealmMigration. The Migration code can be seen below:

```
public class Migration implements RealmMigration{
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion){
        ...
        if(oldVersion == 0 || oldVersion == 1){
            if(!schema.get("Turma").getPrimaryKey().equals("codeTurma")){
                schema.get("Turma")
                             .removePrimaryKey()
                             .addPrimaryKey("codeTurma");
            }

            if(!schema.contains("Subject")){
                schema.create("Subject")
                             .addField("id", String.class, FieldAttribute.PRIMARY_KEY)
                             .addField("codeSubject", int.class)
                             .addField("nameSubject", String.class)
                             .addField("codeTurma", int.class);
            }

            //Other changes here

            //The following code is my doubt about the reason of the crash
            if(schema.get("Turma").hasField("codeSubject") 
                   && schema.get("Turma").hasField("nameSubject")){
                final RealmList<DynamicRealmObject> subjects = new RealmList<>();

                final RealmResults<DynamicRealmObject> turmas = realm.where("Turma").findAll();
                if(turmas.size > 0){
                    for(final DynamicRealmObject turma : turmas){
                        if(turma.getString("nameSubject") != null){
                            DynamicRealmObject subject = realm.createObject("Subject"); //Is this the reason?
                            subject.setInt("codeSubject", turma.getInt("codeSubject"));
                            subject.setString("nameSubject", turma.getString("nameSubject"));
                            subject.setInt("codeTurma", turma.getInt("codeTurma"));

                            subjects.add(subject);
                        }

                        for(final DynamicRealmObject turma : turmas){
                            final RealmList<DynamicRealmObject> subjectsTurma = new RealmList<>();
                            for(final DynamicRealmObject subject : subjects){
                                if(turma.getInt("codeSubject") == subject.getInt("codeSubject")
                                         && turma.getInt("codeTurma") == subject.getInt("codeTurma")){
                                    subjectsTurma.add(subject);
                                }
                            }

                            turma.setList("subjects", subjectsTurma);
                        }
                    }
                }
            }

            ...
            //Other schema changes here

           oldVersion++;
        }
    }
}
```

The `if(oldVersion == 0 || oldVersion == 1)` is because I had an issue in the first migration, where some users had the nameSubject null, then now I added the `if(turma.getString("nameSubject") != null)`

Is the reason for the problem the creation of the object DynamicRealmObject subject inside the for loop?

I can't reproduce the exact error in any device I try, the migration runs and no error occur.

**Realm Version**: 1.1.0
**Android Studio Version**: 2.2
**Devices that the error occurred:** 
- Motorola Moto G3 (Android 5.1)
- Motorola XT1097 (Android 6.0)
- Motorola XT1069 (Android 5.0)
- Tablet Samsung SM-T530 (Android 4.4)

Thanks in advance.

**Comment by zaki50** [comment] 2016-10-07 06:52
We didn't release Realm-Java 1.3.0.
What is the Realm version actually used?

And I couldn't see why the error suggests the error is from the migration code.

**Comment by Zhuinden** [comment] 2016-10-07 07:36
@zaki50 I would assume the issue is with setting up the list, for example creating 100000 subjects

**Comment by brntsw** [comment] 2016-10-07 12:12
@zaki50 it's actually version 1.1.0. The version 1.3.0 that I mentioned is the io.realm:android-adapters version.

**Comment by zaki50** [comment] 2016-10-07 20:30
Exception happend here (https://github.com/realm/realm-java/blob/v1.1.0/realm/realm-library/src/main/java/io/realm/Realm.java#L220)

This line does not invoke migration code. The migration will happen in a few lines after (https://github.com/realm/realm-java/blob/v1.1.0/realm/realm-library/src/main/java/io/realm/Realm.java#L227).

This means that this issue is not related to migration.

The message indicates that the size of database file is about 800M bytes and it's too big to `mmap()`.

**Comment by zaki50** [comment] 2016-10-07 20:36
There are various reasons to cause big file.
One is of too many objects in the database. However, most case is that a Realm instance was left open in a background thread.

If you are using non-looper threads, please check if all Realm instances are closed correctly.

**Comment by zaki50** [comment] 2016-10-07 20:40
I'll update the title

**Comment by brntsw** [comment] 2016-10-07 20:54
@zaki50 It seems clearer now, I implemented an executeTransactionAsync inside the onNext method of RxJava, as it can be seen below:

```
public void onNext(...){
    realm.executeTransactionAsync(new Realm.Transaction(){
        @Override
        public void execute(Realm realm){
            //Do stuff here
        }
    }
}
```

So I need to close the Realm that is the parameter of the execute method, right?

**Comment by Zhuinden** [comment] 2016-10-07 21:17
@brntsw no, closing the background Realm in the async transaction is handled automatically by Realm after the asynchronous transaction is complete

**Comment by Zhuinden** [comment] 2016-10-07 21:18
However, on non-looper background threads, any opened Realm instance should be closed in `finally {`.

**Comment by zaki50** [comment] 2016-10-07 21:21
No need to close the Realm instance passed to the `Transaction#execute(Realm)`.

**Comment by kneth** [comment] 2016-11-07 09:02
I'm closing the issue. Don't hesitate to reopen or create new issue if you experience the same issue.

**Closed by kneth** 2016-11-07 09:02 UTC
Labels: S:Waiting For User, T:Help
