### ISSUE TITLE
OutOfMemoryError: std::bad_alloc in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp line 615

### ISSUE THREAD

**Issue by vladimirfx** [realm/realm-java#6035] opened 2018-06-21 12:42 UTC
#### Expected Results

Not crash

#### Actual Results
`
 Fatal Exception: java.lang.OutOfMemoryError: std::bad_alloc in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp line 615 
       at io.realm.internal.Table.nativeMoveLastOver(Table.java)
       at io.realm.internal.Table.moveLastOver(Table.java:330)
       at io.realm.RealmObject.deleteFromRealm(RealmObject.java:114)
       at io.realm.RealmObject.deleteFromRealm(RealmObject.java:86)
       at ru.fcb.mobilefieldcollection.debt.RealmDebtsRepo.lambda$deleteAddress$65(RealmDebtsRepo.java:833)
       at ru.fcb.mobilefieldcollection.debt.-$$Lambda$RealmDebtsRepo$nFUtGhorCa5JcN1IbRVbg-l08bw.apply(lambda)
       at ru.fcb.mobilefieldcollection.realm.Block-CC.lambda$toFunction$0(Block.java:15)
       at ru.fcb.mobilefieldcollection.realm.-$$Lambda$Block$rxUy2qhKx6FrOVMDHmXqTRfzwqk.apply(lambda)
       at ru.fcb.mobilefieldcollection.realm.RealmTemplate.executeInRealm(RealmTemplate.java:92)
       at ru.fcb.mobilefieldcollection.realm.RealmTemplate.executeInRealm(RealmTemplate.java:82)
       at ru.fcb.mobilefieldcollection.debt.RealmDebtsRepo.deleteAddress(RealmDebtsRepo.java:827)
       at ru.fcb.mobilefieldcollection.debt.DebtDataReceiver.processAddress(DebtDataReceiver.java:164)
       at ru.fcb.mobilefieldcollection.debt.DebtDataReceiver.process(DebtDataReceiver.java:65)
       at ru.fcb.mobilefieldcollection.server.MfcServerConnection$WebSocketListener.lambda$onMessage$2(MfcServerConnection.java:251)
       at ru.fcb.mobilefieldcollection.server.-$$Lambda$MfcServerConnection$WebSocketListener$9h2sSXgOqPaj6sBRQIA76EP9FIk.call(lambda)
       at ru.fcb.mobilefieldcollection.realm.RealmUnitOfWork.lambda$doWork$1(RealmUnitOfWork.java:43)
       at ru.fcb.mobilefieldcollection.realm.-$$Lambda$RealmUnitOfWork$GFV_q7dLAawcDKekC9SreLyZVCc.get(lambda)
       at ru.fcb.mobilefieldcollection.realm.RealmUnitOfWork.doWork(RealmUnitOfWork.java:61)
       at ru.fcb.mobilefieldcollection.realm.RealmUnitOfWork.doWork(RealmUnitOfWork.java:41)
       at ru.fcb.mobilefieldcollection.server.MfcServerConnection$WebSocketListener.onMessage(MfcServerConnection.java:248)
       at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:760)
`
#### Steps & Code to Reproduce

Crash report: http://crashes.to/s/5d7a298c470

Crash happens when one thread is deleting row while another detaching it.

#### Code Sample
Realm config:
```java
        return new RealmConfiguration
                .Builder()
                .name(realmName)
                .schemaVersion(Constants.DB_VERSION)
                .directory(dbDir)
                .encryptionKey(key)
                .migration(MIGRATION)
                .initialData(INIT_REALM_TX)
                .build();


```

#### Version of Realm and tooling
Realm version(s): 5.2.0

Realm sync feature enabled: no

Android Studio version: 3.1.2

Which Android version and device: Andoid 6-7, various devices

**Comment by Zhuinden** [comment] 2018-06-21 14:19
What do you mean by detaching? `realm.copyFromRealm()`?

**Comment by vladimirfx** [comment] 2018-06-21 15:32
Yes. Stack fragment:

>  io.realm.internal.UncheckedRow.nativeGetString (UncheckedRow.java)
--
  | io.realm.internal.UncheckedRow.getString (UncheckedRow.java:157)
  | io.realm.ru_fcb_mobilefieldcollection_debt_PendingDocumentRealmProxy.realmGet$ref (ru_fcb_mobilefieldcollection_debt_PendingDocumentRealmProxy.java:264)
  | ru.fcb.mobilefieldcollection.debt.PendingDocument.hashCode (PendingDocument.java:111)
  | sun.misc.Hashing.singleWordWangJenkinsHash (Hashing.java:48)
  | java.util.HashMap.get (HashMap.java:348)
  | io.realm.ru_fcb_mobilefieldcollection_debt_PendingDocumentRealmProxy.createDetachedCopy (ru_fcb_mobilefieldcollection_debt_PendingDocumentRealmProxy.java:901)
  | io.realm.DefaultRealmModuleMediator.createDetachedCopy (DefaultRealmModuleMediator.java:1178)
  | io.realm.Realm.createDetachedCopy (Realm.java:1613)
  | io.realm.Realm.copyFromRealm (Realm.java:1280)
  | io.realm.Realm.copyFromRealm (Realm.java:1245)

**Comment by vladimirfx** [comment] 2018-06-21 15:35
Thread dump:
[ru.fcb.mobilefieldcollection_issue_123_crash_.txt](https://github.com/realm/realm-java/files/2124322/ru.fcb.mobilefieldcollection_issue_123_crash_.txt)

All crashes has similar stacktrace.

**Comment by cmelchior** [comment] 2018-06-21 19:49
What happens in this lambda? 
```
 at ru.fcb.mobilefieldcollection.debt.RealmDebtsRepo.lambda$deleteAddress$65(RealmDebtsRepo.java:833)
```

**Comment by cmelchior** [comment] 2018-06-28 12:20
Closing due to inactivity. Please reopen if you have further information.

**Comment by vladimirfx** [comment] 2018-06-30 08:32
Please, reopen.

**Comment by cmelchior** [comment] 2018-11-28 11:55
We cannot really debug this without a sample project that reproduces the behavior as most likely this is just a sub-optimal use of the API somewhere. I'll close this issue now, but feel free to reopen if you can provide a project we can look at.

**Closed by cmelchior** 2018-11-28 11:55 UTC
Labels: O:User, T:Help

**Comment by ggajews** [comment] 2019-08-28 15:10
We are observing the same crash. We can observe many crashes, but can't reproduce it locally. It happens on `SyncAdapter thread`, when `deleteFromRealm()` is called.
Code we are using to delete list:
```
if (list != null) {
   val snapshot = list.createSnapshot()
   snapshot.forEach { obj ->
      if (obj.isValid) {
         obj.deleteFromRealm()
       }
    }
}
```
There are no more then 250 objects in the list.
Any ideas why this might fail? How can we proceed with it? Logs, that we may add?
It seems that it happens for only a small portion of the users but multiple times, like the issue is still there even after app restart.
