### ISSUE TITLE
Couldnot delete Realm File 

### ISSUE THREAD

**Issue by teddywest32** [realm/realm-java#1223] opened 2015-06-18 16:47 UTC
I am trying to delete and repopulate my database with new data's but cannot delete the realm database. I am getting "java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file." but when i check the realm instance is null. 
Eg:
<code>
package com.myapp.jsonFetcher;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.AsyncTask;
import android.os.Handler;
import android.preference.PreferenceManager;
import android.util.Log;
import android.widget.Toast;

import com.google.gson.ExclusionStrategy;
import com.google.gson.FieldAttributes;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.StatusLine;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.DefaultHttpClient;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.List;

import io.realm.Realm;
import io.realm.RealmObject;

public class getJson extends AsyncTask<Void, Void, String> {
    private Context context;
    private List<Route> Routes;
    private List<RouteLocation> RouteLocations;
    private String Url = "192.168.0.1/";
    private String UrlExtra;
    private Realm realm;
    private String ENCRYPTION_KEY;
    private String UPDATE_STATUS;

    public getjson(Context context) {
        this.context = context;
    }

    @Override
    protected void onPreExecute() {
        ENCRYPTION_KEY = context.getString(R.string.EncryptionKey);
        UPDATE_STATUS = context.getString(R.string.UpdateSuccess);
        super.onPreExecute();
    }

    @Override
    protected String doInBackground(Void... params) {
        for (int i = 0; i <=2; i++) {
            try {
                HttpClient httpClient = new DefaultHttpClient();
                if (i == 0) {
                    Log.i("Realm", "Nothing to do");
                }
                else if (i == 1) {
                    UrlExtra = "route/";
                }
                else if (i == 2) {
                    UrlExtra = "routelocation/";
                }
                HttpGet httpPost = new HttpGet(Url + UrlExtra);
                HttpResponse response = httpClient.execute(httpPost);
                StatusLine statusLine = response.getStatusLine();
                if (statusLine.getStatusCode() == 200) {
                    HttpEntity entity = response.getEntity();
                    InputStream inputStream = entity.getContent();
                    try {
                        Reader reader = new InputStreamReader(inputStream);

                        GsonBuilder gsonBuilder = new GsonBuilder().setExclusionStrategies(new ExclusionStrategy() {
                            @Override
                            public boolean shouldSkipField(FieldAttributes f) {
                                return f.getDeclaringClass().equals(RealmObject.class);
                            }

                            @Override
                            public boolean shouldSkipClass(Class<?> clazz) {
                                return false;
                            }
                        });
                        Gson gson = gsonBuilder.create();
                        if (i == 0)
                        {
                                    Log.i("Realm", ""+realm);
                                    Realm.deleteRealmFile(context, "file.realm");
                        }
                        else if (i == 1) {
                            Routes = Arrays.asList(gson.fromJson(reader, Route[].class));
                            inputStream.close();
                            RouteHandle(Routes);
                        } else if (i == 2) {
                            RouteLocations = Arrays.asList(gson.fromJson(reader, RouteLocation[].class));
                            inputStream.close();
                            RouteLocationHandle(RouteLocations);
                        } 
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    Log.e(TAG, "Error:" + statusLine.getStatusCode());
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        realm.close();
        return ;
    }

    @Override
    protected void onPostExecute(String s) {
        Log.i("qwq", realm+"");
        if (realm == null)
        {
            Log.i("realm", "realm closed");
        }
        else
        {
            Log.i("realm", "realm not closed");
            realm.close();
            Log.i("re", ""+realm);
        }
        super.onPostExecute(s);
    }

    public void RouteHandle(List<Route> Routes) {
        this.Routes = Routes;

        for (Route Route : FetchJSONData.this.Routes) {
            AddRoute(Route.getId(), Route.getRouteName(), Route.getRouteDetail(), Route.getRemarks());
        }
    }

    public void RouteLocationHandle(List<RouteLocation> RouteLocations) {
        this.RouteLocations = RouteLocations;

        for (RouteLocation RouteLocation : FetchJSONData.this.RouteLocations) {
            AddRouteLocation(RouteLocation.getId(), RouteLocation.getLocationName(), RouteLocation.getRemarks());
        }
    }

    public void AddRoute(int Id, String RouteName, String RouteDetail, String Remarks)
    {
        realm = Realm.getInstance(context, "mydb.realm");
        realm.beginTransaction();
        RouteSchema RouteSchema = realm.createObject(RouteSchema.class);
        RouteSchema = realm.copyToRealmOrUpdate(RouteSchema);
        RouteSchema .setId(Id);
        RouteSchema .setRouteName(RouteName);
        RouteSchema .setRouteDetail(RouteDetail);
        RouteSchema .setRemarks(Remarks);
        realm.commitTransaction();

    }

    public void AddRouteLocation(int Id, String LocationName, String Remarks)
    {
        realm.beginTransaction();
        RouteLocationSchema RouteLocationSchema = realm.createObject(RouteLocationSchema.class);
        RouteLocationSchema = realm.copyToRealmOrUpdate(RouteLocationSchema);
        RouteLocationSchema .setId(Id);
        RouteLocationSchema .setLocationName(LocationName);
        RouteLocationSchema .setRemarks(Remarks);
        realm.commitTransaction();
    }
}
</code>

Also when i close the realm, it is not being closed. What is the problem? 

<code>
06-19 07:50:20.295  22989-22989/com.myapp.jsonFetcher I/qwq﹕ io.realm.Realm@41575ad0
06-19 07:50:20.295  22989-22989/com.myapp.jsonFetcher I/realm﹕ realm not closed
06-19 07:50:20.295  22989-22989/com.myapp.jsonFetcher W/REALM﹕ Calling close() on a Realm that is already closed: /data/data/com.myapp.jsonFetcher/files/file.realm
06-19 07:50:20.295  22989-22989/com.myapp.jsonFetcher I/re﹕ io.realm.Realm@41575ad0
06-19 07:50:25.606  22989-23337/com.myapp.jsonFetcher I/asa﹕ eeeeeeeeeeeeeeeeee
06-19 07:50:25.696  22989-23337/com.myapp.jsonFetcher I/Realm﹕ null
06-19 07:50:25.785  22989-23337/com.myapp.jsonFetcher W/System.err﹕ java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file.
06-19 07:50:25.785  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.Realm.deleteRealmFile(Realm.java:1522)
06-19 07:50:25.785  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.Realm.deleteRealmFile(Realm.java:1502)
06-19 07:50:25.835  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.doInBackground(getJson.java:127)
06-19 07:50:25.835  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.doInBackground(getJson.java:34)
06-19 07:50:25.835  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
06-19 07:50:25.835  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
06-19 07:50:25.845  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
06-19 07:50:25.945  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
06-19 07:50:25.945  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
06-19 07:50:25.985  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
06-19 07:50:26.435  22989-23337/com.myapp.jsonFetcher W/System.err﹕ io.realm.exceptions.RealmException: Primary key constraint broken. Value already exists: 27
06-19 07:50:26.435  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:734)
06-19 07:50:26.447  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.internal.Table.checkIntValueIsLegal(Table.java:728)
06-19 07:50:26.447  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.internal.Row.setLong(Row.java:173)
06-19 07:50:26.447  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.RouteSchemaRealmProxy.setId(RouteSchemaRealmProxy.java:56)
06-19 07:50:26.447  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.AddRoute(getJson.java:241)
06-19 07:50:26.447  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.RouteHandle(getJson.java:203)
06-19 07:50:26.455  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.doInBackground(getJson.java:138)
06-19 07:50:26.455  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.doInBackground(getJson.java:34)
06-19 07:50:26.455  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
06-19 07:50:26.455  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
06-19 07:50:26.465  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
06-19 07:50:26.465  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
06-19 07:50:26.465  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
06-19 07:50:26.465  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
06-19 07:50:26.665  22989-22991/com.myapp.jsonFetcher D/dalvikvm﹕ GC_CONCURRENT freed 721K, 61% free 4949K/12668K, paused 5ms+25ms, total 91ms
06-19 07:50:26.766  22989-23337/com.myapp.jsonFetcher W/System.err﹕ java.lang.IllegalStateException: Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().
06-19 07:50:26.766  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.internal.ImplicitTransaction.promoteToWrite(ImplicitTransaction.java:39)
06-19 07:50:26.776  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at io.realm.Realm.beginTransaction(Realm.java:1301)
06-19 07:50:26.776  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.AddRouteLocation(getJson.java:254)
06-19 07:50:26.776  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.RouteLocationHandle(getJson.java:211)
06-19 07:50:26.776  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.doInBackground(getJson.java:143)
06-19 07:50:26.776  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at com.myapp.jsonFetcher.getJson.doInBackground(getJson.java:34)
06-19 07:50:26.786  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
06-19 07:50:26.786  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
06-19 07:50:26.786  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
06-19 07:50:26.786  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
06-19 07:50:26.786  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
06-19 07:50:26.796  22989-23337/com.myapp.jsonFetcher W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
06-19 07:50:27.275  22989-22991/com.myapp.jsonFetcher D/dalvikvm﹕ GC_CONCURRENT freed 809K, 62% free 4878K/12668K, paused 6ms+10ms, total 88ms
06-19 07:50:27.506  22989-23337/com.myapp.jsonFetcher W/System.err﹕ java.lang.IllegalStateException: Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().
06-19 07:50:27.545  22989-22989/com.myapp.jsonFetcher I/qwq﹕ io.realm.Realm@40cf6df0
06-19 07:50:27.545  22989-22989/com.myapp.jsonFetcher I/realm﹕ realm not closed
06-19 07:50:27.545  22989-22989/com.myapp.jsonFetcher W/REALM﹕ Calling close() on a Realm that is already closed: /data/data/com.myapp.jsonFetcher/files/file.realm
06-19 07:50:27.555  22989-22989/com.myapp.jsonFetcher I/re﹕ io.realm.Realm@40cf6df0

</code>

**Comment by beeender** [comment] 2015-06-19 02:35
```
Realm.deleteFile(context, "mydb.realm");
```
Is above called at everytime you get into the testing loop? Is realm a class member?

And
"Also when i close the realm, it is not being closed. What is the problem? "
Did the close run into any exception or warnings? Which "close" has this problem? close in the testing loop? And how did you know it is not being closed? Any error messages?

It would be helpful to have some code to show how did you start the testing loop.

**Comment by teddywest32** [comment] 2015-06-19 08:17
@beeender  Updated the codes. The Realm always says
<code>java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file. </code>

**Comment by beeender** [comment] 2015-06-19 08:39
As i can tell, you created realm instance in AddRoute which can be called multiple times in the loop of RouteHandle. Please remember to call close on every realm instance you created. GC is not reliable here.

In your case, i suggest you simply create the realm instance in **onPreExecute** and call close on realm instance in **onPostExecute** . No need to check null/create/close of the instance in **doInBackground**.

And also i have seen warnings about the duplicated primary key in the log. It is caused by realm.createObject using the default value for the primary key which might not be what you want. Try use below code:

```java
RouteSchema RouteSchema = new RouteSchema();
RouteSchema .setId(Id);
RouteSchema .setRouteName(RouteName);
RouteSchema .setRouteDetail(RouteDetail);
RouteSchema .setRemarks(Remarks);
RouteSchema = realm.copyToRealmOrUpdate(RouteSchema);
```

When you call createObject, the object will be created (with default primary key value) and **copied** to the realm automactially, no need to call copyToRealmOrUpdate after that.

Just please remember:
**Every single realm instance needs to be closed properly.**

**Comment by teddywest32** [comment] 2015-06-25 07:57
@beeender   This code is just for updating the database right? 
<code> realm.copyToRealmOrUpdate(RouteSchema); </code>

Can't we delete the database when the database is open? 

I have found a problem with my codes on my Main Activity that the activity is using the database code. And when i close the database the problem is 


06-25 07:31:18.612    4573-4577/com.myapp.jsonFetcher D/dalvikvm﹕ GC_CONCURRENT freed 1345K, 13% free 9772K/11172K, paused 8ms+19ms, total 143ms
06-25 07:31:18.702    4573-4573/com.myapp.jsonFetcher D/dalvikvm﹕ Trying to load lib /data/app-lib/com.myapp.jsonFetcher-1/librealm-jni.so 0x40cd56b8
06-25 07:31:18.702    4573-4573/com.myapp.jsonFetcher D/dalvikvm﹕ Added shared lib /data/app-lib/com.myapp.jsonFetcher-1/librealm-jni.so 0x40cd56b8
06-25 07:31:18.782    4573-4573/**com.myapp.jsonFetcher D/REALM﹕ jni: ThrowingException 8, Table is closed, and no longer valid to operate on., .**
06-25 07:31:18.782    4573-4573/**com.myapp.jsonFetcher D/REALM﹕ Exception has been throw: Illegal State: Table is closed, and no longer valid to operate on. **
06-25 07:31:18.792    4573-4573/com.myapp.jsonFetcher D/AndroidRuntime﹕ Shutting down VM
06-25 07:31:18.792    4573-4573/com.myapp.jsonFetcher W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40a71930)
06-25 07:31:18.822    4573-4573/com.myapp.jsonFetcher W/GAV4﹕ Thread[main,5,main]: Service unavailable (code=1), will retry.
06-25 07:31:18.902    4573-4573/com.myapp.jsonFetcher E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.jsonFetcher/com.myapp.jsonFetcher.MainActivity}: java.lang.IllegalStateException: Illegal State: Table is closed, and no longer valid to operate on.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Illegal State: Table is closed, and no longer valid to operate on.
            at io.realm.internal.TableView.nativeSize(Native Method)
            at io.realm.internal.TableView.size(TableView.java:129)
            at io.realm.RealmResults.size(RealmResults.java:305)
            at com.myapp.jsonFetcher.MainActivity$PlaceholderFragment.onCreateView(MainActivity.java:483)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:953)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1164)
            at android.app.Activity.performStart(Activity.java:5114)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
06-25 07:31:23.841    4573-4632/com.myapp.jsonFetcher W/GAV4﹕ Thread[Service Reconnect,5,main]: Service unavailable (code=1), using local store.

The problem appears when i close the database as

<code>
public RealmResults<RouteLocationSchema> RetriveLocation() 
{
realm = Realm.getInstance(context, "mydb.realm");
RealmResults<RouteLocationSchema> AllLocations = realm.where(RouteLocationSchema.class).findAll();
realm.close();
return AllLocations;
} </code>

Also the codes return with only 60 - 65 array of data's while there are ~240 array's of data.  I am unable to get the data's.

**Comment by beeender** [comment] 2015-06-25 08:40
* `copyToRealmOrUpdate`

We use proxy for the user defined RealmObject which means when you create a RealmObject by
```
MyModel model = new MyModel();
model.setInt(1);
```
It is not reflected to the Realm db yet.
You have to call `copyToRealm` or `copytToRealmOrUpdate` to write the data changes to Realm.
If you create your RealmObject like:
```
MyModel model = realm.createObject(MyModel.class);
model.setInt(1)
```
The proxy object will be created and your changes will be written to Realm without calling  `copyToRealm` or `copytToRealmOrUpdate`.

* The problem is you cannot use the `RealmResults` after the realm instance which is used to create that results closed.

Maybe you can handle the Realm instance in your activity's life cycle?

**Comment by beeender** [comment] 2015-06-29 01:43
I am closing this issue now. If you have any other support needed, `stackoverflow.com` would be a better place.
Thanks!!

**Closed by beeender** 2015-06-29 01:43 UTC
Labels: Pending, support
