### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by Kistamushken** [realm/realm-java#2027] opened 2016-01-04 12:17 UTC
Hey, guys. I'm getting loads of SIGSEGVs right now (Realm 0.87.1). Our app performs a lot of async queries and writes(we have a ViewPager with 10 elements, where each element is a RecyclerView). Basically, these elements are feeds where the same or different posts are sorted in different ways. Sometimes crash occurs when user just swings the ViewPager, sometimes it occurs when user restarts this fragment. 

RealmChangeListener is usually set in the onStart() method and removed in the onStop() method of a fragment. Btw, I tried commenting out removeChangeListeners, but it didn't really help.

Looking forward to your response, sadly right now this issue totally bricks our app :(

Here is the log:
[RealmLog.txt](https://github.com/realm/realm-java/files/77161/RealmLog.txt)

By the way, I've noticed that D/REALM: REALM_CHANGED realm:io.realm.HandlerController@537635c8 updating async queries, total: NUMBER goes higher and higher over time.

Small update: I am using Realm as a Singleton, but I when I encountered this problem I've tried switching to the opening Realm in onStart() and closing it in onStop(), but it also didn't help.

Btw, this scenario is much easier to reproduce on older devices and/or api versions (API 4.1.1)

**Comment by nhachicha** [comment] 2016-01-05 13:15
Hi @Kistamushken 
is it possible to share the APK and/or the code (even privately help@realm.io)
we'll try to investigate
Cheers,

**Comment by Kistamushken** [comment] 2016-01-05 16:19
@nhachicha I will send debug version of our apk to help@realm.io and provide you with a scenario to reproduce shortly shortly.

**Comment by Kistamushken** [comment] 2016-01-05 17:35
@nhachicha sent you the apk.

**Comment by cmelchior** [comment] 2016-01-28 15:36
We have just released 0.87.4 with a potential fix for this. We still haven't been able to reproduce the exact error you are reporting here, but upon investigation found something that appeared to be the root cause. So if you can test with 0.87.4 that would be much appreciated.

**Comment by Kistamushken** [comment] 2016-01-29 12:12
@cmelchior been testing my app with the new realm version(0.87.4) for the last day. Seems like you are right and the bug you've fixed in the core actually fixed this issue and #2021 all together. Thanks a lot guys. You are awesome :)

**Comment by cmelchior** [comment] 2016-01-29 12:22
Thank you for reporting back @Kistamushken. Sounds great. I'll close this issue then. Feel free to reopen if it re-appears.

**Closed by cmelchior** 2016-01-29 12:22 UTC
Labels: Help, Pending
