### ISSUE TITLE
Trying to catch a dead lock

### ISSUE THREAD

**Issue by RobertoArtiles** [realm/realm-java#1728] opened 2015-11-05 03:36 UTC
Hi there,

I'm trying to locate a dead-lock which is happening somewhere inside Realm.
By logging I found that I get an infinite ANR in ```onCreate()``` of the MainActivity on the line ```Realm.getDefaultInstance()```. Another place where it hangs is a worker thread on the line ```Realm.close()```.

Here is how the worker thread body looks like (without the domain details):
```java
Realm realm = null;
try {
    realm = Realm.getDefaultInstance();
    RealmResults<A> results = realm.where(A.class).findAll();
    realm.beginTransaction();
    for (int i = results.size() - 1; i >= 0; i--) {
        final A item = results.get(i);
        String value = item.getSomeStringValue();
        callSomeMethod(value); // this method throws an exception not related to realm when i == 1
    }
    realm.commitTransaction();
} finally {
    if (realm != null) {
        realm.close(); // hangs on this line based on the logs
    }
}
```

I was able to narrow down where exactly Realm.close() hangs. It is the line ```synchronized (BaseRealm.class)```:
```java
protected void lastLocalInstanceClosed() {
        // validatedRealmFiles must not modified while other thread is executing createAndValidate()
        synchronized (BaseRealm.class) {
            validatedRealmFiles.remove(configuration.getPath());
        }
        realmsCache.get().remove(configuration);
    }
}
```

Here is the sequence of actions accordingly to logs:

1. Application.onCreate() called and starts the worker thread
2. Worker thread is going through the items
3. MainActivity.onCreate() called and it hangs on Realm.getDefaultInstance()
4. Exception thrown in the worker thread, and it hangs on realm.close()
5. Infinite ANR in MainActivity

It's very hard to locate the problem because it's not 100% reproducible and time-dependent. If I remove transaction, or there is no exception then the dead-lock doesn't happen (could be just due to timing). Also, I have another running worker thread in background which uses realm. But it successfully finishes and doesn't hang on ```realm.close()```. 

I tried to reproduce it in a small project, but it didn't work out.

I hope this description could lead you to some ideas what could go wrong, or what I can check to locate the exact problem.

**Comment by beeender** [comment] 2015-11-05 03:51
@RobertoArtiles 
Thanks a lot for this information!
About `4. Exception thrown in the worker thread, and it hangs on realm.close()`
can you please let us know what exception has been thrown and where is it from?

**Comment by RobertoArtiles** [comment] 2015-11-05 04:02
It's NPE caused by new File(null) called in the method.

**Comment by beeender** [comment] 2015-11-05 04:04
@RobertoArtiles And what is the realm version you are testing?

**Comment by RobertoArtiles** [comment] 2015-11-05 04:06
Oh, of course. 0.84.1

**Comment by beeender** [comment] 2015-11-05 04:10
I think there is a problem `Realm.create` is synchronized on the wrong class `Realm` instead of `BaseRealm` . Thanks a lot for the feedback!! We will create a test case and fix the problem.

**Comment by RobertoArtiles** [comment] 2015-11-05 04:13
Sounds good. Hope it reproduces. I couldn't wrap my head around synchronization in Realm.java.

**Comment by yaming116** [comment] 2015-11-05 06:08
I has a same error.

```java
java.lang.NullPointerException:
io.realm.Realm.getColumnInfo(Realm.java:727)
io.realm.Realm.get(Realm.java:720)
io.realm.Realm.createObject(Realm.java:710)
io.realm.TeacherClassObjectRealmProxy.copy(TeacherClassObjectRealmProxy.java:735)
io.realm.TeacherClassObjectRealmProxy.copyOrUpdate(TeacherClassObjectRealmProxy.java:730)
io.realm.UserModuleMediator.copyOrUpdate(UserModuleMediator.java:161)
io.realm.Realm.copyOrUpdate(Realm.java:1130)
io.realm.Realm.copyToRealmOrUpdate(Realm.java:763)
io.realm.Realm.copyToRealmOrUpdate(Realm.java:808)
com.xuehai.xhenglistbrush.db.user.UserDB.createUpdateTeacher_aroundBody10(UserDB.java:96)
com.xuehai.xhenglistbrush.db.user.UserDB$AjcClosure11.run(UserDB.java:1)
org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
com.xuehai.xhenglistbrush.db.user.UserDB.createUpdateTeacher(UserDB.java:95)
com.xuehai.xhenglistbrush.user.InitActivity$7.processor(InitActivity.java:221)
com.xuehai.xhenglistbrush.user.InitActivity$7.processor(InitActivity.java:217)
com.zhitongyun.httpclient.NetworkClient.doInBackground(NetworkClient.java:175)
com.zhitongyun.httpclient.NetworkClient.doInBackground(NetworkClient.java:22)
com.zhitongyun.httpclient.utils.AppAsyncTask$2.java.lang.Object call()(AppAsyncTask.java:305)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
java.util.concurrent.FutureTask.run(FutureTask.java:137)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
java.lang.Thread.run(Thread.java:856)

```

**Comment by zaki50** [comment] 2015-11-05 08:25
@yaming116 I guess you are using `0.84.0` and that NPE is tracked in #1646 and fixed in #1648.
Please update Realm to `0.84.1` which includes the fix of the issue.

**Comment by yaming116** [comment] 2015-11-05 11:06
@zaki50 ok,thanks

**Comment by beeender** [comment] 2015-11-05 12:34
@RobertoArtiles  I can reproduce your dead lock now. There is a problem in your code, but surely we should fix it in the Realm side well. Before we release the new version with fix, you can just `cancelTransaction` when exception throws before close the Realm. Or just simply use `Realm.executeTransaction()` instead of calling `beginTransaction` and `commitTransaction`.

The problem is there are some complex logic mixed with our transaction lock and the java `BaseRealm` lock.

If you are interested, here is the test case to reproduce the issue:

```java
public void testOpenRealmWhileTransactionInAnotherThread() throws InterruptedException {
    final CountDownLatch realmOpenedInBgLatch = new CountDownLatch(1);
    final CountDownLatch realmClosedInFgLatch = new CountDownLatch(1);
    final CountDownLatch transBeganInBgLatch = new CountDownLatch(1);
    final CountDownLatch finishedLatch = new CountDownLatch(1);

    Thread thread = new Thread(new Runnable() {
        @Override
        public void run() {
            Realm realm = Realm.getInstance(testConfig);
            realmOpenedInBgLatch.countDown();
            try {
                realmClosedInFgLatch.await();
                realm.beginTransaction();
                transBeganInBgLatch.countDown();
                finishedLatch.await();
            } catch (InterruptedException e) {
                e.printStackTrace();
                return;
            }
            realm.close();
        }
    });
    thread.start();

    realmOpenedInBgLatch.await();
    testRealm.close();
    realmClosedInFgLatch.countDown();
    transBeganInBgLatch.await();

    testRealm = Realm.getInstance(testConfig);
    finishedLatch.countDown();
}
```

**Comment by RobertoArtiles** [comment] 2015-11-05 19:55
Great! Thanks. Seems like it fixed a problem for me.

**Comment by RobertoArtiles** [comment] 2015-11-05 20:11
@beeender But I'm just curious. Shouldn't realm.close() take care of open transactions and just simply cancel them, or is too intrusive?

**Comment by beeender** [comment] 2015-11-06 02:33
@RobertoArtiles `Realm.close()` will cancel the transaction only if that Realm is the last instance in the thread. We are sharing the same Realm instance in the same thread to make things faster.

So, I do think the `cancelTransaction` is necessary for most cases :)

**Comment by RobertoArtiles** [comment] 2015-11-06 05:14
Ok, thanks. Refactored everything to use transaction closures.

**Comment by RobertoArtiles** [comment] 2015-11-09 23:54
@beeender FYI error reproduced again even after I replaced all the transactions either with ```realm.executeTransaction()``` or ```realm.cancelTransaction()``` in case of the error.

The exception happens in the same place (in the worker thread), but now it's wrapped in transaction block. MainActivity still stops with ANR on realm.getDefaultInstance(). Although, worker thread doesn't stop on realm.close() anymore.

**Closed** 2015-11-11 08:32 UTC
Labels: bug, P1
