### ISSUE TITLE
Realm query for "case insensitive"  string is actually not case insensitive for Unicode letters

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#1299] opened 2015-07-16 16:26 UTC
The exact problem is that I specified that the query is not case sensitive, but I have the following string

"Éjszakai műsor"

And with `é` it returns nothing, but with `É` it returns the value as intended.

**Comment by kneth** [comment] 2015-07-17 06:09
Your observation is correct, and is covered in the [FAQ](https://realm.io/docs/java/latest/#case-insensitive-queries). We intend to investigate ICU to be able to support a broader set of letters - both for queries and sorting (see https://github.com/realm/realm-java/issues/1031).

**Comment by Zhuinden** [comment] 2015-07-17 10:56
Ah, thank you. I guess I should have noticed that earlier. Technically if I just search insensitively for both the lower case and the capitalized versions, then I should find most of what I'm looking for - or at least that's how I'll work around it in the meantime.

**Comment by emanuelez** [comment] 2015-07-21 07:45
Closing this as a duplicate of #1031

**Closed by emanuelez** 2015-07-21 07:45 UTC
Labels: Pending, support
