### ISSUE TITLE
Realm Db returns no db items

### ISSUE THREAD

**Issue by jvm12345** [realm/realm-java#2817] opened 2016-05-16 16:06 UTC
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
> ********** BUG ************

Android App:
Realm database fails to return data after app goes to background or in sleep for sometime and comes back foreground. It happens all the time usually app stays in background for overnight but also happens when it goes to background and comes back or switches screens too fast. It could be that Realm not fetching data when fast switching or frequent requests are made in succession.

#### Goal

> What do you want to achieve?
Realm to return data reliably in all cases.
#### Expected Results

Realm to return data reliably in all cases.

#### Actual Results
Realm does not return data at times.

>  E.g. full stack trace with exception
No exception but findAllSorted() and findAllSortedAsync() fail all the time.

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

realmResults = realm.where(ItemModel.class).findAllSorted("title");

RealmResults<ItemModel> itemModels = realm.where(ItemModel.class).findAllSortedAsync("title");

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
0.90.0
Android Studio version: ? 2.2.1

Which Android version and device: ?
Samsung S4, Tab 3, Lenovo Tab2, LG G2 (OS 4.x, 5.x)

**Comment by cmelchior** [comment] 2016-05-16 16:45
Hi @jvm12345 

The above code sample should work when run, so I am guessing it is related to somethinge else. Can your provide the broader context? Perhaps by reproducing it in a sample project or giving us access to your project?

**Comment by jvm12345** [comment] 2016-05-18 05:14
Hi cmelchior,

Thanks for getting back on this one. Here is code:

// Realm wrapper
public class RealmDbHelper {

    private static RealmDbHelper mInstance = null;
    private static int SCHEMA_VERSION = 1;

    public static RealmDbHelper getInstance() {
        if(mInstance == null)
            mInstance = new RealmDbHelper();
        return mInstance;
    }

    private RealmDbHelper(){
        RealmConfiguration config = new RealmConfiguration.Builder(SparkPayApplication.getInstance())
                                        .schemaVersion(SCHEMA_VERSION)
                                        .build();
        Realm.deleteRealm(config);
        Realm.setDefaultConfiguration(config);
    }

    public Realm getRealm() {
        return Realm.getDefaultInstance();
    }


// fetching items from realm
public RealmResults<ItemModel> getAllItemsFromDb(boolean sorted) {
       Realm realm = RealmDbHelper.getInstance().getRealm();
        RealmResults realmResults;
        if(sorted) {
            realmResults = realm.where(ItemModel.class).findAllSorted("title");
        } else {
            realmResults = realm.where(ItemModel.class).findAll();
        }
        mRealm = realm;
        return realmResults;
    }
}

-  What is the best way to pass RealmObjects across async tasks or async tasks to main thread? Also is there a way or specific method call to clone or change RealmObject to normal/pojo object once they are fetched from db (like in-memory objects and hence can be passed around)
- Any api/syntax for matching regex or wildcard while querying for table field (eg. "title", "Cat*")
- when do we expect to have 1.x release or stable release (i believe 0.x.x is beta).

**Comment by emanuelez** [comment] 2016-05-18 08:13
The code above should work, even if the `RealmDbHelper` class is not really needed. Can you produce a small sample project showing the issue?

> What is the best way to pass RealmObjects across async tasks or async tasks to main thread? Also is there a way or specific method call to clone or change RealmObject to normal/pojo object once they are fetched from db (like in-memory objects and hence can be passed around)

You can use async queries to perform queries in another thread and have the result handed to you in the original thread. All the complexity is handled by Realm. You can also detach objects from realm and make an in-memory copy of them using `copyFromRealm()` (https://realm.io/docs/java/latest/api/io/realm/Realm.html#copyFromRealm-E-). Please notice that this is not the suggest way to do it because you will lose all the nice auto-updating properties of Realm results.

> Any api/syntax for matching regex or wildcard while querying for table field (eg. "title", "Cat*")

We don't support wildcards but we offer some basic methods such as `beginsWith()` (https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#beginsWith-java.lang.String-java.lang.String-) which covers your specific example.

> when do we expect to have 1.x release or stable release (i believe 0.x.x is beta).

As soon as it is ready. As you know we give top priority to support so it's impossible for us to make a schedule since timings depend on the support load.

**Comment by jvm12345** [comment] 2016-05-23 19:29
Thanks Emanulez for the details, will try your suggestions. 
I've been in the process of verifying/testing on various devices, seems low frequency occurrences, will keep you updated in case I see it again. For the relatively larger db rows (100s to 1000s), do you suggest async api (eg findAllAsync) or either way is fine.

Thanks much.

Best,
Jignesh

**Comment by cmelchior** [comment] 2016-05-25 10:09
Either is probably fine, but if you are supporting a wide variety of devices, then using `findAllAsync` is the safer approach, as you are guaranteed it will not block the UI thread.

**Comment by emanuelez** [comment] 2016-06-06 08:21
It looks like this issue can be closed. Please contact us if it needs to be re-opened! :)

**Comment by jvm12345** [comment] 2016-06-25 05:38
Hello emanuelez,

I've been observing since last few days and i am afraid, I still see the issue. As I mentioned before, realm db is not fetching any data if device and app stay in background for longer period of time esp. after overnight next day. Please suggest what's the best way to resolve this, there is no error and I've no way to see if default.realm file has anything. Can you please suggest how can I see default.realm on production devices since we don't have unlocked devices. Appreciate your help a lot.

Thank you very much.

Best
Jignesh
CapitalOne

**Comment by jvm12345** [comment] 2016-06-28 15:58
Can you please reopen the issue? Is there a way to create realm.default in SD card or accessible part of device?

**Comment by mbberezovsky** [comment] 2016-07-14 09:31
I can join, there is still an issue.
During some period of app background activity (device is sleeping) some realm objects become totally unavailable. There are many objects of several classes in my application (may happen to tens of thousands). More objects there are - frequency is more often (seems like that, only users having more than 10K objects start experiencing problem).

some code for you:
declaration of the class:
`public abstract class GenericObjectDAO<T extends RealmObject>`
nothing specific.
Occasionally after some period of time of inactivity this method starts returning empty list. Also nothing specific. Not always but still happens.
   ` public List<T> ListAll(Class<T> pClass)
    {
	    return AppRealm.where(pClass).findAll();
    }`

the problem might be related to the fact i only open realm instance once, when app starts, and close it only onTerminate() application.

Should i probably reopen/close it more often?
What is your recommendation/advice Christian?

**Comment by beeender** [comment] 2016-07-14 09:37
@jvm12345 Sorry for missing your comments. We haven't seen the problem you mentioned before. Would you please make a simple project which reproduce the issue? You can send it to help@realm.io (and with some instructions about how to reproduce it.)

Thanks!

**Comment by beeender** [comment] 2016-07-14 09:39
and BTW, what does "realm db is not fetching any data if device and app stay in background for longer period of time esp" mean?

the query gives you an empty results?

**Comment by jvm12345** [comment] 2016-07-20 22:55
That's what exactly going on, findAll() does not return any query data. So as suggested earlier, I've added addChangeListener with findAllAsync() call which also does not return any data. Please note that I've *not* kept single realm object open as it's been seen by mbberezovsky but close realm object once query is done. Also added code in this thread above: jvm12345 commented on May 17 • edited

**Comment by beeender** [comment] 2016-07-21 01:37
*findAll() does not return any query data.*  is the data saved in another thread? if yest, the updated version won't seen in the thread which is calling `findAll()` until the looper event arrived. You probably need to use change listener to wait for it.

If you can share a simple project to demonstrate the problem, we will be happy to take a look.

Thanks!

**Comment by jvm12345** [comment] 2016-07-28 20:57
Thanks for the suggestions. Can you please explain about last part: 
    "the updated version won't seen in the thread which is calling findAll() until the looper event arrived."

Also per documentation, findAll() is sync call, that means it will return data in the same call/thread and also not the stale or old data, correct? Seems the query needs to be fired from UI thread, wonder if there is any better way or updates to this in recent releases?

**Comment by stk1m1** [comment] 2016-07-29 05:59
Hi @jvm12345, 

> findAll() is sync call, that means it will return data in the same call/thread and also not the stale or old data.

When you spawn a Realm instance in background Looper thread, it could have older, stale data. When new, updated data arrive and is saved in another thread, the background Realm will receive updated data _automatically_ when background Looper event arrive. 

I've been following this comment, and you and I can see we have requested multiple time for a small, sample project to diagnose your issue, but nothing so far has handed to our side. In order to provide best possible support, please consider share with us one. I'll keep open this for now.

**Comment by kneth** [comment] 2016-08-06 06:10
@jvm12345 Do you have a chance to share a small sample project so we have solve the issue?

**Comment by kneth** [comment] 2016-08-16 07:05
@jvm12345 Can you provide more information so we can help you?

**Comment by kneth** [comment] 2016-08-24 07:46
I am closing the issue since @jvm12345 hasn't provided further information or a sample project. You are welcome to reopen the issue when you have relevant information.

**Closed by kneth** 2016-08-24 07:46 UTC
Labels: S:Waiting For User, T:Help

**Comment by ssunkar** [comment] 2016-09-20 06:23
Hi

findAll() does not return any query data. So as suggested earlier, I've added addChangeListener with findAllAsync() call which also does not return any data.

Below is my code sample.
I am calling getTicketPhotosToSave () from asynctask.  Though there records in realm, its not returning any data from DB.

 RealmResults<TicketPhoto> ticketPhotoRealmResults = ticketPhotoDB.getTicketPhotosToSave();


public RealmResults<TicketPhoto> getTicketPhotosToSave (){
        return realm.where(TicketPhoto.class).equalTo("IsModified", true).findAll();

    }

**Comment by Zhuinden** [comment] 2016-09-20 06:57
Does this happen on the UI thread?

**Comment by ssunkar** [comment] 2016-09-20 17:08
No.. I am updating realm object from main thread like this.

public void updatePhoto(final int ticketID) {
        realm.beginTransaction();
        RealmResults<TicketPhoto> ticketPhotos = realm.where(TicketPhoto.class).equalTo("TicketID", ticketID).findAll();
        for (TicketPhoto ticketPhoto : ticketPhotos) { 
            ticketPhoto.IsModified = true;
        }
        realm.commitTransaction(); 
    }

At same time one background service is running for every five minutes and keeps checking for any objects having IsModified flag as true. From my background service(IntentService), am using AsyncTask and in doInBackground, am trying to get those IsModified records and  I assume realm should pick those records and update with my server. Used the below code to get data from realm. 

public RealmResults getTicketPhotosToSave (){
return realm.where(TicketPhoto.class).equalTo("IsModified", true).findAll(); 
}

When am still in the same Photo activity where I save photo to realm with IsModified flag as true, realm in background service is not picking those records. But when I destroy the app and just run it again, service is now picking those records. Am not sure if am doing something wrong here.
