### ISSUE TITLE
RealmMigrationNeededException after renaming an indexed field and adding a new field with the old name

### ISSUE THREAD

**Issue by edgars-supe** [realm/realm-java#4093] opened 2017-01-23 13:20 UTC
Hello!
Recently, I had to rename an indexed field and add a new field with the same name as the old name for the existing one, but without an index. Everything was okay until we noticed that users are getting an exception and can't even launch the app. 
Stack trace:
```java
io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 13 but was 12
    at io.realm.EventRealmProxy.validateTable(EventRealmProxy.java:701)
    at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:78)
    at io.realm.Realm.initializeRealm(Realm.java:348)
    at io.realm.Realm.createAndValidate(Realm.java:313)
    at io.realm.Realm.createInstance(Realm.java:278)
    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
    at io.realm.Realm.getDefaultInstance(Realm.java:209)
    at [redacted]
```
Event class before the changes:
```java
public class Event extends RealmObject implements Parcelable, MediaObject {
    @PrimaryKey
    private long id;
    @Index
    private int channelId;
    private Channel channel;
    private String title;
    private String description;
    private String picture;
    private Long timeStartUnix;
    private Long timeStopUnix;
    private String category1;
    private String sysStatus;
    private boolean isArchive;
    private String continueWatchingTime;
    //...
}
```
And after:
```java
public class Event extends RealmObject implements Parcelable, MediaObject {
    @PrimaryKey
    private long id;
    @Index
    private int channelXprsId;
    private Long channelId;
    private Channel channel;
    private String title;
    private String description;
    private String picture;
    private Long timeStartUnix;
    private Long timeStopUnix;
    private String category1;
    private String sysStatus;
    private boolean isArchive;
    private String continueWatchingTime;
    //...
}
```
Here's the relevant part of the migration:
```java
if(oldVersion == 16) {
    schema.get("Event")
        .renameField("channelId", "channelXprsId")
        .addField("channelId", Long.class);
    oldVersion++;
}
```
While debugging, I noticed that the static FIELD_NAMES list contains all 13 columns, but during validation I saw that the Table object has only 12 columns (from Table.toString(), I assume), which is what the issue is about.
I can only reproduce it on one device currently, and it happened when installing the same version of the application over the old one, however it told me that the update is incompatible and performed a clean install, so, as far as I know, a migration shouldn't even have happened. Furthermore, I can't reproduce it while upgrading from the previous app version to the new one, yet there are a number of such crashes from real users, so we want to get a bugfix out as soon as possible.
Realm version(s): 2.3.0 (reproducable in 2.1.1 as well)
Realm sync feature enabled: no
Android Studio version: 2.2.3
Which Android version and device: API >= 19, multiple devices

**Comment by kneth** [comment] 2017-01-24 09:33
When did you see that the Table object had 12 columns? If it is before the code snippet, it is fine but after the code snippet (and if `oldVersion` is 17), then there is something wrong (17 as `oldVersion` is incremented in the code snippet).

Are you sure that the old Realm file was removed when it did the clean installation?

**Comment by edgars-supe** [comment] 2017-01-24 10:10
I saw the 12 column info appear during debugging in ```validateTable()```.
```java
public static EventColumnInfo validateTable(SharedRealm sharedRealm, boolean allowExtraColumns) {
        if (sharedRealm.hasTable("class_Event")) {
            Table table = sharedRealm.getTable("class_Event"); //table: "The Table class_Event has 'id' field as a PrimaryKey, and contains 12 columns: channelId, id, channel, timeStartUnix, timeStopUnix, title, description, category1, sysStatus, picture, isArchive, continueWatchingTime. And 108 rows."
            final long columnCount = table.getColumnCount(); //columnCount: 12
            if (columnCount != 13) {
                if (columnCount < 13) {
                    throw new RealmMigrationNeededException(sharedRealm.getPath(), "Field count is less than expected - expected 13 but was " + columnCount);
                }
    //...
```
Which gets called in ```validateTable``` in DefaultRealmModuleMediator.java. Realm version is 17 at that time.

**Comment by kneth** [comment] 2017-01-26 09:13
We need to add a unit test which resembles your use case (I can't see one in https://github.com/realm/realm-java/blob/master/realm/realm-library/src/androidTest/java/io/realm/RealmMigrationTests.java).

**Comment by kneth** [comment] 2017-01-30 15:04
I have tried - without luck - to reproduce the issue. Please take a look at #4123 and tell me if your app does migration differently. I have attached a screenshot of the Realm Browser showing the asset file.

![screen shot 2017-01-30 at 15 59 43](https://cloud.githubusercontent.com/assets/1225363/22428008/aab0a750-e705-11e6-8700-f90ebad6573b.png)

**Comment by edgars-supe** [comment] 2017-01-30 15:16
The field that is renamed is indexed in my model. Maybe the fact that the renamed ```channelId``` is an ```int```, and the new one is a ```Long``` has got something to do with it?

**Comment by kneth** [comment] 2017-01-30 16:58
Good points. 

`int` -> `Long` makes it nullable (or not `@Required`) but otherwise it is the same type.

**Comment by bmeike** [comment] 2017-02-02 19:45
Added two new unit tests, for the described scenarios, in: #4143

**Comment by kneth** [comment] 2017-02-07 10:22
I am closing the issue since #4142 wasn't able to reproduce it.

**Closed by kneth** 2017-02-07 10:22 UTC
Labels: Reproduction Required, S:In Progress, T:Help
