### ISSUE TITLE
SIGSEGV(SEGV_MAPERR) SIGSEGV(SEGV_ACCERR)

### ISSUE THREAD

**Issue by deco-ding** [realm/realm-java#4004] opened 2017-01-09 03:27 UTC
1 #00 pc 00086598 /data/app-lib/com.netease.ntespm-1/librealm-jni.so [armeabi-v7a]
2 #01 pc 000a9d37 /data/app-lib/com.netease.ntespm-1/librealm-jni.so [armeabi-v7a]
3 #02 pc 0005ec8d /data/app-lib/com.netease.ntespm-1/librealm-jni.so [armeabi-v7a]
4 java:
5 io.realm.internal.SharedRealm.void nativeSetVersion(long,long)(Native Method)
6 io.realm.internal.SharedRealm.void setSchemaVersion(long)(SharedRealm.java:236)
7 io.realm.BaseRealm.void setVersion(long)(BaseRealm.java:496)
8 io.realm.Realm.void initializeRealm(io.realm.Realm)(Realm.java:323)
9 io.realm.Realm.io.realm.Realm createAndValidate(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices[])(Realm.java:299)
10 io.realm.Realm.io.realm.Realm createInstance(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices[])(Realm.java:264)
11 io.realm.RealmCache.io.realm.BaseRealm createRealmOrGetFromCache(io.realm.RealmConfiguration,java.lang.Class)(RealmCache.java:143)
12 io.realm.Realm.io.realm.Realm getDefaultInstance()(Realm.java:209)

![image](https://cloud.githubusercontent.com/assets/4246885/21756641/b2d90d9e-d65e-11e6-84df-501c09dfd998.png)

**Comment by beeender** [comment] 2017-01-09 04:48
What is the Realm version for the above backtrace?

**Comment by deco-ding** [comment] 2017-01-09 04:50
@beeender beeender realm version:2.2.1

**Comment by beeender** [comment] 2017-01-09 04:56
Decoded backtrace:

```
1 #00 pc 00086598 /data/app-lib/com.netease.ntespm-1/librealm-jni.so [armeabi-v7a] realm::ArrayString::set(unsigned int, realm::StringData)
2 #1 pc 000a9d37 /data/app-lib/com.netease.ntespm-1/librealm-jni.so [armeabi-v7a] realm::Group::do_get_or_add_table(realm::StringData, bool (*)(realm::Spec const&), void (*)(realm::Table&), bool*)
3 #2 pc 0005ec8d /data/app-lib/com.netease.ntespm-1/librealm-jni.so [armeabi-v7a] (anonymous namespace)::create_metadata_tables(realm::Group&)
4 java:
5 io.realm.internal.SharedRealm.void nativeSetVersion(long,long)(Native Method)
6 io.realm.internal.SharedRealm.void setSchemaVersion(long)(SharedRealm.java:236)
7 io.realm.BaseRealm.void setVersion(long)(BaseRealm.java:496)
8 io.realm.Realm.void initializeRealm(io.realm.Realm)(Realm.java:323)
9 io.realm.Realm.io.realm.Realm createAndValidate(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices[])(Realm.java:299)
10 io.realm.Realm.io.realm.Realm createInstance(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices[])(Realm.java:264)
11 io.realm.RealmCache.io.realm.BaseRealm createRealmOrGetFromCache(io.realm.RealmConfiguration,java.lang.Class)(RealmCache.java:143)
12 io.realm.Realm.io.realm.Realm getDefaultInstance()(Realm.java:209)
```

**Comment by beeender** [comment] 2017-01-09 04:58
Same bt with #3561 Very much like the same bug. @kneth , dup it?

**Comment by Zhuinden** [comment] 2017-01-09 07:50
This looks like that Samsung bug you guys are fixing

**Comment by kneth** [comment] 2017-01-09 08:34
Yes, it is a duplicate of #3651 - at least the crash is identical. From the device list from @deco-ding it looks like the same devices. I'll close the issue - @deco-ding please follow #3651.

**Comment by deco-ding** [comment] 2017-01-09 08:41
@kneth  ok thx

**Closed** 2017-01-09 10:05 UTC
Labels: T:Duplicate

**Comment by Zhuinden** [comment] 2017-03-30 12:04
https://github.com/realm/realm-java/pull/4402 might fix this once it's merged
