### ISSUE TITLE
Blackberry Q10: Function not implemented in io_realm_internal_SharedGroup.cpp line 113

### ISSUE THREAD

**Issue by biftekman** [realm/realm-java#3184] opened 2016-07-14 10:06 UTC
Crashlytics reports an issue with Blackberry Q10,
Running Android 4.3

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Function not implemented in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SourceFile)
       at io.realm.internal.SharedGroup.openSharedGroupOrFail(SourceFile:95)
       at io.realm.internal.SharedGroup.(SourceFile:74)
       at io.realm.internal.SharedGroupManager.(SourceFile:49)
       at io.realm.BaseRealm.(SourceFile:81)
       at io.realm.Realm.(SourceFile:140)
       at io.realm.Realm.createAndValidate(SourceFile:240)
       at io.realm.Realm.createInstance(SourceFile:220)
       at io.realm.RealmCache.createRealmOrGetFromCache(SourceFile:126)
       at io.realm.Realm.getDefaultInstance(SourceFile:166)

Maybe related to #3178 or #1380 ?

**Comment by Zhuinden** [comment] 2016-07-14 11:52
Duplicate of https://github.com/realm/realm-java/issues/3178

What version of Realm are you using?

**Comment by biftekman** [comment] 2016-07-14 11:55
Using 1.0.0

**Comment by Zhuinden** [comment] 2016-07-14 11:57
In that case the core upgrade to 1.2.0 is what broke it, that'll help the Realm guys a lot, thanks :)

**Comment by beeender** [comment] 2016-07-15 03:32
Close this and dup to #3178 
I will look into this when fix the adb issue with my z10 ... it is not working after android toolchain updates....

**Closed by beeender** 2016-07-15 03:32 UTC
Labels: T:Duplicate
