### ISSUE TITLE
Could not initialize the Realm Object Server

### ISSUE THREAD

**Issue by anujjpandey** [realm/realm-java#5814] opened 2018-03-07 19:02 UTC
#### Goal

> Checking the compatibility with android O

#### Actual Results

> Getting ```
```
03-07 19:38:34.464 8999-8999/com.automotive.tracker E/zygote: No implementation found for void io.realm.SyncManager.nativeInitializeSyncManager(java.lang.String) (tried Java_io_realm_SyncManager_nativeInitializeSyncManager and Java_io_realm_SyncManager_nativeInitializeSyncManager__Ljava_lang_String_2)


Could not initialize the Realm Object Server
                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5770)
                                                                          at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
                                                                       Caused by: io.realm.exceptions.RealmException: Could not initialize the Realm Object Server
                                                                          at io.realm.internal.SyncObjectServerFacade.init(SyncObjectServerFacade.java:60)
                                                                          at io.realm.Realm.init(Realm.java:249)
                                     
```

```

java.lang.NullPointerException: Attempt to invoke interface method 'io.realm.SyncUser io.realm.UserStore.getCurrent()' on a null object reference
                                                                          at android.app.ActivityThread.handleCreateService(ActivityThread.java:3376)
                                                                          at android.app.ActivityThread.-wrap4(Unknown Source:0)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1701)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'io.realm.SyncUser io.realm.UserStore.getCurrent()' on a null object reference
 
```
```

#### Code Sample
 Realm.init(getApplicationContext());

#### Version of Realm and tooling
Realm version(s): 4.3.4 
Realm sync feature enabled: yes

Android Studio version: 3.0.1

Which Android version and device: 8.1.0- 27

**Comment by cmelchior** [comment] 2018-03-08 07:02
We should work fine on Oreo. My guess is that somehow an old version of Realm without Sync was mixed with a new install of one with Sync.

I would try by:
- Clean out all local caches
- Rebuild app
- Manually uninstall the app on the device
- Install the app again on the device.

**Comment by cmelchior** [comment] 2018-03-14 12:45
I assume the above solved your issue. If not, feel free to reopen.

**Comment by funeasysoft** [comment] 2018-03-15 05:10
I had same problem.
but, I solved it.
I should initialized Realm.

```
public class MyApplication extends Application {
  @Override
  public void onCreate() {
    super.onCreate();
    Realm.init(this);
  }
}
```
https://realm.io/docs/java/latest/#initializing-realm

**Comment by Zhuinden** [comment] 2018-03-18 19:38
@cmelchior you know, I kinda wonder if multidex + static initializer block can cause trouble: https://github.com/realm/realm-java/blob/ddbebcb97a9b86ed458dece0e75143c60421e272/realm/realm-library/src/main/java/io/realm/internal/ObjectServerFacade.java#L36-L53

**Comment by anujjpandey** [comment] 2018-04-06 09:33
@cmelchior tried your solution but didn't worked for me

**Comment by cmelchior** [comment] 2018-04-06 09:56
Are you using multidex?

**Comment by anujjpandey** [comment] 2018-04-30 09:29
No we are not using mutidex

**Comment by cmelchior** [comment] 2018-06-29 10:33
Since this has not been reported by anyone else and we cannot reproduce it, I'll close this issue. If you can reproduce this in a sample project, feel free to reopen so we can investigate it.

**Closed by cmelchior** 2018-06-29 10:33 UTC
Labels: O:User, Reproduction Required, T:Help
