### ISSUE TITLE
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: io/realm/DefaultRealmModule.class

### ISSUE THREAD

**Issue by vamshikhoslalabs** [realm/realm-java#4452] opened 2017-04-07 12:32 UTC
**In my app:**

```java
Realm.init(this);
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
    .name("myrealm.app")
    .modules(Realm.getDefaultModule(),new SampleRealmModule())
    .schemaVersion(1)
    .build();

Realm.setDefaultConfiguration(realmConfiguration);
```

**In my library**

```java
@RealmModule(library = true,allClasses = true)
public class SampleRealmModule {

}
```

**Comment by istx25** [comment] 2017-04-07 17:45
Hi @vamshikhoslalabs. Would you be able to provide us with the following information?

- Realm version(s): ?
- Realm sync feature enabled: yes/no
- Android Studio version: ?
- Which Android version and device: ?

As well as a sample project that demonstrates the issue (if possible).

Thanks.

**Comment by mhdtouban** [comment] 2017-04-08 21:12
Same issue happening with me!
Realm version(s): 3.1.1
Realm sync feature enabled: no
Android Studio version: 2.3.1
Android version :7.1.2

**Comment by vamshikhoslalabs** [comment] 2017-04-10 06:24
Hi @istx25 here are details :

Realm version : 3.1.1
Realm sync feature enabled : no
Android Studio version : 2.3
Android version : 7.1

**Comment by zaki50** [comment] 2017-04-10 11:20
Hi @vamshikhoslalabs and @mhdtouban 

Thank you for your reporting.

We have a sample project that uses library project. https://github.com/realm/realm-java/tree/master/examples/moduleExample
Do you see any differences from your project?

And could you provide small sample project which reproduce this issue?

**Comment by mhdtouban** [comment] 2017-04-13 08:33
HI @zaki50 I already followed the module example and the app was working fine until I updated to latest support library version to 25.2. I had to revert back to 25.0.0

**Comment by kneth** [comment] 2017-04-24 09:30
@mhdtouban Thanks for the feedback. We need to investigate a bit further.

**Comment by vamshikhoslalabs** [comment] 2017-04-25 11:50
@kneth Hi kneth i'm working on a Android SDK i'm using realm as a db library. Now i'm trying to share my SDK as a aar file to the developers, even they are using realm as a db library. While initializing my library by developers it give my instance as the default instance to the developers  when they call Realm.getDefaultInstance. Can you please give some example in my current scenario. Thank you.

**Comment by kneth** [comment] 2017-04-26 09:31
@vamshikhoslalabs We don't have a simple solution for your case. We load the `.so` file when `Realm.init()` is called. Deep down, `dlopen()` is called, and I can easily imagine that loading the same `.so` file in different version will lead to random crashes. Even for `.so` files at the same version but different locations, I think you can run into troubles. So if only one call to `Realm.init()` is performed (either by your SDK or the app), your chances are better.

**Comment by vamshikhoslalabs** [comment] 2017-04-26 09:47
@kneth Hey kneth I tried removing the Realm.init() call from my SDK. Still the developer is facing the issue of schema not part of realm configuration.

**Comment by vamshikhoslalabs** [comment] 2017-04-26 09:51
@kneth Can I use Realm for developing an SDK can you tell me that so I could stop using realm as a ORM library for my SDK.

**Comment by kneth** [comment] 2017-04-26 10:02
@vamshikhoslalabs What I was trying to say is that loading `.so` files isn't trivial. Can you provide a example project which shows this? If you don't wish to shared it publicly, you can send it to help@realm.io.

**Comment by vamshikhoslalabs** [comment] 2017-04-26 10:12
@kneth I would like to talk directly so I can understand what is that i'm doing wrong my end or from developers end. Kindly let me know if it is possible.

**Comment by Zhuinden** [comment] 2017-04-26 10:25
I love Realm but personally if I were making an SDK, I probably wouldn't use Realm as persistence because of possibility of causing version mismatch. 

But even if you do, you definitely shouldn't set the default configuration from the SDK, and you need to expose your RealmObjects via a `@RealmModule`

**Comment by vamshikhoslalabs** [comment] 2017-04-26 10:27
@Zhuinden Thank you for you message. I was not clear in this part "But even if you do, you definitely shouldn't set the default configuration from the SDK, and you need to expose your RealmObjects via a @RealmModule" I have exposed my RealmObject via a `@RealmModule `

**Comment by Zhuinden** [comment] 2017-04-26 10:29
Then developer needs to create a configuration where he sets the modules as `.module(Realm.getDefaultModule(), new LibraryModule())`

**Comment by vamshikhoslalabs** [comment] 2017-04-26 10:29
@Zhuinden  There are scenarios where developers wont be using realm as an ORM library in that case I should set the default configuration from the SDK right otherwise it will break at some point saying no Realm configuration defined.

**Comment by Zhuinden** [comment] 2017-04-26 10:30
@vamshikhoslalabs ....don't use `Realm.getDefaultInstance()` if you are developing SDK, use `Realm.getInstance(realmConfiguration)`

**Comment by vamshikhoslalabs** [comment] 2017-04-26 10:32
@Zhuinden Ok was using it Realm.getDefaultInstance will change it to Realm.getInstance(realmConfiguration).

**Comment by vamshikhoslalabs** [comment] 2017-04-27 05:56
@Zhuinden Hi Zhuinden can you check my project once so you could give me some inputs on how to use the Realm for SDKs and help me integrate my SDK with developers. 
Thank you.

**Comment by Zhuinden** [comment] 2017-04-27 06:44
is the original error `DefaultRealmModule.class duplicate` gone?

**Comment by vamshikhoslalabs** [comment] 2017-04-27 06:51
@Zhuinden "is not part of the schema for this Realm" error is not being thrown after removing my SDKs `Realm.init(context)` and by the I have a RealmObject class which I have to expose to the developers. In your previous comment you mentioned not to give the RealmModule, but I wont expose the RealmModule how can the developers send the data releated to that object.

**Comment by Zhuinden** [comment] 2017-04-27 07:09
if you have to expose the RealmObject, then yes, you do need to provide the module :stuck_out_tongue:

**Comment by vamshikhoslalabs** [comment] 2017-04-27 07:12
@Zhuinden Ok cool. @Zhuinden I have asking you guys if you help me in setting up few things from my end. It would be better if we talk on Skype or some other platform so that it would be really helpful for me.

**Comment by cmelchior** [comment] 2017-10-24 12:31
Closing as this issue could not be reproduced, nor does it seem others are running into it. Feel free to re-open if more info become available about this.

**Closed by cmelchior** 2017-10-24 12:31 UTC
Labels: Reproduction Required, T:Bug
