### ISSUE TITLE
Realm (6.0.2) not working with Unity Library module.

### ISSUE THREAD

**Issue by joeShuff** [realm/realm-java#6797] opened 2020-04-06 13:38 UTC
#### Goal
I want to be able to have the unity library as an element of my app, and be able to use realm to store data locally.

#### Actual Results
The solution does build, however when I go to open the `UnityPlayerActivity` I get the following error.
```
04-06 13:44:25.285 6012-6012/com.joeshuff.alanunitytest E/Unity: Failed to load 'libmain.so', the application will terminate.
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.joeshuff.alanunitytest-1/base.apk"],nativeLibraryDirectories=[/data/app/com.joeshuff.alanunitytest-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libmain.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:988)
        at com.unity3d.player.UnityPlayer.<clinit>(Unknown Source)
        at com.unity3d.player.UnityPlayerActivity.onCreate(UnityPlayerActivity.java:41)
        at com.joeshuff.alanunitytest.MainUnityActivity.onCreate(MainUnityActivity.kt:34)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5258)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-06 13:44:25.405 6012-6028/com.joeshuff.alanunitytest I/art: Background sticky concurrent mark sweep GC freed 30325(2MB) AllocSpace objects, 16(256KB) LOS objects, 17% free, 9MB/11MB, paused 9.006ms total 69.188ms
04-06 13:44:26.064 6012-6043/com.joeshuff.alanunitytest I/FirebaseCrashlytics: Crashlytics report upload complete: 5E8B241200ED-0001-177C-4A739013D48F
04-06 13:48:33.165 6012-6012/com.joeshuff.alanunitytest I/Process: Sending signal. PID: 6012 SIG: 9
```

If I remove the realm import lines 
```
classpath "io.realm:realm-gradle-plugin:6.0.2"
apply plugin: 'realm-android'
```

It opens fine. I have tried the solutions mentioned in #2518 but no luck. For now I have disabled realm as it's not needed right now, but it will be needed soon.

#### Version of Realm and tooling

Realm version(s): 6.0.2

Realm Sync feature enabled: No

Android Studio version: IntelliJ 2019.3.3

Android Build Tools version: 29.0.1

Gradle version: 3.4.2

**Comment by cmelchior** [comment] 2020-04-06 13:44
That should work. Realm and Unity are just two separate native libraries. One problem I have noticed though is that the Android Build process can be a bit fickle if the native binaries do not match completely with whatever device the app is being deployed on.

The error message you see just say that the Unity library is not part of the APK. I would start by checking that.

Then I would check which ABI is actually being shipped in the app. I suspect it might be caused by the device perhaps trying to load either 32- or 64-bit variants of the native code and Unity does not provide those for whatever reason.

**Comment by joeShuff** [comment] 2020-04-06 14:16
I checked on different devices (API 29 Android 10 and API 25 Android 7.1.1) and it works fine. However, the above error was on a tablet (API 22 Android 5.1). Strange. Thanks for your reply, it made me realise I needed to try on another device.

Now to find out whether I need to raise the min sdk or if some modifications can be made to the unity build

**Comment by cmelchior** [comment] 2020-05-07 12:11
Closing as this seems to be an issue outside Realm.

**Closed by cmelchior** 2020-05-07 12:11 UTC
Labels: O-Community, T-Help
