### ISSUE TITLE
Realm query sometimes return empty data

### ISSUE THREAD

**Issue by jing-y** [realm/realm-java#2986] opened 2016-06-12 06:19 UTC
Hi There,

I am using Realm v1.0.0 for our Android app. I used Realm for iOS before, and it works really great, so I also decided to use Realm for Android.

We are using Realm with RxJava. It currently works in this way:

	// class: DataService
	public ConentService {
		public Observable<List<Content>> getAllContents(final int offset, final int limit) {
			return RxUtil.makeObservableWithRealm(new RXUtil.RealmCallable<List<Content>>() {
				@Override
				public List<Content> call(Realm realm) throws Exception {
					List<RealmContent> realmContents = realm.where(RealmContent.class).findAllSorted("createAt", Sort.DESCENDING);
					int begin = offset;
					int end = offset + limit;
					if (end > realmContents.size()) {
						end = realmContents.size();
					}
					if (begin >= end) {
						return new ArrayList<>();   // MARK: Point A
					}
					realmContents = realmContents.subList(begin, end);
					return convertRealmContentToRegularContent(realmContents); // MARK: Point B
				}
			});
 		}
	}
   
	// class: RxUtil
	// create Observable for RxAndroid
	public RxUtil {
       public static <T> Observable<T> makeObservableWithRealm(final RealmCallable<T> func) {
           return Observable.create(
               new Observable.OnSubscribe<T>() {
                   @Override
                   public void call(Subscriber<? super T> subscriber) {
                       Realm realm = Realm.getDefaultInstance();
                       try {
                           subscriber.onNext(func.call(realm));
                       } catch (Exception e) {
                           e.printStackTrace();
                           Log.e("RXUtil", e.toString());
                           throw new Error(e);
                       } finally {
                            // guratee all realm instances can be closed;
                           realm.close();
                       }
                   }
               });
        }
	}
   
	// class: RealmCallable
	public interface RealmCallable<V> {
       V call(Realm realm) throws Exception;
	}

The above works most of the time, but I found sometimes the
`
getAllContents()
`
method returns an empty result. This usually occurs in the users very first session, eg. I open the app (uninstall app, resintall app, open app and create one post, then keep invoking pull-down-to-refresh method for the content list view, I will see this issue happen several times).

After I kill the app and reopen however, this issue disappears.

I am stuck in this issue, would you please help with the following?

a) Is the code I have used incorrect? Should I be invoking realm in a different way?

BTW, I read almost all tutorial & doc, I know you suggested to call realm query on UI thread directly or use realm Rx feature, but due to some historical reason, I cannot refactor everything w/ realm Rx style,

b) Do I need to do special handling for the first session access?

c) Is there a bug or issue in this version of realm that needs fixing?

Thanks!

**Comment by cmelchior** [comment] 2016-06-12 06:34
You have this code here:
```
if (begin >= end) {
  return new ArrayList<>();   // MARK: Point A
}
 ```

So if the Realm is empty it will return the empty list?
Have you verified that you actually found any data?
```
List<RealmContent> realmContents = realm.where(RealmContent.class).findAllSorted("createAt", Sort.DESCENDING);
Log.d("Test", "Size: " + realmContent.size());
```

**Comment by eddyhutchins** [comment] 2016-06-12 09:40
Hi @cmelchior. The query parameter is 'offset=0, limit=20', and we also verified that the result size is actually 0.

**Comment by cmelchior** [comment] 2016-06-12 17:55
No, there shouldn't be any special consideration for first launch, but I am still not sure I understand the problem? Didn't you expect the Realm to be empty? Because your code seems to correctly return the empty list in case of an empty search result.

If you didn't expect the Realm to be empty, are you somehow deleting the Realm when starting the app?

Possible method calls that could clear the Realm:
`Realm.deleteRealm(config)`
`realm.deleteAll()`
`realm.delete(Content.class)`
`RealmConfiguration.deleteRealmIfMigrationRequired()`

**Comment by jing-y** [comment] 2016-06-13 04:26
Hi cmelchior,

I think I find the cause.  This issue comes out only in first time user open app and create contents. After kill and reopen app, this issue disappears.

The special thing we does for the first time app launch is data migration. I have one big migration function which migrates data from SQLite to Realm. 

The migration code works in this way:

Create AsyncTask, and execute following code in Background Thread:

        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction(); // catch exception, cancel tx and close it
        try {
            realm.deleteAll();   // MARK: this causes db empty issue
            realm.commitTransaction();
        } catch (Exception e) {
            realm.cancelTransaction();
            realm.close();
        }

		migrationUserSettings()
        migrationUserData()
        migrationContentData()
        migrationNotificationData()
        ...
        
I guess there is some problem w/ `realm.deleteAll();`, after I remove this code, this issue disappears.

Is there anything special we should take care when clean realm database?

Thanks

**Comment by jing-y** [comment] 2016-06-13 05:48
I changed the code to clean each table individually w/ `deleteAllFromRealm()` method, then this issue disappeared.

FYI, Following is my new code:


    public <E extends RealmModel> void cleanRealmTable(Class<E> clazz) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction(); // catch exception, cancel tx and close it
        try {
            realm.where(clazz).findAll().deleteAllFromRealm();
            realm.commitTransaction();
        } catch (Exception e) {
            realm.cancelTransaction();
        }
        realm.close();
    }
    
    
    public void migrateDataFromSqliteToRealm() {

		// The following clean Realm DB code may be unsafe,
		// there is one dicussion about it now:
        // https://github.com/realm/realm-java/issues/2986
        //
		// Realm realm = Realm.getDefaultInstance();
		// realm.beginTransaction(); // catch exception, cancel tx and close it
		// try {
		// 		realm.deleteAll();
		// 		realm.commitTransaction();
		// } catch (Exception e) {
		// 		realm.cancelTransaction();
		// 		realm.close();
		// }

    	cleanRealmTable(RealmUserSettings.class);
	    migrationUserSettings()
    
    	cleanRealmTable(RealmUser.class);
	    migrationUserData()
    
	    cleanRealmTable(RealmContent.class);
	    migrationContentData()
    
	    cleanRealmTable(RealmNotification.class);
	    migrationNotificationData()
	    
	    ...
    }

**Comment by kneth** [comment] 2016-06-15 07:37
@jing-y I am happy to hear that you have found a solution. But I would like to understand why `deleteAll()` didn't work in the first place. Is it possible for you to share your project with us? If you wish to do it privately, you can email it to help@realm.io.

**Comment by jing-y** [comment] 2016-06-17 07:48
Hi @kneth , Thank you. I looked into realm code, and I find `deleteAll()` clean database in this way:

	/**
     * Deletes all objects from this Realm.
     *
     * @throws IllegalStateException if the corresponding Realm is closed or called from an incorrect thread.
     */
    public void deleteAll() {
        checkIfValid();
        for (RealmObjectSchema objectSchema : schema.getAll()) {
            schema.getTable(objectSchema.getClassName()).clear();
        }
    }

And for my case, the `schema.getAll()` returns following classes:

	RealmContent
	RealmUser
	RealmAppContact
	RealmAddressBookContact
	RealmAddressBookPhoneNumber
	RealmChatMessage
	RealmAppNotification
	RealmStringObject
	RealmAppLog
	RealmComment
	RealmChatContext
	RealmFriendRequest
	RealmContact
	RealmShareLog
	RealmAppUser
	RealmBackendNotification
	
Those classes actually have relationships to others. like `RealmChatMessage` depens on data in `RealmUser`, and almost all tables depends on `RealmStringObject`. So is it possible that `deleteAll()` just breaks the database constraint internally?

**Comment by kneth** [comment] 2016-06-17 07:59
@jing-y Thanks for the details. In theory, deleting all objects in one table shouldn't be a problem. Consider the case where A links to B (A has a field which is a list of Bs). When you remove all objects in A, B isn't touched. When you remove all objects in B, all the objects in A are updated (the lists now have length zero).

Said that, it is a good time to revisit the `deleteAll()` method to be sure that the theory holds :-)

**Comment by kneth** [comment] 2016-06-17 09:29
@jing-y I have tried all permutations of the deleting objects, and the theory still holds: #3024.

**Comment by kneth** [comment] 2016-06-24 12:49
I am closing the issue since tests at our side was not able to reproduce it. Don't hesitate to open the issue or create a new if you have further details.

**Closed by kneth** 2016-06-24 12:49 UTC
Labels: S:Waiting For User, T:Help

**Comment by danieldelouya** [comment] 2017-05-01 14:42
I'm having this issue. When the entire realm is delete and i try to query some data that has been added after it was previously entirely deleted, it sometimes returns an empty query.

**Comment by cmelchior** [comment] 2017-05-01 14:53
Hi @danieldelouya Without sample project there isn't much we can do, but if you are using RealmChangeListeners to be notified about changes this shouldn't happen.

**Comment by Zhuinden** [comment] 2017-05-01 14:59
@danieldelouya this is possible if you query on non-looper background threads outside of a transaction and you had at least 1 unclosed Realm instance and therefore caused version retention.

**Comment by danieldelouya** [comment] 2017-05-01 15:01
@Zhuinden So how do you suggest I avoid it exactly? :)

**Comment by danieldelouya** [comment] 2017-05-01 15:01
I'm pretty sure I don't have any unclosed realm instances

**Comment by Zhuinden** [comment] 2017-05-01 15:50
@danieldelouya if you do queries on non-looper threads, then you should probably do that in a transaction, I guess :slightly_smiling_face: 

And Realm instance needs to be closed when the thread's lifeline ends. I tend to do try-with-resources, or close in finally.

Looper threads (such as the UI thread) typically can't provide "stale data" because Realm can automatically update their instances.

**Comment by muthuraj57** [comment] 2018-10-26 10:02
I'm experiencing this now in a findAll call. I made all my db calls as Single, so it may be accessed/inserted in any thread. 

> if you do queries on non-looper threads, then you should probably do that in a transaction

This solves the issue for me. But I think this more like a workaround.

> And Realm instance on non-looper thread needs to be closed when the thread's lifeline ends

I'm using Realm.getDefaultInstance.use{} from kotlin and I think I close all realm instances. Anyway, how do I check if I have any opened realm instances?

**Comment by Zhuinden** [comment] 2018-10-26 10:05
@muthuraj57 I finally managed to get Realm to add `realm.refresh()` which can make sense in certain cases on non-looper background threads.
