### ISSUE TITLE
Delete RealmObject

### ISSUE THREAD

**Issue by NhenDen** [realm/realm-java#3848] opened 2016-11-28 06:49 UTC
Hello everybody,
I have a issue, I want delete 1 RealmObject. My code:
` realm.beginTransaction();
realm.delete(InterestDownload.class);
realm.commitTransaction();`

but my app delete data in the first, the second not delete data. Example, i have 3 item. The first i delete 3 item and insert 6 item other, ok no problem. But the second i delete 6 item and insert 4 item other, my app not delete 6 item, I have 10 item. I have no idea. Help my find bug.

**Comment by Zhuinden** [comment] 2016-11-28 07:06
There is definitely not enough code here to tell you the cause of the problem.

**Comment by NhenDen** [comment] 2016-11-28 07:46
Full my code:
`mDownloadDataDialog.dismiss();
                showSmileLoading();

                String userID = ApplicationController.getInstance().getUserData().getId();
                mTimeLastUpdateInterest = "0";
                RealmController.clearInterestDownload(mRealm);
                getPresenter().requestInterestDownload(userID, mTimeLastUpdateInterest, String.valueOf(mInterestPageNumberCurrent));`

`public static void clearInterestDownload(Realm realm) {
        realm.beginTransaction();
        realm.delete(InterestDownload.class);
        realm.commitTransaction();
    }`

You can help me find error :(

**Comment by NhenDen** [comment] 2016-11-28 07:47
I save data in Realm
`private void saveDataInterestData(final List<InterestDownload> interestDownloads) {
        mRealm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.insertOrUpdate(interestDownloads);
            }
        });
    }`

**Comment by zaki50** [comment] 2016-11-28 10:42
@NhenDen Could you provide a simple project that reproduce this issue?

**Comment by zaki50** [comment] 2016-12-05 07:50
I'll close this.

Please reopen this when you make a code to reproduce this.

**Closed by zaki50** 2016-12-05 07:50 UTC
Labels: S:Waiting For User, T:Help
