### ISSUE TITLE
Support in RealmArray for basic types (int, strings, etc.)

### ISSUE THREAD

**Issue by timanglade** [realm/realm-java#932] opened 2015-03-06 17:03 UTC
Similar to https://github.com/realm/realm-cocoa/issues/1312

**Comment by cmelchior** [comment] 2015-03-06 17:35
Duplicate of https://github.com/realm/realm-java/issues/575

**Comment by timanglade** [comment] 2015-03-06 17:36
Thanks for the catch!

**Closed by cmelchior** 2015-03-06 17:35 UTC
