### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid Group file format.

### ISSUE THREAD

**Issue by jasonross** [realm/realm-java#961] opened 2015-03-14 08:21 UTC
I am a fan of Realm. When use it,there is a crash below:
<pre>
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid Group file format.
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.(SharedGroup.java:58)
       at io.realm.Realm.(Realm.java:199)
       at io.realm.Realm.createAndValidate(Realm.java:516)
       at io.realm.Realm.create(Realm.java:480)
       at io.realm.Realm.getInstance(Realm.java:397)
       at io.realm.Realm.getInstance(Realm.java:378)
</pre>
Can anybody tell me why ?

**Comment by cmelchior** [comment] 2015-03-16 05:59
We need some more information to debug this. Please see this: https://github.com/realm/realm-java#filing-issues

**Comment by NirpE** [comment] 2015-03-16 08:25
I have encountered the same problem, but not yet found steps to reproduce this. Using encrypted database.

**Comment by NirpE** [comment] 2015-03-17 06:30
@cmelchior is this information provided enough to dig into this problem?

**Comment by emanuelez** [comment] 2015-03-17 11:24
What version of Realm are you using?

**Comment by NirpE** [comment] 2015-03-17 11:25
This is version 0.80.0

**Comment by kneth** [comment] 2015-03-17 12:47
@NirpE Are you using encrypted Realm files? And do you wish to change the encryption key?

**Comment by NirpE** [comment] 2015-03-17 12:50
Yes, the following error occurs when encryption key is changed and due to
the open realm issue I cannot delete the existing realm file when the
exception is catched.

tiistai 17. maaliskuuta 2015 Kenneth Geisshirt <notifications@github.com>
kirjoitti:

> @NirpE <https://github.com/NirpE> Are you using encrypted Realm files?
> And do you wish to change the encryption key?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/961#issuecomment-82325825>.
>


-- 
Lähetetty Gmail Mobilesta

**Comment by kneth** [comment] 2015-03-17 13:39
In that case, you will have to copy your Realm file to a new file. Use the `Realm.writeEncryptedCopyTo()` method.

**Comment by NirpE** [comment] 2015-03-17 13:46
My case is that the user has changed and the db should be wiped, but the
exception doesnt allow me to delete the db because realm thinks connection
is open.

tiistai 17. maaliskuuta 2015 Kenneth Geisshirt <notifications@github.com>
kirjoitti:

> In that case, you will have to copy your Realm file to a new file. Use the
> Realm.writeEncryptedCopyTo() method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/961#issuecomment-82357139>.
>


-- 
Lähetetty Gmail Mobilesta

**Comment by kneth** [comment] 2015-03-17 14:00
After the call to `Realm.writeEncryptedCopyTo()`, you can call `Realm.close()` and then `Realm.deleteRealmFile()`.

**Comment by NirpE** [comment] 2015-03-17 14:42
But the problem is with the realm code, naturally I don’t know if the key changes so I get the exception but I can’t recover from that problem like I have stated.

**Comment by NirpE** [comment] 2015-03-17 14:50
So I am not trying to make a copy, but I try to recover and create a new db with the new key for the new user.

**Comment by emanuelez** [comment] 2015-03-18 11:28
If you want to generate a brand new Realm file with a different encryption key you can simply create a new Realm instance with a different file name:

```
Realm newRealm = Realm.getInstance(context, "newName.realm");
```

**Comment by NirpE** [comment] 2015-03-18 11:34
I do not want to change the file name. Simply remove old, create new with same name. I could do this if the openRealm map handling would be proper to catch that exception when creating Realm object and removing it from open realms since it is not valid. Now it assumes that Realm object constructor never fails and the check is only performed if the created object is valid.

**Comment by NirpE** [comment] 2015-03-19 05:47
Did you understood the scenario I have and what is the problem with Realm code? Basically the problem is with createAndValidate method:

<code>realm = new Realm(absolutePath, key, autoRefresh);</code>

Before this line openRealms thinks we are returning Realm object, but the construction fails and it is not removed from openRealms.

**Comment by cmelchior** [comment] 2015-03-20 20:44
Yes, I think we understand the problem, and you are right. The internal caches are not cleared if the constructor fails. This should be fixed.

**Closed** 2015-03-25 18:50 UTC
Labels: bug, P1
