### ISSUE TITLE
io.realm.exceptions.RealmException: class com.kaikeba.common.entity.student.CourseModel is not part of the schema for this Realm.

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#1282] opened 2015-07-10 07:57 UTC
I have a data with this structure,
when i  use realm.createOrUpdateObjectFromJson(CourseModel.class, (String) data) to create database,  it report crash log like the title.

@RealmClass
public class CourseModel extends RealmObject implements Serializable {
    @PrimaryKey
    private int id;
    private RealmList<GuideCourseLms> lms_course_list;
    private RealmList<ItemVideo> videos;
    private String certificate_img;
    private String recommen;
........get()   ....set()...
}

@RealmClass
public class GuideCourseLms extends RealmObject implements Serializable {
    @PrimaryKey
    private long id;
    private long course_id;
    private RealmList<CourseArrangeInfo> course_arrange;
.........get() .......set().....
}

@RealmClass
public class CourseArrangeInfo extends RealmObject implements Serializable {
    @PrimaryKey
    private long id;
    private long course_id;
    private String name;
    private String position;
    private String unlock_at;
    private String workflow_state;
    private String require_sequential_progress;
    private boolean isGroupSelected;
    private RealmList<ArrangeItems>items;
.......get().....set()....
}

@RealmClass
public class ArrangeItems extends RealmObject implements Serializable {
    @PrimaryKey
    private int id;
    private long indent;
    private long position;
    private String title;      //    ": "第01周-导学",
    private String type;       // ": "Page",
    private String html_url;   //   ": "http://learn-test.kaikeba.com/courses/735/modules/items/23900",
    private String url; 
.......get().....set()....
}

**Comment by mjliu** [comment] 2015-07-10 09:19
I write a demo also has this error . I write this demo without Hashky,it's ok,but,with Hashky it crashed.

@RealmClass
public class Person extends RealmObject implements Serializable{

    @PrimaryKey
    private String name;
    private String age;
    private RealmList<Animal> animals;
......get sets()....
}

@RealmClass
public class Animal extends RealmObject {
    @PrimaryKey
    private String name;
    private int age;
    private RealmList<Dogs> dogs;
......get sets()....
}

@RealmClass
public class Dogs extends RealmObject {
    @PrimaryKey
    private String name;
    private int age;
    private RealmList<Hashky> hashkies;
......get sets()....
}

@RealmClass
public class Hashky extends RealmObject {
    @PrimaryKey
    private String name;
    private int age;
......get sets()....
}

RealmList<Person>persons = new RealmList<Person>();
                    for(int i = 0;i < 10;i++){
                        Person p = new Person();
                        p.setName("jack" + i);
                        p.setAge("age" + i);
                        RealmList<Animal> animals = new RealmList<Animal>();
                        for(int j = 0;j < 10;j++){
                            Animal animal = new Animal();
                            animal.setName("animal" + "_" + i + "_" + j);
                            animal.setAge(j);
                            RealmList<Dogs> dogs = new RealmList<Dogs>();
                            for(int k = 0;k < 5;k++){
                                Dogs dogs1 = new Dogs();
                                dogs1.setName("dogs" + "_" + i + "_" + j + "_" + k);
                                dogs1.setAge(k);
                                RealmList<Hashky>hashkies = new RealmList<Hashky>();
                                for(int m = 0;m < 8;m++){
                                    Hashky hashky = new Hashky();
                                    hashky.setName("hashky" + "_" + i + "_" + j + "_" + k + "_" + m);
                                    hashky.setAge(m);
                                    hashkies.add(hashky);
                                }
                                dogs1.setHashkies(hashkies);
                                dogs.add(dogs1);
                            }
                            animal.setDogs(dogs);
                            animals.add(animal);
                        }
                        p.setAnimals(animals);
                        persons.add(p);
                    }
                    realm.beginTransaction();
                    realm.copyToRealmOrUpdate(persons);
                    realm.commitTransaction();

**Comment by emanuelez** [comment] 2015-07-10 09:25
Did you happen to add the Hashky model class without performing a migration or deleting the Realm file?

**Comment by mjliu** [comment] 2015-07-10 09:32
@emanuelez   I write this ,  but it does not work.

RealmConfiguration realmConfig = new RealmConfiguration.Builder(this)
                .deleteRealmIfMigrationNeeded()
                .build();
        realm = Realm.getInstance(realmConfig);

**Comment by emanuelez** [comment] 2015-07-10 09:36
Also `private RealmList hashkies;` should be `private RealmList<Hashky> hashkies;`.
The annotation processor should complain about that. What version of Realm are you using? Android Studio or Eclipse?

**Comment by mjliu** [comment] 2015-07-10 09:43
@emanuelez  
I use IntelliJ iDEA ,Realm  version  0.81.1    
private RealmList<Hashky> hashkies;  that's what I use.

**Comment by emanuelez** [comment] 2015-07-10 09:44
Well, you have to provide a generic type to the RealmList

**Comment by beeender** [comment] 2015-07-10 09:46
@mjliu Can you share your demo project with us? help@realm.io 
Thanks!

**Comment by mjliu** [comment] 2015-07-10 09:48
@beeender  ok, thank you

**Comment by mjliu** [comment] 2015-07-10 09:54
@beeender   the demo is send to you

**Comment by mjliu** [comment] 2015-07-10 09:59
@beeender  无法发送到 help@realm.io

**Comment by beeender** [comment] 2015-07-10 09:59
Try this one mc@realm.io

**Comment by mjliu** [comment] 2015-07-10 10:29
@beeender   I use gmail send to you  but  it doesn't accept .zip ,I send these files.

**Comment by beeender** [comment] 2015-07-10 11:05
It is caused by building environment. After clean & rebuild, problem gone.
@mjliu I am closing this issue now, thanks a lot for your feedback!

**Closed by beeender** 2015-07-10 11:05 UTC
Labels: support

**Comment by yfsx** [comment] 2016-02-10 03:53
i think you cant just "clean and rebuild" the program @beeender . imagine if you build some app and shared to google play, and you have millions users using your apps. When the app "force close" because this problem, they can't "clean and rebuild" the apps, so the programmer must prevent it, which is prevent "clear and rebuild" it.

so far i have 2 approaches which can help you guys, but sometimes i still got this error

http://stackoverflow.com/a/34392556/3737254

  RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build();
      try {
          return Realm.getInstance(realmConfiguration);
      } catch (RealmMigrationNeededException e){
          try {
              Realm.deleteRealm(realmConfiguration);
              //Realm file has been deleted.
              return Realm.getInstance(realmConfiguration);
          } catch (Exception ex){
              throw ex;
              //No Realm file to remove.
          }
      }

you still can use Realm.getInstance(context);

or 

  RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).deleteRealmIfMigrationNeeded().build();
          Realm.setDefaultConfiguration(realmConfiguration);

 by this way, you must use Realm.GetDefaultInstance(); everytime you call Realm
