### ISSUE TITLE
QarthPatchMonintor::CheckNotifyEvent before read E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@b0522d4

### ISSUE THREAD

**Issue by Taverz** [realm/realm-java#6922] opened 2020-06-05 15:57 UTC
QarthPatchMonintor::CheckNotifyEvent before read
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@b0522d4
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@5c49c7d
I/AwareBitmapCacher: init processName:com.example.myapplicationRealmRead pid=3475 uid=10193
D/ZrHung.AppEyeUiProbe: notify runnable to start.
D/ZrHung.AppEyeUiProbe: Runnable thread started.
E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
V/ActivityThread: Skipping new config:{1.15 250mcc20mnc [ru_RU] ldltr sw423

2020-06-05 18:31:14.345 3475-3550/com.example.myapplicationRealmRead E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@b0522d4
2020-06-05 18:31:14.347 3475-3550/com.example.myapplicationRealmRead E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@5c49c7d
2020-06-05 18:31:14.412 3475-3517/com.example.myapplicationRealmRead E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2020-06-05 18:31:15.315 3475-3475/? E/REALM_JNI: jni: ThrowingException 2, Out of range  in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 98(requested: 1 valid: 0), .
2020-06-05 18:31:15.315 3475-3475/? E/REALM_JNI: Exception has been thrown: Out of range  in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 98(requested: 1 valid: 0)
2020-06-05 18:31:15.319 3475-3475/? E/cationRealmRea: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-05 18:31:15.327 3475-3475/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplicationRealmRead, PID: 3475
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplicationRealmRead/com.example.myapplicationRealmRead.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: Out of range  in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 98(requested: 1 valid: 0)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: Out of range  in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 98(requested: 1 valid: 0)
        at io.realm.internal.OsResults.nativeGetRow(Native Method)
        at io.realm.internal.OsResults.getUncheckedRow(OsResults.java:342)
        at io.realm.OrderedRealmCollectionImpl.get(OrderedRealmCollectionImpl.java:123)
        at io.realm.RealmResults.get(RealmResults.java:69)
        at com.example.myapplicationRealmRead.MainActivity.onCreate(MainActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 

**I can not read the database, what is the reason?**
_  Standard app.class, database in date / date / <app> / file - name ("name.realm")
_ 

`public class DataRealm  extends RealmObject {
String name;
`
### ****
`  @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);
        RealmConfiguration configuration=new RealmConfiguration.Builder()
                .name("2nnnnffdefault.realm")
                // .assetFile("daaaelt.realm")
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(configuration);`

`

        relm = Realm.getDefaultInstance();

        txv = findViewById(R.id.ttr);
        RealmQuery query = relm.where(DataRealm.class);
        RealmResults<DataRealm> res = query.findAll();
        //RealmResults<DataRealm> results = relm.where(DataRealm.class).findAll();

        String dd = res.get(1).getEN();  // <- ERROR  line  // highlight  getEN   why?
        txv.setText(dd);
`

**Comment by Taverz** [comment] 2020-06-05 17:17
**Read me file**
`E/cationRealmRea: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplicationRealmRead, PID: 10007
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplicationRealmRead/com.example.myapplicationRealmRead.MainActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm': Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path:Exception backtrace:
    <backtrace not supported on this platform>. (Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path: /data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm': Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path:Exception backtrace:
    <backtrace not supported on this platform>. (Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path: /data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:337)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)
        at com.example.myapplicationRealmRead.MainActivity.onCreate(MainActivity.java:36)
`
Main activity 36 ---->    relm = Realm.getDefaultInstance();

` 2020-06-05 20:06:57.471 10007-10038/com.example.myapplicationRealmRead E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@8ac3425
2020-06-05 20:06:57.472 10007-10038/com.example.myapplicationRealmRead E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@2d3a9fa
2020-06-05 20:06:57.519 10007-10031/com.example.myapplicationRealmRead E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
2020-06-05 20:06:58.022 10007-10007/com.example.myapplicationRealmRead E/cationRealmRea: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-05 20:06:58.032 10007-10007/com.example.myapplicationRealmRead E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplicationRealmRead, PID: 10007
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplicationRealmRead/com.example.myapplicationRealmRead.MainActivity}: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm': Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path:Exception backtrace:
    <backtrace not supported on this platform>. (Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path: /data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm': Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path:Exception backtrace:
    <backtrace not supported on this platform>. (Invalid top array (ref: 3760, size: 11)
    Exception backtrace:
    <backtrace not supported on this platform> Path: /data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:337)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
        at io.realm.Realm.getDefaultInstance(Realm.java:407)
        at com.example.myapplicationRealmRead.MainActivity.onCreate(MainActivity.java:36) `

**Comment by cmelchior** [comment] 2020-06-17 11:55
For some reason `res.get(1)` doesn't exist. For some reason, the query result doesn't return any results. Why I don't know.

**Comment by cmelchior** [comment] 2020-08-26 10:29
There are a number of different errors being reported here: 

1# 
```
ComponentInfo{com.example.myapplicationRealmRead/com.example.myapplicationRealmRead.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: Out of range in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 98(requested: 1 valid: 0)
```

Is an error accessing an array that is empty. This is working as intended. You should check if the array is empty before accessing index 1.

2#
```
'/data/data/com.example.myapplicationRealmRead/files/nnnnffdefault.realm': Invalid top array (ref: 3760, size: 11) Exception backtrace: <backtrace not supported on this platform> Path:Exception backtrace: <backtrace not supported on this platform>. (Invalid top array (ref: 3760, size: 11)
```

Is a legit problem, but the format indicates an older version of Realm is being used. Upgrading to the latest 7.0.2 would be the first step here.

Closing

**Closed by cmelchior** 2020-08-26 10:29 UTC
Labels: O-Community, T-Help
