### ISSUE TITLE
**Bugs** Fatal signal 11 (SIGSEGV), code 1, fault addr 0x248

### ISSUE THREAD

**Issue by mhdtouban** [realm/realm-java#4330] opened 2017-03-15 22:03 UTC
**Bugs**: Crash is happening suddenly in the app 
#### Actual Results

>  A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x248 in tid 12164 (com.x.dev)
                                                       
                                                       [ 03-15 23:55:42.919   375:  375 W/         ]
                                                       debuggerd: handling request: pid=12164 uid=10576 gid=10576 tid=12164

#### Steps & Code to Reproduce

> Describe your current debugging efforts.
The issue happens suddenly. Mostly when I delete something from Realm.

        final Item Item = realmUI.where(Item.class).equalTo("id", Id).findFirst();

        Realm realm = Realm.getDefaultInstance();
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm transactionRealm) {

            Item.deleteFromRealm();

            }
        });
        realm.close();

#### Version of Realm and tooling
Realm version(s): ?
2.3.1
Realm sync feature enabled: yes/no
no
Android Studio version:?
2.3
Which Android version and device:?
Nexus6p android v7.1

**Comment by beeender** [comment] 2017-03-16 02:11
1. Are you using encryption with Realm?
2. We fixed a crash problem in `v2.3.2`, can you try it?
3. If you are still having the problem, would you please let us know how to reproduce it?

**Comment by Zhuinden** [comment] 2017-03-16 09:59
Execute the query **inside** the transaction

**Comment by mhdtouban** [comment] 2017-03-18 22:36
the error is not happening anymore in v3.0 , will keep you up to date in case happened again.

**Comment by Zhuinden** [comment] 2017-03-19 08:26
if I was right, then results integration forces the RealmResults to be up to date via `realm.beginTransaction()` (part of `executeTransaction()` and therefore you don't need to query inside the transaction to force the RealmResults to be up to date

If I was off, then who knows :smile:

**Comment by beeender** [comment] 2017-03-20 02:12
@Zhuinden It should throw an invalid row exception before instead of native crash ...

But anyway, good not know it is not happening in `3.0.0`. I am closing this now. Let us know if it happened again.

**Closed by beeender** 2017-03-20 02:12 UTC
Labels: T:Help

**Comment by guness** [comment] 2017-04-29 01:21
It happened to me on a Sony Xperia Z1 device with, Realm 3.1.3 version. I was quick sliding betfeen fragments. and it is crashed.

**Comment by Zhuinden** [comment] 2017-04-29 08:43
@guness well what do your fragments do?

**Comment by guness** [comment] 2017-04-29 11:55
@Zhuinden I have fragments within a ViewPager.
3 of them is using lists with Realm adapter. one is using single realm object to fill details.

Each time I slide between fragments, app first fills the list/details and send a network request then updates data using Realm. (Adapters later take care of the rest).

I was crazy going between fragments in order to reproduce another error, but hit this one.

**Comment by mhdtouban** [comment] 2017-05-01 13:22
Hello, the error comes up again with me while trying to delete an object from realm:

```
Realm realm = Realm.getDefaultInstance();

        final Comment comment = realm.where(Comment.class).equalTo("id", commentId).findFirst();

        if (comment != null) {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {

                    comment.deleteFromRealm();
                }
            });
      }
        realm.close();
```
I also tried to delete it with 
```
     realm.beginTransaction();
        comment.deleteFromRealm();
        realm.commitTransaction();
        realm.close();
```
but also same error happened.

**Comment by mhdtouban** [comment] 2017-05-01 13:57
also can be reproducable 
```
Realm realm = Realm.getDefaultInstance();
RealmResults<Comment> comment = realm.where(Comment.class).equalTo("id",commentId).findAll();
     
        if (comment != null) {
            if (comment.isValid()) {
                realm.beginTransaction();
                comment.deleteFirstFromRealm();
                realm.commitTransaction();
            }
       }
            realm.close();
```

**Comment by Zhuinden** [comment] 2017-05-01 14:06
Execute the query inside the transaction.

**Comment by mhdtouban** [comment] 2017-05-01 18:20
@Zhuinden your suggestion didn't solve the issue.

**Comment by mhdtouban** [comment] 2017-05-01 18:20
UPDATE: I have checked if the comment object is being deleted from the database using RealmBroswer and it seems the native error is happening after the object deletion from DB.

**Comment by Zhuinden** [comment] 2017-05-01 18:24
Realm realm = Realm.getDefaultInstance();
    realm.beginTransaction();
    RealmResults<Comment> comment = realm.where(Comment.class).equalTo("id",commentId).findAll(); 
    if(!comment.isEmpty()) { 
        comment.deleteFirstFromRealm();
    }
    realm.commitTransaction();
    realm.close();

**Comment by mhdtouban** [comment] 2017-05-01 18:30
Additional information to add, there is a relationship between comments and posts where each post has realmlist<Comment>. What I want to do here is to delete a comment found in DB for that post.

**Comment by Zhuinden** [comment] 2017-05-01 18:34
@mhdtouban the code I posted *should* work.

But you can also try `comment.get(0).deleteFromRealm()` as well, although it shouldn't have different behavior.

**Comment by mhdtouban** [comment] 2017-05-01 18:36
@Zhuinden I tried all possibilities above but am still getting this annoying native crash.Thanks anyway

**Comment by Zhuinden** [comment] 2017-05-01 18:43
@mhdtouban in that case you might want to set `RealmLog.setLevel(LogLevel.TRACE)` or something similar, and whatever happens before the crash should be posted here from the log; I have no idea how to read it, but Realm people do :smile:

**Comment by mhdtouban** [comment] 2017-05-01 19:52
here is the stacktrace

`05-01 22:51:41.798 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.798 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.798 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.798 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_Collection_nativeCreateResults
05-01 22:51:41.803 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.803 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_Collection_nativeIsValid 547102673792
05-01 22:51:41.803 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.803 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeBeginTransaction 547610388352
05-01 22:51:41.803 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 547610388352
05-01 22:51:41.803 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.804 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsInTransaction 547610388352
05-01 22:51:41.804 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_Collection_nativeDeleteFirst 547102673792
05-01 22:51:41.804 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.804 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeCommitTransaction 547610388352
05-01 22:51:41.819 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.819 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 547610388352
05-01 22:51:41.819 20320-20320/com.topshou.dev V/REALM_JNI:  --> Java_io_realm_internal_UncheckedRow_nativeIsNull 547110531360
                                                            
                                                            --------- beginning of crash
05-01 22:51:41.819 20320-20320/com.topshou.dev A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x248 in tid 20320 (com.topshou.dev)
                                                       
                                                       [ 05-01 22:51:41.820   385:  385 W/         ]
                                                       debuggerd: handling request: pid=20320 uid=10632 gid=10632 tid=20320
`

**Comment by Zhuinden** [comment] 2017-05-01 20:32
@mhdtouban oh you crashed at `nativeIsNull` meaning that's a duplicate of https://github.com/realm/realm-java/issues/4540

You'll get a proper exception with the snapshot version

**Comment by mhdtouban** [comment] 2017-05-01 22:15
thanks @Zhuinden, this issue was is that I was trying to access a stored object from a list which was deleted. Now am getting an informative exception 
 ```java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?```

**Comment by Zhuinden** [comment] 2017-05-01 23:55
Glad to hear the pesky bug is finally caught :slightly_smiling_face:
