### ISSUE TITLE
realm.refresh in 0.89.0 not working

### ISSUE THREAD

**Issue by luhui** [realm/realm-java#2671] opened 2016-04-26 02:13 UTC
#### Goal

> I want to get latest result in main thread after a `executeTransactionAsync ` complete

#### Expected Results

> Get the latest result in `OnSuccess` callback

#### Actual Results

>  old version will be get in 0.89.0, works fine on 0.88.3

#### Steps & Code to Reproduce

> 1. save async with `realm.executeTransactionAsync`
> 2. call `realm.refresh` on `OnSuccess` callback
> 3. fetch latest result after `real.refresh` called
> 4. Found the old version in 0.89.0, found the newest version in 0.88.3

#### Code Sample

```java
String id = UUID.randomUUID().toString();
Log.e("lh", "before save " + id + "----" + Realm.getDefaultInstance().allObjects(Event.class).size());
realm.executeTransactionAsync(realm1 -> {
    Event games = new Event();
    games.setId(id);
    games.setName("test-name!!");
    realm1.copyToRealmOrUpdate(games);
}, () -> {
    //Not update yet
    Log.e("lh", "save " + id + " result ...." + realm.allObjects(Event.class).size());
    realm.refresh();
    Log.e("lh", "after realm.refresh()-----save " + id + " result ...." + realm.allObjects(Event.class).size());
            //Delay 1s, will be work
    new TimerTask(1000).startTask(() -> Log.e("lh", "save " + id + " result after 1s...." + realm.allObjects(Event.class).size()));
});
```
> Complete sample code is [here](https://github.com/luhui/RealmExample), on `FirstFragmeng.java` `updateEvent()`, line 116

#### Version of Realm and tooling
Realm version(s): 0.89.0

Android Studio version: 2.0 preview8

Which Android version and device: all device with Android 4.4 & 5.0

**Comment by njovy** [comment] 2016-04-26 04:49
Having the same issue after upgrade to 0.89.0

**Comment by zaki50** [comment] 2016-04-26 05:27
@luhui Which do you execute that sample code on UI( or Looper) thread or non-Looper thread?

**Comment by zaki50** [comment] 2016-04-26 05:52
I couldn't reproduce this.

I wrote following test case in `RealmAsyncQueryTests.java` and

```
    @Test
    @RunTestInLooperThread
    public void issue2671() {
        final Realm realm = looperThread.realm;

        final String id = UUID.randomUUID().toString();
        Log.e("lh", "before save " + id + "----" + realm.allObjects(Event.class).size());
        realm.executeTransactionAsync(
                new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm1) {
                        Event games = new Event();
                        games.setId(id);
                        games.setName("test-name!!");
                        realm1.copyToRealmOrUpdate(games);
                    }
                }
                , new Realm.Transaction.OnSuccess() {
                    @Override
                    public void onSuccess() {
                        //Not update yet
                        Log.e("lh", "save " + id + " result ...." + realm.allObjects(Event.class).size());
                        realm.refresh();
                        Log.e("lh", "after realm.refresh()-----save " + id + " result ...." + realm.allObjects(Event.class).size());
                    }
                });
    }
```

got following log.

```
lh      : before save ec5c81c5-de17-4c61-b604-0e8f1a66ddad----0
lh      :save ec5c81c5-de17-4c61-b604-0e8f1a66ddad result ....1
lh      :after realm.refresh()-----save ec5c81c5-de17-4c61-b604-0e8f1a66ddad result ....1
```

It seems to work as expected.

`RealmAsyncQueryTests` has a test case `executeTransactionAsync_onSuccess` which tests similar case.

@luhui Do you see any difference with your code?

**Comment by luhui** [comment] 2016-04-26 07:09
Hi @zaki50 , it seems like the realm instance initial in different way.  In my case, realm init with `Realm.getDefaultInstance()` in `Fragment`'s `onCreate` method, which initial on UI thread.
Did this test case run on UI thread?

**Comment by beeender** [comment] 2016-04-26 13:41
Is it the same issue with https://github.com/realm/realm-java/issues/1893 ?
@dalinaum

**Comment by zaki50** [comment] 2016-04-26 15:19
@luhui test is executed on a thread which has a Looper. That is equivalent to UI thread for Realm.

**Comment by dalinaum** [comment] 2016-04-26 16:12
@luhui Did you use async queries before using `executeTransactionAsync`?

**Comment by zaki50** [comment] 2016-04-30 07:11
I've updated test case(added async query before async transaction).
And got the same result with what @luhui described.

It's not a problem of `refresh()`, but a problem of async transaction (https://github.com/realm/realm-java/commit/7f65b387931ff4d92692a1fc6b95bc7611133f5f).

```
    @Test
    @RunTestInLooperThread
    public void issue2671() {
        final Realm realm = looperThread.realm;

        final RealmResults<Event> all = realm.where(Event.class).findAllAsync();
        all.addChangeListener(new RealmChangeListener<RealmResults<Event>>() {
            @Override
            public void onChange(RealmResults<Event> element) {
                if (!element.isLoaded()) {
                    return;
                }
                Log.e("lh", "asyncQuery(size): " + element.size());
            }
        });

        final String id = UUID.randomUUID().toString();
        Log.e("lh", "before save " + id + "----" + realm.allObjects(Event.class).size());
        realm.executeTransactionAsync(
                new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm1) {
                        Event games = new Event();
                        games.setId(id);
                        games.setName("test-name!!");
                        realm1.copyToRealmOrUpdate(games);
                    }
                }
                , new Realm.Transaction.OnSuccess() {
                    @Override
                    public void onSuccess() {
                        //Not update yet
                        Log.e("lh", "save " + id + " result ...." + realm.allObjects(Event.class).size());
                        realm.refresh();
                        Log.e("lh", "after realm.refresh()-----save " + id + " result ...." + realm.allObjects(Event.class).size());
                        looperThread.testComplete();
                    }
                });
    }
```

The result is...
```
4-30 03:01:54.277  1911  1925 E lh      : before save 667a1d60-9889-4084-b673-1e4e5acce5db----0
04-30 03:01:54.289  1911  1925 E lh      : asyncQuery(size): 0
04-30 03:01:54.299  1911  1925 E lh      : save 667a1d60-9889-4084-b673-1e4e5acce5db result ....0
04-30 03:01:54.299  1911  1925 E lh      : after realm.refresh()-----save 667a1d60-9889-4084-b673-1e4e5acce5db result ....0
```

**Comment by zaki50** [comment] 2016-04-30 07:12
@luhui I'll mark this as a duplicate of #1893 
If you are not using async query at all, please reopen this.

**Closed by zaki50** 2016-04-30 07:12 UTC
Labels: S:Waiting For User, T:Help

**Comment by luhui** [comment] 2016-05-03 11:57
@zaki50 Sorry for late reply, it's the same as #1983 
Thank you for all guys :)
