### ISSUE TITLE
Annotation Processor throws an Exception if there are no RealmObject subclasses

### ISSUE THREAD

**Issue by timanglade** [realm/realm-java#677] opened 2014-12-17 08:04 UTC
Realm realm = Realm.getInstance(this , “Blah”); 

throws:

     io.realm.exceptions.RealmException: Could not find the generated ValidationList class: Annotation processor may not have been executed

This shouldn’t happen, as some people may try to compile their project before adding any classes, or may temporarily have a project state where they have no Realm classes.

**Comment by cmelchior** [comment] 2015-04-15 16:36
Duplicate of #860, so closing this one.

**Closed by cmelchior** 2015-04-15 16:36 UTC
Labels: enhancement, P2
