### ISSUE TITLE
RealmFileException: Top ref outside file

### ISSUE THREAD

**Issue by unengchen** [realm/realm-java#6632] opened 2019-10-07 03:17 UTC
#### Goal
 io.realm.exceptions.RealmFileException: Unable to open a realm at path 

#### Actual Results
Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.zcla.bankaccesscontrol/files/log_info.realm': Invalid top array (ref, [0], [1], [2]): 12432, 24, 4320, 24576 Path:. (Invalid top array (ref, [0], [1], [2]): 12432, 24, 4320, 24576 Path: /data/data/com.zcla.bankaccesscontrol/files/log_info.realm) (/data/data/com.zcla.bankaccesscontrol/files/log_info.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.OsSharedRealm.(OsSharedRealm.java:171)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:318)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
at io.realm.Realm.getInstance(Realm.java:428)
at com.zcla.bankaccesscontrol.helper.RealmHelper.getLogRealm(RealmHelper.java:101)
at com.zcla.bankaccesscontrol.global.GlobalActivity.initData(GlobalActivity.java:107)
at com.zcla.bankaccesscontrol.activity.ScreensaverActivity.initData(ScreensaverActivity.java:56)
at com.unengchen.basesdk.view.BaseActivity.onCreate(BaseActivity.java:34)
at android.app.Activity.performCreate(Activity.java:7036)
at android.app.Activity.performCreate(Activity.java:7027)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
at android.app.ActivityThread.-wrap11(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:164) 
at android.app.ActivityThread.main(ActivityThread.java:6494) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

#### Steps & Code to Reproduce
public Realm getLogRealm() {
mLogRealmConfig = new RealmConfiguration.Builder()
                .name(LOG_DATABASE_NAME)
                .schemaVersion(3)
                .modules(new LogRealmModule())
                .migration(new LogRealmMigration())
                .build();
        return Realm.getInstance(mLogRealmConfig);
    }

#### Version of Realm and tooling

Realm version(s): 5.14.0

Realm Sync feature enabled: No

Android Studio version: 3.4

Android Build Tools version: 28

Gradle version: 3.4.1

Which Android version and device(s): 8.0

**Comment by bmunkholm** [comment] 2019-10-07 06:11
It sounds like this is either not a correct Realm file or that it has been corrupted in some way.
1. Do you have any code that uses normal file operations to move or copy the file in any way?
2. Is this happening in production or test?
3. Is this the only occurance?
4. Do you have access to the file?

**Comment by unengchen** [comment] 2019-10-07 08:29
My app is self-startup, and this error is likely to occur every time the power is off and restarted.

**Comment by unengchen** [comment] 2019-10-07 08:37
If I turn on ADB mode, this error will occur, and if I turn it off, it won't happen.

**Comment by bmunkholm** [comment] 2019-10-09 10:32
@unengchen Could you please answer each of the questions 1-4 above?
Also, are you using encryption?

**Comment by unengchen** [comment] 2019-10-10 03:41
@bmunkholm 
1、I have no move or copy the file，I just use Realm.getInstance() to get my realm object
2、it happen in my production
3、when the power is off and restarted in adb mode（adb connect my device），my app is self-startup then realm.getInstance()，the error occur。but close ADB MODE，the error do not occur。
4、Yes，and I have no encryption

**Comment by bmunkholm** [comment] 2019-10-10 17:55
Ok, so it doesn't seem to happen *for your users* in production, but only for you when you debug using ADB.

Did you really copy/paste the exception correctly? It seems there is some duplication in the text in the first 5 lines after "Actual results".

Are you sure you have write access to the file at that location?

**Comment by unengchen** [comment] 2019-10-11 00:24
The AS(android studio) show the exception, I copy/paste it directly。
I am sure that I have access to write ，And I do not write or update my realm object , I just get data from realm to show 。

**Comment by RJFares** [comment] 2019-10-11 04:54
I received a crash report from 1 user who tried to open my app 3 times in a row and got the same crash whenever Realm.getDefaultInstance was called when first starting the app.
He's working on Android 7.0 and Xperia L1.

I cannot reproduce this. The file is encrypted and I do not manually move/copy realm files. But note the size of the array is 0. What could be the problem?

Here's the log:
```
Fatal Exception: io.realm.exceptions.RealmFileException
Unable to open a realm at path '/data/data/.../files/484': Invalid top array (ref: 11680, size: 0) Exception backtrace: <backtrace not supported on this platform>
```

**Comment by bmunkholm** [comment] 2019-10-11 06:06
@RJFares We are currently investigating a corruption bug when using encrypted files. This may be related.

**Comment by bmunkholm** [comment] 2019-10-11 06:07
@unengchen It would help us if you can make a github repository with a complete application and step by step instructions on how to reproduce the issue.

**Comment by unengchen** [comment] 2019-10-11 07:02
@bmunkholm you can write a demo（self-startup）, call realm.getInstance when app starts。debug demo using ADB（must use ADB to connect device, like that adb connect 192.168.1.22:5555） ，and the power off and restarted. the exception will occur likely.

**Comment by hzy00** [comment] 2019-10-21 07:10
The similar crash here. And it happened on production release.
```
Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/mobi.mangatoon.comics.aphone/files/default.realm': Invalid top array (ref: 38970648, size: 0) Path:. (Invalid top array (ref: 38970648, size: 0) Path: /data/data/mobi.mangatoon.comics.aphone/files/default.realm) (/data/data/mobi.mangatoon.comics.aphone/files/default.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:332)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
       at io.realm.Realm.getDefaultInstance(Realm.java:407)
```
Realm version(s): 5.15.1

Realm Sync feature enabled: Yes

Android Studio version: 3.5

Android Build Tools version: 28

Gradle version: 3.3.1

Android Device: Android 8.1.0、8.0、7.0、7.1.2
vivo 1724、samsung Galaxy Note9

**Comment by Zhuinden** [comment] 2019-10-21 10:45
People, you need to specify if you're using encryption or not.

**Comment by unengchen** [comment] 2019-10-22 01:02
@Zhuinden I do not use encryption

**Comment by unengchen** [comment] 2019-10-22 01:04
@hzy00 you can make a github repository with a complete application and step by step instructions on how to reproduce the issue.

**Comment by KonstantinSkuratovich** [comment] 2019-12-24 09:39
There is a similar crash. 
It's happened on production release. Only one user (but very important) has faced this issue, but it has been reproduced **32 times in a row**. 
He has tried to clear the app data and reinstall the app but there is no success, the app crashes every time at the startup. 

```
io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/{appName}/files/default.realm': Invalid top array (ref: 562768, size: 9504768)
Exception backtrace:
<backtrace not supported on this platform> Path:Exception backtrace:
<backtrace not supported on this platform>. (Invalid top array (ref: 562768, size: 9504768)
Exception backtrace:
<backtrace not supported on this platform> Path: /data/data/live.carson.app/files/default.realm
Exception backtrace:
<backtrace not supported on this platform>) (/data/data/live.carson.app/files/default.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
```
Realm version(s): 6.0.0
Gradle version: 3.5.2
Android Device: Samsung S9+ (Android 9), no rooted.

1. The realm file hasn't been moved or deleted.
2. There was no migration. 
3. There is no encryption used.

**Comment by OlegNovosad** [comment] 2020-01-15 14:17
We got same errors on production (we use encryption):

```
Caused by io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/<package_id>/files/encrypted.realm': Invalid mnemonic. top_ref[0]: 4B170, top_ref[1]: 6235653763633438, mnemonic: 35 65 0 61, fmt[0]: 9, fmt[1]: 51, flags: 32. (Invalid mnemonic. top_ref[0]: 4B170, top_ref[1]: 6235653763633438, mnemonic: 35 65 0 61, fmt[0]: 9, fmt[1]: 51, flags: 32) (/data/data/<package_id>/files/encrypted.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init> + 49(OsSharedRealm.java:49)
       at io.realm.internal.OsSharedRealm.getInstance + 13(OsSharedRealm.java:13)
       at io.realm.internal.OsSharedRealm.getInstance + 5(OsSharedRealm.java:5)
       at io.realm.RealmCache.b + 69(RealmCache.java:69)
       at io.realm.RealmCache.a + 9(RealmCache.java:9)
       at io.realm.Realm.b + 4(Realm.java:4)
other NDA code
```

**Comment by Zhuinden** [comment] 2020-01-15 16:24
@OlegNovosad what is the Realm version?

**Comment by OlegNovosad** [comment] 2020-01-15 17:34
> @OlegNovosad what is the Realm version?

6.0.2

**Comment by PhanTuanKiet** [comment] 2020-02-16 03:12
i have same issue
if use Realm Java 6.0.2, i cant even build. The error show in android studio's logcat
if switch to 7.0.0-beta (latest),  app might work but the realm file seems corrupted and cant be open by realm studio with same message "unable to open ...  Invalid top array (ref: 2848, size: 11)"

**Comment by jpmcosta** [comment] 2020-06-11 12:01
Just had the same issue on Realm 6.1.0.

```
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/<package_name>/files/database.realm': Invalid top array (ref: 20025432, size: 4)
Exception backtrace:
<backtrace not supported on this platform> Path:Exception backtrace:
<backtrace not supported on this platform>. (Invalid top array (ref: 20025432, size: 4)
Exception backtrace:
<backtrace not supported on this platform> Path: /data/data/<package_name>/files/database.realm
Exception backtrace:
<backtrace not supported on this platform>) (/data/data/<package_name>/files/database.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:8)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:12)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:5)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:11)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:2)
       at io.realm.Realm.getInstance(Realm.java:4)
       at <package_name>.realm.core.RealmHandler.useRealm(RealmHandler.java:2)
       at <package_name>.realm.core.RealmHandler.a(RealmHandler.java:7)
       at <package_name>.realm.core.RealmHandler.useRealm$default(RealmHandler.java:35)
       at <package_name>.initializer.main.InitializerMain$initialize$1.invokeSuspend(InitializerMain.java:35)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.a(BaseContinuationImpl.java:5)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by JoyHong** [comment] 2020-06-15 03:45
any update? i had the same issue too on Realm v7.0.0

**Comment by dayachand-systematix** [comment] 2020-07-24 13:18
The issue is with the realm studio version. It should work after upgrade the realm studio version.

**Comment by JoyHong** [comment] 2020-07-28 01:10
> The issue is with the realm studio version. It should work after upgrade the realm studio version.

emm. how to upgrade the realm studio version?

**Comment by RajAggrawal0507** [comment] 2020-09-24 07:35
The same issue happened with me on an iOS device in production and iOS simulator in debug mode.

1. I have an older version installed on the simulator
2. Install newer version (By running code in Xcode.)and on launch, it crashed.

Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/Users/raj/Library/Developer/CoreSimulator/Devices/3B94EE68-69CA-40CA-9A0C-4401A3616B29/data/Containers/Data/Application/C298DC59-1776-41E9-B780-0D1607C8F874/Documents/default.realm': Invalid top array (ref: 46928, size: 11)

**Comment by gioramixin** [comment] 2020-10-11 07:19
also happens to me

crash_info_entry_0
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '': Invalid top array size (ref: 93672, size: 0) Exception backtrace: 0 Realm 0x0000000103bb0604 _ZNK5realm9SlabAlloc6verifyEv + 140 1 Realm 0x0000000103bd4ed8 _ZN5realm5Group18validate_top_arrayERKNS_5ArrayERKNS_9SlabAllocE + 1188 2 Realm 0x0000000103bd1488 _ZN5realm5Group6attachEmbb + 208 3 Realm 0x0000000103be18f0 _ZN5realm11TransactionC2ENSt3__110shared_ptrINS_2DBEEEPNS_9SlabAllocERNS3_12ReadLockInfoENS3_13TransactStageE + 332 4 Realm 0x0000000103bdd960 _ZN5realm2DB10start_readENS_9VersionIDE + 132 5 Realm 0x0000000103bdba44 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 3812 6 Realm 0x0000000103bde1fc _ZN5r

in production to some of the users

**Comment by Zhuinden** [comment] 2020-10-12 10:25
Please specify Realm-Java version when making these reports

**Comment by heitorhackcanabal** [comment] 2021-02-08 13:47
Any update? I had the same issue too on Realm v7.0.1.

**Comment by Zhuinden** [comment] 2021-02-08 23:14
But did it stick around with 10.3.0?

**Comment by heitorhackcanabal** [comment] 2021-02-19 17:32
Is this crash fixed on 10.3.0 version?

**Comment by behdad222** [comment] 2021-02-21 10:09
I have similar issues with V10.3.0
OS version: Android 10
Device: SM-A107F

```
io.realm.exceptions.RealmFileException: Invalid top array size (ref: 720126944, size: 16139008)
Exception backtrace:
<backtrace not supported on this platform> () in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
	at io.realm.BaseRealm.<init>(BaseRealm.java:138)
	at io.realm.BaseRealm.<init>(BaseRealm.java:105)
	at io.realm.Realm.<init>(Realm.java:159)
	at io.realm.Realm.createInstance(Realm.java:495)
	at io.realm.RealmCache.createInstance(RealmCache.java:481)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
	at io.realm.Realm.getInstance(Realm.java:424)
```

**Comment by chintak369promact** [comment] 2021-03-03 06:00
@bmunkholm 

I am also facing the same issue on the production app of the end-user.

```
io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.my.app/files/my.realm': 
Invalid top array (ref: 165943760, size: 7481097) Exception backtrace: <backtrace not supported on this platform>
```
When the user opens the app, it gets crashed with this exception.

My app uses realm version is: **6.0.1**

**Comment by bmunkholm** [comment] 2021-03-03 10:54
@chintak369promact Thanks for reporting this. 6.0.1 has had a lot of updates and fixes since. I would suggest updating to the latest version.

**Comment by chintak369promact** [comment] 2021-03-04 08:52
Ok @bmunkholm, So will it get resolved in using latest **10.3.1** version?

**Comment by bmunkholm** [comment] 2021-03-05 08:01
@chintak369promact That's not entirely possible to predict. "Invalid top array" means that the file is somehow corrupted. But there has been important bugfixes since your version, so it's highly recommended to update to the latest. If it should reoccur, please create a new issue with more information so we can troubleshoot that. Thanks!

**Comment by jedelbo** [comment] 2021-03-10 13:09
Issue renamed. The last entries is about the top ref being outside the file - or perhaps more likely: the file size is wrong.

**Comment by finnschiermer** [comment] 2021-05-27 13:25
Has anybody seen this error again after 10.6.0 ?

**Comment by jpmcosta** [comment] 2021-05-27 13:29
I still wasn't able to update to v10, due to #7426, but I can always reply later and ask to reopen the issue, if I get any reports.

**Comment by bmunkholm** [comment] 2021-09-06 17:03
Since all these observations are quite old now, we will close this issue for now. If anyone experiences anything again, please create a new separate issue for each observation. Thanks for all your help!

**Closed by bmunkholm** 2021-09-06 17:03 UTC
Labels: T-Bug-Crash, Reproduction-Required, O-Community
