### ISSUE TITLE
RealmResults::asObservable not always returns a value when subscription is not kept in memory

### ISSUE THREAD

**Issue by AranHase** [realm/realm-java#2485] opened 2016-03-16 14:52 UTC
#### Goal

> What do you want to achieve?

Do a lot of simple realm queries with `findAllAsync().asObservable()` and have them all return a value, even without explicitly holding a reference to its subscription.

(or add a note in the docs about the importance of always holding a reference to the subscriptions? for the noobs like me...)

#### Expected Results

Whenever we create an observable with `findAllAsync().asObservable()`, it would be nice to always get a `RealmResults`, even when we don't hold a reference to the subscription.

#### Actual Results

Some observables created with `findAllAsync().asObservable()` will never call the `onNext(...)` of the subscription.

#### Steps & Code to Reproduce

I created a small Android app showing the problem I'm facing on a bigger application.

The important code is on this line:
https://github.com/AranHase/TestFindAllAsync/blob/13ba8e68d9b9061825125ff3475c6d7091aa93bf/app/src/main/java/com/example/hasegawa/testfindallasync/MainActivity.kt#L84

In this test, one thousand "Realm observables" are created. Every time one observable is created, a counter gets incremented. For each of those observable, one subscription is created (and may or may not be explicitly stored in memory). When this subscription returns any value, another counter is incremented.

When the subscription is stored in memory, then we get the expected behavior (one thousand observables created, and one thousand results). However, when we do not store the subscription in memory, the number of results may not be one thousand.

This line determines if the subscription should be kept in memory or not, and it will change the behavior of the program:
https://github.com/AranHase/TestFindAllAsync/blob/13ba8e68d9b9061825125ff3475c6d7091aa93bf/app/src/main/java/com/example/hasegawa/testfindallasync/MainActivity.kt#L106

I also tried a `flatMap` approach in here:
https://github.com/AranHase/TestFindAllAsync/blob/13ba8e68d9b9061825125ff3475c6d7091aa93bf/app/src/main/java/com/example/hasegawa/testfindallasync/MainActivity.kt#L114

However, `flatMap` fails with: 

                                                                                       java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@b297227 rejected from io.realm.internal.async.RealmThreadPoolExecutor@873a166[Running, pool size = 5, active threads = 5, queued tasks = 100, completed tasks = 125]
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
                                                                                                 at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:104)
                                                                                                 at io.realm.internal.async.RealmThreadPoolExecutor.submit(RealmThreadPoolExecutor.java:68)
                                                                                                 at io.realm.RealmQuery.findAllAsync(RealmQuery.java:1470)
                                                                                                 at com.example.hasegawa.testfindallasync.MainActivity$onClick$1.call(MainActivity.kt:90)
                                                                                                 at com.example.hasegawa.testfindallasync.MainActivity$onClick$1.call(MainActivity.kt:19)
                                                                                                 at rx.Observable$29.onNext(Observable.java:8031)
                                                                                                 at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                                 at rx.internal.operators.OnSubscribeRange$RangeProducer.fastpath(OnSubscribeRange.java:126)
                                                                                                 at rx.internal.operators.OnSubscribeRange$RangeProducer.request(OnSubscribeRange.java:63)
                                                                                                 at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                                                 at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                                                 at rx.internal.operators.OnSubscribeRange.call(OnSubscribeRange.java:38)
                                                                                                 at rx.internal.operators.OnSubscribeRange.call(OnSubscribeRange.java:26)
                                                                                                 at rx.Observable.subscribe(Observable.java:8191)
                                                                                                 at rx.Observable.subscribe(Observable.java:8158)
                                                                                                 at rx.Observable.subscribe(Observable.java:8017)
                                                                                                 at com.example.hasegawa.testfindallasync.MainActivity.onClick(MainActivity.kt:85)
                                                                                                 at android.view.View.performClick(View.java:5198)
                                                                                                 at android.view.View$PerformClick.run(View.java:21147)
                                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

#### Version of Realm and tooling
Realm version(s): 0.88.1

Android Studio version: 2.1 Preview 1

Which Android version and device: Nexus 5 API 23 (emulator)

**Comment by cmelchior** [comment] 2016-03-17 09:33
Hi @AranHase 

Thank you very much for the project. I am able to reproduce it, and it looks like something is a bit off.
Especially since if you switch from `findAllAsync()` to `findAll()` it works as expected.

I'll look into it.

**Comment by cmelchior** [comment] 2016-03-17 11:30
A few observations that is unrelated to the bug:

The use of `observeOn(AndroidSchedulers.mainThread())` is actually not needed since everything is running on the main thread. Adding them just introduces additional latency, which is  why you are seeing the `RejectedExecutionException` with `flatmap` but not the current implementation. If you remove the `observeOn` it will also crash with `RejectedExecutionException`

Realm has an internal ThreadPoolExecutor that is limited to 100 tasks. AsyncTask does the same incidentially. The reason being that a mobile platform is a constrained device and running so many concurrent tasks is probably a sign of some underlying design problem.

That doesn't explain why some onNext events seem to go missing, so I'll continue to investigate further.

**Comment by AranHase** [comment] 2016-03-17 12:46
Hey @cmelchior , thank you for the observations. Now I understand the problem with the `flatMap` approach very clearly, and should be straightforward to avoid it (like using `concatMap` instead).

**Comment by cmelchior** [comment] 2016-03-17 13:41
Hi @AranHase 

I think I found the problem. When we create our Observables we don't keep a strong reference to the RealmResults which means it can be GC'ed which in turn will stop it from emitting. 

I am working on a fix, but in the mean time saving the subscription in a strong reference is a good work-around. It also makes it a lot easier to unsubscribe in case you need to abort earlier.

**Comment by AranHase** [comment] 2016-03-17 14:32
@cmelchior that was fast, thank you :) And yeah, having an explicit reference to the subscription seems like a good idea.

**Comment by cmelchior** [comment] 2016-03-31 10:26
Fixed by #2493

**Closed by cmelchior** 2016-03-31 10:26 UTC
Labels: S:Review, T:Bug
