### ISSUE TITLE
How to use Realm asObservable() with RxJava's concat() operator?

### ISSUE THREAD

**Issue by ar-g** [realm/realm-java#1998] opened 2015-12-23 15:52 UTC
I'm trying to use Realm with RxJava and Retrofit in a way DanLew described [here][1] concating input from realm and retrofit but it gets stuck if I adding realm into the chain
```java
    Observable.concat(countryStorage.restoreAsObservable(),
                  networkService.api()
                      .getCountries()
                      .doOnNext(countryStorage::save))
                  .first()
                  .observeOn(AndroidSchedulers.mainThread())
                  .subscribe(//never reaching here)
```
storage
   
```java
     @Override public Observable<List<Country>> restoreAsObservable() {
            Realm realm = realmProvider.get();
            return realm.where(Country.class)
                .findAll()
                .asObservable()
                .map(countries -> return realm.copyFromRealm(countries))
                .first(countries -> return !countries.isEmpty())
                .doOnCompleted(realm::close());
          }
```
It seems that this could happen that observable is hot from Realm, but nothing about it in the docs and how I suppose to compose Realm with other observables?

**UPDATE:**
It turns to be that it works fine in old way. The question still remain about new api.
```java
    return Observable.just(
            realm.copyFromRealm(realm.where(Country.class).findAll()))
            .filter(countries -> !countries.isEmpty())
            .doOnCompleted(realm::close);
```

[1]: http://blog.danlew.net/2015/06/22/loading-data-from-multiple-sources-with-rxjava/

**Comment by cmelchior** [comment] 2015-12-24 06:29
Hi @ar-g 
From a quick glance, that code looks OK. What does your subscriber do? Even if Realm somehow did something wrong, you should still see an List emitted from the Network request.

Also, all Realm Observables are hot as they are are automatically kept up to date. This is also mentioned in the documentation. If you want a `onComplete()` event doing `first()` like you do should work.

**Comment by ar-g** [comment] 2015-12-24 08:59
Hey @cmelchior 
This is the problem it is just getting frozen and when debugging it's not even reaching the subscriber. Doesn't matter if there is data in realm or not. Concat operator waiting for until sequence from realm will finish which is not happening. I guess it's my mistake. It seems to be correct behaviour if need to have up to date data. 

So in case, I need sequence will finish after emitting data. Should I use realm like in Update code?

**Comment by cmelchior** [comment] 2016-01-04 08:16
Hi @ar-g 
Sorry for the late reply. The original code should be fine from what I can tell so something else must be going on. I can see you are doing this:

```
 .first(countries -> return !countries.isEmpty())
```
Which would filter out any empty lists, maybe that is preventing your observable from continuing?

**Comment by cmelchior** [comment] 2016-01-21 08:35
Closing due to no response. Please reopen if you are still seeing this issue.

**Comment by prefanatic** [comment] 2016-01-23 15:10
I'm having a similar problem to @ar-g,

```java
Observable<Summoner> disk = realm.where(Summoner.class)
                    .equalTo("name", name)
                    .findFirst()
                    .asObservable()
.cast(Summoner.class);

Observable<Summoner> network = summonerInterface.getSummonersByNames(region.region, name, API_KEY)
                    .compose(netTransformer(method))
                    .map(result -> result.get(name))
                    .filter(result -> result != null);

return Observable.concat(disk, network)
                    .first()
                    .doOnError(e -> Timber.e(e, "SummonerApi.getSummonerByName(%s)", name));

**Comment by cmelchior** [comment] 2016-01-26 10:54
Are you able to create a small example project that reproduces this? 

I tested the following, which works:
```
realm.beginTransaction();
realm.createObject(AllTypes.class).setColumnLong(42);
realm.commitTransaction();

Observable<AllTypes> disk = realm.where(AllTypes.class).equalTo(AllTypes.FIELD_LONG, 42).findFirst()
        .asObservable()
        .cast(AllTypes.class);

AllTypes inMem = new AllTypes();
inMem.setColumnLong(1);
Observable<AllTypes> inMemory = Observable.just(inMem);

Observable.concat(disk, inMemory)
        .first()
        .doOnError(new Action1<Throwable>() {
            @Override
            public void call(Throwable throwable) {
                fail("BOOM : " + throwable.getMessage());
            }
        })
        .subscribe(new Action1<AllTypes>() {
            @Override
            public void call(AllTypes rxObject) {
                assertEquals(42, rxObject.getColumnLong());
            }
        });
```

In the code above you are just returning an observable. Are you just subscribing to that or are you manipulating the observable further?

**Comment by kneth** [comment] 2016-02-03 10:49
@prefanatic Did you have success with the suggestions by @cmelchior?

**Comment by prefanatic** [comment] 2016-02-03 22:26
@kneth @cmelchior 

Sorry for the delay - I haven't had much time recently to look into this in much more detail.

I haven't been able to reproduce this since my original comment.  I believe my findFirst issue was caused by having no objects in Realm to start with, and I was hitting NPE's.  Those NPE's were originally hidden from me due to my onError handling from the observable wasn't quite verbose.

However find(First/All)Async still don't work properly for me.  I only get "RealmObject is not valid" responses from the result of said operation.  Filtering these objects by isLoaded doesn't make too much sense for me, as I know for a fact these objects exist within Realm.

I get proper functionality by handling the async myself, by leveraging Observable.defer w/ subscribeOn and observeOn myself.  Inside this defer, I access the default realm instance and then block with findAll.

**Comment by cmelchior** [comment] 2016-02-12 08:32
Hi @prefanatic `findFirst().asObservable()` will always emit an object, but that object is just a placeholder and you can check `isValid()` to see if it contains any data, also we found a bug with `findFirstAsync` that caused it to never emit if it didn't find any results, which might have been the cause of this. It has been fixed in our `0.88-SNAPSHOT` though.

But its great you found a work-around, so i'll close this now.

**Closed by cmelchior** 2016-02-12 08:32 UTC
Labels: T:Help

**Comment by savepopulation** [comment] 2016-09-07 08:24
hi @cmelchior findFirst().asObservable() gets null pointer if findFirst() returns null. You get a null pointer exception.

**Comment by cmelchior** [comment] 2016-09-07 08:26
@savepopulation Yes, sorry it should have been `findFirstAsync().asObservable()` `findFirstAsync()` always returns an object. You can check if it is valid by using `obj.isValid()`.

**Comment by savepopulation** [comment] 2016-09-07 10:08
@cmelchior thanks for fast reply :) I already use `findFirstAsync()` but with RxJava concat operator it gets stuck.

Here's my local observable implementation:

```
return realm.where(Page.class)
               .equalTo("query", query)
               .findFirstAsync()
               .asObservable()
               .filter(new Func1<RealmObject, Boolean>() {
                   @Override
                   public Boolean call(RealmObject realmObject) {
                       return realmObject.isValid() && realmObject.isLoaded();
                   }
               })
               .subscribeOn(AndroidSchedulers.mainThread())
               .cast(Page.class);

```

**Comment by Zhuinden** [comment] 2017-01-16 09:35
"local observables" don't make sense with Realm's default RxObservableFactory, because `onCompleted()` is never called. It's because all data shown on the UI should belong to a Realm instance on that given thread.

`Observable.concat()` requires `onCompleted()` to work, but a `RealmChangeListener`'s listening does not end unless you remove it (which happens when you unsubscribe).
