### ISSUE TITLE
Java 1.8 and Android not working

### ISSUE THREAD

**Issue by mars3142** [realm/realm-java#2630] opened 2016-04-20 14:14 UTC
I can't use Android with Java 1.8 and Realm.

see http://stackoverflow.com/questions/36746452/realm-io-with-java-1-8-and-android

The jack option is found: http://developer.android.com/preview/j8-jack.html

**Comment by stk1m1** [comment] 2016-04-20 14:34
Hi @mars3142 

Could you be kind enough to provide us a simple example we can reproduce the problem you are going through? We'd have hard time to fully comprehend the cause that leads to the situation above.

**Comment by bkromhout** [comment] 2016-04-20 15:13
@mars3142, if you look at the bottom of the page that your second link goes to, you'll notice that there are a few drawbacks to using Jack currently. One of those is that Jack doesn't currently expose a way to modify your application's class files between the compilation and packaging steps. 

Now, I know for a fact that this means that the android-apt plugin won't work with Jack currently, and I'm fairly sure that Realm also uses the same transformer API to do its bytecode manipulation, so it also won't work either. Simply put, Jack isn't going to be an option if you want to use android-apt or Realm currently (or any library which uses android-apt, such as ButterKnife, Dagger, etc).

If you want some of the Java 8 features (such as lambdas), I would recommend *not* using Jack for now, and instead using retrolambda. I won't go into that since there are numerous tutorials on the internet detailing that, but I can tell you that I use both retrolambda and Realm in my project and they work perfectly.

Relevant links:
* [This article](http://trickyandroid.com/the-dark-world-of-jack-and-jill/) explains the issue more in depth than I have here 
* [Issue on android-apt](https://bitbucket.org/hvisser/android-apt/issues/33/support-for-jack-and-jill#comment-26954359)
* [Issue on Android bug tracker](https://code.google.com/p/android/issues/detail?id=204065)

**Comment by cmelchior** [comment] 2016-04-20 15:15
Hi @bkromhout. Thanks for the detailed response and you are pretty much spot on. Realm uses both annotation processing and the Transform API, neither of which are supported by Jack right now.

**Comment by mars3142** [comment] 2016-04-21 06:39
And why can't you implement realm without the need for manipulating of the bytecode? Everytime Google changes the build tools, dependencies like realm and others will break. That's really bad.

**Comment by cmelchior** [comment] 2016-04-21 06:47
You can hardly fault people for using the API's and tools that are at their disposal today? Nobody knows what will happen in the future and Jack is still very much work-in-progress. 

It is fair that you want to try bleeding edge build tools, but they are clearly marked as such by Google with all the caveats that come with it.

We try to support the newest stuff as soon as possible, but trying to make Realm work with a build tool that isn't even complete yet doesn't seem like the best use of our time.

**Comment by FabianTerhorst** [comment] 2016-04-21 20:25
you can follow the progress of jack bytecode manipulation support here: https://code.google.com/p/android/issues/detail?id=204065

**Comment by emanuelez** [comment] 2016-04-21 20:41
Not to mention that Google itself just started to provide first party tools to do proper bytecode manipulation in the build system (the Transform API), and that's what we waited to provide a functionality long waited for.

**Closed** 2016-05-02 12:30 UTC
Labels: S:Waiting For User, T:Help

**Comment by Zhuinden** [comment] 2016-05-17 14:33
> we waited to provide a functionality long waited for.

For those wondering, that being the ability to implement interfaces on RealmObjects (and have custom methods), and that getters/setters are no longer necessary.

So it's quite a win.

**Comment by shashank090789** [comment] 2016-09-05 05:48
@cmelchior any update regarding this?

**Comment by beeender** [comment] 2016-09-05 05:54
@shashank090789 There is still no response from google about transforming API support for JACK. See https://code.google.com/p/android/issues/detail?id=210730&q=Jack%20transform&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

**Comment by kirsting** [comment] 2016-12-12 02:25
Right now in my project, we extract realm to another module and setup realm there, then open jack in 'app' module is fine.

**Comment by kneth** [comment] 2016-12-12 12:05
@kirsting If you have time - and are allow to do so - it would be great for the community if you can share some code and comments on how you do that.

**Comment by kirsting** [comment] 2016-12-12 13:01
@kneth Before we move to jack, our project setup realm in 'app' module (add realm plugin to 'app' module's build.gradle file). Then we create a new module named 'core' and add realm plugin to 'core' module's build.gradle. We move all RealmObject classes and some realm relevant classes to 'core' module.  Then we add 'core' module's dependency to 'app' module and remove realm plugin in 'app' module's build.gradle file. 
Realm plugin is not working with jack. Since realm plugin and jack are all module level, move realm plugin and basic RealmObject classes to another module as a library. That's our thought. Sorry for my poor English explanation..

**Comment by Zhuinden** [comment] 2016-12-23 09:50
```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
        maven {url "https://clojars.org/repo/"}
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath "io.realm:realm-gradle-plugin:1.2.0"
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
    }
}
```

and

```
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'realm-android'

android {
    compileSdkVersion xx
    buildToolsVersion "xx"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

works just fine for Java 8 language features (lambdas, method references, try-with-resources), btw.

**Comment by Zhuinden** [comment] 2016-12-29 17:31
@ojarabo I have never seen that error before.

https://github.com/Zhuinden/rx-realm-recyclerview-experiment/blob/master/app/build.gradle

This example works for me...

**Comment by ojarabo** [comment] 2016-12-29 18:18
Thanks ;)

**Comment by ojarabo** [comment] 2016-12-30 09:53
@Zhuinden Thanks. I have checked and indeed works. My problem is that I was using jack, but I know there are other open issues regarding to jack-retrolambda-realm.

**Comment by Zhuinden** [comment] 2016-12-30 11:15
@ojarabo Jack doesn't work until https://code.google.com/p/android/issues/detail?id=210730 is resolved

**Comment by nremond** [comment] 2017-01-28 10:21
@Zhuinden the good news is that the issue is now resolved :-)

**Comment by Zhuinden** [comment] 2017-01-28 10:58
@nremond I assume Realm would need to somehow make their plugin work with Jack

**Comment by Zhuinden** [comment] 2017-03-15 13:55
@nremond now that Jack is deprecated, there is no need to support Jack

**Comment by maoueh** [comment] 2017-03-15 20:03
@Zhuinden Jack is deprecated? Do you have a link pointing to this?

**Comment by kneth** [comment] 2017-03-16 10:49
@maoueh The good news is that we will get Java 8 soon!

**Comment by olegsoftjava** [comment] 2017-06-23 13:39
Hi, it work. Realm + Java8 + -> ;)
My Gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.xxx.xxx.xxx"
        minSdkVersion 17
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}


buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:3.4.0"
    }
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'me.tatarka:gradle-retrolambda:3.2.3'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'io.reactivex:rxjava:1.1.6'

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.google.firebase:firebase-database:10.0.1'
    compile 'com.google.firebase:firebase-auth:10.0.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.mostafagazar:customshapeimageview:1.0.4'
    compile 'com.github.bluejamesbond:textjustify-android:2.1.6'
    testCompile 'junit:junit:4.12'
}

apply plugin: 'realm-android'
apply plugin: 'me.tatarka.retrolambda'

allprojects {
    tasks.withType(JavaCompile) {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}

**Comment by kneth** [comment] 2017-06-23 14:24
@olegsoftjava You are using preview of Android Studio 3.0, right?

**Comment by olegsoftjava** [comment] 2017-06-23 14:37
my Android studio 2.3.3

**Comment by olegsoftjava** [comment] 2017-06-23 14:38
All info:
Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by Zhuinden** [comment] 2017-06-23 16:33
> classpath 'me.tatarka:gradle-retrolambda:3.2.3'
> apply plugin: 'me.tatarka.retrolambda'

Yep, Retrolambda works, although when Android Studio 3.0 comes out (and Realm can finally support the build tools 3.x as well) then Retrolambda will no longer be needed
