### ISSUE TITLE
IllegalStateException: Class doesn't exist and the shared Realm is not in transaction.

### ISSUE THREAD

**Issue by johnryan** [realm/realm-java#3667] opened 2016-10-20 16:30 UTC
```
java.lang.IllegalStateException: Class class_TWUser doesn't exist and the shared Realm is not in transaction.
    at io.realm.internal.SharedRealm.nativeGetTable(SharedRealm.java)
    at io.realm.internal.SharedRealm.getTable(SharedRealm.java:226)
    at io.realm.RealmSchema.getTable(RealmSchema.java:296)
    at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:316)
    at io.realm.RealmQuery.<init>(RealmQuery.java:138)
    at io.realm.RealmQuery.createQuery(RealmQuery.java:87)
    at io.realm.Realm.where(Realm.java:1214)
    at com.truly.truly.datamanagers.UserDataManager.getCurrentUser(UserDataManager.java:38)
    at com.truly.truly.base.TrulyApplication.getCurrentUser(TrulyApplication.java:248)
    at com.truly.truly.base.TrulyApplication.isLoggedIn(TrulyApplication.java:262)
    at com.truly.truly.util.GcmIntentService.onHandleIntent(GcmIntentService.java:77)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

I've tried to reproduce unsuccessfully but the Realm has been initialized (it happens in the onCreate of `TrulyApplication` so i'm not sure how it could get into this state
#### Version of Realm and tooling

Realm version(s): 2.0.2

Android Studio version: 2.2.1

Which Android version and device: SM-G900T / 6.0.1

**Comment by kneth** [comment] 2016-10-24 09:36
So you find

    Realm.init(context);
    realm = Realm.getDefaultInstance();

somewhere? And without errors?

**Comment by johnryan** [comment] 2016-10-24 13:00
Correct, the Realm.init(context) is called earlier in the stack trace during the initialization of the application. I would assume it would have crashes there if there was a problem with the .init()

**Comment by Zhuinden** [comment] 2016-10-24 13:03
Do you use Firebase Crash Reporting?

**Comment by johnryan** [comment] 2016-10-24 13:29
@Zhuinden No this crash report is from HockeyApp

**Comment by cmelchior** [comment] 2016-10-27 12:04
The error seems to happen in your `GCMIntentService`. Is that intent service running in its own process?

**Comment by johnryan** [comment] 2016-10-27 15:09
@cmelchior I don't think it is i.e. it has no process specified in AndroidManifest.xml. One other interesting thing of note, looking at our crash for an OOM error came in at the exact same time. Is it possible that either the OOM killing the process could have caused some weird state?

**Comment by nyarlathotep77** [comment] 2016-11-02 14:26
I'm having a very similar issue but only on Proguard'ed release builds.
Is it the same in this scenario or does it happen on debug build variants as well?

**Comment by johnryan** [comment] 2016-11-02 14:30
@nyarlathotep77 i'm also using proguard

**Comment by nyarlathotep77** [comment] 2016-11-02 14:49
It seems the issue is not strictly related to Proguard, but Release builds. I've built a release non-Proguard'ed version of my app and I can still see the problem.
If I build a debug version the problem disappears.
@johnryan do you have the same behaviour?

**Comment by johnryan** [comment] 2016-11-02 15:07
@nyarlathotep77 this crash has only happened in production a few times, i'm not sure how to reproduce, but yes mine is also a release build.

**Comment by johnryan** [comment] 2016-11-02 16:31
@nyarlathotep77 actually I was able to make it happen once in a debug build, I think it has something to do with calling `realm.deleteAll();` trying to reproduce though

**Comment by kneth** [comment] 2016-11-07 08:33
@johnryan Did you have any success in reproducing the issue?

**Comment by kneth** [comment] 2016-11-21 08:28
@johnryan I'll close the issue for new. If you have any updates (in particular a reproduction test case), don't hesitate to reopen.

**Closed by kneth** 2016-11-21 08:28 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help

**Comment by Zhuinden** [comment] 2016-11-21 08:31
This really sounds like an issue with multiple processes. Possibly multi-process migration, actually. Broadcast receivers and pending intent + notification or an incomplete application upgrade could produce something like this.

**Comment by mabuthraa** [comment] 2017-09-16 09:28
I could reproduce this issue easily. It happens when firstly Realm has been initialized then later resources of Realm being removed in internal storage of app (as default location). Next operation from Realm instance would throw that exception above. It's necessary to init Realm again to avoid that exception .. just note that database data had been rubbed out.

I hope that might help,'.
