### ISSUE TITLE
Target SDK NullPointer Exception

### ISSUE THREAD

**Issue by RaysonYeungHK** [realm/realm-java#6084] opened 2018-07-26 09:46 UTC
As I removed the targetSdkVersion from the gradle file, the app cannot compile anymore.

Here is the error log

Caused by: java.lang.NullPointerException
        at io.realm.transformer.Utils.getTargetSdk(Utils.java:67)
        at io.realm.transformer.RealmTransformer.sendAnalytics(RealmTransformer.kt:154)
        at io.realm.transformer.RealmTransformer.exitTransform(RealmTransformer.kt:116)
        at io.realm.transformer.RealmTransformer.transform(RealmTransformer.kt:111)
        at com.android.build.api.transform.Transform.transform(Transform.java:288)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

**Comment by nhachicha** [comment] 2018-07-26 10:01
duplicate of  https://github.com/realm/realm-java/issues/6082

**Closed by nhachicha** 2018-07-26 10:01 UTC
Labels: O:User
