### ISSUE TITLE
"Realm instance has been closed" exception on un-closed Realm

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4648] opened 2017-05-15 22:51 UTC
@cmelchior and @zhuinden recall quirky experiences with `RealmCache` causing an open Realm to appear closed.

The issue arose, recently in #4641 

This issue tracks identifying and fixing the bug

**Comment by bmeike** [comment] 2017-05-15 23:46
@zaki50 suggests that this may be related to #4551

**Comment by zaki50** [comment] 2017-05-15 23:50
@bmeike No, since #4551 is only in the `master` branch and not yet released.

**Comment by Zhuinden** [comment] 2017-05-16 06:52
I wanted to find this odd behavior a while ago to pinpoint it if there truly is an issue somewhere - all I know is that Realm instance doesn't "auto-close" unless you actually call `close()` on a Realm instance *somewhere*. But I don't know if calling `close()` on one instance can truly affect other instance.

**Comment by cmelchior** [comment] 2017-05-16 06:56
Note, I don't think it is related to the RealmCache, but to the activity lifecycle. If I remember correctly last I checked, it appeared that sometimes things like ListView/RecyclerView would get invalidated during `onDestroy()` which would force a redraw and then naturally crash since the Realm was closed and data not available. I did not get to the bottom of it though.

**Comment by bmeike** [comment] 2017-05-17 21:37
@cmelchior Shall I move this issue to #adapters?

**Comment by xiaogu-space** [comment] 2017-06-14 03:55
I also encountered the same problem，is there a good solution？

**Comment by beeender** [comment] 2017-08-04 09:26
@bmeike do we have any reproduce steps for this? After checking the original issue, it looks very much something wrong in the user's code with controlling Realm life-cycles.

**Comment by Zhuinden** [comment] 2017-08-04 09:35
I think it was all caused by just that RealmResults and its Change listener is not invalidated / removed when activity.onDestroy is called so if a change happens after activity dies, the RealmResults is not guaranteed to be dead and can still try to update adapter even though it is a dead view hierarchy

**Comment by Zhuinden** [comment] 2017-08-04 09:36
Also Realm should be closed only after `super.onDestroy` because of some accessibility magic

**Comment by Zhuinden** [comment] 2017-08-04 09:45
@beeender so it is as if even though local instance is closed, then RealmResults is invalid even if global instance is open.

**Comment by beeender** [comment] 2017-12-12 05:16
should be a user issue, don't see there is an issue with `RealmCache`. close it.

**Closed by beeender** 2017-12-12 05:16 UTC
Labels: T:Bug
