### ISSUE TITLE
Wrong transactional state

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-java#5458] opened 2017-10-24 09:53 UTC
#### Goal

I think this is a know problem, I've sent the full log privately to help@tpro.io.

#### Steps & Code to Reproduce

> It's really hard to reproduce, this never happened to me and only happened to two users of our app.

Example of log:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.my.app/com.my.app.MainActivity}: java.lang.IllegalStateException: Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3788)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by java.lang.IllegalStateException: Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)
       at io.realm.internal.OsObject.nativeStartListening(OsObject.java)
       at io.realm.internal.OsObject.addListener(OsObject.java:114)
       at io.realm.ProxyState.addChangeListener(ProxyState.java:136)
       at io.realm.RealmObject.addChangeListener(RealmObject.java:448)
       at io.realm.RealmObject.addChangeListener(RealmObject.java:355)
       at com.my.app.mainPresenter.checkUser(MainPresenter.kt:69)
       at com.my.app.MainActivity.onResume(MainActivity.kt:238)
```
#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: no

Which Android version and device: Android 7.0

**Comment by beeender** [comment] 2017-10-24 10:07
Uh, this issue! it is a restriction of the listener implementation.
Would you be able to move the `addChangeListener()` call out of the listener callback?

**Comment by ppamorim** [comment] 2017-10-26 16:46
@beeender I need to always listen the change of this object. What you recommend me to do?
On the first app run the object is null, but after a server sinchronization this value gets loaded and attached into a change listener. Will it be solved if I create a method to reload this object on change and then attach the listener?

**Comment by Zhuinden** [comment] 2017-10-26 17:23
For me,

       at com.my.app.mainPresenter.checkUser(MainPresenter.kt:69)
       at com.my.app.MainActivity.onResume(MainActivity.kt:238)

Seeing these two methods would be nice.

**Comment by beeender** [comment] 2017-10-27 05:02
the backtrace shows that it happens in `com.my.app.MainActivity.onResume` which feels like you called `beginTransaction()` without `commitTransaction()`/`cancelTransaction()` on the **UI thread**. Is it possible? sometimes if exception happens after `beginTransaction()` and it has been caught, the transaction may not be closed properly. I guess use `Realm.executeTransaction()` will avoid this problem.

**Comment by ppamorim** [comment] 2017-10-27 17:55
@beeender No transaction is done on UI thread. The structure here is very strong and only allow transactions on a interactor that uses the ThreadPoolExecutor (kinda of async task that I created).

**Comment by ppamorim** [comment] 2017-10-27 17:59
@Zhuinden `onResume()` call the method `checkUser()` of the presenter, this method searches the user on the realm file, with no transaction involved. Loads the managed object and attach the `ObjectChangeListener` and them notify the view the result of search, all on the UI thread of course. The presenter's `ObjectChangeListener` notifies the view too.

**Comment by ppamorim** [comment] 2017-10-27 18:02
@beeender Maybe an transaction during the query? Remember: All transactions are made out of the main thread and all queries of objects that are used on the UI are made on the UI thread.

**Comment by Zhuinden** [comment] 2017-10-27 18:19
I have this feeling that this could be fixed by putting the `addRealmObjectListener` into a `handler.post()` but I have honestly no idea why that would be needed

**Comment by ppamorim** [comment] 2017-10-27 20:01
@Zhuinden `handler.post()` solves anything.

**Comment by beeender** [comment] 2017-10-30 03:08
The callback of the listeners will be running on the caller thread. So if you have add a listener from the UI thread, then the listener will be called on the UI thread. Maybe that is the problem?

Anyway, happy to know your problem is solved. But it is important to know what is the root cause :)

**Closed by beeender** 2017-10-30 03:08 UTC
Labels: T:Help

**Comment by Zhuinden** [comment] 2017-10-30 08:32
Is it really solved?

**Comment by ppamorim** [comment] 2017-11-02 10:45
@beeender @Zhuinden Not really, Until now I was not able to send a update correcting this issue. But based in the solution I think it will work. Thanks btw.

**Comment by ppamorim** [comment] 2017-11-10 16:57
@beeender @Zhuinden Happened to me again while the app was adding the listener on root object. :(

**Comment by beeender** [comment] 2017-11-16 03:15
@ppamorim 

Call `RealmLog.setLevel(LogLevel.ALL);` at the beginning of the app, and get a full logcat for us. I can help to check.
