### ISSUE TITLE
Sorting results by child RealmList size

### ISSUE THREAD

**Issue by cioraneanu** [realm/realm-java#4501] opened 2017-04-14 18:40 UTC
I love the addition of sorting by linked fields, but I find myself needing a sort by child list size as well.

For example:
```
public class Person extends RealmObject {
    private String name;
    private RealmList<Dog> dogsList;
}

public class Dog extends RealmObject {
    private String name;
    private int age;
}
```

I want to get the list of Persons sorted by the number of dogs they own. Something like this:
`personsList = personsList.sort("dogsList.size", Sort.DESCENDING);`

Currently I'm stuck with using redundant fields such as "dogsCount" and updating these fields at each add/delete operation which is a real pain. Any chance to get this kind of sort? :)

**Comment by Zhuinden** [comment] 2017-04-14 18:52
Well it would be nice but it is tracked by https://github.com/realm/realm-java/issues/1598 currently

**Comment by zaki50** [comment] 2017-04-15 12:29
Hi @cioraneanu 

As @Zhuinden said, we don't have a feature for that for now.
You need to maintain count field as you said.

I'll close this as a duplicate of #1598.

**Comment by zaki50** [comment] 2017-04-15 12:40
Ah, sorry.  #1598 is for query, not for sorting.
I'm reopening this.

**Comment by bdkjones** [comment] 2021-08-30 08:17
I don't suppose there's been any progress on this in 4 years? It's a very large pain point in an otherwise excellent framework.

**Comment by cmelchior** [comment] 2021-08-30 08:23
Unfortunately not. The Core issue to track is this one: https://github.com/realm/realm-core/issues/4586.

Right now the work-around would be to maintain a separate property with the size information, e.g `list` and `listSize` But I can see that being annoying to do.

**Closed** 2024-05-23 13:37 UTC
Labels: T-Enhancement, O-Community, Pipeline-Idea-Backlog
