### ISSUE TITLE
Interprocess support for encrypted Realms

### ISSUE THREAD

**Issue by KynoYang** [realm/realm-java#1477] opened 2015-09-17 15:53 UTC
Realm version is 0.8.2,  Android version is 4.4.2

Encrypted interprocess sharing is currently unsupported in io_realm_internal_SharedGroup.cpp line 115
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
       at io.realm.Realm.<init>(Realm.java:207)
       at io.realm.Realm.createAndValidate(Realm.java:597)
       at io.realm.Realm.create(Realm.java:567)
       at io.realm.Realm.getInstance(Realm.java:540)

Anyone know what it is?

**Comment by beeender** [comment] 2015-09-17 16:19
Are you using same Realm in different processes? @KynoYang Multi-processes support for java is not supported yet...

**Comment by KynoYang** [comment] 2015-09-18 03:45
Yes, OMG...

**Comment by kneth** [comment] 2015-09-23 12:49
As @beeender points out, multiprocess access isn't yet supported - see #1091.

**Comment by beeender** [comment] 2016-05-17 14:01
@KynoYang is still seeing this issue http://crashes.to/s/afa05a92642

This should be the dup issue to #2762

**Comment by phamducgiam** [comment] 2016-06-20 04:09
Hi.

I encountered this issue too cause of using firebase. It causes by adding plugin 'com.google.gms.google-services' for automatically integrating firebase sdk. If I removed that plugin or remove realm encryption, everything is ok. Any suggesstion? Thanks.

**Comment by beeender** [comment] 2016-06-20 04:28
@phamducgiam Do you have something like `process:remote` in your manifest?

**Comment by phamducgiam** [comment] 2016-06-20 04:41
@beeender: I just found out. It's because firebase crash automatically create a background process for reporting. I just disable firebase crash for now and will fix it later.

**Comment by biftekman** [comment] 2016-07-25 07:27
Here's my observation, reposted here as instructed in #3203


```
io.realm.exceptions.RealmError: Unrecoverable error. /data/data/<package>/files/database.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 22257. Current pid is 17958. in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.a(SourceFile:95)
	at io.realm.internal.SharedGroup.<init>(SourceFile:74)
	at io.realm.internal.SharedGroupManager.<init>(SourceFile:49)
	at io.realm.BaseRealm.<init>(SourceFile:81)
	at io.realm.Realm.<init>(SourceFile:140)
	at io.realm.Realm.b(SourceFile:240)
	at io.realm.Realm.a(SourceFile:220)
	at bbq.a(SourceFile:126)
	at io.realm.Realm.getDefaultInstance(SourceFile:166)
```

Crashlytics reports this kind of crash for around 1,5% of about 50k users so far and I can't figure out what causes it, neither reproduce it on any of our test devices or emulator.


**Things to consider:**
- `getDefaultInstance()` that causes the crash is always called inside `onCreate()` method of our Application class. That's where Realm's default configuration gets set and default instance is obtained.
- Our manifest file doesn't define any remote processes, like `process:remote`
- If a third party library created a remote process, we would expect the crash to always happen? (I also try to catch it with RealmIOException, but that doesn't seem to do anything for any reason)
- Crash always spikes on the first days following the update and drops significantly after, indicating that only users who updated get affected.
- Considering the sheer amount of crashes and users affected, we get no complaint emails reporting this.


#### Version of Realm and tooling
Realm version(s): 1.1.0
Android Studio version: 2.1.2
Which Android version and device: all supported (4.0.3+)

**Comment by stk1m1** [comment] 2016-07-25 07:34
I'm reopening this issue as this is repoted to exist still.

**Comment by beeender** [comment] 2016-07-26 02:48
@biftekman A hypothesis is there is a bug with some devices's package manager. When installing and running the new version of APK, the old process has not been killed yet -- This would trigger your issue and #2928 . 

> Crash always spikes on the first days following the update and drops significantly after, indicating that only users who updated get affected.

And I think above fact supports our hypothesis well.

We made some workaround try to solve #2928 -- delay some time if we see there is another process alive and opening the Realm file, but from feedback, it doesn't help too much :(

**Comment by biftekman** [comment] 2016-07-26 06:50
@beeender does the crash then kill the old process as well? Meaning that reopening the app afterwards would occur normally?

**Comment by beeender** [comment] 2016-07-26 06:56
@biftekman It will only kill the process which throws this exception. But from the exception message:

> Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 22257. Current pid is 17958. in io_realm_internal_SharedGroup.cpp

Interesting thing is we can see it is actually the old process throws the exception ( `17958`, since the pid number is not big enough, i guess we can assume `22257` is started later than `17958`).

Can you see in the crashlytics backend that the exception is reported from the old version or the new version? (Although I am not quite sure how does crashlytics get the version information. If it gets the information based on the apk installed on the system, then it will always reports the new version i think?)

**Comment by biftekman** [comment] 2016-07-26 07:41
@beeender 
Looking through our crash logs, current pid value is not always less than opened one, for example

> Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 4543. Current pid is 22644. in io_realm_internal_SharedGroup.cpp line 113

But that should not indicate that current process id is either "newer" or "older". Although PIDs are allocated on a sequential basis, but when max value is reached, allocations start from 0 again. 


Regarding Crashlytics reporting: as it is in our case initialised inside Application class which can be started by a process under the same package, it will report a crash from whatever process causes it. Since we always see crash results matching the newer versions, I'd guess the new process throws the exception.

**Comment by beeender** [comment] 2016-07-26 07:46
`4543` is a quite small number for a pid, unless it is just powered on, i'd rather to assume it is "older" than `22644`. But anyway, it is all guessing ... 

Do you have any logic to restart a service in the apk? I tried something like `START_STICKY`, but cannot reproduce it :(

**Comment by biftekman** [comment] 2016-07-26 08:49
The only time the app starts a service is when I bind IInAppBillingService to Activity.

But in any case, creating another process during runtime should crash the app in our situation anyway, since Realm instance is obtained in application class, which never happens. So that shouldn't prove anything. 

Regarding your original hypothesis, did you manage to reproduce the "not-killed process on update" before?
If so, it seems very plausible.

**Comment by beeender** [comment] 2016-07-26 08:56
We tried a lot, but never reproduce "not-killed process on update" :(

But from the crash log, there are two processes for a same app are running in the system which should not ever happen ... We tried a lot but cannot reproduce it on any of our devices ...

**Comment by biftekman** [comment] 2016-07-26 12:27
Is a following workaround currently possible for our situation:
If there is a process that holds an open instance of Realm, is there a way to detect that and close that instance from second process that is about to obtain a new instance?

**Comment by beeender** [comment] 2016-08-02 06:50
@biftekman Sorry for the late reply
> If there is a process that holds an open instance of Realm, is there a way to detect that and close that instance from second process that is about to obtain a new instance?
The problem is it is really hard to detect the other process is holding an open instance for good or not.

> Never obtain an instance of Realm in Application class, because that will keep it open for as long as that process is alive.
> Instead, always obtain instance when needed and close when done, without exceptions.
Yep, I think this could make the situation better. But one concern is if the system is still not doing the right thing, eg.: running into the old process's service which tries to open a Realm there, it still could happen :(

**Comment by beeender** [comment] 2016-08-02 07:56
@biftekman Do you use firebase or any other libs could start a background process?

**Comment by biftekman** [comment] 2016-08-02 08:45
@beeender no.

For the next update I'm working on a workaround, trying to catch a process about to be destroyed and make sure every Realm instance is closed before it does.
Will let you know if it'll have any impact.

Also, if it would help, should I send you the crash reports?
With about 5000 crashes in the last two weeks, might be some interesting data there :)

**Comment by beeender** [comment] 2016-08-02 08:47
@biftekman Yes, please! also a apk would be helpful. You can send it to help@realm.io if you want to share it privately. Thanks a lot!

**Comment by fjzboy** [comment] 2017-01-05 05:18
01-05 13:16:16.556 17572-17572/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   io.realm.exceptions.RealmError: Unrecoverable error. /data/data/com.fjz.caipu/files/caipu.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 16761. Current pid is 17572. in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
                                                       at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
                                                       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
                                                       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
                                                       at io.realm.Realm.getDefaultInstance(Realm.java:209)

when I killed my app from TaskManager, then launch it again, this crash happened.

**Comment by kneth** [comment] 2017-01-05 12:44
Which version of Realm do you use?

**Comment by fjzboy** [comment] 2017-01-06 05:07
Hi,
I use 2.2.0 version, and I find that this issue happened  only on some of device(coolpad), and worked well on samsung s7.

**Comment by kneth** [comment] 2017-01-06 09:52
@fjzboy Which model of coolpad? The reason I ask is that I wish to see if is reproducible on that Android version in general or if it's a device specific thing.

Can you try to upgrade to 2.2.2?

**Comment by dimmduh** [comment] 2017-01-26 08:54
Same issue :(
samsung s6
`E/REALM_JNI: jni: ThrowingException 5, /data/data/com.offer4app.demo/files/default.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 3359. Current pid is 3303. in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 87, .
01-26 16:51:09.881 3303-3540/com.offer4app.demo E/REALM_JNI: Exception has been throw: Unrecoverable error. /data/data/com.offer4app.demo/files/default.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 3359. Current pid is 3303. in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 87
01-26 16:51:09.881 3303-3540/com.offer4app.demo E/REALM_JAVA: io.realm.exceptions.RealmError: Unrecoverable error. /data/data/com.offer4app.demo/files/default.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 3359. Current pid is 3303. in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 87
                                                                  at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:208)
                                                                  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:186)
                                                                  at io.realm.RealmQuery$2.call(RealmQuery.java:1699)
                                                                  at io.realm.RealmQuery$2.call(RealmQuery.java:1692)
                                                                  at io.realm.internal.async.BgPriorityCallable.call(BgPriorityCallable.java:36)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)`

**Comment by Zhuinden** [comment] 2017-01-26 09:01
@dimmduh SharedGroup? what Realm version are you using

**Comment by Zhuinden** [comment] 2017-01-26 09:02
That's interesting, `SharedRealm.finalize()` got an NPE

**Comment by dimmduh** [comment] 2017-01-26 09:18
@Zhuinden I used 2.2.2. I just updated to 2.3.0 and got same issue.
I reproduced issue, and I guess it's not because of realm (but that's not good that's it crashes the app).
1) I debug connection on phone via proxy to fiddler
2) I use appmetrica sdk, when app start, appmetrica init and trying to connect, but cannot because fiddler change ssl sert and appmetrica server does not accept connection.
3) I close app and launch again => and got this issue
I guess because appmetrica does not let app finish and realm is still occupied when I restart app.
I guess it can happen not only with appmetrica but any sdk that can occupy app and not let it finish.
I hope it's clear :)

**Comment by Zhuinden** [comment] 2017-01-26 10:17
@dimmduh this is a breakthrough @cmelchior @kneth

**Comment by dimmduh** [comment] 2017-01-26 10:34
Ohh... my mistake ... I put all my init code (realm, configs, etc) in MyApplication onCreate method, but the problem was I did not know appmetrica sdk works in details. Appmetrica sdk creates multiple application instances (to send crash logs even main app was crashed) that's why realm init was called twice.

**Comment by biftekman** [comment] 2017-01-26 10:43
I've been experiencing this issue for the last 4 months or so :)
However, ever since I moved realm init out of application's onCreate method, number of crashes dropped to insignificant numbers. Yet they still appear.

**Comment by stargt** [comment] 2017-04-27 02:08
Fundamentally, This problem can be solved by Encrypted interprocess sharing support.
I am seriously expecting it to be fixed by an official update ASAP.

**Comment by gelbertgel** [comment] 2017-09-13 14:12
I have same issue. 
My realm version: 3.3.2. 
Phone model: GM Discovery 
Android sdk: 4.4.2

Please help me :(

 ```
 io.realm.exceptions.RealmError: Unrecoverable error. /data/data/ com.a.android/files/e_r.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 12453. Current pid is 9111. in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 238
                                                     at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                     at io.realm.internal.SharedRealm.<init>(Unknown Source)
                                                     at io.realm.internal.SharedRealm.a(Unknown Source)
                                                     at io.realm.internal.SharedRealm.a(Unknown Source)
                                                     at io.realm.bg.b(Unknown Source)
                                                     at io.realm.bg.a(Unknown Source)
                                                     at io.realm.bf.m(Unknown Source)
                                                     at com.a.android.dao.a.a(Unknown Source)
                                                     at com.a.android.MyApplication.e(Unknown Source)
                                                     at com.a.android.v.e.t.a(Unknown Source)
                                                     at com.a.android.v.e.t.onCreate(Unknown Source)
                                                     at com.a.android.util.a.a.onCreate(Unknown Source)
                                                     at android.app.Activity.performCreate(Activity.java:5264)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
                                                     at android.os.Handler.dispatchMessage(Handler.java:110)
                                                     at android.os.Looper.loop(Looper.java:193)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5307)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:831)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
                                                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Zhuinden** [comment] 2017-09-13 14:20
@gelbertgel it most likely means that you are opening an encrypted Realm in two different processes by trying to read from a Realm instance in `Application.onCreate()`.

**Comment by gelbertgel** [comment] 2017-09-13 14:29
there is no problem like that. 
 google-services version is updated 3.0.0 to 3.1.0 and compile play-services version is 9.0.0 to 11.2.0

New versions:
classpath 'com.google.gms:google-services:3.1.0'
compile 'com.google.android.gms:play-services:11.2.0'
compile 'com.google.firebase:firebase-messaging:11.2.0'

**Comment by gelbertgel** [comment] 2017-09-14 11:11
I have restarted my phone and fixed it. Thanks..

**Comment by kuno** [comment] 2018-01-27 10:03
Shame on me, I made a mistake move my `getDefaultInstance()` method into Application's onCreate callback ... ...

**Comment by Zhuinden** [comment] 2018-01-27 14:19
@kuno actually we seem to have permission troubles on the Huawei P8 even when it's in `Activity.onCreate()`. The only tricky thing is that a broadcast receiver also tries to access Realm, and at least one of them seems to fail?

**Comment by byrneciaran** [comment] 2018-03-13 11:42
I have this issue, and I am opening an encrypted Realm in two different processes. I have implemented a SyncAdapter, and the idea is that the app performs background syncs in response to data changes, server notifications, etc. The SyncAdapter kicks off a separate process to handle this. Meanwhile, the user is working away in the app oblivious to this.

Just to clarify - is this scenario not supported with encrypted realms?

**Comment by cmelchior** [comment] 2018-04-05 08:38
Hi @byrneciaran 
Sorry for the late response. Encrypted Realms are currently not supported across multiple processes, only normal Realms.

**Comment by deathstroke007** [comment] 2018-11-29 23:01
@Zhuinden @cmelchior So, is there any workaround for this or the issue gets resolved in 5.8.0? This error has been reported once since I upload my application on play store which is around 2 months back. My daily active user is around 50 - 80 right now. I am initializing the Realm in Application's **oncreate** like this -

```
Realm.init(App.this);
                RealmConfiguration config = new RealmConfiguration.Builder()
                        .encryptionKey(REALM_KEY.getBytes())
                        .schemaVersion(0)
                        .deleteRealmIfMigrationNeeded()
                        .build();
                Realm.setDefaultConfiguration(config);
                Realm.getInstance(config);
```
And using **getDefaultInstance()** wherever i need it throughout the application.

Do I need to change anything? I am not able to reproduce it.

**Comment by luispereira** [comment] 2019-02-06 09:39
I'm able to reproduce this issue 100% of the time when I import LeakCanary in my project

**Comment by Zhuinden** [comment] 2019-02-06 11:49
You should early-return in the analyzer process as per the documentation of Leakcanary and not open a Realm in the analyzer process.

**Comment by gsantoscarrot** [comment] 2019-04-03 19:33
I am having this issue too, but always at the first time when I update my App, so when I opened again, everything works fine, I have no idea why

**Comment by tfkci** [comment] 2019-12-18 07:29
Fatal Exception: io.realm.exceptions.RealmError
Unrecoverable error. /data/data//files/default.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 13446. Current pid is 18022. in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

For my case, the crash is only seen in some Samsung S9 , S10 and S10+ devices. I am not creating a different process. It maybe caused by third party library or system libraries.  I saw crash report in Crashlytics and it is very rare. Couldn't reproduce and localize problem.

**Comment by kneth** [comment] 2019-12-18 08:48
@tfkci v6.0.1 has a fix of a race condition related to encryption, so if you are using an older version, please consider to upgrade.

**Comment by tfkci** [comment] 2019-12-18 18:48
Sorry I forgot to write the version. I use v6.0.2 . it should also has a fix I think.

**Comment by 09ae9c** [comment] 2019-12-27 02:57
Hi,

Realm Version: 6.0.1, Still crash...

```
 Unrecoverable error. /data/data/***/files/YUc5eVkzSjFlRjluYkc5aVlXeGZjbVZoYkcwPQ==.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 22164. Current pid is 1009. in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
```

**Comment by tfkci** [comment] 2020-01-24 09:57
After update have this issue for a while. But can't reproduce (v6.0.2)

**Comment by strooooke** [comment] 2020-02-18 08:28
Issue is still ongoing with v6.1.0:
```
Unrecoverable error. /data/data/****/files/default.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 8814. Current pid is 1216. in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
```
Occurs repeatedly (on subsequent app starts) for the same user (but several users are impacted).
Cannot reproduce locally - just seeing the crash reports.

Might be interesting: I have subsequent reports (that may very well belong to the same user), where the "opened by pid" stays constant, and the "current pid" changes.

**Comment by Myk-da-Beast** [comment] 2020-02-18 22:50
I see some users recommend moving `Realm.init(context)` out of `Application.onCreate()`, but where is the recommended initialization location in that case?

**Comment by Zhuinden** [comment] 2020-02-18 23:11
Don't move `Realm.init(context)` out of `Application.onCreate()`, but you can move `Realm.getDefaultInstance()` out of `Application.onCreate()`.

**Comment by Myk-da-Beast** [comment] 2020-02-19 17:18
Thanks for the clarification. I don't have `Realm.getDefaultInstance()` in `Application.onCreate()` though, and I still get this problem. I suppose it has not yet been fixed?

**Comment by Myk-da-Beast** [comment] 2020-02-19 17:25
Does `Realm.setDefaultConfiguration()` cause the same issue that `Realm.getDefaultInstance()` does?

**Comment by Zhuinden** [comment] 2020-02-19 17:34
Not that I know of 🤔

**Comment by vangivang** [comment] 2020-04-07 09:41
I am seeing the same issue.
Realm version: 6.0.2

I too cannot reproduce this on my current devices. But Crashlytics indicate these happens on Samsung A20s and I just got it now. So I will attempt to update the application that crashes in a couple of ways. Perhaps it will reproduce.

Any way, in Application onCreate() I init Realm with Realm.init(). Which as mentioned here is fine.
You also mentioned not to call Realm.getDefaultInstance() in onCreate() and I think we do call it.
We are checking if there is an old unencrypted Realm file and if there is, we copy it to an encrypted file and delete the old file.
Here is the code that does this:

First I call this in Application onCreate():

```
public void buildDatabase(){
        Realm.init(this);
        RealmConfiguration.Builder tempConfig = new RealmConfiguration.Builder()
                .schemaVersion(AppRealmMigration.CURRENT_VERSION)
                .migration(new AppRealmMigration())
                .modules(new RealmAsimovCoreModule(), new RealmAsimovProtocolV5Module(), new RealmAsimov());

        RealmConfiguration encryptedConfig = RealmUtils.get().getEncryptedInstance(tempConfig, "default.realm");
        Realm.setDefaultConfiguration(encryptedConfig);
        Realm.compactRealm(encryptedConfig);
    }
```

And here is RealmUtils.get().getEncryptedInstance:
```
public RealmConfiguration getEncryptedInstance(RealmConfiguration.Builder realmConfiguration, String unencryptedFileName){

        RealmConfiguration oldConfig = realmConfiguration.build();

        String encryptedFileName = encryptedFileName(unencryptedFileName);
        realmConfiguration.name(encryptedFileName);
        realmConfiguration.encryptionKey(realmEncryptionKey);
        RealmConfiguration newConfig = realmConfiguration.build();

        File newRealmFile = new File(newConfig.getPath());
        if (newRealmFile.exists()) {
            Realm.deleteRealm(oldConfig);
            return newConfig;
        } else {
            try (Realm realm = Realm.getInstance(oldConfig)) {
                // Migrate old Realm and delete old
                realm.writeEncryptedCopyTo(newRealmFile, realmEncryptionKey);

                realm.close();
                Realm.deleteRealm(oldConfig);
                return newConfig;
            } catch (Exception e) {
                Logger.log("RealmUtils", "Failed to create encrypted realm (with key: " + realmEncryptionKey + ") with exception: " + e.getMessage(), Logger.FILE_ONLY);
                return newConfig;
            }
        }
    } 
```

I suspect Realm.getInstance(oldConfig) is like Realm.getDefaultInstance ?

Could this be the issue? 

Thank you

**Comment by vangivang** [comment] 2020-04-16 11:52
Could calling Realm.compactRealm() during Realm init cause this issue? I am calling that during Application onCreate(). I'll try to change it to compactOnLaunch() in the RealmConfiguration builder.

**Comment by prettyClouds** [comment] 2020-09-30 20:30
To sum up this thread:

1) You can't access an encrypted Realm from two different processes, so if you are doing that on purpose, one of the processes will crash.

2) It looks like when Android updates, the old APK can still be running when the new one starts up. If the new process tries to access an encrypted Realm while the old one still has an instance, the new one crashes.

What I can't seem to find is any recommendation on how to minimize this issue. One that comes to mind is to minimize the amount of time between when a process calls `Realm.getDefaultInstance()` and `Realm.close()`. Patterns like getting a Realm everytime and Activity is created and closing it when it's destroyed will probably exacerbate this problem.  Is there anything I am missing?  Is there a better way to solve this?  
@beeender @kneth

**Comment by Zhuinden** [comment] 2020-10-19 17:28
I hear what can help is checking in a BaseActivity if `applicationContext` is your custom application class, if it is not, then just don't initialize anything.

**Comment by volo-droid** [comment] 2020-11-14 21:32
> Occurs repeatedly (on subsequent app starts) for the same user (but several users are impacted).
> Cannot reproduce locally - just seeing the crash reports.
> 
> Might be interesting: I have subsequent reports (that may very well belong to the same user), where the "opened by pid" stays constant, and the "current pid" changes.

We're observing exactly the same in our project. Most of the issues are coming from Samsung S10+, on that device we had a spike of 286 crashes affecting 4 users within 4 days. For example, there're more than 70 crashes with the same opened pid 20925:

Time| PIDs
---|---
12 Nov 2020, 17:27:00|opened by pid: 20925. Current pid is 14901.
12 Nov 2020, 16:26:45|opened by pid: 20925. Current pid is 6094.
12 Nov 2020, 13:26:43|opened by pid: 20925. Current pid is 25312.
12 Nov 2020, 12:40:46|opened by pid: 20925. Current pid is 6122.
12 Nov 2020, 10:25:49|opened by pid: 20925. Current pid is 21103.
12 Nov 2020, 10:11:48|opened by pid: 20925. Current pid is 17393.
12 Nov 2020, 08:22:05|opened by pid: 20925. Current pid is 15637.
12 Nov 2020, 08:22:00|opened by pid: 20925. Current pid is 15398.
12 Nov 2020, 07:21:26|opened by pid: 20925. Current pid is 11062.
12 Nov 2020, 07:21:22|opened by pid: 20925. Current pid is 10834.   
…|…

One question, would it be possible to include not only a PID but also a process name?

**Comment by Zhuinden** [comment] 2020-11-15 00:39
@volo-droid what is your Realm version, and what Realm version created the Realm file?

**Comment by volo-droid** [comment] 2020-11-16 00:28
@Zhuinden The current version is 7.0.2, but I'm not sure what version was used to create a Realm file. The whole Realm thing is encapsulated in an in-house SDK we use, I'd have to check with its maintainers. In the git blame I can see the following Realm versions 5.4.1 -> 6.1.0 -> 7.0.2

**Comment by andersfredlund** [comment] 2021-07-16 05:16
I also see this issue popping up when it is time to upgrade our app and it is mostly Galaxy S10+

**Comment by johnsabilla** [comment] 2021-08-20 18:29
We also experience this exception on v7.0.8

**Comment by vonox7** [comment] 2021-11-22 11:58
@volo-droid you can get the other processName via:
```
  private fun getProcessName(pid: Int): RunningAppProcessInfo? {
    val manager = App.instance.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
    return manager.runningAppProcesses.find { it.pid == pid }
  }

val otherPid = Regex("DB has been opened by pid: ([\\d]+)").find(exception.message!!)!!.groups[1]!!.value.toInt()
getProcessName(otherPid)?.processName
```

Note that this issue might happen not only during app-upgrade, but also when your app has a Worker do to some background work.

**Comment by cmelchior** [comment] 2023-04-01 08:30
Fixed by https://github.com/realm/realm-java/pull/7795

**Closed by cmelchior** 2023-04-01 08:30 UTC
Labels: T-Bug-Crash, O-Community
