### ISSUE TITLE
The promise that Realm works for Android API since 9 has been broken

### ISSUE THREAD

**Issue by Kcorab** [realm/realm-java#3455] opened 2016-09-18 16:10 UTC
> ### Prerequisites
> - We do not support Java outside of Android at the moment.
> - Android Studio >= 1.5.1
> - A recent version of the Android SDK.
> - JDK version >=7.
> - _We support all Android versions since API Level 9 (Android 2.3 Gingerbread & above)._

Source: https://realm.io/docs/java/latest/#getting-help

Inside the class `Realm` instances of `JsonReader` are used that require API 11 at minimum.

**Comment by Zhuinden** [comment] 2016-09-18 17:08
Actually, the library should work perfectly well, apart from the JSON import API when used directly against InputStream. 

It's actually specified right [here](https://github.com/realm/realm-java/pull/489)  and expected.

**Comment by zaki50** [comment] 2016-09-18 17:30
@Kcorab As @Zhuinden said, this is actually an intended behavior.
This should be mentioned in API reference and I made a PR to fix this (#3456).

**Comment by zaki50** [comment] 2016-09-19 06:03
I've updated Javadoc and it will be included in next release.

**Closed by zaki50** 2016-09-19 06:03 UTC
Labels: S:Review, T:Doc
