### ISSUE TITLE
Remove primary key, index is not removed.

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2944] opened 2016-06-07 02:27 UTC
This is reported on SO http://stackoverflow.com/questions/37667205/primary-key-migration-with-realm-1-0

----

I'm trying to perform a migration in Realm that migrates the primary key, and I'm getting the following error:

    Index not defined for field 'local_id' in existing Realm file. Either set @Index or migrate using io.realm.internal.Table.removeSearchIndex().

Here's my migration code:

```java
    schema.get("Calendar")
                    .addField("local_id", String.class)
                    .transform(new RealmObjectSchema.Function() {
                        @Override
                        public void apply(DynamicRealmObject obj) {
                            obj.set("local_id", obj.getString("id") + obj.getString("start"));
                        }
                    })
                    .removePrimaryKey()
                    .addPrimaryKey("local_id");
```

I don't see what else I need to do. I've added `@Index` on the `local_id` field, and it didn't make a difference. Anyone know what I need to do?

**Comment by heatherSnepenger** [comment] 2016-06-07 12:32
@stk1m1 thanks for looking into this. Is there a good way to migrate the primary key? Some way I can work around this bug?

**Comment by stk1m1** [comment] 2016-06-07 12:42
@heatherSnepenger 

Sorry for your trouble and, in fact, we just start looking into your issue. Realm isn't supposed to behave this way due to recent fixes. Actually, there is one thing you can help us. Could send us a sample project we can use to reproduce your issue? It would be great if you can send us the problematic database file as well to help@realm.io. 

We'll look forward.

**Comment by heatherSnepenger** [comment] 2016-06-07 13:05
@stk1m1 thanks. I'm going try to make a sample project that reproduces the issue. I cannot share the current project I'm working on that has the issue.

**Comment by stk1m1** [comment] 2016-06-07 13:52
@heatherSnepenger We'd be happy to have a bare-bone project just with models that caused the issue. We'll look forward. ;)

**Comment by heatherSnepenger** [comment] 2016-06-07 20:00
@stk1m1 I think I solved it after all. Didn't notice that my working branch was using version 0.90.0. I'm doing more testing, but I think I'm good

**Comment by stk1m1** [comment] 2016-06-07 20:43
@heatherSnepenger Great to hear that. I'm closing the issue now.

**Closed** 2016-06-07 20:42 UTC
Labels: S:P1 Backlog, T:Bug
