### ISSUE TITLE
Realm object wont 'Re-Open'

### ISSUE THREAD

**Issue by xbroak** [realm/realm-java#2246] opened 2016-02-07 12:57 UTC
Realm realm = Realm.getDefaultInstance();
 in onCreate

realm.close();
 in on Destroy

as per the best practices, however, when opening a new activity (A detail view for a list item) the onDestroy is called on the parent activity closing the Realm, fine. Upon closing the new child activity, onCreate is again called for the parent activity where we would now assume that Realm will "Re-Open" thanks to calling getDefaultInstance() and i can carry on as before. However the realm object seems to be permanently closed. No matter how many times i get a new Realm instance, it is always reported as closed.

What's going on?

**Comment by cmelchior** [comment] 2016-02-08 08:38
The lifecycle calls `onCreate` and `onDestroy` should overlap:

```
ActivityA:onCreate()
ActivityB:onCreate()
ActivityA:onDestroy();
ActivityB:onDestroy();
```

Which means that the Realm instance should be kept alive. Can you share the running code or a small sample project with this behaviour?

**Comment by xbroak** [comment] 2016-02-08 10:26
Realm realm;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_urllist);

        toolbar = (Toolbar) findViewById(R.id.tool_bar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        realm = Realm.getDefaultInstance();

    }

    @Override
    protected void onDestroy() {
        realm.close();
        Log.i(TAG, "OnDestroy Called");
        super.onDestroy();
    }

Here you go! That's all the code i have, two plain activities, both using the above code. Opening the next activity, works great, it can use it's own instance of Realm, closing the new activity and returning to the original activity leaves me with an already closed realm despite onCreate being called again. Thanks!

**Comment by cmelchior** [comment] 2016-02-08 10:30
I think the problem is that you are calling `realm.close()` before calling `super.onDestroy()`. We have seen in other cases that `onDestroy` is triggering re-layouts which might read RealmObjects.

**Comment by xbroak** [comment] 2016-02-08 10:37
Oh really? I hope it ends up being that simple! Just for what it's worth, my only realm access is a single call in an OnClick with:

    if(!realm.isClosed){
        Toast...
    }

**Comment by xbroak** [comment] 2016-02-08 11:24
Damn, nope, same issue. It does not even happen every time! Perhaps if i open and close the child activity a couple of times in a row, or seemingly at random

**Comment by xbroak** [comment] 2016-02-08 11:25
if(realm == null || realm.isClosed()) {
            realm = Realm.getDefaultInstance();
    }

I've even tried just having this right before the isClosed() check, still nothing

**Comment by kneth** [comment] 2016-02-10 09:55
@xbroak Can you share your code with us? If you wish to share it privately, just email help@realm.io.

**Comment by xbroak** [comment] 2016-02-12 16:52
Hi @kneth ,

You should be able to just make a new project, with two activities, copy the code above into each of them and replicate the problem. That's currently my project!

Thanks!

**Comment by nhachicha** [comment] 2016-02-15 14:19
Hi @xbroak 
I created a sample project with your 2 Activities https://github.com/nhachicha/SupportSandbox
couldn't reproduce your issue. 

Closing is based on reference counting (if you have 2 Realm _open_ you need 2 calls to _close_ to really free the resource & close the Realm)
Even if the Activity lifecycle of the 2 Activities overlaps (_onCreate_ of Activity 2 is called before _onDestroy_ of the first Activity) there is no concurrency issue, since they're both run inside the main looper sequentially. 

Please let me know If you can reproduce the issue using the provided code
Cheers,

**Comment by cmelchior** [comment] 2016-03-07 10:54
Closing this due to no response and we cannot reproduce the reported problem.

**Closed by cmelchior** 2016-03-07 10:54 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help
