### ISSUE TITLE
RealmChangeListener onChange() method is not triggered

### ISSUE THREAD

**Issue by zmcode** [realm/realm-java#2569] opened 2016-04-07 19:03 UTC
#### Goal

In Android, I am trying to update different views - such as `ViewHolder` in `RecyclerView` and a bunch of other custom views - that contain different instances of the logically-same object using a `RealmChangeListener`.

This is the object class:
```java
public class Post extends RealmObject {
    ...
}
```
I am currently using the [FastAdapter](https://github.com/mikepenz/FastAdapter) library so I have this `PostItem` class which is basically the item that is going to be stored inside the adapter and provides the logic to bind to a `ViewHolder`:
```java
public class PostItem extends AbstractItem<PostItem, PostItem.ViewHolder> {
    private Post mPost;
    private RealmChangeListener mRealmChangeListener;
    ...
    public PostItem withPost(Post post) {
        mPost = post;
        mRealmChangeListener = new RealmChangeListener() {
            @Override
            public void onChange() {
                // here I call a custom listener which should then update the Recycler 
                // of which it is responsible - something like:
                // myCustomListener.onRealmChange(PostItem.this, mPost)
            }
        };
        mPost.removeChangeListeners();
        mPost.addChangeListener(mRealmChangeListener);
    }
    ...
}
```
The user can then make some action such as liking or saving the post. Each time I am making a request to the server and upon success I take the object coming back in the responde and update it in the database in this way:
```java
public class LikePostTask extends AsyncTask<Void, Void, Post> {
    ...
    @Override
    protected void onPostExecute(Post post) {
        DomainController.getInstance().save(post);
    }
}

public class DomainController {
    ...
    public <T extends RealmObject> T save(final T object) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        T realmObject = realm.copyToRealmOrUpdate(object);
        realm.commitTransaction();
        return realmObject;
    }
}
```

#### Expected Results

If I understand it correctly after the `save()` method is executed the `onChange()` method of the `RealmChangeListener` should be called upon the next iteration of the run loop on the UI thread.

#### Actual Results

However the `onChange()` method is not triggered. I tried putting a breakpoint inside it and it's never reached. 

The thing is the objects instances inside the `PostItem` objects are updated. After scrolling to force a rebind of the `ViewHolder` the UI is updated with the right information but again whatever I put inside the `onChange()` method is never executed.

#### Version of Realm and tooling
Realm version(s): 0.88.2

Android Studio version: 2.1 preview 5

Which Android version and device: 6.0.1 on a Galaxy S6

**Comment by beeender** [comment] 2016-04-08 03:21
Is there any possibility that your `PostItem` gets GCed? If `PostItem.mPost` gets GCed, the listener will be removed automatically.

and
``
mPost.removeChangeListeners();`
``

Do multiple `PostItem` share the same `mPost` reference?

**Comment by zmcode** [comment] 2016-04-08 07:13
This is how I load the `PostItem` into the adapter:
```java
public class PostsFragment extends Fragment {
    private FastItemAdapter<PostItem> myAdapter;
    ...
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        ...
        myAdapter = new FastItemAdapter<>();
        ...
        new GetPostsTask().execute();
        ...
    }

    class GetPostsTask extends AsyncTask<Void, Void, List<Posts>> {
        ...
        @Override
        public void onPostExecute(List<Post> posts) {
            // the posts list here is made up by objects that are detached from the realm
            // beacause it is the result of parsing the server response
            List<PostItem> items = new ArrayList<>(posts.size());
            final DomainController domainController = DomainController.getInstance();
            for (Post post : posts) {
               Post realmPost = domainController.save(post);
               items.add(new PostItem().withPost(realmPost));
            }
            myAdapter.set(items); // here I set the items inside the adapter
        }    
    }
}
```
To answer your questions: 

1. I load the posts inside the `onCreateView()` method so they should stay alive inside the adapter as long as the fragment does.

2. Each `PostItem` is created with a `Post` returned by the `save()` method of my `DomainController` singleton which as you can see above is what the `realm.copyToRealmOrUpdate()` returns. Moreover:
    - there are not duplicated posts in the list I get from the server;
    - each post has a unique ID that I use as primary key in realm. 

    So unless I am missing something each `PostItem` should get an unique reference to its post.

**Comment by beeender** [comment] 2016-04-11 08:04
When you create the `RealmObject` in the `DomainController.save()`, a Realm instance is created and closed in the method as well. That also means the object returned from the function becomes invalid because of the corresponding Realm instance gets closed. So the suggestion is passing a Realm instance to the `save()` function as well and keep it opened until you don't need those RealmObjects related Realm instance anymore.

**Comment by zmcode** [comment] 2016-04-11 08:51
Then why if I log the `valid` property of the `Post` in another method of the `PostItem` it appears to be `true`?

```java
public class PostItem extends AbstractItem<PostItem, PostItem.ViewHolder> {
    ...
    @Override
    public void onLikeButtonClick(...) {
        if (BuildConfig.DEBUG) Log.d(sLogTag, String.format("Post is valid: %s", mPost.isValid())); 
        // the log above says it is true
        ...
    }
}
```
Moreover, the `Post` object inside the `PostItem` is actually updated, because if I force a rebinding of the `ViewHolder` scrolling up and down everything is fine.

However I will try keeping a global reference to the `Realm` instance inside my singleton in order to avoid getting it closed. Is this a good idea or do I need to pass it each time to the `save()` method?

**Comment by zmcode** [comment] 2016-04-11 14:58
Ok I tried with a `Realm` instance inside my `DomainController` singleton. And it has partially worked. 

The thing is I have `PostItem` in two `Recycler` that are in two adjacent fragments inside a `ViewPager`.
After adding the global `Realm` instance the `onChange()` method is triggered inside the `PostItem` of one of the fragment but not in the other.

I have also tried to remove the line in which I remove all the listeners bound to the `Post` (`mPost.removeChangeListeners();`) but still it does not call both the listeners.

**Comment by beeender** [comment] 2016-04-12 07:31
@zmcode More details about the Realm instance. We are managing Realm instances based on reference counter internally for the same thread. It makes you get the same instance if you have one already in the that thread. This also means you will need to close the Realm instance twice if you opened it twice to "really" close the Realm. I guess this is the reason why "it has partially worked. "

Maybe this could give you some inspiration about this https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

**Comment by zmcode** [comment] 2016-04-12 07:56
This is my singleton:
```java
public class DomainController {
    private static final String sLogTag = DomainController.class.getSimpleName();
    private static final String sNullContextExceptionMsg = "Cannot complete initialization with a null context";
    private static DomainController ourInstance;
    private final Realm realm;

    private DomainController(Context context) {
        if (context == null) throw new NullPointerException(sNullContextExceptionMsg);
        RealmConfiguration config = new RealmConfiguration.Builder(context)
                .schemaVersion(1)
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(config);
        realm = Realm.getDefaultInstance();
        if (BuildConfig.DEBUG) Log.i(sLogTag, "Initialization completed");
    }

    public static DomainController getInstance(Context context) {
        if (ourInstance == null) ourInstance = new DomainController(context);
        return ourInstance;
    }

    public <T extends RealmObject> T save(final T object) {
        realm.beginTransaction();
        T realmObject = realm.copyToRealmOrUpdate(object);
        realm.commitTransaction();
        return realmObject;
    }

    public <T extends RealmObject> Collection<T> save(final Collection<T> objects) {
        realm.beginTransaction();
        Collection<T> realmObjects = realm.copyToRealmOrUpdate(objects);
        realm.commitTransaction();
        return realmObjects;
    }

    public <T extends RealmObject> void delete(final Class<T> objectsClass) {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.clear(objectsClass);
            }
        });
    }

    public <T extends RealmObject> void delete(final T object) {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                object.removeFromRealm();
            }
        });
    }

    public <T extends RealmObject> T getDetachedCopy(final T object) {
        return realm.copyFromRealm(object);
    }
}
```
I was trying to follow the google developers guidelines [about extending the `Application` class](http://developer.android.com/reference/android/app/Application.html):

> There is normally no need to subclass Application. In most situation, static singletons can provide the same functionality in a more modular way. If your singleton needs a global context (for example to register broadcast receivers), the function to retrieve it can be given a Context which internally uses Context.getApplicationContext() when first constructing the singleton.

Is it a feasible solution or I really need to get a `Realm` instance inside all of my fragments and activities?

**Comment by beeender** [comment] 2016-04-14 07:51
I think it is OK to do it like that as long as you only access the `DomainController` on the same thread. Are you going to expose `DomainController.realm` as `DomainController.getRealm()` to use other Realm's convenient methods?

**Comment by zmcode** [comment] 2016-04-14 14:55
Ok I had imagined threads would have been a limitation even if I must say that I tried using the `save()` method inside the `doInBackground()` of an `AsyncTask` and it did not throw any exceptions, is it normal?!

Actually I am not planning to expose the `DomainController.realm` for now.

However I had to tell you that the `RealmChangeListener` are not called yet. Is there anything else I can try?

**Comment by beeender** [comment] 2016-04-15 07:37
It depends. Now the static Realm instance will be created in the thread where the `DomainController` initiated the first time. So, if the first time it is called is in the AsyncTask's `doInBackground()`, i can imagine it won't throw exception in the same AsyncTask. But if that is not case, then something is going wrong.

Personally I would like to control the Realm's life cycle in the activity/fragment/service since that would be clear to see which thread they get created, less chance to make mistake.

**Comment by zmcode** [comment] 2016-04-15 08:45
> It depends. Now the static Realm instance will be created in the thread where the DomainController initiated the first time. So, if the first time it is called is in the AsyncTask's doInBackground(), i can imagine it won't throw exception in the same AsyncTask. But if that is not case, then something is going wrong.

The `DomainController` is initialized in the UI thread but I tried it again and it correctly threw an exception now. I am sorry  but I think that the first time I tried it the 'instant run' feature of android studio may have not actually loaded the new lines of code.

Anyway, assuming that I only use the `DomainController` inside the UI thread, which is actually the case, why would the listeners not be triggered yet?

**Comment by beeender** [comment] 2016-04-19 08:48
there are some possibilities:

1. The Realm instance gets closed, please notice that we are using reference counter which means if you close Realm twice in activity 2, the Realm instance in activity might be closed.
2. Listener has been removed.
3. There is no change has been made to the Realm, maybe to another Realm?

Without seeing the whole project, it is hard to see what the problem is. If you can share a sample project to reproduce the issue, that would be really helpful.

**Comment by kneth** [comment] 2016-05-02 12:55
@zmcode Did you have a chance to create a small example project which can reproduce the issue?

**Comment by zmcode** [comment] 2016-05-02 15:59
Ok here is a sample project that I created:
https://github.com/zmcode/RealmChangeListenerTest

It contains two tabs, each one with a recycler containing a single item. When you click on the item it should update the item name with a random number and then update the `ViewHolder` in both tabs using the `RealmChangeListener`. However I am not able to make it work :(.

**Comment by beeender** [comment] 2016-05-03 07:22
Thanks a lot for the project!
It is a bug that `copyToRealmOrUpdate` doesn't call `HanlderController.addToRealmObjects()` (when update?)
https://github.com/realm/realm-java/issues/2686#issuecomment-215298614 also needs to be considered when fix this.

We will fix this ASAP. Sorry for the inconvenience.

**Comment by zmcode** [comment] 2016-05-03 08:31
I am glad I was able to help you figuring that out :)

**Closed** 2016-05-03 13:47 UTC
Labels: S:In Progress
