### ISSUE TITLE
Feature Request: Lists / Arrays with simple types and strings

### ISSUE THREAD

**Issue by RobertoArtiles** [realm/realm-java#999] opened 2015-03-30 20:45 UTC
Hi guys,

Might be a duplicate, but I couldn't find a similar issue.
Would be really great to have a such feature.

**Comment by emanuelez** [comment] 2015-03-30 21:05
Yes, it is a duplicate of #575. Please refer to it for updates.

**Closed by emanuelez** 2015-03-30 21:05 UTC

**Comment by RobertoArtiles** [comment] 2015-03-30 21:13
Thanks.
