### ISSUE TITLE
Can't commit a non-existing write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 260

### ISSUE THREAD

**Issue by mengyaCS** [realm/realm-java#4789] opened 2017-06-15 05:56 UTC
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by mengyaCS** [comment] 2017-06-15 05:56
Can't commit a non-existing write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 260

**Comment by bmeike** [comment] 2017-06-15 06:26
Why not?  Cut us a break here?

Could you please fill out the template with a couple of bits of important information: the version of Realm you are using, whether sync is enabled, the Android device and version on which the problem occurs?  Any suggestions about how to reproduce the issue.

This information will give us a much better chance of finding and fixing the problem.

**Comment by Zhuinden** [comment] 2017-06-15 07:54
@mengyaCS well it says you are calling `realm.commitTransaction()` without calling `realm.beginTransaction()`.

**Comment by kneth** [comment] 2017-06-26 07:25
I am closing the issue with the hope that @mengyaCS figured out what is wrong.

**Closed by kneth** 2017-06-26 07:25 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help

**Comment by engr-erum** [comment] 2018-07-20 05:04
@Zhuinden i m doing this https://pastebin.com/WLHzpZHr but still getting error

**Comment by Zhuinden** [comment] 2018-07-20 09:28
@engr-erum well that exception says you cannot call `realm.cancelTransaction` if there is no actual transaction in progress. I could say you can use `realm.isInTransaction` to check if you're in a transaction, but generally you shouldn't randomly cancel transactions just because you aren't sure when you're running them in your code.

**Comment by ashukhurana90** [comment] 2018-09-04 15:34
Exception has been thrown: Can't commit a non-existing write transaction in /Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 144
E/AndroidRuntime: FATAL EXCEPTION: main

**Comment by zainForAndro** [comment] 2020-02-19 06:31
you need to call realm.beginTransaction() before calling realm.commitTransaction(). If you are using realm.executeTransaction{ } then don't call realm.commitTransaction() to avoid exception.
