### ISSUE TITLE
Investigate connection between BadVersionException and calling load() on async query results 

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#4097] opened 2017-01-24 08:21 UTC
Ported hypothesis from http://stackoverflow.com/questions/41804318/realmchangelistener-does-not-execute-when-added-shortly-after-asynchronous-write?noredirect=1#comment70833516_41804318

Realm version: 2.3.0

**Comment by ppamorim** [comment] 2017-01-24 10:11
It is a know issue. Should be fixed on: https://github.com/realm/realm-java/pull/3834

**Comment by kneth** [comment] 2017-01-26 09:21
The SO user is claiming he got it to work.

**Comment by benj56** [comment] 2017-01-26 14:23
@kneth 
I think this is a misunderstanding, I did not get it to work, it is just working more reliable depending on delays between the write and the queries, which is not really a solution.

I believe there might be a problem involving the "caller thread is behind the worker thread" case in the HandlerController.java. 

Anyway, maybe the root cause of the problem that leads to my ChangeListener not triggering is what causes the BadVersionException (and sometimes SEGFAULT instead)  when calling load() on these Results.

**Comment by benj56** [comment] 2017-01-27 10:42
@cmelchior @kneth 
Would it make sense to open this again or could I create a new issue?

**Comment by cmelchior** [comment] 2017-01-27 10:47
@benj56 I re-opened this issue

**Comment by kneth** [comment] 2017-01-28 08:06
@benj56 I hope that we have a snapshot release including #3834 soon.

**Comment by benj56** [comment] 2017-02-06 07:57
@kneth Would very much appreciate it. I've been looking at #3834 every few days, but can't really tell the progress. Do you think a snapshot is ready within one-two weeks? Thanks!

**Comment by kneth** [comment] 2017-02-06 09:54
@benj56 #3834 is a big PR so reviewing it to a state where we can merge it, is taking longer than expected. I do hope that it is merged within two weeks from now!

**Comment by cmelchior** [comment] 2017-03-20 10:56
@benj56 Can you reproduce this with Realm Java 3.0.0, that should contain a fix for this?

**Comment by benj56** [comment] 2017-03-20 12:05
@cmelchior It is fixed, thanks.

**Closed** 2017-03-20 12:05 UTC
Labels: T:Help
