### ISSUE TITLE
./gradlew androidJar build error

### ISSUE THREAD

**Issue by chonamdoo** [realm/realm-java#1128] opened 2015-05-16 04:28 UTC
window build 

![12313](https://cloud.githubusercontent.com/assets/6761814/7668681/b515aab8-fc80-11e4-95f5-bafa677b6b52.png)

i add realm-jni 
   "--system=windows-x86_64",

toolchains.each { toolchain ->
    task "generateNdkToolchain${toolchain.name.capitalize()}"(type: Exec) {
        group 'build setup'
        description "Generate the NDK standalone toolchain for the ${toolchain.name.capitalize()} platform"
        dependsOn { checkProperties }
        outputs.dir new File("${buildDir}/standalone-toolchains/${toolchain.name}")
        commandLine = [
            "bash",
            "${project.ext['ndk.dir']}/build/tools/make-standalone-toolchain.sh",
            "--system=windows-x86_64",
            "--platform=android-${toolchain.platform}",
            "--install-dir=${buildDir}/standalone-toolchains/${toolchain.name}",
            "--toolchain=${toolchain.fullName}-${clang?'clang'+toolchain.version[Compiler.CLANG]:toolchain.version[Compiler.GCC]}"
        ]
    }
}

![11111](https://cloud.githubusercontent.com/assets/6761814/7668714/4c6847bc-fc82-11e4-8e94-e4ef0d77bb66.png)

**Comment by kneth** [comment] 2015-05-18 08:06
We have an open issue on supporting Windows for building. See #911.

**Comment by cmelchior** [comment] 2015-05-18 18:07
Closing this as a duplicate of #911

**Closed by cmelchior** 2015-05-18 18:07 UTC
