### ISSUE TITLE
It will cause crashed in HUAWEI mobile phone...

### ISSUE THREAD

**Issue by yuanhoujun** [realm/realm-java#3892] opened 2016-12-10 07:04 UTC

**Comment by Zhuinden** [comment] 2016-12-10 08:22
Which Huawei mobile phone? By type

**Comment by yuanhoujun** [comment] 2016-12-11 00:28
Huawei mate8 , and another Huawei mobile phone is also crashed , but i forget its type .
It looks like it is crashed in all Huawei mobile phones

**Comment by diegomontoya** [comment] 2016-12-11 02:50
@yuanhoujun You need to submit 1) code 2) realm version used for this issue.

**Comment by Zhuinden** [comment] 2016-12-11 10:07
3.) stack trace if any

**Comment by yuanhoujun** [comment] 2016-12-12 07:56
12-12 15:55:50.983 2700-2700/me.foji.realmdbutils E/REALM_JNI: jni: ThrowingException 5, Operation not permitted in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92, .
12-12 15:55:50.983 2700-2700/me.foji.realmdbutils E/REALM_JNI: Exception has been throw: Unrecoverable error. Operation not permitted in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92

Device: Huawei plk-tl100

**Comment by yuanhoujun** [comment] 2016-12-12 07:57
Os version: EMUI 4.0.1 Android OS: 6.0,

**Comment by kneth** [comment] 2016-12-12 09:08
#3895 seems to be the same issue.

@yuanhoujun Can you provide a test case/sample project where we can reproduce the error?

**Comment by yuanhoujun** [comment] 2016-12-13 06:04
@kneth https://github.com/yuanhoujun/RealmHelper , try this sample in Huawei mate8 or other Huawei devices 。

**Comment by beeender** [comment] 2016-12-13 06:45
@yuanhoujun You sample project is creating Realm file on an external storage, it might be the same issue with #3629 which has been fixed in core & objectstore. We need do a java release.

**Comment by beeender** [comment] 2016-12-13 06:46
I will verify this on huawei device after fix released. So don't close this for now.

**Comment by yuanhoujun** [comment] 2016-12-13 09:58
Ok, i'm watting to fix this bug .

**Comment by beeender** [comment] 2016-12-14 13:46
@yuanhoujun 
1. You project has a problem with using `getExternalStorageDirectory()`. It won't work on recent Huawei phones since you will not have permission to write to the root of external storage. See https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory()
2. I can reproduce your issue "Operation not permitted" by changing the `getExternalStorageDirectory`  to `externalCacheDir` and using a sd-card with the phone.
3. I verified the issue will be solved by https://github.com/realm/realm-java/pull/3904 

Since it has the exact same root cause with #3629 , i will just close this one. Let me know if you still have the issue with our following release (`v2.2.2`)

**Closed by beeender** 2016-12-14 13:46 UTC
Labels: S:P1 Backlog, T:Bug-Crash

**Comment by yuanhoujun** [comment] 2016-12-16 04:21
Ok
