### ISSUE TITLE
examples.unittesting - ExampleRealmTest fails for dogRepo

### ISSUE THREAD

**Issue by behelit** [realm/realm-java#2190] opened 2016-01-28 22:11 UTC
Realm version: realm-java-0.87.3

In the unittesting example, in the ExampleRealmTest, in the shouldVerifyTransactionWasCreated test, the test fails because dog is null:
```
DogRepository dogRepo = new DogRepositoryImpl();
dogRepo.createDog("Spot");
```

This calls the following, in the DogRespistoryImpl class:
```
public class DogRepositoryImpl implements DogRepository {

    @Override
    public void createDog(String name) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        Dog dog = realm.createObject(Dog.class);
        dog.setName(name);
        realm.commitTransaction();
        realm.close();
    }
}
```
realm.createObject(Dog.class) returns null and causes the next line to crash.

The actual error:
```
java.lang.NullPointerException
	at io.realm.examples.unittesting.repository.DogRepositoryImpl.createDog(DogRepositoryImpl.java:29)
	at io.realm.examples.unittesting.ExampleRealmTest.shouldVerifyTransactionWasCreated(ExampleRealmTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1873)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:773)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:638)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:49)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```

**Comment by behelit** [comment] 2016-01-29 06:05
Seems like no unit tests work.
Steps to reproduce:
Android Studio 1.5.1
1. Download realm-java-0.87.3.zip
2. Extract
3. Open examples project using Android Studio
4. In the Android project view, expand unitTestExample, io.realm.examples.unittesting (androidTest)
5. Open jUnit3ExampleTest
Errors....

Cannot resolve onView
Cannot resolve wiwthText
Cannot resolve matches
Cannot resolve isDisplayed()

Same with jUnit4ExampleTest

**Comment by beeender** [comment] 2016-01-29 06:07
did you run `./gradlew installRealmJava` before open the example in AS?

**Comment by behelit** [comment] 2016-02-01 03:55
before open the example?

if you mean after, then this is what happens:

> FAILURE: Build failed with an exception.
>                               
> * What went wrong:            
> Task 'installRealmJava' not found in root project 'examples'.
>

**Comment by beeender** [comment] 2016-02-01 05:51
@behelit Run it from the root directory of realm ~

**Comment by kneth** [comment] 2016-02-05 17:01
@behelit Did you have success in running building the example?

**Comment by behelit** [comment] 2016-02-10 04:01
If I go up a directory and run the command specified, it returns:
'gradlew' is not recognized as an internal or external command,
operable program or batch file.

Please note, I use Windows..

**Comment by kneth** [comment] 2016-02-10 09:46
Building Realm on Windows isn't supported. But you should be able to import the examples into Android Studio.

**Comment by kneth** [comment] 2016-02-10 12:52
I have not been able to reproduce it on a Windows computer. My procedure was:

1. Downloaded the Realm zip file
2. Unzip the file
3. Launched Android Studio
4. Imported the root of the example
5. Launched an emulator
6. Ran the unittest examples
7. Observed the screen of the emulated device

**Comment by behelit** [comment] 2016-02-12 05:42
My scenario:
1. Downloaded realm-java-0.87.3.zip file
2. Extract file to new folder
3. Launch Android Studio

Using 'Open Existing Project'
4. Open an existing Android Studio Project->Select folder that files were extracted to
5. Android Studio informs 'Frameworks detected - ... Configure
6. Click configure, it selects default options, press ok
7. only java folder is shown in Android studio, cannot navigate to any other locations or the 'examples' source, unable to do anything

If I use "Import" like kneth implied, I don't know if you actually meant import or not...
4. Import project (Eclipse ADT, Gradle, etc.)
5. Choose folder of extracted files
6. Create project from existing sources
7. Specify Project name
8. Mark All source files for adding to project root
9. Review libraries found
10. review suggested module structure
11. Select project SDK
12. Finish

Multiple errors, IDE crash, migrate project to gradle, frameworks detected, and other unknown unexplained issues.

What am I doing that's different?

**Comment by cmelchior** [comment] 2016-02-22 12:03
Hi @behelit 
It sounds like there is something more fundemental wrong with your IDE in that case. Note that you shouldn't need to create a new project, because that sounds like it isn't working for you. Just selecting "File > Open" and point to the folder with the examples should be enough.

**Comment by cmelchior** [comment] 2016-03-01 09:23
This should have been fixed by https://github.com/realm/realm-java/pull/2320, please reopen if that is not the case.

**Closed by cmelchior** 2016-03-01 09:23 UTC
Labels: Reproduction Required, S:Waiting For User, T:Help
